- tubemq-core/src/main/java/com/tencent/tubemq/corebase/utils/TStringUtils.java
replace StringBuffer with StringBuilder in TStringUtils
> [TUBEMQ-27] replace StringBuffer with StringBuilder in TStringUtils

- .gitignore
Fix path error in gitignore.
From `tube-server/test/` to `tubemq-server/src/test/`
> [TUBEMQ-28] fix ignore path error

- tubemq-server/src/main/java/org/apache/tubemq/server/broker/msgstore/mem/MsgMemStore.java
Calling clear () in close () is not necessary, and it is easy to cause data disorder.
> [TUBEMQ-37] Offset is set to 0 when Broker goes offline

- tubemq-client/src/main/java/org/apache/tubemq/client/consumer/BaseMessageConsumer.java
- tubemq-client/src/main/java/org/apache/tubemq/client/consumer/ClientSubInfo.java
- tubemq-client/src/main/java/org/apache/tubemq/client/consumer/ConsumerResult.java
- tubemq-client/src/main/java/org/apache/tubemq/client/consumer/FetchContext.java
- tubemq-client/src/main/java/org/apache/tubemq/client/consumer/MessageFetchManager.java
- tubemq-client/src/main/java/org/apache/tubemq/client/consumer/RmtDataCache.java
- tubemq-client/src/main/java/org/apache/tubemq/client/consumer/TopicProcessor.java
replace explicit type with <>
example: List<String> list = new ArrayList<String>(); -> List<String> list = new ArrayList<>();
scope of influence:
package: org.apache.tubemq.client.consumer
> [TUBEMQ-91] replace explicit type with <>

- tubemq-client/src/main/java/org/apache/tubemq/client/consumer/BaseMessageConsumer.java
- tubemq-client/src/main/java/org/apache/tubemq/client/consumer/ConsumerSamplePrint.java
- tubemq-client/src/main/java/org/apache/tubemq/client/consumer/RmtDataCache.java
- tubemq-client/src/main/java/org/apache/tubemq/client/consumer/SimplePullMessageConsumer.java
- tubemq-client/src/test/java/org/apache/tubemq/client/consumer/RmtDataCacheTest.java
1. Fix type
ared -> area
partionStr -> partitionStr
getPartitonByKey -> getPartitionByKey
2. Simplify 'instanceof' judgment
This code
```
if (e instanceof IOException || e instanceof Exception) {
//
}
```
It can be replaced by the following code
```
if (e instanceof Exception) {
//
}
```
> [TUBEMQ-98] Fix typo & Simplify 'instanceof' judgment

- tubemq-core/src/main/java/org/apache/tubemq/corebase/cluster/MasterInfo.java
Because the core module uses jdk1.7, this code cannot use 'putIfAbsent'
```
addrMap4Failover.putIfAbsent(tmpNodeAddrInfo.getHostPortStr(), tmpNodeAddrInfo);
```
We should use the original
```
if (addrMap4Failover.get(tmpNodeAddrInfo.getHostPortStr()) == null) {
addrMap4Failover.put(tmpNodeAddrInfo.getHostPortStr(), tmpNodeAddrInfo);
}
```
> [TUBEMQ-102] Fix question [TUBEMQ-101] [Optimize code]

- tubemq-client/src/main/java/org/apache/tubemq/client/consumer/RmtDataCache.java
- tubemq-core/src/main/java/org/apache/tubemq/corebase/utils/MapBackedSet.java
1. Fixed a bug
Syntax error
```
map.keySet().iterator(); (1.8 syntax) -> new ArrayList<>(map.keySet()).iterator();
```
2. Minor changes
```
if (curToken != null && curToken == usedToken) {
return true;
}
change to
return curToken != null && curToken == usedToken;
```
```
if (isReged == null) {
return true;
}
change to
return isReged == null;
```
```
List<String> partKeys = new ArrayList<>();
partKeys.addAll(partitionUsedMap.keySet());
change to
List<String> partKeys = new ArrayList<>(partitionUsedMap.keySet());
```
> [TUBEMQ-127] Fixed a bug & minor changes

- tubemq-core/src/test/java/org/apache/tubemq/corebase/policies/TestFlowCtrlRuleHandler.java
- tubemq-core/src/test/java/org/apache/tubemq/corerpc/codec/DataConverterUtilTest.java
- tubemq-core/src/test/java/org/apache/tubemq/corerpc/codec/PbEnDecoderTest.java
- tubemq-core/src/test/java/org/apache/tubemq/corerpc/netty/NettyProtocolEncoderTest.java
- tubemq-core/src/test/java/org/apache/tubemq/corerpc/utils/TSSLEngineUtilTest.java
1. Optimize the use of assertions
2. Fix possible null pointer exception
```
SSLEngine sslEngine = null;
try {
// create engine
sslEngine = TSSLEngineUtil.createSSLEngine(keyStorePath, trustStorePath,
keyStorePassword, trustStorePassword, true, false);
} catch (Throwable e) {
e.printStackTrace();
}
// If the above code is a field, it may cause the object sslEngine is null
boolean needClientAuth = sslEngine.getNeedClientAuth();
```
> [TUBEMQ-138] Optimize core module test case code

- tubemq-client/src/main/java/org/apache/tubemq/client/config/ConsumerConfig.java
- tubemq-client/src/main/java/org/apache/tubemq/client/config/TubeClientConfig.java
- tubemq-core/src/main/java/org/apache/tubemq/corebase/exception/AddressException.java
- tubemq-core/src/main/java/org/apache/tubemq/corebase/utils/AddressUtils.java
- tubemq-core/src/test/java/org/apache/tubemq/corebase/utils/AddressUtilsTest.java
1. Remove the requirement to provide localHostIP
2. Optimize the TubeClientConfig constructor to remove some explicit exceptions
> [TUBEMQ-141] Remove the requirement to provide localHostIP

- bin/tubemq
- docs/tubemq_user_guide.md
I merged the features of the 2 scripts (master.sh/broker.sh), which support commands to start, stop and restart on either the master or broker server.
When the directory path is added to the path environment variable, it works like this:
I wonder if this solves the problem with this jira?
> [TUBEMQ-172] simplify start/stop script

- tubemq-server/pom.xml
Delete duplicate dependency of jetty in tuber-server pom.
Jira link with: https://issues.apache.org/jira/browse/TUBEMQ-205
> [TUBEMQ-205] Delete duplicate dependency of jetty in tuber-server pom

- tubemq-server/src/test/java/org/apache/tubemq/server/broker/msgstore/disk/FileSegmentListTest.java
- tubemq-server/src/test/java/org/apache/tubemq/server/broker/msgstore/disk/FileSegmentTest.java
There are some residual files after executed unit tests by 'tubemq-server' module, create temporary files to avoid this problem.
Jira link with: https://issues.apache.org/jira/browse/TUBEMQ-206
> [TUBEMQ-206] Delete residual files after executed unit tests

- pom.xml
- tubemq-connectors/pom.xml
- tubemq-connectors/tubemq-connector-flink/pom.xml
- tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/Tubemq.java
- tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/TubemqOptions.java
- tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/TubemqSourceFunction.java
- tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/TubemqTableSource.java
- tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/TubemqTableSourceFactory.java
- tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/TubemqValidator.java
- tubemq-connectors/tubemq-connector-flink/src/main/resources/META-INF/services/org.apache.flink.table.factories.TableFactory
- tubemq-connectors/tubemq-connector-flink/src/test/java/org/apache/flink/connectors/tubemq/TubemqTest.java
1. Add module of 'tubemq-connectors' for project, it will contains all types of connector for TubeMQ, like Flink, Spark, etc. 
2. Support TubeMQ connector of source for Apache Flink.
Jira link with: https://issues.apache.org/jira/browse/TUBEMQ-197
> [TUBEMQ-197] Support TubeMQ connector of source for Apache Flink

- tubemq-server/src/main/java/org/apache/tubemq/server/broker/web/BrokerAdminServlet.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebAdminGroupCtrlHandler.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerDefConfHandler.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerTopicConfHandler.java
Fixed unnecessary method calls such as String.valueOf ()
For exmple:
```
String.valueOf(inputTopicName).trim();
change to
inputTopicName.trim();
```
```
String.valueOf(inputConsumerId).trim();
change to 
inputConsumerId.trim();
```
etc..
> [TUBEMQ-224] Fixed: Unnecessary conversion to string inspection for server module

- tubemq-server/src/main/java/org/apache/tubemq/server/broker/TubeBroker.java
If the broker fails to register with the master, a total of 5 reconnections will be attempted. But I think we should pause the thread for a period of time every time the connection fails to be reconnected
```
for (int i; i < reconnectionTimes; i++) {
try {
tryConnect();
} catch (Throwable e) {
try {
TimeUnit.MILLISECONDS.sleep(200);
} catch (InterruptedException ignored) {
//ignore interrupted
}
}
}
```
> [TUBEMQ-232] TubeBroker#register2Master, reconnect and wait

- tubemq-docker/README.md
- tubemq-docker/tubemq-k8s/.helmignore
- tubemq-docker/tubemq-k8s/Chart.yaml
- tubemq-docker/tubemq-k8s/README.md
- tubemq-docker/tubemq-k8s/templates/_broker.tpl
- tubemq-docker/tubemq-k8s/templates/_helpers.yaml
- tubemq-docker/tubemq-k8s/templates/_master.tpl
- tubemq-docker/tubemq-k8s/templates/_zookeeper.tpl
- tubemq-docker/tubemq-k8s/templates/broker-configmap.yaml
- tubemq-docker/tubemq-k8s/templates/broker-ini-configmap.yaml
- tubemq-docker/tubemq-k8s/templates/broker-pdb.yaml
- tubemq-docker/tubemq-k8s/templates/broker-service.yaml
- tubemq-docker/tubemq-k8s/templates/broker-statefulset.yaml
- tubemq-docker/tubemq-k8s/templates/master-configmap.yaml
- tubemq-docker/tubemq-k8s/templates/master-ini-configmap.yaml
- tubemq-docker/tubemq-k8s/templates/master-pdb.yaml
- tubemq-docker/tubemq-k8s/templates/master-service.yaml
- tubemq-docker/tubemq-k8s/templates/master-statefulset.yaml
- tubemq-docker/tubemq-k8s/templates/zookeeper-configmap.yaml
- tubemq-docker/tubemq-k8s/templates/zookeeper-pdb.yaml
- tubemq-docker/tubemq-k8s/templates/zookeeper-service.yaml
- tubemq-docker/tubemq-k8s/templates/zookeeper-statefulset.yaml
- tubemq-docker/tubemq-k8s/values.yaml
> [TUBEMQ-241] add k8s helm chart for tubemq

- bin/broker.cmd
- bin/env.cmd
- bin/master.cmd
Implement windows startup scripts, which consists of 3 command scripts:
1. env.cmd: this is to setup JDK-related configurations;
2. master.cmd: this is to start Master node, based on env.cmd;
3. broker.cmd: this is to start Broker node, based on env.cmd as well.
Details: [JIRA# TUBEMQ-226](https://issues.apache.org/jira/browse/TUBEMQ-226)
> [TUBEMQ-226] Add Windows startup scripts

- tubemq-server/src/main/java/org/apache/tubemq/server/broker/metadata/BrokerDefMetadata.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/metadata/TopicMetadata.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/msgstore/MessageStore.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/msgstore/disk/MsgFileStore.java
Implement the unflushSize as a factor to trigger data flush, and the changes consist of the following 3 parts:
**MsgFileStore**: Make use of curUnflushSize and unflushDataHold settings to trigger;
**Metadata**: Reuse unflushDataHold to store the flush strategy;
Details: [TUBE-126](https://issues.apache.org/jira/browse/TUBEMQ-126)
> [TUBEMQ-126] Increase the unflushed data bytes control

- bin/env.cmd
- tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerDefConfHandler.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerTopicConfHandler.java
As in bug description, it would fail the data validation as we have reused a parameter which was deprecated, and has modified the original definition in BDB, so it requires to be set as UNDEFINED or it would be treated as not properly initialized.
By the way, fix a tiny typo that the min heap size would never be 512g (too big!).
> [TUBEMQ-265] Unexpected broker disappearance in broker list after updating default broker metadata

- .gitignore
- tubemq-client-twins/tubemq-client-cpp/CMakeLists.txt
- tubemq-client-twins/tubemq-client-cpp/build_linux.sh
- tubemq-client-twins/tubemq-client-cpp/example/CMakeLists.txt
- tubemq-client-twins/tubemq-client-cpp/example/log/CMakeLists.txt
- tubemq-client-twins/tubemq-client-cpp/example/log/main.cc
- tubemq-client-twins/tubemq-client-cpp/include/tubemq/logger.h
- tubemq-client-twins/tubemq-client-cpp/src/CMakeLists.txt
- tubemq-client-twins/tubemq-client-cpp/src/client_config.cc
- tubemq-client-twins/tubemq-client-cpp/src/flowctrl_def.cc
- tubemq-client-twins/tubemq-client-cpp/third_party/CMakeLists.txt
[TUBEMQ-274]Support CMake compilation
> [TUBEMQ-274]Support CMake compilation

- tubemq-server/pom.xml
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/web/WebServer.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/web/WebServer.java
As mortbay version of Jetty 6 is old enough, this PR upgrade it to the latest eclipse version of Jetty 9, so as to keep in sync with the latest fixes and improvements.
Also it's the pre-step of adding support about POST request, as there has been no document for now to develop on Jetty 6 (a thing about 10+ years ago).
> [TUBEMQ-308] Upgrade Jetty 6 (mortbay) => Jetty 9 (eclipse)

- tubemq-server/src/main/java/org/apache/tubemq/server/master/web/WebServer.java
As described in [TUBEMQ-320](https://issues.apache.org/jira/browse/TUBEMQ-320).
Tested fine for both WebAPI part and Static Resource part.
Remember to test with Ctrl-F5 to force browser send request without cache.
> [TUBEMQ-320] Request for static web contents would get responses with no content

- tubemq-client/src/main/java/org/apache/tubemq/client/consumer/BaseMessageConsumer.java
- tubemq-client/src/main/java/org/apache/tubemq/client/consumer/RmtDataCache.java
- tubemq-client/src/test/java/org/apache/tubemq/client/consumer/RmtDataCacheTest.java
Analyzing the code, the timer event loss has never occurred before, it is suspected to be related to the running platform environment. I add a timeout detection mechanism to the Push consumption mode, which trigger a timeout events to the partitions that have expired but have not triggered , to avoid partition idleness .
> [TUBEMQ-359] TubeMQ consume speed dropped to 0 in some partitions, it is a very serious bug

- tubemq-client-twins/tubemq-client-cpp/src/client_connection.cc
- tubemq-client-twins/tubemq-client-cpp/src/client_service.cc
Add static const variable definition to fix link error reported at https://issues.apache.org/jira/browse/TUBEMQ-380
> [TUBEMQ-380] fix static const variable definition

- tubemq-client-twins/tubemq-client-python/src/cpp/tubemq_client.cc
- tubemq-client-twins/tubemq-client-python/src/cpp/tubemq_config.cc
- tubemq-client-twins/tubemq-client-python/src/cpp/tubemq_errcode.cc
- tubemq-client-twins/tubemq-client-python/src/cpp/tubemq_message.cc
- tubemq-client-twins/tubemq-client-python/src/cpp/tubemq_return.cc
[TUBEMQ-399] expose C++ SDK method by Pybind11
> [TUBEMQ-399] expose C++ SDK method by Pybind11

- tubemq-client-twins/tubemq-client-python/src/python/example/client.conf
- tubemq-client-twins/tubemq-client-python/src/python/example/test_consumer.py
[TUBEMQ-400] add example for consume message
> [TUBEMQ-400] add example for consume message

- tubemq-client-twins/tubemq-client-python/README.md
- tubemq-client-twins/tubemq-client-python/setup.py
add cpp configurations for python sdk install
> [TUBEMQ-405] add cpp configurations for python sdk install

- tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/Tubemq.java
The reason for this problem is that the Tubemq class is shared in the source and sink, but the required parameters required by the source and sink are inconsistent, the Tubemq.toConnectorProperties() does not check whether the corresponding required parameters are met according to different ways of use.
The problem is solved by adding the consumerRole attribute (the default true, consumer role) and the role setting API asConsumer (boolean isConsumer) in the Tubemq class
> [TUBEMQ-441]An error occurred when using the Tubemq class to create a sink table

- bin/env.sh
This problem is a clerical error. TubeMQ is used in very large-scale scenarios, Master and Broker are rarely deployed in one machine, even if they are deployed in one, there is no performance problem, so this problem has not been found.
> [TUBEMQ-442]Modifying the jvm parameters when the broker starts does not take effect

- tubemq-client/src/main/java/org/apache/tubemq/client/common/TClientConstants.java
- tubemq-client/src/main/java/org/apache/tubemq/client/consumer/SimplePullMessageConsumer.java
Since the available status of the partition is also controlled by the server, if the detection sleep interval is too long, the partition consumption delay response will not be sensitive enough, so adjust the value to a smaller value.
> [TUBEMQ-445]Adjust the status check default sleep interval of pullConsumeReadyChkSliceMs

- tubemq-core/src/main/java/org/apache/tubemq/corebase/utils/AddressUtils.java
- tubemq-example/src/main/java/org/apache/tubemq/example/MessageConsumerExample.java
- tubemq-server/src/main/java/org/apache/tubemq/server/tools/cli/CliConsumer.java
Found some small bugs
1. AddressUtils.getIPV4LocalAddress() should first check whether localIPAddress has been set, and use it directly under the premise that it has been set to reduce unnecessary get operations;
2. The fetchCount parameter in MessageConsumerExample may be negative, so the executorService object should not use fetchCount as the initial value.
3. Remove the useless parameter WITHOUTDELAY
> [TUBEMQ-446]Small bugs fix that do not affect the main logics

- bin/tubemq-broker-admin.sh
- pom.xml
- tubemq-server/pom.xml
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/web/AbstractWebHandler.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/web/BrokerAdminServlet.java
- tubemq-server/src/main/java/org/apache/tubemq/server/common/fielddef/CliArgDef.java
- tubemq-server/src/main/java/org/apache/tubemq/server/common/fielddef/WebFieldDef.java
- tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/HttpUtils.java
- tubemq-server/src/main/java/org/apache/tubemq/server/common/webbase/WebMethodMapper.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/web/action/screen/Webapi.java
- tubemq-server/src/main/java/org/apache/tubemq/server/tools/cli/CliAbstractBase.java
- tubemq-server/src/main/java/org/apache/tubemq/server/tools/cli/CliBrokerAdmin.java
- tubemq-server/src/main/java/org/apache/tubemq/server/tools/cli/CliConsumer.java
- tubemq-server/src/main/java/org/apache/tubemq/server/tools/cli/CliProducer.java
1. Add Broker-Admin's Cli command, directly enter the command(deficiency: I want to implement the command and then bring the sub-command mode, and found that commons-cli cannot support my own ideas, temporarily adopt this plan, and adjust it when there is a better plan );
2. Modify some implementation bugs of web-api
> [TUBEMQ-447] Add Broker-Admin Cli

- tubemq-server/src/main/java/org/apache/tubemq/server/master/TMaster.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/nodemanage/nodeconsumer/ConsumerInfoHolder.java
The current implementation of ConsumeTupleInfo can be completely replaced by Tuple2 to reduces duplicate class definitions.
> [TUBEMQ-451]Replace ConsumeTupleInfo with Tuple2

- tubemq-client/src/main/java/org/apache/tubemq/client/config/TubeClientConfig.java
- tubemq-core/src/main/java/org/apache/tubemq/corebase/utils/AddressUtils.java
1. Check the IP type when adding the local IP input setting;
2. Cancel the requirement of compulsory setting of IP address, if it does not exist, take the first IPV4 address of the machine;
3. The client configuration adds the localAddress information printing
> [TUBEMQ-450]TubeClientException: Generate producer id failed

- tubemq-server/src/main/java/org/apache/tubemq/server/master/MasterConfig.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/TMaster.java
1. Increase the rebalance parallelism control parameter rebalanceParallel in master.ini
2. Process rebalance based on parallelism
> [TUBEMQ-463]Adjust Master rebalance process implementation

- tubemq-server/src/main/java/org/apache/tubemq/server/broker/metadata/TopicMetadata.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/msgstore/MessageStore.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/msgstore/MessageStoreManager.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/msgstore/StoreService.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/offset/DefaultOffsetManager.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/offset/OffsetService.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/utils/GroupOffsetInfo.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/utils/TopicPubStoreInfo.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/web/BrokerAdminServlet.java
> [TUBEMQ-482] Add offset query api

- tubemq-core/src/main/java/org/apache/tubemq/corebase/utils/MixedUtils.java
- tubemq-core/src/main/proto/MasterService.proto
- tubemq-server/src/main/java/org/apache/tubemq/server/common/TServerConstants.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/bdbstore/BdbStoreService.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/bdbstore/DefaultBdbStoreService.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/bdbstore/bdbentitys/BdbClusterSettingEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/nodemanage/nodebroker/BrokerConfManager.java
1. add cluster default setting table;
2. add functions for operate table.
> [TUBEMQ-499] Add configure store

- tubemq-server/src/main/java/org/apache/tubemq/server/broker/metadata/ClusterConfigHolder.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/msgstore/disk/FileSegment.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/msgstore/disk/MsgFileStore.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/utils/DataStoreUtils.java
When reading the stored data file, use the upper limit maxMsgSize length of the message to read data, to avoid the adjustment of the maxMsgSize during system operation
> [TUBEMQ-509] Adjust the packet length check when data is loaded

- tubemq-server/src/main/java/org/apache/tubemq/server/broker/msgstore/MessageStore.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/offset/DefaultOffsetManager.java
- tubemq-server/src/main/java/org/apache/tubemq/server/broker/web/BrokerAdminServlet.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/MasterConfig.java
- tubemq-server/src/main/java/org/apache/tubemq/server/tools/cli/CliConsumer.java
- tubemq-server/src/main/java/org/apache/tubemq/server/tools/cli/CliProducer.java
At present, many places in the code implementation use conditional operators(? : ) for value checking, but it's not very readable, and the MixedUtils.mid() function is used instead
> [TUBEMQ-511]Replace the conditional operator (?:) with mid()

- tubemq-client-twins/tubemq-client-cpp/conf/client.conf
- tubemq-client-twins/tubemq-client-python/src/python/tubemq/client.conf
The two files adopts the LICENSE version of TubeMQ when the project is open source, and is adjusted to the standard LICESNE file of Apache V2.
> [TUBEMQ-544]Adjust the LICENSE statement in the client.conf files of Python and C/C++ SDK

- pom.xml
- tubemq-client-twins/tubemq-client-cpp/src/any.h
- tubemq-client-twins/tubemq-client-cpp/src/buffer.h
- tubemq-core/src/main/java/org/apache/tubemq/corebase/utils/TStringUtils.java
1. Restore the original license header of the referenced external source files;
2. Modify rat configuration in pom.xml to exclude the LICENSE normative check of the cited external source files;
3. Confirm that the referenced source file already has a LICENSE statement(already exists, no need to modify).
> [TUBEMQ-546]Restore the original license header of the referenced external source files

- tubemq-docker/tubemq-all/Dockerfile
- tubemq-manager/bin/start-manager.sh
- tubemq-manager/bin/stop-manager.sh
- tubemq-manager/conf/logback.xml
- tubemq-manager/src/main/assembly/assembly.xml
The following files do not carry the standard Apache V2 LICENSE header:
tubemq-docker/tubemq-all/Dockerfile
tubemq-manager/bin/start-manager.sh
tubemq-manager/bin/stop-manager.sh
tubemq-manager/conf/logback.xml
tubemq-manager/src/main/assembly/assembly.xml
> [TUBEMQ-558] Adjust the LICENSE of the file header

- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/DataOpErrCode.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/BaseEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/BrokerConfEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/ClusterSettingEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/GroupBlackListEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/GroupConfigEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/GroupFilterCtrlEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/TopicConfEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/TopicCtrlEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/TopicPropGroup.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/AbstractMapper.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/BrokerConfigMapper.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/ClusterConfigMapper.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/GroupBlackListMapper.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/GroupFilterCtrlMapper.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/TopicConfigMapper.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/TopicCtrlMapper.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/impl/bdbimpl/BdbBrokerConfigMapperImpl.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/impl/bdbimpl/BdbClusterConfigMapperImpl.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/impl/bdbimpl/BdbGroupBlackListMapperImpl.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/impl/bdbimpl/BdbGroupConfigMapperImpl.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/impl/bdbimpl/BdbGroupFilterCtrlMapperImpl.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/impl/bdbimpl/BdbTopicConfigMapperImpl.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/impl/bdbimpl/BdbTopicCtrlMapperImpl.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/keepalive/AliveObserver.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/keepalive/KeepAlive.java
1. Add data cache processing of BDB metadatas;
2. Adjust Mapper's interface collection
3. Add equals and matching interface for each Entity class
> [TUBEMQ-581] Add data cache in BDB metadata Mapper implementations

- tubemq-client-twins/tubemq-client-cpp/example/consumer/test_consumer.cc
- tubemq-client-twins/tubemq-client-cpp/example/consumer/test_multithread_pull.cc
- tubemq-client-twins/tubemq-client-cpp/include/tubemq/tubemq_client.h
- tubemq-client-twins/tubemq-client-cpp/include/tubemq/tubemq_config.h
- tubemq-client-twins/tubemq-client-cpp/src/client_service.cc
- tubemq-client-twins/tubemq-client-cpp/src/client_service.h
- tubemq-client-twins/tubemq-client-cpp/src/const_config.h
- tubemq-client-twins/tubemq-client-cpp/src/tubemq_client.cc
- tubemq-client-twins/tubemq-client-cpp/src/tubemq_config.cc
- tubemq-client-twins/tubemq-client-cpp/src/version.h
1. Adjust the StartTubeMQService API to support service initialization according to TubeMQServiceConfig object;
2. Adjust the ToString() function definition of BaseConfig,ConsumerConfig classes
> [TUBEMQ-594] Trpc-go tube sdk strongly rely on local config

- tubemq-server/src/main/java/org/apache/tubemq/server/common/fielddef/WebFieldDef.java
- tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/WebParameterUtils.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/MetaDataManager.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/BdbMetaStoreServiceImpl.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/MetaStoreService.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/BaseEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/BrokerConfEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/ClusterSettingEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/GroupBlackListEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/GroupConsumeCtrlEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/GroupResCtrlEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/TopicCtrlEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/TopicDeployEntity.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/mapper/BrokerConfigMapper.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/mapper/GroupConsumeCtrlMapper.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/mapper/GroupResCtrlMapper.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/mapper/TopicCtrlMapper.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/mapper/TopicDeployMapper.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbBrokerConfigMapperImpl.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbGroupConsumeCtrlMapperImpl.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbGroupResCtrlMapperImpl.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbTopicCtrlMapperImpl.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbTopicDeployMapperImpl.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerConfHandler.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebGroupConsumeCtrlHandler.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebGroupResCtrlHandler.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebMasterInfoHandler.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebTopicCtrlHandler.java
- tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebTopicDeployHandler.java
1. add WebTopicCtrlHandler class
2. Adjust the return result type of WebParameterUtils.getAUDBaseInfo()
> [INLONG-597] Adjust WebTopicCtrlHandler class implementation

- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/tools/MasterStartup.java
Reverts apache/incubator-inlong#551
Sorry, I must revert this PR
The modification of this PR is a modification of the CLI command, we have defined a principle in the CLI command: we only record the information after the program is started in the log file. If the program fails to start due to a wrong startup parameter, we output it through System.err.println(), and you can also see this CLI directory, all other classes follow this definition.
> Revert "[INLONG-744] Error log, should use log4j"

- inlong-tubemq/conf/broker.ini
- inlong-tubemq/conf/master.ini
1. change default port to 8715 in master.ini
2. add configuration instruction for defEthName in broker.ini
> [INLONG-750] Improve master.ini and broker.ini

- tubemq-client-twins/tubemq-client-go/client/consumer.go
- tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
- tubemq-client-twins/tubemq-client-go/client/message.go
> [INLONG-755]Go SDK Consumer Result

- README.md
Fixes [INLONG-783](https://issues.apache.org/jira/browse/INLONG-783): https://issues.apache.org/jira/browse/INLONG-783
Fix typo in README file.
Check the grammar of README and fix some typos.
> [INLONG-783] Fix typo in README file

- .github/workflows/ci_checkstyle.yml
https://issues.apache.org/jira/browse/INLONG-787
The checkstyle workflow starts up failed because [reviewdog/action-setup](https://github.com/reviewdog/action-setup) is not allowed to be used.
This PR sets up reviewdog through [install.sh](https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh) rather than actions.
- update checkstyle workflow
> [INLONG-787] ci: update checkstyle workflow

- tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
- tubemq-client-twins/tubemq-client-go/flowctrl/handler.go
- tubemq-client-twins/tubemq-client-go/remote/remote.go
- tubemq-client-twins/tubemq-client-go/rpc/master.go
https://issues.apache.org/jira/browse/INLONG-788
*(or)*
*(or)*
*(example:)* …
> [INLONG-788]Fix Go SDK Remote Cache Bug

- .github/labeler.yml
- .github/workflows/ci_labeler.yml
Fixes #1401
Using [labeler](https://github.com/actions/labeler) to automatically label new pull requests based on the paths of files being changed. The label of PR can make people clearly know what it does.
- Add labeler workflow
> [INLONG-1401] ci: add labeler workflow

- .asf.yaml
Fixes #1405 
modify the notifications for issue status, to avoid too many issue mails. we will use a special issue account in the future.
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? (not applicable / docs …
> [INLONG-1405][Platform] modify the notifications for issue status, to avoid too many issue mails

- inlong-tubemq/tubemq-docker/tubemq-all/Dockerfile
- inlong-tubemq/tubemq-docker/tubemq-all/README.md
Fixes #1415
*(or)*
*(or)*
*(example:)* …
> [INLONG-1415][TubeMQ] Docker image expose zookeeper port for other component usages

- docker/docker-compose/docker-compose.yml
Fixes #1448 
change tube-manager address in `docker-compose.yml`
>  [INLONG-1448][docker-compose] fix bug in docker-compose.yml

- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/constants/FetcherConstants.java
- inlong-dataproxy-sdk/src/main/java/org/apache/inlong/dataproxy/utils/ServiceDiscoveryUtils.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/AgentController.java
Fixes #1453
Modified part of inlong-manager's openapi interface 
> [INLONG-1453] agent connect dataproxy fail when using docker-compose

- inlong-dataproxy/conf/common.properties
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java
Fixes #1468
The update interval of dataproxy is quite long and may cause produce error when config is not updated
The update process of dataproxy should be quicker and configurable
> [INLONG-1468][dataproxy] The update interval of dataproxy is quite long and may cause produce error when config is not updated

- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/TMaster.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/balance/DefaultLoadBalancer.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodeconsumer/ConsumerInfoHolder.java
Fixes #1470 
Optimization items:
1. Modify the usage mode of the subGroups object to be read-only processing;
2. Adjust the log printing to output the set of consumer groups affected by each abnormality;
3. Modify the consumption information acquisition of the consumer group, and add the check that the result is null;
4. When optimizing the processing of consumer events, the list is changed from judging the size to judging whether it is empty
> [INLONG-1470]Java.util.ConcurrentModificationException error when rebalance

- inlong-tubemq/tubemq-manager/pom.xml
Fixes #1475
Tube manager compile ch.qos.logback with error
add some vital dependency
> [INLONG-1475][inlong-tubemq] Tube manager compile ch.qos.logback with error

- tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
- tubemq-client-twins/tubemq-client-go/client/heartbeat.go
- tubemq-client-twins/tubemq-client-go/metadata/subscribe_info.go
- tubemq-client-twins/tubemq-client-go/remote/remote.go
- tubemq-client-twins/tubemq-client-go/util/util.go
Fixes #1525 
*(or)*
*(or)*
*(example:)* …
> [INLONG-1525]Fix bug which will cause Go SDK fail to parse SubscribeInfo

- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/rmt_data_cache.cc
> [INLONG-1560] C++ SDK can not return error code of PartInUse and PartWaiting correctly

- docker/kubernetes/templates/_helpers.tpl
- docker/kubernetes/templates/agent-statefulset.yaml
- docker/kubernetes/templates/broker-pdb.yaml
- docker/kubernetes/templates/broker-statefulset.yaml
- docker/kubernetes/templates/dataproxy-statefulset.yaml
- docker/kubernetes/templates/manager-web-statefulset.yaml
- docker/kubernetes/templates/master-pdb.yaml
- docker/kubernetes/templates/master-statefulset.yaml
- docker/kubernetes/templates/mysql-statefulset.yaml
- docker/kubernetes/templates/tubemq-manager-service.yaml
- docker/kubernetes/templates/tubemq-manager-statefulset.yaml
- docker/kubernetes/templates/website-statefulset.yaml
- docker/kubernetes/templates/zookeeper-statefulset.yaml
- docker/kubernetes/values.yaml
fix: #1562
There are some syntax bugs and configuration bugs in helm chart.
For example:
https://github.com/apache/incubator-inlong/blob/51523c7d66845fc6c8183cc27cb1ce068bebcdf5/docker/kubernetes/templates/tubemq-manager-statefulset.yaml#L78
It should be `{{ template "inlong.mysql.hostname" . }}`
Besides, the `busybox` image don't support `/bin/bash`, so it should uses `/bin/sh`.
Etc., etc. I will fix it right away.
- `docker/kubernetes/template/*.yaml`
- `docker/kubernetes/template/_helpers.tpl`
- `docker/kubernetes/values.yaml`
- `docker/kubernetes/values.yaml`: `CRLF` -> `LF`
I will complete the documentation in another PR.
> [INLONG-1562][K8S] Fix syntax bugs and configuration bugs in helm chart

- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/rmt_data_cache.cc
> [INLONG-1568][TubeMQ] C++ SDK cant not return the whether the partition has been registered correctly

- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/CMakeLists.txt
- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/README.md
- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/example/CMakeLists.txt
- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/example/consumer/CMakeLists.txt
- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/example/consumer/test_multi_thread_filter.cc
- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/include/tubemq/tubemq_tdmsg.h
- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/release/release_linux.sh
- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/client_service.cc
- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/executor_pool.cc
- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/executor_pool.h
- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/tubemq_message.cc
- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/tubemq_tdmsg.cc
- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/version.h
- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/tests/CMakeLists.txt
- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/third_party/CMakeLists.txt
> [INLONG-1573][TubeMQ] Add TDMsg decode logic to TubeMQ's C++ SDK

- tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
- tubemq-client-twins/tubemq-client-go/config/config.go
- tubemq-client-twins/tubemq-client-go/config/config_test.go
- tubemq-client-twins/tubemq-client-go/errs/errs.go
- tubemq-client-twins/tubemq-client-go/example/consumer.go
- tubemq-client-twins/tubemq-client-go/transport/client.go
- tubemq-client-twins/tubemq-client-go/util/util.go
Fixes #1570 
*(or)*
*(or)*
*(example:)* …
> [INLONG-1570] Provide a more elegant way to set the parameter of config

- inlong-tubemq/bin/broker.cmd
- inlong-tubemq/bin/env.cmd
- inlong-tubemq/bin/master.cmd
- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/conf/client.conf
- inlong-tubemq/tubemq-client-twins/tubemq-client-python/src/python/tubemq/client.conf
issue: #1579
Fix the license header error in cmd and conf files.
BTW, the license header in `cmd` type files should start with '@rem' instead of `rem` and in `conf` type files should start with `#` instead of `;`.
> [INLONG-1579] Fix the license header error in cmd and conf files

- .github/workflows/ci_check_license.yml
- .licenserc.yaml
fix: #1571
We can use [SkyWalking Eyes](https://github.com/marketplace/actions/license-eye) to check license headers. 
- `.github/workflows/ci_check_license.yml`
- `.licenserc.yaml`
> [INLONG-1571][CI] Add check license header workflow

- inlong-sort/pom.xml
Fixes #1587 
When compile under JDK11, it will build failed. And the latest Intellij IDEA internal is jdk11.
```
[ERROR] Failed to execute goal on project sort-core: Could not resolve dependencies for project org.apache.inlong:sort-core:jar:0.11.0-incubating-SNAPSHOT: Could not find artifact jdk.tools:jdk.tools:jar:1.7 at specified path /work/JAVA_WORK/jdk/jdk/../lib/tools.jar -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
```
Exclude hbase dependency.
*(or)*
This change is already covered by existing tests, such as *(please describe …
> [INLONG-1587][Sort] Fix compile error

- .idea/vcs.xml
- inlong-sort/pom.xml
- pom.xml
Fixes #1729
Avoid using constant value as version when referencing other modules, we can use `${project.version}`
```
<dependency>
<groupId>org.apache.inlong</groupId>
<artifactId>inlong-common</artifactId>
<version>0.12.0-incubating-SNAPSHOT</version>
<exclusions>
<exclusion>
<artifactId>slf4j-api</artifactId>
<groupId>org.slf4j</groupId>
</exclusion>
<exclusion>
<artifactId>snappy-java</artifactId>
<groupId>org.xerial.snappy</groupId>
</exclusion>
<exclusion>
<artifactId>guava</artifactId>
<groupId>com.google.guava</groupId>
</exclusion>
</exclusions>
</dependency>
``` …
> [INLONG-1729] [sort] Avoid using constant value as version when referencing other modules

- inlong-dataproxy/conf/log4j.properties
Fixes #1746 
the log4j properties for dataproxy contains some useless code and some class name are incorrect
> [INLONG-1746][Dataproxy] [improve] the log4j properties for dataproxy contains some useless code and some class name are incorrect

- inlong-tubemq/tubemq-client-twins/tubemq-client-go/util/util.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/util/util_test.go
Fixes #1769
Fix panic in `SplitToMap`
Use builtin function to implement `SplitToMap`
*(or)*
*(or)*
*(example:)*
- Does this pull request …
> [INLONG-1769][TubeMQ]Fix bug in util function `SplitToMap` in Go SDK

- inlong-tubemq/tubemq-client-twins/tubemq-client-go/sub/info.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/sub/info_test.go
Fixes #1783 
Topic filters does not take effect in Go SDK
Make topic filters take effect in Go SDK
*(or)*
*(or)*
*(example:)*
- Does this …
> [INLONG-1783]Make topic filters take effect in Go SDK

- inlong-common/src/main/java/org/apache/inlong/commons/config/metrics/CountMetric.java
- inlong-common/src/main/java/org/apache/inlong/commons/config/metrics/Dimension.java
- inlong-common/src/main/java/org/apache/inlong/commons/config/metrics/GaugeMetric.java
- inlong-common/src/main/java/org/apache/inlong/commons/config/metrics/MetricDomain.java
- inlong-common/src/main/java/org/apache/inlong/commons/config/metrics/MetricItem.java
- inlong-common/src/main/java/org/apache/inlong/commons/config/metrics/MetricItemMBean.java
- inlong-common/src/main/java/org/apache/inlong/commons/config/metrics/MetricItemSet.java
- inlong-common/src/main/java/org/apache/inlong/commons/config/metrics/MetricItemSetMBean.java
- inlong-common/src/main/java/org/apache/inlong/commons/config/metrics/MetricRegister.java
- inlong-common/src/main/java/org/apache/inlong/commons/config/metrics/MetricUtils.java
- inlong-common/src/main/java/org/apache/inlong/commons/config/metrics/MetricValue.java
- inlong-common/src/test/java/org/apache/inlong/commons/config/metrics/item/AgentMetricItem.java
- inlong-common/src/test/java/org/apache/inlong/commons/config/metrics/item/TestMetricItemMBean.java
- inlong-common/src/test/java/org/apache/inlong/commons/config/metrics/set/DataProxyMetricItem.java
- inlong-common/src/test/java/org/apache/inlong/commons/config/metrics/set/DataProxyMetricItemSet.java
- inlong-common/src/test/java/org/apache/inlong/commons/config/metrics/set/TestMetricItemSetMBean.java
[Feature]Inlong-common provide monitoring indicator reporting mechanism with JMX, user can implement the code that read the metrics and report to user-defined monitor system.
Title Name: [INLONG-1786][component] [Feature]Inlong-common provide monitoring indicator reporting mechanism with JMX, user can implement the code that read the metrics and report to user-defined monitor system.
Fixes #1786
Motivation
Inlong-common provide monitoring indicator reporting mechanism with JMX, user can implement the code that read the metrics and report to user-defined monitor system.
Inlong-module can add monitor metric class that is the subclass of org.apache.inlong.commons.config.metrics.MetricItem, and register it to MBeanServer.
User-defined plugin can get module metric with JMX, and report metric …
> [INLONG-1786] Inlong-common provide monitor indicator #1786

- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/BaseMessageConsumer.java
- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/ClientSubInfo.java
- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/RmtDataCache.java
- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/SimpleClientBalanceConsumer.java
- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/factory/TubeBaseSessionFactory.java
- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/factory/TubeMultiSessionFactory.java
- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/factory/TubeSingleSessionFactory.java
- inlong-tubemq/tubemq-client/src/test/java/org/apache/inlong/tubemq/client/consumer/RmtDataCacheTest.java
- inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/ClientBalanceConsumerExample.java
Fixes #1805 
1. Adjust RmtDataCache to increase the data cache for client partition allocation processing;
2. Add the SimpleClientBalanceConsumer class to support client partition allocation processing;
3. Optimize BaseMessageConsumer to remove duplicate parameter definitions;
4. Add the usage example of ClientBalanceConsumer class
> [INLONG-1805]Add ClientBalanceConsumer class implementation

- inlong-tubemq/bin/env.sh
Fixes #1819 
1. Increase the Xms and Xmx values and set them equal to avoid insufficient memory during operation;
2. Increase the Xmn value to increase the memory of the young generation
3. Add GC configuration settings
> [INLONG-1819] Optimize GC parameter configuration in TubeMQ's env.sh file

- inlong-agent/agent-common/src/test/java/org/apache/inlong/agent/metrics/TestMetrics.java
- inlong-agent/agent-core/pom.xml
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobManager.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobMetrics.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskManager.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskMetrics.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskWrapper.java
- inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/TestTaskMetrics.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/channel/MemoryChannel.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/metrics/PluginMetric.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/PulsarSink.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/TextFileReader.java
Fixes #1826 
The agent metric now cannot cope with the inlong-common metric
Should use jmx metric defined in inlong-common
Use jmx metric defined in inlong-common
> [INLONG-1826][Feature][InLong-Agent] Use jmx metric defined in inlong-common

- inlong-agent/bin/agent-env.sh
Fixes #1854 
Agent Rmi args should be added in agent-env.sh
add rmi args in agent-env.sh
> [INLONG-1854][Feature][InLong-Agent] Agent Rmi args should be added in agent-env.sh

- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/AbsMetricItem.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/CountMetricItem.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/GaugeMaxMetricItem.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/GaugeMinMetricItem.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/GaugeNormMetricItem.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/MetricType.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/MetricValue.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/MetricValueType.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/MetricValues.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerServiceServer.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/TubeBroker.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/metrics/BrokerMetricMXBean.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/metrics/BrokerMetrics.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/metrics/BrokerMetricsHolder.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/disk/FileSegment.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/disk/MsgFileStore.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/mem/MsgMemStore.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/DefaultOffsetManager.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/offsetstorage/ZkOffsetStorage.java
- inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/broker/BrokerMetricsTest.java
Fixes #1872
1. Define the MXBean of the TubeMQ module: The main consideration is to provide different keys for TubeMQ according to different interfaces when collecting indicators, and the difference in operating interfaces;
2. Add metrics burying point of the Broker module
> [INLONG-1872]The Broker of TubeMQ supports metrics with JMX

- inlong-common/src/main/java/org/apache/inlong/commons/config/metrics/MetricItemMBean.java
- inlong-common/src/main/java/org/apache/inlong/commons/config/metrics/MetricItemSetMBean.java
- inlong-common/src/main/java/org/apache/inlong/commons/config/metrics/MetricRegister.java
- inlong-common/src/test/java/org/apache/inlong/commons/config/metrics/item/TestMetricItemMBean.java
- inlong-common/src/test/java/org/apache/inlong/commons/config/metrics/set/TestMetricItemSetMBean.java
- inlong-dataproxy/conf/common.properties
- inlong-dataproxy/dataproxy-source/pom.xml
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/DataProxyMetricItem.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/MetricListenerRunnable.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/prometheus/PrometheusMetricListener.java
- inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/metrics/TestDataProxyMetricItemSet.java
- inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/sink/pulsar/federation/TestPulsarProducerFederation.java
[INLONG-1911] add pulling metric of Prometheus, pulling metric value will not be reset.
Fixes #1911
*(or)*
*(or)*
*(example:)*
- Does this pull request introduces a new feature? (yes / no) …
> [INLONG-1911] add pulling metric of prometheus, pulling metric value will not be resetted.

- inlong-sort-standalone/conf/common.properties
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/metrics/prometheus/PrometheusMetricListener.java
Fixes #1926 
*(or)*
*(or)*
*(example:)* …
> [INLONG-1926] Inlong-Sort-Standalone support JMX metrics listener for pulling.

- inlong-manager/manager-dao/src/test/resources/sql/apache_inlong_manager.sql
- inlong-manager/manager-web/sql/apache_inlong_manager.sql
- inlong-manager/manager-web/src/test/resources/sql/apache_inlong_manager.sql
Fixes #1967
*(or)*
*(or)*
*(example:)* …
> [INLONG-1967][Bug][InLong-Manager] Cannot create the Pulsar subscription

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/AgentUtils.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/PulsarSink.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/SqlReader.java
Fixes #1978 
Multiple import tasks run normally
Create multiple data streams for the same data access service, and each data stream is configured with file import tasks
add uniq id when register metric
> [INLONG-1978][Bug][InLong-Agent] Create multiple file import tasks, and inlong-agent reports an error when registering metric

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/RemoteConfigJson.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/PropertiesConfigHolder.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/remote/ConfigMessageServlet.java
Fixes #1980 
inlong groupId instead of null will be in the left side of "="(as p1)，and dataproxy generates too much junk files in a short period of time(as p2), it's not easy to clear after a long time.
fix bug
and remove backup files
> [INLONG-1980][Bug][InLong-Dataproxy] the content of topics.properties generated incorrectly，and too much backup files generate automatically

- inlong-agent/agent-release/assembly.xml
- inlong-agent/agent-release/pom.xml
- inlong-audit/audit-dist/assembly/assembly.xml
- inlong-audit/audit-dist/pom.xml
- inlong-audit/audit-source/assembly/assembly.xml
- inlong-audit/audit-source/pom.xml
- inlong-audit/audit-store/assembly/assembly.xml
- inlong-audit/audit-store/pom.xml
- inlong-dataproxy/dataproxy-dist/pom.xml
- inlong-dataproxy/dataproxy-dist/src/main/assembly/assembly.xml
- inlong-manager/manager-web/assembly.xml
- inlong-manager/manager-web/pom.xml
- inlong-sort-standalone/sort-standalone-dist/pom.xml
- inlong-sort-standalone/sort-standalone-dist/src/main/assembly/assembly.xml
- inlong-tubemq/tubemq-client/pom.xml
- inlong-tubemq/tubemq-client/src/main/assembly/assembly.xml
- inlong-tubemq/tubemq-example/pom.xml
- inlong-tubemq/tubemq-example/src/main/assembly/assembly.xml
- inlong-tubemq/tubemq-manager/pom.xml
- inlong-tubemq/tubemq-manager/src/main/assembly/assembly.xml
- inlong-tubemq/tubemq-server/pom.xml
- inlong-tubemq/tubemq-server/src/main/assembly/assembly.xml
Fixes #1981
Rollback the modification of [1], the empty deliverables will be formed when the version is packaged
1. https://github.com/apache/incubator-inlong/pull/1982/commits/7ec403d6b0a3520b8631a595adfdbbaf7e8bec01
> [INLONG-1981][Bug] When compiling the project, the InLong-audit module reported Warning errors (addendum)

- inlong-dataproxy/dataproxy-dist/pom.xml
- inlong-dataproxy/dataproxy-dist/src/main/assembly/assembly.xml
> [INLONG-1997][Bug][InLong-DataProxy] package of DataProxy is not exist in distribution dir

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
> [INLONG-2014][InLong-DataProxy] inlong-dataproxy could not identify the groupId and topic format of topics.properties 

- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/SourceFileDetailEntityMapper.java
- inlong-manager/manager-dao/src/main/resources/mappers/SourceFileDetailEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/DataStreamServiceImpl.java
> [INLONG-2018][InLong-Manager] After approving data access, some failures happen and the data access is always in the state of configuration

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constants/CommonConstants.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/ProxyMessage.java
Fixes #2035 
Agent use wrong tid __ to generate message
Agent use right tid  to generate message
> [INLONG-2035][Bug] Agent use wrong tid __ to generate message

- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/TDMsgMixedSerializedRecord.java
- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/deserialization/DeserializationSchema.java
- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/deserialization/MultiTenancyDeserializer.java
- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/deserialization/MultiTenancyTDMsgMixedDeserializer.java
- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/deserialization/TDMsgDeserializer.java
- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/deserialization/TDMsgMixedDeserializer.java
- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/tubemq/MultiTenancyTubeConsumer.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/flink/deserialization/MultiTenancyTDMsgMixedDeserializerTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/flink/deserialization/TDMsgMixedDeserializerTest.java
Fixes #2038 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2038][Bug]inlong-sort abandon data from pulsar due to an ClassCastException

- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/CommonPropertiesHolder.java
- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/metrics/SortMetricItem.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarFederationWorker.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarProducerCluster.java
Fixes #2058 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2058] The metric of Sort-standalone append a dimension(minute level) of event time, supporting audit reconciliation of minute level.

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/CommonPropertiesHolder.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/DataProxyMetricItem.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/federation/PulsarFederationWorker.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/federation/PulsarProducerCluster.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
Fixes #2056 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2056] The metric of DataProxy append a dimension(minute level) of event time, supporting audit reconciliation of minute level. 

- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/utils/Constants.java
- inlong-sort-standalone/sort-standalone-source/pom.xml
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarProducerCluster.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/SourceContext.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/DefaultTopicChangeListener.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/FetchCallback.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSource.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSourceContext.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SubscribeFetchResult.java
- inlong-sort-standalone/sort-standalone-source/src/main/test/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSourceTest.java
Fixes #1892
Integrate SortSdk into SortSdkSource, and support to consume events from Pulsar cache cluster.
Same as the motivation.
*(or)*
*(or)*
*(example:)* …
> [INLONG-1892][Inlong-sort-standalone] Sort-standalone support consume events from Pulsar.

- inlong-tubemq/tubemq-manager/pom.xml
Fixes #2064
*(or)*
*(or)*
*(example:)* …
> [INLONG-2064] tubemq-manager TopicEntry.java:[28,36] package javax.validation.constraints not exists

- inlong-dataproxy/bin/dataproxy-stop.sh
Fixes #2068 
see  #2068 
change from org.apache.flume.node.Application to org.apache.inlong.dataproxy.node.Application
> [INLONG-2068][Bug] the class name in dataproxy stop.sh is wrong

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/MetaSink.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
Fixes #2096 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2096] DataProxy add InlongGroupId+InlongStreamId metric dimensions in TDSDKSource and TubeSink.

- .github/workflows/ci_build_docker.yml
Fixes: #2028 
Add support for docker build on GitHub Actions.
- `.github/workflows/ci_build_docker.yml`
Execute the following command.
```shell
mvn --batch-mode --update-snapshots -e -V clean verify -DskipTests -Pdocker
```
> [INLONG-2028][CI] Add support for docker build on GitHub Actions

- .github/workflows/ci_build.yml
- .github/workflows/ci_ut.yml
Fixes: #2119
Now, the website component has been excluded when building or testing project on GitHub Actions.
https://github.com/apache/incubator-inlong/blob/7b5c1ede854bda35cd13a8340dd615137bad1190/.github/workflows/ci_build.yml#L49-L50
https://github.com/apache/incubator-inlong/blob/7b5c1ede854bda35cd13a8340dd615137bad1190/.github/workflows/ci_ut.yml#L49-L50
But, according to https://stackoverflow.com/questions/63445967/githubs-action-is-not-building-react-application, we can set the `CI` environment variable to false to build node project on GitHub Actions.
Make the website component included and set the `CI` environment variable to false to build and test it.
Same solution as #2112
https://github.com/apache/incubator-inlong/blob/6fb2d928f58221c933a5d49e319f693ea94077bd/.github/workflow …
> [INLONG-2119][Website][CI] Add support for building inlong website when building and testing project

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/MetaSink.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
Fixes #2144 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2144] InlongDataProxy recover TDMsg1 protocol of TDSDKSource and MetaSink

- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/clickhouse/output/ClickHouseShardOutputFormat.java
Fixes #2148 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2148] Fix the problem that the pattern used for extracting clickhouse metadata is not compatible with some versions of clickhouse

- inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/metrics/TestDataProxyMetricItemSet.java
Fixes #2137 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2137][dataproxy] fix the flaky TestDataProxyMetricItemSet test

- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/Message.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/TBaseConstants.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/utils/DateTimeConvertUtils.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/utils/MixedUtils.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/utils/TStringUtils.java
- inlong-tubemq/tubemq-core/src/test/java/org/apache/inlong/tubemq/corebase/MessagesTest.java
- inlong-tubemq/tubemq-core/src/test/java/org/apache/inlong/tubemq/corebase/utils/DateTimeConvertUtilsTest.java
- inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/MAMessageProducerExample.java
- inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/MessageProducerExample.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/metrics/BrokerMetrics.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/utils/WebParameterUtils.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/bdbstore/bdbentitys/BdbBlackGroupEntity.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/bdbstore/bdbentitys/BdbBrokerConfEntity.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/bdbstore/bdbentitys/BdbClusterSettingEntity.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/bdbstore/bdbentitys/BdbConsumeGroupSettingEntity.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/bdbstore/bdbentitys/BdbConsumerGroupEntity.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/bdbstore/bdbentitys/BdbGroupFilterCondEntity.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/bdbstore/bdbentitys/BdbGroupFlowCtrlEntity.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/bdbstore/bdbentitys/BdbTopicAuthControlEntity.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/bdbstore/bdbentitys/BdbTopicConfEntity.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/BaseEntity.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metrics/MasterMetrics.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/tools/cli/CliProducer.java
- inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/common/WebParameterUtilsTest.java
- inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/BaseEntityTest.java
Fixes #2160
This PR revision mainly makes the following changes, and the changes are carried out in the form of equivalent replacement:
1. Construct a DateTimeConvertUtils class, which is responsible for data format conversion operations;
2. Remove the time conversion functions date2yyyyMMddHHmmss and yyyyMMddHHmmss2date in WebParameterUtils, and replace them with the corresponding functions of the DateTimeConvertUtils class;
3. Update other processing logic for time conversion
> [INLONG-2160][tubemq] Time format conversion using DateTimeFormatter

- inlong-sort-standalone/conf/common.properties
- inlong-sort-standalone/pom.xml
- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/CommonPropertiesHolder.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/metrics/prometheus/PrometheusMetricListener.java
Fixes #2164 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2164] Sort-standalone expose metric data using prometheus HttpServer.

- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/common/ClientMetrics.java
- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/common/TClientConstants.java
- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/config/TubeClientConfig.java
- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/BaseMessageConsumer.java
- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/SimpleClientBalanceConsumer.java
- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/SimplePullMessageConsumer.java
- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/SimplePushMessageConsumer.java
- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/producer/ProducerManager.java
- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/producer/SimpleMessageProducer.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/AbsMetricItem.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/CountMetricItem.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/GaugeMaxMetricItem.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/GaugeMinMetricItem.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/TimeDltMetricItem.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/ValueAdjustType.java
- inlong-tubemq/tubemq-core/src/test/java/org/apache/inlong/tubemq/corebase/MessagesTest.java
- inlong-tubemq/tubemq-core/src/test/java/org/apache/inlong/tubemq/corebase/metric/MetricItemTest.java
- inlong-tubemq/tubemq-core/src/test/java/org/apache/inlong/tubemq/corebase/utils/DateTimeConvertUtilsTest.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/metrics/BrokerMetrics.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/metrics/BrokerMetricsHolder.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metrics/MasterMetrics.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metrics/MasterMetricsHolder.java
- inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/broker/BrokerMetricsTest.java
- inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/master/MasterMetricsTest.java
> [INLONG-2176] Add histogram metric and client-side metric output

- inlong-dataproxy/conf/common.properties
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/CommonPropertiesHolder.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/prometheus/PrometheusMetricListener.java
- inlong-dataproxy/pom.xml
Fixes #2106 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2106] DataProxy expose metric data using prometheus HttpServer.

- docker/docker-compose/README.md
- docker/docker-compose/docker-compose.yml
- docker/kubernetes/templates/_helpers.tpl
- docker/kubernetes/templates/dataproxy-statefulset.yaml
- docker/kubernetes/templates/manager-web-service.yaml
- docker/kubernetes/templates/manager-web-statefulset.yaml
- docker/kubernetes/templates/website-statefulset.yaml
- docker/kubernetes/values.yaml
- docker/publish.sh
- inlong-distribution/distribution.xml
- inlong-manager/manager-docker/README.md
- inlong-manager/manager-docker/pom.xml
Fixes #2210
*(or)*
*(or)*
*(example:)* …
> [INLONG-2210] package inlong-manager-web as inlong-manager

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/audit/AuditInfo.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/audit/AuditRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
- inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/service/core/AuditServiceTest.java
Audit data supports auditId batch query
Fixes #2192 
*(or)*
*(or)*
*(example:)*
- If a …
> [INLONG-2192] Audit data supports auditId batch query

- inlong-sort-standalone/pom.xml
Fixes #2202 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2202] add lower version log4j exclusion in sort-standalone pom.xml

- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerServiceServer.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/MessageStore.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/MessageStoreManager.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/disk/FileSegment.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/disk/FileSegmentList.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/disk/MsgFileStore.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/disk/Segment.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/disk/SegmentList.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/mem/MsgMemStore.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/tools/StoreRepairAdmin.java
- inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/broker/msgstore/disk/FileSegmentListTest.java
- inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/broker/msgstore/disk/FileSegmentTest.java
- inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/broker/msgstore/mem/MsgMemStoreTest.java
Fixes #2232
1. Add the write and read processing of start and end timestamp information for Segment;
2. Based on point 1, modify the corresponding API calling logic, increase the incoming time information, and find the corresponding segment according to the specified timestamp
3. Add comments to improve code readability
> [INLONG-2232][tubemq] Add start and end timestamp of segment

- inlong-sdk/sort-sdk/pom.xml
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/InLongTopicFetcher.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SysConstants.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/entity/CacheZoneCluster.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/entity/InLongTopic.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/InLongTopicManagerImpl.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/pulsar/InLongPulsarFetcherImpl.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/tube/InLongTubeFetcherImpl.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/tube/TubeConsumerCreater.java
[INLONG-1931][Feature][sort-sdk] sort-sdk support consume tube events from cachezone
Fixes #1931
*(or)*
*(or)*
*(example:)*
- Does this pull request introduce a new feature? (yes / …
> [INLONG-1931][Feature][sort-sdk] sort-sdk support consume tube events from cachezone

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/BaseSource.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ConfStringUtils.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/DefaultServiceDecoder.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageFactory.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServiceDecoder.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleMessageHandler.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleTcpSource.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleUdpSource.java
- inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/source/UdpSourceTest.java
DataProxy add supporting to udp protocol for reporting data
Fixes #1950
> [INLONG-1950][DataProxy] DataProxy add supporting to udp protocol for reporting data

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/MetricListenerRunnable.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/prometheus/PrometheusMetricListener.java
- inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/metrics/TestMetricListenerRunnable.java
Fixes #2264 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2264] DataProxy get metric value with error JMX ObjectName

- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/metrics/MetricListenerRunnable.java
- inlong-sort-standalone/sort-standalone-common/src/test/java/org/apache/inlong/sort/standalone/metrics/TestMetricListenerRunnable.java
- inlong-sort-standalone/sort-standalone-common/src/test/java/org/apache/inlong/sort/standalone/metrics/TestSortMetricItemSet.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/metrics/prometheus/PrometheusMetricListener.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/hive/HiveSink.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/hive/WriteHdfsFileRunnable.java
Fixes #2263 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2263] SortStandalone get metric value with error JMX ObjectName

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sort/SortClusterConfigResponse.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/SortService.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/SortController.java
- inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/controller/openapi/SortControllerTest.java
Fixes #2161
Interface that sort acquire configs of current cluster.  Which consists of a series tasks that inlcudes the topic of caches where fetch data, and the address of sinks data sent to. 
Add controller of getSortClusterConfig, the tables has not defined yet.
*(or)*
*(or)*
*(example:)* …
> [INLONG-2161][Feature][Manager] Manager support getSortClusterConfig interface.

- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/SortClusterConfgiEntity.java
- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/SortClusterConfgiEntityMapper.java
- inlong-manager/manager-dao/src/main/resources/generatorConfig.xml
- inlong-manager/manager-dao/src/main/resources/mappers/SortClusterConfgiEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/SortClusterConfigService.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortClusterConfigServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java
- inlong-manager/manager-web/sql/apache_inlong_manager.sql
- inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/controller/openapi/SortControllerTest.java
Fixes #2161
Define sort_cluster_config table. 
Use cluster name to select the corresponding tasks and the sink type of each task.
Add mappers of sort_cluster_config
Add invalid cluster name check.
Add UT of blank cluster name
*(or)*
*(or)*
*(example:)* …
> [INLONG-2161][Feature][Manager] add the sort_cluster_config table for getClusterConfig interface

- inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/kafka/KafkaSinkTestBase.java
- inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/kafka/RowToJsonKafkaSinkTest.java
- inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/kafka/RowToStringKafkaSinkTest.java
Fixes #2344 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2344][Bug][InLong-Sort] Fix kafka sink ut failed under multithread compiling

- inlong-sort-standalone/conf/es/GetClusterConfig.json
- inlong-sort-standalone/conf/es/GetSortSourceConfig.json
- inlong-sort-standalone/conf/es/common.properties
- inlong-sort-standalone/pom.xml
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/DefaultEvent2IndexRequestHandler.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsCallbackListener.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsChannelWorker.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsIdConfig.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsIndexRequest.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsOutputChannel.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSink.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSinkContext.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSinkFactory.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/IEvent2IndexRequestHandler.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/SortClusterConfig.conf
- inlong-sort-standalone/sort-standalone-source/src/test/java/common.properties
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestDefaultEvent2IndexRequestHandler.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsCallbackListener.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsChannelWorker.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsOutputChannel.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsSinkContext.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/source/sortsdk/TestSortSdkSource.java
- inlong-sort-standalone/sort-standalone-source/src/test/resources/SortClusterConfig.conf
- inlong-sort-standalone/sort-standalone-source/src/test/resources/common.properties
Fixes #2326 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2326] Inlong-Sort-Standalone support to sort the events to ElasticSearch cluster.

- inlong-manager/pom.xml
Fixes #2404
security vulnerability
pom change
*(or)*
*(or)*
*(example:)* …
> [INLONG-2404][Manager] Upgrade log4j to 2.17.1 due to CVEs

- inlong-agent/pom.xml
- inlong-sort/pom.xml
Fixes #2404
ensure new version of log4j used in all modules
pom changes
*(or)*
*(or)*
*(example:)* …
> [INLONG-2404] update more refs to logj2 version (update to 2.17.1)

- inlong-audit/pom.xml
- inlong-tubemq/tubemq-manager/pom.xml
Fixes #2422
use secure libs
pom changes
*(or)*
*(or)*
*(example:)* …
> [INLONG-2422] [Bug] upgrade logback to 1.2.10 due to security issues

- inlong-agent/pom.xml
- inlong-tubemq/pom.xml
- licenses/inlong-dataproxy/LICENSE-binary
- licenses/inlong-tubemq/LICENSE-binary
Fixes #2430 
use secure libs
pom changes
*(or)*
*(or)*
*(example:)* …
> [INLONG-2430] upgrade to jetty 9.4.44.v20210927

- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestDefaultEvent2IndexRequestHandler.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsCallbackListener.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsChannelWorker.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsOutputChannel.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsSinkContext.java
mock JMX MBean register.
Fixes #2435 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2435][Sort] Fix Sort-standalone UT Exceptions

- inlong-agent/agent-common/pom.xml
- inlong-audit/audit-common/pom.xml
- inlong-audit/audit-common/src/main/proto/AuditApi.proto
- inlong-audit/audit-sdk/pom.xml
- inlong-audit/audit-sdk/src/test/java/org/apache/inlong/audit/util/AuditDataTest.java
Modify the version of audit protobuf  2.5.0
Fixes #2441
> [INLONG-2441] [Inlong-Audit] Modify the version of audit protobuf

- inlong-tubemq/pom.xml
- inlong-tubemq/tubemq-server/pom.xml
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/simplemvc/VelocityTemplateEngine.java
- licenses/inlong-dataproxy/LICENSE-binary
- licenses/inlong-tubemq/LICENSE-binary
Fixes #2453
using secure libraries
* pom changes
* Velocity OUTPUT_ENCODING property no longer seems to be supported but velocity code defaults to UTF-8 anyway
*(or)*
*(or)*
*(example:)* …
> [INLONG-2453] [TUBEMQ] upgrade velocity to secure version

- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/SortTaskSinkParamEntity.java
- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/SortTaskSinkParamEntityMapper.java
- inlong-manager/manager-dao/src/main/resources/generatorConfig.xml
- inlong-manager/manager-dao/src/main/resources/mappers/SortTaskSinkParamEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/SortTaskSinkParamService.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortTaskIdParamServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortTaskSinkParamServiceImpl.java
- inlong-manager/manager-web/sql/apache_inlong_manager.sql
- inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/controller/openapi/SortControllerTest.java
Fixes #2465 
Last part of getClusterconfig interface.
Add sink params table which maintain the params of sort sink.
*(or)*
*(or)*
*(example:)* …
> [INLONG-2465][Manager] GetClusterConfig interface support select sinkParams

- inlong-dataproxy/dataproxy-source/pom.xml
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/CommonPropertiesHolder.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/dispatch/DispatchManager.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/dispatch/DispatchProfile.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/DataProxyMetricItem.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/SinkContext.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/tubezone/TubeClusterProducer.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/tubezone/TubeZoneProducer.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/tubezone/TubeZoneSink.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/tubezone/TubeZoneSinkContext.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/tubezone/TubeZoneWorker.java
- inlong-dataproxy/pom.xml
Fixes #2381 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2381] DataProxy support Tube sink of PB compression cache message protocol. 

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/dispatch/DispatchManager.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsarzone/PulsarClusterProducer.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsarzone/PulsarZoneProducer.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsarzone/PulsarZoneSink.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsarzone/PulsarZoneSinkContext.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsarzone/PulsarZoneWorker.java
Fixes #2379 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2379] DataProxy support Pulsar sink of PB compression cache message protocol.

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/dispatch/DispatchManager.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/kafkazone/KafkaClusterProducer.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/kafkazone/KafkaZoneProducer.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/kafkazone/KafkaZoneSink.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/kafkazone/KafkaZoneSinkContext.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/kafkazone/KafkaZoneWorker.java
Fixes #2380 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2380] DataProxy support Kafka sink of PB compression cache message protocol.

- docker/docker-compose/README.md
- docker/docker-compose/docker-compose.yml
Fixes: #2509
The audit feature has been brought in #1738. Next we should add support for it on Docker Compose.
- `docker/docker-compose/docker-compose.yml`
- `docker/docker-compose/README.md`
> [INLONG-2509][Feature][Audit][DockerCompose] Add support for Audit on Docker Compose

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/AgentUtils.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
Fixes #2530
Agent data time never changes
Agent data time never changes
Use Agent local time to be the send time when sending data
> [INLONG-2530][Agent][Bug] Agent data time never changes

- README.md
The Quick Start URL is invalid, Now modify it to the URL of Quick Start in the official website(https://inlong.apache.org)
issue: https://github.com/apache/incubator-inlong/issues/2531
> [INLONG-2531][Doc]The Quick Start URL is invalid

- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/common/QueryMetaResult.java
- inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/PartitionExt.java
- inlong-tubemq/tubemq-manager/pom.xml
fix param error and add override annotation
I think it is easy to be merged
fix #2596
> [INLONG-2596][TubeMQ] fix param error and add override annotation

- docker/kubernetes/templates/_helpers.tpl
- docker/kubernetes/templates/audit-statefulset.yaml
- docker/kubernetes/templates/manager-statefulset.yaml
- docker/kubernetes/templates/mysql-pvc.yaml
- docker/kubernetes/templates/mysql-secret.yaml
- docker/kubernetes/templates/mysql-service.yaml
- docker/kubernetes/templates/mysql-statefulset.yaml
- docker/kubernetes/templates/tubemq-manager-statefulset.yaml
- docker/kubernetes/values.yaml
issue: #2631
sometimes, there are existed MySQL services we can reuse.
- `docker/kubernetes`
> [INLONG-2631][k8s] make MySQL optional 

- docker/kubernetes/templates/audit-configmap.yaml
- docker/kubernetes/templates/audit-statefulset.yaml
Fixes: #2640
The value In ConfigMap must be strings and not integers.
- `docker/kubernetes/audit-configmap.yaml`
- `docker/kubernetes/audit-statefulset.yaml`
> [INLONG-2640][K8s][Audit] Fix data type error in Audit Configmap

- bin/inlong-daemon
Fixes [#2646](https://github.com/apache/incubator-inlong/issues/2646)
When starting inlong, the message middleware selects pulsar, but the script does not detect it.
the detection of the pulsar process adds another startup class PulsarStandaloneStarter
> [INLONG-2646][MQ]The startup script cannot detect that pulsar starts the process in standalone mode

- inlong-sort/pom.xml
- inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/partition/RowPartitionComputer.java
Fixes #2667 
1. Some classes are not serializable.
2. dependency hive-service-rpc is not included.
> [INLONG-2667][Sort] Fix bugs that occur when starting up sort-single-tenant

- bin/inlong-daemon
Fixes  https://github.com/apache/incubator-inlong/issues/2659
Could not build the program from JAR file. Because the inlong-sort folder only has the sort-dist-*.jar file
Modify the name of the inlong-sort component startup jar package
> [INLONG-2659][Sort] Modify the name of the inlong-sort component startup jar package

- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobManager.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java
- inlong-common/src/main/java/org/apache/inlong/common/enums/ManagerOpEnum.java
Fixes #2688 
Agent support task freeze and restart when needed
Agent support task freeze and restart when needed
And when the job is Binlog or Kafka the job instance id should be equal with job id since it's a single job 
> [INLONG-2688][Agent] Agent support freeze and restart task when needed

- inlong-common/src/main/java/org/apache/inlong/common/enums/DataTypeEnum.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/FlinkSortBaseConf.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/MqBaseConf.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/TubeBaseConf.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/UserDefinedSortConf.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongGroupTransfer.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/Constant.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/settings/InlongGroupSettings.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/ZkDisabledEventSelector.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/ZkEnabledEventSelector.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/DeserializationInfo.java
Fixes #2717 
If middleware(queue) is not necessary then use none of the middleware to identify.
> [INLONG-2717][Manager][Sort] Support none of middleware and Add DataTypeEnum

- .github/workflows/ci_build.yml
fix: #2747
Add support for uploading binary package when building the project on GitHub Actions.
- `.github/workflows/ci_build.yml`
> [INLONG-2747][Feature][CI]: Add support for uploading binary package

- .github/workflows/ci_build_docker.yml
fix: #2753
Add support for pushing the latest docker images when building them.
- `.github/workflows/ci_build_docker.yml`
> [INLONG-2753][CI] Add support for pushing docker images when building them

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongClientImpl.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java
Fixes #2741
Inlong client adds an api to get groupinfo and list groups.
support getGroupInfo for inlong client
support ListGroupList for inlong client
> [INLONG-2741][Manager] Inlong client adds an interface for querying inlong group

- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsSinkContext.java
Fixes #2730
UT will be done in the last issue #2651 
*(or)*
*(or)*
*(example:)*
- If a …
> [INLONG-2730][Sort] Reduce the number of AsyncProducerClient

- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/SortSourceConfigEntityMapper.java
- inlong-manager/manager-dao/src/main/resources/generatorConfig.xml
- inlong-manager/manager-dao/src/main/resources/mappers/SortSourceConfigEntityMapper.xml
Fixes #2798 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2798][Manager] Fix SortSourceConfig xml file problem

- inlong-agent/pom.xml
Fixes #2818 
Agent kafka job and binlog job has jar conflict, should update kafka connect version
Agent kafka job and binlog job has jar conflict, should update kafka connect version
> [INLONG-2818][Agent] Kafka and Binlog's jar has a conflict, update Kafka connect version

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
Fixes #2830 
Support more than one source for a pair of groups and streams.
- Does this pull request introduces a new feature? (no)
> [INLONG-2830][Manager] Support more than one source for a pair of groups and streams

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CommonConstants.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/ProxyMessage.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/DebeziumFormat.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/DebeziumSourceFormat.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskWrapper.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/message/PackProxyMessage.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/BinlogReader.java
- inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestBinlogReader.java
Fixes #2788 
Agent support sync sends data to dataproxy when needed (binlog etc.)
Agent support sync sends data to dataproxy when needed (binlog etc.)
Agent support sync sends data to dataproxy when needed (binlog etc.)
> [INLONG-2788][Agent] Support sync send data to dataproxy when needed

- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobManager.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskManager.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/BinlogReader.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/snapshot/BinlogSnapshotBase.java
- inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestBinlogOffsetManager.java
Fixes #2870 
Agent should use base64 to encode offset since iso-8859-1 is not supported by manager
Agent should use base64 to encode offset since iso-8859-1 is not supported by manager
> [INLONG-2870][Agent] Use base64 to encode snapshot instead of using iso-8859-1

- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractStreamSourceOperation.java
Fixes #2888
[INLONG-2888][Manager] Stream source was not deleted when calling delete operate.
> [INLONG-2888][Manager] Stream source was not deleted when calling delete operate

- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/Sender.java
Fix use syncSendMessage to send message will throw npe. 
Fixes #2922
> [INLONG-2922][SDK] Fix NPE in syncSendMessage to send message

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongStreamConf.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamTransfer.java
Fixes #2939 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2939][Manager] Add strictly ordered flag in manager client

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/AgentUtils.java
- inlong-agent/conf/agent.properties
Fixes #2908
*(or)*
*(or)*
*(example:)* …
> [INLONG-2908][Agent] Remove the space before the UUID

- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/FetchCallback.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SubscribeFetchResult.java
Fixes #2385 
Support sort sdk  **onFinishedBatch** method, consume batch message from cache 
*(or)*
*(or)*
*(example:)*
- If a …
> [INLONG-2385][Sort] SortStandalone support sort sdk consume batch message

- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsCallback.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsChannelWorker.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsIdConfig.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsSink.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsSinkContext.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaFederationWorker.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/cls/TestClsIdConfig.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/cls/TestDefaultEvent2LogItemHandler.java
Fixes #2651
Add **ClsChannelWorker** that acquire events from channel and send it by calling cls sdk. The process of sending implements transaction.
**ClsSink** is response for the maintainance of **ClsChannelWorker** .
*(or)*
*(or)*
*(example:)* …
> [INLONG-2651][Sort] Add CLS sink, and UT

- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
Fixes #2974 
Support agent to pull tasks without ip and uuid.
1. For the needed to be added and active task, select without IP and UUID, when they were pulled from manager, set the agent IP and UUID;
3. For the other status tasks, select by IP and UUID.
> [INLONG-2974][Manager] Support agent to pull tasks without ip and uuid

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongGroupContext.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/workflow/EventLogView.java
Fixes #2982 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2982][Manager] Add group logs in manager client

- inlong-dataproxy/bin/dataproxy-start.sh
Fixes #2987 
*(or)*
*(or)*
*(example:)* …
> [INLONG-2987][DataProxy] Fix typo in dataproxy-start.sh

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sort/SortSourceConfigResponse.java
- inlong-manager/manager-dao/src/main/resources/mappers/SortSourceConfigEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/SortSourceService.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/SortServiceImplTest.java
- inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
- inlong-manager/manager-web/sql/apache_inlong_manager.sql
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/SortController.java
Fixes #2694
parent issue #2573 
The sturcture of table **sort_source_config** is 
`id`            int(11)       NOT NULL AUTO_INCREMENT COMMENT 'Incremental primary key',
`cluster_name`  varchar(128)  NOT NULL COMMENT 'Cluster name',
`task_name`     varchar(128)  NOT NULL COMMENT 'Task name',
`zone_name`     varchar(128)  NOT NULL COMMENT 'Cache zone name',
`topic`         varchar(128)  DEFAULT NULL COMMENT 'Topic',
`ext_params`    text          DEFAULT NULL COMMENT 'Another fields, will saved as JSON type'
One topic belongs to one zone,  while one zone has a few of topics.
The properties of zone or topic are in the field ext_params.
The way to  differ the proerties belongs to zone or topic, is that if the field **topic** is null.  If so, it's zone properties, otherwise, it's topic's
Add …
> [INLONG-2694][Manager] Implement services of getSortSource Interface and add UT

- inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
- inlong-manager/manager-web/sql/apache_inlong_manager.sql
Fixes #3024 
Save cluster failed as the token field is too long.
> [INLONG-3024][Manager] Save cluster failed as the token field is too long

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/pojo/ThirdPartyClusterConfig.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/PulsarSink.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java
Add compressionType and maxPendingMessagesAcrossPartitions configuration while create pulsar producer #3058
Fixes #3058
> [INLONG-3058][DataProxy] Add some configs while creating Pulsar producer

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/TdmqPulsarBaseConf.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongGroupTransfer.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupMqExtBase.java
Fixes #3090 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3090][Manager] Add TDMQ_PULSAR type in manager

- inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/PulsarClusterInfo.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/PulsarBaseConf.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/TdmqPulsarBaseConf.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/consumption/ConsumptionMqExtBase.java
- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/ThirdPartyClusterEntityMapper.java
- inlong-manager/manager-dao/src/main/resources/mappers/ThirdPartyClusterEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/CommonOperateService.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ConsumptionServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongGroupServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ThirdPartyClusterServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/mq/CreatePulsarGroupForStreamTaskListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/mq/CreatePulsarGroupTaskListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/mq/CreatePulsarResourceTaskListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/mq/CreatePulsarTopicForStreamTaskListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/mq/PulsarEventSelector.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SourceInfoUtils.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/consumption/listener/ConsumptionCompleteProcessListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/stream/CreateStreamWorkflowDefinition.java
Fixes #3089 
Create group resource failed after approving one inlong group.
1. Fix exception while executing create group resource listener.
2. Add TDMQ_PULSAR type.
> [INLONG-3089][Manager] Create group resource failed after approving one inlong group

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SerializationUtils.java
Fixes #3097 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3097] Fix json parser error for TDMQ-PULSAR

- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/FetchCallback.java
Fixes #3117
*(or)*
*(or)*
*(example:)* …
> [INLONG-3117][Sort-Standalone] Fix parameter error when invoking SortSdk ack method

- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/QueryConsumeConfigImpl.java
Fixes #3121
*(or)*
*(or)*
*(example:)* …
> [INLONG-3121][SDK] Fix parameters error when SortSdk request getSortSource 

- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/CommonPropertiesHolder.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSource.java
Fixes #3116
*(or)*
*(or)*
*(example:)* …
> [INLONG-3116][Sort-Standalone] Fix SortSdkSource does not specify the manager url

- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SubscribeFetchResult.java
Fixes #3122 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3122][Sort-Standalone] Fix missing TASK_NAME parameter when report to Audit

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongGroupTransfer.java
Fixes #3140 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3140][Manager] Fix NPE in Manager Client

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java
Fixes #3152 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3152][Manager] Throw exception when group is in initialization

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/RemoteConfigManager.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/CacheClusterConfigHolder.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/CommonPropertiesHolder.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/IdTopicConfigHolder.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/dispatch/DispatchManager.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/node/ManagerPropertiesConfigurationProvider.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/kafkazone/KafkaZoneSink.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/kafkazone/KafkaZoneSinkContext.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsarzone/PulsarClusterProducer.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsarzone/PulsarZoneSink.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsarzone/PulsarZoneSinkContext.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/tubezone/TubeZoneSink.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/tubezone/TubeZoneSinkContext.java
- inlong-manager/manager-dao/src/main/resources/mappers/ClusterSetMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/DataProxyClusterServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java
Fixes #3136 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3136][DataProxy] get "NOUPDATE" configuration from Manager when request md5 is same.

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/sink/HiveSink.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSinkTransfer.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hive/HiveSinkDTO.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hive/HiveSinkListResponse.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hive/HiveSinkRequest.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hive/HiveSinkResponse.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SinkInfoUtils.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/thirdparty/sort/DisableZkForSortTest.java
Fixes #3166
Replace hdfsDefaultFs and warehouseDir of Hive sink with the dataPath field.
> [INLONG-3166][Manager] Replace hdfsDefaultFs and warehouseDir of Hive sink with the dataPath field

- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractStreamSourceOperation.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
- inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
- inlong-manager/manager-web/sql/apache_inlong_manager.sql
Fixes #3179 
Check the source name can not be the same when saving stream source.
> [INLONG-3179][Manager] Check the source name can not be the same when saving stream source

- inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestBinlogOffsetManager.java
Fixes #3077
FileNotFoundException occurred in unit tests
change test base to TestBinlogOffsetManager
> [INLONG-3077][Agent] FileNotFoundException occurred in unit tests #3077

- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/BinlogReader.java
Fixes #3199 
[INLONG-3199][Agent] Two binlog task running at the same time may have data loss
make message queue local private vaiable rather than static 
> [INLONG-3199][Agent] Two binlog task running at the same time may have data loss

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/IdTopicConfigHolder.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/pojo/IdTopicConfig.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsarzone/PulsarClusterProducer.java
Fixes #3196 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3196][DataProxy] Support to produce message to different topic in multiple Pulsar Cache

- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClient.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/SortClientImpl.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSource.java
Fixes #3237 
1. update sdk config periodiclly, to avoid the case that the init manager node offline and sdk cannot request config.
2. remove expire client, if the task has been removed from SortClusterConfig.
*(or)*
*(or)*
*(example:)* …
> [INLONG-3237][Sort-Standalone] SdkSource support periodiclly update sdk config and remove expire client.

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ConsumptionServiceImpl.java
Fixes #3242 
When submitting data consumption, set pulsar middleware_type, and solve the problem of class conversion.
*(or)*
*(or)*
*(example:)*
- If yes, how is …
> [INLONG-3243][Manager] Fix ConsumptionMqExtBase cannot be cast to ConsumptionPulsarInfo

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/AgentService.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
- inlong-manager/manager-web/sql/apache_inlong_manager.sql
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/AgentController.java
Fixes #3264 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3264][Manager] Fix deadlock in stream source

- inlong-agent/agent-docker/agent-docker.sh
Fixes #3271 
Agent docker.sh cannot get localip
Agent docker.sh  get localip use correct linux cmd
> [INLONG-3271][Agent] Agent docker.sh cannot get localip

- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/SourceSnapshotOperation.java
- inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
- inlong-manager/manager-web/sql/apache_inlong_manager.sql
Fixes #3287 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3287] Fix heartbeat manager init in Manager Service

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/plugin/Reader.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskWrapper.java
- inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/task/TestTaskWrapper.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/KafkaSource.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/BinlogReader.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/KafkaReader.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/SqlReader.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/TextFileReader.java
- inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestKafkaReader.java
Fixes #3274
When Kafka topic is deleted, then change task status to failed.
When Kafka topic is deleted, then change task status to failed.
> [INLONG-3274][Agent]  Change the task status to failed when the Kafka topic was deleted

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java
Fixes #3306 
use rocksdb as default db in agent
use rocksdb as default db in agent
> [INLONG-3306][Agent] Use rocksdb as default db

- inlong-distribution/distribution.xml
Fixes #3316
Change target sort jar from sort-dist to sort-single-tenant in inlong-distribution module
> [INLONG-3316][Sort] Change target sort jar from sort-dist to sort-single-tenant in inlong-distribution module

- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsIdConfig.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsSink.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsSinkContext.java
Fixes #3332
NP when init deletingClients and ClsWorkers
data race in ClsIdConfig, result in unexpected keyList
*(or)*
*(or)*
*(example:)* …
> [INLONG-3332][Sort-Standalone] Fix NP and data race in ClsSink

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java
Fixes #3337 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3337][Manager] Fix API error in manger client

- inlong-sort-standalone/sort-standalone-common/pom.xml
- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/ManagerUrlHandler.java
- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/SortClusterConfigHolder.java
- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/SortClusterConfigType.java
- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/SortSourceConfigType.java
- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/loader/ClassResourceQueryConsumeConfig.java
- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/loader/ClassResourceSortClusterConfigLoader.java
- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/loader/CommonPropertiesManagerUrlLoader.java
- inlong-sort-standalone/sort-standalone-source/pom.xml
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSinkContext.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSource.java
Fixes #3328 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3328][Sort-Standalone] Support to load sort-sdk configuration from file in Sort-standalone

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongGroupServiceImpl.java
Fixes #3362 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3362][Manager] Make Group.updateStatus new Transaction

- inlong-tubemq/conf/master.ini
- inlong-tubemq/pom.xml
Fixes #3363
1. Modify master.ini to use ZooKeeper as the default storage component;
2. Modify the BDB dependency scope in pom.xml to provided
> [INLONG-3363][TubeMQ]Added how to use optional BDB components and documentation

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SourceState.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractStreamSourceOperation.java
Fixes #3370 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3370][Manager] Optimize stream source delete logic

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CommonConstants.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/BinlogReader.java
Fixes #3359 
[INLONG-3359][Agent] Add semaphore for each proxy sink to prevent oom
the channel for limiting size is job-wise, we need a semaphore for all sinks
[INLONG-3359][Agent] Add semaphore for each proxy sink to prevent oom
> [INLONG-3359][Agent] Add semaphore for each proxy sink to prevent oom

- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/BinlogReader.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/BinlogTimeConverter.java
Fixes #3402
Add debezium datetime format converter
Add debezium datetime format converter
*(or)*
*(or)*
*(example:)* …
> [INLONG-3402][Agent] Add debezium datetime format converter

- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java
- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/TcpClientExample.java
- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ClientMgr.java
- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/Sender.java
- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/threads/IndexCollectThread.java
- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/threads/TimeoutScanThread.java
Fixes #3387 
- send heartbeat for idle dataChannel to keep alive
- reuse bad host while dataproxy hosts are rare, avoid there is no dataChannel
- improve code style
*(or)*
*(or)*
*(example:)* …
> [INLONG-3387][SDK] Strengthen the strategy of heartbeat and channel update for dataproxy

- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/SortClusterConfigHolder.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSource.java
Fixes #3435 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3435][Sort-Standalone] Fix user-defined SortClusterConfigType problem in Sort-standalone.

- inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/partition/JdbcHivePartitionCommitPolicy.java
- inlong-sort/sort-connectors/src/test/java/org/apache/inlong/sort/flink/hive/partition/JdbcHivePartitionCommitPolicyTest.java
Fixes #3434 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3434][Sort] Optimize the automatic splicing of database after hive jdbc url

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/CommonOperateService.java
Fixes #3451
Got wrong results when querying tube cluster info.
*(or)*
*(or)*
*(example:)*
- If a feature is not documented yet in …
> [INLONG-3451][Manager] Got wrong results when querying tube cluster info

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/SinkField.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSinkTransfer.java
Fixes #3064
*(or)*
*(or)*
*(example:)* …
> [INLONG-3064][Manager] Unify field types of sink and source in manager client

- inlong-agent/agent-plugins/pom.xml
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/BinlogTimeConverter.java
Fixes #3476 
[INLONG-3476][Agent] debezium 1.8.1 has npe, fall back to 1.8.0
[INLONG-3476][Agent] debezium 1.8.1 has npe, fall back to 1.8.0
> [INLONG-3476][Agent] debezium 1.8.1 has npe, fall back to 1.8.0

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSinkTransfer.java
Fixes #3480 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3480][Manager] Fix null pointer exception when calling sink method in manager client

- docker/kubernetes/templates/agent-service.yaml
- docker/kubernetes/templates/agent-statefulset.yaml
- docker/kubernetes/templates/audit-service.yaml
- docker/kubernetes/templates/audit-statefulset.yaml
- docker/kubernetes/templates/dashboard-service.yaml
- docker/kubernetes/templates/dashboard-statefulset.yaml
- docker/kubernetes/templates/dataproxy-service.yaml
- docker/kubernetes/templates/dataproxy-statefulset.yaml
- docker/kubernetes/templates/manager-service.yaml
- docker/kubernetes/templates/mysql-service.yaml
- docker/kubernetes/templates/tubemq-broker-service.yaml
- docker/kubernetes/templates/tubemq-broker-statefulset.yaml
- docker/kubernetes/templates/tubemq-manager-service.yaml
- docker/kubernetes/templates/tubemq-master-service.yaml
- docker/kubernetes/templates/tubemq-master-statefulset.yaml
- docker/kubernetes/templates/zookeeper-service.yaml
- docker/kubernetes/templates/zookeeper-statefulset.yaml
- docker/kubernetes/values.yaml
Fixes: #3490
Make `dashboard`, `dataproxy` and `manager` service types and ports configurable. Like this:
```yaml
service:
type: NodePort
clusterIP:
nodePort: 30801
loadBalancerIP:
externalName:
externalIPs:
```
- `docker/kubernetes`
> [INLONG-3490][InLong] Make service types and ports configurable

- inlong-tubemq/tubemq-docker/tubemq-all/Dockerfile
fixes: #3547
Install `curl` and `procps` packages in tubemq docker container.
- `inlong-tubemq/tubemq-docker/tubemq-all/Dockerfile`
> [INLONG-3547][TubeMQ] Fix curl and ps commands not found bug in docker container 

- docker/kubernetes/templates/tubemq-broker-service.yaml
- docker/kubernetes/templates/tubemq-broker-statefulset.yaml
- docker/kubernetes/templates/tubemq-manager-service.yaml
- docker/kubernetes/templates/tubemq-manager-statefulset.yaml
- docker/kubernetes/templates/tubemq-master-service.yaml
- docker/kubernetes/templates/tubemq-master-statefulset.yaml
- docker/kubernetes/templates/zookeeper-service.yaml
- docker/kubernetes/templates/zookeeper-statefulset.yaml
Fixes: #3560
Fix invalid port names in tubemq pods.
**The port name should be no more than 15 characters.**
All pods can be started correctly by command:
```
sudo kubectl get pods -n inlong -o wide
```
Shorten pod names.
> [INLONG-3560][TubeMQ] Fix invalid port names in tubemq pods

- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/InLongTopicManagerImpl.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/QueryConsumeConfigImpl.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/DefaultEvent2IndexRequestHandler.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSource.java
Fixes #3591 
*(or)*
*(or)*
*(example:)* …
> [INLONG-3591][Sort-Standalone] Support multiple SortTask with the one-on-one relationship of Source and SortTask.

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/file/FileSourceRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/file/FileSourceOperation.java
- inlong-tubemq/pom.xml
Fixes #3603
The serialization type cannot be empty for the File source.
> [INLONG-3603][Manager] The serialization type cannot be empty for File source

- docker/kubernetes/README.md
- docker/kubernetes/templates/NOTES.txt
- docker/kubernetes/values.yaml
Fixes: #3489
- provide some useful information in [NOTES.txt](docker/kubernetes/templates/NOTES.txt)
- provide more detailed comments in [values.yaml](docker/kubernetes/values.yaml) to help users configure it
The [NOTES.txt](docker/kubernetes/templates/NOTES.txt) content will be printed when installing the chart.
*(example:)*
> [INLONG-3489][K8s] Improve documentation in helm chart

- docker/kubernetes/templates/manager-statefulset.yaml
- inlong-manager/manager-docker/Dockerfile
- inlong-manager/manager-docker/manager-docker.sh
Fixes: #3681
Add an initialize database step in Docker container.
- Install `default-mysql-client` in manager `Dockerfile`
- Add an initialize database step in `manager-docker.sh`
- Add initContainer to wait mysql ready in `manager-statefulset.yaml`
> [INLONG-3681][Manager] Add an initialize database step in Docker container

- docker/kubernetes/templates/audit-statefulset.yaml
- inlong-audit/audit-docker/Dockerfile
- inlong-audit/audit-docker/audit-docker.sh
Fixes: #3734
Refer to https://github.com/apache/incubator-inlong/pull/3715#issuecomment-1099151404
Add an initialize database step in Docker container
- Install `default-mysql-client` in audit `Dockerfile`
- Add an initialize database step in `audit-docker.sh`
- Fix `JDBC_URL` in `audit-statefulset.yaml`
> [INLONG-3734][Audit] Add an initialize database step in Docker container

- .github/workflows/ci_build_docker.yml
- .github/workflows/ci_docker.yml
issue: #3744
Docker images are not pushed in `release-*` branches.
- Fix trigger condition when pushing Docker image
- Rename workflow: `ci_build_docker` -> `ci_docker`
BTW, unfortunately, there is any way to do regex matching on `if` conditional expressions yet on GitHub Actions. I referenced https://stackoverflow.com/questions/58862864/github-actions-ci-conditional-regex
> [INLONG-3744][CI] Fix trigger condition when pushing Docker image

- inlong-audit/audit-proxy/src/test/java/org/apache/inlong/audit/sink/TubeSinkTest.java
> [INLONG-3765][Audit] Fix audit-proxy TubeSinkTest ut

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/ConstantParam.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/ConstantParamTest.java
> [INLONG-3793][Sort] Add ConstantParam definition to support transform

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/ConstantParam.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/FunctionParam.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/TimeUnitConstantParam.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/TimeUnitConstantParamTest.java
> [INLONG-3794][Sort] Add TimeUnitConstantParam definition to support transform

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/FieldRelationShip.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/FieldRelationShipTest.java
> [INLONG-3790][Sort] Add FieldRelationShip definition to support transform

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/relation/NodeRelationShip.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/relation/NodeRelationTest.java
> [INLONG-3789][Sort] Add NodeRelationShip definition to support transform

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/ConstantParam.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/FunctionParam.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/StringConstantParam.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/TimeUnitConstantParam.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/ConstantParamTest.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/StringConstantParamTest.java
> [INLONG-3890][Sort] Add StringConstantParam to enhance support for constant parameters

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/Function.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/FunctionParam.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/function/SplitIndexFunction.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/function/SplitIndexFunctionTest.java
- inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/function/SplitIndexFunctionTest.java
> [INLONG-3893][Sort] Add string delimiting support for transform

- inlong-agent/agent-docker/agent-docker.sh
- inlong-audit/audit-docker/audit-docker.sh
- inlong-dataproxy/dataproxy-docker/dataproxy-docker.sh
- inlong-tubemq/tubemq-docker/tubemq-manager/manager-docker.sh
Fixes: #3898 
Fix log paths of Agent, Audit, DataProxy and TubeMQ Manager containers.
change logs path to `logs/info.log`
> [INLONG-3898][Docker] Fix log paths of Agent, Audit, DataProxy and TubeMQ Manager containers

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/sink/KafkaSink.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSinkTransfer.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/kafka/KafkaSinkDTO.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/kafka/KafkaSinkListResponse.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/kafka/KafkaSinkRequest.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/kafka/KafkaSinkResponse.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/LoadNodeUtils.java
> [INLONG-3921][Manager] Add primary key in Kafka source

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/BuiltInFieldInfo.java
- inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/parser/impl/FlinkSqlParser.java
- inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/DistinctNodeSqlParseTest.java
> [INLONG-3833][Sort] Fix hive partition fields format error

- inlong-manager/manager-web/sql/apache_inlong_manager.sql
Fixes #3951 
Unique index error for cluster_name in SQL file.
> [INLONG-3951][Manager] Unique index error for cluster_name in SQL file

- .github/dependabot.yml
Fixes: #3974
Add support for [Dependabot](https://docs.github.com/en/enterprise-server@3.4/code-security/dependabot)
- `.github/dependabot.yml`
> [INLONG-3974] Add dependabot.yml

- docker/docker-compose/docker-compose.yml
- docker/kubernetes/values.yaml
fixes: #3845
Fix the MySQL permission error in Manager Pod.
The [manager.log](https://github.com/apache/incubator-inlong/files/8571125/manager.log) by the command:
```shell
sudo kubectl logs inlong-manager-0 -n inlong
```
Modify the mysql container version to 8.0.28.
> [INLONG-3845][Docker][K8s] Fix the MySQL permission error in Manager Pod

- docker/docker-compose/docker-compose.yml
Fixes: #4001
Refer to https://github.com/apache/incubator-inlong/pull/3978#issuecomment-1111660330
Modify MySQL Docker image version to `8.0.28`
- `docker/docker-compose/docker-compose.yml`
> [INLONG-4001][Docker] Modify MySQL Docker image version to `8.0.28`

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/FieldType.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/FieldInfoUtils.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/FieldRelationShipUtils.java
> [INLONG-4017][Manager] Fix DataType deserialized Exception

- inlong-sort/sort-single-tenant/pom.xml
- inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/mysql/table/MySqlReadableMetadata.java
Fixes #4048 
Fix sort metadata type process error and hive-exec dependency scope error
modify sort pom and fix `mysql-cdc-inlong` metadata type
> [INLONG-4048][Sort] Fix sort metadata type process error and hive-exec scope error

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/HiveLoadNode.java
Fixes #4050 
Some parameter restrictions are not necessary when using mysql CDC to hive
> [INLONG-4050][Sort] Fix parameter definition error of HiveLoad

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/ExtractNodeUtils.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/LoadNodeUtils.java
> [INLONG-4060][Manager] Fix NodeUtils for sort

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/CanalJsonFormat.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/KafkaLoadNode.java
- inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/parser/impl/FlinkSqlParser.java
- inlong-sort/sort-single-tenant/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/MetaFieldSyncTest.java
> [INLONG-3815][Sort] Fix meta field sync error

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/FieldRelationShipUtils.java
> [INLONG-4067][Manager] Optimize fieldRelationShip in split transform

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongStream.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java
> [INLONG-4075][Manager] Add update, delete source, sink and transform APIs in manager client

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongStream.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java
> [INLONG-4078][Manager] Add Java docs for manager client APIs

- inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java
- inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/mysql/table/MySqlReadableMetadata.java
Fixes #4097
The jetbrains annotation is in the package of avro, so when remove the dependency the compilation fails
Use javax constrain notNull annotation 
> [INLONG-4097][Sort] Use javax constrain notNull annotation

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/DefaultInlongStreamBuilder.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/InlongStreamResponse.java
> [INLONG-4100][Manager] Add id in update request for source/sink/transform

- inlong-dashboard/src/components/MetaData/StorageHive.tsx
- inlong-dashboard/src/locales/cn.json
- inlong-dashboard/src/locales/en.json
Fixes #4102 
Add tooltip for dataPath of the Hive sink.
> [INLONG-4102][Dashboard] Add tooltip for dataPath of the Hive sink

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/Function.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/FunctionParam.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/function/CascadeFunctionWrapperTest.java
> [INLONG-3835][Sort] Register CascadeFunctionWrapper in the parent interface

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/ClusterPageRequest.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupPageRequest.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/SinkPageRequest.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/SourcePageRequest.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/InlongStreamPageRequest.java
- inlong-manager/manager-dao/src/main/resources/mappers/DataProxyClusterEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
Fixes #4120
Change the keyWord to keyword in query params, because the keyWord was error.
*(example:)*
> [INLONG-4120][Manager] Change the keyWord to keyword in query params

- inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJsonEnhancedDecodingFormat.java
- inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJsonEnhancedEncodingFormat.java
> [INLONG-3817][Sort] Fix null point exception in canal-json format

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceOperation.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/autopush/AutoPushSourceOperation.java
> [INLONG-4118][Manager] It should not return an empty list when paging the auto-push source

- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CommandDescribe.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CommandList.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CommandToolMain.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/GroupInfo.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/util/PrintUtils.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/validator/GroupStatus.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongGroupContext.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongClientImpl.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupPageRequest.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/StreamPipeline.java
- inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
Fixes #4139 
Query inlong group by the status list in manager client.
1. Add statusList param in page request.
2. Change the `State` class to `Status`.
> [INLONG-4139][Manager] Query inlong group by the status list in manager client

- inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/parser/impl/FlinkSqlParser.java
…eneration order
Fixes #3830 
*(example:)*
> [INLONG-3830][Sort] Fix the error that the SQL execution order is inconsistent with the generation order

- .github/workflows/ci_stale.yml
fix: #4161
Fix incorrect name in stale workflow
- step name: `stable` -> `stale`
- label name: `stable` -> `stale`
> [INLONG-4161][CI] Fix incorrect name in stale workflow

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/HBaseConstant.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/LoadNode.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/HbaseLoadNode.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/HbaseLoadNodeTest.java
- inlong-sort/sort-single-tenant/pom.xml
- inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/parser/impl/FlinkSqlParser.java
- inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/HbaseLoadFlinkSqlParseTest.java
- licenses/inlong-sort/LICENSE
- licenses/inlong-sort/NOTICE
- pom.xml
Fixes #4156 
supporting sink data to hbase
Add Hbase load node
*(example:)*
> [INLONG-4156][Sort] Add HBase load node

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/StreamTransformServiceImpl.java
> [INLONG-4181][Manager] Fix transform update api

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/FieldRelationShipUtils.java
> [INLONG-4183][Manager] Fix splitFields in manager service

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongGroup.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/BlankInlongGroup.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java
> [INLONG-4194][Manager] Add update sort config API in manager client

- .github/workflows/ci_greeting.yml
fix: #4205
Fix error in the greeting workflow.
> The `pull_request_target` event is similar to `pull_request`, except that it runs in the context of the base repository of the pull request, rather than in the merge commit. This means that you can more safely make your secrets available to the workflows triggered by the pull request, because only workflows defined in the commit on the base repository are run. For example, this event allows you to create workflows that label and comment on pull requests, based on the contents of the event payload.
reference:
- https://github.com/actions/first-interaction/issues/31
- https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
- replace `pull_request` with `pull_request_target`
> [INLONG-4205][CI] Fix error in the greeting workflow

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/SourceListResponse.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceListResponse.java
>  [INLONG-4221][Manager] Remove duplicate serializationType in KafkaSourceListResponse

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/DefaultInlongStreamBuilder.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java
Fixes #4203
- The stream of the HTTP request is not closed, which may cause a leak
- When creating an OkHttp request, there is redundant code. After the get() param, post() is used, and it can also be simplified.
- When parsing the response, the processing is a bit cumbersome, and the generic type is not used
- Use try-with-resources to prevent unclosed streams
- Provide a new JSON parsing method to easily parse the response of HTTP requests
- Correct some wrong usage of creating OkHttp Request object
- Does this pull request introduces a new feature? (no)
> [INLONG-4203][Manager] Improve HTTP request and response parse in manager client

- inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/group/GroupController.java
- inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/group/request/FilterCondGroupReq.java
- inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/group/request/FlowControlGroupReq.java
- inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/TubeConst.java
> [INLONG-4217][TubeMQ] Add the flow control method and filtering method of the consumption group settings

- inlong-manager/manager-client/pom.xml
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/auth/DefaultAuthentication.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/auth/SecretAuthentication.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/auth/SecretTokenAuthentication.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/auth/TokenAuthentication.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/util/JsonUtils.java
Fixes #< 4239 >
remove fastjson dependency, it's not necessary to use fastjson .Most open source projects also don't introduce fastjson
replace fastjson with jackson
- [  ] This change is a trivial rework/code cleanup without any test coverage.
> [INLONG-4239][Manager] Remove fastjson dependency

- .asf.yaml
fix: #4251
There are some improvable configuration in `.asf.yaml`, such as `Branch protection`, and so on.
Please check out https://cwiki.apache.org/confluence/exportword?pageId=127405038
- add `Branch protection` configuration in `.asf.yaml`
> [INLONG-4251][GitHub] Improve GitHub configuration in `.asf.yaml`

- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/BinlogSource.java
- inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestTextFileReader.java
- inlong-agent/agent-plugins/src/test/resources/log4j2.xml
Fixes #4235 
1. Agent-plugin unit test output log
2. Handle exceptions calling PowerMockRunner to initialize the TestTextFileReader class
> [INLONG-4235][Agent] Add log4j2 config file and fix the mock error of TestTextFileReader

- inlong-agent/agent-release/pom.xml
- licenses/inlong-agent/LICENSE
The agent module specifies dependencies on kafka-clients: version 3.0.0
Fixes #4283
> [INLONG-4283][Agent] Specifies kafka-clients version to 3.0.0

- inlong-sort/pom.xml
- inlong-sort/sort-connectors/mysql-cdc/pom.xml
- inlong-sort/sort-connectors/pom.xml
- licenses/inlong-sort/LICENSE
[Bug][Sort]
The imported dependency uses a protocol that does not conform to apache, then removed related direct reference.
Fixes #4385 
GPL component,then  removed related direct reference.
alter pom and license
cdc: 
mysql-->kafka
mysql-->sqlserver
and so on
*(example:)*
> [INLONG-4385][Sort] Excluse or remove the mysql:mysql-connector-java:jar:8.0.21 package

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/TDSQLPostgresLoadNode.java
- inlong-sort/sort-connectors/mysql-cdc/pom.xml
- pom.xml
GPL components do not conform to the terms of this project,so exclude this packeage.
If you want to continue to use related capabilities, please introduce this dependency in your own project.
Fixes #4390 
GPL components do not conform to the terms of this project.
Exclude this package
*(example:)* …
> [INLONG-4390][Sort] Exclude mysql:mysql-connector-java:jar package

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/es/ElasticsearchFieldInfo.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/es/ElasticsearchApi.java
Elasticsearch scaling_factor used format info, it's wrong. Fix this problem.
Fixes #4388 
Elasticsearch scaling_factor used format info, it's wrong.
Change scaling_factor uses correct information.
> [INLONG-4388][Manager] Change Elasticsearch scaling_factor use correct mapping info

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/LoadNode.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/MySqlLoadNode.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/MySqlLoadNodeTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/MySqlLoadSqlParseTest.java
> [INLONG-4383][Sort] Add MySQL data load support

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/LoadNode.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/OracleLoadNode.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/OracleLoadNodeTest.java
- inlong-sort/sort-connectors/jdbc/pom.xml
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/converter/AbstractJdbcRowConverter.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/converter/clickhouse/ClickHouseRowConverter.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/converter/oracle/OracleRowConverter.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/converter/sqlserver/SqlServerRowConvert.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/OracleDialect.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/SqlServerDialect.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDialects.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/OracleLoadSqlParseTest.java
- pom.xml
Fixes #4394 
I want to support data load to Oracle database.
It  support data load to Oracle database.
*(example:)*
> [INLONG-4394][Sort] Add Oracle data load support

- inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/group/result/AllBrokersOffsetRes.java
- inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/group/result/ConsumerInfoRes.java
- inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/group/result/GroupOffsetRes.java
- inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/group/result/OffsetPartitionRes.java
- inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/group/result/TopicOffsetRes.java
- inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/topic/request/DeleteGroupReq.java
- inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/TopicServiceImpl.java
> [INLONG-4392][TubeMQ] Optimize the method of querying the offset information of consumer groups on Broker

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Constants.java
- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/Entrance.java
- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/NativeFlinkSqlParser.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/NativeFlinkSqlParserTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/PostgresLoadNodeFlinkSqlParseTest.java
Fixes #4405 
sort support run sql script.
Add `NativeFlinkSqlParser` to parse SQL file.
In `Entrance` class, run SQL script by `--sql.script.file` configuration.
> [INLONG-4405][Sort] Support run SQL script

- inlong-sort/sort-connectors/jdbc/pom.xml
- pom.xml
Due to module splitting, dependencies need to be introduced separately into.
Fixes #4429 
Due to module splitting, dependencies need to be introduced separately into.
Modules that separate each connector.
Add sqlserver jdbc driver
*(example:)*
> [INLONG-4429][Sort] Add SQL Server JDBC driver and management version

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/LoadNode.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/GreenplumLoadNode.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/FunctionParam.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/GreenplumLoadNodeTest.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/GreenplumDialect.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDialects.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDynamicTableFactory.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/GreenplumLoadSqlParseTest.java
Fixes #4448 
I want to support data load to Greenplum database.
It support data load to Greenplum database.
*(example:)*
> [INLONG-4448][Sort] Add Greenplum database data load support

- inlong-tubemq/tubemq-docker/tubemq-all/Dockerfile
This reverts commit 4e340b639fd07c5f86d3754cb149a4002838019b.
Fixes #<xyz>
*(example:)* …
> [INLONG-4451][TubeMQ] Revert update the base docker image for TubeMQ

- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaFederationSink.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaFederationWorker.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaProducerCluster.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/FetchCallback.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSource.java
> [INLONG-4453][Sort-Standalone] Fix bug that report wrong audit when send to kafka failed

- inlong-sort/sort-dist/pom.xml
[INLONG-4491][Sort] Fix missing dependencies after packaging for sort-dist module
- Fixes #4491 
Fix `sort-dist` maven package lose dependencies.
1. remove `artifactSet` of `sort-dist pom`. 
2. set `createDependencyReducedPom` false.
sort-dist is a execute jar should set `createDependencyReducedPom` false.
wo can see the [discussion](https://stackoverflow.com/questions/22904573/what-is-the-purpose-of-dependency-reduced-pom-xml-generated-by-the-shade-plugin).
And [flink-dist](https://github.com/apache/flink/blob/master/flink-dist/pom.xml) set `createDependencyReducedPom` false too.
> [INLONG-4491][Sort] Fix missing dependencies after packaging for sort-dist module

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/mq/CreatePulsarGroupTaskListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/mq/CreatePulsarResourceTaskListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/mq/CreatePulsarSubscriptionTaskListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/mq/CreatePulsarTopicTaskListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/consumption/listener/ConsumptionCompleteProcessListener.java
> [INLONG-4468][Manager] Use the user-configured URL instead of the DNS of Pulsar

- inlong-dashboard/src/components/MetaData/StorageHive.tsx
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hive/HiveSinkRequest.java
- Fixes #4500 
Remove non-null restriction on hiveConfDir parameter, as the Sort module has no non-null restriction on this field.
> [INLONG-4500][Manager][Dashboard] Remove non-null restriction on hiveConfDir parameter

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
- Title Example: [INLONG-4497][Manager] Fix deleteGroup Async method in Client
- Fixes #4497 
*(example:)* …
> [INLONG-4497][Manager] Fix the method of asynchronously deleting the inlong group in the client

- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/config/ControllerExceptionHandler.java
[INLONG-4505][Manager] Improve the return information of validation rules
- Fixes #4505 
- Now the request's verification exception prompt only returns the first exception information. If multiple rules match, only the first one is returned, which is unreasonable.
- Remove some unnecessary annotations
- Remove some unnecessary annotations
- Return all exception information
> [INLONG-4505][Manager] Improve the return information of validation rules

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongGroupTransfer.java
- Title Example: [INLONG-4532][Manager] Fix group init method in Client
- Fixes #4532 
*(example:)* …
> [INLONG-4532][Manager] Fix init sort config error during initing group info in the client

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/InlongClusterInfo.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/InlongClusterRequest.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/dataproxy/DataProxyClusterInfo.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/dataproxy/DataProxyClusterRequest.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/pulsar/PulsarClusterDTO.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/pulsar/PulsarClusterInfo.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/pulsar/PulsarClusterRequest.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/tube/TubeClusterInfo.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/tube/TubeClusterRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/AbstractClusterOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/DataProxyClusterOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterOperatorFactory.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterService.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/PulsarClusterOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/TubeClusterOperator.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/ConsumptionServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/InlongClusterServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/InlongStreamServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/group/InlongGroupServiceTest.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/AgentController.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenClusterController.java
- Fixes #4541 
Support save extension params for inlong cluster.
Support saves, gets, and updates the extension params for inlong clusters through the factory design pattern.
For example, pulsar admin URL and tenant are extension params, they are not in the inlong_cluster table, this PR supports saving them into the ext_params.
`org.apache.inlong.manager.service.cluster.InlongClusterServiceTest`
> [INLONG-4541][Manager] Support save extension params for inlong cluster

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/FieldType.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/operation/InlongStreamProcessOperation.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
> [INLONG-1858][Manager] Fix hive add column bug

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/HiveLoadNode.java
- inlong-sort/sort-core/src/main/resources/log4j2.properties
An error occurs when the user omits an incoming version, data sink hive.
Alter log version module of sort core.
- Fixes #4591 
Test error.
Set default version 3.1.2.
Change log version  from log4j to log4j2.
*(example:)*
> [INLONG-4591][Sort] Set the default hive version and alter the log version from log4j to log4j2 in the sort core module

- conf/inlong.conf
- docker/docker-compose/docker-compose.yml
- docker/publish.sh
- inlong-agent/agent-docker/README.md
- inlong-audit/audit-docker/README.md
- inlong-dataproxy/dataproxy-docker/README.md
- inlong-manager/manager-docker/README.md
- inlong-tubemq/tubemq-docker/tubemq-all/README.md
- inlong-tubemq/tubemq-docker/tubemq-manager/README.md
- Fixes #4613
Change the tag of Docker images to 1.2.0-incubating.
Change the tag of Docker images to 1.2.0-incubating.
> [INLONG-4613][Release] Change the tag of Docker images to 1.2.0-incubating

- inlong-audit/conf/audit-proxy-pulsar.conf
- inlong-audit/conf/audit-proxy-tube.conf
- Fixes #4579 
*Adjust channel and sink configuration of audit-proxy
> [INLONG-4579][Audit] Delete redundant configuration in channel and sink

- inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/config/ElasticsearchConfig.java
- inlong-audit/conf/application.properties
- [INLONG-4594][Audit] Make Elasticsearch authentication configurable
- Fixes #4594 
- make Elasticsearch authentication configurable
- support es cluster with multi hosts
*(example:)*
- If a feature is not applicable for documentation, explain …
> [INLONG-4594][Audit] Make Elasticsearch authentication configurable

- inlong-distribution/src/main/assemblies/release.xml
Improve the packaging operation.
- Fixes #4624 
*(example:)*
> [INLONG-4624][Sort] Package pulsar and hive connectors to same file

- inlong-sort/sort-connectors/hbase/pom.xml
- Fixes #4638 
Remove the dependency of spotbugs-annotations.
The License of spotbugs-annotations is GPL, it's not suitable in the Apache open source projects.
> [INLONG-4638][Sort] Remove the dependency of spotbugs-annotations

- inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/group/GroupController.java
- inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/group/request/BatchDeleteGroupReq.java
- inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/TopicServiceImpl.java
- inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/TubeConst.java
… and batch delete authorized consumer group
- Fixes #4551
Batch delete consumer groups and authorized consumer groups from the blacklist.
> [INLONG-4551][TubeMQ] Batch delete consumer groups and authorized consumer groups from the blacklist

- .github/workflows/ci_build.yml
- .github/workflows/ci_chart_test.yml
- .github/workflows/ci_check_license.yml
- .github/workflows/ci_docker.yml
- .github/workflows/ci_ut.yml
Fixes #4653
Add concurrency support on GitHub Actions
Add concurrency support on GitHub Actions.
See https://docs.github.com/en/actions/using-jobs/using-concurrency for more information.
> [INLONG-4653][CI] Add concurrency support on GitHub Actions

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/common/AgentThreadFactory.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/AgentUtils.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/ThreadUtils.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/Job.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobManager.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskManager.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskPositionManager.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/trigger/TriggerManager.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/snapshot/BinlogSnapshotBase.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/trigger/DirectoryTrigger.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/trigger/PathPattern.java
- inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/TestOOMExit.java
- inlong-agent/conf/agent.properties
- [INLONG-4535][Agent] Support configurable automatic exit function when OOM happens
- Fixes #4535 
- Generally, the occurrence of OutOfMemoryError means that agent won't run and collect data as ususal. To solve this problem and avoid human manipulation , we let agent supports automatically exit when OOM happens. Therefore, users can use scripts or other detection tools to monitor whether agent exits and restarts it if necessary.
- If "agent.enable.oom.exit" parameter is set as "true" in agent.properties, agent will automatically exit when OutOfMemoryError happens. 
*(Please pick either of the following …
> [INLONG-4535][Agent] Support configurable automatic exit function when OOM happens

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/ExtractNodeUtils.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/MongoExtractNode.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/MongoExtractNodeTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/MongoExtractFlinkSqlParseTest.java
- Fixes #4665 
The primary key must be _id in MongoDB CDC Connector
modify the MongoExtractNode constructor
> [INLONG-4665][Sort] The primary key must be _id in mongoDB CDC Connector

- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DataTypeConvertSqlParseTest.java
Title: [INLONG-4685][Sort] Add data type convert implicitly support
- Fixes #4685 
Add data type convert implicitly support.
Data type convert implicitly will be supportted.
*(example:)* …
> [INLONG-4685][Sort] Add data type convert implicitly support

- inlong-manager/manager-client/pom.xml
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/AuthInterceptor.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongGroupApi.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongStreamApi.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/StreamSinkApi.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/StreamSourceApi.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/StreamTransformApi.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/WorkflowApi.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/util/JsonUtils.java
- licenses/inlong-manager/LICENSE
- pom.xml
- Fixes #4674 
The previous implementation of the client is not particularly good
1. The authentication information of the user's login is spliced ​​in the path each time
2. Param and PathVariable are manually spliced ​​together, and the scalability is not good
3. All the request methods for connecting to the web are all in one class
4. The previous execution of the http request package is not concise enough
1. The processing of authentication information is placed in the interceptor, and then if the authentication information is replaced by a header, it only needs to be modified here
2. The method of client requesting web controller is divided according to business, corresponding to the web aspect, which is convenient for maintenance and search
3. Use declarative annotations to simplify …
> [INLONG-4674][Manager] Refactor the client by using the Retrofit framework

- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DataTypeConvertSqlParseTest.java
- inlong-sort/sort-formats/format-base/src/main/java/org/apache/inlong/sort/formats/base/TableFormatUtils.java
- Title Example: [INLONG-4730][Sort] Fix meta field format is null when parse json to sql
- Fixes #4730 
Fix meta field format is null when parse json to sql
modify UT  `DataTypeConvertSqlParseTest`
add exception detail for TableFormatUtils
modify `parseFieldRelations` of FlinkSqlParser
> [INLONG-4730][Sort] Fix meta field format is null when parse json to sql

- inlong-tubemq/tubemq-client-twins/tubemq-client-go/README.md
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/consumer.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/heartbeat.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/codec/tubemq_codec.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/codec/tubemq_codec_test.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/config/config.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/example/consumer.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/example/multi_routine_consumer.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/flowctrl/handler.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/flowctrl/item.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/go.mod
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/metadata/node.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/metadata/partition.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/metadata/subscribe_info.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/multiplexing/multiplexing.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/multiplexing/multlplexing_test.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/remote/remote.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/rpc/broker.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/rpc/client.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/rpc/master.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/selector/selector.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/sub/info.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/sub/info_test.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/tdmsg/bin_msg.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/tdmsg/td_msg.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/transport/client.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/util/util.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-python/setup.py
> [INLONG-4721][TubeMQ] Remove the "incubat*" tag in the tubemq-go-sdk code

- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DecimalFormatSqlParseTest.java
- inlong-sort/sort-formats/format-base/src/main/java/org/apache/inlong/sort/formats/base/TableFormatUtils.java
- inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/common/DecimalFormatInfo.java
- inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/common/TimeFormatInfo.java
- inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/common/TypeInfo.java
- Title: [INLONG-4735][Sort] Add precision support for DecimalFormatInfo, TimeFormatInfo
Fixes #4735 
Add precision support for DecimalFormatInfo, TimeFormatInfo
The precision configuration of DecimalFormatInfo, TimeFormatInfo will be supported.
*(example:)* …
> [INLONG-4735][Sort] Add precision support for DecimalFormatInfo, TimeFormatInfo

- inlong-sort/pom.xml
- inlong-sort/sort-connectors/iceberg/pom.xml
[INLONG-4732][Sort] Iceberg commit hive catalog table failed because table not found
- Fixes #4732 
fix iceberg hive Compatibility issues
> [INLONG-4732][Sort] Fix Iceberg commit Hive catalog table not found

- README.md
- Fixes #4758
In convenience of coping and pasting for users, command line codes in READEME should remove leading $ sign. take [kafka](https://github.com/apache/kafka) for example, there is no leading $ sign before the codes in kafka READEME.md
Removed  leading $ sign in README.md
*(example:)*
- Does this pull request introduce a new feature? (yes / **no**)
- If a feature is not documented yet in this PR, please create …
> [INLONG-4758][Doc] Remove leading $ sign in README.md

- .github/workflows/ci_build.yml
- .github/workflows/ci_chart_test.yml
- .github/workflows/ci_check_license.yml
- .github/workflows/ci_docker.yml
- .github/workflows/ci_ut.yml
Reverts apache/inlong#4654
because it will affect docker image build and cancel the running workflow.
> [INLONG-4653][Revert] Add concurrency support on GitHub Actions

- .github/workflows/ci_docker.yml
Fixes #4769
Now, if only the source codes are changed, the docker workflow won't be triggerd.
If the source codes are changed, the docker workflow should be triggered when pushing them, and not in a pull request.
In a pull request. the docker workflow is only triggered when the build files are changed.
In a pushed commit, changes to the source codes or build files will both trigger the docker workflow.
So, if you just changed the source codes, the docker workflow will not be triggered in you pull request, but it will be triggered when your pull request is merged.
```yaml
on:
push:
paths:
- '.github/workflows/ci_docker.yml'
- '**/pom.xml'
- 'inlong-agent/**'
- 'inlong-audit/**'
- 'inlong-common/**'
- 'inlong-dashboard/**'
- 'inlong-dataproxy/**'
- 'inlong-distribution/**'
- …
```
> [INLONG-4769][CI] Fix error trigger condition in the docker workflow

- inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/processor/ServiceTaskProcessor.java
- Fixes #4766
When the complete request is fired directly from client the action context is already built.
> [INLONG-4766][Manager] Fix workflow NP problem when the COMPLETE request is fired directly from client

- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/AckPolicy.java
- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/CommonPropertiesHolder.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/channel/BufferQueueChannel.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/channel/CacheMessageRecord.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/channel/ProfileEvent.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsSinkContext.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSinkContext.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/FetchCallback.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/cls/TestDefaultEvent2LogItemHandler.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsSinkContext.java
- Title: [INLONG-4777][SortStandalone] SortStandalone change ack policy: from checking message count to checking every message.
- Fixes #4777 
*(example:)* …
> [INLONG-4777][SortStandalone] Change ack policy from checking message count to checking every message

- docker/docker-compose/docker-compose.yml
- docker/kubernetes/templates/manager-statefulset.yaml
- docker/kubernetes/values.yaml
- inlong-manager/manager-docker/manager-docker.sh
[Improve][Kubernets] Add flink configure in k8s yaml
- Fixes #4827 
Add flink configure in k8s yaml.
Get env from yaml to change inlong-manager/plugins/flink-sort-plugin.properties flink hostname and port.
Add flink configure in k8s yaml.
Get env from yaml to change inlong-manager/plugins/flink-sort-plugin.properties flink hostname and port.
> [INLONG-4827][Kubernets] Add Flink config into the YAML files

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
- Fixes #4834 
*After deleting the data_proxy cluster config, the data_proxy node under it was not deleted*
> [INLONG-4834][Manager] After deleting the data_proxy cluster config, the data_proxy node under it was not deleted

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/tube/TubeClusterDTO.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/tube/TubeClusterInfo.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/tube/TubeClusterRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/TubeClusterOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/mq/util/TubeMQOperator.java
Add Manager configuration parameters to Tube.
- Fixes #4843 
Task configuration succeeded.
Add RPC Url
*(example:)*
> [INLONG-4843][Manager] Add RPC URL for TubeMQ cluster 

- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DataTypeConvertSqlParseTest.java
- [INLONG-4815][Sort] Supporting field type cast when sinking data to HBase
- Fixes #4815 
Supporting field type cast when sinking data to HBase.
* Modify FlinkSqlParser generate sql for HBase 
* Add UT for type cast
> [INLONG-4815][Sort] Supporting field type cast when sinking data to HBase

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/ck/ClickHouseSink.java
Modify the ClickHouse Sink configuration to make the saved configuration consistent with the query
- Fixes #4880
> [INLONG-4880][Manger] Modify the ClickHouse configuration to make the saved info consistent with the query

- inlong-sort/sort-connectors/elasticsearch-6/pom.xml
- inlong-sort/sort-connectors/elasticsearch-7/pom.xml
- inlong-sort/sort-connectors/hbase/pom.xml
- inlong-sort/sort-connectors/hive/pom.xml
- inlong-sort/sort-connectors/iceberg-dlc/pom.xml
- inlong-sort/sort-connectors/iceberg/pom.xml
- inlong-sort/sort-connectors/jdbc/pom.xml
- inlong-sort/sort-connectors/kafka/pom.xml
- inlong-sort/sort-connectors/mongodb-cdc/pom.xml
- inlong-sort/sort-connectors/mysql-cdc/pom.xml
- inlong-sort/sort-connectors/oracle-cdc/pom.xml
- inlong-sort/sort-connectors/postgres-cdc/pom.xml
- inlong-sort/sort-connectors/pulsar/pom.xml
- inlong-sort/sort-connectors/sqlserver-cdc/pom.xml
[INLONG-4892][Sort] Sort connector package without own java SPI 'Factory' file
- Fixes #4892 
It is clear thar connector own 'META-INF/services/org.apache.flink.table.factories.Factory' has not been packaged. So just package it.
> [INLONG-4892][Sort] Sort connector package without own Factory files

- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClientConfig.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSource.java
- Title: [INLONG-4884][SortSDK] Fix data duplicated problem when default ackTimeout value of Pulsar consumer is 0
- Fixes #4884 
*(example:)* …
> [INLONG-4884][SortSDK] Fix data duplicated problem when default ackTimeout value of Pulsar consumer is not 0

- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterEntityMapper.java
- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongGroupEntityMapper.java
- inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
- Fixes #4874
Cascade modification of associated data when modifying or deleting cluster tag.
Modify or delete the cluster tag, if there are some InlongGroups that use this tag, an exception will be thrown and those InlongGroupIds using this cluster tag will be returned.
If there is no InlongGroup using this tag, modify/delete the tag and modify/delete the tag associated with other clusters.
> [INLONG-4874][Manager] Cascade modification of associated data when modifying or deleting cluster tag

- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/web/AbstractWebHandler.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/web/BrokerAdminServlet.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/webbase/WebMethodMapper.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/AbstractWebHandler.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebOtherInfoHandler.java
> [INLONG-4924][TubeMQ] Add admin_get_methods method

- inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkService.java
- inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/enums/ConnectorJarType.java
- Fix #4915
1. The pulsar source jar selector enum is missing. Add it so the jars are correctly selected when the Pulsar is used as the source node.
2. The current job submits implementation requires the dependent jars to be all present on the Flink node. This is not convenient when the Flink nodes are different from the manager nodes:
Rather than placing jars before the job submits, it's more flexible and straightforward to just upload the dependent connectors with the job jar:
Pros:   Easy to use. Less concern about jar management.  New connectors are supported anytime.
Cons:  Need to upload more files thus extra network overhead.
> [INLONG-4915][Manager] Add Pulsar source type and improve connector jar discovery mechanism

- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/web/BrokerAdminServlet.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/utils/WebParameterUtils.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebAdminGroupCtrlHandler.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebOtherInfoHandler.java
> [INLONG-4934][Bug] Reversed value for admin_enable_stats methods

- .github/workflows/ci_docker.yml
- docker/build-docker-images.sh
- docker/publish-by-arch.sh
[INLONG-4910][CI] Build arm images only on release branch
- Fixes #4910 
Rebuild ci_docker steps to make arm images only build with release branch.
Rebuild ci_docker steps to make arm images only build with release branch.
> [INLONG-4910][CI] Build arm images only on the release branch

- inlong-distribution/src/main/assemblies/sort-connectors.xml
- inlong-sort/sort-connectors/pom.xml
- inlong-sort/sort-connectors/tubemq/pom.xml
- inlong-sort/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java
- inlong-sort/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/DynamicTubeMQDeserializationSchema.java
- inlong-sort/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQDynamicTableFactory.java
- inlong-sort/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQOptions.java
- inlong-sort/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQTableSource.java
- inlong-sort/sort-connectors/tubemq/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- inlong-sort/sort-core/pom.xml
feature: Add TubeMQ connector
1.It can be used through the Flink Table API and SQL.
2.This feature currently supports only reads.
TubeMQ introduce：https://inlong.apache.org/docs/next/modules/tubemq/overview
- Fixes #4890 
1.Extend support for MQ types.
2.Use the large-scale data capabilities of TubeMQ.
1.Add TubeMQ consumers .
2.Extend Flink's dynamic table.
> [INLONG-4890][Sort] Support TubeMQ connector

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sortstandalone/SortSourceClusterInfo.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sortstandalone/SortSourceGroupInfo.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sortstandalone/SortSourceStreamInfo.java
- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterEntityMapper.java
- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongGroupEntityMapper.java
- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSinkEntityMapper.java
- inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortClusterServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/SortServiceImplTest.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java
- Fixes #4178
In order to support new db model and reduce the number of query to database, the interface of sort sdk config management should be refactored.
One cluster can register multiple tasks, each task represents one flow from mq to downstream sink, and each task can register multiple InlongGroupId.
Use local cache to maintain _**SortSourceConfigResponse**_ of all tasks.
Reload all configs each 10 seconds.
Main step:
1. Get all streams, and group them to by cluster and task
2. Get all inlong groups, and group them by groupId
3. Get all clusters, and group by cluster tag
4. Prepare CacheZones for each cluster and task
- Empty request params
- Wrong request params
- Same md5
- Corret …
> [INLONG-4178][Manager]  Refactor getSortSource API for Sort Standalone

- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/metrics/PluginPrometheusMetric.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/metrics/SinkPrometheusMetric.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/metrics/SourcePrometheusMetric.java
- [INLONG-4998][Agent] Create PrometheusMetric repeatedly
- Fixes #4998 
*(example:)* …
> [INLONG-4998][Agent] Avoid to create PrometheusMetric repeatedly

- inlong-common/src/main/java/org/apache/inlong/common/enums/TaskTypeEnum.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SourceType.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/tubemq/TubeMQSource.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/tubemq/TubeMQSourceDTO.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/tubemq/TubeMQSourceRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/SortConfig4NormalGroupOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/ExtractNodeUtils.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/tubemq/TubeMQSourceOperator.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/source/TubeMQSourceServiceTest.java
This feature adds support for Tubes as data sources.
- Fixes #5018 
Data source TubeMQ are supported and can be consumed by Sort.
1.Update SortConfig4NormalGroupOperator
2.Add TubeMQ source bean and request
*(example:)*
> [INLONG-5018][Manager] Support for Tube data sources

- .github/ct.yml
- docker/kubernetes/templates/agent-statefulset.yaml
- docker/kubernetes/templates/dataproxy-statefulset.yaml
- docker/kubernetes/templates/mysql-pvc.yaml
- docker/kubernetes/templates/mysql-statefulset.yaml
- docker/kubernetes/templates/tubemq-broker-statefulset.yaml
- docker/kubernetes/templates/tubemq-master-statefulset.yaml
- docker/kubernetes/templates/zookeeper-statefulset.yaml
- docker/kubernetes/values.yaml
Divide persistentVolumeClaim by statefulsets
- Fixes #4977 
Divide persistentVolumeClaim by statefulsets
Divide persistentVolumeClaim by statefulsets
1、Divide persistentVolumeClaim by statefulsets
2、Add dataproxy persistentVolumeClaim and agent persistentVolumeClaim
> [INLONG-4977][Kubernetes] Divide persistentVolumeClaim by statefulsets

- inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/core/impl/TaskServiceImpl.java
- Fixes #5052
Ensure that the re executed workflow will no longer behave as successful execution and go to the next step in the case of failure
Add  listeners for workflowtask on the interface where you click execute again
> [INLONG-5052][Manager] The workflow that failed to execute still failed, but returned success

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongStream.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/StreamSinkApi.java
- inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClientTest.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/mysql/MySQLSink.java
- Fixes #5007
The Web already has an interface, but there is no corresponding interface on the client side
- Add the method that Client can query the details of the sink through the Id or Name of the sink
- org.apache.inlong.manager.client.api.inner.InnerInlongManagerClientTest#testGetMysqlSinkInfo
> [INLONG-5007][Manager] Client supports getting sink details by id

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/AgentUtils.java
- inlong-agent/agent-common/src/test/java/org/apache/inlong/agent/db/TestRocksDbImp.java
- inlong-agent/agent-common/src/test/resources/binlogJob.json
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/conf/ConfigJetty.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobManager.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java
- inlong-dashboard/package-lock.json
- [INLONG-5054][Agent] Fix Agent can not import old job after reboot due to inconsistent prefix
- Fixes #5054 
when store single jobProfile into local db, add prefix “job_” with the job id
*(example:)* …
> [INLONG-5054][Agent] Fix Agent can not import old job after reboot due to inconsistent prefix

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/SourceRequest.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/StreamSource.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/file/FileSourceDTO.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceDTO.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/mongodb/MongoDBSourceDTO.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/mysql/MySQLBinlogSourceDTO.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/oracle/OracleSourceDTO.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/postgresql/PostgreSQLSourceDTO.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/pulsar/PulsarSourceDTO.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/sqlserver/SQLServerSourceDTO.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/tubemq/TubeMQSourceDTO.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/ExtractNodeUtils.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/source/StreamSourceServiceTest.java
Title: [INLONG-5070][Manager] Add more parameter settings support for stream source
Fixes #5070 
Add more parameter settings support for stream source. At present, each connector on the sort-connectors side supports a large number of parameter settings, but the manager only exposes a small part of them, so the manager also needs to expose related parameter settings.
The stream source will add proprerties field for setting more parameter.
*(example:)*
- *Extended …
> [INLONG-5070][Manager] Add more parameter settings support for stream source

- inlong-tubemq/tubemq-manager/sql/apache_tube_manager.sql
- Fixes #5087 
In MySQL 5.7, I initialize the database through sql/apache_tube_manager.sql in the inlong-tubemq-manager directory.
The following error occurred：
ERROR 1273 (HY000): Unknown collation: 'utf8mb4_0900_ai_ci'
> [INLONG-5087][TubeMQ] Fix initialize the database failure in MySQL 5.7

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortClusterServiceImpl.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/SortServiceImplTest.java
[INLONG-5051] getSortCluster API allows a cluster with empty task
- Fixes #5051
The case that sort-standalone request a cluster, which has empty config, should be considered as success.
To prevent the case that the last stream of this cluster is deleted, and sort-standalone recevied a non success response, it will not stop the consumption of this stream case the response code is not success.
- Does this pull request introduce a new feature?  yes
> [INLONG-5051][Manager] Get Sort cluster allows a cluster with an empty tasks

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
[INLONG-5088][Manager]  SortSource Service support only consume the MQ cluster with the same tag
- Fixes #5088 
Current getSortSource API will return all the stream of the given task, without consider whether the MQ cluster of these streams match the task or not.
SortSource Service support only consume the MQ cluster with the same tag
SortServiceImplTest
> [INLONG-5088][Manager] Support only consumes the MQ cluster with the same tag

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaOffset.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSource.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceDTO.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/ExtractNodeUtils.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/KafkaConstant.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/enums/KafkaScanStartupMode.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNode.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNodeTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DataTypeConvertSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DecimalFormatSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DistinctNodeSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/FlinkSqlParserTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/FullOuterJoinSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/InnerJoinRelationSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/KafkaSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/LeftOuterJoinSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/MetaFieldSyncTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/RightOuterJoinSqlParseTest.java
- [INLONG-5074][Sort] KafkaExtractNode support more StartupMode
- Fixes #5074 
KafkaExtractNode supports consumption from specified partitions and offsets
- *org.apache.inlong.sort.parser.KafkaSqlParseTest*
> [INLONG-5074][Sort] KafkaExtractNode support more StartupMode

- docker/docker-compose/docker-compose.yml
- docker/kubernetes/templates/manager-statefulset.yaml
- docker/kubernetes/values.yaml
- inlong-manager/manager-docker/Dockerfile
- inlong-manager/manager-docker/manager-docker.sh
- Fixes #5104
*(example:)*
- If a …
> [INLONG-5104][Docker] Update flink address environment for Flink sort plugin

- inlong-sort/sort-formats/format-inlongmsg-pb/pom.xml
- inlong-sort/sort-formats/format-inlongmsg-pb/src/main/java/org/apache/inlong/sort/formats/inlongmsgpb/InLongMsgPbDecodingFormat.java
- inlong-sort/sort-formats/format-inlongmsg-pb/src/main/java/org/apache/inlong/sort/formats/inlongmsgpb/InLongMsgPbDeserializationSchema.java
- inlong-sort/sort-formats/format-inlongmsg-pb/src/main/java/org/apache/inlong/sort/formats/inlongmsgpb/InLongMsgPbFormatFactory.java
- inlong-sort/sort-formats/format-inlongmsg-pb/src/main/java/org/apache/inlong/sort/formats/inlongmsgpb/InLongMsgPbOptions.java
- inlong-sort/sort-formats/pom.xml
[INLONG-4806][Sort] Sort support consume pb message
- Fixes #4806
- Fixes #4807
Sort do not support deserialize inlong pb msg format
The inner csv format will thow exception when the real field size exceeds the excepted one.
Sort support InlongMsg pb format.
Support Csv inner format ignore tailing unmappable.
*(example:)*
- If a feature is not documented yet …
> [INLONG-4806][Sort] Sort support InlongMsg pb format

- inlong-manager/manager-plugins/pom.xml
- inlong-manager/manager-web/pom.xml
- licenses/inlong-manager/LICENSE
1.Task error, failed to create Hive Metastore client.
2.Dependency error.
- Fixes #4948 
1.Please confirm startup hiveserver2 and metastore service.
2.Put hive-site.xml to HDFS.
3.Hive config information
4.hive-site.xml example.
Notice: If an error is still reported, please add HIVE_HOME environment.
This configuration will be improved in the future.
Update dependency.
- [ x] This change is a trivial rework/code cleanup without any test coverage.
*(example:)* …
> [INLONG-4948][Manager] Failed to create Hive Metastore client

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sortstandalone/SortSourceGroupInfo.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/SortServiceImplTest.java
- Fixes #5127 
Rename second_xxx to backup_xxx in sort-standalone management interface
Rename second_xxx to backup_xxx in sort-standalone management interface
*(example:)*
> [INLONG-5127][Manager] Rename second_xxx to backup_xxx in sort-standalone management interface

- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/rollback/TimeBasedFilterInterceptor.java
- Fixes #5094
Implements time interval interceptor to support Sort-standalone rollback sender
Implements time interval interceptor
*(example:)*
> [INLONG-5094][SortStandalone]  Implements time interval interceptor

- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/utils/FlumeConfigGenerator.java
- Fixes #5117
Current config loading strategy restricts the flexibility of sort-standalone by naming the only type of components in config file. Which means one sort-standalone node can only support a series of tasks with the same type of sink.
By specify this params into SortTask, the sort-standalone will be decoupled from node to task.
allow sort-standalone get type of components from remote config
*(example:)*
- If a …
> [INLONG-5117][SortStandalone] Support specify component type from remote config

- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/FileCallback.java
- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/EncryptConfigEntry.java
- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ProxysdkException.java
- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/TimeScanObject.java
- Fixes #5161
*(example:)*
- If a …
> [INLONG-5161][SDK] Remove the redundant annotation for the author

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/DefaultSortConfigOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/LoadNodeUtils.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/NodeRelationUtils.java
- Fixes #5157
Failed to build Sort config as the relations are empty.
Create Sort StreamInfo for Lightweight mode and Standard mode.
> [INLONG-5157][Manager] Fix failed to build Sort config as the relations are empty

- .github/workflows/ci_build.yml
- .github/workflows/ci_docker.yml
- .github/workflows/ci_ut.yml
- .github/workflows/codeql_analysis.yml
- Fixes #5098 
CI build takes a long time to execute, and the speed can be improved by Maven parallel compilation
maven execution parameters
we can refer this, https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3
> [INLONG-5098][CI] Use maven parallel build feature to improve project workflow build speed

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sortstandalone/SortSourceStreamInfo.java
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
- inlong-sort/pom.xml
- Fixes #5165
The TopicProperties in SortSourceConfig, which is used to config sort sdk, collects wrong topic properties.
The correct topic properties of each stream should be maintain by ext_params in Stream_Sink , instead of Inlong_Group
SortServiceImplTest
> [INLONG-5165][Manager] Getting Sort source collects wrong topic properties of each stream

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CommonConstants.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/FetcherConstants.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/HttpManager.java
- inlong-agent/agent-core/src/test/resources/agent.properties
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java
- inlong-agent/agent-plugins/src/test/resources/agent.properties
- inlong-agent/conf/agent.properties
- inlong-common/src/main/java/org/apache/inlong/common/util/BasicAuth.java
- inlong-dataproxy/conf/common.properties
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/AuthUtils.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/RemoteConfigManager.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/ConfigConstants.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/auth/InlongShiro.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/UserServiceImpl.java
- inlong-manager/manager-web/sql/apache_inlong_manager.sql
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/ShiroConfig.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/impl/InlongShiroImpl.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/openapi/OpenAPIAuthenticatingRealm.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/openapi/OpenAPIFilter.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/openapi/SecretToken.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/web/AuthenticationFilter.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/web/WebAuthorizingRealm.java
- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ConfigConstants.java
- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java
- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java
- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/HttpClientExample.java
- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/TcpClientExample.java
- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ServiceDiscoveryUtils.java
- Fixes #5167
The Manager's Open APIs are free to call from anywhere anonymously, which is not secure.
Some sort of authentication support is needed to very the identity of the clients (i.e. authorized Agent/DataProxy/SDK, etc.).
- Open API basic auth integration with Apache Shiro.
- Client component basic auth header added.
- Default secretId & secretKey pair configuration to keep the suite ready to go out of the box.
(User should replace with their own if they care)
There are several ways to provide web API authentication, with the typical two described below:
See at: https://en.wikipedia.org/wiki/Basic_access_authentication  or [rfc7617](https://www.rfc-editor.org/rfc/rfc7617)
The auth process is simple:
A) The API server side creates a secretID & secretKey pair for each client who …
> [INLONG-5167][Manager][Agent][Dataproxy][SDK] Manager open API authentication support

- pom.xml
- Fixes #5182
The current version 0.13 does not support parallel builds, a warning message will appear
After the plugin is upgraded, it can support parallel builds
apache-rat-plugin version 0.13 -> 0.14
https://creadur.apache.org/rat/apache-rat-plugin/rat-mojo.html
> [INLONG-5182][CI] Upgrade apache-rat-plugin to compatible with parallel builds

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongClientImpl.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongClusterClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongClusterApi.java
- inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/ClusterInfo.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/ClusterNodeResponse.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/ClusterTagResponse.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/pulsar/PulsarClusterInfo.java
- Fixes #4931 
Supplement the api that the manager web has but the client does not have.
Supplement inlong cluster api in manager client.
org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java
> [INLONG-4931][Manager] Supplement inlong cluster API in manager client

- inlong-manager/manager-dao/src/main/resources/mappers/ConsumptionEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/DataNodeEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterNodeEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterTagEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/StreamTransformEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/UserEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/WorkflowApproverEntityMapper.xml
- inlong-manager/manager-dao/src/test/java/org/apache/inlong/manager/dao/mapper/InlongGroupEntityMapperTest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/AbstractClusterOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ConsumptionServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/DataNodeServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongStreamServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/UserServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/WorkflowApproverServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/AbstractGroupOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/AbstractSinkOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/StreamTransformServiceImpl.java
- Fixes #5188 
1、Make sure to create group workflow success.
2、Remove redundant parameter settings
When inserting data, the service layer will no longer set creatTime, modifyTime, isDeleted and version,
but let the database generate automatically
org.apache.inlong.manager.service.cluster.InlongClusterServiceTest
> [INLONG-5188][Manager] Fix the error of creating group workflow and remove redundant settings

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/DLCIcebergLoadNode.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/IcebergLoadNode.java
- inlong-sort/sort-connectors/iceberg-dlc/pom.xml
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/FlinkCatalog.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/FlinkCatalogFactory.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/FlinkConfigOptions.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/FlinkDynamicTableFactory.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/IcebergTableSink.java
- inlong-sort/sort-connectors/iceberg/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- licenses/inlong-sort-connectors/LICENSE
- Fixes #5131 
iceberg/dlc does not support CDC sink, so we could give an option to regard all changelog data as insert-only data. So we can insert into iceberg/dlc from canal-json，rowkind as an iceberg schema field.
add a canal json option to support insert-only mode
*(example:)* …
> [INLONG-5131][Sort] Import all changelog mode data ingest into Iiceberg or DLC

- inlong-tubemq/tubemq-manager/bin/init-tube-cluster.sh
> [INLONG-5215][TubeMQ] Fix execution error of init-tube-cluster.sh script

- inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/DataProxyConfigRequest.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/RemoteConfigManager.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/HttpUtils.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java
- Fixes #5197 
The usage of get or post seems to be not quite in line. After discussion with heal we decide to unify open api request method to POST.
> [INLONG-5197][Manager] Unify the HTTP request method of the OpenAPI query interface from GET to POST

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/NodeRelationUtils.java
- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/UnionSqlParseTest.java
Title: [INLONG-5152][Sort] Add union parse support for FlinkSqlParser
Fixes #5152 
I want to add union parse support for FlinkSqlParser. Because the usage scenarios of sub-database and sub-tables can be processed through union, and the data reconciliation of such scenarios can be solved at the same time.
FlinkSqlParser will supports parsing union node relation.
*(example:)*
- Does this pull request …
> [INLONG-5152][Manager][Sort] Add union parse support for FlinkSqlParser

- inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/sink/TestPulsarSink.java
- inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/sink/TestTubeSink.java
- Fixes https://github.com/apache/inlong/issues/5192
Add test for tube sink. KafkaSink has not been implemented yet, so test TubeSink first.
Add test for tube sink. KafkaSink has not been implemented yet, so test TubeSink first.
> [INLONG-5192][DataProxy] Add unit test for TubeMQ sink

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
- Fixes #5246 
Ensure that the agent can get the dataproxy node.
Return all cluster nodes under the same cluster tag and type to the agent instead of return first.
*(example:)*
> [INLONG-5246][Manager] Return all cluster nodes under the same tag and type

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/SinkContext.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/kafkazone/KafkaZoneSinkContext.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsarzone/PulsarZoneSinkContext.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/tubezone/TubeZoneSinkContext.java
- Fixes https://github.com/apache/inlong/issues/5238
Fix error metric params in PulsarZoneSinkContext::addSendFailMetric.
Fix error metric params in PulsarZoneSinkContext::addSendFailMetric.
> [INLONG-5238][DataProxy] Error metric params in addSendFailMetric

- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/RpcConstants.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/netty/NettyClient.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/netty/NettyClientFactory.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/netty/NettyProtocolDecoder.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/netty/NettyProtocolEncoder.java
- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/netty/NettyRpcServer.java
- inlong-tubemq/tubemq-core/src/test/java/org/apache/inlong/tubemq/corerpc/netty/NettyProtocolEncoderTest.java
Fix the protocol from 1.1.0 and later is not smoothly compatible with previous versions
- Fixes #5097
*(example:)* …
> [INLONG-5097][TubeMQ] Keep the protocol compatible with previous versions

- inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/heartbeat.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/rpc/client.go
- inlong-tubemq/tubemq-client-twins/tubemq-client-go/util/util.go
- Fixes #5281 
Reconnect to tubemq server if StandbyException is thrown
if StandbyException is returned from the tubemq server, try to reconnect to the another master.
*(example:)*
- Does this …
> [INLONG-5281][TubeMQ] Reconnect to tubemq server if StandbyException is thrown

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/OrderFieldEnum.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/OrderTypeEnum.java
- inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/common/PageRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java
- Title Example: [INLONG-5285][Manager] Support custom query for group, stream, source and sink
- Fixes #5285 
*Support custom query for group, stream, source and sink*
*When querying group, stream, source or sink, it should support custom query by field.*
> [INLONG-5285][Manager] Support custom query for group, stream, source and sink

- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/LoadNodeUtils.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/ClickHouseLoadNode.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/ClickHouseLoadNodeTest.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDialects.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/ClickHouseSqlParserTest.java
- inlong-sort/sort-end-to-end-tests/pom.xml
- inlong-sort/sort-end-to-end-tests/src/test/java/org/apache/inlong/sort/tests/ClickHouseCase.java
- inlong-sort/sort-end-to-end-tests/src/test/resources/flinkSql/clickhouse_test.sql
Handling exceptions: please declare primary key for sink table when query contains update/delete record.
- Fixes #4814 
Briefly describe ideas
1. The problem is that with flink JDBC SQL you have to specify the primary key.
2. When the Sort module sees the processing of primaryKey, it should be a problem with the parameters in the node. Gotta go check it out
3. Debug test locates that the primaryKey in the file read by sort is indeed empty
4.  To query the source of assignment of GroupInfo.StreamInfo.nodes, there are only CreateSortConfigListenerV2 and CreateStreamSortConfigListener classes, and they are both created by the createNodesForStream() method.
5. Test after bug fixes
> [INLONG-4814][Sort][Manager] Declare the primary key for sink table when the query contains update/delete

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongStream.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/StreamSourceClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/StreamSourceApi.java
- inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java
- Fixes #4929 
Add get stream source by id API  in manager client.
org.apache.inlong.manager.client.api.inner.ClientFactoryTest#testGetStreamSourceById
> [INLONG-4929][Manager] Add stream source API in Manager client

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/InLongMetric.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/InlongMetric.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/HBaseConstant.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/PostgresConstant.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/MySqlExtractNode.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/PostgresExtractNode.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/HbaseLoadNode.java
- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java
Title: [INLONG-5312][Sort] Add unified inlong.metric parameter injection support for nodes
Fixes #5312 
At present, many connectors support indicator reporting, but we have not added relevant metric reporting parameters at the entrance. And so, I add unified `inlong.metric` parameter injection support for nodes.
The metric parameter `inlong.metric` will be added to the node options auto if it has implemented the interface InLongMetric.
*(example:)*
- *Extended …
> [INLONG-5312][Sort] Add unified inlong.metric parameter injection support for nodes

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
- Fixes #5335 
Unserialize baseSortConfig in InlongGroupInfo which needed in workflow.
*(example:)* …
> [INLONG-5335][Manager] Unserialize Sort config when getting GroupInfo

- inlong-sort/sort-connectors/connector-base/src/main/java/org/apache/inlong/sort/base/metric/ThreadSafeCounter.java
- inlong-sort/sort-connectors/connector-base/src/test/java/org/apache/inlong/sort/base/metric/ThreadSafeCounterTest.java
- inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/sink/HBaseSinkFunction.java
- Fixes #5169 
* Fix race condition issue of HBaseSinkFunction metric collection
- If yes, how is the feature documented? (not applicable)
> [INLONG-5169][Sort] Fix race condition issue of HBaseSinkFunction metric collection

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CommonConstants.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/KubernetesConstants.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/MetadataConstants.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/FileJob.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
- inlong-agent/agent-plugins/pom.xml
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/TextFileSource.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/AbstractFileReader.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/FileReaderOperator.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/FilesReader.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/KubernetesFileReader.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/TextFileReader.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/MetaDataUtils.java
- inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestTextFileReader.java
- licenses/inlong-agent/LICENSE
- pom.xml
The feature supports the collection of data splicing metadata information.
- Fixes #5362 
1.Refactoring FileReader
2.Add AbstractReader
3.Connect k8s metadata
*TestTextFileReader
> [INLONG-5362][Agent] Supports the collection of data splicing metadata information

- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDynamicOutputFormatBuilder.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDynamicTableFactory.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDynamicTableSink.java
- licenses/inlong-sort-connectors/LICENSE
Import all changelog mode data ingest into JDBC
- Fixes #5315
*JDBC does not support CDC sink without primary key, so we could give an option to regard all changelog data as insert-only data. So we can insert into jdbc from canal-json，mysql-cdc etc.*
*add a `sink.ignore.changelog` option to support insert-only mode*
> [INLONG-5315][Sort] Import all changelog mode data ingest into JDBC

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/PostgresLoadNode.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/GenericJdbcSinkFunction.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcBatchingOutputFormat.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/TableJdbcUpsertOutputFormat.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/metric/MetricData.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDialects.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDynamicOutputFormatBuilder.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDynamicTableFactory.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDynamicTableSink.java
- Fixes #5100 
Add reporting metrics for JDBC
Add reporting metrics for JDBC
*(example:)*
> [INLONG-5100][Sort] Add reporting metrics for JDBC

- inlong-sort/sort-connectors/iceberg-dlc/pom.xml
- inlong-sort/sort-connectors/iceberg/pom.xml
- Fixes #5375 
Iceberg-inlong connector lose its meta-inf
change two pom
*(example:)*
> [INLONG-5375][Sort] Iceberg-inlong connector lose its meta-inf

- inlong-audit/bin/store-start.sh
- Fixes #5402 
1. Modify the directory specified by the audit module
2. Modify the audit module Java startup command
3. A judgment condition is added to the application startup, and the previous condition is not enough
> [INLONG-5402][Audit] Modify the audit module startup script

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/DataNode.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/DataNodeImpl.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/ClientFactory.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/DataNodeClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/DataNodeApi.java
- inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/DataNodeResponse.java
- Fixes #5371 
Add data node API in the manager client
- org.apache.inlong.manager.client.api.inner.ClientFactoryTest#testSaveDataNode
- org.apache.inlong.manager.client.api.inner.ClientFactoryTest#testGetDataNode
- org.apache.inlong.manager.client.api.inner.ClientFactoryTest#testListDataNode
- org.apache.inlong.manager.client.api.inner.ClientFactoryTest#testUpdateDataNode
- org.apache.inlong.manager.client.api.inner.ClientFactoryTest#testDeleteDataNode
> [INLONG-5371][Manager] Add data node API in the manager client

- inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/BaseSortConf.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/FlinkSortConf.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/UserDefinedSortConf.java
- inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sort/BaseSortConfTest.java
- [INLONG-5409][Manager] Fix json serialization for class BaseSortConf
- Fixes #5409 
Fix json serialization for class BaseSortConf
* Remove `sortType` field for BaseSortConf
* Add `getType` method for FlinkSortConf and UserDefinedSortConf
* Remove `type` field for FlinkSortConf and UserDefinedSortConf
* Add UT for BaseSortConf
> [INLONG-5409][Manager] Fix json serialization for class BaseSortConf

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/sort/SortConfigListener.java
- [INLONG-5442][Manager] Fix accept logic error for SortConfigListener
- Fixes #5442 
Fix accept logic error for SortConfigListener
* modify SortConfigListener, remove mq judging. Because lightwight task is no mq. We should change accept logic when we merge listener.
> [INLONG-5442][Manager] Fix accept logic error for SortConfigListener

- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/StreamSinkFieldEntity.java
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkFieldEntityMapper.xml
- inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql
- inlong-manager/manager-web/sql/apache_inlong_manager.sql
… SinkField fields do not match
- Title Example: [INLONG-5401][Manager] Fix StreamSinkFieldEntity and SinkField fields not match 
- Fixes #5401 
*Fix StreamSinkFieldEntity and SinkField fields not match *
*Fix StreamSinkFieldEntity and SinkField fields not match *
*(example:)* …
> [INLONG-5401][Manager] Fix StreamSinkFieldEntity and SinkField fields not match 

- inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/MQClusterInfo.java
- inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
- Fixes #5432 
Return the type of the MQ cluster when processing the getConfig method
Return the type of the MQ cluster when processing the getConfig method
`mqType` is added to the returned information.
The mq type returned is `TUBEMQ` and `PULSAR`.
> [INLONG-5432][Manager] Return the type of the MQ cluster when processing the getConfig method

- inlong-agent/agent-docker/README.md
- inlong-agent/agent-docker/agent-docker.sh
Add Manager Open API secret config
- Fixes #5466 
no
no
> [INLONG-5466][Docker] Add the ENV for Manager Open API secret config

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/User.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/UserImpl.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/ClientFactory.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/UserClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/UserApi.java
- inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/user/UserInfo.java
- Fixes #5493 
Add user API in the manager client
- org.apache.inlong.manager.client.api.inner.ClientFactoryTest#testRegisterUser
- org.apache.inlong.manager.client.api.inner.ClientFactoryTest#testGetUserById
- org.apache.inlong.manager.client.api.inner.ClientFactoryTest#testUpdateUser
- org.apache.inlong.manager.client.api.inner.ClientFactoryTest#testDeleteUser
> [INLONG-5493][Manager] Add user API in the manager client

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/KubernetesConstants.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/AbstractFileReader.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/FileReaderOperator.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/KubernetesFileReader.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/FileDataUtils.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/MetaDataUtils.java
File collects in the k8s, data, and metadata of k8s need to connect a message.
- Fixes #5533 
File data and k8s metadata to connect a message.
```
{
"_content_":"data",
"_time_":"time",
"_pod_name_":"test"
}
```
> [INLONG-5533][Agent] Support structured output in the Kubernetes

- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/BinlogReader.java
- Fixes #5540
When MySQL binlog reader read from binlog it will report java.lang.NullPointerException.
initialize the variable `readerMetric`
> [INLONG-5540][Agent] Fix the NPE for MySQL binlog reader

- inlong-dashboard/src/components/StaffSelect/index.tsx
- inlong-dashboard/src/pages/UserManagement/index.tsx
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/UserClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongStreamApi.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/UserApi.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/UserController.java
- Fixes #5585 
1.This url does not need the leading `/`.
2.`GET` requests do not support objects as parameters.
1.Remove `/`.
2.Modify request method to POST.
> [INLONG-5582][Manager][Dashboard] Fix error in client API

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/Workflow.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/WorkflowImpl.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/WorkflowClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/WorkflowApi.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/WorkflowEventApi.java
- inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java
- inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/WorkflowClientTest.java
- Fixes #5562 
Add the workflow API in the manager client
- *org.apache.inlong.manager.client.api.inner.WorkflowClientTest#testWorkflowStart*
- *org.apache.inlong.manager.client.api.inner.WorkflowClientTest#testListProcess*
> [INLONG-5562][Manager] Add the workflow API in the manager client

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/AgentUtils.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentManager.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobWrapper.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/TextFileSource.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/AbstractFileReader.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/TextFileReader.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/FileDataUtils.java
Support k8s log:
1. standard k8s log
2. ordinary k8s log
- Fixes #5589 
1. To judge json 
2. To connect data and metadata
> [INLONG-5589][Agent] To extend type of file data for k8s log

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/MySqlExtractNode.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/WatermarkField.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/relation/InnerTemporalJoinRelationRelation.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/relation/JoinRelation.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/relation/LeftOuterTemporalJoinRelationRelation.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/relation/NodeRelation.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/relation/TemporalJoinRelation.java
- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/MySqlTemporalJoinRelationSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/RedisTemporalJoinRelationSqlParseTest.java
Title: [INLONG-5599][Sort] Add temporal join support for mysql
Fixes #5599 
Add temporal join support for mysql.
1.Add ExtractMode used to distinguish between different extract modes.
2.Update MySqlExtractNode to support scan.
3.Add unit test for this case.
*(example:)* …
> [INLONG-5599][Sort] Add temporal join support for MySQL

- inlong-distribution/src/main/assemblies/sort-connectors.xml
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/FileSystemLoadNode.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
- inlong-sort/sort-connectors/filesystem/pom.xml
- inlong-sort/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/AbstractFileSystemTable.java
- inlong-sort/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/FileSystemTableFactory.java
- inlong-sort/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/FileSystemTableSink.java
- inlong-sort/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/stream/AbstractStreamingWriter.java
- inlong-sort/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/stream/StreamingFileWriter.java
- inlong-sort/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/stream/StreamingSink.java
- inlong-sort/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/stream/compact/CompactFileWriter.java
- inlong-sort/sort-connectors/filesystem/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- inlong-sort/sort-connectors/pom.xml
- inlong-sort/sort-core/pom.xml
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/FilesystemSqlParserTest.java
- licenses/inlong-sort-connectors/LICENSE
- licenses/inlong-sort-connectors/NOTICE
- [INLONG-5587][Sort] Add filesystem connector module for inlong metric and inlong audit
- Fixes #5587 
Add filesystem connector module for inlong metric and inlong audit
* Add filesystem connector module for supporting inlong.metric and inlong.audit and sink.ignore.changelog option
* Add UT for filesystem load node
> [INLONG-5587][Sort] Add filesystem connector module for inlong metric and inlong audit

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/ElasticsearchLoadNode.java
- Fixes #5605 
Fix bug when primary Key and routing-feild are null in Elasticsearch 7 connector
remove the default value of routing.field-name
> [INLONG-5605][Sort] Fix bug when primary Key and routing-feild are null in Elasticsearch 7 connector

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/FilterFunction.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/Function.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/FunctionParam.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/function/AddFunction.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/function/BetweenFunction.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/function/CastFunction.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/function/IntervalFunction.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/function/SubtractFunction.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/relation/InnerTemporalJoinRelation.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/relation/IntervalJoinRelation.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/relation/JoinRelation.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/relation/LeftOuterTemporalJoinRelation.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/relation/NodeRelation.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/function/AddFunctionTest.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/function/BetweenFunctionTest.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/function/IntervalFunctionTest.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/function/SubtractFunctionTest.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/relation/InnerTemporalJoinRelationTest.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/relation/IntervalJoinRelationTest.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/relation/LeftTemporalJoinRelationTest.java
- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/IntervalJoinRelationSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/MySqlTemporalJoinRelationSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/RedisTemporalJoinRelationSqlParseTest.java
Title: [INLONG-5613][Sort] Add interval join support for FlinkSqlParser
Fixes #5613 
Support interval join for FlinkSqlParser.
1.Add AddFunction, BetweenFunction, SubtractFunction, IntervalFunction.
1.Add support interval join parse for FlinkSqlParser
*(example:)* …
> [INLONG-5613][Sort] Add interval join support for FlinkSqlParser

- inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaProducer.java
Title: [INLONG-5637][Sort] Fix kafka load node npe error
Fixes #5637
Fix the npe error of kafka load node
Update the logic  of sendOutMetrics and sendDirtyMetrics in FlinkKafkaProducer.
*(example:)* …
> [INLONG-5637][Sort] Fix kafka load node npe error

- .github/workflows/ci_docker.yml
- docker/publish-by-arch.sh
[INLONG-5652][Docker] Fix push aarch64 images script
- Fixes #5652 
[INLONG-5652][Docker] Fix push aarch64 images script
[INLONG-5652][Docker] Fix push aarch64 images script
> [INLONG-5652][Docker] Fix push aarch64 images script

- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/MultiTopicsFetcher.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClientConfig.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/pulsar/PulsarConsumer.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/pulsar/PulsarMultiTopicsFetcher.java
- Fixes #5621 
1. Defination of basic class of multi-topic fetcher
2. Support one pulsar consumer subscribe multi topics at the same time.
*(example:)* …
> [INLONG-5621][SDK] Support multi-topic fetcher for Pulsar

- conf/inlong.conf
- docker/docker-compose/docker-compose.yml
- inlong-agent/agent-docker/README.md
- inlong-audit/audit-docker/README.md
- inlong-dataproxy/dataproxy-docker/README.md
- inlong-manager/manager-docker/README.md
- inlong-tubemq/tubemq-docker/tubemq-all/README.md
- Fixes #5657 
[INLONG-5657][Release] Change the tag of Docker images to 1.3.0
[INLONG-5657][Release] Change the tag of Docker images to 1.3.0
> [INLONG-5657][Release] Change the tag of Docker images to 1.3.0

- inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/pack_queue.cc
- [INLONG-5667][SDK] Change key value of groupId and streamId while wrapping message
- Fixes #5667 
DataProxy using key "groupId" and "streamId" to get inlongGroupId and inlongStreamId of user message.
*(example:)* …
> [INLONG-5667][SDK] Change key value of groupId and streamId while wrapping message

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/AgentUtils.java
- inlong-agent/agent-common/src/test/java/org/apache/inlong/agent/common/TestAgentUtils.java
- inlong-agent/agent-common/src/test/resources/agent.properties
- inlong-agent/agent-docker/agent-docker.sh
- inlong-agent/conf/agent.properties
Support custom fixed ip for Agent.
For example:
Ip has to fixed in the k8s.
- Fixes #5675 
Add config information.
No message.
> [INLONG-5675][Agent] Support custom fixed ip for Agent

- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/MultiTopicsFetcher.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/kafka/AckOffsetOnRebalance.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/kafka/KafkaMultiTopicsFetcher.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/pulsar/PulsarMultiTopicsFetcher.java
- Fixes #5623 
1. Introduce **_skiplist_** to maintain the offset commit of each TopicPartitions
2. The costomized msgOffset is different from **_KafkaSingleTopicFetcher_**, which is consist of topic:partitionId:offset.
*(example:)* …
> [INLONG-5623][SDK] Support multi-topic fetcher for Kafka

- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldRelationUtils.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/LoadNodeUtils.java
- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java
- [INLONG-5680][Manager] Fix field relation object generate error cause generate union sql throw NPE exception
- Fixes #5680 
Fix field relation object generate error cause generate union sql throw NPE exception
* Modify FieldRealtionUtil about removing nodeId of outputField
* Modify LoadNodeUtil about removing nodeId of outputField
* Modify Sort FlinkSqlParser comment
> [INLONG-5680][Manager][Sort] Fix field relation object generate error cause generate union SQL throw NPE

- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterEntityMapper.java
- inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/heartbeat/HeartbeatManager.java
- Fixes #5698 
Make sure the dataproxy cluster tag was not restored to the default after the manager was restarted.
After receiving the cluster heartbeat information, if there is a cluster with the same name, the information will not be modified.
> [INLONG-5698][Manager] Fixed the DataProxy cluster tag was restored after the manager was restarted

- inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/DeleteSortListener.java
- inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/DeleteStreamListener.java
- inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/RestartSortListener.java
- inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/RestartStreamListener.java
- inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/StartupStreamListener.java
- inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/SuspendSortListener.java
- inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/SuspendStreamListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ConsumptionServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
- inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/core/impl/WorkflowQueryServiceImpl.java
- Fixes #5694 
Make sure the group information of initsort failure can be viewed normally
This ensures that no null pointer exception will be reported when getting the sort configuration information.
> [INLONG-5694][Manager] Fix the problem that gets the inlong group error

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/ExtractNodeUtils.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/autopush/AutoPushSource.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/autopush/AutoPushSourceDTO.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/autopush/AutoPushSourceRequest.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSource.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSourceDTO.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSourceRequest.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSource.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSourceDTO.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSourceRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/pulsar/PulsarSourceOperator.java
[INLONG-5703][Manager] Get separator from enum 'DataSeparator' and remove fieldDelimiter from properties of PulsarSource
- Fixes #5703 
- DataSeparator is an ascii code, so we should get separator from enum `DataSeparator `
- if not remove fieldDelimiter, it will be parse into sql option. for example:
```
"properties": {
"properties.auth-params": "token:xxxx",
"properties.auth-plugin-classname": "org.apache.pulsar.client.impl.auth.AuthenticationToken",
"fieldDelimiter": "|"
}
```
> [INLONG-5703][Manager] Add separator-related fields for some sources

- pom.xml
> [INLONG-5724][CI] Skip the apache-rat-plugin when building the docker-compose

- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClientConfig.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/kafka/KafkaSingleTopicFetcher.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/pulsar/PulsarMultiTopicsFetcher.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/pulsar/PulsarSingleTopicFetcher.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/tube/TubeSingleTopicFetcher.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/kafka/InLongKafkaFetcherImpl.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/pulsar/InLongPulsarFetcherImpl.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/tube/InLongTubeFetcherImpl.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/metrics/SortSdkPrometheusMetricListener.java
- Fixes #5665
Current strategy is that invoke callback after deserializing one batch of MQ messages, which will result in full gc in the case of high load.
Change it to invoke callback after deserializing each MQ message to reduce full gc, but it will produce times of callback invoking.
*(example:)* …
> [INLONG-5665][SDK] Invoke callback in each MQ message to avoid massive full gc in high load

- inlong-sort/sort-formats/format-inlongmsg-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgDeserializationSchema.java
* [INLONG-5737][Sort] Fix InLongMsg with inner format raw deserialize throw NullPointException* 
- Fixes #5737 
*Fix InLongMsg with inner format raw deserialize throw NullPointException*
*Add  an initialization code for InLongMsg inner DeserializationSchema.*
> [INLONG-5737][Sort] Fix InLongMsg with inner format raw deserialize throw NullPointException

- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/include/tubemq/tubemq_tdmsg.h
> [INLONG-5748][TubeMQ] Remove the virtual keyword of the destructor of the TubeMQTDMsg and DataItem classes

- inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/withoutadmin/PulsarFetcher.java
- inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/withoutadmin/ReaderThread.java
- inlong-sort/sort-formats/format-inlongmsg-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgDeserializationSchema.java
- [INLONG-5754][Sort] Fix Pulsar connecotr deserialize complex format with multiple data will cause data loss
- Fixes #5754 
Fix Pulsar connecotr deserialize complex format with multiple data will cause data loss
Beacuse before it deserialize ont message to one rowData, so it means only one record will be sended to downstream after parsing a message.
now i store all sub record in one message, and it means multiple records will be sended to downstream if message contains multiple complex record.
> [INLONG-5754][Sort] Fix Pulsar connecotr deserialize complex format with multiple data will cause data loss

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/sort/SortConfigListener.java
- Fixes #5756
Change the condition of the accept method for SortConfigListener.
> [INLONG-5756][Manager] Change the condition of the accept method for SortConfigListener

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/Heartbeat.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/HeartbeatImpl.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/ClientFactory.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/HeartbeatClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/HeartbeatApi.java
- inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/HeartbeatClientTest.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/heartbeat/ComponentHeartbeatResponse.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/heartbeat/GroupHeartbeatResponse.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/heartbeat/StreamHeartbeatResponse.java
- Fixes #5765 
Add heartbeat API in the manager client.
- org.apache.inlong.manager.client.api.inner.HeartbeatClientTest
> [INLONG-5765][Manager] Add heartbeat API in the manager client

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/StreamStatus.java
- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSinkEntityMapper.java
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkFieldEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/ck/ClickHouseResourceOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/AbstractSinkOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamProcessService.java
- Fixes #5611
Set the sink status after updating the sink info.
After updating the stream sink info, if the status of inlong stream was CONFIG_SUCCESSFUL or CONFIG_FAILED, change the sink status to CONFIG_ING, otherwise not change the sink status.
1. If the stream status was CONFIG_SUCCESSFUL, no matter what status of the sink, all changing to CONFIG_ING, and start the CREATE_STREAM_PROCESS, after the process will change the sink status to CONFIG_SUCCESSFUL or CONFIG_FAILED.
2. If the stream status was CONFIG_FAILED, it means there are some errors occurred, the user must fix it first, and in this situation, sink status also need to be CONFIG_ING, it tells the user that the sink info was updated success, and begin to configuring. Only after the stream error was fixed, the sink status will …
> [INLONG-5611][Manager] Set the sink status after updating the sink info

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/source/AbstractSourceOperateListener.java
- Fixes #5769
Fix the FILE type unsupported for SourceOperateListener.
> [INLONG-5769][Manager] Fix the FILE type unsupported for SourceOperateListener

- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongConsumeEntityMapper.java
- inlong-manager/manager-dao/src/main/resources/mappers/InlongConsumeEntityMapper.xml
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/queue/pulsar/PulsarTopicInfo.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/InlongConsumeService.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/InlongConsumeServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/ConsumptionService.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ConsumptionServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/consumption/ConsumptionCompleteProcessListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaResourceOperators.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarResourceOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/tubemq/TubeMQResourceOperator.java
- Fixes #5781
Support creating consumer groups for all sinks.
For Pulsar, an InlongStream maps a Pulsar Topic.
And we support the creation of multiple StreamSinks under the same InlongStreamId, which means that Sort needs to consume the data in the Topic once for each StreamSink, so a consumer group must be created for each StreamSink.
> [INLONG-5781][Manager] Support creating consumer groups for all sinks

- licenses/inlong-manager/LICENSE
- pom.xml
- Fixes #5645
*(example:)*
- If a …
> [INLONG-5645][CVE] Bump pagehelper from 5.3.0 to 5.3.1 to fix SQL injection vulnerability

- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/utils/FlumeConfigGenerator.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/rollback/TimeBasedFilterInterceptor.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSource.java
- Fixes #5805
The configuration to init flume interceptors is lack of a key to specify the type of interceptors.
Which result in incorret init of interceptors.
*(example:)* …
> [INLONG-5805][Sort] Fix incorrect interceptor initialization

- docker/build-docker-images.sh
Add platform for aarch64
- Fixes #5816 
Add platform for aarch64
Add platform for aarch64
build-docker-images.sh lost USE_PLATFORM args.  Add platform for aarch64 can fix build no arm64 images.
I have test as follow:
> [INLONG-5816][Docker] Add platform for aarch64

- inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/ElasticsearchSinkBase.java
- inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/table/RowElasticsearchSinkFunction.java
- Fixes #5822 
Fix metric is empty in the case of tke2es
inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/ElasticsearchSinkBase.java
inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/table/RowElasticsearchSinkFunction.java
> [INLONG-5822][Sort] Fix the error of metric is empty for Elasticsearch

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mqzone/AbstractZoneSinkContext.java
- Fixes #5834
Recenetly I learned how inlong to do audit and discover some mistake, so just fix it
1. AUDIT_ID_DATAPROXY_READ_SUCCESS -> AUDIT_ID_DATAPROXY_SEND_SUCCESS
2. readFailCount -> sendFailCount
no
> [INLONG-5834][DataProxy] Fix the mistake for the sink metric in MQ Zone

- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/DefaultOffsetManager.java
- Fixes https://github.com/apache/inlong/issues/5859
The code duplication rate for method getAndResetTmpOffset and method setTmpOffset is as high as 90%.
In fact, method getAndResetTmpOffset can reuse method setTmpOffset.
The code duplication rate for method getAndResetTmpOffset and method setTmpOffset is as high as 90%.
In fact, method getAndResetTmpOffset can reuse method setTmpOffset.
> [INLONG-5859][TubeMQ] Remove the redundant codes in DefaultOffsetManager

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
- Fixes #5875
The new sub source task version should not be copied from template task but defaults to 1.
Or else subsequent operations may fail due to version not matching.
> [INLONG-5875][Manager] Set the version for the issued sub-sources

- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/kafka/InlongKafkaDTO.java
- Fixes #5919 
Ensure that the inlonggroup information with mq of kafka can be obtained normally
Added participated and nonparametric constructors for InlongKafkaDTO
- [X ] This change is a trivial rework/code cleanup without any test coverage.
> [INLONG-5919][Manager] Fix that cannot successfully obtain the Kafka info for inlong group

- inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/daemon/AbstractDaemonService.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/DefaultOffsetManager.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/OffsetRecordService.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/stats/TrafficStatsService.java
- inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/utils/SimpleVisitTokenManager.java
- Fixes https://github.com/apache/inlong/issues/5907
it is not recommended to execute a scheduled task by while-sleep. 
Replace while-sleep with ScheduledExecutorService.
> [INLONG-5907][TubeMQ] Replace the while-sleep with ScheduledExecutorService for tube server loopProcess

- inlong-common/src/main/java/org/apache/inlong/common/enums/TaskTypeEnum.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/SourceType.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/ExtractNodeUtils.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/redis/RedisSource.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/redis/RedisSourceDTO.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/redis/RedisSourceRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/redis/RedisSourceOperator.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/source/RedisSourceServiceTest.java
- Fixes #5863
extend redis ExtractNode in Manager module
Follow the [extend extractNode](https://inlong.apache.org/zh-CN/docs/design_and_concept/how_to_extend_data_node_for_manager)
+ Add RedisSource, RedisSourceDTO, RedisRequestDTO
+ Add Redis type in TaskTypeEnum and SourceType
+ Add RedisSourceOperator
+ Add unit test for Redis source service
- RedisSourceServiceTest for testing Redis source service …
> [INLONG-5863][Manager] Extend Redis extract node

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongClientImpl.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongClusterClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongClusterApi.java
- Fixes #5936 
It should return `Call<Response<PageResult<ClusterInfo>>>`.
Modify return type to `Call<Response<PageResult<ClusterInfo>>>`.
> [INLONG-5936][Manager] Fix return type of cluster API

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNode.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/MySqlExtractNode.java
Title: [INLONG-5940][Sort] Compatible with the old version of sort protocol with mysql and kafka extract node
Fixes #5940 
Compatible with the old version of sort protocol with mysql and kafka extract node
Update the protocol of mysql and kafka extract node.
*(example:)*
- If yes, how is the feature documented? (not applicable / docs / JavaDocs …
> [INLONG-5940][Sort] Compatible with the old version of sort protocol with mysql and kafka extract node

- inlong-sort/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/stream/AbstractStreamingWriter.java
Title: [INLONG-5959][Sort] Support metric state recovery for filesystem
Fixes #5959
Support metric state recovery for filesystem
Update AbstractStreamingWriter to support metric state recovery for filesystem
*(example:)* …
> [INLONG-5959][Sort] Support metric state recovery for filesystem

- inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/sink/HBaseSinkFunction.java
Title: [INLONG-5955][Sort] Support metric state recovery for hbase
Fixes #5955
Support metric state recovery for hbase
Update HBaseSinkFunction to support metric state recovery
*(example:)* …
> [INLONG-5955][Sort] Support metric state recovery for HBase

- inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/DebeziumSourceFunction.java
- Fixes #5950
[INLONG-5950][Sort] Support metric state recovery for mongo-cdc
[INLONG-5950][Sort] Support metric state recovery for mongo-cdc
*(example:)*
> [INLONG-5950][Sort] Support metric state recovery for mongodb-cdc

- inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterNodeEntityMapper.xml
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/DataNodeRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceTest.java
- Fixes #5953
Timed out dataproxy nodes should be removed before returned to agents.
> [INLONG-5953][Manager] Filter DataProxy nodes by status when necessary

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java
- Fixes #5975
Transform nodes are dropped in full-link modes.
Make full-link mode compatible with lightweight mode when transform nodes are present.
> [INLONG-5975][Manager] Support transform nodes in standard mode

- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CreateCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/DeleteCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/DescribeCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/ListCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/UpdateCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/ClusterInfo.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/validator/ClusterTypeValidator.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongClusterClient.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ClusterType.java
- Fixes #5102 
Manager tools supports CRUD for inlong cluster.
1.Add CRUD for inlong cluster.
2.Add cluster type parameter validation.
2.Add cluster id validation in `org.apache.inlong.manager.client.api.inner.client.InlongClusterClient#update`.
1. managerctl list cluster
```
cluster      Get cluster summary information
Usage: cluster [options]
Options:
--tag
cluster tag
--type
cluster type
```
2. managerctl describe cluster
```
cluster      Get cluster details
Usage: cluster [options]
Options:
* -id, --id
cluster id
```
3. managerctl create cluster
```
cluster      Create cluster by json file
Usage: cluster [options]
Options:
-f, --file
json file
```
4. managerctl update cluster
```
cluster      Update cluster by json file
Usage: cluster [options]
Options:
-f, --file
json file
```
5. …
> [INLONG-5102][Manager] Command tools add CRUD for inlong cluster

- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CreateCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/DeleteCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/DescribeCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/ListCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/UpdateCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/ClusterTagInfo.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/util/ClientUtils.java
- Fixes #5990 
Command tools add CRUD for inlong cluster tag.
1.Add CRUD for inlong cluster tag.
2.Modify exception judgment in `org.apache.inlong.manager.client.cli.util.ClientUtils#readFile`
1. managerctl list cluster-tag
```
cluster-tag      Get cluster tag summary information
Usage: cluster-tag [options]
Options:
--tag
cluster tag
```
2. managerctl describe cluster-tag
```
cluster-tag      Get cluster tag details
Usage: cluster-tag [options]
Options:
* -id, --id
cluster tag id
```
3. managerctl create cluster-tag
```
cluster-tag      Create cluster tag by json file
Usage: cluster-tag [options]
Options:
-f, --file
json file
```
4. managerctl update cluster-tag
```
cluster-tag      Update cluster tag by json file
Usage: cluster-tag [options]
Options:
-f, --file
json file
```
5. …
> [INLONG-5990][Manager] Command tools add CRUD for inlong cluster tag

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/SinkMetricData.java
- inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/ElasticsearchSinkBase.java
- inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/ElasticsearchSinkFunction.java
- inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/table/RowElasticsearchSinkFunction.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/GenericJdbcSinkFunction.java
- Fixes #5992 
Fix runtimeContext not initialized in JDBC and ES when reload metric status
JDBC connector and ES connector
> [INLONG-5992][Sort] Fix runtimeContext not initialized in JDBC and ES when reload metric status

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/ConsumePulsarOperator.java
- Fixes #6014 
*When an int is compared to an Integer, the Integer may be null.*
*Use equals to compare two numbers for the same*
*(example:)*
> [INLONG-6014][Manager] Int type cannot be compared with null using ==

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/sort/StreamSortConfigListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
- Fixes #6001 
Ensure that the newly created sink under the successfully configured stream can be configured normally
Judge the stream status when saving. If the configuration is successful, the sink configuration process will be triggered
> [INLONG-6001][Manager] Ensure that the newly created sink under the successful stream can be configured normally

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java
- Fixes #6003
In the beginning only **lightweight mode** supports the ETL transform nodes. Clients configure their extract/transform/load nodes  at will and what they submit is what they see so everyone is happy.
This ceases to be the case when **standard sort mode** tries to support transform nodes as well. In standard mode multiple upstream sources are collected to MQ first and are not the real extract nodes anymore. Instead the MQ cache node becomes **the real extract node**.  
This is achieved by manager through replacing the original upstream source nodes (file、binlog...) with the MQ cache node when constructing the extract node in standard mode.
However the clients are ignorant of any of this.  From their point of view nothing is changed and the MQ node is invisible to them. So in …
> [INLONG-6003][Manager] Change the transform source node name to be MQ node in standard mode

- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CreateCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/DeleteCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/DescribeCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/ListCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/UpdateCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/ClusterNodeInfo.java
- Fixes #6004 
Command tools add CRUD for inlong cluster node.
1..Add CRUD for inlong cluster tag.
1. managerctl list cluster-node
```
cluster-node      Get cluster node summary information
Usage: cluster-node [options]
Options:
--tag
cluster tag
--type
cluster type
```
2. managerctl describe cluster-node
```
cluster-node      Get cluster node details
Usage: cluster-node [options]
Options:
* -id, --id
cluster node id
```
3. managerctl create cluster-node
```
cluster-node      Create cluster node by json file
Usage: cluster-node [options]
Options:
-f, --file
json file
```
4. managerctl update cluster-node
```
cluster-node      Update cluster node by json file
Usage: cluster-node [options]
Options:
-f, --file
json file
```
5. managerctl delete cluster-node
```
cluster-node      Delete …
```
> [INLONG-6004][Manager] Command tools add CRUD for inlong cluster node

- inlong-sort/sort-connectors/iceberg-dlc/src/main/java/org/apache/inlong/sort/iceberg/flink/sink/IcebergStreamWriter.java
*[INLONG-6027][Sort] Dlc did not restore metric data successfully*
- Fixes #6027 
*Dlc did not restore metric data successfully*
> [INLONG-6027][Sort] Dlc did not restore metric data successfully

- inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/db/entities/ClickHouseDataPo.java
- inlong-audit/audit-store/src/main/resources/sql/apache_inlong_audit_clickhouse.sql
- inlong-audit/sql/apache_inlong_audit_clickhouse.sql
- Title: [INLONG-6026][Audit] Fix the executed error of ClickHouse audit SQL file
- Fixes #6026
ClickHouse not support those operations, remove them.
```
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";
```
> [INLONG-6026][Audit] Fix the executed error of ClickHouse audit SQL file

- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/KubernetesFileReader.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/MetaDataUtils.java
- inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/utils/MetaDataUtilsTest.java
Fix file could not be matched in the k8s.
Add a Regular Expression.
- Fixes #6047 
The file name in the soft link path must be matched with the regular.
Add a util
> [INLONG-6047][Agent] Fix file could not be matched in the k8s

- inlong-dataproxy/bin/dataproxy-ng
- [INLONG-6049][DataProxy] Add jvm parameter about error log print
- Fixes #6049 
*(example:)*
- If a …
> [INLONG-6049][DataProxy] Disable OmitStackTraceInFastThrow to print verbose error logs

- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/ck/ClickHouseDataNodeDTO.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/ck/ClickHouseDataNodeInfo.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/ck/ClickHouseDataNodeRequest.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/iceberg/IcebergDataNodeDTO.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/iceberg/IcebergDataNodeInfo.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/iceberg/IcebergDataNodeRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/ck/ClickHouseDataNodeOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/iceberg/IcebergDataNodeOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/ck/ClickHouseResourceOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/hive/HiveResourceOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/iceberg/IcebergResourceOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/AbstractSinkOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/ck/ClickHouseSinkOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/hive/HiveSinkOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/iceberg/IcebergSinkOperator.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/DataNodeServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/HiveSinkServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/IcebergSinkServiceTest.java
- Fixes #6063
Modifications:
- read from data node  when ck url is not supplied
- read from iceberg data node when iceberg catalog uri is not supplied
- remove jdbc url from hive data node because it's the same as url in base class.
> [INLONG-6063][Manager] Utilize ClickHouse and Iceberg data node

- docker/kubernetes/templates/agent-statefulset.yaml
- docker/kubernetes/templates/audit-statefulset.yaml
- docker/kubernetes/templates/dashboard-statefulset.yaml
- docker/kubernetes/templates/dataproxy-statefulset.yaml
- docker/kubernetes/templates/manager-statefulset.yaml
Add liveness reliability for modules.
- Fixes #6094 
Add liveness reliability for modules
Add liveness reliability for modules
Add liveness reliability for modules. Every modules automatically pull up after process stopped by accident.
> [INLONG-6094][Kubernetes] Add liveness reliability for modules

- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/ExtractNodeUtils.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaOffset.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSource.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSourceDTO.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSourceRequest.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/KafkaConstant.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/enums/KafkaScanStartupMode.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNode.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNodeTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DataTypeConvertSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DecimalFormatSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DistinctNodeSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/FlinkSqlParserTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/FullOuterJoinSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/InnerJoinRelationSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/IntervalJoinRelationSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/KafkaSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/LeftOuterJoinSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/MetaFieldSyncTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/MySqlTemporalJoinRelationSqlParseTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/RightOuterJoinSqlParseTest.java
- [INLONG-6089][Manager][Sort] kafka extract node support raw format and scan mode support timestamp
- Fixes #6089 
kafka extract node support raw format and scan mode support timestamp
* Add kafka extract node support scan mode timestamp
* Add raw format for kafka extract node
> [INLONG-6089][Manager][Sort] Kafka extract node supports raw format and timestamp scan mode

- inlong-common/src/main/java/org/apache/inlong/common/enums/MetaField.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/Metadata.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/MySqlExtractNode.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/SqlServerExtractNode.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/MySqlExtractNodeTest.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/DebeziumSourceFunction.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/internal/DebeziumChangeFetcher.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/internal/FlinkDatabaseSchemaHistory.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlReadableMetadata.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/AllMigrateTest.java
- inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJson.java
- Fixes #6113 
The Mysql Connector for extracting data now doesn't support reading table schema when there is no primary key specified.
Canal Json requires field names called mysqlType and sqlType which contains information in table schema
The pr modifies the implementation of debezium function to get table schema from debezium databaseHistory
1 Add a new meta field called DATA_BYTES to represent the canal presentation of a record
2 make the table schema contained in databasehistory static
3 fill canal json with info from table schema
run AllMigrateTest
> [INLONG-6113][Sort] Mysql cdc connector support read table schema when using debezium function

- inlong-manager/manager-docker/manager-docker.sh
- Fixes #6136 
Fix the docker logs command could not find log file error
Change the manager-web.log -> manager-all.log
> [INLONG-6136][Manager] Fix the docker logs command could not find log file error

- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/table/MetadataConverter.java
Title: [INLONG-6166][Sort] Fix can not get pkNames metadata for MySqlExtractNode
Fixes #6166 
Fix can not get pkNames metadata for MySqlExtractNode
Update the default action of method 'read' in class 'MetadataConverter'
*(example:)* …
> [INLONG-6166][Sort] Fix can not get pkNames metadata for MySqlExtractNode

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java
- Fixes #6171
Lightweight group may contain multiple union nodes rather than transform nodes which leads to the wrong branch when generating node relations. Fix it.
- lightweight group goes to the branch using user specified relation and union mutiple input nodes as before.
- standard group with transform nodes do the same as above, but redirects the input node to the MQ node.
- standard group without transform node use the source and sink nodes directly.
> [INLONG-6171][Manager] Fix the lightweight group union nodes relation error

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/KafkaConstant.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/KafkaLoadNode.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/AbstractDynamicSchemaFormat.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/CanalJsonDynamicSchemaFormat.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormat.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/JsonDynamicSchemaFormat.java
- inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/format/CanalJsonDynamicSchemaFormatTest.java
- inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormatTest.java
- inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/partitioner/RawDataHashPartitioner.java
- inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicTableFactory.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/KafkaLoadSqlParseTest.java
Title: [INLONG-6160][Sort] Support dynamic partition for KafkaLoadNode
Fixes #6160 
Support dynamic partition for KafkaLoadNode when the format of kafka is raw and the 'key.fields' is not specifyed.
This is mainly for some whole database migration scenarios, we assume that the upstream input data is a mixed schema of whole database migration, we ignore the real schema for now, receive the entire record in a binary raw data format, and fetch and parse its schema and data on the kafka sink side, and according to Some data values ​​are dynamically written to related topic partitions.
Dynamic partition writing has some …
> [INLONG-6160][Sort] Support dynamic partition for KafkaLoadNode

- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java
- inlong-common/src/main/java/org/apache/inlong/common/constant/ProtocolType.java
- inlong-common/src/main/java/org/apache/inlong/common/heartbeat/ComponentHeartbeat.java
- inlong-common/src/main/java/org/apache/inlong/common/heartbeat/HeartbeatMsg.java
- inlong-dataproxy/conf/common.properties
- inlong-dataproxy/conf/dataproxy-pulsar.conf
- inlong-dataproxy/conf/dataproxy-tube.conf
- inlong-dataproxy/dataproxy-docker/Dockerfile
- inlong-dataproxy/dataproxy-docker/dataproxy-docker.sh
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/ConfigConstants.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/heartbeat/HeartbeatManager.java
- inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterNodeEntityMapper.xml
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterPageRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/heartbeat/HeartbeatManager.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/heartbeat/HeartbeatManagerTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/HeartbeatServiceTest.java
- inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql
- inlong-manager/manager-web/sql/apache_inlong_manager.sql
Support node protocol reporting and query.
1.DataProxy supports http and tcp protocol reporting.
2.Agent supports to query dp node by protocol.
3.Manager client supports to query dp node by protocol and groupId.
- Fixes #6181 
1.This PR supports node of dp protocol, for example: tcp, http.
2.Agent queries node of dp by dp SDK.
3.Maneger client  queries node of cluster by protocol 
Agent send manager.
Dataproxy Multi-protocol reporting.
Update SDK param of dp-config.
> [INLONG-6181][Agent][DataProxy][Manager] Support node protocol reporting and query

- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CreateCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/DeleteCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/DescribeCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/ListCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/UpdateCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/UserInfo.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/validator/UserTypeValidator.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/User.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/UserImpl.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/UserClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/UserApi.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/UserTypeEnum.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/UserController.java
- Fixes #5049 
Command tools add CRUD for user.
1. Support get `UserTypeEnum.code` by `UserTypeEnum.name` in `UserTypeEnum`
2. Add CRUD for user.
3. Add `getUserByName` for manager-client
1.managerctl list user
```
user      Get user summary information
Usage: user [options]
Options:
--type
user type
-u, --username
username
```
2.managerctl describe user
```
user      Get user details
Usage: user [options]
Options:
* -id, --id
user id
```
4.managerctl create user
```
user      Create user
Usage: user [options]
Options:
-d, --days
valid days
-p, --password
password
-t, --type
account type
-u, --username
username
```
5.managerctl update user
```
user      Update User
Usage: user [options]
Options:
-d, --days
new valid days
-u, --username
username to be modify
```
6.managerctl delete user …
> [INLONG-5049][Manager] Command tools add CRUD for user

- inlong-dataproxy/conf/common.properties
> [INLONG-6217][DataProxy] Delete the cluster.id in the common.properties file

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/AgentPrometheusMetricListener.java
Support different components to parse their related metric.
- Fixes #6194 
Because the metrics uploaded by different agent components may be different, I split the metric item id_counter of prometheus and use KEY_PLUGIN_ID or KEY_COMPONENT_NAME as the primary key.
It is convenient for the different metric operation behind, and then there will be no common empty  data dimension in different component.
> [INLONG-6194][Agent] Support parsing metrics for different components

- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/GroupInfo.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/SinkInfo.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/SourceInfo.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/StreamInfo.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/util/ParseStatus.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/util/PrintUtils.java
- Fixes #6222 
1.Add a parameter to `ParseStatus` to differentiate between different state types.
Run `managerctl list source -g xxx -s xxx`
> [INLONG-6222][Manager] Fix parse source status failure in Command tools

- pom.xml
There are 1 security vulnerabilities found in org.apache.hive:hive-exec 3.1.2
- [CVE-2021-34538](https://www.oscs1024.com/hd/CVE-2021-34538)
fix #6231
Upgrade org.apache.hive:hive-exec from 3.1.2 to 3.1.3 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> [INLONG-6231][CVE] Upgrade org.apache.hive:hive-exec to 3.1.3

- inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/DataProxyNodeResponse.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongClientImpl.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongClusterClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongClusterApi.java
- inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterService.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java
1. Support query of DataProxy cluster based on inlongGroupId and protocolType.
2. The common code to extract the cluster query.
- Fixes #6220 
Update Manager client, add query DataProxy nodes by group id and protocol type.
InlongClusterController.listNodeByGroupId
```
@test
ClientFactoryTest.testListClusterNode()
```
> [INLONG-6220][Manager] Support query cluster nodes by the manager client

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Constants.java
- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/Entrance.java
Title: [INLONG-6243][Sort] Add custom name for sort job
Fixes #6243 
Add custom name for sort job, if it is not specified, it will be 'InLong-Sort-Job'.
1. Add job name setting with 'org.apache.inlong.sort.Entrance'
2. Add  JOB_NAME constant  for 'org.apache.inlong.sort.configuration.Constants'
*(example:)* …
> [INLONG-6243][Sort] Support custom name for Sort job

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormat.java
- inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormatTest.java
- inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormatWithSchemaTest.java
Title: [INLONG-6256][Sort] Support debezium-json format with schema parse for DebeziumJsonDynamicSchemaFormat
Fixes #6256 
Support debezium-json format with schema parse for DebeziumJsonDynamicSchemaFormat.
A complete debezium format with schema will put metadata, physical fields, etc. in the payload, we also need to support parsing of this format and extract physical data, metadata, ddl, and etc. The data example as follows:
```{
"schema": { 
"type": "struct",
"fields": [
{
"type": "struct",
"fields": [
{
"type": "int32",
"optional": false,
"field": "id"
},
{
"type": "string",
"optional": false,
"field": "first_name" …
```
> [INLONG-6256][Sort] Support debezium-json format with schema parse for DebeziumJsonDynamicSchemaFormat

- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java
- Fixes #6250 
[INLONG-6250][Sort] Return ZonedTimestamp when mysql data schema is timestamp or dataTime
[INLONG-6250][Sort] Return ZonedTimestamp when mysql data schema is timestamp or dataTime
run AllmigrateTest
> [INLONG-6250][Sort] Return ZonedTimestamp when mysql data schema is timestamp or dataTime

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/DorisConstant.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/DorisLoadNode.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/CanalJsonDynamicSchemaFormat.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormat.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/JsonDynamicSchemaFormat.java
- inlong-sort/sort-connectors/doris/pom.xml
- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicTableFactory.java
- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicTableSink.java
- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisStreamLoad.java
- inlong-sort/sort-connectors/doris/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DorisMultipleSinkTest.java
- licenses/inlong-sort-connectors/LICENSE
Title: [INLONG-6212][Sort] Support multiple sink for DorisLoadNode
Fixes #6212
Support multiple sink for DorisLoadNode.In this scenario, we agree that the upstream data stream is binary data in a certain format such as 'canal-json' or 'debezium', and the main processing steps as follows:
1. Deserialize the binary data by the format specified with 'sink.multiple.format'
2. Dynamic extract the database and table from it used with 'sink.multiple.database-pattern' and 'sink.multiple.table-pattern'
3. Convert the deserialized data to the json data that is used for Doris StreamLoad
4. Use StreamLoad load data to Doris used …
> [INLONG-6212][Sort] Support multiple sink for DorisLoadNode

- inlong-sort/sort-formats/format-json/pom.xml
- Fixes #6283 
sort jar conflict between sort-dist and connector
make debezium-core in sort-format-json provided since the dependency can be found in connector jar
> [INLONG-6283][Sort] Fix the JAR conflict between sort-dist and sort-connector

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/heartbeat/HeartbeatManager.java
- [INLONG-6285][DataProxy] Add authorization info while reporting heartbeat to Manager
- Fixes #6285 
*(example:)* …
> [INLONG-6285][DataProxy] Add authorization info while reporting heartbeat to Manager

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/SinkType.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/doris/DorisSink.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/doris/DorisSinkDTO.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/doris/DorisSinkRequest.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/LoadNodeUtils.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/doris/DorisSinkOperator.java
- Fixes #6232
Manager support Apache Doris load node management.
For more design info, see #5043
1. Add DORIS type in SinkType
2. New classes DorisSink,  DorisSinkDTO, and DorisSinkRequest, which contain doris-inlong sort parameters
3. LoadNodeUtils provides DorisLoadNode instance
> [INLONG-6232][Manager] Support Apache Doris load node management

- inlong-tubemq/tubemq-manager/pom.xml
There are 1 security vulnerability found in com.google.guava:guava 21.0
- [CVE-2018-10237](https://www.oscs1024.com/hd/CVE-2018-10237)
Fixes: #6263
Upgrade com.google.guava:guava from 21.0 to 30.0-jre for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> [INLONG-6263][CVE] Upgrade com.google.guava to 30.0-jre

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/JsonDynamicSchemaFormat.java
- inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/DynamicKafkaSerializationSchema.java
- inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaProducer.java
Title: [INLONG-6296][Sort] Split one record to multiple records when the physical data has more records for KafkaLoadNode
Fixes #6296
Split one record to multiple records when the physical data has more records for KafkaLoadNode
It is only used for multiple sink scenario, for example, the raw data is:
``` {
"data":[
{
"id":352,
"price":1.14,
"currency":"US",
"order_time":"2022-08-16 18:59:09"
},
{
"id":353,
"price":1.22,
"currency":"US",
"order_time":"2022-08-16 18:59:09"
}
],
"type":"INSERT",
"pkNames":[
"id"
],
"database":"inlong",
"ts":1666772931248,
"table":"orders"
}
```
and then it will be split into two records …
> [INLONG-6296][Sort] Split one record to multiple records when the physical data has more records for KafkaLoadNode

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicTableFactory.java
- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicTableSink.java
Title: [INLONG-6307][Sort] Add whether to ignore single-table error policy processing for multiple sink of DorisLoadNode
Fixes #6307
Add whether to ignore single-table error policy processing for multiple sink of DorisLoadNode
In multiple sink writing scenario, a table may have an error during the writing process. At this time, we can either ignore this error or throw this error to ensure data consistency, so i add the option 'sink.multiple.ignore-single-table-errors' to support this strategy choice.
1.Add a option 'sink.multiple.ignore-single-table-errors' for org.apache.inlong.sort.base.Constants
2.Update …
> [INLONG-6307][Sort] Add whether to ignore single-table error policy processing for multiple sink of DorisLoadNode

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/JsonDynamicSchemaFormat.java
- inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/format/CanalJsonDynamicSchemaFormatTest.java
- Fixes #6311 
In multiple sink scene， for example Mysql -> Iceberg，update data will produce old data, but it miss some field, it only contains modified field, so we must ignore missing field in it. 
*Bugfix:Multiple sink scene canal json old data missing field cause job fail*
> [INLONG-6311][Sort] Fix missing fields error for the old Canal JSON data in multiple sink scenes

- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java
- Fixes #6335 
support blob and binary data from mysql
binary data are supported using nio bytebuffer, we use utf-8 to decode as string
binary data are supported using nio bytebuffer, we use utf-8 to decode as string
run allmigratetest
> [INLONG-6335][Sort] Support the blob and binary data of MySql all migrate

- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
Title: [INLONG-6322][Sort] Fix write data incorrect for doris connector with sink multiple scenario
Fixes #6322 
Fix write data incorrect for doris connector with sink multiple scenario
Update DorisDynamicSchemaOutputFormat to fix it.
*(example:)*
- If a …
> [INLONG-6322][Sort] Fix write data incorrect for doris connector with sink multiple scenario

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/heartbeat/HeartbeatManagerTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/HeartbeatServiceTest.java
- Fixes #6343 
Ensure that the key information is not empty when saving the cluster information
When saving cluster information, determine whether the cluster tag, type, name is empty
When saving cluster information, determine whether the cluster tag, type, name is empty
*(example:)*
> [INLONG-6343][Manager] Fix the problem that the cluster tag is empty when saving cluster information

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongStreamApi.java
- Fixes #6395 
Before `Call<Response<Boolean>> delete(@Path("groupId") String groupId, @Path("streamId") String streamId);`
Should be `Call<Response<Boolean>> delete(@Query("groupId") String groupId, @Query("streamId") String streamId);
`
*(example:)*
- Does this pull request introduce a new …
> [INLONG-6395][Manager] Fix wrong annotation in InlongStreamApi delete method

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/autopush/AutoPushSourceOperator.java
- Fixes #6387 
- The auto push source type can be in status that does not make sense, for example, TO_BE_ISSUED_FROZEN.
- The auto push source fields are not correctly updated.
- Other adaptation issue.
- Replace all temporary status with end status for auto push source type.
- Correctly update stream source fields and inlong stream fields.
- Remove stream operation on sink update (**open for discussion**)
_So what's the appropriate time to restart after config updates ? Perhaps it's better be launched by end user in a separate call. According to the Single Responsibility Principle the service update handler should only perform no other than config updating._
> [INLONG-6387][Manager] Adapt auto-push source status and fix source field update

- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java
- Fixes #6373 
fix time value when data type is datetime and timestamp
fix time value when data type is datetime and timestamp
For timestamp, the debezium will first get the timestamp in the database time zone, and then convert it into UTC time zone.
So we only need to convert the timestamp in UTC time zone back to its origin timestamp
For zoned time stamp, we need to convert the zone time stamp using time zone set by user and  the reformat the zoned timestamp into a timestamp ended with Z since flink JsonToRowDataConverters can only parse a zoned timestamp ended with UTC "Z" time zone.
*(example:)*
- *Extended integration test for …
> [INLONG-6373][Sort] Fix the time value when data type is datetime and timestamp

- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/DynamicSchemaHandleOperator.java
[INLONG-6401][Sort] Bugfix:Schema update stuck in dead loop cause stackoverflow in multiple sink scences
- [INLONG-6401][Sort] Bugfix:Schema update stuck in dead loop cause stackoverflow in multiple sink scences
- Fixes #6401
*Explain here the context, and why you're making that change. What is the problem you're trying to solve*
*If can not handle this schema update, should not push data into next operator, just break the dead loop*
> [INLONG-6401][Sort] Schema update stuck in dead loop cause stackoverflow in multiple sink scences

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/StreamSinkClient.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/SinkRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeOperateHelper.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeService.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/AbstractSinkOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkService.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/ClickHouseSinkServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/DLCIcebergSinkServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/ElasticsearchSinkServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/GreenplumSinkServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/HBaseSinkServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/HDFSStreamSinkServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/HiveSinkServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/IcebergSinkServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/KafkaSinkServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/MySQLSinkServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/MySQLStreamSinkServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/OracleSinkServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/PostgreSQLSinkServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/SQLServerSinkServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/TDSQLPostgreSQLSinkServiceTest.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSinkController.java
- Fixes #6412
Add a parameter to control whether to initiate the process for StreamSink.
1. Add `startProcess` parameter in `SinkRequest`, which is used by saving or updating APIs;
2. Add `startProcess` in the query parameter for delete API.
`XxxSinkServiceTest`
> [INLONG-6412][Manager] Add a parameter to control whether to initiate the process for StreamSink

- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/DebeziumSourceFunction.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/MySqlSource.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/metrics/MySqlSourceReaderMetrics.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlRecordEmitter.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlSourceReader.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/split/MySqlMetricSplit.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/split/MySqlSplit.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/split/MySqlSplitSerializer.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/split/MysqlMetricSplit.java
- [INLONG-6318][Sort] Mysql connector support metric state snapshot and restore
- Fixes #6318 
* Mysql connector support metric state snapshot and restore
Mysql connector use the `SourceFunction` and the new [Source](https://cwiki.apache.org/confluence/display/FLINK/FLIP-27%3A+Refactor+Source+Interface) to read data.
We can use `CheckpointedFunction` to support metric state snapshot and restore when we use `SourceFunction`.
But We can't use `CheckpointedFunction` when use the new [Source](https://cwiki.apache.org/confluence/display/FLINK/FLIP-27%3A+Refactor+Source+Interface). 
So we address this problem by adding a `MySqlMetricSplit` to support metric state snapshot and restore.
* Add `MysqlMetricSplit` to support metric state snapshot and restore
* Modify `DebeziumSourceFunction` to …
> [INLONG-6318][Sort] MySQL connector supports snapshots and restores the metric state

- .github/ISSUE_TEMPLATE/bug-report.yml
- Fixes #6430
1.0.0 is not maintained, so remove it, and add the forward 1.4.0.
> [INLONG-6430][Release] Add the 1.4.0 version option for the bug report

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java
Manager splits ips is error.
Fix heart beat information error for ip.
- Fixes #6440 
Heartbeat information is error.
Add ips information.
> [INLONG-6440][Manager] Fix heart beat information error for ip

- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/kafka/InlongKafkaDTO.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/kafka/InlongKafkaInfo.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/kafka/InlongKafkaRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaResourceOperators.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaUtils.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperator.java
- Fixes #6451 
Using Kafka as MQ.
1. Remove the operation that creates a consumer for the Kafka topic, Kafka MQ does not need to create consumers in advance.
2. Rewrite getSourcesMap for the Kafka source operator.
> [INLONG-6451][Manager] Optimize the resource process of Kafka MQ

- inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamEntityMapper.xml
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkEntityMapper.xml
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/standalone/SortSourceStreamInfo.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/standalone/SortSourceStreamSinkInfo.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sort/SortServiceImplTest.java
- Fixes #6426
The old version of **_SortSourceService_**  only support one stream under one group.
SortServiceImplTest
- Does this pull request introduce a new feature? yes 
> [INLONG-6426][Manager] SortSourceService support multi stream under one group

- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/DebeziumSourceFunction.java
- [INLONG-6471][Sort] MySQL connector metric restore lost init data for using sourceFunction
- Fixes #6471 
* MySQL connector metric restore lost init data for using sourceFunction
* Modify `DebeziumSourceFunction`
> [INLONG-6471][Sort] MySQL connector metric restore lost init data for using sourceFunction

- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongConsume.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongConsumeImpl.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/ClientFactory.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongConsumeClient.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongConsumeApi.java
- inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java
- inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/InlongConsumeClientTest.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongConsumeController.java
- Fixes #6477 
Supplement the API that the manager web exists but the client does not exist for the manager client.
1. Add consume API in the manager client
2. Change the `delete` API return type to `boolean`
org.apache.inlong.manager.client.api.inner.InlongConsumeClientTest
> [INLONG-6477][Manager] Add consume API in the manager client

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarResourceOperator.java
- Fixes #6463 
Manager only create subscription and topic of one related cluster, which will result in consume faliure of sort-flink
*(example:)* …
> [INLONG-6463][Manager] Support create subscription and topic of multiple pulsar cluster

- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/kafka/ConsumeKafkaDTO.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/kafka/ConsumeKafkaInfo.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/kafka/ConsumeKafkaRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/ConsumeKafkaOperator.java
- Fixes #6505 
Support Kafka consumes type.
Add `ConsumeKafkaOperator` and kafka consume entity.
> [INLONG-6505][Manager] Support Kafka MQ in Inlong Consume

- inlong-distribution/src/main/assemblies/release.xml
- Fixes #6510
CK sql file do not need Initialize when using docker-compose.
> [INLONG-6510][Docker] Exclude ClickHouse SQL file in audit for docker mode

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ErrorCodeEnum.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupProcessService.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupService.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/group/UpdateGroupCompleteListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/group/UpdateGroupFailedListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamService.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java
- Fixes #5024
Improve the delete operation of InlongGroup.
1. Before starting the delete process, check whether the group can be updated.
2. At the end of the delete process, call the delete method to delete the inlong group. 
1. Before starting the delete process (`InlongGroupProcessOperation#deleteProcess`), first call the `InlongGroupServiceImpl#doDeleteCheck` method to check, and then start the process after the check is passed;
2. After the process succeeds, `UpdateGroupCompleteListener` calls the deletion method (`groupService.delete(groupId, operator)`.
> [INLONG-5024][Manager] Improve the delete operation of InlongGroup

- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
- Fixes #6533 
Fix the problem of manager did not distribute the task according to the clusterName
Query the tasks to be delivered based on the clustername.
> [INLONG-6533][Manager] Fix the problem of manager did not distribute the task according to the clusterName

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/JsonDynamicSchemaFormat.java
[INLONG-6537][Sort] Fix During DDL synchronization 'decimal' type loss of precision
- Title Example: [INLONG-6537][Sort] Fix During DDL synchronization 'decimal' type loss of precision
- Fixes #6537 
*Fix During DDL synchronization 'decimal' type loss of precision*
*Define a larger range 'decimal(15, 5)'.*
> [INLONG-6537][Sort] Fix the decimal type loss of precision during DDL synchronization

- inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/debezium/table/RowDataDebeziumDeserializeSchema.java
[INLONG-6507][Sort] Convert date to timestamp in oracle connector
- Fixes #6507
In debezium, the oracle date type will be read as the int64 type, but the oracle date type mapping is the debezium timestamp type, and the debezium timestamp type is the string format of date-time. So, we need to convert the int64 to the string format of date-time.
When parsing field value, if the field schema is date or timestamp type, we need to convert the filed value from the number of milliseconds to the string format of date-time. The main logic is as follows:
```java
/**
* extract the data with the format provided by debezium
*
* @param fieldValue
* @param schemaName
* @return the extracted data with schema
*/
private Object getValueWithSchema(Object fieldValue, String schemaName) {
if …
```
> [INLONG-6507][Sort] Convert date to timestamp in oracle connector

- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java
- Fixes #6529 
Fix microtime time zone error in mysql connector
The debezium convert micro time to utc, so we need to convert it back using utc time zone 
*(example:)*
> [INLONG-6529][Sort] Fix microtime time zone error in mysql connector

- .github/workflows/ci_docker.yml
- Fixes #6555
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> [INLONG-6555][CI] Update for set-output command is deprecated

- inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/debezium/table/RowDataDebeziumDeserializeSchema.java
- Fixes #6552
The debezium read oracle's timestamp type as a number of microseconds, we should convert it to a  string format of date-time.
If field schema is timestamp type, we need convert to  a string format of date-time from a number of microseconds.
> [INLONG-6552][Sort] Fix MicroTimestamp error in oracle connector

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNode.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/KafkaLoadNode.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNodeTest.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/KafkaLoadNodeTest.java
- inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJsonEnhancedDecodingFormat.java
- inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJsonEnhancedDeserializationSchema.java
- inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJsonEnhancedEncodingFormat.java
- inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJsonEnhancedSerializationSchema.java
- Title: [INLONG-6548][Sort] Optimize metadata field naming for format of canal-json
- Fixes #6548
Optimize metadata field naming for format of canal-json
Update the name of metadata  field
*(example:)* …
> [INLONG-6548][Sort] Optimize metadata field naming for format of canal-json

- .github/workflows/ci_chart_test.yml
- Fixes #6555
there is missed a place that needs to fix.
> [INLONG-6555][CI] Update for set-output command is deprecated (addendum)

- inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
- Fixes #6568 
Fix the problem that the status of the deleted source was incorrectly modified
After the group and stream workflows are configured, only update the status of data sources that have not been deleted.
> [INLONG-6568][Manager] Not modify the status of the deleted source

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupProcessService.java
- Fixes #6563 
Fix the problem of no error message was displayed when deleting a group failed
Get the execution result of deleting the group workflow, and throw an exception if the deletion fails
> [INLONG-6563][Manager] It should throw error info when deleting an inlong group failed

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/FieldType.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtils.java
- Fixes #6570 
Gets the string before the first occurrence of a `(`.
> [INLONG-6570][Manager] Ignore the length of the field when building sort config

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/OrderBatchPackProfileV0.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/SimpleBatchPackProfileV0.java
- Title: [INLONG-6592][DataProxy] Fix the problem of missing OrderEvent
- Fixes #6592 
- Fixes #6593
*(example:)* …
> [INLONG-6592][DataProxy] Fix the problem of missing OrderEvent

- inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/StartupStreamListener.java
- Fixes #6516 
This NPE is because the sort task has been started on the stream workflow. However, the process of starting Sort tasks has been initiated in `{@link StartupSortListener}` and sort tasks are only associated with InlongGroup, so it is unnecessary to start Sort tasks for InlongStream, this is a meaningless repetitive operation.
Skip starting sort in stream workflow
> [INLONG-6516][Manager] Skip starting the Sort task in the InlongStream workflow

- inlong-dataproxy/dataproxy-docker/Dockerfile
- inlong-dataproxy/dataproxy-docker/dataproxy-docker.sh
- Title Example: [INLONG-6604][Component] Title of the pull request
[INLONG-6604][DataProxy] Fix can not get the local IP in the docker container
- Fixes #6604
Fix can not get the local IP in the docker container
get the local IP in the docker container excluding the ip of the network segment starting with 30.
get the local IP in the docker container excluding the ip of the network segment starting with 30.
*(example:)* …
> [INLONG-6604][DataProxy] Fix can not get the local IP in the docker container

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/MetricOption.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/SinkMetricData.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/util/MetricStateUtils.java
- inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/sink/HBaseSinkFunction.java
- [INLONG-6574][Sort] Add dirty data metric for HBase
- Fixes #6574 
* Add dirty data metric for HBase
* Modify base of sort-connector module, add `dirtyRecordsOut` `dirtyBytesOut`.
* Modify HBase connector for metric computing, exception just print and count dirtyData.
> [INLONG-6574][Sort] Add dirty data metric for HBase

- inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/utils/FlumeConfigGenerator.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/SinkContext.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsCallbackListener.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsOutputChannel.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSink.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSinkContext.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSource.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestDefaultEvent2IndexRequestHandler.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsCallbackListener.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsChannelWorker.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsOutputChannel.java
- inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsSinkContext.java
- Title: [INLONG-5628][SortStandalone] Add buffer limit of sink dispatch queue
- Fixes #5628 
*(example:)* …
> [INLONG-5628][Sort] Add buffer limit for dispatch queue of the sink

- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsOutputChannel.java
- Fixes #6600 
When one stream is removed from or migrated to one sink, the unsent ES request will be retried and failed forever.
Check if the EsIdConfig is still exist before each send. If no, discard this request.
- Does this pull request introduce a new feature? / no
> [INLONG-6600][Sort] Fix dead lock when one stream is removed from or migrated to one sink

- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaFederationSinkContext.java
- Fixes #6586 
Got wrong node duration time of kafka sink.
Before : `long nodeDuration = currentTime - NumberUtils.toLong(Constants.HEADER_KEY_SOURCE_TIME, msgTime);`
Should be: `long nodeDuration = currentTime - currentRecord.getFetchTime();
`
- Does this pull request introduce a new feature? No
> [INLONG-6586][Sort] Fix wrong node duration time of kafka sink

- inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java
- Fixes #6621 
- 
Fixed the problem of source tasks are issued repeatedly
1.The workflow is executed without updating the data source in a SOURCE_NORMAL state.
2.When updating the data source, the data source state changes from SOURCE_NORMAL to TO_BE_ISSUED_RETRY.
> [INLONG-6621][Manager] Fixed the problem of source tasks are issued repeatedly

- inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/sink/HBaseDynamicTableSink.java
- inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/sink/HBaseSinkFunction.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/DebeziumSourceFunction.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/utils/CallbackCollector.java
- [INLONG-6636][Sort] Keep metric computing consistent for source MySQL and sink HBase
- Fixes #6636 
It generates four `RowKind` data: insert, update_before, update_after, delete when source is mysql cdc. 
We will count all `RowKind` data when computing metric of mysql cdc. HBase use upsert to write data and only need three `RowKind` data: insert, update_after, delete. Flink runtime will optimize code when sync mysql-cdc to HBase. Flink will use `DropUpdateBeforeFunction#filter` to drop `update_before` data. We need HBase computing four `RowKind` data to keep consistent with mysql-cdc. So we will change  return value to all `RowKind` type of `HBaseDynamicTableSink#getChangelogMode`.
* Modify HBaseDynamicTableSink#getChangelogMode.
* HBase skip `update_before` data .
* MySQL cdc metric …
> [INLONG-6636][Sort] Keep metric computing consistent for source MySQL and sink HBase

- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/ClickHouseSqlParserTest.java
- [INLONG-6594][Sort] Fix ClickHouse sort connector throw exception when source is change log stream
- Fixes #6594 
Fix ClickHouse sort connector throw exception when source is change log stream
* ClickHouse throw exception "Can't UPDATE key column id" when update source data. It means that alter table update ... where can't update primaryKey. [refer to](https://stackoverflow.com/questions/55976700/is-it-possible-to-update-primary-key-in-clickhouse-using-mergetree-engine) .
* ClickHouse throw exception "Table default.test_user doesn't exist". But jdbc-url have database name. https://github.com/ClickHouse/ClickHouse/issues/19278. Maybe we should specify database.
* Modify clickhouse Dialect
* Modify clickhouse load node UT, tableName should include 'database.table'
> [INLONG-6594][Sort] Fix ClickHouse connector throw exception when source is change log stream

- inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java
- Title: [INLONG-6639][Sort] Fix DynamicPulsarDeserializationSchema deserialize NPE problem when sourceMetricData is not initialized.
- Fixes #6639 
Fix DynamicPulsarDeserializationSchema deserialize NPE problem when sourceMetricData is not initialized.
Do not report metrics when sourceMetricData is not initialized.
> [INLONG-6639][Sort] Fix DynamicPulsarDeserializationSchema deserialize NPE problem when sourceMetricData is not initialized

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtyData.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtyOptions.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtyType.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/DirtySink.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/DirtySinkFactory.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/log/LogDirtySink.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/log/LogDirtySinkFactory.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/utils/FormatUtils.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/util/LabelUtils.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/util/PatternReplaceUtils.java
- inlong-sort/sort-connectors/base/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/dirty/FormatUtilsTest.java
- inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/util/LabelUtilsTest.java
- inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/util/PatternReplaceUtilsTest.java
Title: [INLONG-6617][Sort] Add common process for dirty data sink and supports log sink
- Fixes #6617 
Add common process for dirty data sink and supports log sink.
This piece is designed as follows:
1. Add option 'dirty.ignore' to determine whether to ignore dirty data, default is 'false'
2. If the option 'dirty.ignore' is 'true', it can be determined whether to enable sink for dirty data by option 'dirty.sink.enable'
3. If the option 'dirty.sink.enable' is 'true', The dirty data can be sink to the target system by option 'sink.dirty.connector'
4. Only supports 'log' sink for dirty data for now.
6. Add labels for dirty …
> [INLONG-6617][Sort] Add common process for dirty data sink and supports log sink

- inlong-sort/sort-connectors/base/pom.xml
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/DirtySinkFactory.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/log/LogDirtySink.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/log/LogDirtySinkFactory.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/s3/S3DirtySink.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/s3/S3DirtySinkFactory.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/s3/S3Helper.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/s3/S3Options.java
- inlong-sort/sort-connectors/base/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- licenses/inlong-sort-connectors/LICENSE
- pom.xml
- Title: [INLONG-6654][Sort] Supports s3 side-output for dirty data
- Fixes #6654
Supports s3 side-output for dirty data, through it, dirty data can be archived to s3.
This piece is designed as follows(some common process of dirty data side-output can view https://github.com/apache/inlong/pull/6618):
1. Add s3 side-output implements
In this part, i will add dirty data cache and flush to s3  periodically.
2. Add s3 side-output factory to create object of s3 side-output
1.Add the core class S3DirtySink for dirty data side-output
2.Add S3DirtySinkFactory to create S3DirtySink
3.Add S3Options to config S3DirtySink
4.Add …
> [INLONG-6654][Sort] Supports s3 side-output for dirty data

- bin/init-config.sh
Fixes #6685 
Modify the sed command using MacOS
When the init-config.sh script executes the sed command, it is necessary to first determine the current OS type and perform respective adaptations.
The `sed` command is used for substitution in MacOS.
```shell
sed -i ...
```
while GNU syntax can be used in Linux.
```shell
sed -i '' ...
```
> [INLONG-6685][Script] The bin/init-config.sh script compatible with MacOS

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/enums/ReadPhase.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/MetricOption.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/MetricState.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/SourceMetricData.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/phase/ReadPhaseMetricData.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SourceSubMetricData.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SourceTableMetricData.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/util/MetricStateUtils.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/DebeziumSourceFunction.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/MySqlSource.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlTableSource.java
- [INLONG-6584][Sort] Add read phase metric and table level metric for MYSQL
- Fixes #6584
The background is that when the entire database is migrated, the business needs to count the indicators of table granularity. Dynamically generate table granularity MetricGroup according to the schema of data records; internally maintain MetricGroup container to realize table granularity reporting indicators.
Inherit the original node-level indicators. Connectors with different table-level indicators use different table-level indicator entities, which are determined by the connector itself
> [INLONG-6584][Sort] Add read phase metric and table level metric for MySQL

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/log/LogDirtySinkFactory.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/s3/S3DirtySinkFactory.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/utils/DirtySinkFactoryUtils.java
- inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/DynamicKafkaSerializationSchema.java
- inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/KafkaDynamicSink.java
- inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/DynamicKafkaDeserializationSchema.java
- inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicSource.java
- inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicTableFactory.java
- inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/UpsertKafkaDynamicTableFactory.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/KafkaLoadSqlParseTest.java
- Title: [INLONG-6671][Sort] Supports dirty data side-output for kafka connector
- Fixes #6671
Supports dirty data side-output for kafka connector.
In this part:
2. It is needs to determine whether it is dirty data in the connector.
3. Side output dirty data by the 'DirtySink' dependents on the configured, the built-in side-out of dirty data has 'LogDirtySink'(https://github.com/apache/inlong/pull/6618) and 'S3DirtySink'(https://github.com/apache/inlong/pull/6655).
1. Create dirty sink and inject it for kafka source and kafka sink
2. Add dirty handle for …
> [INLONG-6671][Sort] Supports dirty data side-output for kafka connector

- inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/utils.cc
- Fixes #6638
Supplementary repair, adjust the verification rules
> [INLONG-6638][TubeMQ] C++ client supports filtering consume with the "-" character (addendum)

- inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkService.java
- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/Entrance.java
- Title: [INLONG-6675][Sort] Sort does not report metrics because Flink Sql missing the `metrics.audit.proxy.hosts` parameter
- Fixes #6675 
Fix `metrics.audit.proxy.hosts` parameter missing problem.
Pass the `metrics.audit.proxy.hosts` parameter to `org.apache.inlong.sort.Entrance`
> [INLONG-6675][Sort] Add metrics.audit.proxy.hosts option to support report metrics

- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
[ [INLONG-6690] doris multiple sink migration throws exception at enable batch delete](https://github.com/apache/inlong/issues/6690) 
A one liner bugfix which fixes the issue of some problems encountered when doing multiple sink migration
> [INLONG-6690][Sort] Fix the multiple migrations of Doris when batch delete was enabled

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/JobProfile.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
- inlong-agent/agent-common/src/test/java/org/apache/inlong/agent/conf/TestConfiguration.java
- inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/Job.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java
- inlong-common/pom.xml
- inlong-common/src/main/java/org/apache/inlong/common/enums/DataReportTypeEnum.java
- inlong-common/src/main/java/org/apache/inlong/common/enums/TaskTypeEnum.java
- inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/DataConfig.java
- inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/DataProxyTopicInfo.java
- inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/MQClusterInfo.java
- [INLONG-6681][Agent] Handle different sink type configurations
- Fixes #6681 
- Let `Agent` support different sink type, such as `DataProxy` and Pulsar etc.
- Parse and handle sink configuration of agent job
- Based sink configuration, choose proxySend or not
*(example:)* …
> [INLONG-6681][Agent] Handle different sink type configurations

- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaProducerCluster.java
- Fixes #6706 
Fix wrong kafka sink client id， the same client id will result in low throughput
*(example:)*
> [INLONG-6706][Sort] Fix the wrong client id of Kafka sink

- docker/docker-compose/docker-compose.yml
Fixes #6689 
Specify the `--platform` parameter of the `MySQL` image.
By modifying the `--platform` parameter of the `MySQL` image, it can simulate `x86` instructions to build a docker image under different system architectures, and only need the same `docker-compose` script
> [INLONG-6689][Docker]  Support running docker-compose on Arm Chip

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
- Fixes #6732 
SortSdk topic properties should get from stream_sink instead of inlong_stream.
*(example:)*
> [INLONG-6732][Manager] Fix wrong SortSDK topic properties

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtyType.java
- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicTableFactory.java
- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicTableSink.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DorisExtractNodeToDorisLoadNodeTest.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DorisMultipleSinkTest.java
- Fixes #6724
Supports dirty data side-output for Doris sink.
In this part:
1. Create a dirty sink and inject it into Doris sink
2. Add dirty handle for 'DorisDynamicSchemaOutputFormat'
3. Add a unit test for this …
> [INLONG-6724][Sort] Supports dirty data side-output for doris sink

- pom.xml
Bump version of pulsar-connector to 1.13.6.2
- Fixes #6754 
Currently, the release candidate version used in sort-connector/pulsar may have unknown bugs, upgrade to a stable version
Version 1.13.6.2 is close to the currently used stable version, update to this version
*(example:)* …
> [INLONG-6754][Sort] Bump version of pulsar-connector to 1.13.6.2

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/SinkMetricData.java
- inlong-sort/sort-connectors/hive/src/main/java/org/apache/inlong/sort/hive/filesystem/AbstractStreamingWriter.java
- Fixes #6657 
Add dirty data metric for Hive.
1. Add `DirtyRecords` and `DirtyBytes` when init `MetricOption`.
2. Calculate dirty data when an exception is caught.
> [INLONG-6657][Sort] Add dirty data metric for Hive

- inlong-common/src/main/java/org/apache/inlong/common/heartbeat/ComponentHeartbeat.java
- inlong-common/src/main/java/org/apache/inlong/common/heartbeat/HeartbeatMsg.java
- inlong-dataproxy/conf/common.properties
- inlong-dataproxy/conf/dataproxy-pulsar.conf
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/RemoteConfigManager.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/ConfigConstants.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/heartbeat/HeartbeatManager.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneProducer.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/ConfStringUtils.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java
- Fixes #6738]
The new sink layer does not integrate well with the default tcp/http source, such as 
- channel event type not match
- cluster zone tag by default is empty, leading to NPE
- null pulsar token not supported
- namespace is specified in the cluster level other than the group level
- other problems
Fix the problems mentioned above
> [INLONG-6738][DataProxy] New sink architecture integration

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtyData.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtyType.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/log/LogDirtySink.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/s3/S3DirtySink.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/utils/FormatUtils.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/sink/MultipleSinkOption.java
- inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/dirty/FormatUtilsTest.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/FlinkDynamicTableFactory.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/IcebergTableSink.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/FlinkSink.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/DynamicSchemaHandleOperator.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergMultipleStreamWriter.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergSingleStreamWriter.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/IcebergNodeSqlParserTest.java
- Title: [INLONG-6765][Sort] Supports dirty data side-output for iceberg sink
- Fixes #6765 
Supports dirty data side-output for iceberg sink.
In this part:
1. Create a dirty sink and inject it into Iceberg sink
2. Add dirty handle for 'IcebergSingleStreamWriter' and 'DynamicSchemaHandleOperator'
3. Add a unit test for this …
> [INLONG-6765][Sort] Supports dirty data side-output for Iceberg sink

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/SinkType.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/starrocks/StarRocksSink.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/starrocks/StarRocksSinkDTO.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/starrocks/StarRocksSinkRequest.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/LoadNodeUtils.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/starrocks/StarRocksSinkOperator.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/StarRocksConstant.java
- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/StarRocksLoadNode.java
- [INLONG-6745][Manager] Support StarRocks load node management
- Fixes #6745
Inspired by doris-inlong, starrocks-inlong can also support transferring all tables in one database on time.
StarRocks FE api has changed, been different from Doris FE api. If you use doris-cdc-inlong to handle StarRocks tables writing, it will give a error: http://x.x.x.x:xxxx/api/backends?is_alive=true failed. java.io.IOException: Failed to get response from Doris. That is why we need a sarrocks-inlong connector.
This PR provides StarRocks load node management is InLong Manager.
1. SinkType has new STARROCKS type.
2. manager-pojo has new StarRocksSink, StarRocksSinkDTO and StarRocksSinkRequest classes.
3. LoadNodeUtils has new createLoadNode method for creating StarRocksLoadNode object.
4. manager-service has …
> [INLONG-6745][Manager] Support StarRocks load node management

- inlong-sort/sort-connectors/hive/src/main/java/org/apache/inlong/sort/hive/HiveTableSink.java
- inlong-sort/sort-connectors/hive/src/main/java/org/apache/inlong/sort/hive/filesystem/AbstractStreamingWriter.java
- inlong-sort/sort-connectors/hive/src/main/java/org/apache/inlong/sort/hive/filesystem/CompactFileWriter.java
- inlong-sort/sort-connectors/hive/src/main/java/org/apache/inlong/sort/hive/filesystem/StreamingFileWriter.java
- inlong-sort/sort-connectors/hive/src/main/java/org/apache/inlong/sort/hive/filesystem/StreamingSink.java
- inlong-sort/sort-connectors/hive/src/main/java/org/apache/inlong/sort/hive/table/HiveTableInlongFactory.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/FlinkSqlParserTest.java
- Title: [INLONG-6795][Sort] Supports dirty data side-output for hive sink
- Fixes #6795
Supports dirty data side-output for hive sink.
In this part:
1. Create a dirty sink and inject it into hive sink
2. Add dirty handle for 'AbstractStreamingWriter'
3. Add a unit test for this …
> [INLONG-6795][Sort] Supports dirty data side-output for hive sink

- inlong-sort/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/FileSystemTableFactory.java
- inlong-sort/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/FileSystemTableSink.java
- inlong-sort/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/stream/AbstractStreamingWriter.java
- inlong-sort/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/stream/StreamingFileWriter.java
- inlong-sort/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/stream/StreamingSink.java
- inlong-sort/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/stream/compact/CompactFileWriter.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/FlinkSqlParserTest.java
- Title: [INLONG-6797][Sort] Supports dirty data side-output for filesystem sink
- Fixes #6797
Supports dirty data side-output for filesystem sink.
In this part:
1. Create a dirty sink and inject it into filesystem sink
2. Add dirty handle for 'AbstractStreamingWriter'
3. Add a unit test for this
*(Please pick either of the …
> [INLONG-6797][Sort] Supports dirty data side-output for filesystem sink

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/FieldType.java
- Title: [INLONG-6804][Manager] Workflow initialization threw IllegalArgumentException: Unsupported FieldType text or keyword
- Fixes #6804 
Fix workflow initialization threw IllegalArgumentException: Unsupported FieldType text or keyword
Add `TEXT` and  `KEYWORD` data type.
> [INLONG-6804][Manager] Workflow initialization threw IllegalArgumentException: Unsupported FieldType text or keyword

- inlong-audit/audit-common/pom.xml
- inlong-sdk/sdk-common/pom.xml
- inlong-tubemq/tubemq-core/pom.xml
- pom.xml
- Fixes #6810 
Unify versions of `os-maven-plugin` and `protobuf-maven-plugin`.
Bump up `os-maven-plugin` to version `1.6.0` and `protobuf-maven-plugin` to `0.6.1`
-no docs needed
> [INLONG-6810][POM] unify versions of os-maven-plugin and protobuf-maven-plugin

- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsOutputChannel.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSinkContext.java
- Fixes #6770 
Optimize default EsSink params
Add more Es bulkprocesser config params.
Optimize the default params: 
1. Add parallelism
2. Lower the upper bound of length of each field.
> [INLONG-6770][Sort] Optimize EsSink params

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java
- Title : [INLONG-6835][Manager] Error about backup mq resource of DataProxy getAllConfig interface.
- Fixes #6835 
*(example:)*
- If a feature is not documented yet in this PR, please create a follow-up issue …
> [INLONG-6835][Manager] Fix the error about backup mq resource of DataProxy getAllConfig interface

- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/es/ElasticsearchSinkDTO.java
- Title: [INLONG-6815][Manager] Elasticsearch port parameter is missing
- Fixes #6815 
Fix elasticsearch port parameter is missing problem.
`ElasticsearchSinkDTO` add get `port` parameter.
> [INLONG-6815][Manager] Elasticsearch port parameter is missing

- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaFederationSinkContext.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaFederationWorker.java
- Fixes #6839 
The remain event will stay in memory forever since there is no any idConfig related to this event when stream offline.
This will cause memory leak and poor performance.
Just ack and discards those events which does not relate any idConfigs.
> [INLONG-6839][Sort] Clean up remain event when the related stream is offline

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/util/MetricStateUtils.java
- inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/table/RowElasticsearchSinkFunction.java
- Title: [INLONG-6813][Sort] MetricStateUtils threw NPE when write to es and no dirtyRecordsOut counter
- Fixes #6813 
Fix metricStateUtils threw NPE when write to es and no dirtyRecordsOut counter.
Register a `DIRTY` counter.
> [INLONG-6813][Sort] MetricStateUtils threw NPE when write to es and no dirtyRecordsOut counter

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/manager/InlongMultiTopicManager.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/manager/InlongSingleTopicManager.java
- Fixes #6830 
One dirty stream sink should not affect other sdk configs
Catch exceptions in **InlongTopic** level,  instead of **CacheZone** level. All dirty stream sinks will result in a empty InlongTopic in the related **CacheZones**. 
SortSdk just fillter these empty topics.
> [INLONG-6830][Manager] Optimize the config managerment of SortSDK

- inlong-dataproxy/dataproxy-docker/dataproxy-docker.sh
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/BatchPackManager.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSink.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/SimpleBatchPackProfileV0.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/kafka/KafkaHandler.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/tube/TubeHandler.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
- Fixes #6848
- data is converted to pb by default, support original default protocol and headers under the new sink layer
- fix script config file name error
> [INLONG-6848][DataProxy] Adapt original InlongMsg protocol and headers

- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/debezium/task/MySqlSnapshotSplitReadTask.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/assigners/ChunkSplitter.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/split/MySqlSnapshotSplit.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlTableInlongSourceFactory.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/AllMigrateTest.java
- Fixes #6842 
Fixes #6842
A minor modification and improvemnt for Dblog : https://netflixtechblog.com/dblog-a-generic-change-data-capture-framework-69351fb9099b 
1、remove the constraint in mysql-cdc 2.0 for primary key
2、for those tables which don't contain primary key, split the whole table as a chunk during split stage
3、since there's no need for the MySqlSourceEnumerator to upsert binlog with the snapshot data for a whole table 
split , just let the highwatermark equals to the lowwatermark to escape the upsert stage.
run AllmigrateTest
- If a feature is not documented …
> [INLONG-6842][Sort] Improve mysql-cdc2.0 to support tables without primary key

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortClusterServiceImpl.java
- Fixes #6827 
One dirty stream sink record should not result in config failed of cluster level, just skip the dirty record itself.
SortClusterService catch exceptions of parsing dirty stream sink and return a empty id params, instead of throw them to higher level. 
In this way, the dirty stream sink records will only affect itself, rather than resulting in cluster level config failure.
> [INLONG-6827][Manager] Optimize the config managerment of SortStandalone

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtySinkHelper.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtyType.java
- inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/ElasticsearchSink.java
- inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/table/Elasticsearch6DynamicSink.java
- inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/table/Elasticsearch6DynamicSinkFactory.java
- inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/ElasticsearchSink.java
- inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7DynamicSink.java
- inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7DynamicSinkFactory.java
- inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/ElasticsearchSinkBase.java
- inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/table/RowElasticsearchSinkFunction.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/ElasticsearchSqlParseTest.java
- Title: [INLONG-6869][Sort] Supports dirty data side-output for elasticsearch sink
- Fixes #6869
Supports dirty data side-output for elasticsearch sink.
In this part:
1. Create a dirty sink and inject it into elasticsearch sink
2. Add dirty handle for 'ElasticsearchSinkBase' and 'RowElasticsearchSinkFunction'
3. Add a unit test …
> [INLONG-6869][Sort] Supports dirty data side-output for elasticsearch sink

- licenses/inlong-agent/LICENSE
- licenses/inlong-audit/LICENSE
- licenses/inlong-dataproxy/LICENSE
- licenses/inlong-manager/LICENSE
- licenses/inlong-sort-connectors/LICENSE
- licenses/inlong-sort-standalone/LICENSE
- licenses/inlong-tubemq-server/LICENSE
- pom.xml
- Fixes #6867
Protobuf Java vulnerable to Uncontrolled Resource Consumption
> [INLONG-6867][CVE] Bump protobuf to 3.19.6 to fix Java vulnerable

- inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/DynamicKafkaSerializationSchema.java
- inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/DynamicKafkaDeserializationSchema.java
- Title: [INLONG-6884][Sort] Add dirty message for kafka connector
- Fixes #6884
Add dirty message for kafka connector. The dirty message is the cause of dirty data, in this part, i will ingest it for kafka connector and it can be used by '${DIRTY_MESSAGE}' if needed.
Add  dirty message handle for 'DynamicKafkaDeserializationSchema' and 'DynamicKafkaSerializationSchema'
*(example:)*
- Does this pull …
> [INLONG-6884][Sort] Add dirty message for kafka connector

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/ConfigConstants.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mqzone/impl/pulsarzone/PulsarClusterProducer.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/federation/PulsarProducerCluster.java
- inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/utils/MockUtils.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/ConfigConstants.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClientConfig.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/InlongTopicManagerImpl.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/manager/InlongMultiTopicManager.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/manager/InlongSingleTopicManager.java
- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarProducerCluster.java
- Title Example: [INLONG-6907][SortStandalone] Support to close StatsRecorder of pulsar client
- Fixes #6907 
*(example:)* …
> [INLONG-6907][SortStandalone] Support to close StatsRecorder of pulsar client

- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CreateCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/DescribeCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/ListCommand.java
- inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/TransformInfo.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/transform/MultiDependencyTransform.java
- inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/transform/SingleDependencyTransform.java
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/TransformConstants.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/StreamTransform.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/deduplication/DeDuplicationDefinition.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/encrypt/EncryptDefinition.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/filter/FilterDefinition.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/joiner/JoinerDefinition.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/replacer/StringReplacerDefinition.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/splitter/SplitterDefinition.java
- Fixes #6918 
Command tools support Transform when creating inlong group.
1. Add `@NoArgsConstructor` and `TransformConstants` for Jackson deserialization.
2. Add `TransformInfo` for Jackson serialization.
> [INLONG-6918][Manager] Command tools support Transform

- inlong-dashboard/src/locales/cn.json
- inlong-dashboard/src/locales/en.json
- inlong-dashboard/src/metas/groups/defaults/Kafka.ts
- inlong-dashboard/src/metas/groups/defaults/Pulsar.ts
- inlong-dashboard/src/metas/groups/defaults/TubeMq.ts
- Fixes https://github.com/apache/inlong/issues/6916
> [INLONG-6916][Dashboard] MQ type adds partition limit

- inlong-dashboard/src/locales/cn.json
- inlong-dashboard/src/locales/en.json
- inlong-dashboard/src/metas/clusters/defaults/Pulsar.ts
> [INLONG-6930][Dashboard]Create a new cluster token placeholder configuration i18n

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/JsonDynamicSchemaFormat.java
- Title: [INLONG-6952][Sort] Cancel parsing fault tolerance for JsonDynamicSchemaFormat
- Fixes #6952
Cancel parsing fault tolerance for JsonDynamicSchemaFormat. The variable replacement here is mainly used for
multi-sink scenario synchronization destination positioning, so the value of null cannot be ignored.
Cancel parsing fault tolerance for 'JsonDynamicSchemaFormat'
*(example:)*
- Does this pull …
> [INLONG-6952][Sort] Cancel parsing fault tolerance for JsonDynamicSchemaFormat

- inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkService.java
- inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/enums/Constants.java
- inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/RestartSortListener.java
- inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/RestartStreamListener.java
- inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/StartupSortListener.java
**[INLONG-6909][Manager] Rename Flink Job to avoid conflicts**
- Fixes #6909 
Generate job name in format `InLong-Sort-<GroupId>` from `org.apache.inlong.manager.pojo.workflow.form.process.GroupResourceProcessForm`
*(example:)*
- If a feature is not documented yet in this PR, please create a follow-up issue for adding …
> [INLONG-6909][Manager] Rename Flink Job to avoid conflicts

- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/NativeFlinkSqlParser.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/NativeFlinkSqlParserTest.java
- Title: [INLONG-6968][Sort] SqlParseException: Encountered "\\'".
- Fixes #6968 
Fix SqlParseException: Encountered "\\'".
`NativeFlinkSqlParser` splits sql statements by semicolon and newline character.
> [INLONG-6968][Sort] Fix the SqlParseException: Encountered "\'"

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SinkSubMetricData.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SinkTableMetricData.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SinkTopicMetricData.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/util/MetricStateUtils.java
- inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/manager/StarRocksSinkManager.java
- inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/StarRocksDynamicSinkFunction.java
- StarRocks supports table level metric
- Fixes #6899
StarRocks supports table level metrics.
1. `SinkSubMetricData` and `SinkTableMetricData` provide method to collect the metrics,   inspired by SourceSubMetricData and SourceTableMetricData.
2. Replaced SinkMetricData with SinkTableMetricData in `StarRocksSinkManager` and `StarRocksDynamicSinkFunction`.
*(example:)*
- If a feature …
> [INLONG-6899][Sort] StarRocks supports table level metric

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SourceTableMetricData.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/DebeziumSourceFunction.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/metrics/MySqlSourceReaderMetrics.java
- inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/debezium/DebeziumSourceFunction.java
- inlong-sort/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/cdc/postgres/DebeziumSourceFunction.java
[INLONG-7006][Sort] Optimize reading metric at the table level, and the metric label is passed in by a specific connector.
- Fixes #7006
Optimize reading metric at the table level, and the metric label is passed in by a specific connector.
The indicator label of the base class is passed in by the specific connector used to avoid introducing too many labels in the base class.
> [INLONG-7006][Sort] Optimize reading metric at the table level, and the metric label is passed in by a specific connector.

- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/ClickHouseDialect.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/OracleDialect.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/SqlServerDialect.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/TDSQLPostgresDialect.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingComm.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingOutputFormat.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/AbstractJdbcDialect.java
- [INLONG-6978][Sort] get PG primary keys from connection query db
- Fixes #6978 
Get primary key from exception can't meet all conditions, change to query db.
1.  AbstractJdbcDialect add getPkNamesFromDb function: get getPkNames from query db.tb.
2. JdbcMultiBatchingOutputFormat query getPkNamesFromDb when getOrCreateStatementExecutor.
> [INLONG-6978][Sort] Get primary keys for PostgreSQL

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java
- Fixes #7028 
Failed to query the task status when one of them have deleted.
Skip this task, guaranteed to return normal information.
> [INLONG-7028][Manager] Fix query task status list failed

- inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaFederationSinkContext.java
- Fixes #7037
Make sure that when one stream offline from a task, the remain event will be ack and commit successfully.
When the related topic does not exist, should return **_Null Kafka IdConfig_** instead of throw exception.
- Does this pull request introduce a new feature?  no
> [INLONG-7073][Sort]  Remove exception when topic does not exist

- inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java
- Fixes #7035
The message sender generate repeated msg id when in concurrency.
Make it globally unique by static sharing
> [INLONG-7035][SDK] Fix the id generator not globally unique for DataProxy

- inlong-dashboard/src/locales/cn.json
- inlong-dashboard/src/locales/en.json
- inlong-dashboard/src/metas/streams/common/StreamDefaultInfo.ts
- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/ExtractNodeUtils.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/StreamSource.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamExtParam.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamInfo.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/pulsar/PulsarSourceOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/tubemq/TubeMQSourceOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java
*[INLONG-6998][Dashboard][Manager] Support ignore deserialization erro…*
- Fixes #6998 
When the reported message contains garbage data, any problem of the message format will cause the Flink job to automatically restart until the data in the MQ is repaired; 
Otherwise, all the data is piled into the MQ to continue processing.
This option `ignoreParseError` is exposed in the hope that the user can adjust it according to the data format requirements.
Pass the attribute `ignoreParseError` to the concrete implementation of format, which is enabled by default.
The follow sql generated:
```sql
CREATE TABLE `table_s-v3`(
`uid` INT,
`uname` STRING,
`cata` STRING,
`eid` STRING,
`fee` DOUBLE,
`ftime` TIMESTAMP(2))
WITH (
'inlong.metric.labels' = 'groupId=sg-v2&streamId=s-v3&nodeId=s-v3', …
```
> [INLONG-6998][Dashboard][Manager] Support ignore deserialization error

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/InlongConsumeInfo.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/pulsar/ConsumePulsarInfo.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/AbstractConsumeOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/ConsumePulsarOperator.java
Fixes #7067 
Data consumption details provide serverUrl, adminUrl and topic information.
- Provide the complete topic name, serverUrl and adminUrl when obtaining the topic of data consumption.
- Remove the topic prefix when saving topic information.
> [INLONG-7067][Manager] Provide MQ cluster info in consumption details

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SinkTableMetricData.java
- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
- inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/manager/StarRocksSinkManager.java
- inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/manager/StarRocksStreamLoadVisitor.java
- inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/StarRocksDynamicSinkFunction.java
- inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/StarRocksDynamicTableSink.java
- inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/StarRocksDynamicTableSinkFactory.java
- [INLONG-7083][Sort] StarRocks connector supports dirty data archives and metric
- Fixes #7083
StarRocks connector supports dirty data archives
1. `StarRocksDynamicTableSinkFactory.java` has new DirtyOptions, DirtySink and DirtySinkHelper objects.
2. `StarRocksDynamicTableSink.java`, `StarRocksDynamicSinkFunction.java` and `StarRocksSinkManager.java` get `DirtySinkHelper` tool from `StarRocksDynamicTableSinkFactory` one by one.
3. `StarRocksSinkManager.java` uses `DirtySinkHelper` to write dirty data and upload dirty data metrics when catching exceptions.
*(example:)*
- …
> [INLONG-7083][Sort] StarRocks connector supports dirty data archives and metric

- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/converter/AbstractJdbcRowConverter.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/converter/mysql/MySQLRowConverter.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/MySQLDialect.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingOutputFormat.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDialects.java
- Fixes #7076
- Users want to real time sync multi-tables data in mongoDB、KAFKA etc to MySql or other JDBC based databases in many case. We need multi table-sink connector for MySql.
- Based on flink-connector-jdbc, sort-connector-jdbc can sink data to MySql in two formats: canal-json.
- Add multi table sink for MySQL
- add MySQLRowConverter, MySQLDialect
- modify JdbcMultiBatchingOutputFormat and AbstractJdbcRowConverter to Support Mysql data type
*(example:)*
```sql
CREATE TABLE cdc_mysql_source (
`data` BYTES METADATA FROM 'meta.data_canal' VIRTUAL
) WITH (
'inlong.metric.labels' = 'groupId=1&streamId=1&nodeId=1',
'migrate-all' = 'true',
'connector' = 'mysql-cdc-inlong',
'scan.incremental.snapshot.enabled' = …
```
> [INLONG-7076][Sort] Add multi table sink for MySQL

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtyType.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingOutputFormat.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDynamicOutputFormatBuilder.java
- [INLONG-7075][Sort] Add table level metric and dirty data backup for PostgreSQL
- Fixes #7075 
*(example:)* …
> [INLONG-7075][Sort] Add table level metric and dirty data backup for PostgreSQL

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/s3/S3DirtySink.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/s3/S3Helper.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SinkTableMetricData.java
- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
Fixes #7061
Design:
for all incoming dirty data, try to parse and add table level metrics, no matter what the data is. If it fails for any reason, add global metrics instead.
the try block only works if 
1) the dirty data is rowdata, if deserialization causes error/npe, then just add global metric
2) the task is multiple sink，since table level metric is meaningless for single table tasks.
for single table and unparsable dirty data, either null pointer or ioexception will be thrown. In either case, just add node level metrics instead.
> [INLONG-7061][Sort] Support table level metrics for Apache Doris connector and add dirty metrics

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SinkTableMetricData.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/FlinkSink.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/DynamicSchemaHandleOperator.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergMultipleStreamWriter.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergSingleStreamWriter.java
[INLONG-7073][Sort] Support table level metrics for Apache Iceberg connector
- [INLONG-7073][Sort] Support table level metrics for Apache Iceberg connector
- Fixes #7073 
*Support table level metrics for Apache Iceberg connector*
> [INLONG-7073][Sort] Support table level metrics for Apache Iceberg connector

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/mysql/MySQLSinkOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperator.java
- Fixes #7151 
1. Create Kafka extract node failed
2. Create Mysql load node failed
1. Get info from the data node when Mysql JDBC URL is empty.
2. Add judgment conditions to avoid repeated assignments.
> [INLONG-7151][Manager] Fix failure to create node when init sort

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNode.java
- inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNodeTest.java
- [INLONG-7103][Sort] Support InLongMsg format in Kafka
- Fixes #7103 
*(example:)*
> [INLONG-7103][Sort] Support InLongMsg format in Kafka

- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/ClientContext.java
- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/pulsar/PulsarSingleTopicFetcher.java
- Fixes #7154 
Get SortSdk metric item fail when the topic does not exist, which will lead to null pointer exception.
1. Make sure the topic is not null
2. Catch exceptions when fetch and process MQ messages, ensure the fetcher thread will not exit unexpectedly.
> [INLONG-7154][SDK] Fix metric report failure when topic does not exist

- inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/ClientPipelineFactory.java
- inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderChannel.java
- inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/util/Config.java
- [INLONG-7159][Audit] Fix the problem of audit sdk create thread  when the audit service is not deployed 
- Fixes  #7159
> [INLONG-7159][Audit] Fix the problem of audit sdk create thread not deployed

- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/utils/RecordUtils.java
- Fixes #7161 
Mysql connector only output the latest record in snapshot stage for table without primary key
when normalizedSplitRecords, use a list to store records without primary key rather than a map with format <key, record> ,
since the key is null for table without primary key and the records would overide others 
run allmigrateTest
> [INLONG-7161][Sort] Fix bug that Mysql connector only output the latest record in snapshot stage for table without primary key

- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergSingleFileCommiter.java
[INLONG-7172][Sort] Fix new table write into iceberg failed
- Fixes #7172 
When a new table is added in the Flink job,  and then restart the job with status. The new table can be successfully written to iceberg.
The new table has no state after the job is restarted, so we need to ignore the subsequent operations when the state is restored.
```java
if (context.isRestored()) {
// New table doesn't have restored flink job id.
if (!jobIdState.get().iterator().hasNext()) {
return;
}
/**
* ...
*/
}
```
> [INLONG-7172][Sort] Fix new table write into iceberg failed

- inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/BaseExample.java
- inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/ut/BaseTest.java
- inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java
- inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/kafka/KafkaClusterDTO.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/pulsar/PulsarClusterDTO.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/pulsar/PulsarClusterInfo.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/pulsar/PulsarClusterRequest.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupBriefInfo.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/pulsar/InlongPulsarDTO.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/pulsar/InlongPulsarInfo.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/pulsar/InlongPulsarRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/KafkaClusterOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/PulsarClusterOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/ConsumePulsarOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupOperator4Pulsar.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/consume/apply/ApproveConsumeProcessListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarResourceOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/pulsar/PulsarSourceOperator.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceTest.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/consume/InlongConsumeServiceTest.java
- Fixes #5776
**Add tenant param to InlongGroup that uses Pulsar.**
Currently, the tenant parameter is stored in the Pulsar cluster information, which is not reasonable.
Because a Pulsar cluster supports many tenants, just like its namespaces and topics, **it is a one-to-many relationship with the cluster, not a one-to-one relationship.**
1. Add `tenant` param for `InlongPulsarInfo`.
2. First, get the tenant from `InlongPulsarInfo`, and then get it from the `PulsarCluster`, finally, use the default tenant `public`.
> [INLONG-5776][Manager] Add tenant param to InlongGroup that uses Pulsar

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/JsonToRowDataConverters.java
Fix time zone incorrect.
- Fixes #7186 
The data with datetime and timestamp format are written to iceberg, and the time zone is incorrect.
Refer to jdbc's handling of timestamp:
class path: `org.apache.inlong.sort.jdbc.internal.JdbcMultiBatchingOutputFormat`
```java
case TIMESTAMP_WITH_LOCAL_TIME_ZONE:
TemporalAccessor parsedTimestampWithLocalZone =
SQL_TIMESTAMP_WITH_LOCAL_TIMEZONE_FORMAT.parse(fieldValue);
LocalTime localTime = parsedTimestampWithLocalZone.query(TemporalQueries.localTime());
LocalDate localDate = parsedTimestampWithLocalZone.query(TemporalQueries.localDate());
record.setField(i, TimestampData.fromInstant(LocalDateTime.of(localDate, localTime)
.toInstant(ZoneOffset.UTC)));
break;
case TIMESTAMP_WITHOUT_TIME_ZONE:
fieldValue = fieldValue.replace("T", " ");
TimestampData …
```
> [INLONG-7186][Sort] Fix time zone incorrect

- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTO.java
- inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTOTest.java
- Fixes #7213 
Add a check to the URL encoding of mysql JDBC URL.
1.Add a check to the URL encoding of mysql JDBC URL.
2.Add checks for three unsafe parameters that can cause arbitrary file reading problems.  They are
allowLoadLocalInfile, allowUrlInLocalInfile, allowLoadLocalInfileInPath.
> [INLONG-7213][Manager] Add encoding check to the MySQL JDBC URL

- inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTO.java
- Fixes #7222 
Decode the MySQL JDBC URL thoroughly
Decode the MySQL JDBC URL thoroughly
> [INLONG-7222][Manager] Decode the MySQL JDBC URL thoroughly

- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/EqualityFieldKeySelector.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/FlinkSink.java
- licenses/inlong-sort-connectors/LICENSE
Iceberg connector supports keyby with the primary key
- Fixes #7197 
To improve the writing efficiency, iceberg supports the use of primary keys as keyby to distribute records.
Implement a KeySelector that makes keyby according to the primary key. For details, see the `EqualityFieldKeySelector.class`
> [INLONG-7197][Sort] Iceberg connector supports keyby with the primary key

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/AllCacheClusterSelector.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/BatchPackManager.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/CacheClusterSelector.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneProducer.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSink.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSinkContext.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneWorker.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/RandomCacheClusterSelector.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/kafka/KafkaHandler.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java
- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/tube/TubeHandler.java
- Title: [INLONG-7231][DataProxy] DataProxy add selector policy of cache cluster list
- Fixes #7231 
- When DataProxy send data to all cache clusters, if the number of Pulsar topic is enough, Zookeeper of Pulsar will go to OutOfMemory because the metadata of PulsarProducer is too big.
- DataProxy will only create one Pulsar client for a cache cluster, and only create one PulsarProducer for a Pulsar topic.
- DataProxy can send data to subset of cache cluster list.
- The selector policy can be configurable and extensibility.
*(example:)*
- *Extended integration test for recovery after broker …
> [INLONG-7231][DataProxy] Add selector policy of cache cluster list

- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/metrics/MySqlSourceReaderMetrics.java
- inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlRecordEmitter.java
- Fixes #7250
At present, the reading stage is determined by the identification of the data itself, but when the stock data has been synchronized, if there is no incremental data, it is impossible to perceive whether to enter the incremental stage.
Use the heartbeat event to judge the time to enter the binlog stage, so as to optimize the indicator that MySQL enters the incremental stage when the whole database is migrated.
> [INLONG-7250][Sort] Output the read phase metrics for MySQL reader

- inlong-dashboard/src/locales/cn.json
- inlong-dashboard/src/locales/en.json
- inlong-dashboard/src/metas/streams/common/StreamDefaultInfo.ts
- [INLONG-7246][INLONG-7246][Dashboard] Remove helper info of DataType in Stream configuration
- Fixes #7246 
*(example:)* …
> [INLONG-7246][Dashboard] Remove helper info of DataType in Stream configuration

- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
- [INLONG-7252][Sort] Fix Doris connector throw NPE when DATE type data is null
- Fixes #7257 
* Fix Doris connector throw NPE when DATE type data is null
* modify `DorisDynamicSchemaOutputFormat#open()` to judge null
> [INLONG-7252][Sort] Fix Doris connector throw NPE when DATE type data is null

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/hudi/HudiSinkOperator.java
- [INLONG-7271][Manager] The primary key and partition key of the hudi table support comma separation
- Fixes #7271 
*(example:)*
- If a feature is not documented yet in this PR, please create a follow-up issue …
> [INLONG-7271][Manager] Support comma separation for primary key and partition key of Hudi table

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sort/SortServiceImplTest.java
- Fixes #7254 
When a InlongGroupId is in the process of switching, the config of source cluster and target cluster will be mixed up.
Which doubles the data consuming from MQ.
The solution is to check if the target sort cluster is tagged. If so, fiter the MQs under this tag; otherwise, get all MQs of both source and target MQs.
> [INLONG-7254][Manager] Fix config error when InlongGroupId is in the process of switching

- inlong-distribution/src/main/assemblies/sort-connectors.xml
- inlong-sort/README.md
- inlong-sort/sort-connectors/redis/README.md
- inlong-sort/sort-connectors/redis/pom.xml
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/config/RedisDataType.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/config/RedisOptions.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/config/SchemaMappingMode.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/container/InlongRedisClusterContainer.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/container/InlongRedisCommandsContainer.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/container/InlongRedisContainer.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/schema/RedisSchema.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/schema/RedisSchemaFactory.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/schema/StateEncoder.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/schema/impl/AbstractRedisSchema.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/schema/impl/BitmapStaticKvPairSchema.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/schema/impl/HashDynamicSchema.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/schema/impl/HashStaticKvPairSchema.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/schema/impl/HashStaticPrefixMatchSchema.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/schema/impl/PlainPrefixMatchSchema.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/sink/AbstractRedisSinkFunction.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/sink/RedisBitmapSinkFunction.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/sink/RedisDynamicTableSink.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/sink/RedisHashSinkFunction.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/sink/RedisPlainSinkFunction.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/sink/RedisSinkFunction.java
- inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/table/RedisDynamicTableFactory.java
- inlong-sort/sort-connectors/redis/src/test/java/org/apache/inlong/sort/redis/RedisDynamicTableFactoryTest.java
- inlong-sort/sort-connectors/redis/src/test/java/org/apache/inlong/sort/redis/RedisTableTest.java
- [INLONG-7060][Sort] Support write redis in sort-connector-redis 
- Fixes #7060 
1. Support write different redis-modes: cluster / standalone
2. Support data-types: plain / bitmap / hash
3. Support different schema mapping mode: dynamic / prefix-match / kv-pair
> Dirty data and metrics stat will be added in approaching PR.
See detail:  <a href="https://redis.io/topics/data-types-intro">redis data type</a>
Redis strings commands are used for managing string values in Redis
* A Redis hash is a data type that represents a mapping between a string field and a string value.<br/>
* There are two members in hash DataType: <br/>
* the first member is Redis hash field.<br/>
* the second member is Redis hash value.
* Redis Lists are simply lists of strings, sorted by insertion order.
* You can add …
> [INLONG-7060][Sort] Support write redis in sort-connector-redis 

- inlong-distribution/src/main/assemblies/sort-connectors.xml
- inlong-sort/pom.xml
- inlong-sort/sort-connectors/kudu/pom.xml
- inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/common/Kudu.java
- inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/common/KuduOptions.java
- inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/common/KuduTableInfo.java
- inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/common/KuduUtils.java
- inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/common/KuduValidator.java
- inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/sink/AbstractKuduSinkFunction.java
- inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/sink/KuduAsyncSinkFunction.java
- inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/sink/KuduSinkFunction.java
- inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/sink/KuduWriter.java
- inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/source/KuduConsumerTask.java
- inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/source/KuduLookupFunction.java
- inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/table/KuduDynamicTableFactory.java
- inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/table/KuduDynamicTableSink.java
- inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/table/KuduDynamicTableSource.java
- inlong-sort/sort-connectors/kudu/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- inlong-sort/sort-connectors/kudu/src/test/java/org/apache/inlong/sort/connector/kudu/KuduTableFactoryTest.java
- inlong-sort/sort-connectors/kudu/src/test/java/org/apache/inlong/sort/connector/kudu/KuduTestBase.java
- inlong-sort/sort-connectors/kudu/src/test/resources/log4j-test.properties
- inlong-sort/sort-connectors/pom.xml
- licenses/inlong-sort-connectors/licenses/LICENSE-kudu-client-1.16.0.txt
- pom.xml
*[INLONG-7058][Sort] Support Apache kudu connector*
- Fixes #7058 
```sql
CREATE TABLE kudu_tbl(
uid int,
fee double,
event_id bigint,
remark varchar
)
WITH(
'connector'='kudu-inlong',
'masters'='localhost:8081;localhost:8080',
'table'='actual_tbl',
'flush-mode'='AUTO_FLUSH_SYNC',
'lookup.max-cache-size' = '-1',
'lookup.max-cache-time' = '60s',
'sink.start-new-chain' = 'true',
'max-retries' = '3',
'sink.max-buffer-size' = '100',
'sink.write-thread-count' = '5', 
'sink.max-buffer-time' = '30s',
'sink.write-with-async-mode' = 'false',
'sink.write-with-upsert-mode' = 'true',
'sink.cache-queue-max-length' = '-1',
'sink.ignore-all-changelog' = 'false'
);
```
The `Apache Kudu` `sort-connector` is fully integrated with Flink 1.13.x's Table and SQL API. By configuring `KuduTableInfo` …
> [INLONG-7058][Sort] Support Apache Kudu connector

- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
https://github.com/apache/inlong/issues/7286
------------------------------------------------
Motivation:
An error stack which is arrayIndexoutofbounds. 
After investigation, it is because the dirtyidentifier is null for multiple sink.
This was okay since we dont need the identifier to process data in multiple sink scenarios, but this is not ok for dirty data log output
Modifications:
generated a precise dirtyidentifier in addrow, so that load() call will have the actual identifier instead of null.
> [INLONG-7286][Sort] Fix issue of tableidentifier being null when addRow

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/s3/S3DirtySink.java
- Fixes #7293
For JDBC multiple sink, the cos was filled very quickly, with a new file created every second instead of minute.
So I tried to debug, and realized that whenever dirtysink.invoke() is called, dirtysink.flush() will be called as well.
So the record will be flush into cos every second instead of every minute, and this is not how it is supposed to work.
I added a mechanism to prevent the flush() from being triggered in dirtysink too often, so that every two calls to dirtysink.flush() will at least have dirtysink.batchinverval seconds in between, and cos won't flush too quickly.
> [INLONG-7292][Sort] S3DirtySink flushes too quickly

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/RedisLoadNode.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/RedisNodeSqlParserTest.java
- [INLONG-7306][Sort] Use properties to save extended parameters in RedisLoadNode
- Fixes #7306 
*(example:)* …
> [INLONG-7306][Sort] Use properties to save extended parameters in RedisLoadNode

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtySinkHelper.java
- inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/dirty/RegexReplaceTest.java
- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingOutputFormat.java
- inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/manager/StarRocksSinkManager.java
- Fixes #7292
There are two different bugs that should be fixed by this.
1) when archiving, the patternreplaceutils and JsonDymanicSchema competes for ${} symbol, and it will throw exceptions.
2) Sometimes, when invoking dirty data, there is no JsonNode. In this case, the dirty data still needs to be archived.
This fix does two things:
1) created a regexreplace method which does the regex replacement process all at once, while not interfering (editing) the common process layer.
2) for those cases where jsonnode is not available, manually pass in identifier so that at least the data can be processed in all cases
> [INLONG-7292][Sort] Accurately detect and archive dirty data for Doris/StarRocks/JDBC

- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
- [INLONG-7311][Sort] Fix Doris StreamLoad unable to archive dirtydata
- Fixes #7311 
When testing dirty data to doris sink, I found that none of the dirty data is archived, and the metric is always 0 for successfully written and 0 for dirty.
I found the cause is that when flush(), the data is written by DorisStreamLoad.load(), and within this method exception will occur.
However, when load() fails, its return value, respContent, will be null since an exception is thrown, and at this time, the current logic will not archive this as dirty data.
Changed the archive strategy so that  when respContent is null (exception during streamload), the unwritten data will be archived as dirtydata if dirtysink is not null.
> [INLONG-7311][Sort] Fix Doris StreamLoad unable to archive dirtydata

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaResourceOperators.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperator.java
- Fixes #7325 
The Kafka topic naming rules are updated to: `inlongGroupId.inlongStreamId`, but the Flink task submitted by sort is still `inlongstreamId`.
`inlongstreamId` -> `inlongGroupId.inlongStreamId`
> [INLONG-7325][Manager] Format the topic name and data separator for Kafka

- inlong-dashboard/craco.config.ts
- inlong-dashboard/package-lock.json
- inlong-dashboard/package.json
- inlong-dashboard/scripts/vite-plugin-resolve-env.ts
- inlong-dashboard/src/configs/default/conf.ts
- inlong-dashboard/src/configs/default/index.ts
- inlong-dashboard/src/configs/locales/conf.ts
- inlong-dashboard/src/configs/menus/conf.ts
- inlong-dashboard/src/configs/routes/conf.ts
- inlong-dashboard/vite.config.ts
- Fixes #7327
Supports the use of different environment variable configurations, including `.env`, `.env.local`, etc. For example, users can declare `INLONG_ENV=mytest` in the configuration file, and the system will automatically use the corresponding configuration file under mytest: `src/configs/menus/conf.mytest.ts`
> [INLONG-7327][Dashboard] Support using different env variable

- .gitignore
- inlong-manager/manager-web/src/main/resources/application-dev.properties
- inlong-tools/dev/README.md
- inlong-tools/dev/inlong-dev-toolkit.sh
*[INLONG-7030] Build tool for local debugging environment*
- Fixes #7030 
The inlong-manager project relies on too many configurations and packages. When debugging locally, multiple default directories need to be created, which is complicated.
Therefore, a script is urgently needed to quickly support local debugging.
Furthermore, local debugging of other modules also requires similar tools. Temporarily named devkit, looking forward to the addition of more functions.
*(example:)* …
> [INLONG-7030][Manager][Sort] Build tool for local debugging environment

- inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/ClientContext.java
- Fixes #7349 
Each SortClients creates a SortSdkMetricItemSet with same name (taskId), which leads to a register failure when register this bean as MetricItemSet.
Add a random value in the name of SortSdkMetricItemSet
> [INLONG-7349][SDK] Fix init failure when a single SortTask create multiple SortClients

- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/PostgreSQLReader.java
- Fixes #7353 
1. `AgentMetricItem` is repeatedly defined and not initialized, just use the one in the abstract parent class `AbstractReader`.
2. If deploying multiple instances of the Debezium Postgres connector, must use distinct replication slot names.
1. Remove redundant definitions.
2. Set the slot name.
> [INLONG-7353][Agent] Fix error of PostgreSQL connector

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/greenplum/GreenplumSqlBuilder.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/postgresql/PostgreSQLSqlBuilder.java
- inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/source/StreamSourceServiceTest.java
Fix the ungraceful util tool import classes of Lists/Maps
- Fixes https://github.com/apache/inlong/issues/7358
Use gracefull util tool class import for the full project
- Use com.google.common.collect.Lists import for GreenplumSqlBuilder instead of org.apache.commons.compress.utils.Lists
- Use com.google.common.collect.Lists import for PostgreSQLSqlBuilder instead of org.apache.commons.compress.utils.Lists
- Use com.google.common.collect.Maps import for StreamSourceServiceTest instead of org.apache.curator.shaded.com.google.common.collect.Maps
> [INLONG-7358][Manager] Fix the ungraceful util tool import classes of Lists/Maps

- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/mysql/MySQLDataNodeDTO.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSink.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTO.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkRequest.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/LoadNodeUtils.java
- inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTOTest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/mysql/MySQLDataNodeOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/mysql/MySQLResourceOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/mysql/MySQLSinkOperator.java
- Fixes #7379 
Add a database name for MySQLSink.
The databaseName is currently included in mysql  jdbcUrl.
In fact, the user only needs to focus on `ip:post` when save mysql DataNode.
And select database when saving sink information.
So add a database to MySQLSink.
Add a database name for MySQLSink
> [INLONG-7379][Manager] Add a database name for MySQLSink

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/SqlServerJob.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/SQLServerSource.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/SQLServerReader.java
- Fixes #7387 
1. Fix field name:
`user` -> `username`
`dbname` -> `database`
`serverName` -> `schemaName`
> [INLONG-7387][Agent] Fix error of SqlServer connector

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtySinkHelper.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SinkTableMetricData.java
- inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/dirty/RegexReplaceTest.java
- inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingOutputFormat.java
- inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/manager/SinkBufferEntity.java
- inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/manager/StarRocksSinkManager.java
- inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/manager/StarRocksStreamLoadVisitor.java
- inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/StarRocksDynamicSinkFunction.java
- Fixes #7391
When migrating the whole db, the records are composed with JSON format to submit to StarRocks Server. JSON data may cause StarRocks Server high CPU loads. Data with CSV format will reduce CPU loads.
Records will be lost if an exception threw by StarRocks Server. We may upload the records to S3 bucket as dirty data. This is useful when auditing and checking.
1. DirtySinkHelper in base module has …
> [INLONG-7391][Sort] Support CSV format and dirty data collecting for StarRocks connector all db migrating

- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
- inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/RedisJob.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/RedisSource.java
- inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/RedisReader.java
- inlong-common/src/main/java/org/apache/inlong/common/enums/TaskTypeEnum.java
- Fixes #7404 
1. Missing redis job for Redis connector.
1. Add `RedisJob`.
> [INLONG-7404][Agent] Fix error of Redis connector

- inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/UpsertKafkaDynamicTableFactory.java
- Fixes: https://github.com/apache/inlong/issues/7411
Fix the invalid of kafka source meitric due to inlongMetric being null
In the createDynamicTableSource method of the UpsertKafkaDynamicTableFactory class, when building a KafkaDynamicSource object, you need to pass in the INLONG_METRIC configuration
> [INLONG-7411][Sort] Fix the invalid of kafka source meitric due to inlongMetric being null

- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/FlinkSink.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergMultipleStreamWriter.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergSingleStreamWriter.java
- Fixes https://github.com/apache/inlong/issues/7417
Use SinkTableMetricData instead of SinkMetricData in IcebergSingleStreamWriter
Use SinkTableMetricData instead of SinkMetricData in IcebergSingleStreamWriter
> [INLONG-7417][Sort] Use SinkTableMetricData instead of SinkMetricData in IcebergSingleStreamWriter

- inlong-sort/sort-connectors/cdc-base/pom.xml
- inlong-sort/sort-connectors/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/source/IncrementalSource.java
- inlong-sort/sort-connectors/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/source/jdbc/JdbcIncrementalSource.java
- inlong-sort/sort-connectors/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/source/reader/IncrementalSourceRecordEmitter.java
- inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/source/OracleSourceBuilder.java
- inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/table/OracleTableSource.java
- inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/table/OracleTableSourceFactory.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/OracleExtractSqlParseTest.java
- licenses/inlong-sort-connectors/LICENSE
- pom.xml
Support open incremental snapshot in oracle cdc connector
- Fixes #7410
Support open incremental snapshot in oracle cdc connector and Improve the efficiency of reading records.
Add `scan.incremental.snapshot.enabled=true` to the option of the Flink Sql, for example:
```sql
CREATE TABLE products (
ID INT NOT NULL,
NAME STRING,
DESCRIPTION STRING,
WEIGHT DECIMAL(10, 3),
PRIMARY KEY(id) NOT ENFORCED
) WITH (
'connector' = 'oracle-cdc-inlong',
'hostname' = 'localhost',
'port' = '1521',
'username' = 'flinkuser',
'password' = 'flinkpw',
'database-name' = 'XE',
'schema-name' = 'inlong',
'table-name' = 'user',
'scan.incremental.snapshot.enabled' = 'true');
```
Add some options:
```java
enableParallelRead
splitSize
splitMetaGroupSize
fetchSize
connectTimeout
connectMaxRetries
connectionPoolSize …
```
> [INLONG-7410][Sort] Support open incremental snapshot in oracle cdc connector

- inlong-tubemq/tubemq-docker/tubemq-all/Dockerfile
- Fixes #7433
Recover the zookeeper 3.4 to be compatible with JDK 1.8, TubeMQ needs JDK 1.8
> [INLONG-7433][Docker] Recover the zookeeper 3.4 to be compatible with JDK 1.8

- .github/workflows/ci_chart_test.yml
- docker/docker-compose/docker-compose.yml
- docker/kubernetes/Chart.yaml
- docker/kubernetes/templates/NOTES.txt
- docker/kubernetes/templates/agent-statefulset.yaml
- docker/kubernetes/templates/zookeeper-configmap.yaml
- inlong-audit/audit-common/pom.xml
- inlong-audit/audit-sdk/pom.xml
- Fixes #7435
Fixed some small description errors
- open 8080 mapping for the pulsar in docker-compose
- update the chart version
- remove the `sudo` requirements for k8s notice
- correct the component error for the agent template.
- remove the valid kindest version.
> [INLONG-7435][Doc] Fixed some small description errors

- inlong-sort/sort-connectors/hbase/pom.xml
- inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/sink/HBaseSinkFunction.java
- [INLONG-7441][Sort] Fix HBase connector dependency lost and dirty data process error
- Fixes #7441 
* Fix HBase connector dependency lost and dirty data process error
* Modify pom file of HBase connector
* Modify HBaseSinkFunction
> [INLONG-7441][Sort] Fix HBase connector dependency lost and dirty data process error

- docker/kubernetes/README.md
- docker/kubernetes/templates/audit-statefulset.yaml
- docker/kubernetes/templates/tubemq-broker-configmap.yaml
- docker/kubernetes/templates/tubemq-broker-ini-configmap.yaml
- docker/kubernetes/templates/tubemq-broker-pdb.yaml
- docker/kubernetes/templates/tubemq-broker-service.yaml
- docker/kubernetes/templates/tubemq-broker-statefulset.yaml
- docker/kubernetes/templates/tubemq-manager-service.yaml
- docker/kubernetes/templates/tubemq-manager-statefulset.yaml
- docker/kubernetes/templates/tubemq-master-configmap.yaml
- docker/kubernetes/templates/tubemq-master-ini-configmap.yaml
- docker/kubernetes/templates/tubemq-master-pdb.yaml
- docker/kubernetes/templates/tubemq-master-service.yaml
- docker/kubernetes/templates/tubemq-master-statefulset.yaml
- docker/kubernetes/templates/zookeeper-configmap.yaml
- docker/kubernetes/templates/zookeeper-pdb.yaml
- docker/kubernetes/templates/zookeeper-service.yaml
- docker/kubernetes/templates/zookeeper-statefulset.yaml
- docker/kubernetes/values.yaml
- Fixes #7447
Make the Pulsar the default MQ option to lower the complexity, it's so difficult for users to understand TubeMQ.
At the same time, users could all support MQ types.
> [INLONG-7447][Docker] Make the Pulsar the default MQ option to lower the complexity

- inlong-sort/sort-connectors/iceberg/pom.xml
- Fixes https://github.com/apache/inlong/issues/7412
Fix dependency error: java.lang.NoClassDefFoundError
```
2023-02-17 10:28:40.553 [flink-akka.actor.default-dispatcher-27] INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph - DynamicSchemaHandleOperator (1/1) (69c8d5bfe7432ff0fb330799caf9fe63) switched from INITIALIZING to FAILED on cql-0mmcgg0c-666096-taskmanager-1-1 @ 9.166.0.206 (dataPort=46585).
java.lang.NoClassDefFoundError: com/amazonaws/auth/BasicAWSCredentials
at org.apache.inlong.sort.iceberg.shaded.org.apache.inlong.sort.base.dirty.sink.s3.S3DirtySink.open(S3DirtySink.java:94) ~[pool-1-thread-4-1676600553196-test-sort-connector-iceberg-dlc-1.5.0-SNAPSHOT.jar:1.5.0-SNAPSHOT]
at org.apache.inlong.sort.iceberg.shaded.org.apache.inlong.sort.base.dirty.DirtySinkHelper.ope …
```
> [INLONG-7412][Sort] Fix dependency error: java.lang.NoClassDefFoundError for iceberg

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/s3/S3DirtySink.java
- Title: [INLONG-7459][Sort] Fix dirty data can't be archived to s3 for hbase
- Fixes #7459 
Fix dirty data can't be archived to s3 for hbase
Change the  third-party dependencies package from commons-lang to commons-lang3 for class 'org.apache.commons.lang3.StringEscapeUtils'
*(example:)*
- If yes, how is the feature documented? (not applicable …
> [INLONG-7459][Sort] Fix dirty data can't be archived to s3 for hbase

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/queue/QueueResourceListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/queue/StreamQueueResourceListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/sink/SinkResourceListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/sort/SortConfigListener.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/sort/StreamSortConfigListener.java
- Fixes #7468 
Fix re-executing the workflow fails to load the new configuration information.
Fix re-executing the workflow fails to load the new configuration information.
Obtain the current configuration in real time.
> [INLONG-7468][Manager] Fix re-executing the workflow fails to load the new configuration information

- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
- inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/util/DorisParseUtils.java
- Fixes #7392 
Doris Single table had performance bottlenecks. The throughput was 1700 records/s, and this pr fixes 2 bugs to enhance its performance to 50000 records/s.
1. refactored EnableBatchDelete and related helpers so that the Schema is not calculated by RestService after initialization.
2. Refactored the date bugfix pr into DorisParseUtils so that it will not interfere with single table.
> [INLONG-7392][Sort] Refactor Doris single table to solve performance issues

- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/DynamicSchemaHandleOperator.java
- Fixes https://github.com/apache/inlong/issues/7453
In the Iceberg Connector, the blacklist feature will cause metric and archiving of dirty data to be invalid.
In the Iceberg connector, blacklisting will cause metric and archiving dirtiness to be ineffective, so the blacklisting feature needs to be removed.
> [INLONG-7453][Sort] Fix the blacklist of Iceberg connector will lose the metric and archiving of dirty data

- inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNode.java
- inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicTableFactory.java
- Fixes #7299
- All supported formats are checked in `ExtractNodeUtils.parsingFormat()`, so it does not need to check again for Kafka ExtractNode.
- Add `valueFormatPrefix` check for `inlong-msg.' prefix options.
> [INLONG-7299][Sort] Optimize the options check for the Kafka connector

- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/BaseDeltaTaskWriter.java
Fix iceberg's data were duplicated when delete records in upsert mode, if message has delete record of data in CDC of RDB.
- Fixes #7470 
Keep ACID in the iceberg.
Modify class BaseDeltaTaskWriter in the iceberg
> [INLONG-7470][Sort] Fix Iceberg's data were duplicated when delete records in upsert mode

- inlong-sort/sort-connectors/filesystem/pom.xml
- inlong-sort/sort-connectors/kafka/pom.xml
- [INLONG-7483][Sort] Fix Connector dependency shade range is not right
- Fixes #7483 
* Fix Connector dependency shade range is not right
* Modify pom file of kafka and filesystem
> [INLONG-7483][Sort] Fix Connector dependency shade range is not right

- inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJsonEnhancedSerializationSchema.java
- Title: [INLONG-7477][Sort] Fix the metadata of table write error for canal-json
- Fixes #7477
Fix the metadata of table write error for canal-json
Fix the metadata of table write error for canal-json in class 'CanalJsonEnhancedSerializationSchema.java'
*(example:)* …
> [INLONG-7477][Sort] Fix the metadata of table write error for canal-json

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/group/InitGroupCompleteListener.java
- Fixes #7501 
Fix InlongStream status is not updated after InlongGroup configuration is successful.
Fix InlongStream status is not updated after InlongGroup configuration is successful.
> [INLONG-7501][Manager] Fix InlongStream status is not updated after InlongGroup configuration is successful

- inlong-sort/sort-connectors/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/source/reader/external/IncrementalSourceScanFetcher.java
- inlong-sort/sort-connectors/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/source/reader/external/IncrementalSourceStreamFetcher.java
[INLONG-7488][Sort] Fix the issue of only being able to read one record during the incremental snapshot
- Fixes #7488 
Open  incremental snapshot, Oracle tables need to have primary keys in order to read all data. For tables without primary keys, you can refer to the current PR for a fix.
In the snapshot, `record.key()` is null, so it will overwrite the previous record. So we can to add record without primary key into list.
```java
if (!reachChangeLogStart) {
if (record.key() == null) {
snapshotRecordsWithoutKey.add(record);
} else {
outputBuffer.put((Struct) record.key(), record);
}
}
```
> [INLONG-7488][Sort] Fix the issue of only being able to read one record during the incremental snapshot

- inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/manager/StarRocksStreamLoadVisitor.java
- inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/StarRocksDynamicSinkFunction.java
- Fixes #7504
StarRocks will throw NullPointerException when dirty.ignore is false.
Check if null when parsing dirty.label, dirty.logtag and dirty.identifier in class `StarRocksDynamicSinkFunction`.
*(example:)*
- *Extended integration test for recovery …
> [INLONG-7504][Sort] Fix NPE when dirty ignore is false

- inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java
- Fixes #7513
There are duplicate definitions here, so delete the duplicate part.
Delete the duplicate definition part.
> [INLONG-7513][DataProxy] Delete duplicate definitions

- inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7DynamicSink.java
- inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/table/RowElasticsearchSinkFunction.java
- Fixes #7487 
Similar to doris/jdbc/kafka, ES needs to change changelog too, so that read metric and write metric can both be 2 records for upsert changelog. 
1. changed changelogMode for es
2. additionally, calculate metrics for update_before changelog for es7 sink.
> [INLONG-7487][Sort] Change changelog mode to capture update_before for ES 

- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupRequest.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/SinkRequest.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/SourceRequest.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamRequest.java
- inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/DeleteTransformRequest.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java
- Fixes #7529 
Optimize some interfaces.
1.Change the pattern limitation of InlongGroupId and InlongStreamId.
2.Support query for group, stream, source and sink by update_time or create_time.
3.Check the clusterTag when saving the cluster.
> [INLONG-7529][Manager] Change the pattern limitation of InlongGroupId and InlongStreamId

- inlong-audit/audit-proxy/pom.xml
- inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/sink/KafkaSink.java
- inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/sink/PulsarSink.java
- inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/sink/TubeSink.java
- inlong-audit/audit-proxy/src/test/java/org/apache/inlong/audit/sink/KafkaSinkTest.java
- inlong-audit/conf/audit-proxy-kafka.conf
- pom.xml
- Fixes #7519 
Audit support Kafka.
1. Add `KafkaSink` to send messages
2. Add `audit-proxy-kafka.conf`
org.apache.inlong.audit.sink.KafkaSinkTest
> [INLONG-7519][Audit] Proxy support Kafka

- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergMultipleStreamWriter.java
- inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergSingleStreamWriter.java
- Fixes  https://github.com/apache/inlong/issues/7546
The S3DirtySink#open method is not called in IcebergSingleStreamWriter and IcebergMultipleStreamWriter, resulting in dirty data that may never be flushed and archived:
https://github.com/apache/inlong/blob/12ee6c42c8e7e4869c170ae97656ff79c323e881/inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/s3/S3DirtySink.java#L108-L113
In the open method of IcebergSingleStreamWriter and IcebergMultipleStreamWriter, call the DirtySink#open method
> [INLONG-7546][Sort] Fix dirty data not archived for iceberg connector

- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/log/LogDirtySink.java
- inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/s3/S3DirtySink.java
- Title: [INLONG-7550][Sort] Optimize the log printing level of dirty data to avoid generating a large number of logs
- Fixes #7550 
Optimize the log printing level of dirty data to avoid generating a large number of logs
Set the level of dirty data log to debug for 'LogDirtySink' and 'S3DirtySink'
*(example:)* …
> [INLONG-7550][Sort] Optimize the log printing level of dirty data to avoid generating a large number of logs

- inlong-sort/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/cdc/postgres/table/PostgreSQLReadableMetaData.java
- Fixes #7543
Refer issue https://github.com/apache/inlong/issues/7397 , postgres cdc connector also sends two data with the same UPDATE operation.
Postgres cdc connector also should fix the type in canal-json or debezium-json when UPDATE operation.
For UPDATE_BEFORE output DELETE
For UPDATE_AFTER output INSERT
*(example:)*
- *Added …
> [INLONG-7543][Sort] Fix PostgreSQL connector output two data with the same UPDATE operation

- bin/init-config.sh
- bin/inlong-daemon
- conf/inlong.conf
- inlong-dataproxy/conf/common.properties
- Fixes #7528
Add the Kafka support for audit standalone deployment, and enable audit by default.
> [INLONG-7528][Script] Add the Kafka support for audit standalone deployment

- inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/debezium/table/RowDataDebeziumDeserializeSchema.java
Fix Oracle CDC reads timestamp type record error
- Fixes #7559 
Oracle CDC reads timestamp type record error. Because Oracle CDC has been shaded, the schema will have the prefix 'org.apache.inlong.sort.cdc.oracle.shaded' added, so we need to use `schemaName.endsWith()` to determine the Schema type.
Use `schemaName.endsWith()` to determine the Schema type.
```java
String schemaName = schema.name();
if (schemaName.endsWith(Timestamp.SCHEMA_NAME)) {
return TimestampData.fromEpochMillis((Long) dbzObj);
} else if (schemaName.endsWith(MicroTimestamp.SCHEMA_NAME)) {
long micro = (long) dbzObj;
return TimestampData.fromEpochMillis(
micro / 1000, (int) (micro % 1000 * 1000));
} else if (schemaName.endsWith(NanoTimestamp.SCHEMA_NAME)) {
long nano = (long) dbzObj;
return …
```
> [INLONG-7559][Sort] Fix Oracle CDC reads timestamp type record error

- inlong-sort/sort-connectors/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/config/BaseSourceConfig.java
- inlong-sort/sort-connectors/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/config/JdbcSourceConfig.java
- inlong-sort/sort-connectors/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/config/MetricConfig.java
- inlong-sort/sort-connectors/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/source/IncrementalSource.java
- inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/base/source/IncrementalSource.java
Extract metrics as common parameters
- Fixes #7567 
In order to better adapt to metrics from other CDCs, make metric parameters as common parameter. Other CDC's SourceConfig only need to implements MetricConfig.
1. Add the metricConfig interface
```java
public interface MetricConfig extends Serializable {
String getInlongMetric();
String getInlongAudit();
}
```
2. Put metric parameters inside BaseSourceConfig and implements MetricConfig.
```java
public abstract class BaseSourceConfig implements SourceConfig, MetricConfig {
/****/
// --------------------------------------------------------------------------------------------
// Metric Configurations
// --------------------------------------------------------------------------------------------
protected final String inlongMetric;
protected …
```
> [INLONG-7567][Sort] Extract metrics as common parameters

- inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
- inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
- Fixes #7577 
Fix the manager generate too many streamSource instances when pulling tasks.
The previous query was to pull out all Streamsources in the templateId and filter them.
If there were 200 agents, this method would generate 500 + streamSource instances each time, leading to a large amount of gc.
Filtering is now done directly in the mysql layer to avoid generating too many instances and causing gc.
> [INLONG-7577][Manager] Fix high CPU usage when the number of StreamSource is too large

- inlong-dashboard/src/configs/default/conf.ts
- inlong-dashboard/src/utils/request.ts
When users do custom deployment, they can use the responseParse parameter to process data returned by internal http or external services.
- Fixes #7582
> [INLONG-7582][Dashboard] Support responseParse config

- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/AbstractDataNodeOperator.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeOperator.java
- Fixes #7591 
Support updating related streamSources after updating DataNode.
Currently, no streamSource uses Datanodes, It will be gradually supported later.
Therefore, nothing is done in the `updateRelatedStreamSource` method.
Support updating related streamSources after updating DataNode.
> [INLONG-7591][Manager] Support updating related streamSources after updating DataNode

- inlong-sort/sort-connectors/mongodb-cdc/pom.xml
- inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/source/IncrementalSource.java
- inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/source/MongoDBSource.java
- inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/source/MongoDBSourceBuilder.java
- inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/source/reader/IncrementalSourceRecordEmitter.java
- inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/source/reader/MongoDBRecordEmitter.java
- inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/table/MongoDBTableSource.java
- inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/table/MongoDBTableSourceFactory.java
- licenses/inlong-sort-connectors/LICENSE
[INLONG-7537][Sort] Enable incremental snapshot for MongoDB CDC
- Fixes #7537 
After enabling incremental snapshots in MongoDB CDC, data can be read in chunks to improve reading efficiency.
Add the `MongoDBSource` class to implement incremental snapshot logic.
- If yes, how is the feature documented? ( docs )
This feature add some options, details for  https://github.com/apache/inlong-website/pull/710 .
| **Option**                | **Required** | **Default**      | **Type** | **Description**                                              |
| ------------------------- | ------------ | …
> [INLONG-7537][Sort] Enable incremental snapshot for MongoDB CDC

- inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/DebeziumSourceFunction.java
- inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/debezium/DebeziumDeserializationSchema.java
- inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/debezium/internal/DebeziumChangeFetcher.java
- inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/debezium/table/MongoDBConnectorDeserializationSchema.java
- [INLONG-7595][Sort] Mongo read phase metrics need to update when no incremental data
- Fixes #7595 
It won't report incremental read phase metrics when i use single parallel logic and no incremental data.
Mongo read phase metrics need to update when no incremental data.
* `DebeziumDeserializationSchema` add overload `deserialize` for jugde read phase
*  `DebeziumSourceFunction` fix error logic for get read phase
> [INLONG-7595][Sort] Mongo read phase metrics need to update when no incremental data

- inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java
- inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/AllMigrateTest.java
- Fixes #7589 
Now it's not capable for sort to generate multi insert sqls for one output with multiple inputs which is not acceptable for user cases.
For instance, user may want to get data from multiple data sources, they can only use union operation for now. But union operation in flink is too heavy.
We need to support generate sqls from one stream such that:
Insert into sink select * from sourceA;
Insert into sink select * from sourceB;
Change the `parseNode` to `ParseSingleNode` because the recuisive method will be multi branches which is not suitable for reading. And move the input nodes parsing outside of `parseNode` method to make it easy for reading
Run `AllmigrateTestMultiRelations`
> [INLONG-7589][Sort] Support multi node relation with same output but different input nodes

- .github/workflows/ci_docker.yml
- docker/build-docker-images.sh
- docker/publish-by-arch.sh
- [INLONG-7626][Docker] Delete tubemq-cpp images on x86
- Fixes #7626 
- Delete tubemq-cpp images on x86.
- Because storage on GitHub workflow is not enough. Sometime agent arm image will be dropped.
- Delete tubemq-all images on arm
- Now time Zookeeper version is not support arm platform.
- Delete tubemq-cpp images on x86.
- Because storage on GitHub workflow is not enough. Sometime agent arm image will be dropped.
- Delete tubemq-all images on arm
- Now time Zookeeper version is not support arm platform.
- Expand swapfile to expand disk space.
- Remove unused dependence, such as dotnet, android and ghc.
> [INLONG-7626][Docker] Optimize the docker push workflow

- inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/consts/ConfigConstants.java
- inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/file/ConfigManager.java
- inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/file/RemoteConfigJson.java
- inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/node/Application.java
- inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/sink/KafkaSink.java
- inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/sink/PulsarSink.java
- inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/sink/TubeSink.java
- inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/sink/pulsar/PulsarClientService.java
- inlong-audit/audit-proxy/src/test/java/org/apache/inlong/audit/sink/KafkaSinkTest.java
- inlong-audit/audit-proxy/src/test/java/org/apache/inlong/audit/sink/PulsarSinkTest.java
- inlong-audit/audit-proxy/src/test/java/org/apache/inlong/audit/sink/TubeSinkTest.java
- inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java
- inlong-audit/conf/application.properties
- inlong-audit/conf/audit-proxy-kafka.conf
- inlong-audit/conf/audit-proxy-pulsar.conf
- inlong-audit/conf/audit-proxy-tubemq.conf
- inlong-common/src/main/java/org/apache/inlong/common/pojo/audit/AuditConfig.java
- inlong-common/src/main/java/org/apache/inlong/common/pojo/audit/AuditConfigRequest.java
- inlong-common/src/main/java/org/apache/inlong/common/pojo/audit/MQInfo.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterService.java
- inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
- inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/AuditController.java
- Fixes #7413 
Get the MQ cluster address from the manager.
1. Fix `httpGet` to `httpPost`
2. Add managerHosts and cluster params in `server.properties`
3. Add open API in the manager
> [INLONG-7413][Audit] Audit get MQ config from Manager
