apache/inlong

tubemq-core/src/main/java/com/tencent/tubemq/corerpc/netty/NettyRpcServer.java
tubemq-server/src/main/java/com/tencent/tubemq/server/master/web/action/screen/Webapi.java
tubemq-server/src/main/java/com/tencent/tubemq/server/master/web/simplemvc/RequestContext.java

optimization for delete unnecessary code
[JIRA](https://issues.apache.org/jira/projects/TUBEMQ/issues/TUBEMQ-9?filter=allopenissues)

optimization for delete unnecessary code

---

tubemq-core/src/main/java/com/tencent/tubemq/corerpc/client/Callback.java

https://issues.apache.org/jira/browse/TUBEMQ-10

TUBEMQ-10 javadoc error

---

tubemq-core/src/main/java/com/tencent/tubemq/corerpc/netty/NettyRpcServer.java

Fixes Bug #<[TUBEMQ-14](https://issues.apache.org/jira/browse/TUBEMQ-14)>
Bug fix, Syntax correct
delete error charset

TUBEMQ-14: Some compilation errors

---

tubemq-core/src/main/java/com/tencent/tubemq/corerpc/netty/NettyRpcServer.java

Fixes Bug #<[TUBEMQ-14](https://issues.apache.org/jira/browse/TUBEMQ-14)>
Bug fix, Syntax correct
delete error charset

[TUBEMQ-14]: Some compilation errors

---

docs/http_access_API_definition.md
tubemq-core/src/main/java/com/tencent/tubemq/corerpc/client/Callback.java

https://issues.apache.org/jira/browse/TUBEMQ-15

[TUBEMQ-15] correct spelling

---

pom.xml
tubemq-client/pom.xml
tubemq-core/pom.xml
tubemq-example/pom.xml
tubemq-server/pom.xml

1. Adjust version format
2. Add mailist, scm, license, issueManagement in pom.xml

[TUBEMQ-21]Change version number from x.y-SNAPSHOT to x.y.z-incubating-SNAPSHOT

---

tubemq-client/src/main/java/com/tencent/tubemq/client/consumer/ConsumerSamplePrint.java
tubemq-server/src/main/java/com/tencent/tubemq/server/broker/utils/BrokerSamplePrint.java
tubemq-server/src/main/java/com/tencent/tubemq/server/broker/utils/DiskSamplePrint.java
tubemq-server/src/main/java/com/tencent/tubemq/server/master/utils/BdbStoreSamplePrint.java

ConsumerSamplePrint#printExceptionCaught difftime -> diffTime
BrokerSamplePrint#printExceptionCaught difftime-> diffTime
DiskSamplePrint#printExceptionCaught difftime-> diffTime
BdbStoreSamplePrint#printExceptionCaught difftime-> diffTime

[TUBEMQ-26] correct spelling

---

tubemq-core/src/main/java/org/apache/tubemq/corebase/balance/EventStatus.java
tubemq-core/src/main/java/org/apache/tubemq/corebase/balance/EventType.java

refactor enum implemention from inner annoynmous to constructor with necessary parameters

[TUBEMQ-33] refactor enum implemention of inner annoynmous

---

tubemq-client/src/main/java/org/apache/tubemq/client/consumer/BaseMessageConsumer.java
tubemq-client/src/main/java/org/apache/tubemq/client/producer/SimpleMessageProducer.java
tubemq-client/src/main/java/org/apache/tubemq/client/producer/qltystats/DefaultBrokerRcvQltyStats.java
tubemq-client/src/test/java/org/apache/tubemq/client/producer/qltystats/DefaultBrokerRcvQltyStatsTest.java
tubemq-core/src/main/java/org/apache/tubemq/corebase/TErrCodeConstants.java
tubemq-core/src/main/java/org/apache/tubemq/corerpc/RpcServiceFactory.java
tubemq-server/src/main/java/org/apache/tubemq/server/broker/BrokerServiceServer.java

[TUBEMQ-47] fix some typos

---

tubemq-client/src/main/java/org/apache/tubemq/client/consumer/FetchContext.java
tubemq-client/src/main/java/org/apache/tubemq/client/consumer/SimplePullMessageConsumer.java
tubemq-client/src/main/java/org/apache/tubemq/client/factory/TubeMultiSessionFactory.java
tubemq-client/src/main/java/org/apache/tubemq/client/factory/TubeSingleSessionFactory.java
tubemq-client/src/main/java/org/apache/tubemq/client/producer/RoundRobinPartitionRouter.java
tubemq-core/src/main/java/org/apache/tubemq/corebase/policies/FlowCtrlItem.java
tubemq-core/src/main/java/org/apache/tubemq/corebase/utils/AbstractSamplePrint.java
tubemq-core/src/main/java/org/apache/tubemq/corerpc/benchemark/RcpService4BenchmarkClient.java
tubemq-core/src/main/java/org/apache/tubemq/corerpc/benchemark/RpcService4BenchmarkServer.java
tubemq-server/src/main/java/org/apache/tubemq/server/broker/nodeinfo/ConsumerNodeInfo.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/fileconfig/ZKConfig.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/FileUtil.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/UserAuthFilter.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebAdminFlowRuleHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebAdminTopicAuthHandler.java

[TUBEMQ-75] remove unused Logger

---

tubemq-core/src/main/java/org/apache/tubemq/corebase/cluster/MasterInfo.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/bdbstore/bdbentitys/BdbTopicConfEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/nodemanage/nodebroker/BrokerConfManager.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/common/BaseResult.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerDefConfHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerTopicConfHandler.java

1. Optimize code
```
if (addrMap4Failover.get(tmpNodeAddrInfo.getHostPortStr()) == null) {
addrMap4Failover.put(tmpNodeAddrInfo.getHostPortStr(), tmpNodeAddrInfo);
}
```
Change to
```
addrMap4Failover.putIfAbsent(tmpNodeAddrInfo.getHostPortStr(), tmpNodeAddrInfo);
```
2. Fix type
getParameteres -> getParameters
datestring -> dateString
setunFlushDataHold -> setUnflushDataHold
getunFlushDataHold -> getUnflushDataHold
Because I do n’t know whether it will affect other components, such as log parsing, etc., I did not change it here
```
.append(",\"unFlushDataHold\":").append(getUnflushDataHold())
```

[TUBEMQ-101] Optimize code & Fix type

---

pom.xml
tubemq-client/src/test/java/org/apache/tubemq/client/consumer/RmtDataCacheTest.java
tubemq-client/src/test/java/org/apache/tubemq/client/producer/qltystats/DefaultBrokerRcvQltyStatsTest.java
tubemq-server/pom.xml

1. Modify the maven jdk compilation version to solve the syntax error during development and compilation
2. Add maven jdk compilation version comment

[TUBEMQ-121] Modify the maven jdk compilation version

---

tubemq-client/src/main/java/org/apache/tubemq/client/consumer/RmtDataCache.java

[TUBEMQ-149]Some of the consumers stop consuming their corresponding partitions and never release the partition to others

---

tubemq-example/src/main/java/org/apache/tubemq/example/MAMessageProducerExample.java
tubemq-example/src/main/java/org/apache/tubemq/example/MessageConsumerExample.java
tubemq-example/src/main/java/org/apache/tubemq/example/MessageProducerExample.java

1. Modify the wrong comment
```
/**
* Send message synchronous. More efficient and recommended.
*/
public void sendMessageAsync() {}
```
change to
```
/**
* Send message asynchronous. More efficient and recommended.
*/
public void sendMessageAsync() {}
```
2. Optimize variable naming

[TUBEMQ-154] Modify the wrong comment & Minor changes for example module

---

tubemq-client/src/main/java/org/apache/tubemq/client/consumer/BaseMessageConsumer.java
tubemq-client/src/main/java/org/apache/tubemq/client/producer/ProducerManager.java

1. According to Broker, record and check whether the next request carries user authentication information or authorization token information provided by Broker
2. According to Master requirements, add authentication information to the Master heartbeat request processing

[TUBEMQ-158] nextWithAuthInfo2B status should be managed independently according to Broker

---

docker/build/Dockerfile
docker/build/README.md
docker/build/settings.xml

support build with docker image

[TUBEMQ-169]support build with docker image

---

bin/env.sh

MASTER_JVM_ARGS="-Xmx10g -Xms6g ...
BROKER_JVM_ARGS="-Xmx16g -Xms8g ...
are configurations for production environment.

[TUBEMQ-173]default values can be overwrite by MASTER_JVM_SIZE and BROKER_JVM_SIZE

---

conf/broker.ini
conf/master.ini

Reverts apache/incubator-tubemq#111

Revert "[TUBEMQ-178]change default IPs configuration after TUBEMQ-171 finished"

---

docs/tubemq_user_guide.md

[TUBEMQ-188]fix error for example command

---

tubemq-client/src/main/java/org/apache/tubemq/client/consumer/BaseMessageConsumer.java

change ee.printStackTrace() to logger

[TUBEMQ-196] use log to print exception

---

tubemq-client/src/main/java/org/apache/tubemq/client/consumer/BaseMessageConsumer.java
tubemq-client/src/main/java/org/apache/tubemq/client/producer/ProducerManager.java
tubemq-client/src/main/java/org/apache/tubemq/client/producer/qltystats/DefaultBrokerRcvQltyStats.java
tubemq-core/src/main/java/org/apache/tubemq/corerpc/RpcServiceFactory.java
tubemq-server/src/main/java/org/apache/tubemq/server/broker/TubeBroker.java

use ThreadUtil.sleep replace Thread.sleep to avoid too many try/catch
except we need to do something by process this exception

[TUBEMQ-216] use ThreadUtil.sleep replace Thread.sleep

---

tubemq-client/src/main/java/org/apache/tubemq/client/config/ConsumerConfig.java
tubemq-client/src/main/java/org/apache/tubemq/client/consumer/RmtDataCache.java
tubemq-client/src/main/java/org/apache/tubemq/client/consumer/SimplePullMessageConsumer.java
tubemq-client/src/main/java/org/apache/tubemq/client/producer/ProducerManager.java
tubemq-client/src/test/java/org/apache/tubemq/client/consumer/MessageFetchManagerTest.java
tubemq-client/src/test/java/org/apache/tubemq/client/factory/TubeBaseSessionFactoryTest.java
tubemq-core/src/main/java/org/apache/tubemq/corebase/utils/DataConverterUtil.java

Optimize code
```
List<Message> messageList = new ArrayList<>();
if (transferedMessageList == null || transferedMessageList.isEmpty()) {
return messageList;
}
change to 
if (transferedMessageList == null || transferedMessageList.isEmpty()) {
return new ArrayList<>();
}
List<Message> messageList = new ArrayList<>(transferedMessageList.size());
```
```
for (int i; i < 0; i++) {}
change to 
for (Object o; objects) {}
```
```
String.valueOf(consumerGroup).trim();
change to 
consumerGroup.trim();
```
etc..

[TUBEMQ-213] Optimize code & Minor changes

---

tubemq-core/src/main/java/org/apache/tubemq/corebase/policies/FlowCtrlRuleHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/broker/BrokerServiceServer.java
tubemq-server/src/main/java/org/apache/tubemq/server/broker/msgstore/MessageStore.java
tubemq-server/src/main/java/org/apache/tubemq/server/broker/web/BrokerAdminServlet.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/aaaserver/SimpleCertificateBrokerHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/fileconfig/AbstractFileConfig.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/WebParameterUtils.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/balance/DefaultLoadBalancer.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/bdbstore/bdbentitys/BdbBrokerConfEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/bdbstore/bdbentitys/BdbGroupFlowCtrlEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/bdbstore/bdbentitys/BdbTopicConfEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/tools/BdbGroupAdmin.java

- Replacing valueOf() with a static method of parseXXX()
- Remove unnecessary 'String.valueOf()' call in BrokerAdminServlet#adminGetMemStoreStatisInfo
[Details on JIRA.](https://issues.apache.org/jira/projects/TUBEMQ/issues/TUBEMQ-222)

[TUBEMQ-222] Optimize code: Unnecessary boxing/unboxing conversion

---

docker/tubemq-build/README.md

remove build guide in docker-build readme

[TUBEMQ-227]remove build guide in docker-build readme

---

README.md

Update link to new contribution docs.

[TUBEMQ-231] Update URL link to contribution documents

---

.asf.yaml
.gitignore

move pr/issue comments to commits@tubemq.apache.org
See: https://issues.apache.org/jira/browse/TUBEMQ-234

[TUBEMQ-234] Add .asf.yaml to change notifications

---

.travis.yml
README.md
pom.xml

[TUBEMQ-235] Add code coverage supporting for pull request created.

---

pom.xml

After repository address is changed, the project can be compiled successfully.
```
[INFO] ------------------< org.apache.tubemq:tubemq-server >-------------------
[INFO] Building Apache TubeMQ - Server 0.5.0-incubating-SNAPSHOT          [5/7]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from berkeleydb-je: https://download.dcache.org/nexus/repository/berkeleydb-je/com/sleepycat/je/7.3.7/je-7.3.7.pom
Downloaded from berkeleydb-je: https://download.dcache.org/nexus/repository/berkeleydb-je/com/sleepycat/je/7.3.7/je-7.3.7.pom (1.7 kB at 386 B/s)
Downloading from berkeleydb-je: https://download.dcache.org/nexus/repository/berkeleydb-je/com/sleepycat/je/7.3.7/je-7.3.7.jar
Downloaded from berkeleydb-je: …
```

[TUBEMQ-236] Can't get dependencies from the maven repository

---

pom.xml
tubemq-client/pom.xml
tubemq-server/pom.xml

See https://issues.apache.org/jira/projects/TUBEMQ/issues/TUBEMQ-230

[TUBEMQ-230] upgrade test dependency, support jdk13

---

tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/TubemqOptions.java
tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/TubemqSinkFunction.java
tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/TubemqTableSink.java
tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/TubemqTableSourceSinkFactory.java

1. Support tubemq flink SinkFunction.
2. Support Table interface for TubeMQ flink connector
Jira Link: https://issues.apache.org/jira/browse/TUBEMQ-197

[TUBEMQ-197] Support TubeMQ connector for Apache Flink

---

tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/TubemqOptions.java
tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/TubemqSinkFunction.java

Support TubeMQ sink function for flink
Jira link: https://issues.apache.org/jira/browse/TUBEMQ-199

[TUBEMQ-199] Support TubeMQ sink function for flink

---

tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/TubemqTableSink.java
tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/TubemqTableSourceSinkFactory.java

Support Table interface for TubeMQ flink connector
Jira link: https://issues.apache.org/jira/browse/TUBEMQ-242

[TUBEMQ-242] Support Table interface for TubeMQ flink connector

---

bin/broker.sh
bin/master.sh
bin/tubemq

Reverts apache/incubator-tubemq#156

Revert "[TUBEMQ-240]add status command for broker/master script"

---

resources/templates/layout/default.vm
resources/templates/layout/tubeweb.vm
tubemq-server/src/main/java/org/apache/tubemq/server/master/MasterConfig.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/action/screen/Tubeweb.java

if useWebProxy is true, the web resource path is http://proxy_ip:proxy_port/webapi.htm
otherwise, the web resource is http://active_master_ip:web_port/webapi.htm

[TUBEMQ-244] support access web using proxy IP

---

tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/WebParameterUtils.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerDefConfHandler.java

remove broker IP check, the hostname with special meaning works fine.

[TUBEMQ-246] remove broker ip check

---

tubemq-client-twins/tubemq-client-cpp/inc/TubeClientConfig.h
tubemq-client-twins/tubemq-client-cpp/src/TubeClientConfig.cpp

Construct sub-directories in the main project to facilitate the integration of subsequent tasks

[TUBEMQ-250] Create C/C++ configure files

---

conf/master.ini
tubemq-docker/tubemq-all/Dockerfile
tubemq-docker/tubemq-all/tubemq.sh

support using different mapping port for standalone mode

[TUBEMQ-254] support using different mapping port for standalone mode

---

tubemq-server/src/main/java/org/apache/tubemq/server/broker/msgstore/disk/MsgFileStatisInfo.java
tubemq-server/src/main/java/org/apache/tubemq/server/broker/msgstore/disk/MsgFileStore.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/nodemanage/nodebroker/BrokerConfManager.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerDefConfHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerTopicConfHandler.java

Add related API operations of unFlushDataHold field and statistical processing

[TUBEMQ-126] Increase the unflushed data bytes control

---

tubemq-client-twins/tubemq-client-go/config.go
tubemq-client-twins/tubemq-client-go/consumer.go

Init Consumer and add a default PullConsumer
Init Config

[TUBEMQ-264] Init pull consumer and config

---

bin/env.cmd
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerDefConfHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerTopicConfHandler.java

Reverts apache/incubator-tubemq#180

Revert "[TUBEMQ-265] Unexpected broker disappearance in broker list after updating default broker metadata"

---

bin/env.cmd
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerDefConfHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerTopicConfHandler.java

See [TUBEMQ-265](https://issues.apache.org/jira/projects/TUBEMQ/issues/TUBEMQ-265) for details.

[TUBEMQ-265] Unexpected broker disappearance in broker list after updating default broker metadata

---

.gitmodules
tubemq-client-twins/tubemq-client-cpp/example/README.md
tubemq-client-twins/tubemq-client-cpp/example/log/main.cc
tubemq-client-twins/tubemq-client-cpp/inc/logger.h
tubemq-client-twins/tubemq-client-cpp/inc/noncopyable.h
tubemq-client-twins/tubemq-client-cpp/inc/singleton.h
tubemq-client-twins/tubemq-client-cpp/inc/unique_seq_id.h
tubemq-client-twins/tubemq-client-cpp/src/logger.cc

[TUBEMQ-268] C++ SDK log module

[TUBEMQ-268] C++ SDK log module

---

tubemq-client-twins/tubemq-client-cpp/inc/atomic_def.h
tubemq-client-twins/tubemq-client-cpp/inc/client_config.h
tubemq-client-twins/tubemq-client-cpp/inc/const_config.h
tubemq-client-twins/tubemq-client-cpp/inc/const_rpc.h
tubemq-client-twins/tubemq-client-cpp/inc/file_ini.h
tubemq-client-twins/tubemq-client-cpp/inc/flowctrl_def.h
tubemq-client-twins/tubemq-client-cpp/inc/logger.h
tubemq-client-twins/tubemq-client-cpp/inc/message.h
tubemq-client-twins/tubemq-client-cpp/inc/meta_info.h
tubemq-client-twins/tubemq-client-cpp/inc/singleton.h
tubemq-client-twins/tubemq-client-cpp/inc/utils.h
tubemq-client-twins/tubemq-client-cpp/inc/version.h
tubemq-client-twins/tubemq-client-cpp/src/client_config.cc
tubemq-client-twins/tubemq-client-cpp/src/file_ini.cc
tubemq-client-twins/tubemq-client-cpp/src/flowctrl_def.cc
tubemq-client-twins/tubemq-client-cpp/src/logger.cc
tubemq-client-twins/tubemq-client-cpp/src/message.cc
tubemq-client-twins/tubemq-client-cpp/src/meta_info.cc
tubemq-client-twins/tubemq-client-cpp/src/utils.cc

1. Remove unnecessary whitespaces
2. Replace int and long with uint32_t, int32_t, int64_t
3. Standardize the use statement of std;
4. Standardize code length and code format

[TUBEMQ-272]Unified C/C++ files's code style

---

.gitignore
tubemq-client-twins/tubemq-client-python/__init__.py
tubemq-client-twins/tubemq-client-python/config/__init__.py
tubemq-client-twins/tubemq-client-python/network/__init__.py
tubemq-client-twins/tubemq-client-python/requirements.txt
tubemq-client-twins/tubemq-client-python/service/__init__.py
tubemq-client-twins/tubemq-client-python/setup.py
tubemq-client-twins/tubemq-client-python/test/__init__.py
tubemq-client-twins/tubemq-client-python/tubemq/__init__.py
tubemq-client-twins/tubemq-client-python/util/__init__.py

[TUBEMQ-260] Init Python client module

[TUBEMQ-260] Init Python client module

---

tubemq-client-twins/tubemq-client-cpp/README.md
tubemq-client-twins/tubemq-client-cpp/build_linux.sh
tubemq-client-twins/tubemq-client-cpp/include/tubemq/atomic_def.h

atomic_def.h use C++11 stdlib class

[TUBEMQ-281]atomic_def.h use C++11 stdlib class

---

tubemq-client-twins/tubemq-client-cpp/include/tubemq/executor_pool.h
tubemq-client-twins/tubemq-client-cpp/include/tubemq/singleton.h
tubemq-client-twins/tubemq-client-cpp/src/logger.cc

C++ SDK singleton & executor_pool optimization

[TUBEMQ-292]C++ SDK singleton & executor_pool optimization

---

pom.xml
tubemq-server/pom.xml
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/WebServer.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/simplemvc/MultipartHttpServletRequest.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/simplemvc/WebApiServlet.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/simplemvc/WebFilter.java

Complete adding POST support to WebAPI, and now it could properly respond to GET, POST (x-www-form-urlencoded) and POST (multipart/form-data) formats on HTTP/1.1.

[TUBEMQ-309] Add POST support to WebAPI

---

tubemq-example/src/main/java/org/apache/tubemq/example/MessageConsumerExample.java

The example was to subscribe to multiple topics in a single thread.  Now modify it to subscribe to topics on multiple threads.

[TUBEMQ-327] Fix the concurrency problem in the example

---

tubemq-server/src/main/java/org/apache/tubemq/server/common/offsetstorage/ZkOffsetStorage.java

add exception process for BindException, print log and then exit

[TUBEMQ-316] add exception process for BindException, print log and then exit

---

tubemq-client-twins/tubemq-client-cpp/src/connection.cc
tubemq-client-twins/tubemq-client-cpp/src/connection.h
tubemq-client-twins/tubemq-client-cpp/src/connection_pool.h

[TUBEMQ-290]C++ SDK TCP Connect

[TUBEMQ-290]C++ SDK TCP Connect

---

LICENSE

For c/c++ reference code
https://github.com/Qihoo360/evpp/blob/master/evpp/any.h version c5038a6 LICENSE BSD 3-Clause
https://github.com/Qihoo360/evpp/blob/master/evpp/buffer.h version b2535d7 LICENSE BSD 3-Clause
https://github.com/apache/pulsar/blob/master/pulsar-client-cpp/lib/Future.h b3596c4 LICENSE Apache 2.0

[TUBEMQ-353]Update LICENSE about C/C++ SDK's code reference

---

CHANGES.md

Add 0.6.0 version release modification to CHANGES.md

[TUBEMQ-362]Add 0.6.0 version release modification to CHANGES.md

---

CHANGES.md
pom.xml
tubemq-client/pom.xml
tubemq-connectors/pom.xml
tubemq-connectors/tubemq-connector-flink/pom.xml
tubemq-connectors/tubemq-connector-flume/pom.xml
tubemq-connectors/tubemq-connector-spark/pom.xml
tubemq-core/pom.xml
tubemq-docker/pom.xml
tubemq-docker/tubemq-all/pom.xml
tubemq-docker/tubemq-build/pom.xml
tubemq-example/pom.xml
tubemq-server/pom.xml

[TUBEMQ-363]Adjust the version information of all pom.xml

 [TUBEMQ-363]Adjust the version information of all pom.xml

---

tubemq-client-twins/tubemq-client-cpp/src/rmt_data_cache.cc
tubemq-client-twins/tubemq-client-cpp/src/rmt_data_cache.h

[TUBEMQ-370] Calling GetCurConsumedInfo API always returns failure

[TUBEMQ-370] Calling GetCurConsumedInfo API always returns failure

---

tubemq-client-twins/tubemq-client-cpp/README.md
tubemq-docker/tubemq-cpp/Dockerfile
tubemq-docker/tubemq-cpp/README.md
tubemq-docker/tubemq-cpp/pom.xml

support build C++ SDK with docker image to solve dependency problem

[TUBEMQ-390] support build C++ SDK with docker image

---

tubemq-client-twins/tubemq-client-python/README.md
tubemq-client-twins/tubemq-client-python/src/python/example/README.md

[TUBEMQ-401] fix readme bug

---

README.md

1. Translate words to English.
"比如:" -> "e.g."
2. Fix spelling errors.
"Afater" => "After"
3. Convert fullwidth characters to halfwidth characters.
Thanks :")

[TUBEMQ-407] Fix some content in README.md

---

README.md

[TUBEMQ-408] fix link problem in readme

---

pom.xml
tubemq-client/pom.xml
tubemq-connectors/pom.xml
tubemq-connectors/tubemq-connector-flink/pom.xml
tubemq-connectors/tubemq-connector-flume/pom.xml
tubemq-connectors/tubemq-connector-spark/pom.xml
tubemq-core/pom.xml
tubemq-docker/pom.xml
tubemq-docker/tubemq-all/pom.xml
tubemq-docker/tubemq-build/pom.xml
tubemq-example/pom.xml
tubemq-server/pom.xml

[TUBEMQ-429] adjust the version information of all pom.xml to 0.7.0-incubating

[TUBEMQ-429] adjust the version information of all pom.xml to 0.7.0-incubating

---

tubemq-client/src/main/java/org/apache/tubemq/client/config/ConsumerConfig.java
tubemq-client/src/main/java/org/apache/tubemq/client/consumer/PullMessageConsumer.java

Supplement the usage notes of Java SDK's API

[TUBEMQ-419] SetMaxPartCheckPeriodMs() negative number, getMessage() still lock the thread[addendum]

---

tubemq-server/src/main/java/org/apache/tubemq/server/broker/web/BrokerAdminServlet.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/WebParameterUtils.java

Adjust Broker's HTTP API implementation according to the new parameter check scheme：check the parameters through the field definition table of WEB API, unify the parameter field names and attribute values of each API interface, and facilitate interface expansion and maintenance

[TUBEMQ-436] Adjust Broker's HTTP API implementation

---

tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/TubemqTableSourceSinkFactory.java
tubemq-connectors/tubemq-connector-flink/src/main/resources/META-INF/services/org.apache.flink.table.factories.TableFactory

There is a issue when creating table source sink factory instance, fixed it with this pr.
Jira link: https://issues.apache.org/jira/browse/TUBEMQ-437

[TUBEMQ-437] Fix tubemq table source sink factory instance creating problem

---

tubemq-core/src/main/java/org/apache/tubemq/corebase/utils/Tuple2.java
tubemq-example/src/main/java/org/apache/tubemq/example/MAMessageProducerExample.java
tubemq-example/src/main/java/org/apache/tubemq/example/MessageConsumerExample.java
tubemq-example/src/main/java/org/apache/tubemq/example/MessageProducerExample.java
tubemq-example/src/main/java/org/apache/tubemq/example/MessagePullConsumerExample.java
tubemq-example/src/main/java/org/apache/tubemq/example/MessagePullSetConsumerExample.java
tubemq-server/src/main/java/org/apache/tubemq/server/tools/cli/CliProducer.java

1. Unify parameter names and formats to avoid ambiguity;
2. Optimize code implementation logic to reduce repetitive code;

[TUBEMQ-449]Adjust Example implementation

---

tubemq-server/src/main/java/org/apache/tubemq/server/common/fielddef/WebFieldDef.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/WebParameterUtils.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/nodemanage/nodebroker/BrokerConfManager.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerTopicConfHandler.java

1. add admin_query_topicName api to get topicName set of brokerId;
2. add admin_query_brokerId api to get brokerId set of topic；

[TUBEMQ-470] Add query API of TopicName and BrokerId collection

---

tubemq-manager/src/main/java/org/apache/tubemq/manager/controller/TubeMQResult.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/controller/cluster/ClusterController.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/controller/node/NodeController.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/controller/node/request/AddBrokersReq.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/controller/node/request/BrokerConf.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/service/NodeService.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/utils/ConvertUtils.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/utils/MasterUtils.java
tubemq-manager/src/test/java/org/apache/tubemq/manager/controller/TestBusinessController.java
tubemq-manager/src/test/java/org/apache/tubemq/manager/controller/TestNodeController.java

[TUBEMQ-468] add new feature - add one or more brokers in one cluster - online\offline\reload

[TUBEMQ-468] add new feature - add one or more brokers in one cluster - online\offline\reload

---

tubemq-server/src/main/java/org/apache/tubemq/server/broker/metadata/BrokerMetadataManager.java
tubemq-server/src/main/java/org/apache/tubemq/server/broker/metadata/MetadataManager.java
tubemq-server/src/main/java/org/apache/tubemq/server/broker/metadata/TopicMetadata.java
tubemq-server/src/main/java/org/apache/tubemq/server/broker/offset/DefaultOffsetManager.java
tubemq-server/src/main/java/org/apache/tubemq/server/broker/offset/OffsetService.java
tubemq-server/src/main/java/org/apache/tubemq/server/broker/web/BrokerAdminServlet.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/fielddef/WebFieldDef.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/offsetstorage/OffsetStorage.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/offsetstorage/ZkOffsetStorage.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/offsetstorage/zookeeper/ZKUtil.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/TMaster.java

1. Adjust OffsetStorage class, add the consum group information reading APIs of zk storage;
2. Adjust OffsetService class, add query and modify APIs of group Offset;
3. Adjust BrokerAdminServlet class, add group query, group offset query, and group offset clone APIs

[TUBEMQ-475] add the offset clone api of the consume group

---

tubemq-manager/src/main/java/org/apache/tubemq/manager/controller/cluster/ClusterController.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/controller/node/NodeController.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/utils/MasterUtils.java

[TUBEMQ-480] batch set brokers to read or write mode and query brokers run info or config

[TUBEMQ-480] batch set brokers to read or write mode and query brokers run info or config

---

tubemq-manager/src/main/java/org/apache/tubemq/manager/controller/node/request/BatchAddTopicReq.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/controller/node/request/CloneTopicReq.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/controller/topic/TopicTdmController.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/controller/topic/TopicWebController.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/service/NodeService.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/service/TubeMQHttpConst.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/service/tube/TubeHttpBrokerInfoList.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/service/tube/TubeHttpTopicInfoList.java
tubemq-manager/src/test/java/org/apache/tubemq/manager/controller/TestBusinessController.java

[TUBEMQ-487] add new feature clone topic + batch add topics

[TUBEMQ-487] add new feature clone topic + batch add topics

---

tubemq-manager/src/main/java/org/apache/tubemq/manager/controller/topic/TopicWebController.java

[TUBEMQ-488] reorg topic operation including batch delete / query / modify

[TUBEMQ-488] reorg topic operation including batch delete / query / modify

---

tubemq-manager/src/main/java/org/apache/tubemq/manager/controller/node/request/CloneOffsetReq.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/controller/topic/TopicWebController.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/service/NodeService.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/service/tube/TubeHttpTopicInfoList.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/utils/ConvertUtils.java

[TUBEMQ-465] add new feature - copy offset from one group to another

[TUBEMQ-465] add new feature - copy offset from one group to another

---

tubemq-server/src/main/java/org/apache/tubemq/server/broker/offset/DefaultOffsetManager.java
tubemq-server/src/main/java/org/apache/tubemq/server/broker/offset/OffsetService.java
tubemq-server/src/main/java/org/apache/tubemq/server/broker/web/BrokerAdminServlet.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/fielddef/WebFieldDef.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/fileconfig/ZKConfig.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/offsetstorage/OffsetStorage.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/offsetstorage/ZkOffsetStorage.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/offsetstorage/zookeeper/ZKUtil.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/ProcessResult.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/WebParameterUtils.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerTopicConfHandler.java

1. Add delete api of consume group offset;
2. Adjust the read implementation of ZK storage content
3. Optimized code implementation

[TUBEMQ-486]Add the delete API of consumer group offset

---

tubemq-client/src/main/java/org/apache/tubemq/client/producer/AllowedSetting.java
tubemq-core/src/main/java/org/apache/tubemq/corebase/TBaseConstants.java
tubemq-core/src/main/java/org/apache/tubemq/corebase/utils/MixedUtils.java
tubemq-core/src/main/java/org/apache/tubemq/corebase/utils/SettingValidUtils.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/fielddef/WebFieldDef.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/WebParameterUtils.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/bdbstore/bdbentitys/BdbClusterSettingEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/nodemanage/nodebroker/BrokerConfManager.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebMasterInfoHandler.java

1. add admin_query_cluster_default_setting
2. admin_set_cluster_default_setting
Currently, these only supports the setting of maxMsgSize, and later we can support other parameter settings based on this structure.

[TUBEMQ-500] Add setting operate API

---

tubemq-server/src/main/java/org/apache/tubemq/server/broker/BrokerServiceServer.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/fielddef/WebFieldDef.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/paramcheck/PBParameterUtils.java

1. adjust hostName, groupName, clientId fields check logic;
2. adjust topicName's check logic.

[TUBEMQ-508] Optimize Broker's PB parameter check processing logic

---

tubemq-client-twins/tubemq-client-cpp/CMakeLists.txt

[TUBEMQ-506] cmakelist error, rm -Werror

---

tubemq-manager/src/main/java/org/apache/tubemq/manager/controller/cluster/ClusterController.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/controller/cluster/request/DeleteClusterReq.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/repository/ClusterRepository.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/service/ClusterServiceImpl.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/service/TubeMQHttpConst.java
tubemq-manager/src/main/java/org/apache/tubemq/manager/service/interfaces/ClusterService.java

[TUBEMQ-531] delete cluster

---

NOTICE

1. Correct the year of NOTICE
2. Add missing information of NOTICE from other Apache licensed NOTICE files

[TUBEMQ-551] Adjust NOTICE file content

---

tubemq-server/src/main/java/org/apache/tubemq/server/broker/web/BrokerAdminServlet.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/webbase/WebMethodMapper.java

1. Accumulation rules for alignment record numbers;
2. Increase the space between different content in log printing

[TUBEMQ-556]Index value is bigger than the actual number of records

---

tubemq-client/src/main/java/org/apache/tubemq/client/producer/RoundRobinPartitionRouter.java

Co-authored-by: 曹显乐 <xianle.cao@vivo.com>

[TUBEMQ-555] short session data can only be written to a specific partition (addendum)

---

LICENSE

1. add Compass LICENSE notice;
2. add berkeleydb-je LICENSE notice.

[TUBEMQ-559] Update the LICENSE file according to the 0.8.0-RC2 review

---

DISCLAIMER
DISCLAIMER-WIP
LICENSE
NOTICE
pom.xml
tubemq-client/src/main/assembly/assembly.xml
tubemq-core/src/main/java/org/apache/tubemq/corebase/utils/TStringUtils.java
tubemq-server/src/main/assembly/assembly.xml

1. Restore the license to the relevant content of the source code;
2. Replace the related content of TStringUtils.java with the component content of Apache V2;
3. Change DISCLAIMER to DISCLAIMER-WIP

[TUBEMQ-562]Update project contents according to the 0.8.0-RC3 review

---

tubemq-core/src/main/java/org/apache/tubemq/corebase/utils/Tuple2.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/fielddef/WebFieldDef.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/fielddef/WebFieldType.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/WebParameterUtils.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/TMaster.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/nodemanage/nodebroker/TopicPSInfoManager.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/nodemanage/nodeconsumer/ConsumerBandInfo.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/nodemanage/nodeconsumer/ConsumerInfoHolder.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/action/screen/Master.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebOtherInfoHandler.java
tubemq-server/src/test/java/org/apache/tubemq/server/master/nodemanage/nodebroker/TopicPSInfoManagerTest.java

1. Adjust WebOtherInfoHandler class implementation
2. Optimize the implementation logic of related subclasses
3. Add the field name definition of web api

[TUBEMQ-571] Adjust WebOtherInfoHandler class implementation

---

tubemq-server/src/main/java/org/apache/tubemq/server/common/fielddef/WebFieldDef.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/bdbstore/bdbentitys/BdbGroupFlowCtrlEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/nodemanage/nodebroker/BrokerConfManager.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebAdminFlowRuleHandler.java

Adjust WebAdminFlowRuleHandler class implementation

[TUBEMQ-573]Adjust WebAdminFlowRuleHandler class implementation

---

tubemq-core/src/main/java/org/apache/tubemq/corebase/TBaseConstants.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/TServerConstants.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/statusdef/ManageStatus.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/statusdef/RuleStatus.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/statusdef/TopicStatus.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/ProcessResult.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/WebParameterUtils.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/BaseEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/BrokerConfEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/ClusterSettingEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/GroupBlackListEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/GroupConsumeCtrlEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/GroupFlowCtrlEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/TopicAuthCtrlEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/TopicConfEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/TopicPropGroup.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/BrokerConfigMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/ClusterConfigMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/GroupBlackListMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/GroupConsumeCtrlMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/GroupFlowCtrlMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/TopicAuthCtrlMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/TopicConfigMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/nodemanage/nodebroker/BrokerConfManager.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebAdminGroupCtrlHandler.java

1. Increase the representation object of metadata in memory;
2. Add operation interfaces that need to be supported by the actual storage layer of metadata
3. Other minor adjustments and optimizations

[TUBEMQ-576] Build metadata entity classes

---

tubemq-server/src/main/java/org/apache/tubemq/server/master/bdbstore/DefaultBdbStoreService.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/entity/GroupFilterCtrlEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/ClusterConfigMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/GroupBlackListMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/GroupConfigMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/GroupFilterCtrlMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/TopicConfigMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/dao/mapper/TopicCtrlMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/impl/bdbimpl/BdbBrokerConfigMapperImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/impl/bdbimpl/BdbClusterConfigMapperImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/impl/bdbimpl/BdbGroupBlackListMapperImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/impl/bdbimpl/BdbGroupConfigMapperImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/impl/bdbimpl/BdbGroupFilterCtrlMapperImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/impl/bdbimpl/BdbTopicConfigMapperImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/impl/bdbimpl/BdbTopicCtrlMapperImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/impl/bdbimpl/TBDBStoreTables.java

Add Mapper implementation class based on BDB storage

[TUBEMQ-578] Build implementation classes based on BDB storage

---

tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/DataOpErrCode.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/MetaStoreService.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metastore/impl/bdbimpl/BdbMetaStoreServiceImpl.java

1. Implement the keep-alive class based on BDB;
2. Implement BDB-based metadata management operation class

[TUBEMQ-580] Build active and standby keep-alive services

---

tubemq-core/src/main/java/org/apache/tubemq/corebase/utils/KeyBuilderUtils.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/fielddef/WebFieldDef.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/ProcessResult.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/WebParameterUtils.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/bdbstore/bdbentitys/BdbGroupFilterCondEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/bdbstore/bdbentitys/BdbGroupFlowCtrlEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/MetaDataManager.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/BdbMetaStoreServiceImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/MetaStoreService.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/TStoreConstants.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/BaseEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/ClusterSettingEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/GroupBlackListEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/GroupConsumeCtrlEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/GroupResCtrlEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/TopicDeployConfEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/mapper/GroupConsumeCtrlMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/mapper/TopicDeployConfigMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbGroupConsumeCtrlMapperImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbTopicDeployConfigMapperImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/GroupProcessResult.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebGroupConsumeCtrlHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebGroupResCtrlHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebMasterInfoHandler.java

1. add WebGroupConsumeCtrlHandler class implementation
2. adjust MetaDataManager and BdbMetaStoreServiceImpl class implementation
3. adjust WebGroupResCtrlHandler class implementation
4. other optimizations

[TUBEMQ-593]Add WebGroupConsumeCtrlHandler class implementation

---

tubemq-server/src/main/java/org/apache/tubemq/server/common/TServerConstants.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/fielddef/WebFieldDef.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/WebParameterUtils.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/MetaDataManager.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/BdbMetaStoreServiceImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/MetaStoreService.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/BaseEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/BrokerConfEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/ClusterSettingEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/GroupConsumeCtrlEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/GroupResCtrlEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/TopicCtrlEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/TopicDeployConfEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/mapper/BrokerConfigMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/mapper/TopicDeployConfigMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbBrokerConfigMapperImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbTopicDeployConfigMapperImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/BrokerProcessResult.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerConfHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebGroupConsumeCtrlHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebGroupResCtrlHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebMasterInfoHandler.java

1. add WebBrokerConfHandler class implementation
2. adjust entity classes

[INLONG-595]Add WebBrokerConfHandler class implementation

---

tubemq-server/src/main/java/org/apache/tubemq/server/common/fielddef/WebFieldDef.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/statusdef/ManageStatus.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/MetaDataManager.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/BdbMetaStoreServiceImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/MetaStoreService.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/ClusterSettingEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/TopicCtrlEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/TopicDeployEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/mapper/TopicDeployMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbTopicDeployMapperImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/TopicProcessResult.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebAdminFlowRuleHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerConfHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebMasterInfoHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebTopicConfHandler.java

1. add WebTopicConfHandler class implementation
2. adjust MetaDataManager.java implementation

[INLONG-596] Add WebTopicConfHandler class implementation

---

tubemq-server/src/main/java/org/apache/tubemq/server/broker/web/BrokerAdminServlet.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/WebParameterUtils.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/MetaDataManager.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebAdminFlowRuleHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerConfHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerTopicConfHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebGroupConsumeCtrlHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebGroupResCtrlHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebMasterInfoHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebOtherInfoHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebTopicCtrlHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebTopicDeployHandler.java

1. Adjust the corresponding functions, changing the field container parameter type to generic type
2. Adjust other implementations

[INLONG-599]Adjust WebParameterUtils.java's static functions

---

tubemq-server/src/main/java/org/apache/tubemq/server/common/fielddef/WebFieldDef.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/paramcheck/PBParameterUtils.java
tubemq-server/src/main/java/org/apache/tubemq/server/common/utils/WebParameterUtils.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/bdbstore/bdbentitys/BdbGroupFlowCtrlEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/MetaDataManager.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/BdbMetaStoreServiceImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/MetaStoreService.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/BaseEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/ClusterSettingEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/GroupConsumeCtrlEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/entity/GroupResCtrlEntity.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/dao/mapper/GroupConsumeCtrlMapper.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbGroupConsumeCtrlMapperImpl.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebAdminFlowRuleHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebAdminGroupCtrlHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebAdminTopicAuthHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebBrokerConfHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebGroupConsumeCtrlHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebGroupResCtrlHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebMasterInfoHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebOtherInfoHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebTopicCtrlHandler.java
tubemq-server/src/main/java/org/apache/tubemq/server/master/web/handler/WebTopicDeployHandler.java

1. adjust WebAdminGroupCtrlHandler class implementation
2. adjust WebAdminFlowRuleHandler class implementation
3. adjust WebAdminTopicAuthHandler class implementation

[INLONG-574]Adjust WebAdminGroupCtrlHandler class implementation

---

tubemq-client-twins/tubemq-client-go/config/config.go
tubemq-client-twins/tubemq-client-go/config/config_test.go

[INLONG-619]Configuration for Go SDK.

---

tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
tubemq-client-twins/tubemq-client-go/client/heartbeat.go
tubemq-client-twins/tubemq-client-go/flowctrl/handler.go
tubemq-client-twins/tubemq-client-go/go.mod
tubemq-client-twins/tubemq-client-go/log/config.go
tubemq-client-twins/tubemq-client-go/log/log.go
tubemq-client-twins/tubemq-client-go/log/log_test.go
tubemq-client-twins/tubemq-client-go/log/logger.go
tubemq-client-twins/tubemq-client-go/log/warpper_zaplog.go

[INLONG-637]Go SDK log

---

inlong-tubemq/tubemq-manager/bin/start-admin-docker.sh
inlong-tubemq/tubemq-manager/bin/start-admin.sh

[INLONG-656] fix tubemanager start.sh

[INLONG-656] fix tubemanager start.sh

---

inlong-agent/agent-release/package.xml
inlong-agent/agent-release/pom.xml

[INLONG-667] rename tar in agent

[INLONG-667] rename tar in agent

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerResultFormatter.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/dtos/DataConfig.java

[INLONG-688] change additionstr to additionAtr in agent

[INLONG-688] change additionstr to additionAtr in agent

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/beans/TryBean.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdpart/mq/CreateTubeConsumeGroupTaskEventListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdpart/mq/TubeMqOptService.java

[INLONG-694] Add retry mechanism for creating tube consumer group

[INLONG-694] Add retry mechanism for creating tube consumer group

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/beans/TryBean.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdpart/mq/CreateTubeConsumeGroupTaskEventListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/newbusiness/CreateResourceWorkflowDefinition.java

[INLONG-701] Update create resource workflow definition

[INLONG-701] Update create resource workflow definition

---

inlong-manager/manager-dao/pom.xml
inlong-manager/manager-service/pom.xml

Fixed the problem of log dependency conflict

[INLONG-751] InLong Manager start up error

---

tubemq-client-twins/tubemq-client-go/rpc/broker.go
tubemq-client-twins/tubemq-client-go/rpc/client.go
tubemq-client-twins/tubemq-client-go/rpc/master.go

[INLONG-764]Fix Go SDK RPC Request bug

---

README.md

Fixes [Jira Issue](https://issues.apache.org/jira/projects/INLONG/issues): 
https://issues.apache.org/jira/browse/INLONG-770
there are some building method changes, it's better to update the readme document,
*(or)*
*(or)*
*(example:)* …

[INLONG-770] update the readme document

---

tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
tubemq-client-twins/tubemq-client-go/codec/tubemq_codec.go
tubemq-client-twins/tubemq-client-go/rpc/client.go

Fixes [Jira Issue](https://issues.apache.org/jira/browse/INLONG-766): https://issues.apache.org/jira/browse/INLONG-766
*Fix Go SDK codec bug
*(or)*
*(or)*
*(example:)* …

[INLONG-766]Fix Go SDK Codec Bug

---

inlong-tubemq/tubemq-docker/pom.xml
inlong-tubemq/tubemq-docker/tubemq-cpp/pom.xml

Fixes [Jira Issue](https://issues.apache.org/jira/projects/INLONG/issues):
https://issues.apache.org/jira/browse/INLONG-776
*(or)*
*(or)*
*(example:)* …

[INLONG-776] fix the version error for tubemq cpp client docker image

---

tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
tubemq-client-twins/tubemq-client-go/client/heartbeat.go
tubemq-client-twins/tubemq-client-go/rpc/master.go
tubemq-client-twins/tubemq-client-go/sub/info.go

Fixes [Jira Issue](https://issues.apache.org/jira/projects/INLONG/issues): https://issues.apache.org/jira/browse/INLONG-771
*(or)*
*(or)*
*(example:)* …

[INLONG-771]Fix Go SDK Authorization Bug

---

tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
tubemq-client-twins/tubemq-client-go/metadata/consumer_event.go
tubemq-client-twins/tubemq-client-go/remote/remote.go
tubemq-client-twins/tubemq-client-go/rpc/master.go

Fixes [Jira Issue](https://issues.apache.org/jira/projects/INLONG/issues): https://issues.apache.org/jira/browse/INLONG-778
*(or)*
*(or)*
*(example:)* …

[INLONG-778]Fix Go SDK Consumer Bug

---

tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
tubemq-client-twins/tubemq-client-go/flowctrl/handler.go

Fixes [Jira Issue](https://issues.apache.org/jira/projects/INLONG/issues): https://issues.apache.org/jira/browse/INLONG-780
*(or)*
*(or)*
*(example:)* …

[INLONG-780]Fix flow control bug

---

inlong-agent/agent-docker/Dockerfile
inlong-agent/agent-docker/README.md
inlong-agent/agent-docker/agent-docker.sh
inlong-agent/agent-docker/pom.xml
inlong-agent/agent-release/assembly.xml
inlong-agent/agent-release/pom.xml
inlong-agent/bin/agent-env.sh
inlong-agent/conf/log4j.properties
inlong-agent/pom.xml
inlong-tubemq/pom.xml
pom.xml

Fixes [Jira Issue](https://issues.apache.org/jira/projects/INLONG/issues):
https://issues.apache.org/jira/browse/INLONG-781
*(or)*
*(or)*
*(example:)* …

[INLONG-781] add inlong agent docker image support

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes [Jira Issue](https://issues.apache.org/jira/projects/INLONG/issues):
https://issues.apache.org/jira/browse/INLONG-782
*(or)*
*(or)*
*(example:)* …

[INLONG-782] Optimize The PULL_REQUEST_TEMPLATE

---

.github/workflows/ci_build.yml
.github/workflows/ci_checkstyle.yml
.github/workflows/ci_ut.yml

https://issues.apache.org/jira/browse/INLONG-732
Optimize the  CI/CD workflow for build and integration test.
- update unit test workflow file name
- add build workflow
- add checkstyle workflow

[INLONG-732] ci: optimize the CI/CD workflow for build and integration test

---

tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
tubemq-client-twins/tubemq-client-go/client/heartbeat.go

https://issues.apache.org/jira/browse/INLONG-784
*(or)*
*(or)*
*(example:)* …

[INLONG-784]Fix Go SDK Heartbeat Bug

---

tubemq-client-twins/tubemq-client-go/metadata/partition.go
tubemq-client-twins/tubemq-client-go/metadata/subcribe_info.go

https://issues.apache.org/jira/browse/INLONG-785
*(or)*
*(or)*
*(example:)* …

[INLONG-785]Fix Go SDK Metadata Bug

---

tubemq-client-twins/tubemq-client-go/config/config.go
tubemq-client-twins/tubemq-client-go/config/config_test.go
tubemq-client-twins/tubemq-client-go/log/config.go
tubemq-client-twins/tubemq-client-go/remote/remote.go

https://issues.apache.org/jira/projects/INLONG/issues/791
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? (not applicable / docs / JavaDocs …

[INLONG-791]Go SDK Support multiple topic addresses

---

tubemq-client-twins/tubemq-client-go/codec/tubemq_codec.go
tubemq-client-twins/tubemq-client-go/errs/errs.go
tubemq-client-twins/tubemq-client-go/metadata/metadata.go
tubemq-client-twins/tubemq-client-go/metadata/node.go
tubemq-client-twins/tubemq-client-go/metadata/partition.go
tubemq-client-twins/tubemq-client-go/metadata/subscribe_info.go
tubemq-client-twins/tubemq-client-go/remote/remote.go

https://issues.apache.org/jira/projects/INLONG/issues/793
*(or)*
*(or)*
*(example:)* …

[INLONG-793]Fix Some Corner Case in Go SDK

---

inlong-manager/manager-api/pom.xml
inlong-website/Dockerfile
inlong-website/README.md
inlong-website/nginx.conf
inlong-website/pom.xml

https://issues.apache.org/jira/projects/INLONG/issues/NLONG-794
*(or)*
*(or)*
*(example:)* …

[INLONG-794] add website docker image

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java

https://issues.apache.org/jira/projects/INLONG/issues/INLONG-799
*(or)*
*(or)*
*(example:)* …

[INLONG-799] fix common.properties path for dataproxy

---

inlong-common/src/main/java/org/apache/inlong/commons/msg/DataInputBuffer.java
inlong-common/src/main/java/org/apache/inlong/commons/msg/DataOutputBuffer.java
inlong-common/src/main/java/org/apache/inlong/commons/msg/TDMsgAttrBuilder.java
inlong-dataproxy-sdk/src/main/java/org/apache/inlong/dataproxy/codec/EncodeObject.java
inlong-dataproxy-sdk/src/main/java/org/apache/inlong/dataproxy/codec/ProtocolDecoder.java
inlong-dataproxy-sdk/src/main/java/org/apache/inlong/dataproxy/codec/ProtocolEncoder.java
inlong-dataproxy-sdk/src/main/java/org/apache/inlong/dataproxy/config/EncryptConfigEntry.java

https://issues.apache.org/jira/projects/INLONG/issues/INLONG-800
*Fix codetyle.*
*Fixed codetyle.*
*(or)*
*(or)*
*(example:)* …

[INLONG-800] Fix codestyle of some comments and methods names.

---

README.md

https://issues.apache.org/jira/projects/INLONG/issues/INLONG-803
*(or)*
*(or)*
*(example:)* …

[INLONG-803] add docker requirement for building InLong

---

.asf.yaml

https://issues.apache.org/jira/projects/INLONG/issues/INLONG-804
*(or)*
*(or)*
*(example:)* …

[INLONG-804] Optimize the ASF Configuration

---

.asf.yaml

https://issues.apache.org/jira/projects/INLONG/issues/INLONG-806
*(or)*
*(or)*
*(example:)* …

[INLONG-806] open GitHub Issue For InLong

---

inlong-manager/manager-docker/Dockerfile
inlong-manager/manager-docker/README.md
inlong-manager/manager-docker/manager-docker.sh
inlong-manager/manager-docker/pom.xml
inlong-manager/manager-web/assembly.xml
inlong-manager/manager-web/pom.xml
inlong-manager/pom.xml

https://issues.apache.org/jira/projects/INLONG/issues/INLONG-773
*(or)*
*(or)*
*(example:)* …

[INLONG-773] add manager docker image

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md

fix #1264
*(or)*
*(or)*
*(example:)* …

[INLONG-1264][Platform] update the issue template for InLong

---

.asf.yaml
README.md
inlong-tubemq/pom.xml

[INLONG-1394][Platform] Update the document after Migrate InLong Issue
Fixes #1394
*(or)*
*(or)*
*(example:)*
- If yes, …

[INLONG-1394][Platform] Update the document after Migrate InLong Issue

---

inlong-dataproxy/dataproxy-source/pom.xml
inlong-dataproxy/pom.xml

Fixes #1407 
*(or)*
*(or)*
*(example:)* …

[INLONG-1407][DataProxy]Adjust the pom dependency of the DataProxy module

---

NOTICE

Fixes #1411 
*(or)*
*(or)*
*(example:)* …

[INLONG-1411] Adjust the project NOTICE content

---

inlong-tubemq/tubemq-docker/tubemq-manager/Dockerfile
inlong-tubemq/tubemq-docker/tubemq-manager/README.md
inlong-tubemq/tubemq-docker/tubemq-manager/manager-docker.sh
inlong-tubemq/tubemq-manager/src/main/resources/application.properties

Fixes #1413
*(or)*
*(or)*
*(example:)* …

[INLONG-1413][tubemq] init tubemq cluster for tubemq manager docker image

---

inlong-distribution/pom.xml

Fixes #1417
*(or)*
*(or)*
*(example:)* …

[INLONG-1417][Platform] rename the distribution file for inlong

---

inlong-manager/manager-docker/Dockerfile
inlong-manager/manager-docker/README.md
inlong-manager/manager-docker/manager-docker.sh
inlong-manager/manager-docker/pom.xml
inlong-manager/manager-web/bin/startup.sh
inlong-manager/manager-web/src/main/resources/application-dev.properties
inlong-manager/manager-web/src/main/resources/application-prod.properties
inlong-manager/manager-web/src/main/resources/application-test.properties

Fixes #1423
modify the docker image of the inlong-manager module
add env varibles in Dockerfile

[INLONG-1423][InLong-Manager] modify the docker image of the inlong-manager module

---

tubemq-client-twins/tubemq-client-go/client/consumer.go
tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
tubemq-client-twins/tubemq-client-go/remote/remote.go

Fixes #1427
*(or)*
*(or)*
*(example:)* …

[INLONG-1427]Go SDK return maxOffset and updateTime in ConsumerOffset

---

tubemq-client-twins/tubemq-client-go/example/consumer.go

Fixes #1430
*(or)*
*(or)*
*(example:)* …

[INLONG-1430]Go SDK example

---

docker/docker-compose/README.md
docker/docker-compose/docker-compose.yml
docker/docker-compose/sql/apache_inlong_manager.sql
docker/docker-compose/sql/tubemanager.sql
inlong-dataproxy/bin/flume-ng
inlong-dataproxy/dataproxy-docker/README.md
inlong-manager/manager-docker/Dockerfile
inlong-manager/manager-docker/README.md
inlong-manager/manager-docker/manager-docker.sh
inlong-manager/manager-docker/pom.xml
inlong-manager/manager-web/bin/restart.sh
inlong-manager/manager-web/bin/shutdown.sh
inlong-manager/manager-web/bin/startup.sh
inlong-sort/pom.xml
inlong-sort/sort-formats/pom.xml
inlong-tubemq/tubemq-manager/bin/start-manager.sh
inlong-website/Dockerfile
inlong-website/nginx.conf
inlong-website/website-docker.sh

Fixes #1320 
Support Standalone mode to run InLong Using Docker Compose
*(or)*
*(or)*
*(example:)* …

[INLONG-1320][platform] Support Standalone mode to run InLong Using Docker Compose

---

inlong-tubemq/resources/assets/scripts/brokerDetail.js
inlong-tubemq/resources/assets/scripts/common/module.js
inlong-tubemq/resources/assets/scripts/topicDetail.js
inlong-tubemq/resources/templates/screen/config/brokerDetail.vm
inlong-tubemq/resources/templates/screen/config/topicDetail.vm
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerConfig.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/utils/WebParameterUtils.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/MasterConfig.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/MetaDataManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebBrokerConfHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebMasterInfoHandler.java

Fixes #1439
1. remove "deleteWhen" field in resource files;
2. add the validity check for the port setting;

[INLONG-1439] Add the port legal check and remove the useless deleteWhen field

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/MetaDataManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/BdbMetaStoreServiceImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/MetaStoreService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/TopicDeployEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/GroupConsumeCtrlMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/TopicDeployMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbBrokerConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbGroupConsumeCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbTopicDeployMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebTopicDeployHandler.java

[INLONG-1444] Fix Web API multiple field search logic bug

---

inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/policies/FlowCtrlRuleHandler.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/utils/TStringUtils.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/fielddef/WebFieldDef.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/bdbstore/bdbentitys/BdbGroupFlowCtrlEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/MetaDataManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/GroupConsumeCtrlEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/TopicCtrlEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbBrokerConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbGroupConsumeCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebAdminGroupCtrlHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebGroupConsumeCtrlHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebGroupResCtrlHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebTopicDeployHandler.java

[INLONG-1447] Fix Group Control API logic bug

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/utils/WebParameterUtils.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/MetaDataManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/BdbMetaStoreServiceImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebAdminFlowRuleHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebTopicCtrlHandler.java

[INLONG-1451] Fix the bugs of topic control api

---

docker/README.md
docker/get-project-version.py
docker/publish.sh

Fixes #1455 
*(or)*
*(or)*
*(example:)* …

[INLONG-1455][platform] add a script to publish docker images

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Constants.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/Entrance.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/Record.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/SerializedRecord.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/deserialization/DeserializationSchema.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/deserialization/TDMsgMixedDeserializer.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/metrics/MetricData.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/metrics/MetricsAggregator.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/metrics/MetricsAssignerWithPeriodicWatermarks.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/metrics/MetricsLogSink.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/transformation/FieldMappingTransformer.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/transformation/RecordTransformer.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/tubemq/MultiTenancyTubeConsumer.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/flink/deserialization/MultiTenancyTDMsgMixedDeserializerTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/flink/hive/HiveSinkITCase.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/flink/metrics/MetricDataTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/flink/metrics/MetricsLogSinkTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/flink/transformation/FieldMappingTransformerTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/flink/transformation/RecordTransformerTest.java

Fixes #1335
*(or)*
*(or)*
*(example:)* …

[INLONG-746] Support metric system in inlong-sort (#1335)

---

docker/docker-compose/docker-compose.yml
inlong-dataproxy/dataproxy-docker/dataproxy-docker.sh

Fixes #1462
*(or)*
*(or)*
*(example:)* …

[INLONG-1462][dataproxy] fix the properties error

---

codestyle/checkstyle.xml
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/TestFileAgent.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestTextFileReader.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/trigger/TestWatchDirTrigger.java
inlong-dataproxy-sdk/src/test/java/org/apache/inlong/dataproxy/TestMetricWorkerThread.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/workflow/WorkflowApproverFilterContext.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentSysConfigServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ClusterInfoServiceImpl.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/source/TubeSourceInfo.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/deserialization/MultiTenancyTDMsgMixedDeserializer.java
inlong-sort/sort-formats/format-tdmsg-csv/src/main/java/org/apache/inlong/sort/formats/tdmsgcsv/TDMsgCsvMixedFormatDeserializer.java

[INLONG-1464] Add code CheckStyle rules

---

inlong-agent/agent-docker/Dockerfile

Fixes #1466
*(or)*
*(or)*
*(example:)* …

[INLONG-1466][agent] fix the snappy error for agent

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerResultFormatter.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/dtos/DataConfig.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/dtos/JobProfileDto.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/PluginUtils.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/TestFileAgent.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/MockSink.java

Fixes #1337
The agent should support file name pattern YYYYDDMM
Add new feature to support file name pattern YYYYDDMM
- If yes, how is the feature documented? (docs)

[INLONG-748][Agent] Support file name pattern YYYYDDMM

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/utils/HttpUtils.java

Fixes #1443
This requirement is supported by the HttpUtils.java[1] class, no need to construct SDK
There are programs that need to access TubeMQ's Master server collection through HTTP, you can refer to the demo example and use it directly
[1] inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/utils/HttpUtils.java

[INLONG-1443] Provide management interface SDK

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/BusinessEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/BusinessEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/DataProxyClusterServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java

Fixes #1474
the interface of get data proxy configurations got abnormal status result
when get data proxy configurations, filter by business status and is_deleted fields.

[INLONG-1474] the interface of get data proxy configurations got abnormal status result

---

.gitignore

Fixes #1498 
ignore the files with versionsBackup suffix for the bumped version
*(or)*
*(or)*
*(example:)* …

[INLONG-1498] ignore the files with versionsBackup suffix for the bumped version

---

CHANGES.md

Fixes #1491
*(or)*
*(or)*
*(example:)* …

[INLONG-1491] Add 0.10.0 version release modification to CHANGES.md

---

inlong-sort/pom.xml

Fixes #1505
*(or)*
*(or)*
*(example:)* …

[INLONG-1505] fix dependencies error when build release-0.10.0

---

CHANGES.md

Fixes #1509
*(or)*
*(or)*
*(example:)* …

[INLONG-1509] fix duplicate issues be counted in CHANGES.md

---

tubemq-client-twins/tubemq-client-go/multiplexing/multiplexing.go

Fixes #1507 
*(or)*
*(or)*
*(example:)* …

[INLONG-1507]Fix Go SDK connection pool bug.

---

inlong-website/nginx.conf

Fixes #1514
*(or)*
*(or)*
*(example:)* …

[INLONG-1514] fix the the incorrect license header

---

tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
tubemq-client-twins/tubemq-client-go/client/version.go
tubemq-client-twins/tubemq-client-go/metadata/subscribe_info.go

Fixes #1527 
*(or)*
*(or)*
*(example:)* …

[INLONG-1527]Go SDK throw error if it fails to connect to master

---

tubemq-client-twins/tubemq-client-go/flowctrl/handler.go
tubemq-client-twins/tubemq-client-go/flowctrl/item.go
tubemq-client-twins/tubemq-client-go/metadata/partition.go

Fixes #1531 
*(or)*
*(or)*
*(example:)* …

[INLONG-1531]Go SDK should init the flow control item of the partition

---

tubemq-client-twins/tubemq-client-go/example/consumer.go

Fixes #1533 
*(or)*
*(or)*
*(example:)* …

[INLONG-1533]Provide more example for Go SDK

---

tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
tubemq-client-twins/tubemq-client-go/flowctrl/handler.go
tubemq-client-twins/tubemq-client-go/remote/remote.go

Fixes #1535 
*(or)*
*(or)*
*(example:)* …

[INLONG-1535]Go SDK should be closed before stopping the event processing goroutine

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/MetaDataManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/MetaStoreService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/DefBrokerRunManager.java

[INLONG-1538] TubeMQ reports the error "Topic xxx not publish" when producing data

---

inlong-tubemq/tubemq-core/src/main/proto/BrokerService.proto

[INLONG-1541] Add replica node request and response define in the BrokerService.proto

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/MessageStore.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/MessageStoreManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/StoreService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/disk/MsgFileStore.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/mem/MsgMemStore.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/nodeinfo/ReplicaNodeInfo.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/utils/DataStoreUtils.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/TServerConstants.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/utils/WebParameterUtils.java
inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/broker/msgstore/mem/MsgMemStoreTest.java

[INLONG-1544] Add replica consumption logic in broker node

---

inlong-tubemq/tubemq-core/src/main/proto/BrokerService.proto

Reverts apache/incubator-inlong#1543

Revert "[INLONG-1541] Add replica node request and response define in the BrokerService.proto"

---

tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
tubemq-client-twins/tubemq-client-go/flowctrl/handler.go
tubemq-client-twins/tubemq-client-go/metadata/partition.go

Fixes #1550 
*(or)*
*(or)*
*(example:)* …

[INLONG-1550]Go SDK should obey the flow control rule

---

inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/BaseMessageConsumer.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/policies/FlowCtrlRuleHandler.java
inlong-tubemq/tubemq-core/src/test/java/org/apache/inlong/tubemq/corebase/policies/TestFlowCtrlRuleHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/TubeBroker.java

[INLONG-1552]Java SDK should deal with the default flow control rule

---

tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
tubemq-client-twins/tubemq-client-go/config/config.go
tubemq-client-twins/tubemq-client-go/remote/remote.go

Fixes #1555 
*(or)*
*(or)*
*(example:)* …

[INLONG-1555]Record the consumer config to the log

---

tubemq-client-twins/tubemq-client-go/example/multi_routine_consumer.go

Fixes #1558 
*(or)*
*(or)*
*(example:)* …

[INLONG-1558]Go SDK multi goroutine consumer example

---

tubemq-client-twins/tubemq-client-go/client/consumer.go
tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
tubemq-client-twins/tubemq-client-go/client/heartbeat.go
tubemq-client-twins/tubemq-client-go/example/consumer.go
tubemq-client-twins/tubemq-client-go/example/multi_routine_consumer.go

Fixes #1563 
*(or)*
*(or)*
*(example:)* …

[INLONG-1563] Fix the bug which can't stop the heartbeat timer and make close can be called once

---

tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
tubemq-client-twins/tubemq-client-go/client/heartbeat.go
tubemq-client-twins/tubemq-client-go/remote/remote.go
tubemq-client-twins/tubemq-client-go/sub/info.go

Fixes #1566 
*(or)*
*(or)*
*(example:)* …

[INLONG-1566]Fix the bug which will cause the user defined partition offset can not take effect

---

inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/baseconsumer.cc
inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/client_subinfo.cc
inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/client_subinfo.h

[INLONG-1569][TubeMQ] The first_registered is not the same with its naming

---

tubemq-client-twins/tubemq-client-go/errs/errs.go
tubemq-client-twins/tubemq-client-go/example/multi_routine_consumer.go
tubemq-client-twins/tubemq-client-go/go.mod
tubemq-client-twins/tubemq-client-go/tdmsg/bin_msg.go
tubemq-client-twins/tubemq-client-go/tdmsg/td_msg.go
tubemq-client-twins/tubemq-client-go/util/util.go

Fixes #1584 
*(or)*
*(or)*
*(example:)* …

[INLONG-1584]Go SDK TDMsg Decode Support

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constants/CommonConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/ProxyMessage.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/plugin/MessageFilter.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/plugin/Sink.java
inlong-agent/agent-docker/README.md
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerResultFormatter.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/dtos/DataConfig.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/dtos/JobProfileDto.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/filter/DefaultMessageFilter.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/message/PackProxyMessage.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/TestFileAgent.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/filter/TestStreamIdFilter.java

Fixes #1732 
In the current agent module, the bid and tid (or dsid) fields are not easy to understan, so modified them to inlongGroupId and inlongStreamId.

[INLONG-1732][InLong-Agent] Modify bid and tid to inlongGroupId and inlongStreamId

---

inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/MessagePullConsumerExample.java
inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/MsgRecvStats.java

[INLONG-1748][Improve] Optimize the realization of class MessagePullConsumerExample

---

inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/MessageConsumer.java
inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/MessagePullConsumerExample.java
inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/MessagePullSetConsumerExample.java
inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/MessagePushConsumerExample.java

[INLONG-1758] Optimize the realization of class MessagePullSetConsumerExample

---

inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/utils/MixedUtils.java
inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/MessageProducerExample.java
inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/MessagePullConsumerExample.java
inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/MessagePullSetConsumerExample.java
inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/MessagePushConsumerExample.java
inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/MsgSendReceiveStats.java

[INLONG-1760] Optimize the realization of class MessageProducerExample

---

inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/utils/MixedUtils.java
inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/MAMessageProducerExample.java
inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/MessageProducerExample.java

[INLONG-1761] Optimize the realization of class MAMessageProducerExample

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/tools/cli/CliProducer.java

[INLONG-1765] Optimize the realization of class CliProducer

---

inlong-website/src/pages/AccessDashboard/ExecutionLogModal.tsx

Fixes #1687
*(or)*
*(or)*
*(example:)* …

[INLONG-1687] Supports paging query for workflow execution log

---

inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/ConsumerResult.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/rv/ProcessResult.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/RpcConstants.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/codec/PbEnDecoder.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/service/MasterService.java
inlong-tubemq/tubemq-core/src/main/proto/MasterService.proto
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/TMaster.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbBrokerConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbClusterConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbGroupConsumeCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbGroupResCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbTopicCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbTopicDeployMapperImpl.java

[INLONG-1775]Define the PB messages used in client partition-assigned

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/dataconsumption/ConsumptionInfo.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/datasource/SourceFileBasicInfo.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/datastorage/BaseStorageInfo.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/datastream/DataStreamApproveInfo.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/datastream/DataStreamFieldInfo.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/BusinessExtEntityMapper.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/DataStreamEntityMapper.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/DataStreamExtEntityMapper.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/DataStreamFieldEntityMapper.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/SourceDbBasicEntityMapper.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/SourceDbDetailEntityMapper.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/SourceFileBasicEntityMapper.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/SourceFileDetailEntityMapper.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StorageHiveEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/SourceFileDetailEntityMapper.xml
inlong-manager/manager-dao/src/test/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/BusinessService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/DataStreamService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/SourceDbService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/SourceFileService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/StorageService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/BusinessServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/DataStreamServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/StorageHiveOperation.java

Fixes #1791
Some bid fields have not been modified.

[INLONG-1791][Feature][InLong-Manager] Some bid fields have not been modified

---

inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/config/RestTemplateConfig.java
inlong-manager/manager-web/src/main/resources/application-test.properties

Modify the RestTemplate to read the configuration from the configuration file.

[INLONG-1798] RestTemplate does not read configuration from the configuration file.

---

inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/common/ConfirmResult.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/common/ConsumeResult.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/common/PeerInfo.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/common/QueryMetaResult.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/common/TClientConstants.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/config/ConsumerConfig.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/BaseMessageConsumer.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/ClientBalanceConsumer.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/factory/MessageSessionFactory.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/factory/TubeBaseSessionFactory.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/factory/TubeMultiSessionFactory.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/factory/TubeSingleSessionFactory.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/TBaseConstants.java

[INLONG-1803]Add the client interface that supports partition allocation

---

README.md

Fixes https://github.com/apache/incubator-inlong/issues/1811
*(or)*
*(or)*
*(example:)* …

[INLONG-1811] Modify the architecture diagram of README.md

---

inlong-website/public/index.html
inlong-website/src/components/FormGenerator/FormItemContent.tsx
inlong-website/src/components/HighSelect/index.tsx
inlong-website/src/utils/index.ts

Fixes #1838 
*(or)*
*(or)*
*(example:)* …

[INLONG-1838] Public components perfect for use in pulsar

---

inlong-website/src/components/AccessHelper/FieldsConfig/businessFields.tsx
inlong-website/src/components/AccessHelper/FieldsConfig/dataFields.tsx
inlong-website/src/pages/AccessCreate/Business/config.tsx
inlong-website/src/pages/AccessCreate/Business/index.tsx
inlong-website/src/pages/AccessCreate/DataStream/config.tsx
inlong-website/src/pages/AccessCreate/DataStream/helper.ts
inlong-website/src/pages/AccessCreate/DataStream/index.tsx
inlong-website/src/pages/AccessCreate/index.tsx
inlong-website/src/pages/AccessDashboard/ExecutionLogModal.tsx
inlong-website/src/pages/AccessDetail/DataStream/StreamItemModal.tsx
inlong-website/src/pages/AccessDetail/DataStream/config.tsx
inlong-website/src/pages/AccessDetail/DataStream/index.tsx
inlong-website/src/pages/AccessDetail/Info/config.tsx
inlong-website/src/pages/AccessDetail/Info/index.tsx
inlong-website/src/pages/AccessDetail/common.d.ts
inlong-website/src/pages/AccessDetail/index.tsx

Fixes #1834 
*(or)*
*(or)*
*(example:)* …

[INLONG-1834] Access support pulsar

---

inlong-website/src/components/ConsumeHelper/BusinessSelect/MyBusinessModal.tsx
inlong-website/src/components/ConsumeHelper/BusinessSelect/index.tsx
inlong-website/src/components/ConsumeHelper/FieldsConfig/basicFields.tsx
inlong-website/src/pages/ConsumeCreate/Info/config.tsx
inlong-website/src/pages/ConsumeCreate/Info/index.tsx
inlong-website/src/pages/ConsumeDetail/Info/config.tsx
inlong-website/src/pages/ConsumeDetail/Info/index.tsx

Fixes #1835 
*(or)*
*(or)*
*(example:)* …

[INLONG-1835] Consume support pulsar

---

inlong-tubemq/pom.xml
inlong-tubemq/tubemq-server/pom.xml
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/TMaster.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/balance/DefaultLoadBalancer.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metrics/MasterMetric.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/BrokerAbnHolder.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/DefBrokerRunManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodeconsumer/ConsumeGroupInfo.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodeconsumer/ConsumerEventManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodeconsumer/ConsumerInfoHolder.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodeproducer/ProducerInfoHolder.java
inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/master/MasterMetricsTest.java
inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/master/nodemanage/nodeconsumer/ConsumerEventManagerTest.java

[INLONG-1852] The Master of TubeMQ supports monitoring indicators with JMX

---

inlong-tubemq/conf/master.ini

Fixes #1863 
exposed repHelperHost configuration for master
no doc need

[INLONG-1863] [TubeMQ] exposed repHelperHost configuration for master

---

inlong-website/src/pages/ConsumeCreate/Info/index.tsx

… of the new consumption
Fixes #1898 
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? (not applicable …

[INLONG-1898] The error of the incharges for the second edit

---

inlong-website/src/components/FormGenerator/FormGenerator.tsx

Fixes #1897 
*(or)*
*(or)*
*(example:)* …

[INLONG-1897] form cannot use chain name

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Constants.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/sink/DorisSinkInfo.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/Entrance.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/doris/DorisMultiSinkFunction.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/doris/DorisSinkFunction.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/doris/DorisSinkOptions.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/doris/DorisSinkOptionsBuilder.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/doris/load/BeInfoResponse.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/doris/load/DorisBeInfoResponse.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/doris/load/DorisConnectParam.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/doris/load/DorisHttpUtils.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/doris/load/DorisRespond.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/doris/load/DorisRespondMsg.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/doris/load/DorisRowConverter.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/doris/load/DorisStreamLoad.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/doris/output/DorisOutputFormat.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/flink/doris/TestDorisSink.java

Fixes #1821 
add sort support doris sink 
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? ( docs ) …

[INLONG-810] Sort Module Support store data to ApacheDoris 

---

inlong-website/src/pages/AccessCreate/Business/config.tsx
inlong-website/src/pages/AccessCreate/index.tsx

Fixes #1902 
*(or)*
*(or)*
*(example:)* …

[INLONG-1902] Access create params error

---

inlong-audit/audit-store/conf/application.properties
inlong-audit/audit-store/conf/logback.xml
inlong-audit/audit-store/conf/server.properties
inlong-audit/audit-store/sql/audit.sql
inlong-audit/audit-store/src/main/java/org/apache/inlong/store/Application.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/store/config/DataServerConfig.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/store/config/PulsarConfig.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/store/db/DruidConfig.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/store/db/DruidDataSourceProperties.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/store/db/dao/AuditDataDao.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/store/db/entities/AuditDataPo.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/store/service/AuditMsgConsumerServer.java
inlong-audit/audit-store/src/main/resources/mapper/AuditDataDao.xml
inlong-audit/audit-store/src/test/java/org/apache/inlong/store/service/AuditStoreTest.java

Fixes #1882
dd audit-store module

[INLONG][feature][audit] add audit-store module

---

inlong-audit/audit-source/conf/audit.conf
inlong-audit/audit-source/conf/pulsar.properties
inlong-audit/audit-source/pom.xml
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/base/HighPriorityThreadFactory.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/base/NamedThreadFactory.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/channel/FailoverChannelSelector.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/node/Application.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/sink/EventStat.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/sink/PulsarSink.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/sink/pulsar/CreatePulsarClientCallBack.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/sink/pulsar/PulsarClientService.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/sink/pulsar/SendMessageCallBack.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/source/DefaultServiceDecoder.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/source/ServerMessageFactory.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/source/ServerMessageHandler.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/source/ServiceDecoder.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/source/SimpleTcpSource.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/utils/FailoverChannelProcessorHolder.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/utils/LogCounter.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/utils/NetworkUtils.java
inlong-audit/audit-source/src/test/java/org/apache/inlong/audit/sink/PulsarSinkTest.java

add audit-source module
Fixes #1881

[INLONG][feature][audit] add audit-source module

---

inlong-tubemq/conf/master.ini

[INLONG-1915][Bug] tubemq master can not start

---

inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/MessagePullSetConsumerExample.java

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*

[INLONG-1920]Failed to start up MultiSession factory by following the demo code

---

inlong-dataproxy/README.md
inlong-dataproxy/conf/flume-mulit-pulsar-demo.conf

add multi-pulsar cluster config demo config
Fixes #1938

[INLONG-1938][DataProxy] add multi-pulsar cluster config demo

---

inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/Entrance.java

* Supports Pulsar source in Sort entrance
* Enable Pulsar source in `Entrance` of Sort module
- If yes, how is the feature documented? not applicable
- If a feature is not applicable for documentation, explain why? it's a trivial fixing

[INLONG-1954][Sort] Sort module supports pulsar source

---

inlong-dataproxy/dataproxy-source/pom.xml
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/federation/PulsarProducerCluster.java
inlong-dataproxy/pom.xml
inlong-sort-standalone/pom.xml
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarFederationSink.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarFederationSinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarFederationWorker.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarProducerCluster.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarProducerFederation.java

Fixes #1893 
*(or)*
*(or)*
*(example:)* …

[INLONG-1893] Inlong-Sort-Standalone support to sort the events to Pulsar clusters.

---

inlong-website/src/components/AccessHelper/FieldsConfig/businessFields.tsx
inlong-website/src/components/MetaData/StorageHive.tsx

Fixes #1955 
*(or)*
*(or)*
*(example:)* …

[INLONG-1955] Do not set the disabled of the hive field

---

inlong-manager/manager-dao/src/test/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql
inlong-manager/manager-web/src/test/resources/sql/apache_inlong_manager.sql

This reverts commit 04aafa3e5331d6e09fddc813702a9a3c4e56c123.
Fixes #<xyz>
*(or)*
*(or)*
*(example:)* …

Revert "[INLONG-1967][Bug][InLong-Manager] Cannot create the Pulsar subscription

---

inlong-manager/manager-dao/src/main/resources/mappers/BusinessPulsarEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/DataStreamServiceImpl.java

[INLONG-1975][Bug]error occurs when deleting a data access

---

inlong-dataproxy/conf/flume-mulit-pulsar-demo.conf

Fixes #1973
modify demo config class package

[INLONG-1973][Bug][InLong-Manager] modify demo config class package

---

CHANGES.md

[INLONG-1943] Add 0.12.0 version release modification to CHANGES

---

inlong-agent/agent-common/pom.xml
inlong-agent/agent-plugins/pom.xml
inlong-agent/agent-release/assembly.xml
inlong-agent/agent-release/pom.xml
inlong-agent/pom.xml
inlong-audit/audit-common/pom.xml
inlong-audit/audit-dist/assembly/assembly.xml
inlong-audit/audit-dist/pom.xml
inlong-audit/audit-docker/pom.xml
inlong-audit/audit-source/assembly/assembly.xml
inlong-audit/audit-source/pom.xml
inlong-audit/audit-store/assembly/assembly.xml
inlong-audit/audit-store/pom.xml
inlong-audit/pom.xml
inlong-dataproxy/dataproxy-dist/pom.xml
inlong-dataproxy/dataproxy-dist/src/main/assembly/assembly.xml
inlong-distribution/distribution.xml
inlong-manager/manager-web/assembly.xml
inlong-manager/manager-web/pom.xml
inlong-sdk/pom.xml
inlong-sort-standalone/sort-standalone-dist/pom.xml
inlong-sort-standalone/sort-standalone-dist/src/main/assembly/assembly.xml
inlong-tubemq/tubemq-client/pom.xml
inlong-tubemq/tubemq-client/src/main/assembly/assembly.xml
inlong-tubemq/tubemq-example/pom.xml
inlong-tubemq/tubemq-example/src/main/assembly/assembly.xml
inlong-tubemq/tubemq-manager/pom.xml
inlong-tubemq/tubemq-manager/src/main/assembly/assembly.xml
inlong-tubemq/tubemq-server/pom.xml
inlong-tubemq/tubemq-server/src/main/assembly/assembly.xml

[INLONG-1981][Bug] When compiling the project, the InLong-audit module reported Warning errors

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/BusinessServiceImpl.java

[INLONG-1984][Bug][InLong-Manager] Create pulsar access, modify pulsar related parameters failed

---

inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/config/TubeClientConfig.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/config/TubeClientConfigUtils.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/ClientSubInfo.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/MessageConsumer.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/MessageFetchManager.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/RmtDataCache.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/Message.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/policies/FlowCtrlItem.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/policies/FlowCtrlRuleHandler.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/utils/AddressUtils.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/utils/OpsSyncInfo.java
inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/broker/metadata/BrokerMetadataManagerTest.java
inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/broker/utils/DataStoreUtilsTest.java

[INLONG-1987][Improve] Add function comment information in TubeMQ

---

inlong-audit/audit-sdk/pom.xml
inlong-audit/audit-sdk/src/test/java/org/apache/inlong/audit/send/SenderChannelTest.java

fix Compile Audit-SDK and report TestNGException
Fixes #1995

[INLONG-1995] [Bug] Compile Audit-SDK and report TestNGException

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/BusinessProcessOperation.java

[INLONG-1984][Bug][InLong-Manager] Set Pulsar params for workflow form after submitting approval

---

inlong-dataproxy/dataproxy-dist/pom.xml
inlong-dataproxy/dataproxy-dist/src/main/assembly/assembly.xml

Fixes #1997
modify build can not create lib package error

[INLONG-1997][Bug][InLong-DataProxy] modify build can not create lib package error

---

inlong-manager/manager-dao/pom.xml
inlong-manager/pom.xml

[INLONG-1958][Bug]Avoid the security risks of log4j package(addendum)

---

inlong-manager/manager-dao/src/main/resources/mappers/DataStreamEntityMapper.xml
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/DataStreamController.java

[INLONG-1975][Bug]error occurs when deleting a data access(addendum)

---

inlong-website/src/pages/AccessCreate/Business/config.tsx
inlong-website/src/pages/AccessDetail/Info/config.tsx

Fixes #2002
*(or)*
*(or)*
*(example:)* …

[INLONG-2002] creating data access with pulsar, users should be able to change the ensemble param

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/BusinessEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/BusinessEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/BusinessServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/DataProxyClusterServiceImpl.java

[INLONG-2009][InLong-Manager] Topic obtained through "openapi/dataproxy/getConfig" is wrong

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java

[INLONG-2009][InLong-DataProxy] Topic obtained through "openapi/dataproxy/getConfig" is wrong  bug inlong-manager

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/BizConstant.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/EntityStatus.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/agent/FileAgentCommandInfo.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/SourceFileDetailEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/SourceFileDetailEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentTaskServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SourceDbServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SourceFileServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/business/listener/BusinessCompleteProcessListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/stream/StreamCompleteProcessListener.java

[INLONG-2012][InLong-Manager] Inlong-Agent could not fetch file agent task through "fileAgent/getTaskConf"

---

inlong-sort/pom.xml

* Fix bug of missing dependency of "jul-to-slf4j"
* Include all log related class in runtime jar
- If yes, how is the feature documented? not applicable
- If a feature is not applicable for documentation, explain why? it's a dependency modification

[INLONG-2020][InLong-Sort] Fix missing dependency of jul-to-slf4j

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java

Fixes #2023 
Agent stream id is not passed to proxy
Agent stream id passed to proxy

[INLONG-2023][Bug]  Agent stream id is not passed to proxy

---

inlong-sort/pom.xml
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/pulsar/PulsarUtils.java

[INLONG-2026][Bug] Found Pulsar client create failure when starting Sort

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java

Fixes #2030 
inlong-agent raises NPE error when running
pass inlong group id in proxy sender

[INLONG-2030][Bug]inlong-agent raises NPE error when running

---

inlong-sort/pom.xml

[INLONG-2032][Bug]"javax.xml.parsers.FactoryConfigurationError" throwed in flink when starting a inlong-sort job

---

.asf.yaml
README.md
inlong-manager/manager-web/src/main/resources/application-dev.properties
inlong-manager/manager-web/src/main/resources/application-prod.properties
inlong-manager/manager-web/src/main/resources/application-test.properties
inlong-manager/manager-web/src/test/resources/application-test.properties
pom.xml

Fixes #2034
*(or)*
*(or)*
*(example:)* …

[INLONG-2034] Update the definition of InLong more clearly

---

inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/flink/deserialization/MultiTenancyTDMsgMixedDeserializerTest.java
inlong-sort/sort-formats/format-tdmsg-base/src/main/java/org/apache/inlong/sort/formats/tdmsg/TDMsgUtils.java
inlong-sort/sort-formats/format-tdmsg-csv/src/main/java/org/apache/inlong/sort/formats/tdmsgcsv/TDMsgCsvUtils.java
inlong-sort/sort-formats/format-tdmsg-csv/src/test/java/org/apache/inlong/sort/formats/tdmsgcsv/TDMsgCsvFormatDeserializerTest.java

* Rename tid to streamId to match the change of other components
* Change the deserialization of message format
* Use streamId instead of tid
* This change is already covered by existing tests
- If yes, how is the feature documented? not applicable
- If a feature is not applicable for documentation, explain why? it should be documented in the whole project

[INLONG-2043][InLong-Sort] Rename tid to streamId

---

inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/tubemq/MultiTenancyTubeConsumer.java
inlong-tubemq/tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/TubemqSourceFunction.java

[INLONG-2046][Bug]inlong-sort could not identify tube master address when inlong-sort and tube-master were deployed in the same machine

---

CHANGES.md

[INLONG-1943] Add 0.12.0 version release modification to CHANGES(addendum)

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdpart/mq/PulsarOptServiceImpl.java

Fixes #2078
*(or)*
*(or)*
*(example:)* …

[INLONG-2078] create partition topic for serial model

---

inlong-dataproxy/conf/flume-mulit-pulsar-demo.conf

Fixes #2070
*(or)*
*(or)*
*(example:)* …

[INLONG-2070] update the default pulsar demo configuration for dataproxy

---

inlong-agent/pom.xml

[INLONG-2073][Improve] remove spring 2.5.6 from dependencyManagement

---

inlong-agent/conf/agent.properties
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java

Fixes #2082
*(or)*
*(or)*
*(example:)* …

[INLONG-2082] add GET method for getIpList

---

inlong-tubemq/tubemq-client-twins/tubemq-client-go/README.md
inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/consumer.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/version.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/example/consumer.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/example/multi_routine_consumer.go

Fixes #2084 
README and Confirm API is a little misleading.
Update Confirm API and README of Go SDK
*(or)*
*(or)*
*(example:)*
- Does this …

[INLONG-2084][Bug]A bug in the Go SDK demo, and the API result class is not clear enough

---

inlong-tubemq/tubemq-docker/tubemq-all/README.md

[INLONG-2087][Bug] Miss a "-p" flag before 2181:2181 in the command "Start Standalone Container"

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/metrics/SourcePrometheusMetrics.java

Fixes: #2094
Make agent source prometheus metrics static.
- `agent/plugin/metrics/SourcePrometheusMetrics.java`

[INLONG-2094][Agent][Bug] Fix registration bug of prometheus metric when submitting a job

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/improve-request.yml
inlong-agent/bin/agent-env.sh
inlong-agent/bin/agent.sh
inlong-agent/conf/agent.properties

Fixes #2098
*(or)*
*(or)*
*(example:)* …

[INLONG-2098] optimize the script and template

---

.asf.yaml
README.md
pom.xml

Fixes #2103
`integration framework` is more accurate for InLong
*(or)*
*(or)*
*(example:)* …

[INLONG-2103] update the definition of Apache InLong

---

inlong-tubemq/tubemq-docker/tubemq-build/Dockerfile
inlong-tubemq/tubemq-docker/tubemq-cpp/Dockerfile

Fixes #2097
*(or)*
*(or)*
*(example:)* …

[INLONG-2097][Agent] change wget command

---

inlong-manager/manager-common/pom.xml
inlong-manager/pom.xml

[INLONG-2107][Manager] remove gson and json-simple from dependency

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/dtos/TaskRequestDto.java

Fixes #2117 
*(or)*
*(or)*
*(example:)* …

[INLONG-2117][agent] optimize class name #2117

---

inlong-sdk/sort-sdk/pom.xml
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/MetricReporter.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClientConfig.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/MetricReporterImpl.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/SortClientImpl.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/metrics/SortSdkMetricItem.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/metrics/SortSdkPrometheusMetricListener.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/stat/SortClientStateCounter.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/stat/StatManager.java

Fixes #2045
*(or)*
*(or)*
*(example:)* …

[INLONG-2045] sort-sdk support Prometheus metrics

---

.asf.yaml

Fixes #2122
*(or)*
*(or)*
*(example:)* …

[INLONG-2122] Send a dev notifications email for issue status

---

NOTICE

[INLONG-2133] Update year to 2022

---

inlong-website/README.md

Fixes #2116
*(or)*
*(or)*
*(example:)* …

[INLONG-2116] Improve the Website README document

---

inlong-sort/pom.xml
inlong-sort/sort-core/pom.xml
inlong-sort/sort-formats/pom.xml

Fixes #2130
*(or)*
*(or)*
*(example:)* …

[INLONG-2130][sort] add objenesis dependency

---

inlong-manager/pom.xml

Fixes #2124
*(or)*
*(or)*
*(example:)* …

[INLONG-2124][manager] update jackson-databind 2.9.10.8 to 2.12.0

---

inlong-dataproxy/bin/dataproxy-stop.sh
inlong-dataproxy/bin/flume-ng

Fixes #2139
*(or)*
*(or)*
*(example:)* …

[INLONG-2139][dataproxy] optimze the stop script

---

inlong-sort/pom.xml
inlong-sort/sort-core/pom.xml

Fixes #2143
*(or)*
*(or)*
*(example:)* …

[INLONG-2143][sort] change pulsar dependency

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/tools/cli/CliConsumer.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/tools/cli/CliProducer.java

[INLONG-2151][Improve] Add time and sort statistics by topic

---

inlong-manager/manager-dao/src/test/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql
inlong-manager/manager-web/src/test/resources/sql/apache_inlong_manager.sql

Fixes #2155 
Some unit tests running failed in the InLong-Manager module.
Update unit test SQL file.

[INLONG-2155][Manager] Fix unit tests error for Manager module

---

pom.xml

Fixes #2137
*(or)*
*(or)*
*(example:)* …

[INLONG-2137][inlong-sdk] restore inlong sdk module in pom.xml

---

inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/clickhouse/partitioner/HashPartitioner.java

Fixes #2171 
*(or)*
*(or)*
*(example:)* …

[INLONG-2171] Fix the problem that partition computed is negative when using distributed table of clickhouse

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/plugin/Reader.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/plugin/Sink.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/conf/ConfigJetty.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/Job.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskPositionManager.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/task/TestTaskWrapper.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ConsoleSink.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/PulsarSink.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/DataBaseSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/SqlReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/TextFileReader.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/filter/TestStreamIdFilter.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/MockSink.java

Fixes #2167 
Agent should support db SQL collect
User can submit a SQL job to read result set from db
Agent should support db SQL collect
User can submit a SQL job to read result set from db
- If yes, how is the feature documented? (docs)

[INLONG-2167][Feature] [Agent] support db SQL collect

---

inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/clickhouse/executor/ClickHouseAppendExecutor.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/clickhouse/executor/ClickHouseUpsertExecutor.java

Fixes #2174 
*(or)*
*(or)*
*(example:)* …

[INLONG-2174] Make the flush operation synchronized in clickhouse sink to prevent data loss

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/JobProfileDb.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/Job.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobWrapper.java
inlong-agent/agent-plugins/pom.xml
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/DataBaseSource.java

Fixes #2179 
add mysql connector
add mysql connector

[INLONG-2179][Feature] [Agent] support db SQL collect - add mysql connector

---

inlong-sort/pom.xml
inlong-sort/sort-core/pom.xml
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/hive/HiveMultiTenantCommitter.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/hive/HiveWriter.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/multitenant/MultiTenantFunctionInitializationContext.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/transformation/RecordTransformer.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/flink/pulsar/MultiTopicPulsarSourceFunctionTest.java

Fixes #2183 
*(or)*
*(or)*
*(example:)* …

[INLONG-2183][Feature][InLong-Sort] Bump flink version to 1.13.5 (#2183)

---

inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/source/ServerMessageHandler.java

fix requestId is not set in response message
Fixes # 2191

[INLONG-2191][AuditSource] fix requestId is not set in response message

---

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditImp.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderGroup.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderManager.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/util/AuditConfig.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/util/AuditData.java
inlong-audit/audit-sdk/src/test/java/org/apache/inlong/audit/send/SenderGroupTest.java
inlong-audit/audit-sdk/src/test/java/org/apache/inlong/audit/send/SenderManagerTest.java

audit-sdk add disaster recovery
Fixes #2054

[INLONG-2054][feature][audit] audit-sdk add disaster recovery

---

inlong-dashboard/src/pages/AccessDetail/Audit/config.tsx
inlong-dashboard/src/pages/AccessDetail/Audit/index.tsx
inlong-dashboard/src/pages/AccessDetail/index.tsx

Fixes #2187
*(or)*
*(or)*
*(example:)* …

[INLONG-2187] support audit view

---

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditImp.java

audit-sdk support real-time report
Fixes #2055

[INLONG-2055][feature][audit] audit-sdk support real-time report

---

inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/consts/ConfigConstants.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/channel/FailoverChannelProcessor.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/sink/PulsarSink.java
inlong-audit/audit-source/src/main/java/org/apache/inlong/audit/source/SimpleTcpSource.java

Fix one message will put tow channel, and store two message issue
Fixes #2199

[INLONG-2199][AuditSource] one message will put tow channel, and store two message

---

inlong-sdk/dataproxy-sdk/pom.xml
pom.xml

Fixes #2227
*(or)*
*(or)*
*(example:)* …

[INLONG-2227] fix the build issue for dataproxy-sdk

---

inlong-audit/audit-store/pom.xml
inlong-audit/pom.xml

fix can not started by start shell 
Fixes #2190

[INLONG-2190][inlong-audit][audit-store] fix can not started by start shell 

---

inlong-dashboard/src/pages/AccessDetail/Audit/config.tsx

Fixes #2233
*(or)*
*(or)*
*(example:)* …

[INLONG-2233][dashboard] get audit id error

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/audit/AuditRequest.java

fix call query audit interface error
Fixes #2237 
*(or)*
*(or)*
*(example:)*
- If a …

[INLONG-2237] fix call query audit interface error

---

inlong-manager/pom.xml

Fixes #2201
*(or)*
*(or)*
*(example:)* …

[INLONG-2230] add jackson-core dependency

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerConfig.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerServiceServer.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/TubeBroker.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/metadata/BrokerMetadataManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/metadata/TopicMetadata.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/MessageStoreManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/StoreService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/DefaultOffsetManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/OffsetRecordInfo.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/OffsetRecordService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/OffsetService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/RecordItem.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/TServerConstants.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/paramcheck/PBParameterUtils.java

[INLONG-2247][tubemq] Read the consume group offset and store to the specified topic

---

inlong-sort/pom.xml
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/sink/IcebergSinkInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/sink/SinkInfo.java
inlong-sort/sort-single-tenant/pom.xml
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/Entrance.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/utils/CommonUtils.java

Fixes #2236 
*(or)*
*(or)*
*(example:)* …

[INLONG-2236][Sort] Introduce iceberg sink in sort-single-tenent

---

inlong-dashboard/src/components/Charts/index.tsx
inlong-dashboard/src/pages/AccessDetail/Audit/config.tsx
inlong-dashboard/src/pages/AccessDetail/Audit/index.tsx

Fixes #2258
*(or)*
*(or)*
*(example:)* …

[INLONG-2258] Audit page support auto select datastream

---

inlong-dataproxy/conf/flume-mulit-pulsar-http-example.conf
inlong-dataproxy/conf/flume-mulit-pulsar-tcp-example.conf
inlong-dataproxy/conf/flume-mulit-pulsar-udp-example.conf
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/PulsarSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/SendMessageCallBack.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/BaseSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleTcpSource.java

fix Source receive one message will be send to pulsar twice when config both memery channel and file channel bug.
Fixes #2224

 [INLONG-2224][DataProxy] Source receive one message will be send to pulsar twice when config both memery channel and file channel

---

inlong-sort-standalone/pom.xml
inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/metrics/SortMetricItem.java
inlong-sort-standalone/sort-standalone-source/pom.xml
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/SortStandaloneApplication.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/metrics/audit/AuditUtils.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/hive/HiveSinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarProducerCluster.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSourceContext.java

Fixes #2256 
*(or)*
*(or)*
*(example:)* …

[INLONG-2256] SortStandalone support audit sdk.

---

inlong-dataproxy/dataproxy-source/pom.xml
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/DataProxyMetricItem.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/audit/AuditUtils.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/node/Application.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/MetaSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/SimpleMessageTubeSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/federation/PulsarProducerCluster.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleMessageHandler.java

Fixes #2255 
*(or)*
*(or)*
*(example:)* …

[INLONG-2255] DataProxy support audit sdk.

---

inlong-dataproxy/conf/flume-mulit-pulsar-http-example.conf
inlong-dataproxy/conf/flume-mulit-pulsar-tcp-example.conf
inlong-dataproxy/conf/flume-mulit-pulsar-udp-example.conf
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java

Inlong-DataProxy support authentication access TDMQ
Fixes #2218

[INLONG-2218][DataProxy] Inlong-DataProxy support authentication access Pulsar

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Constants.java
inlong-sort/sort-core/pom.xml
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/deserialization/DeserializationSchema.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/hive/HiveMultiTenantWriter.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/util/CommonUtils.java

Fixes #2266 
*(or)*
*(or)*
*(example:)* …

[INLONG-2266][Feature]Support reporting metrics by audit-sdk in sort

---

inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/deserialization/DeserializationSchema.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/hive/HiveMultiTenantWriter.java

Fixes #2288 
*(or)*
*(or)*
*(example:)* …

[INLONG-2288] Fix the problem that sort-flink task catches an NPE

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/TubeBroker.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/action/screen/config/BrokerList.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/tools/cli/CliAbstractBase.java
inlong-tubemq/tubemq-server/src/saveServerVersion.cmd
inlong-tubemq/tubemq-server/src/saveServerVersion.sh

[INLONG-2294]Rename the variable BROKER_VERSION to SERVER_VERSION

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/DefaultOffsetManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/TServerConstants.java

[INLONG-2296] Added lag consumption log

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/web/BrokerAdminServlet.java

Fixes #2294
Added Broker's HTTP API for external viewing of Broker's version information

[INLONG-2294]Rename the variable BROKER_VERSION to SERVER_VERSION (addenum)

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerServiceServer.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/web/BrokerAdminServlet.java

[INLONG-2320][Bug][TubeMQ]Out of bounds error when saving the historical offset

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerServiceServer.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/web/BrokerAdminServlet.java

Reverts apache/incubator-inlong#2321

Revert "[INLONG-2320][Bug][TubeMQ]Out of bounds error when saving the historical offset"

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/demo/UdpClientDemo.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/Event.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/MyFileCallBack.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/MyMessageCallBack.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/SendMsgThread.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/UdpClientExample.java

Add http protocol client example
Fixes #2216

[INLONG-2216][DataProxy-sdk] Add udp protocol client example

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/Event.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/MyFileCallBack.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/MyMessageCallBack.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/SendMsgThread.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/TcpClientExample.java

Add TCP protocol client demo
Fixes #2217

[INLONG-2217][DataProxy-sdk] Add TCP protocol client example

---

inlong-agent/agent-common/pom.xml
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constants/AgentConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constants/CommonConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/ConfigUtil.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentMain.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentManager.java
inlong-agent/agent-plugins/pom.xml
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/PulsarSink.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/SqlReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/TextFileReader.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/TestFileAgent.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestTextFileReader.java

Fixes #2297
*(or)*
*(or)*
*(example:)* …

[INLONG-2297][agent] support audit for source and sink

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/Sender.java

asyncSendMessage in sender.java can be optimized to reduce the number of invalid objects 
Fixes #2329

[INLONG-2329][dataproxy-sdk]optimize asyncSendMessage code to reduce the number of invalid objects

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java

…shielded
Fixes #2336 
*(or)*
*(or)*
*(example:)* …

[INLONG-2336][agent] fix the bug that the manager fetcher thread was shielded

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java

create pulsar client need support config ioThreads #2334
Fixes #2334

[INLONG-2334][inlong-dataproxy] create pulsar client need support config ioThreads

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java

'.inlong' as default path of local file is ambiguous
Fixes #2341

[INLONG-2341][inlong-dataproxy-sdk]'.inlong' as default path of local file is ambiguous

---

inlong-dataproxy/conf/log4j.properties

modify dataproxy log name
Fixes #2349

[INLONG-2349][inlong-dataproxy ]modify dataproxy log name

---

inlong-agent/agent-docker/Dockerfile
inlong-agent/agent-docker/agent-docker.sh
inlong-manager/manager-web/sql/apache_inlong_manager.sql

Fixes #2338
*(or)*
*(or)*
*(example:)* …

[INLONG-2338] add default dataproxy address

---

inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/clickhouse/ClickHouseSinkFunction.java
inlong-sort/sort-single-tenant/pom.xml
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/Entrance.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/clickhouse/ClickhouseRowSinkFunction.java

Fixes #2333 
*(or)*
*(or)*
*(example:)* …

[INLONG-2333] Support clickhouse sink in sort-single-tenant

---

inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/HiveCommitter.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/HiveWriter.java
inlong-sort/sort-single-tenant/pom.xml
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/Entrance.java

Fixes #2347 
*(or)*
*(or)*
*(example:)* …

[INLONG-2347] Support hive sink in sort-single-tenant

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/PulsarSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java

monitorIndex should not use msgid for key,it affects performance
Fixes #2371

[INLONG-2371][Bug][InLong-Dataproxy] monitorIndex should not use msgid for key,it affects performance

---

CHANGES.md

Fixes #2390
*(or)*
*(or)*
*(example:)* …

[INLONG-2390] Update changes for 1.0.0

---

CHANGES.md

Fixes #2393 
*(or)*
*(or)*
*(example:)* …

[INLONG-2393] fix the typo for changes file

---

inlong-manager/manager-plugin-examples/pom.xml
inlong-manager/pom.xml

[INLONG-2396][Manager] Add manager-plugin-examples as a sub-module of inlong-manager

---

inlong-sort/sort-single-tenant/pom.xml
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/kafka/KafkaSinkTestBase.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/kafka/RowToJsonKafkaSinkTest.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/kafka/RowToStringKafkaSinkTest.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/utils/NetUtils.java

Fixes #2401 
*(or)*
*(or)*
*(example:)* …

[INLONG-2401][Bug][InLong-Sort] Fix bugs in kafka sink unit tests

---

inlong-manager/pom.xml

Fixes #2406 
libs that have no public security vulnerabilities
pom
*(or)*
*(or)*
*(example:)* …

[INLONG-2406][Manager] Upgrade Shiro version due to the security vulnerabilities

---

inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/TubeMQResult.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/cluster/ClusterController.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/cluster/request/AddClusterReq.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/ClusterServiceImpl.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/MasterServiceImpl.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/interfaces/MasterService.java
inlong-tubemq/tubemq-manager/src/test/java/org/apache/inlong/tubemq/manager/controller/TestClusterController.java

Fixes https://github.com/apache/incubator-inlong/issues/2353
*(or)*
*(or)*
*(example:)* …

[INLONG-2353] Tube manager cluster adds support for multi-master configuration

---

.github/ISSUE_TEMPLATE/bug-report.yml

Fixes #2409
*(or)*
*(or)*
*(example:)* …

[INLONG-2409] add 1.0.0 version option for the bug report

---

inlong-manager/pom.xml

Fixes #2406
fix issue where one dependency wasn't updated in 1st PR
pom change
*(or)*
*(or)*
*(example:)* …

[INLONG-2406] [Manager] fix issue with shiro version

---

inlong-agent/pom.xml
inlong-manager/pom.xml
inlong-sdk/dataproxy-sdk/pom.xml
inlong-tubemq/pom.xml
licenses/inlong-dataproxy/LICENSE-binary
licenses/inlong-tubemq/LICENSE-binary

Fixes #2417 
using secure libs
pom changes
*(or)*
*(or)*
*(example:)* …

[INLONG-2417] update commons-io and commons-collections due to security issues

---

inlong-audit/pom.xml
inlong-manager/pom.xml

Fixes #2425
secure libs
pom changes
*(or)*
*(or)*
*(example:)*

[INLONG-2425] upgrade elasticsearch jars

---

.asf.yaml
README.md
pom.xml

Fixes #2437
*(or)*
*(or)*
*(example:)* …

[INLONG-2437] highlight the massive data scenario for the brief introduction of InLong

---

inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/SimpleClientBalanceConsumer.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/Counter.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/Counting.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/Gauge.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/Histogram.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/Metric.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/MetricSet.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodeproducer/ProducerInfoHolder.java

[INLONG-2433][TubeMQ] Abstract metrics' interface

---

inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/impl/BaseMetric.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/impl/LongMaxGauge.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/impl/LongMinGauge.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/impl/LongOnlineCounter.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/impl/LongStatsCounter.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/impl/SinceTime.java
inlong-tubemq/tubemq-core/src/test/java/org/apache/inlong/tubemq/corebase/metric/SimpleMetricTest.java

[INLONG-2445][TubeMQ] Add Gauge and Counter implementation classes

---

inlong-agent/agent-plugins/pom.xml
inlong-manager/manager-plugin-examples/pom.xml
inlong-sdk/dataproxy-sdk/pom.xml
inlong-sdk/sdk-common/pom.xml
inlong-sdk/sort-sdk/pom.xml
inlong-sort-standalone/pom.xml
inlong-sort-standalone/sort-standalone-common/pom.xml
inlong-sort-standalone/sort-standalone-dist/pom.xml
inlong-sort-standalone/sort-standalone-source/pom.xml

Fixes #2455
*(or)*
*(or)*
*(example:)* …

[INLONG-2455] unify the module name for sort and manager

---

inlong-agent/pom.xml

Fixes #2462
use secure lib
pom change
*(or)*
*(or)*
*(example:)* …

[INLONG-2462] [AGENT] upgrade aviator

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Constants.java
inlong-sort/sort-connectors/pom.xml
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/HiveSinkHelper.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/formats/orc/OrcBulkWriter.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/formats/orc/OrcBulkWriterFactory.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/formats/orc/OrcBulkWriterUtil.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/formats/orc/PhysicalWriterImpl.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/formats/orc/RowVectorizer.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/formats/parquet/ParquetRowWriter.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/formats/parquet/ParquetRowWriterBuilder.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/formats/parquet/ParquetSchemaConverter.java
inlong-sort/sort-connectors/src/test/java/org/apache/inlong/sort/flink/hive/formats/orc/OrcBulkWriterTest.java

Fixes #2354
*(or)*
*(or)*
*(example:)* …

[INLONG-2354][Sort] Support orc format in hive sink

---

.github/workflows/ci_build.yml
.github/workflows/ci_build_docker.yml
.github/workflows/ci_ut.yml

Fixes #2458
*(or)*
*(or)*
*(example:)* …

[INLONG-2458] update the CI/CD workflows

---

inlong-sort/pom.xml
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/sink/HiveSinkInfo.java
inlong-sort/sort-single-tenant/pom.xml
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/Entrance.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/hive/HiveSinkWithoutPartitionTestCase.java

Fixes #2413
*(or)*
*(or)*
*(example:)* …

[INLONG-2413][Sort]Support non-partitioned table when using hive sink

---

inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/impl/ESTHistogram.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/impl/SimpleHistogram.java
inlong-tubemq/tubemq-core/src/test/java/org/apache/inlong/tubemq/corebase/metric/HistogramTest.java

[INLONG-2451][TubeMQ] Add Histogram implementation classes

---

inlong-agent/agent-plugins/pom.xml
inlong-agent/pom.xml

Fixes #2464
*(or)*
*(or)*
*(example:)* …

[INLONG-2464] remove the useless aviator dependency

---

inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/impl/ESTHistogram.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/impl/SinceTime.java
inlong-tubemq/tubemq-core/src/test/java/org/apache/inlong/tubemq/corebase/metric/HistogramTest.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerServiceServer.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/TubeBroker.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/disk/FileSegment.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/disk/MsgFileStore.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/mem/MsgMemStore.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/DefaultOffsetManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/stats/ServiceStatsHolder.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/offsetstorage/ZkOffsetStorage.java
inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/broker/stats/ServiceStatsHolderTest.java

[INLONG-2474][TubeMQ] Adjust the statistics of Broker's message service part

---

inlong-dashboard/package-lock.json

Fixes #2461
*(or)*
*(or)*
*(example:)* …

[INLONG-2461] Use npm audit fix to resolve some vulnerabilities

---

inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/formats/parquet/ParquetRowWriter.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/formats/parquet/ParquetSchemaConverter.java
inlong-sort/sort-connectors/src/test/java/org/apache/inlong/sort/flink/hive/formats/parquet/ParquetBulkWriterTest.java

Fixes #2403 
*(or)*
*(or)*
*(example:)* …

[INLONG-2403][Sort] Fix the problem that Parquet format doen't work

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/stats/ServiceStatsHolder.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/web/AbstractWebHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/TServerConstants.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/webbase/WebCallStatsHolder.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/action/screen/Webapi.java
inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/common/WebCallStatsHolderTest.java

[INLONG-2480][TubeMQ] Add WebCallStatsHolder class for Web API call statistics

---

.github/workflows/ci_check_license.yml

Fixes #2498
*(or)*
*(or)*
*(example:)* …

[INLONG-2498] fix the bug for the skywalking-eyes/license-eye check failed

---

inlong-dashboard/src/components/AccessHelper/DataStorageEditor/DetailModal.tsx
inlong-dashboard/src/components/MetaData/StorageClickhouse.tsx
inlong-dashboard/src/components/MetaData/StorageHive.tsx

Fixes #2500 
Adapt to Manager's modification of data storage.

[INLONG-2500][Dashboard] Adapt to Manager's modification of data storage

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/stats/BrokerStatsType.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/web/BrokerAdminServlet.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/TServerConstants.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/fielddef/WebFieldDef.java

[INLONG-2508][TubeMQ] Add Broker metric operation APIs

---

inlong-manager/manager-dao/src/main/resources/mappers/StorageFieldEntityMapper.xml

Fixes #2507
*(or)*
*(or)*
*(example:)* …

[INLONG-2507][Bug][Manager] Init sort config failed

---

inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/Application.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/config/DataServerConfig.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/config/ElasticsearchConfig.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/config/PulsarConfig.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/config/StoreConfig.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/db/DruidConfig.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/db/DruidDataSourceProperties.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/db/dao/AuditDataDao.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/db/entities/AuditDataPo.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/db/entities/ESDataPo.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/ElasticsearchService.java
inlong-audit/audit-store/src/main/resources/mapper/AuditDataDao.xml
inlong-audit/audit-store/src/test/java/org/apache/inlong/audit/service/AuditStoreTest.java
inlong-audit/audit-store/src/test/java/org/apache/inlong/audit/service/ElasticsearchServiceTest.java
inlong-audit/audit-store/src/test/resources/application.properties
inlong-audit/audit-store/src/test/resources/mapper/AuditDataDao.xml
inlong-audit/conf/application.properties
inlong-audit/conf/mapper/AuditDataDao.xml

Modify audit-store package name according to specification
Fixes #2523
*(or)*
*(or)*
*(example:)* …

[INLONG-2523][Improve][Audit] Modify package name according to specification

---

inlong-dashboard/src/pages/AccessDetail/Audit/config.tsx

Fixes #2535 
*(or)*
*(or)*
*(example:)* …

[INLONG-2535][Dashboard] Audit module display time in reverse order

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/MessageStore.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/mem/MsgMemStore.java
inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/broker/msgstore/mem/MsgMemStoreTest.java

[INLONG-2538][TubeMQ] Optimize message write cache logic

---

inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/node/request/CloneTopicReq.java

Fixes #2521
*(or)*
*(or)*
*(example:)* …

[INLONG-2521][Tube] Solve the problem of multiple clusterId JSON fields in clone topic

---

inlong-audit/audit-common/src/main/proto/AuditApi.proto
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderManager.java

update audit protobuf field type
Fixes :#2549

[INLONG-2549] [Audit] update audit protobuf field type

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/web/BrokerAdminServlet.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/TServerConstants.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebOtherInfoHandler.java

Fixes #2552
1. Added metric data query API for Master service status and Web API calls
2. Add the master's start and stop API for the statistics function to avoid affecting the main service when the load is too high.
3. Added version information query API of Master

[INLONG-2552][TubeMQ] Add Master metric operation APIs

---

inlong-tubemq/pom.xml
inlong-tubemq/tubemq-core/pom.xml
licenses/inlong-tubemq/LICENSE-binary

[INLONG-2555][TubeMQ] Remove slf4j-log4j12

---

inlong-distribution/distribution.xml

Fixes #2561 
Update deploy settings of InLong-Sort
*(or)*
*(or)*
*(example:)* …

[INLONG-2561][Sort] Update deploy settings of InLong-Sort

---

inlong-agent/pom.xml
inlong-audit/pom.xml
inlong-manager/manager-common/pom.xml
inlong-manager/manager-workflow-engine/pom.xml
inlong-manager/pom.xml
inlong-tubemq/pom.xml
inlong-tubemq/tubemq-manager/pom.xml
pom.xml

Fixes #2548 
*(or)*
*(or)*
*(example:)* …

[INLONG-2548][Agent,Manager,Tubemq,Audit] update the version of lombok to 1.18.22

---

inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/utils/MixedUtils.java

[INLONG-2569][TubeMQ] Discarded msgTime value when msgType is empty

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/BizConstant.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/datastorage/kafka/KafkaStorageDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/datastorage/kafka/KafkaStorageListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/datastorage/kafka/KafkaStorageRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/datastorage/kafka/KafkaStorageResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/storage/kafka/KafkaStorageOperation.java
inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/service/core/KafkaStorageServiceTest.java

Fixes #2562
* InLong Manager support data flow to kafka
*(or)*
*(or)*
*(example:)* …

[INLONG-2562] [Manager] Support data flow to Kafka

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/BizConstant.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/datastorage/iceberg/IcebergStorageDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/datastorage/iceberg/IcebergStorageListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/datastorage/iceberg/IcebergStorageRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/datastorage/iceberg/IcebergStorageResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/storage/iceberg/IcebergStorageOperation.java
inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/service/core/IcebergStorageServiceTest.java

Fixes #1714
link to subtask #1520
support iceberg dataflow
manager add iceberg data storage

[INLONG-1520][Manager] Support Iceberg dataflow

---

inlong-audit/bin/store-start.sh
inlong-audit/bin/store-stop.sh

Fixes #2591
stop command will stop all audit processes.

[INLONG-2591][Audit] Fix the wrong option for script

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/ClusterInfoService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ClusterInfoServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/ClusterController.java

Fixes #2588
*Adding some method to support cluster management.*
None.

[INLONG-2588][Manager] Support cluster management

---

inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/formats/orc/RowVectorizer.java
inlong-sort/sort-connectors/src/test/java/org/apache/inlong/sort/flink/hive/formats/orc/RowVectorizerTest.java

Fixes #2554 
Support array and map data structures in ORC writer

[INLONG-2554][Sort] Support array and map data structures in ORC writer

---

docker/kubernetes/templates/_helpers.tpl
docker/kubernetes/templates/audit-configmap.yaml
docker/kubernetes/templates/audit-service.yaml
docker/kubernetes/templates/audit-statefulset.yaml
docker/kubernetes/templates/pulsar-pvc.yaml
docker/kubernetes/templates/pulsar-service.yaml
docker/kubernetes/templates/pulsar-statefulset.yaml
docker/kubernetes/values.yaml

Fixes #2510
Add support for Audit on Kubernetes.
- `docker/kubernetes`

[INLONG-2510][Feature][Aduit][K8s] Add support for Audit on Kubernetes

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ErrorCodeEnum.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongGroupEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/WorkflowEventLogEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ConsumptionServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongGroupServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongStreamServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SourceDbServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SourceFileServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/PushHiveConfigTaskListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/GroupCancelProcessListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/GroupCompleteProcessListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/GroupFailedProcessListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/GroupPassTaskListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/GroupRejectProcessListener.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/WorkflowController.java

Fixes #2617 
Change the group status after workflow.
- Does this pull request introduces a new feature?  no

[INLONG-2617][Manager] Change the group status after the new group workflow was executed

---

docker/publish.sh

Fixes #2623
add audit image for docker publish script
add audit image for docker publish script

[INLONG-2623][audit] add audit image for docker publish script

---

docker/kubernetes/templates/_helpers.tpl
docker/kubernetes/templates/agent-statefulset.yaml
docker/kubernetes/templates/audit-statefulset.yaml
docker/kubernetes/templates/dashboard-statefulset.yaml
docker/kubernetes/templates/dataproxy-statefulset.yaml
docker/kubernetes/templates/manager-service.yaml
docker/kubernetes/templates/manager-statefulset.yaml
docker/kubernetes/templates/mysql-pvc.yaml
docker/kubernetes/templates/mysql-secret.yaml
docker/kubernetes/templates/mysql-service.yaml
docker/kubernetes/templates/mysql-statefulset.yaml
docker/kubernetes/templates/tubemq-broker-statefulset.yaml
docker/kubernetes/templates/tubemq-manager-statefulset.yaml
docker/kubernetes/templates/tubemq-master-service.yaml
docker/kubernetes/templates/tubemq-master-statefulset.yaml
docker/kubernetes/templates/zookeeper-statefulset.yaml
docker/kubernetes/values.yaml

Fixes #2643
*(or)*
*(or)*
*(example:)* …

[INLONG-2643][k8s] update the configuration for helm chart

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sort/SortSourceConfigResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/SortService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/SortController.java

Fixes #2574 
*(or)*
*(or)*
*(example:)* …

[INLONG-2574][Feature][Manager] Defined  source config response

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/definition/WorkflowTask.java

Fixes #2663 
keep fields are consistent

[INLONG-2663][Manager] Fix inconsistent fields in manager-client module

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaStreamSourceOperation.java

Fixes #2653
Supporting Kafka source in InLong Stream.
Add KafkaStreamSourceOperation implemention class.

[INLONG-2653][Manager] Support Kafka source in InLong Stream

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Constants.java
inlong-sort/sort-single-tenant/pom.xml
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/hive/filesystems/CHDFSFsFactory.java
inlong-sort/sort-single-tenant/src/main/resources/META-INF/services/org.apache.flink.core.fs.FileSystemFactory

Fixes #2634 
*(or)*
*(or)*
*(example:)* …

[INLONG-2634][Sort]Support CHDFS filesystem when using hive sink

---

inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/workflow/WorkflowServiceImplTest.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/definition/ServiceTask.java

[INLONG-2662][Manager] Fix bug to avoid reinit of service task

---

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/pulsar/InLongPulsarFetcherImpl.java
inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/InLongPulsarFetcherImplTest.java
inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/InLongTopicManagerImplTest.java

Fixes #2572 
*(or)*
*(or)*
*(example:)* …

[INLONG-2572][SDK] Fix sort-sdk unit test bug

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/sink/HiveSinkInfo.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/HiveWriter.java
inlong-sort/sort-single-tenant/pom.xml

Fixes #2642 
*(or)*
*(or)*
*(example:)* …

[INLONG-2642][Sort] Use proxy user to write hive

---

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/pulsar/InLongPulsarFetcherImpl.java
inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/InLongPulsarFetcherImplTest.java
inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/InLongTopicManagerImplTest.java
inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/decode/MessageDeserializerTest.java

[INLONG-2684][Sort] Fix OOM for sort sdk unit test

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Configuration.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Constants.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/BuiltInFieldInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/util/DefaultValueStrategy.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/deserialization/DeserializationSchema.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/deserialization/MultiTenancyDeserializer.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/deserialization/MultiTenancyInLongMsgMixedDeserializer.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/transformation/FieldMappingTransformer.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/util/CommonUtils.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/flink/transformation/FieldMappingTransformerTest.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/Entrance.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/CallbackCollector.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/DeserializationFunction.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/FieldMappingTransformer.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/deserialization/DeserializationFunctionTest.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/deserialization/FieldMappingTransformerTest.java

Fixes #2625 
Support extracting data time in deserialization

[INLONG-2625][Sort] Support extracting data time in deserialization

---

inlong-common/pom.xml
inlong-common/src/main/java/org/apache/inlong/common/reporpter/AbstractReporter.java
inlong-common/src/main/java/org/apache/inlong/common/reporpter/ResponseType.java
inlong-common/src/main/java/org/apache/inlong/common/reporpter/StreamConfigLogReporter.java
inlong-common/src/main/java/org/apache/inlong/common/reporpter/StreamMetricReporter.java
inlong-common/src/main/java/org/apache/inlong/common/reporpter/dto/StreamConfigLogInfo.java
inlong-common/src/main/java/org/apache/inlong/common/reporpter/dto/StreamMetricInfo.java
inlong-common/src/test/java/org/apache/inlong/common/metric/reporter/ReporterTest.java

add common reporter to report stream config log and stream metric 
Fixes #2703

[INLONG-2703][Common] Add common reporter to report stream config log and stream metric 

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/InlongStreamConfigLogRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/InlongStreamMetricRequest.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/StreamConfigLogEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/StreamMetricEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamConfigLogEntityMapper.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamMetricEntityMapper.java
inlong-manager/manager-dao/src/main/resources/generatorConfig.xml
inlong-manager/manager-dao/src/main/resources/mappers/StreamConfigLogEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/StreamMetricEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/StreamConfigLogService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/StreamMetricService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AbstractService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/StreamConfigLogServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/StreamMetricServiceImpl.java
inlong-manager/manager-web/sql/apache_inlong_manager.sql
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/StreamConfigLogController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/StreamMetricController.java

add metric and config log report interface 
Fixes #2682

[INLONG-2682][Manager] Add stream metric and stream config log related interface

---

inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/AgentController.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ServiceDiscoveryUtils.java

Fixes #2711 
Dataproxy-SDK gets manager IP list error.

[INLONG-2711][Manager][SDK] Dataproxy-SDK gets manager IP list error

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/plugin/Reader.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobWrapper.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/task/TestTaskWrapper.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/SqlReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/TextFileReader.java

Fixes #2686
Agent support snapshot for each task #2686
Agent support snapshot for each task #2686
Get offset from each task and join with a delimiter 

[INLONG-2686][Feature] [Agent] Agent support snapshot for each task #2686

---

inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql

Fixes #2714
Fix SQL script for creating stream_source table.
Update `apache_inlong_manager.sql` file.

[INLONG-2714][Manager] Fix SQL script for creating stream_source table

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/sink/HiveSinkInfo.java

Fixes #2721 
Fix bugs in HiveSinkInfo

[INLONG-2721][Sort] Fix bugs in HiveSinkInfo

---

inlong-dataproxy/conf/common.properties

Fixes #2701 
*(or)*
*(or)*
*(example:)* …

[INLONG-2701][DataProxy] Fix NPE in manager-web because of proxy_custer_name is null

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/SourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/SourceResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceRequest.java

Fixes #2715 
Support more parameters for the Binlog source entity.

[INLONG-2715][Manager] Support more parameters for the Binlog source entity

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AbstractService.java

[INLONG-2723][Manager] Fix batch insert entities error in AbstractService

---

inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/common/ClientStatsInfo.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/common/StatsConfig.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/common/StatsLevel.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/common/TClientConstants.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/config/TubeClientConfig.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/BaseMessageConsumer.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/FetchContext.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/SimpleClientBalanceConsumer.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/SimplePullMessageConsumer.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/SimplePushMessageConsumer.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/producer/ProducerManager.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/producer/SimpleMessageProducer.java
inlong-tubemq/tubemq-client/src/test/java/org/apache/inlong/tubemq/client/consumer/StatsConfigTest.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/TrafficStatsUnit.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/stats/BrokerSrvStatsHolder.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/stats/MsgStoreStatsHolder.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/stats/TrafficStatsService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/webbase/WebCallStatsHolder.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/stats/MasterSrvStatsHolder.java

Fixes #2728 
1. Add partition-based metrics statistics and output of the client;
2. Optimize the implemented metric logic to improve performance;
3. Fix some bugs

[INLONG-2728][TubeMQ] Optimize the content of statistical metrics

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceResponse.java

Fixes #2732 
Support more parameters for Kafka source.

[INLONG-2732][Manager] Support more parameters for Kafka source

---

inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/core/impl/WorkflowContextBuilderImpl.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/definition/ServiceTask.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/definition/UserTask.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/definition/WorkflowTask.java

Fixes #2731 
Use prototype pattern instead of singleton pattern in workflow create process
*(or)*
*(or)*
*(example:)*
- If a feature is not applicable for documentation, explain …

[INLONG-2731][Manager] Add deep clone method to service task, use prototype instead of singleton

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java

[INLONG-2743][Manager] Support getting inlong workflow error for manager-client module

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerConfig.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/MessageStore.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/disk/MsgFileStore.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/mem/MsgMemStore.java
inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/broker/msgstore/mem/MsgMemStoreTest.java

[INLONG-2620][TubeMQ] Add direct write to disk control

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/RemoteConfigJson.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/mq/CreateTubeGroupTaskListener.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java

Fixes #2751 
*(or)*
*(or)*
*(example:)* …

[INLONG-2751][Manager] Fix the response code while query failing

---

.github/workflows/ci_build_docker.yml
docker/publish.sh

fix: #2772
Fix the docker image publish error.
- `.github/workflows/ci_build_docker.yml`
- `docker/publish.sh`

[INLONG-2772][CI] Fix the docker image publish error

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/util/DefaultValueStrategy.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/flink/transformation/FieldMappingTransformer.java
inlong-sort/sort-single-tenant/pom.xml
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/FieldMappingTransformer.java

Fixes #2774 
Fix bugs in single-tenant

[INLONG-2774][Sort] Fix bugs in single-tenant

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/CreateSortConfigListener.java

Fixes #2764 
deduplication dataFlow key

[INLONG-2764][Manager] Fix duplication key when extList already has the same key

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/KafkaJob.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobWrapper.java
inlong-agent/agent-plugins/pom.xml
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/channel/MemoryChannel.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/KafkaSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/TextFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/KafkaReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/snapshot/BinlogSnapshotBase.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/trigger/DirectoryTrigger.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/TestFileAgent.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/MockSink.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestKafkaReader.java
inlong-agent/pom.xml

Fixes #2666 
Agent module supports collecting the data from Kafka.
1. add kafkasource
2. add kafkaReader

[INLONG-2666][Agent] Agent supports collecting the data from Kafka

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/sink/HiveSinkInfo.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/filesystem/Bucket.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/flink/multitenant/pulsar/PulsarTestMetaManagerUtil.java

Fixes #2793 
Fix bugs related to hive sink:
1. Missing '/' when creating path;
2. TextFileFormat json deserialization

[INLONG-2793][Sort] Fix bugs related to hive sink

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/BuiltInFieldInfo.java
inlong-sort/sort-formats/format-json/pom.xml
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/MysqlBinLogData.java
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJsonDecodingFormat.java
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJsonDeserializationSchema.java
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJsonSerializationSchema.java
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/debezium/DebeziumJsonDecodingFormat.java
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/debezium/DebeziumJsonDeserializationSchema.java
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/debezium/DebeziumUtils.java
inlong-sort/sort-formats/pom.xml
inlong-sort/sort-single-tenant/pom.xml
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/Entrance.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/DebeziumDeserializationSchemaBuilder.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/DeserializationFunction.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/DeserializationSchemaFactory.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/FieldMappingTransformer.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/serialization/CanalSerializationSchemaBuilder.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/utils/CommonUtils.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/DebeziumToCanalITCase.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/deserialization/DebeziumDeserializationTest.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/deserialization/FieldMappingTransformerTest.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/serialization/CanalSerializationTest.java

Fixes #2785 
*(or)*
*(or)*
*(example:)* …

[INLONG-2785][Sort] Support extract metadata with debezium format and write them with canal format

---

inlong-dashboard/src/components/AccessHelper/DataSourcesEditor/index.tsx
inlong-dashboard/src/components/AccessHelper/DataStorageEditor/Editor.tsx
inlong-dashboard/src/components/AccessHelper/FieldsConfig/businessFields.tsx
inlong-dashboard/src/utils/requestConcurrentMiddleware.ts

Fixes #2799
Enhance code robustness

[INLONG-2799][Dashboard] Enhance code robustness

---

inlong-dataproxy/conf/log4j2.xml
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/PulsarSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SourceContext.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/tcp/InlongTcpChannelHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/tcp/InlongTcpChannelPipelineFactory.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/tcp/InlongTcpSource.java

update netty version to 4 in inlongTcp* file of dataproxy 
Fixes #2781

[INLONG-2781][DataProxy] Update netty version to 4.x

---

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/pulsar/InLongPulsarFetcherImpl.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/tube/InLongTubeFetcherImpl.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/util/StringUtil.java
inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/pulsar/InLongPulsarFetcherImplTest.java
inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/tube/InLongTubeFetcherImplTest.java

…message protocol
[INLONG-2384] Sort-sdk support Tube consumer of PB compression cache message protocol
Fixes #2384
*(or)*
*(or)*
*(example:)*
- Does this pull request introduce a new …

[INLONG-2384][SDK] Sort-sdk support Tube consumer of PB compression cache message protocol

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/JobProfile.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/conf/ConfigJetty.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/Job.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskWrapper.java

Fixes #2786
Agent jetty server supports different job type
Agent jetty server supports different job type
- Does this pull request introduces a new feature? (no)

[INLONG-2786][Agent] Jetty server supports different job type

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/sink/KafkaSink.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSourceTransfer.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamTransfer.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/kafka/KafkaStreamSinkOperation.java

Fixes #2808 
add kafka sink in manager client

[INLONG-2808][Manager] Manager client support kafka sink

---

inlong-distribution/distribution.xml

Fixes #2832
*(or)*
*(or)*
*(example:)* …

[INLONG-2832][Docker] Package the docker resource to the distribution file

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/Constant.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SourceState.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamFieldEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongGroupServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractStreamSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/SourceSnapshotOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/listener/AbstractSourceOperateListener.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/source/listener/DataSourceListenerTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/workflow/WorkflowServiceImplTest.java
inlong-manager/manager-test/src/main/java/org/apache/inlong/manager/test/BaseTest.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/WorkflowContext.java

Fixes #2821 
Change the status of the source after receiving the task snapshot.

[INLONG-2821][Manager] Change the status of the source after receiving the task snapshot

---

inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/definition/ServiceTask.java

Fixes #2841 
fix a problem about listener can't be invoked

[INLONG-2841][Manager] Fix the listener cannot be invoked

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java

Fixes #2845 
Manager client occurred NPE when parsing the ext info.
Add judgment before parsing the ext info.

[INLONG-2845][Manager] Manager client occurred NPE when parsing the ext info

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongGroup.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongGroupContext.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/BlankInlongGroup.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupState.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongGroupProcessOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/UpdateGroupCompleteListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/UpdateGroupListener.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/source/listener/DataSourceListenerTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/thirdparty/sort/DisableZkForSortTest.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/definition/WorkflowProcess.java

Fixes #2839 
1  Add Intermediate state for Inlong group
2 fix unit test error
This change is already covered by existing tests.

[INLONG-2839][Manager] Add intermediate state for Inlong group

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java

Fixes #2849 
*(or)*
*(or)*
*(example:)* …

[INLONG-2849][Manager] Fix NPE in Manager Client

---

inlong-dataproxy/bin/dataproxy-start.sh
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java

Fixes #2802 
*(or)*
*(or)*
*(example:)* …

[INLONG-2802][DataProxy] Fix mx.properties local file updating too often

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/CommandDb.java
inlong-agent/agent-common/src/test/java/org/apache/inlong/agent/db/TestBerkeleyDBImp.java
inlong-common/src/main/java/org/apache/inlong/common/db/CommandEntity.java

Fixes #2851 
[INLONG-2851][Agent][Feature] Agent change task id string to integer
[INLONG-2851][Agent][Feature] Agent change task id string to integer

[INLONG-2851][Agent] Change the taskId type from string to integer

---

inlong-common/src/main/java/org/apache/inlong/common/enums/TaskTypeEnum.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SourceType.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/CreateSortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SinkInfoUtils.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/BuiltInFieldInfo.java

[INLONG-2829][Manager] Support whole-database migration for the inlong-sort module

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java

Fixes #2873 
Fix serialization problem

[INLONG-2873][Manager] Fix serialization problem cause request exception

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskWrapper.java

Fixes #2857 
Agent support destroy task
Agent support destroy task

[INLONG-2857][Agent] Agent support destroy task

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SerializationUtils.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/BuiltInFieldInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/DebeziumDeserializationInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/serialization/CanalSerializationInfo.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/deserialization/DebeziumDeserializationInfoTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/serialization/CanalSerializationInfoTest.java
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/MysqlBinLogData.java
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJsonSerializationSchema.java
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/debezium/DebeziumJsonDecodingFormat.java
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/debezium/DebeziumJsonDeserializationSchema.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/DebeziumDeserializationSchemaBuilder.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/DeserializationSchemaFactory.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/FieldMappingTransformer.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/serialization/CanalSerializationSchemaBuilder.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/serialization/SerializationSchemaFactory.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/utils/CommonUtils.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/DebeziumToCanalITCase.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/WholeDBMigrationITCase.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/kafka/RowToCanalKafkaSinkTest.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/serialization/CanalSerializationTest.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/utils/CommonUtilsTest.java

Fixes #2847 
Support whole-database migration from debezium format to canal format

[INLONG-2847][Sort] Support whole-database migration from debezium format to canal format

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/HiveServerDao.java

Fixes #2886 
Check if the URL is valid to avoid network security attacks.

[INLONG-2886][Manager] Check if the URL is valid to avoid network security attacks

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Constants.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/DataFlowInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/FieldMappingRule.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/TransformationInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/TransformationRule.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/Entrance.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/transformation/Transformer.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/transformation/TransformerTest.java

[INLONG-2872][Sort] Support field mapping when transforming

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/FullStreamResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongStreamServiceImpl.java

Fixes #2890 
Support query source list in `stream/listAll` API.

[INLONG-2890][Manager] Support query source list in stream/listAll API

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongStreamServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/GroupCompleteProcessListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/stream/StreamCompleteProcessListener.java

Fixes #2892 
Update status of StreamSource after approving the InlongGroup or InlongStream.

[INLONG-2892][Manager] Update status of StreamSource after approving the InlongGroup or InlongStream

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/FetcherConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerResultFormatter.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/DataConfig.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java

Fixes #2894 
Adapt the interface and field modification of the manager module.

[INLONG-2894][Agent] Adapt the interface and field modification of the manager module

---

inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml

Fixes #2904 
*(or)*
*(or)*
*(example:)* …

[INLONG-2904] Fix StreamSourceEntityMapper handling mistakes

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamTransfer.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/DataProxyClusterServiceImpl.java

Fixes #2906 
*(or)*
*(or)*
*(example:)* …

[INLONG-2906][Manager] Fix conflicts defined between dataproxy and sort

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/source/MySQLBinlogSource.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSourceTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SourceType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/CreateSortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SinkInfoUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SourceInfoUtils.java

[INLONG-2917][Manager] Fix migrate all database task in manager

---

inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/example/consumer/test_consumer.cc
inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/example/consumer/test_multi_thread_filter.cc
inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/example/consumer/test_multithread_pull.cc
inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/tubemq_tdmsg.cc
inlong-tubemq/tubemq-client/src/test/java/org/apache/inlong/tubemq/client/consumer/MessageFetchManagerTest.java
inlong-tubemq/tubemq-client/src/test/java/org/apache/inlong/tubemq/client/consumer/PartitionExtTest.java
inlong-tubemq/tubemq-client/src/test/java/org/apache/inlong/tubemq/client/factory/TubeBaseSessionFactoryTest.java
inlong-tubemq/tubemq-client/src/test/java/org/apache/inlong/tubemq/client/factory/TubeMultiSessionFactoryTest.java
inlong-tubemq/tubemq-client/src/test/java/org/apache/inlong/tubemq/client/factory/TubeSingleSessionFactoryTest.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/client/CallFuture.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/offsetstorage/zookeeper/ZooKeeperWatcher.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/utils/HttpUtils.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/utils/WebParameterUtils.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/action/screen/config/BrokerList.java

Fixes #2915
1. Remove meaningless blank lines
2. Replace the IP address with 127.0.0.1;
3. Use static_cast() instead of C-style casts

[INLONG-2915][TubeMQ] Fix code style issues

---

inlong-dataproxy/conf/flume-mulit-pulsar-tcp-example.conf

Add configure example for order message #2926
Fixes #2926

[INLONG-2926][DataProxy] Add configure example for order message

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerGroupContext.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSourceTransfer.java

Fixes #2924 
*(or)*
*(or)*
*(example:)* …

[INLONG-2924][Manager] Fix NPE in manager client

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupState.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SourceType.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/CommonOperateService.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/AgentController.java

Fixes #2913 
Fix get data proxy cluster and update inlong group failed.

[INLONG-2913][Manager] Fix get data proxy cluster and update inlong group failed

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/base/OrderEvent.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/channel/FailoverChannelProcessor.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/channel/FailoverChannelSelector.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/AttributeConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/PulsarSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/MessageUtils.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/codec/ProtocolDecoder.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/codec/ProtocolEncoder.java

support keeping message order 
Fixes #2920

[INLONG-2920][DataProxy] Support keeping message order 

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceResponse.java

[INLONG-2931][Manager] Improve parse response in manager client

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/TriggerProfile.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/HttpManager.java
inlong-agent/agent-common/src/test/java/org/apache/inlong/agent/db/TestBerkeleyDBImp.java
inlong-common/src/main/java/org/apache/inlong/common/db/CommandEntity.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/DataConfig.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java

Fixes #2933 
Change the type of the deliveryTime field from Date to String.

[INLONG-2933][Agent][Manager] Change the type of the deliveryTime field from Date to String

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/DefaultInlongStreamBuilder.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/sink/ClickHouseSink.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSinkTransfer.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SinkInfoUtils.java

Fixes #2930 
Add clickhouse sink support in manager client

[INLONG-2930][Manager] Add ClickHouse sink support in manager client

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/JobProfile.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/TriggerProfile.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/JobProfileDb.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/plugin/Reader.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/BinlogJob.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/AgentUtils.java
inlong-agent/agent-common/src/test/java/org/apache/inlong/agent/db/TestBerkeleyDBImp.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskWrapper.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/task/TestTaskWrapper.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/BinlogReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/KafkaReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/SqlReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/TextFileReader.java

Fixes #2928 
Fix multiple bugs when agent communicate with manager
add job  \ report heartbeat
Fix multiple bugs when agent communicate with manager

[INLONG-2928][Agent] Fix multiple bugs when agent communicate with manager

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/FieldInfo.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/BuiltInFieldInfoTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/kafka/KafkaSinkInfoTest.java

Fixes #2910 
Fix deserialization error of BuiltInField json string

[INLONG-2910][Sort] Fix deserialization error of BuiltInField json string

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/CommonDBServerServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/CommonFileServerServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/listener/AbstractSourceOperateListener.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/AuditController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/BasicInfoController.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/processor/AbstractNextableElementProcessor.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/processor/AbstractTaskProcessor.java

Fixes #2941 
*(or)*
*(or)*
*(example:)* …

[INLONG-2941][Manager] Code optimization for InLong Manager

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/source/MySQLBinlogSource.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSourceTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java

Fixes #2912 
Add fields for the binlog task.

[INLONG-2912][Manager] Add fields for the binlog task

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java

Fixes #2946 
Agent change async send param to boolean
Agent change async send param to boolean

[INLONG-2946][Agent] Agent change async send param to boolean

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/AgentController.java

Fixes #2944 
Should not change the modify_time when updating the source snapshot.

[INLONG-2944][Manager] Should not change the modify_time when updating the source snapshot

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSourceTransfer.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/CommonFileServerServiceImpl.java

Fixes #2934 
*(or)*
*(or)*
*(example:)* …

[INLONG-2934][Manager] Manager client occured NPE since not check NUL

---

LICENSE
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerServiceServer.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/DefaultOffsetManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/OffsetService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/offsetstorage/OffsetStorage.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/offsetstorage/OffsetStorageInfo.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/offsetstorage/ZkOffsetStorage.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/zookeeper/Abortable.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/zookeeper/RecoverableZooKeeper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/zookeeper/RetryCounter.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/zookeeper/RetryCounterFactory.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/zookeeper/ZKUtil.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/zookeeper/ZooKeeperConnectionException.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/zookeeper/ZooKeeperListener.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/zookeeper/ZooKeeperWatcher.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/TMaster.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/balance/DefaultLoadBalancer.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/balance/LoadBalancer.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/BdbMetaStoreServiceImpl.java

[INLONG-2955][TubeMQ] Adjust the offsetstorage and zookeeper package paths

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Constants.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/Entrance.java

Fixes #2953 
*(or)*
*(or)*
*(example:)* …

[INLONG-2953][Sort] Support orderly output

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/ClusterController.java

Fixes #2957 
Optimize the cluster management interface.
Add cluster controller into the openapi package.

[INLONG-2957][Manager] Optimize the cluster management interface

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/StreamSource.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSourceTransfer.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongGroupServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/mq/CreatePulsarGroupForStreamTaskListener.java

Fixes #2965 
*(or)*
*(or)*
*(example:)* …

[INLONG-2965][Manager] Add agentIp in manager client

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/CommonOperateService.java

Fixes #2963 
*(or)*
*(or)*
*(example:)* …

[INLONG-2963][Manager] Fix get Pulsar url in CommonOperateService

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/BerkeleyDbImp.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/AgentUtils.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/BinlogReader.java
inlong-agent/conf/agent.properties

Fixes #2860 
Create file folder when history file set by user does not exist and make uuid configurable 
Create file folder when history file set by user does not exist and make uuid configurable 

[INLONG-2860][Agent] Create file folder when history file set by user does not exist and make uuid configurable

---

inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/ClusterController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenClusterController.java

Fixes #2969 
Fix interface of open API cluster.

[INLONG-2969][Manager] Fix interface of open API cluster

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongGroupContext.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamConfigLogEntityMapper.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AbstractService.java

Fixes #2971 
*(or)*
*(or)*
*(example:)* …

[INLONG-2971][Manager] Support stream log collecting in manager client

---

inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/PulsarClusterInfo.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongGroupConf.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongGroupTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupInfo.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupResponse.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/CommonOperateService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongGroupServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/mq/CreatePulsarGroupForStreamTaskListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/mq/CreatePulsarGroupTaskListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/mq/CreatePulsarResourceTaskListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/mq/CreatePulsarTopicForStreamTaskListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/mq/util/PulsarUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/CreateSortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/PushSortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SourceInfoUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/consumption/listener/ConsumptionCompleteProcessListener.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/thirdparty/mq/util/PulsarUtilsTest.java

Fixes #2973 
Not to get pulsar info from manager client and fix some problem to get pulsar info from `third_party_cluster` table

[INLONG-2973][Manager] Get pulsar info from the cluster table

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/BdbMetaStoreServiceImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/MetaStoreService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/BaseEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/BrokerConfEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/ClusterSettingEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/GroupConsumeCtrlEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/TopicDeployEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/BrokerConfigMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/ClusterConfigMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/GroupConsumeCtrlMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/GroupResCtrlMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/TopicCtrlMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/TopicDeployMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbBrokerConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbClusterConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbGroupConsumeCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbGroupResCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbTopicCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbTopicDeployMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/DefBrokerRunManager.java

[INLONG-2980][TubeMQ] Modify the code style problems of the metadata classes

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/source/MySQLBinlogSource.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java

Fixes #2985 
Fix task type and timezone param for agent

[INLONG-2985][Manager] Fix task type and timezone param for agent

---

inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/cluster/ClusterController.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/cluster/request/DeleteClusterReq.java

Fixes #2979
*(or)*
*(or)*
*(example:)* …

[INLONG-2979][TubeMQ] TubeMQ cluster delete provides token code

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongGroupTransfer.java

Fixes #2993
Check whether the mq info is NULL to avoid NPE.

[INLONG-2993][Manager] Check whether the mq info is NULL to avoid NPE

---

inlong-tubemq/tubemq-client-twins/tubemq-client-go/README.md
inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/message.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/peer.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/codec/tubemq_codec.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/config/config.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/example/consumer.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/example/multi_routine_consumer.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/flowctrl/handler.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/log/logger.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/metadata/consumer_event.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/metadata/partition.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/multiplexing/multiplexing.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/remote/remote.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/rpc/broker.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/rpc/client.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/rpc/master.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/selector/ip_selector_test.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/tdmsg/bin_msg.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/tdmsg/td_msg.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/util/util.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/util/util_test.go

Fixes #2989 
Fix the coding style problem of TubeMQ Go SDK
Fix the coding style problem of TubeMQ Go SDK
*(or)*
*(or)*
*(example:)*
- Does this pull request introduce a new feature? …

[INLONG-2989][TubeMQ] Fix the coding style problem of TubeMQ Go SDK

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/ClusterInfo.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ThirdPartyClusterServiceImpl.java

Fixes #3000 
Add token field for cluster info.

[INLONG-3000][Manager] Add token field for cluster info

---

inlong-dashboard/src/pages/AccessDashboard/ExecutionLogModal.tsx

[INLONG-2996][Dashboard] An error is reported after closing the group execution log modal

---

inlong-dashboard/src/pages/AccessDashboard/ExecutionLogModal.tsx

[INLONG-2997][Dashboard] The group execution log needs to distinguish between different states

---

inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/cluster/ClusterController.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/cluster/request/AddClusterReq.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/entry/ClusterEntry.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/ClusterServiceImpl.java
inlong-tubemq/tubemq-manager/src/test/java/org/apache/inlong/tubemq/manager/controller/TestClusterController.java

…r webport configuration
Fixes https://github.com/apache/incubator-inlong/issues/3002
*(or)*
*(or)*
*(example:)*
- If yes, …

[INLONG-3002][TubeMQ] Support config multi-master port and webport for new cluster 

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Constants.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/source/SourceInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/source/TDMQPulsarSourceInfo.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/pulsar/TDMQPulsarSourceFunction.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/Entrance.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/pulsar/PulsarSourceBuilder.java

Fixes #3009 
*(or)*
*(or)*
*(example:)* …

[INLONG-3009][Sort] Support TDMQ Pulsar source

---

inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/PulsarClusterInfo.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongStreamConf.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/PulsarBaseConf.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/TubeBaseConf.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongGroupTransfer.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/Constant.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/MqType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupMqExtBase.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupPulsarInfo.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongGroupPulsarEntity.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupPulsarEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/CommonOperateService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/DataProxyClusterServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/mq/PulsarEventSelector.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/CreateSortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/PushSortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SourceInfoUtils.java
inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql

Fixes #3007 
*(or)*
*(or)*
*(example:)* …

[INLONG-3007][Manager] Add enable_create_resource for mq conf

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/Constant.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/InlongStreamInfo.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/CreateSortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/PushSortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/ZkDisabledEventSelector.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/ZkEnabledEventSelector.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SerializationUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SinkInfoUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SourceInfoUtils.java

Fixes #3012 
Add built-in fields for source and sink info.
1. Add built-in fields for source and sink info;
2. Optimize the code.

[INLONG-3012][Manager] Support built-in fields for source and sink info

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/ClusterInfo.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ThirdPartyClusterServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenClusterController.java

Fixes #3017 
The interface of OpenAPI does not need authentication.

[INLONG-3017][Manager] The interface of OpenAPI does not need authentication

---

inlong-tubemq/tubemq-client-twins/tubemq-client-go/config/config.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/util/util.go

Fixes #3020
Format the some code of TubeMQ Go SDK
Format the some code of TubeMQ Go SDK
*(or)*
*(or)*
*(example:)*
- If …

[INLONG-3020][TubeMQ] Format the code of Go SDK

---

inlong-agent/agent-docker/agent-docker.sh

Fixes #3022
*(or)*
*(or)*
*(example:)* …

[INLONG-3022][Agent] Fix the agent pod start error

---

inlong-agent/pom.xml

Upgrade snappy version
Fixes #3027

[INLONG-3027][Agent] Upgrade snappy version

---

inlong-tubemq/tubemq-client/src/test/java/org/apache/inlong/tubemq/client/producer/qltystats/DefaultBrokerRcvQltyStatsTest.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/offsetstorage/ZkOffsetStorage.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/zookeeper/ZKUtil.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/BdbMetaStoreServiceImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/AbstractMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/BrokerConfigMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/ClusterConfigMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/ConsumeCtrlMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/GroupResCtrlMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/TopicCtrlMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/TopicDeployMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsBrokerConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsClusterConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsConsumeCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsGroupResCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsTopicCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsTopicDeployMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbBrokerConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbConsumeCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbGroupResCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbTopicCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbTopicDeployMapperImpl.java

Fixes #3029
1. Add the abstract classes of Mapper to separate the specific implementation of cache and BDB;
2. Optimize the implementation logic in the bdbimpl package based on 1
3. Add interface comments

[INLONG-3029][TubeMQ] Adjust the implementation classes under the impl.bdbimpl package

---

inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/TokenConstants.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/TZKNodeKeys.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/ZKBrokerConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/ZKClusterConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/ZKConsumeCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/ZKGroupResCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/ZKTopicCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/ZKTopicDeployMapperImpl.java

[INLONG-2844][TubeMQ] Implement the ZooKeeper-based metadata Mapper class

---

inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/cluster/request/AddClusterReq.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/entry/ClusterEntry.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/ClusterServiceImpl.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/NodeServiceImpl.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/TaskServiceImpl.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/interfaces/NodeService.java
inlong-tubemq/tubemq-manager/src/test/java/org/apache/inlong/tubemq/manager/controller/TestClusterController.java

Fixes https://github.com/apache/incubator-inlong/issues/3015
*(or)*
*(or)*
*(example:)* …

[INLONG-3015] [TubeMQ] Add configuration to support the number of reloaded machines per batch

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/DefaultInlongStreamBuilder.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSinkTransfer.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamTransfer.java

Fixes #3033 
*(or)*
*(or)*
*(example:)* …

[INLONG-3033][Manager] Add sourceFieldName in sinkFields

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/SinkField.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/StreamSink.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/sink/ClickHouseSink.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/sink/HiveSink.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/sink/KafkaSink.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSinkTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/ck/ClickHouseSinkResponse.java

Fixes #3037 
*(or)*
*(or)*
*(example:)* …

[INLONG-3037][Manager] Add field mapping support for source and sink in manage client

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupState.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/CreateSortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SinkInfoUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SourceInfoUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/DeleteGroupWorkflowDefinition.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/RestartGroupWorkflowDefinition.java

Fixes #3042 
*(or)*
*(or)*
*(example:)* …

[INLONG-3042][Manager] Supplements of binlog all migration

---

docker/kubernetes/templates/agent-statefulset.yaml
inlong-dataproxy/dataproxy-docker/Dockerfile
inlong-dataproxy/dataproxy-docker/dataproxy-docker.sh

Fixes #3047
*(or)*
*(or)*
*(example:)* …

[INLONG-3047][DataProxy] Refactor the common config for Docker

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupRequest.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongGroupEntityMapper.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSinkEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongGroupProcessOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongGroupServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/GroupCompleteProcessListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/GroupPassTaskListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/UpdateGroupCompleteListener.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/InlongGroupProcessOperationTest.java
inlong-manager/manager-test/pom.xml
inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/UtilsTest.java
inlong-manager/pom.xml

Fixes #3046 
The status was incorrect after approving an inlong group.

[INLONG-3046][Manager] The status was incorrect after approving an inlong group

---

inlong-agent/pom.xml

Fixes #3051 
*(or)*
*(or)*
*(example:)* …

[INLONG-3050][Agent] Agent update guava version

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/FieldMappingRule.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/TransformationInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/TransformationRule.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/FieldMappingRuleTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/TransformationInfoTest.java

Fixes #3055 
Fix bug occurred when deserializing TransformationInfo json string

[INLONG-3055][Sort] Fix bug occurred when deserializing TransformationInfo json string

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupState.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/CommonOperateService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongGroupProcessOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongGroupServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractStreamSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/PushSortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/GroupCancelProcessListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/GroupCompleteProcessListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/GroupFailedProcessListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/GroupPassTaskListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/GroupRejectProcessListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/InitGroupListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/UpdateGroupCompleteListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/UpdateGroupListener.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/InlongGroupProcessOperationTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/source/listener/DataSourceListenerTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/thirdparty/sort/DisableZkForSortTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/workflow/WorkflowServiceImplTest.java

Fixes #3053 
Push sort config failed as the mqExtInfo is null in workflow form。

[INLONG-3053][Manager] Push sort config failed as the mqExtInfo is null in workflow form

---

DISCLAIMER-WIP
inlong-agent/agent-docker/Dockerfile
inlong-agent/agent-plugins/pom.xml
inlong-audit/audit-docker/Dockerfile
inlong-audit/audit-store/pom.xml
inlong-audit/audit-store/src/test/resources/application.properties
inlong-audit/conf/application.properties
inlong-audit/pom.xml
inlong-manager/manager-dao/pom.xml
inlong-manager/manager-docker/Dockerfile
inlong-manager/manager-web/src/main/resources/application-dev.properties
inlong-manager/manager-web/src/main/resources/application-prod.properties
inlong-manager/manager-web/src/main/resources/application-test.properties
inlong-manager/pom.xml
inlong-tubemq/tubemq-docker/tubemq-manager/Dockerfile
inlong-tubemq/tubemq-docker/tubemq-manager/manager-docker.sh
inlong-tubemq/tubemq-manager/pom.xml
inlong-tubemq/tubemq-manager/src/main/resources/application.properties
pom.xml

Fixes #2784
*(or)*
*(or)*
*(example:)* …

[INLONG-2784] Replace MySQL with PostgreSQL

---

inlong-manager/manager-docker/Dockerfile
inlong-manager/manager-docker/README.md
inlong-manager/manager-docker/manager-docker.sh

Fixes #3065
*(or)*
*(or)*
*(example:)* …

[INLONG-3065][Manager] Support download plugins from remote address

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/DataFormat.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/KafkaOffset.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/source/KafkaSource.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSourceTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/KafkaOffset.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceResponse.java

Fixes #3068 
Add autoOffsetReset param for Kafka source.

[INLONG-3068][Manager] Add autoOffsetReset param for Kafka source

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/Constant.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/ThirdPartyClusterEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/ThirdPartyClusterEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ThirdPartyClusterServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SourceInfoUtils.java
inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql

Fixes #3073 
Get MQ cluster by the type and mq_set_name.

[INLONG-3073][Manager] Get MQ cluster by the type and mq_set_name

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/federation/PulsarProducerCluster.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/DefaultServiceDecoder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServiceDecoder.java
inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/metrics/TestMetricListenerRunnable.java
inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/sink/TestPulsarSink.java
inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/sink/pulsar/federation/TestPulsarFederationSink.java
inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/sink/pulsar/federation/TestPulsarProducerFederation.java
inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/utils/MockUtils.java

[INLONG-2962][DataProxy] Unit tests throw so many error msg

---

inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/source/DefaultServiceDecoder.java
inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/source/ServiceDecoder.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/db/DruidConfig.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/db/dao/AuditDataDao.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/ElasticsearchService.java
inlong-audit/audit-store/src/main/resources/sql/apache_inlong_audit.sql
inlong-audit/audit-store/src/test/java/org/apache/inlong/audit/service/AuditStoreTest.java
inlong-audit/audit-store/src/test/java/org/apache/inlong/audit/service/ElasticsearchServiceTest.java
inlong-audit/audit-store/src/test/resources/application-test.properties

Fixes #2960 #2468
Unit tests error when executing mvn test command.

[INLONG-2960][Audit] Unit tests error when executing mvn test command

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/KafkaReader.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestKafkaReader.java
inlong-agent/pom.xml

Fixes #3083 
*(or)*
*(or)*
*(example:)* …

[INLONG-3083][Agent] Agent should update scala version in kafka client, and commit offset when read finish

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ConfStringUtils.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/tcp/InlongTcpSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/EventLoopUtil.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/MessageUtils.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/DefaultEvent2LogItemHandler.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/IEvent2LogItemHandler.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/FetchCallback.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSource.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SubscribeFetchResult.java
inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsOutputChannel.java
inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsSinkContext.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/group/GroupController.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/topic/TopicWebController.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/NodeServiceImpl.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/interfaces/BrokerService.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/interfaces/MasterService.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/interfaces/NodeService.java

Fixes #2961 #3086
Fix check style error.

[INLONG-2961][DataProxy][Sort] Fix check style errors

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/GroupCompleteProcessListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/UpdateGroupCompleteListener.java

Fixes #3095 
Update inlong group info in the complete listeners, as some ext params will be changed in listeners.

[INLONG-3095][Manager] Update inlong group info in the complete listeners

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/utils/WebParameterUtils.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/DataOpErrCode.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/MetaDataManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/keepalive/KeepAlive.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/BrokerConfigMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsBrokerConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsClusterConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsConsumeCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsGroupResCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsTopicCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsTopicDeployMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbBrokerConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbClusterConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbConsumeCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbGroupResCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbMetaStoreServiceImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbTopicCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbTopicDeployMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/TZKNodeKeys.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/ZKBrokerConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/ZKClusterConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/ZKConsumeCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/ZKGroupResCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/ZKTopicCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/ZKTopicDeployMapperImpl.java

[INLONG-3093][TubeMQ] Optimize the AbsXXXMapperImpl implementation classes

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/message/PackProxyMessage.java

Fixes #3099 
Duplicate send message when agent receive data
Duplicate send message when agent receive data

[INLONG-3099][Agent] Duplicate send message when agent receive data

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/utils/WebParameterUtils.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/MetaDataManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/MetaStoreService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/BrokerConfigMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/ClusterConfigMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/ConsumeCtrlMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/MetaStoreMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/TopicDeployMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsBrokerConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsClusterConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsConsumeCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsGroupResCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsMetaStoreMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsTopicCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsTopicDeployMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbMetaStoreServiceImpl.java

[INLONG-3105][TubeMQ] Add MetaStoreMapper related implementation

---

inlong-sort/sort-single-tenant/pom.xml

Fixes #3110 
*(or)*
*(or)*
*(example:)* …

[INLONG-3110][Sort] Shade flink-avro to avoid potential conflicts

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/KafkaSource.java

[INLONG-3104][Agent]  Add default value for kafka consumer group
Fixes #3104
Add default value for kafka consumer group
Add default value for kafka consumer group

[INLONG-3104][Agent]  Add default value for kafka consumer group

---

inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/partition/RowPartitionComputer.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/CustomDateFormatDeserializationSchemaWrapper.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/serialization/CustomDateFormatSerializationSchemaWrapper.java

Fixes #3113
Fix date and time related bugs

[INLONG-3113][Sort] Fix date and time related bugs

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/SinkField.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/source/KafkaSource.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSinkTransfer.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSourceTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/MetaFieldType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/SinkFieldRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/SinkFieldResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceResponse.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/StreamSinkFieldEntity.java
inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkFieldEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/FieldInfoUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SerializationUtils.java
inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql

Fixes #3112 
*(or)*
*(or)*
*(example:)* …

[INLONG-3112][Manager] Support metadata field in manager and manager client

---

inlong-dashboard/src/components/AccessHelper/DataSourcesEditor/CreateModal.tsx
inlong-dashboard/src/components/AccessHelper/DataSourcesEditor/index.tsx
inlong-dashboard/src/components/AccessHelper/FieldsConfig/dataFields.tsx
inlong-dashboard/src/components/MetaData/DataSourcesBinLog.ts
inlong-dashboard/src/locales/cn.json
inlong-dashboard/src/locales/en.json
inlong-dashboard/src/pages/AccessDetail/DataSources/index.tsx

[INLONG-3128][Dashboard] Make binlog as a source type feature.

---

inlong-agent/pom.xml

Fixes #3100 
[INLONG-3100][Agent] update kafka to newest version 3.1.0
[INLONG-3100][Agent] update kafka to newest version 3.1.0
*(or)*
*(or)*
*(example:)*
- If a feature …

[INLONG-3100][Agent] Upgrade Kafka to the newest version 3.1.0

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/CanalDeserializationInfo.java
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJsonDecodingFormat.java
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJsonDeserializationSchema.java
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalUtils.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/Entrance.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/CanalDeserializationSchemaBuilder.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/DebeziumDeserializationSchemaBuilder.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/DeserializationSchemaFactory.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/FieldMappingTransformer.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/utils/CommonUtils.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/deserialization/CanalDeserializationTest.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/deserialization/DeserializationFunctionTest.java

Fixes #3130 
*(or)*
*(or)*
*(example:)* …

[INLONG-3130][Sort] Support extract specified metadata from input data with canal format

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/fileconfig/ZKConfig.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/zookeeper/ZKUtil.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/MetaDataManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/KeepAliveService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsMetaConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbMetaConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbMetaStoreServiceImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/ZKMetaConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/MasterStatusCheckFilter.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/action/screen/Tubeweb.java

[INLONG-3035][TubeMQ] Optimize the MetaStoreService implementation class

---

inlong-common/src/main/java/org/apache/inlong/common/reporpter/AbstractReporter.java
inlong-common/src/test/java/org/apache/inlong/common/metric/reporter/ReporterTest.java
inlong-dataproxy/conf/common.properties
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java

Fixed a bug if an exception is thrown, no response message to client while using order message
Fixes #3161

[INLONG-3161][DataProxy] Fix not responding client when throwing exception with order message

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/auth/InlongShiro.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/ShiroConfig.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/impl/InlongShiroImpl.java

Fixes #3156
Add Shiro interface for manager authorization.

[INLONG-3156][Manager] Add Shiro interface for manager authorization

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java

Fixes #3163 
*(or)*
*(or)*
*(example:)* …

[INLONG-3163][Manager] Throw Exception when source name or sink name was duplicate

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SourceState.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractStreamSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java

Fixes #3160 
Deleting stream source failed as the status was not allowed to delete.

[INLONG-3160][Manager] Deleting stream source failed as the status was not allowed to delete

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/KafkaSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/KafkaReader.java

[INLONG-3168][Agent] modify deserializerType
Fixes #3168
modify deserializerType
modify deserializerType

[INLONG-3168][Agent] Change the deserialization type from String to byte array

---

inlong-audit/audit-sdk/pom.xml
inlong-audit/pom.xml
inlong-manager/pom.xml
inlong-sort-standalone/pom.xml
inlong-sort/pom.xml
inlong-tubemq/pom.xml
inlong-tubemq/tubemq-connectors/tubemq-connector-flink/pom.xml
inlong-tubemq/tubemq-connectors/tubemq-connector-flink/src/main/java/org/apache/flink/connectors/tubemq/TubemqTableSink.java
pom.xml

[INLONG-2450][InLong] Update the dependency to fix the CVEs

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java

Fixes #3176 
*(or)*
*(or)*
*(example:)* …

[INLONG-3176][Manager] Fix duplicate key exceptions

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java

When creating a producer fails, there is no response message to client 
Fixes #3183

[INLONG-3183][DataProxy] Fix no response to the client when creating a producer failed

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/DefaultMetaDataService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/MetaDataService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/MetaConfigMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsBrokerConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsMetaConfigMapperImpl.java

[INLONG-3143][TubeMQ] Optimize Metadatamanager class implementation

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/CreateSortConfigListener.java

###[INLONG-3188][manager]Fix status is not right when CreateSortConfigListener throw exception
Fixes #3188 
fix status is not right

[INLONG-3188][Manager] Fix status is not right

---

inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml

[INLONG-3190][Manager] Fix sql error in select source list

---

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/QueryConsumeConfigImpl.java
pom.xml

Fixes #3185
*(or)*
*(or)*
*(example:)* …

[INLONG-3185][Sort] use sortTaskId to classify inlongtopic for Sort SDK

---

inlong-agent/agent-docker/Dockerfile
inlong-audit/audit-docker/Dockerfile
inlong-dataproxy/dataproxy-docker/Dockerfile
inlong-manager/manager-docker/Dockerfile
inlong-tubemq/tubemq-docker/tubemq-all/Dockerfile
inlong-tubemq/tubemq-docker/tubemq-manager/Dockerfile

[INLONG-3204][InLong] Add some basic tools to debug for docker image

---

inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/Entrance.java

Fixes #3206 
*(or)*
*(or)*
*(example:)* …

[INLONG-3206][Sort] Do not specify uid for kafka sink in case of transactionalId conflict

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebMasterInfoHandler.java

[INLONG-3072][TubeMQ] Output the total count of control block in admin_query_cluster_topic_view

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongClientImpl.java

Fixes #3209 
*(or)*
*(or)*
*(example:)* …

[INLONG-3112][Manager] Optimize timeout handling in manager client

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupPageRequest.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml

Fixes #3208 
*(or)*
*(or)*
*(example:)* …

[INLONG-3208][Manager] Support batch query by inlong group name and inlong group id

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongClientImpl.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java

Fixes #3210 
*(or)*
*(or)*
*(example:)* …

[INLONG-3210][Manager] Support group batch query in manager client

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SourceDbServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SourceFileServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractStreamSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java

Fixes #3228 
Deadlock found when trying to get lock.
1. Not use `select for update` when querying sources by related id.
2. Add some logs.

[INLONG-3228][Manager] Deadlock found when trying to get lock

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java
inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/CommonPropertiesHolder.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSource.java

Fixes #3175
return null when same md5
*(or)*
*(or)*
*(example:)* …

[INLONG-3175][Manager] SortService check md5

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java

Fixes #3239 
*(or)*
*(or)*
*(example:)* …

[INLONG-3239][Manager] Change the list interface from GET to Post to fix list group error

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongGroupServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongStreamServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractStreamSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/SourceSnapshotOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java

Fixes #3252 
*(or)*
*(or)*
*(example:)* …

[INLONG-3252][Manager] Remove repeated-read transaction in the getting source method

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/KeyValueEntity.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/RocksDbImp.java
inlong-agent/agent-common/src/test/java/org/apache/inlong/agent/db/TestRocksDbImp.java

Fixes #3045 
Add rocksDb implementation for db
Add rocksDb implementation

[INLONG-3045][Agent] Add rocksDb implementation

---

.github/workflows/ci_build.yml
.github/workflows/ci_build_docker.yml
.github/workflows/ci_check_license.yml
.github/workflows/ci_ut.yml

fix: #3234
Improve workflow trigger timing.
- `.github/workflows`

[INLONG-3234][CI] Improve workflow trigger timing

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/kafkazone/KafkaZoneSinkContext.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsarzone/PulsarZoneSinkContext.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/tubezone/TubeZoneSinkContext.java

Fixes #3250 
*(or)*
*(or)*
*(example:)* …

[INLONG-3250][DataProxy] Fix duration error of DataProxy metric

---

inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/kafka/KafkaSinkBuilder.java

Fixes #3260 
*(or)*
*(or)*
*(example:)* …

[INLONG-3260][Sort] Change the default semantic to at-least-once when using kafka producer

---

inlong-audit/audit-store/pom.xml
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/config/MessageQueueConfig.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/consume/BaseConsume.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/consume/PulsarConsume.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/consume/TubeConsume.java
inlong-audit/audit-store/src/test/java/org/apache/inlong/audit/service/consume/PulsarConsumeTest.java
inlong-audit/audit-store/src/test/java/org/apache/inlong/audit/service/consume/TubeConsumeTest.java
inlong-audit/audit-store/src/test/resources/application-test.properties
inlong-audit/conf/application.properties

Fixes #3159 
*(or)*
*(or)*
*(example:)* …

[INLONG-3159][Audit] Store support TubeMQ

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/OffsetRecordService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/DefaultMetaDataService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/BrokerConfEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/TopicDeployEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsMetaConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/TZKNodeKeys.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/zkimpl/ZKMetaConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/DefBrokerRunManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebMasterInfoHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebTopicDeployHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/tools/cli/CliMetaDataBRU.java

[INLONG-3268][TubeMQ] Fix some bugs when metadata is saved to ZooKeeper

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/AgentService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/AgentController.java

Fixes #3269
Change the request method of list query from GET to POST.

[INLONG-3269][Manager] Change the request method of list query from GET to POST

---

inlong-dashboard/src/components/ConsumeHelper/BusinessSelect/MyBusinessModal.tsx
inlong-dashboard/src/pages/AccessCreate/DataStream/index.tsx
inlong-dashboard/src/pages/AccessDashboard/index.tsx
inlong-dashboard/src/pages/AccessDetail/Audit/config.tsx
inlong-dashboard/src/pages/AccessDetail/DataSources/index.tsx
inlong-dashboard/src/pages/AccessDetail/DataStorage/index.tsx
inlong-dashboard/src/pages/AccessDetail/DataStream/index.tsx

Fixes #3275
Change the request method of list query from GET to POST.

[INLONG-3275][Dashboard] Change the request method of list query from GET to POST

---

inlong-sort-standalone/pom.xml

Fixes #3285
security issue
pom
*(or)*
*(or)*
*(example:)*

[INLONG-3285][Sort] Upgrade Elasticsearch jar due to the CVEs

---

inlong-dataproxy/conf/dataproxy-pulsar.conf

Add default order message configuration
Fixes #3282

[INLONG-3282][DataProxy] Add default order message configuration

---

inlong-dataproxy/conf/dataproxy-mulit-pulsar-http-example.conf
inlong-dataproxy/conf/dataproxy-mulit-pulsar-udp-example.conf
inlong-dataproxy/conf/dataproxy-pulsar.conf
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/BaseSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java

Change the default topic to an optional configuration. If there is not default topic, the corresponding topic cannot be found and discarded directly
Fixes #3231

[INLONG-3231][DataProxy] Change the default topic to an optional configuration

---

inlong-dataproxy/conf/dataproxy-pulsar.conf

Default channel config for order message didn't work
Fixes #3291

[INLONG-3291][DataProxy] Add ch-msg3 in default channels for order message

---

inlong-agent/agent-common/src/test/java/org/apache/inlong/agent/db/TestBerkeleyDBImp.java
inlong-agent/agent-common/src/test/java/org/apache/inlong/agent/db/TestRocksDbImp.java
inlong-common/src/main/java/org/apache/inlong/common/db/CommandEntity.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/DataConfig.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/SourceListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/SourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/SourceResponse.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/StreamSourceEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractStreamSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/SourceSnapshotOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql

Fixes #3293
Add version controller for stream source.

[INLONG-3293][Manager] Add version controller for stream source

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/impl/InnerInlongManagerClientTest.java

Fixes #3294 
Fix protocol of client and manager is inconsistent

[INLONG-3294][Manager] Fix protocol of client and manager is inconsistent

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/CommandDb.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobWrapper.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskWrapper.java

Fixes #3297 
[INLONG-3297][Agent] Add version control in Agent CommandEntity
[INLONG-3297][Agent] Add version control in Agent CommandEntity

[INLONG-3297][Agent] Add version control in Agent CommandEntity

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongStreamServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractStreamSourceOperation.java

Fixes #3310 
*(or)*
*(or)*
*(example:)* …

[INLONG-3310][Manager] Optimize Pessimistic Lock for select stream sources

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskWrapper.java

Fixes #3304
[INLONG-3304][Agent] Agent reader cost too much cpu
[INLONG-3304][Agent] Agent reader cost too much cpu

[INLONG-3304][Agent] Agent reader cost too much cpu

---

inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/task/TestTaskWrapper.java

Fixes #3326 
Fix the unit tests for TestTaskWrapper was running too long.

[INLONG-3326][Agent] Fix the unit tests for TestTaskWrapper was running too long

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractStreamSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/SourceSnapshotOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java

Fixes #3312 
Optimize the delete operation for stream source.

[INLONG-3312][Manager] Optimize the delete operation for stream source

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java

Fixes #3323 
*(or)*
*(or)*
*(example:)* …

[INLONG-3323][Manager] Add APIs for manager client

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/TServerConstants.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/fielddef/CliArgDef.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/TopicCtrlEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/TopicDeployEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/TopicPropGroup.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsMetaConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsTopicCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsTopicDeployMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebBrokerConfHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebTopicCtrlHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebTopicDeployHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/tools/cli/CliMetaDataBRU.java
inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/TopicCtrlEntityTest.java
inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/TopicDeployEntityTest.java

[INLONG-3324][TubeMQ] Optimize CliMetaDataBRU class implementation

---

inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/CustomDateFormatDeserializationSchemaWrapper.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/serialization/CustomDateFormatSerializationSchemaWrapper.java

Fixes #3321 
*(or)*
*(or)*
*(example:)* …

[INLONG-3321][Sort] Set the correspond field in output to null if the field value in input is null

---

inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/serialization/DebeziumSerializationInfoTest.java

Fixes #3329
Fix bug of wrong class mapping of debezium serialization info

[INLONG-3329][Sort] Fix bug of wrong class mapping of debezium serialization info

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/BinlogReader.java
inlong-agent/bin/agent-env.sh

Fixes #3335 
Fix agent snapshot mode won't work and optimize jvm parameters
Fix agent snapshot mode won't work and optimize jvm parameters

[INLONG-3335][Agent] Fix agent snapshot mode won't work and optimize jvm parameters

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java

Fixes #3339 
Update source status when agent result was failed.
- M: `AgentServiceImpl`

[INLONG-3339][Manager] Update source status when agent result was failed

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodeconsumer/ConsumerInfoHolder.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebGroupConsumeCtrlHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebMasterInfoHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/tools/cli/CliMetaDataBRU.java

Fixes #3290
1. Add query method admin_query_group_info_by_topic
2. Fix some bugs found

[INLONG-3290][TubeMQ] Support query the consumption group based on the specified topic

---

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsSinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/DefaultEvent2LogItemHandler.java

Fixes #3340 
*(or)*
*(or)*
*(example:)* …

[INLONG-3340][Sort-Standalone] Fix wrong filter and overflow in ClsSink

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/SinkField.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/StreamField.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSinkTransfer.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/SinkFieldRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/SinkFieldResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/InlongStreamFieldInfo.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongStreamFieldEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/StreamSinkFieldEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongStreamFieldEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamFieldEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkFieldEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/CommonOperateService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongStreamServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/FieldInfoUtils.java
inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql

Fixes #3334 
Get source field list from stream field table for Sort.
Add is_meta_field for `InlongStreamFieldEntity` and `StreamSinkFieldEntity`.

[INLONG-3334][Manager] Get source field list from stream field table for Sort

---

inlong-tubemq/pom.xml

[INLONG-3348][TubeMQ] Update protobuf-java version to 3.19.4

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongGroupContext.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/DefaultInlongStreamBuilder.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerStreamContext.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSinkTransfer.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSourceTransfer.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/FullStreamResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/InlongStreamInfo.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/InlongStreamResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/workflow/form/GroupResourceProcessForm.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/workflow/form/UpdateGroupProcessForm.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamFieldEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/CommonOperateService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/InlongStreamService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongGroupProcessOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongStreamServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractStreamSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/listener/AbstractSourceOperateListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/PushSortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SerializationUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SourceInfoUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/StartCreateGroupProcessListener.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/InlongStreamServiceTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/source/listener/DataSourceListenerTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/thirdparty/sort/DisableZkForSortTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/workflow/WorkflowServiceImplTest.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java

[INLONG-3355][Manager] Check the source states before return group state in manager client

---

inlong-sort/sort-single-tenant/pom.xml

Fixes #2496 
*(or)*
*(or)*
*(example:)* …

[INLONG-2496][Sort] Support COS filesystem when using Hive sink

---

inlong-audit/audit-common/pom.xml
inlong-audit/audit-common/src/main/proto/AuditApi.proto
inlong-audit/audit-sdk/pom.xml
inlong-audit/pom.xml

Fiexs:#2408
Upgrade audit pb version to 3.19.4

[INLONG-2408][Audit] Upgrade audit pb version to 3.19.4

---

inlong-dashboard/src/components/AccessHelper/DataStorageEditor/DetailModal.tsx
inlong-dashboard/src/components/AccessHelper/DataStorageEditor/Editor.tsx
inlong-dashboard/src/components/AccessHelper/FieldsConfig/dataFields.tsx
inlong-dashboard/src/components/MetaData/StorageClickhouse.tsx
inlong-dashboard/src/components/MetaData/StorageHive.tsx
inlong-dashboard/src/components/MetaData/index.ts
inlong-dashboard/src/pages/AccessCreate/DataStream/config.tsx
inlong-dashboard/src/pages/AccessDetail/DataStorage/index.tsx
inlong-dashboard/src/pages/AccessDetail/DataStream/config.tsx

[INLONG-3341][Dashboard] Sink supports plug-in configuration

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/SinkFieldRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/SinkFieldResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/InlongStreamFieldInfo.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongStreamFieldEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/StreamSinkFieldEntity.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamFieldEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkFieldEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/FieldInfoUtils.java
inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql

Fixes #3367 
*(or)*
*(or)*
*(example:)* …

[INLONG-3367][Manager] Support custom field format

---

inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/transformation/Transformer.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/DebeziumToCanalITCase.java

Fixes #3372 
*(or)*
*(or)*
*(example:)* …

[INLONG-3372][Sort] Fix the binlog type is always INSERT when the output format is canal

---

inlong-common/src/main/java/org/apache/inlong/common/enums/ComponentTypeEnum.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/PulsarSink.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongClientImpl.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupPageRequest.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongGroupServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DBCollectorController.java

Fixes #3369 
*(or)*
*(or)*
*(example:)* …

[INLONG-3369][Manager] Add streamsource in group/list Api

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/SinkField.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/StreamField.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSinkTransfer.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamTransfer.java

Fixes #3376 
*(or)*
*(or)*
*(example:)* …

[INLONG-3376][Manager] Support custom field format in client

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/AgentUtils.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskWrapper.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/task/TestTaskWrapper.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/BinlogReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/TextFileReader.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/TestFileAgent.java

Fixes #3381 
[INLONG-3381][Agent] Agent wait one minute for dataproxy to prepare topic config
[INLONG-3381][Agent] Agent wait one minute for dataproxy to prepare topic config

[INLONG-3381][Agent] Agent wait one minute for dataproxy to prepare topic config

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/FieldInfoUtils.java

Fixes #3383 
*(or)*
*(or)*
*(example:)* …

[INLONG-3383][Manager] Fix the null pointer caused by sink field not configured with source field

---

inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/filesystem/Bucket.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/filesystem/BucketFactory.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/filesystem/Buckets.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/filesystem/DefaultBucketFactoryImpl.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/filesystem/StreamingFileSink.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/HiveWriter.java

Fixes #3396 
*(or)*
*(or)*
*(example:)* …

[INLONG-3396][Sort] Support multiple dataflow to write the same hive table

---

inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql

Fixes #3397 
Fix SQL script error

[INLONG-3397][Manager] Fix sql script error when saving sink fields

---

inlong-dashboard/src/components/AccessHelper/FieldsConfig/dataFields.tsx
inlong-dashboard/src/pages/AccessCreate/DataStream/config.tsx
inlong-dashboard/src/pages/AccessCreate/DataStream/helper.ts
inlong-dashboard/src/pages/AccessCreate/DataStream/index.tsx
inlong-dashboard/src/pages/AccessDetail/DataStream/StreamItemModal.tsx
inlong-dashboard/src/pages/AccessDetail/DataStream/config.tsx
inlong-dashboard/src/pages/AccessDetail/DataStream/index.tsx

[INLONG-3394][Dashboard] Remove the stream owner parameter and manage it uniformly by group

---

inlong-dashboard/src/components/FormGenerator/plugins.tsx

[INLONG-3390][Dashboard] Text form support date and array dataType

---

docker/kubernetes/templates/audit-statefulset.yaml
inlong-audit/conf/application.properties
inlong-manager/manager-web/src/main/resources/application-dev.properties
inlong-manager/manager-web/src/main/resources/application-prod.properties
inlong-manager/manager-web/src/main/resources/application-test.properties

Agent mysql connection should set allowPublicKeyRetrieval to true to support mysql 8.0
Fixes #2826 
*Agent mysql connection should set allowPublicKeyRetrieval to true to support mysql 8.0*

[INLONG-2826][Manager][Agent] Set allowPublicKeyRetrieval to true to support MySQL 8.x

---

inlong-sort-standalone/conf/es/SortClusterConfig.conf
inlong-sort-standalone/conf/es/sid_es_v3.conf
inlong-sort-standalone/conf/hive/SortClusterConfig.conf
inlong-sort-standalone/conf/hive/sid_hive_inlong6th_v3.conf

Fixes #3408 
*(or)*
*(or)*
*(example:)* …

[INLONG-3408][Sort-Standalone] Replace IP and authentication in configuration example

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/DebeziumDeserializationInfo.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/DebeziumToCanalITCase.java

Fixes #3414 
*(or)*
*(or)*
*(example:)* …

[INLONG-3414][Sort] Set the default value of field includeUpdateBefore for DebeziumDeserializationInfo

---

docker/docker-compose/docker-compose.yml
inlong-distribution/distribution.xml

[INLONG-3412][Docker] optimize the docker-compose for registering component

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/sink/HiveSink.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSinkTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ErrorCodeEnum.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hive/HivePartitionField.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hive/HiveSinkDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hive/HiveSinkRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hive/HiveSinkResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/CommonOperateService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/hive/HiveStreamSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/hive/DefaultHiveTableOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SinkInfoUtils.java

Fixes #3405 
*(or)*
*(or)*
*(example:)* …

[INLONG-3405][Manager] Support generic partition configuration for Hive sink

---

README.md

[INLONG-3420][Improve]Update links in README.md file

---

inlong-dashboard/src/components/MetaData/DataSourcesFile.ts
inlong-dashboard/src/locales/cn.json
inlong-dashboard/src/locales/en.json

[INLONG-2794][Dashboard] Manager website should not display port when adding agent job

---

inlong-dashboard/src/components/MetaData/DataSourcesBinLog.ts
inlong-dashboard/src/locales/cn.json
inlong-dashboard/src/locales/en.json

[INLONG-3423][Dashboard] Add user and password config to binlog source

---

inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJsonSerializationSchema.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/FieldMappingTransformer.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/deserialization/DeserializationFunctionTest.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/deserialization/FieldMappingTransformerTest.java

Fixes #3426 
*(or)*
*(or)*
*(example:)* …

[INLONG-3426][Sort] Unify the value of binlog event type

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebOtherInfoHandler.java

[INLONG-3429][TubeMQ] Add missing adminQueryMasterVersion method

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/RocksDbImp.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
inlong-agent/bin/agent-env.sh
inlong-agent/conf/agent.properties
inlong-common/src/main/java/org/apache/inlong/common/enums/PullJobTypeEnum.java

Fixes #3349 
[INLONG-3353][Agent] Agent add limitation for job number
[INLONG-3353][Agent] Agent add limitation for job number

[INLONG-3349][Agent] Agent add limitation for job number

---

inlong-tubemq/tubemq-manager/sql/apache_tube_manager.sql
inlong-tubemq/tubemq-manager/src/main/assembly/assembly.xml
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/entry/TopicEntry.java
inlong-tubemq/tubemq-manager/src/main/resources/application.properties

Fixes #3445 
remove hibernate for tube manager
remove hibernate for tube manager

[INLONG-3445][TubeMQ] Remove the hibernate dependency for the tube manager

---

inlong-common/src/main/java/org/apache/inlong/common/enums/DataTypeEnum.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/TaskResult.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/StreamField.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ErrorCodeEnum.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/SinkFieldBase.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/SinkFieldRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hive/HivePartitionField.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/InlongStreamFieldInfo.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongStreamFieldEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamFieldEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/hive/HiveStreamSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractStreamSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/hive/DefaultHiveTableOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SerializationUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SinkInfoUtils.java
inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql

Fixes #3428 
Set the default value and code refactor.

[INLONG-3428][Manager] Set the default value and code refactor

---

inlong-tubemq/tubemq-manager/pom.xml

Fixes #3453 
[INLONG-3453][Tube] remove hibernate for tube manager
[INLONG-3453][Tube] remove hibernate for tube manager

[INLONG-3453][TubeMQ] Remove hibernate for tube manager

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java

Fixes #3448 
[INLONG-3448][Manager] Limit the number of Agent pull tasks.

[INLONG-3448][Manager] Limit the number of Agent pull tasks

---

inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/task/TestTaskWrapper.java

Fixes #<xyz>
*(or)*
*(or)*
*(example:)* …

[INLONG-3463][Agent] Fix unit test of TestTaskWrapper

---

inlong-agent/pom.xml

Fixes #3466 
[INLONG-3466][Agent] Agent remove protobuf
[INLONG-3466][Agent] Agent remove protobuf
*(or)*
*(or)*
*(example:)* …

[INLONG-3466][Agent] Agent remove protobuf dependency
