inlong-manager/manager-dao/pom.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/DBCollectorTaskServiceImpl.java

Fixes #3454 
Remove the nimbusds dependency, refactor log info for db collector.

[INLONG-3454][Manager] Remove the nimbusds dependency, refactor log info for db collector

---

inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/HiveSinkHelper.java
inlong-sort/sort-connectors/src/test/java/org/apache/inlong/sort/flink/hive/HiveSinkHelperTest.java
inlong-sort/sort-connectors/src/test/java/org/apache/inlong/sort/flink/hive/formats/orc/OrcBulkWriterTest.java
inlong-sort/sort-connectors/src/test/java/org/apache/inlong/sort/flink/hive/formats/parquet/ParquetBulkWriterTest.java

Fixes #3457 
*(or)*
*(or)*
*(example:)* …

[INLONG-3457][Sort] Exclude partition fields when writing data with parquet/orc format to hive

---

inlong-tubemq/pom.xml
inlong-tubemq/tubemq-server/pom.xml

[INLONG-3477][TubeMQ] Remove direct reference to log4j1.x

---

inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/formats/orc/OrcBulkWriterUtil.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/formats/orc/RowVectorizer.java

Fixes #3483
Fix bug of wrong date data in ORC formatted output

[INLONG-3483][Sort] Fix bug of wrong date data in ORC formatted output

---

inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/formats/parquet/ParquetRowWriter.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/formats/parquet/ParquetSchemaConverter.java
inlong-sort/sort-connectors/src/test/java/org/apache/inlong/sort/flink/hive/formats/parquet/ParquetBulkWriterTest.java

Fixes #3486 
*(or)*
*(or)*
*(example:)* …

[INLONG-3486][Sort] Timestamp or Date type are written wrongly when using Parquet format

---

inlong-dashboard/src/pages/AccessDetail/DataStream/StreamItemModal.tsx
inlong-dashboard/src/pages/AccessDetail/DataStream/index.tsx
inlong-dashboard/src/router.tsx

[INLONG-3498][Dashboard] Adapt manager streams update API

---

inlong-dashboard/package-lock.json
inlong-dashboard/pom.xml

[INLONG-3496][Dashboard] Update node version

---

inlong-dashboard/.npmrc

[INLONG-3492][Dashboard] Initialize a npmrc file

---

inlong-sort-standalone/pom.xml
inlong-sort-standalone/sort-standalone-common/pom.xml
inlong-sort-standalone/sort-standalone-source/pom.xml

[INLONG-3418][Sort-Standalone] Upgrade protobuf version to 3.19.4
Fixes #3418 
*(or)*
*(or)*
*(example:)*
- If yes, how is the feature documented? (not applicable / docs / JavaDocs …

[INLONG-3418][Sort-Standalone] Upgrade protobuf version to 3.19.4

---

inlong-audit/pom.xml
inlong-tubemq/pom.xml
inlong-tubemq/tubemq-manager/pom.xml
licenses/inlong-tubemq/licenses-server/LICENSE
licenses/inlong-tubemq/licenses-server/NOTICE

Fixes #3503
Security issues
*(or)*
*(or)*
*(example:)* …

[INLONG-3503] upgrade spring due to CVE

---

bin/inlong-daemon
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ThirdPartyClusterServiceImpl.java

Fixes #3510
*(or)*
*(or)*
*(example:)* …

[INLONG-3510][Manager] return empty object when not found any inlong group with success status

---

inlong-dashboard/src/components/MetaData/DataSourcesBinLog.ts
inlong-dataproxy/conf/dataproxy-pulsar.conf
inlong-dataproxy/conf/dataproxy-tube.conf
inlong-dataproxy/dataproxy-source/src/main/resources/dataproxy-pulsar.conf

Fixes #3520
*(or)*
*(or)*
*(example:)* …

[INLONG-3520][DataProxy] Unify the data directory for the dataproxy

---

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/SortClientImpl.java

[INLONG-3450]Sort-SDK upgrade pb version to 3.x
Fixes #3450
*(or)*
*(or)*
*(example:)* …

[INLONG-3450][SDK] Sort-SDK change ack log from info to debug

---

inlong-manager/manager-docker/manager-docker.sh
inlong-manager/manager-plugins/pom.xml
inlong-manager/manager-plugins/src/main/assembly/assembly.xml
inlong-manager/manager-web/assembly.xml
inlong-manager/manager-web/pom.xml
inlong-manager/pom.xml

Fixes #3526
*(or)*
*(or)*
*(example:)* …

[INLONG-3526][Manager] Optimize packaging of the default plugins

---

docker/kubernetes/templates/audit-statefulset.yaml
inlong-manager/manager-client-examples/pom.xml
inlong-manager/manager-web/src/main/resources/application-dev.properties
inlong-manager/manager-web/src/main/resources/application-prod.properties
inlong-manager/manager-web/src/main/resources/application-test.properties
inlong-manager/pom.xml

Fixes #3535 
Update JDBC configs and maven pom files.

[INLONG-3535][Manager] Update JDBC configs and maven pom files

---

SECURITY.md

[INLONG-3540][InLong] Add SECURITY.md file

---

inlong-sort/sort-single-tenant/pom.xml
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/Entrance.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/DeserializationFunction.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/utils/CommonUtils.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/DebeziumToCanalITCase.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/WholeDBMigrationITCase.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/deserialization/DeserializationFunctionTest.java

Fixes #3546 
*(or)*
*(or)*
*(example:)* …

[INLONG-3546][Sort] Support reporting metrics by audit-sdk in sort-single-tenant

---

inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/Binlog2KafkaExample.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/sink/KafkaSink.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSinkTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/Constant.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/kafka/KafkaSinkDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/kafka/KafkaSinkListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/kafka/KafkaSinkRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/kafka/KafkaSinkResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/InlongStreamService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongStreamServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SinkInfoUtils.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/sink/KafkaStreamSinkServiceTest.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java

Fixes #3537 
Remove unused APIs and change Kafka sink params.

[INLONG-3537][Manager] Remove unused APIs and change Kafka sink params

---

inlong-sort/pom.xml
inlong-sort/sort-connectors/pom.xml
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/hive/formats/TextRowWriter.java
inlong-sort/sort-connectors/src/test/java/org/apache/inlong/sort/flink/hive/formats/TextRowWriterTest.java

Fixes #3523 
*(or)*
*(or)*
*(example:)* …

[INLONG-3523][Sort] Remove lzo-core dependency

---

inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkService.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/IntergrationTaskRunner.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/dto/FlinkInfo.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/DeleteSortListener.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/RestartSortListener.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/StartupSortListener.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/SuspendSortListener.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/util/FlinkUtils.java
inlong-manager/manager-plugins/src/test/java/org/apache/inlong/manager/plugin/listener/DeleteSortListenerTest.java
inlong-manager/manager-plugins/src/test/java/org/apache/inlong/manager/plugin/listener/RestartSortListenerTest.java
inlong-manager/manager-plugins/src/test/java/org/apache/inlong/manager/plugin/listener/SuspendSortListenerTest.java

Fixes #3538
*(or)*
*(or)*
*(example:)* …

[INLONG-3538][Manager] Adjust mode of getting sort URL

---

inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/node/request/OnlineOfflineBrokerReq.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/node/request/ReloadBrokerReq.java

Fixes https://github.com/apache/incubator-inlong/issues/3568
*(or)*
*(or)*
*(example:)* …

[INLONG-3568][TubeMQ] Nodes realize batch online, offline, and reloading

---

inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkService.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/IntergrationTaskRunner.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/ManagerFlinkTask.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/DeleteSortListener.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/RestartSortListener.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/StartupSortListener.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/SuspendSortListener.java
inlong-manager/manager-plugins/src/test/java/org/apache/inlong/manager/plugin/listener/SuspendSortListenerTest.java

Fixes #3565
*(or)*
*(or)*
*(example:)* …

[INLONG-3565][Manager] Unified the interface for flink plugin

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/PulsarSink.java

Fix Repeated registration jmx metric bean exception.
Fixes #3031

[INLONG-3031][Dataproxy] Fix Repeated registration jmx metric bean exception

---

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/metrics/SortSdkPrometheusMetricListener.java

[INLONG-3576]sort sdk support multi type for prometheusMetric
Fixes #3576
*(or)*
*(or)*
*(example:)* …

[INLONG-3576][SDK] Support multi type for prometheus metric

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/FileJob.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/source/AgentFileSource.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSourceTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/Constant.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SourceType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/file/FileSourceDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/file/FileSourceListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/file/FileSourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/file/FileSourceResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceRequest.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractStreamSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/file/FileStreamSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaStreamSourceOperation.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/AgentServiceTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/source/StreamSourceServiceTest.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/CommonDBServerController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/CommonFileServerController.java

Fixes #3550 
*(or)*
*(or)*
*(example:)* …

[INLONG-3550][Manager] Support File source in client and server

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSourceTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/SourceRequest.java

Fixes #3580 
*(or)*
*(or)*
*(example:)* …

[INLONG-3580][Manager] Remove agentIp in source request

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CommonConstants.java
inlong-agent/agent-plugins/pom.xml
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/AbstractReader.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/MiniAgent.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestTextFileReader.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/utils/TestUtils.java
inlong-agent/pom.xml

Fixes #3076 
*(or)*
*(or)*
*(example:)* …

[INLONG-3076][Agent] MalformedObjectNameException occurred in unit tests

---

inlong-manager/pom.xml

Fixes #3534
spring-boot transitively brings in the real fix - tidier to explicitly bring in fixed version of spring
*(or)*
*(or)*
*(example:)* …

[INLONG-3534][Manager] update spring version due to cve

---

inlong-manager/pom.xml

Fixes #3504
*(or)*
*(or)*
*(example:)* …

[INLONG-3504][Manager] upgrade to jackson without cve

---

inlong-manager/manager-web/bin/managerctl
inlong-manager/manager-web/bin/startup.sh
inlong-manager/manager-web/pom.xml
inlong-manager/manager-web/src/main/resources/application.properties
inlong-manager/pom.xml
pom.xml

Fixes #3596
*(or)*
*(or)*
*(example:)* …

[INLONG-3596][Manager] Update the dependency

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/Constant.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SinkType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SourceType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/SinkFieldBase.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/ck/ClickHouseSinkRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/ck/ClickHouseSinkResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hive/HiveSinkRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hive/HiveSinkResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/iceberg/IcebergSinkRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/iceberg/IcebergSinkResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/kafka/KafkaSinkRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/kafka/KafkaSinkResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceDTO.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/StreamSinkFieldEntity.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/ck/ClickHouseSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/hive/HiveSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/iceberg/IcebergSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/kafka/KafkaSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/binlog/BinlogSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/file/FileSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/hive/CreateHiveTableEventSelector.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SinkInfoUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/stream/CreateStreamWorkflowDefinition.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/sink/ClickHouseStreamSinkServiceTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/sink/HiveStreamSinkServiceTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/sink/IcebergStreamSinkServiceTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/sink/KafkaStreamSinkServiceTest.java

Fixes #3589 
Add Iceberg sink info for Sort.

[INLONG-3589][Manager] Add Iceberg sink info for Sort

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/SourceRequest.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/eventselect/DeleteProcessSelector.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/eventselect/RestartProcessSelector.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/eventselect/StartupProcessSelector.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/eventselect/SuspendProcessSelector.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/hive/CreateHiveSinkForStreamListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/hive/CreateHiveSinkListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/hive/HiveSinkEventSelector.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/mq/PulsarEventSelector.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/mq/TubeEventSelector.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/ZkDisabledEventSelector.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/ZkEnabledEventSelector.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/ServiceTaskListenerFactory.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/stream/CreateStreamWorkflowDefinition.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/thirdparty/hive/HiveSinkEventSelectorTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/workflow/WorkflowServiceImplTest.java

Fixes #3601
Should not create Hive resource when sink type is Kafka.

[INLONG-3601][Manager] Should not create Hive resource when sink type is Kafka

---

inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/source/ServerMessageHandler.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/CommonOperateService.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/deserialization/FieldMappingTransformer.java

Switch must have default branch for check style
Fixes #3623

[INLONG-3623][InLong] Switch must have default branch for check style

---

inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/cluster/ClusterController.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/cluster/request/SwitchClusterReq.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/repository/MasterRepository.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/ClusterServiceImpl.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/MasterServiceImpl.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/TubeConst.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/interfaces/MasterService.java

Fixes https://github.com/apache/incubator-inlong/issues/3621
*(example:)* …

[INLONG-3621][TubeMQ] Added cluster switching method and delete cluster support to delete master

---

.github/ISSUE_TEMPLATE/bug-report.yml

[INLONG-3614][CI] Add 1.1.0 version option for the bug report

---

inlong-manager/manager-test/src/main/resources/application-test.properties
inlong-manager/manager-web/bin/restart.sh
inlong-manager/manager-web/bin/shutdown.sh
inlong-manager/manager-web/bin/startup.sh
inlong-manager/manager-web/src/main/resources/application.properties
inlong-manager/manager-web/src/main/resources/log4j2.xml

Fixes #3642 
Update start script and log configuration.

[INLONG-3642][Manager] Update start script and log configuration

---

inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/MiniAgent.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/TestFileAgent.java

[INLONG-3629][Agent] Improve TestFileAgent unit test

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/HttpManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java

Fix bug Avoid printing a lot of logs.
Fixes #3653

[INLONG-3653][Agent] Avoid printing a lot of logs

---

inlong-dashboard/src/components/AccessHelper/FieldsConfig/dataFields.tsx
inlong-dashboard/src/components/MetaData/DataSourcesFile.ts
inlong-dashboard/src/components/MetaData/StorageClickhouse.tsx

Fixes #3660 
Change visible for dataType and dataSeparator.

[INLONG-3660][Dashboard] Change visible for dataType and dataSeparator

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java

Fixes #3650 
Fixes #3650 
Agent fix timeoffset npe

[INLONG-3650][Agent] Agent fix timeoffset npe

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/util/SerializationUtils.java

Fixes #3662 
Disable ZooKeeper by default and deserialize file source from stream info.

[INLONG-3662][Manager] Disable ZooKeeper by default and deserialize file source from stream info

---

inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/topic/TopicWebController.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/topic/request/SetPublishReq.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/topic/request/SetSubscribeReq.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/ClusterServiceImpl.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/MasterServiceImpl.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/TubeConst.java

Fixes https://github.com/apache/incubator-inlong/issues/3633
*(example:)* …

[INLONG-3633][TubeMQ] Add topic publish and subscribe methods, cluster modification add parameters

---

inlong-dashboard/src/components/AccessHelper/FieldsConfig/dataFields.tsx
inlong-dashboard/src/locales/cn.json
inlong-dashboard/src/locales/en.json

Fixes #3684 
Add tooltip for the stream data type.
Remove unused syncType param.

[INLONG-3684][Dashboard] Add tooltip for the stream data type

---

inlong-agent/agent-common/pom.xml
inlong-agent/agent-plugins/pom.xml
inlong-agent/pom.xml
inlong-audit/audit-proxy/pom.xml
inlong-audit/audit-store/pom.xml
inlong-audit/pom.xml
inlong-dataproxy/dataproxy-source/pom.xml
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/SimpleHttpSource.java
inlong-dataproxy/pom.xml
inlong-manager/manager-web/pom.xml
inlong-sort-standalone/pom.xml
inlong-tubemq/pom.xml
inlong-tubemq/tubemq-client/pom.xml
pom.xml

Tidy up dependencies
Fixes #3672

[INLONG-3672][InLong] Tidy up dependencies

---

inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestBinlogOffsetManager.java

[INLONG-3652][Agent] Improve TestBinlogOffsetManager unit test

---

inlong-agent/bin/agent.sh

[INLONG-3692][Agent] Refactor the stop logic

---

inlong-manager/manager-client-tools/pom.xml
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CommandToolMain.java
inlong-manager/manager-client-tools/src/test/java/org/apache/inlong/manager/client/cli/TestCommand.java
inlong-manager/manager-web/bin/managerctl

[INLONG-3701][Manager] Decrease the size of manager client tools

---

inlong-agent/agent-plugins/pom.xml

[INLONG-3699][Agent] Exclude mysql-connector-java

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/SourceSnapshotOperation.java

[INLONG-3704][Manager] Change the log level for status report

---

inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/AutoPush2HiveExample.java
inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/Binlog2KafkaExample.java
inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/File2HiveExample.java
inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/Kafka2HiveExample.java

[INLONG-3697][Manager] Replenish manager client examples

---

bin/inlong-daemon
inlong-agent/agent-release/assembly.xml
inlong-audit/audit-release/assembly.xml
inlong-dataproxy/dataproxy-dist/src/main/assembly/assembly.xml
inlong-distribution/distribution.xml
inlong-manager/manager-web/assembly.xml
inlong-sort/sort-connectors/pom.xml
inlong-sort/sort-single-tenant/pom.xml
inlong-tubemq/tubemq-server/src/main/assembly/assembly.xml

[INLONG-3708][Manager] Make the built package under windows can run

---

inlong-manager/manager-common/pom.xml
inlong-manager/manager-web/pom.xml

[INLONG-3712][Manager] Exclude validation-api to solve the dependency  conflict

---

inlong-dashboard/src/pages/AccessCreate/DataStream/helper.ts

[INLONG-3721][Dashboard] Submit data when source is AUTO_PUSH

---

CHANGES.md

[INLONG-3613][Doc] Update changes log for 1.1.0

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/SourceSnapshotOperation.java
inlong-manager/manager-web/src/main/resources/application-dev.properties
inlong-manager/manager-web/src/main/resources/log4j2.xml

Fixes #3720 
[INLONG-3720][Manager] Update log4j2 configuration to make the log more readable.

[INLONG-3720][Manager] Update log4j2 configuration to make the log more readable

---

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderHandler.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderManager.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/util/Decoder.java

ByteBuf release has leaks
Fixes #3718

[INLONG-3718][Audit] ByteBuf release has leaks

---

inlong-manager/manager-client-tools/pom.xml
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CommandDescribe.java
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CommandList.java
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CommandUtil.java
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/GroupInfo.java
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/SinkInfo.java
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/SourceInfo.java
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/StreamInfo.java

Fixes #3679 
Output results in tabular format with adaptive column width.

[INLONG-3679][Manager] Optimize managerctl result display

---

inlong-manager/manager-service/pom.xml

[INLONG-3729][Manager] Remove unused hadoop dependency

---

inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CommandDescribe.java
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CommandList.java
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CommandUtil.java
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/enums/InlongGroupState.java
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/util/PrintUtil.java

Fixes #3731 
1、optimize `printUtil`
2、abstract state , support `CREATE`, `REJECTED`, `INITIALIZING`, `OPERATING`, `STARTED`, `FAILED`, `STOPPED`, `FINISHED`, `DELETED`
`managerctl list group -s {state}`

[INLONG-3731][Manager] Abstract state and optimization printUtil

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongGroupServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/thirdparty/sort/CreateSortConfigListener.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/InlongGroupProcessOperationTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/source/listener/DataSourceListenerTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/thirdparty/sort/DisableZkForSortTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/workflow/WorkflowServiceImplTest.java

Fixes #3743 
[INLONG-3743][Manager] Update status of InlongGroup after workflow ended.

[INLONG-3743][Manager] Update status of InlongGroup after workflow ended

---

inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkService.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/dto/FlinkConfig.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/enums/Constants.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/util/FlinkConfiguration.java
inlong-manager/manager-plugins/src/main/resources/flink-sort-plugin.properties

…proxy.hosts
Fixes #3751 
*(example:)*

[INLONG-3751][Manager] Add configuration for plugins to support metrics

---

inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkService.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/IntegrationTaskRunner.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/dto/FlinkConfig.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/enums/Constants.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/util/FlinkConfiguration.java
inlong-manager/manager-plugins/src/main/resources/flink-sort-plugin.properties

[INLONG-3753][Manager] Add configuration for plugins to support metrics

---

inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkService.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/IntegrationTaskRunner.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/dto/FlinkConfig.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/enums/Constants.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/util/FlinkConfiguration.java
inlong-manager/manager-plugins/src/main/resources/flink-sort-plugin.properties

[INLONG-3753][Manager] Add configuration item of drain

---

inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJsonDecodingFormat.java
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/debezium/DebeziumJsonDecodingFormat.java

[INLONG-3756][Sort] Fix the unreported exception X

---

.github/workflows/ci_docker.yml

fixes: #3759
Fix docker image push trigger condition in master branch.
Fix docker image push trigger condition in master branch.

[INLONG-3759][CI] Fix docker image push trigger condition in master branch

---

inlong-manager/manager-dao/pom.xml
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkOperation.java

Fixes #3761 
Sleep 5 seconds when Flink job was not running.

[INLONG-3761][Manager] Sleep 5 seconds when Flink job was not running

---

inlong-tubemq/tubemq-client/src/test/java/org/apache/inlong/tubemq/client/consumer/MessageFetchManagerTest.java
inlong-tubemq/tubemq-client/src/test/java/org/apache/inlong/tubemq/client/factory/TubeBaseSessionFactoryTest.java
inlong-tubemq/tubemq-client/src/test/java/org/apache/inlong/tubemq/client/factory/TubeMultiSessionFactoryTest.java
inlong-tubemq/tubemq-client/src/test/java/org/apache/inlong/tubemq/client/factory/TubeSingleSessionFactoryTest.java
inlong-tubemq/tubemq-client/src/test/java/org/apache/inlong/tubemq/client/producer/RoundRobinPartitionRouterTest.java
inlong-tubemq/tubemq-connectors/tubemq-connector-flume/src/test/java/org/apache/flume/sink/tubemq/TestTubemqSink.java

[INLONG-3763][TubeMQ] Unit test of MessageFetchManagerTest failed

---

README.md

[INLONG-3767][Doc] Add supported data nodes guide for InLong

---

inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CommandList.java
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/enums/InlongGroupState.java

Fixes #3769 
Fix the bug of failing to run list group
`managerctl list group`

[INLONG-3769][Manager] Fix the bug of failing to run list group

---

pom.xml

Fixes #3780
* security issue
* pom change
*(example:)*

[INLONG-3780][CVE] upgrade postgresql due to cve

---

inlong-sort/sort-common/pom.xml
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/BuiltInFieldInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/FieldInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/FunctionParam.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/BuiltInFieldInfoTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/FieldInfoTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/kafka/KafkaSinkInfoTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/FieldMappingRuleTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/TransformationInfoTest.java

[INLONG-3778][Sort] FieldInfo enhanced to support transform

---

inlong-manager/manager-web/src/main/resources/application-dev.properties
inlong-manager/manager-web/src/main/resources/application-prod.properties
inlong-manager/manager-web/src/main/resources/application-test.properties
inlong-manager/manager-web/src/main/resources/log4j2.xml

Fixes #3782 
[INLONG-3782][Manager] Improve the log configuration.

[INLONG-3782][Manager] Improve the log configuration

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/ComareOperator.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/CompareOperator.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/LogicOperator.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/MultiValueCompareOperator.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/Operator.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/SingleValueCompareOperator.java

[INLONG-3786][Sort] Add Operator interface and derived interface definitions to support transform

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/FilterFunction.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/Function.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/GroupTimeWindowFunction.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/TimeWindowFunction.java

[INLONG-3787][Sort] Add Function interface and derived interface definitions to support transform

---

CONTRIBUTING.md
licenses/inlong-manager/LICENSE

[INLONG-3843][Doc] fix the invalid link

---

inlong-audit/audit-docker/audit-docker.sh

[INLONG-3853][Audit] fix the docker images script bug

---

inlong-dashboard/src/pages/AccessCreate/index.tsx
inlong-dashboard/src/pages/AccessDetail/index.tsx

[INLONG-3851][Dashboard] Unify the naming of data streams

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/UserTypeEnum.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupPageRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/user/UserRoleCode.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/UserServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/WebAuthorizingRealm.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/config/ControllerExceptionHandler.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/ClusterController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/UserController.java

Fixes #3673 
Improve the role verification module code and add `@RequireRoles()` annotation in some sensitive URL interface

[INLONG-3673][Manager] Support URL permission access control according to user role

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/ExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/LoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/MySqlExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/KafkaLoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/transform/TransformNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/KafkaLoadNodeTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/MySqlExtractNodeTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/NodeBaseTest.java

[INLONG-3788][Sort] Add Node interface and derived interface definitions to support transform

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/InlongStreamPageRequest.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamEntityMapper.xml
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java

[INLONG-3858][Manager] The other admin role can not list all inlong group info and stream info

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/GroupInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/StreamInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/LoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/transform/TransformNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/GroupInfoTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/StreamInfoTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/KafkaLoadNodeTest.java

[INLONG-3800][Sort] Add GroupInfo and StreamInfo definition to support transform

---

inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CommandToolMain.java

[INLONG-3876][Manager] Fix the managerctl argument parsing bug

---

inlong-tubemq/tubemq-manager/pom.xml

Fixes https://github.com/apache/incubator-inlong/issues/3869
*(example:)* …

[INLONG-3869][TubeMQ] Remove hibernete dependency for tube manager

---

pom.xml

Fixes #3504
current master versions are of sync
*(example:)*

[INLONG-3504][POM] Keep jackson versions consistent

---

inlong-audit/bin/store-start.sh

[INLONG-3895][Audit] Fix the audit store startup script error

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/Function.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/FunctionParam.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/function/RegexpReplaceFirstFunction.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/function/RegexpReplaceFunction.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/function/RegexpReplaceFirstFunctionTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/transformation/function/RegexpReplaceFunctionTest.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/function/RegexpReplaceFirstFunction.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/function/RegexpReplaceFirstFunctionTest.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/function/RegexpReplaceFunctionTest.java

[INLONG-3899][Sort] Add string regexp replace support for transform

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/KafkaConstant.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/enums/ScanStartupMode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/ExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/NodeBaseTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNodeTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/MySqlExtractNodeTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/KafkaLoadNodeTest.java

Fixes #3885 
Add KafkaExtractNode supporting
Add KafkaExtractNode class and test class 
refactor test package

[INLONG-3885][Sort] Add KafkaExtractNode supporting

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/CascadeFunction.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/function/CascadeFunctionWrapper.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/function/RegexpReplaceFirstFunction.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/function/RegexpReplaceFunction.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/function/CascadeFunctionWrapperTest.java

[INLONG-3839][Sort] Add cascade function support for transform

---

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClientConfig.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/QueryConsumeConfigImpl.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/pulsar/InLongPulsarFetcherImpl.java
inlong-sort-standalone/bin/sort-stop.sh
inlong-sort-standalone/pom.xml
inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/SortClusterConfigHolder.java
inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/loader/ClassResourceQueryConsumeConfig.java
inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/loader/ClassResourceSortClusterConfigLoader.java
inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/loader/ManagerSortClusterConfigLoader.java
inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/metrics/MetricListenerRunnable.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsSinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsChannelWorker.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/hive/HiveSink.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/hive/HiveSinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/DefaultEvent2KafkaRecordHandler.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/IEvent2KafkaRecordHandler.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaFederationSinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaIdConfig.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaProducerCluster.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaProducerFederation.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/DefaultEvent2PulsarRecordHandler.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/IEvent2PulsarRecordHandler.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarFederationSinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarIdConfig.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarProducerCluster.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarProducerFederation.java
inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsCallbackListener.java
inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsOutputChannel.java

[INLONG-3773][Sort-Standalone] Support configurable handler to transform data of Kafka

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongStreamServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ThirdPartyClusterServiceImpl.java

[INLOG-3915][Manager] Fix missing entity delete flag assignment

---

inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/cluster/ClusterController.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/node/request/BatchAddTopicReq.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/node/request/BrokerSetReadOrWriteReq.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/topic/TopicWebController.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/NodeServiceImpl.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/interfaces/NodeService.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/tube/AddTopicRequest.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/tube/IpIdRelation.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/tube/TopicConf.java

Fixes https://github.com/apache/incubator-inlong/issues/3691
*(example:)* …

[INLONG-3691][TubeMQ] Improve topic adding method and broker replication method and modify broker publish and subscribe parameters

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/BuiltInFieldInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/transform/DistinctNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/transform/TransformNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/OrderDirection.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/transform/DistinctNodeTest.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/parser/impl/FlinkSqlParser.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/parser/result/FlinkSqlParseResult.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/DistinctNodeSqlParseTest.java

[INLONG-3841][Sort] Add distinct support based time column for transform

---

README.md

[INLONG-3930][Doc] Add more deployment and development guides in Readme

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/source/KafkaSource.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/source/MySQLBinlogSource.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSourceTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaOffset.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/ExtractNodeUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/TransformNodeUtils.java

[INLONG-3920][Manager] Add primary key in Binlog source

---

.github/workflows/ci_build.yml
inlong-dashboard/pom.xml

Fixes #3938
Remove module cache to prevent build failed

[INLONG-3938][Dashboard] Remove module cache and update dependency

---

inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/parser/impl/FlinkSqlParser.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/FullOuterJoinSqlParseTest.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/InnerJoinRelationShipSqlParseTest.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/LeftOuterJoinSqlParseTest.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/RightOuterJoinSqlParseTest.java

[INLONG-3836][Sort] Add join support for transform

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Constants.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/Entrance.java

[INLONG-3829][Sort] Optimize the sort entrance program to support lightweight

---

inlong-audit/audit-proxy/src/test/java/org/apache/inlong/audit/sink/PulsarSinkTest.java
inlong-audit/audit-proxy/src/test/java/org/apache/inlong/audit/sink/TubeSinkTest.java
inlong-audit/audit-store/src/test/java/org/apache/inlong/audit/service/ElasticsearchServiceTest.java
inlong-audit/audit-store/src/test/java/org/apache/inlong/audit/service/consume/PulsarConsumeTest.java
inlong-audit/pom.xml
inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/config/loader/TestThirdPartyClusterConfigLoader.java
inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/sink/TestPulsarSink.java
inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/source/UdpSourceTest.java
inlong-dataproxy/pom.xml
pom.xml

Remove dependency of testng
Fixes #3935

[INLONG-3935][Audit][DataProxy] Remove dependency of testng

---

inlong-sort/sort-single-tenant/pom.xml
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/DebeziumDeserializationSchema.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/DebeziumSourceFunction.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/JsonDebeziumDeserializationSchema.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/StringDebeziumDeserializationSchema.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/Validator.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/history/FlinkJsonTableChangeSerializer.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/internal/DebeziumChangeConsumer.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/internal/DebeziumChangeFetcher.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/internal/DebeziumOffset.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/internal/DebeziumOffsetSerializer.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/internal/FlinkDatabaseHistory.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/internal/FlinkDatabaseSchemaHistory.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/internal/FlinkOffsetBackingStore.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/internal/Handover.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/internal/SchemaRecord.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/table/AppendMetadataCollector.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/table/DebeziumOptions.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/table/DeserializationRuntimeConverter.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/table/DeserializationRuntimeConverterFactory.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/table/MetadataConverter.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/utils/DatabaseHistoryUtil.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/utils/TemporalConversions.java
pom.xml

[INLONG-3924][Sort] Add mysql cdc, support multiple meta data
Fixes #3924 
[INLONG-3924][Sort] Add mysql cdc, support multiple meta data
[INLONG-3924][Sort] Add mysql cdc, support multiple meta data

[INLONG-3924][Sort] Add mysql cdc, support multiple meta data

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/mq/BlankMiddleware.java

[INLONG-3947][Manager] Support BlankMiddleware in Manage

---

inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql

[INLONG-3951][Manager] Unique index error for cluster_name in SQL file

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/commonserver/CommonDbServerPageRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/consumption/ConsumptionQuery.java
inlong-manager/manager-dao/src/main/resources/mappers/CommonDbServerEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/ConsumptionEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/CommonDBServerServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ConsumptionServiceImpl.java

[INLONG-3919][Manager] Data consumption and data source module supports access control

---

inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/master/MasterConfigTest.java

[INLONG-3975][TubeMQ] Modify the MasterConfigTest.java file to configure the incoming parameters

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/MySqlExtractNode.java
inlong-sort/sort-single-tenant/pom.xml

Fixes #3979 
Fix mysqlExtractNode options append error and conflict of flink jar and resolve conflict

[INLONG-3979][Sort] Fix mysqlExtractNode options append error

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/BuiltInFieldInfo.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/parser/impl/FlinkSqlParser.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/MetaFieldSyncTest.java

[INLONG-3831][Sort] Add meta field support for sort lightweight

---

.github/workflows/ci_stable.yml

Fixes: #3971
Add stable workflow.
For more information, please check out https://github.com/actions/stale
- `.github/workflows/ci_stable.yml`

[INLONG-3971][CI] Add stable workflow

---

.github/labeler.yml

fixes: #3818 
Improve pull request labeler configuration
- `.github/labeler.yml`

[INLONG-3818][CI] Improve pull request labeler configuration

---

.github/dependabot.yml

Fixes: #3995
Improve Denpendabot configuration. Make it trigger less often.
- `weekly` --> `monthly`
- decrease the `open-pull-requests-limit`

[INLONG-3995][GitHub] Improve Denpendabot configuration

---

.github/labeler.yml

Fixes: #3998
Improve labeler workflow with `docker`, `k8s` and `github` labels
- `.github/labeler.yml`

[INLONG-3998][GitHub] Improve labeler workflow with docker, k8s and github labels

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/CsvFormat.java

Fixes #4007 
It will not throw exception when have `null` value

[INLONG-4007][Sort] Modify default settings of CSV format

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/CsvFormat.java
inlong-sort/sort-formats/format-json/pom.xml
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJson.java
inlong-sort/sort-single-tenant/pom.xml
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/table/AppendMetadataCollector.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/mysql/source/config/MySqlSourceOptions.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/mysql/table/MySqlReadableMetadata.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/mysql/table/MySqlTableInlongSourceFactory.java
inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/cdc/mysql/table/MySqlTableSource.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/AllMigrateTest.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/FlinkSqlParserTest.java

Fixes #3996 
Sort support all migrate for database
Sort support all migrate for database

[INLONG-3996][Sort] Sort support all migrate for database

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/ClusterNodeRequest.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterEntityMapper.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterNodeEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterNodeEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/InlongClusterService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongClusterServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/InlongClusterServiceTest.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java

[INLONG-3946][Manager] Implement the APIs of cluster management

---

.github/workflows/ci_stable.yml

Fixes: #4024
Imrpove trigger conditons in the stable workflow
- mark issues and PRs be stable after 60 days, and close them after 30 days.

[INLONG-4024][GitHub] Imrpove trigger conditons in the stable workflow

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/FieldType.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/StreamSourceFieldEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/StreamTransformFieldEntity.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/NodeRelationShipUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/StreamTransformServiceImpl.java

 [INLONG-4026][Manager] Fix field type of StreamSourceFieldMapper

---

inlong-dashboard/src/components/MetaData/StorageKafka.tsx

[INLONG-4031][Dashboard] Fix the kafka sink partition num key

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/HiveLoadNode.java

Fix parameter of hive load ‘catalogName’ change not null to null

[INLONG-4035][Sort] Change the restriction of Hive catalogName from not nullable to nullable

---

inlong-sort/sort-single-tenant/pom.xml

Fixes #4044 
Resolve jar conflict
modify pom.xml
*(example:)*

[INLONG-4044][Sort] Resolve conflict of flink-table-api-java-bridge jar

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/ExtractNodeUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/FieldInfoUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/FilterFunctionUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/NodeRelationShipUtils.java

[INLONG-4046][Manager] Fix Filter Function of Join node

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/InlongClusterPageRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/InlongClusterRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/InlongClusterResponse.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongClusterEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterEntityMapper.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterNodeEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongClusterServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/InlongClusterServiceTest.java
inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql

Fixes #4052 
[INLONG-4052][Manager] Remove zone_tag field of inlong cluster table.
`InlongClusterServiceTest`

[INLONG-4052][Manager] Remove zone_tag field of inlong cluster table

---

inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/parser/impl/FlinkSqlParser.java

[INLONG-3823][Sort] Fix error caused by unregistered custom function

---

inlong-sort/sort-single-tenant/src/main/java/org/apache/inlong/sort/singletenant/flink/function/RegexpReplaceFirstFunction.java

[INLONG-3816][Sort] Fix NPE in RegexpReplaceFirstFunction

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/InlongClusterPageRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/InlongClusterRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/InlongClusterResponse.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongClusterEntity.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterNodeEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongClusterServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/InlongClusterServiceTest.java
inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql

Fixes #4069
Add ext_tag field for inlong cluster table.

[INLONG-4069][Manager] Add ext_tag field for inlong cluster table

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongStream.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/DefaultInlongStreamBuilder.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/impl/InlongStreamImplTest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/FieldInfoUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/LoadNodeUtils.java

[INLONG-4070][Manager] Add update and delete APIs for inlong stream in manager client

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/KafkaConstant.java

Fixes #4081 
Fix character error
modify KafkaConstant class

[INLONG-4081][Sort] Fix upsert_kafka constant to upsert-kafka

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/node/DataNodePageRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/node/DataNodeRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/node/DataNodeResponse.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/DataNodeEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/DataNodeEntityMapper.java
inlong-manager/manager-dao/src/main/resources/generatorConfig.xml
inlong-manager/manager-dao/src/main/resources/mappers/DataNodeEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/DataNodeService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/DataNodeServiceImpl.java
inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/DataNodeController.java

Fixes #4071 
Add data cluster table.

[INLONG-4071][Manager] Add data node table and other related classes

---

inlong-manager/manager-client-tools/pom.xml
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CommandUtil.java
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/GroupInfo.java
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/util/PrintUtil.java
inlong-manager/manager-client-tools/src/test/java/org/apache/inlong/manager/client/cli/TestCommand.java

Fixes #4095 
1、Modify the configuration file acquisition method
2、Add judgment to special characters

[INLONG-4095][Manager] Fix UT error and align special characters

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/FieldRelationShipUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/NodeRelationShipUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/StreamTransformServiceImpl.java

[INLONG-4110][Manager] Create cascade function wrapper

---

inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/netty/NettyClientFactory.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/netty/NettyRpcServer.java
inlong-tubemq/tubemq-docker/tubemq-all/README.md
inlong-tubemq/tubemq-docker/tubemq-all/tubemq-docker.sh

[INLONG-4114][TubeMQ] Fix the tubemq all image can not start

---

inlong-dashboard/src/components/ConsumeHelper/BusinessSelect/MyBusinessModal.tsx
inlong-dashboard/src/pages/AccessDashboard/config.tsx
inlong-dashboard/src/pages/AccessDashboard/index.tsx
inlong-dashboard/src/pages/AccessDetail/DataSources/index.tsx
inlong-dashboard/src/pages/AccessDetail/DataStorage/index.tsx
inlong-dashboard/src/pages/AccessDetail/DataStream/config.tsx
inlong-dashboard/src/pages/DataSources/index.tsx

Fixes #4119 
Change the keyWord to keyword in query request params.

[INLONG-4119][Dashboard] Change the keyWord to keyword in query request params

---

inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/util/PrintUtil.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/FlinkSortBaseConf.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/TubeBaseConf.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/UserDefinedSortConf.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/consumption/ConsumptionInfo.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/pulsar/PulsarTopicBean.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/InlongStreamResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/StreamTransform.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/transform/deduplication/DeDuplicationDefinition.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/transform/filter/FilterDefinition.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/transform/joiner/JoinerDefinition.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/transform/replacer/StringReplacerDefinition.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/transform/splitter/SplitterDefinition.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/workflow/ProcessQuery.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/definition/WorkflowProcess.java

[INLONG-3636][Manager] Fix the warning logs during the build

---

.github/ct.yml
.github/kind.yml
.github/labeler.yml
.github/workflows/ci_chart_test.yml
.gitmodules
docker/kubernetes/Chart.yaml
docker/kubernetes/README.md
docker/kubernetes/templates/tubemq-broker-pdb.yaml
docker/kubernetes/templates/tubemq-master-pdb.yaml
docker/kubernetes/templates/zookeeper-pdb.yaml

Fixes: #3473
Use [helm/chart-testing-action](https://github.com/helm/chart-testing-action) to test helm charts on GitHub Actions.
When the helm charts changes, they can be tested automatically.
- Add chart test workflow
Have updated documentation, please check out https://github.com/shink/incubator-inlong/commit/45c705f611b791538fcd55007a41a6c85742bf2b

[INLONG-3473][CI] Add support for chart testing

---

inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/utils/EventLoopUtil.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/util/EventLoopUtil.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/EventLoopUtil.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/util/FlinkUtils.java
inlong-sdk/sdk-common/src/main/java/org/apache/inlong/sdk/commons/protocol/ProxyEvent.java
inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/utils/UnescapeHelper.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/group/GroupController.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/topic/TopicWebController.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/NodeServiceImpl.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/interfaces/MasterService.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/interfaces/NodeService.java

Search the log in https://github.com/apache/incubator-inlong/runs/5983318801?check_suite_focus=true, include:
InvalidJavadocPosition
SummaryJavadoc
SingleLineJavadoc
Fixes #3635 
*(example:)* …

[INLONG-3635][InLong] Fix the Javadoc check style problems for several modules

---

inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/workflow/group/CreateGroupWorkflowDefinitionTest.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/definition/ServiceTask.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/definition/WorkflowProcess.java

[INLONG-4142][Manager] Improve ServiceTask clone method

---

.github/workflows/ci_greeting.yml

fix: #4153
Add support for [first-interaction](https://github.com/actions/first-interaction)
- add a first interaction workflow

[INLONG-4153][CI] Add support for first interaction

---

docker/kubernetes/Chart.yaml
docker/kubernetes/templates/dashboard-statefulset.yaml

Fixes https://github.com/apache/incubator-inlong/issues/4144
*(example:)* …

[INLONG-4144][K8s] Fix the HTTP error appears on the login dashboard when deploying InLong using helm

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/DefaultInlongStreamBuilder.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongStreamServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java

[INLONG-4188][Manager] Check whether the stream exists in the manager client

---

LICENSE
licenses/LICENSE
licenses/inlong-agent/LICENSE
licenses/inlong-audit/LICENSE
licenses/inlong-dashboard/LICENSE
licenses/inlong-dataproxy/LICENSE
licenses/inlong-manager/LICENSE
licenses/inlong-sort-standalone/LICENSE
licenses/inlong-sort/LICENSE
licenses/inlong-tubemq-manager/LICENSE
licenses/inlong-tubemq-server/LICENSE

Fixes #4189 
[INLONG-4189][Sort] fix typo : change from NOTICE to LICENSE
[INLONG-4189][Sort] fix typo : change from NOTICE to LICENSE

[INLONG-4189][Sort] Change the NOTICE to LICENSE

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/PostgresConstant.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/ExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/PostgresExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/PostgresLoadNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/PostgresExtractNodeTest.java
inlong-sort/sort-single-tenant/pom.xml
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/PostgresExtractFlinkSqlParseTest.java
licenses/inlong-sort/LICENSE
licenses/inlong-sort/NOTICE
pom.xml

Fixes #4174 
supporting scan postgres data
Add postgres extract node

[INLONG-4174][Sort] Add Postgres extract node

---

.github/workflows/README.md
.github/workflows/ci_build.yml
.github/workflows/ci_chart_test.yml
.github/workflows/ci_check_license.yml
.github/workflows/ci_docker.yml
.github/workflows/ci_labeler.yml
.github/workflows/ci_ut.yml

fix: #4201
Improve workflows and documentation.
- bump [apache/skywalking-eyes](https://github.com/apache/skywalking-eyes) version to `v0.3.0`
- bump [actions/checkout](https://github.com/actions/checkout) version to `v3`
- add [README.md](https://github.com/shink/incubator-inlong/blob/INLONG-4201/.github/workflows/README.md)

[INLONG-4201][CI] Improve workflows and documentation

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/PostgresConstant.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/LoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/PostgresLoadNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/PostgresLoadNodeTest.java
inlong-sort/sort-single-tenant/pom.xml
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/PostgresLoadNodeFlinkSqlParseTest.java
licenses/inlong-sort/LICENSE
licenses/inlong-sort/NOTICE
licenses/inlong-sort/licenses/LICENSE-postgresql.txt
pom.xml

Fixes #4198 
Supporting load data into Postgres
Add PostgresLoadNode class

[INLONG-4198][Sort] Add Postgres load node

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/InlongClusterRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/InlongClusterResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/node/DataNodeRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/node/DataNodeResponse.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/DataNodeEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongClusterEntity.java
inlong-manager/manager-dao/src/main/resources/mappers/DataNodeEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/DataNodeServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/DataNodeServiceTest.java
inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql

Fixes #4186 
Add token field in cluster and node table.

[INLONG-4186][Manager] Add token field in cluster and node table

---

inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/core/impl/ProcessorExecutorImpl.java

Fixes #4212
The processor executor maybe throws a null pointer exception.
Add null check before the method call.

[INLONG-4212][Manager] The processor executor maybe throws a null pointer exception

---

licenses/LICENSE
licenses/inlong-agent/LICENSE
licenses/inlong-audit/LICENSE
licenses/inlong-dashboard/LICENSE
licenses/inlong-dataproxy/LICENSE
licenses/inlong-manager/LICENSE
licenses/inlong-sort-standalone/LICENSE
licenses/inlong-sort/LICENSE
licenses/inlong-tubemq-manager/LICENSE
licenses/inlong-tubemq-server/LICENSE

Add license for sort singleTenant hive connector
Fixes #4215

[INLONG-4215][Sort] Add license for Hive connector of Sort

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ErrorCodeEnum.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/consumption/ConsumptionInfo.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/consumption/ConsumptionListVo.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/consumption/ConsumptionMqExtBase.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/consumption/ConsumptionPulsarInfo.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/consumption/ConsumptionQuery.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/workflow/form/ConsumptionApproveForm.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/workflow/form/NewConsumptionProcessForm.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/ConsumptionEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/ConsumptionPulsarEntity.java
inlong-manager/manager-dao/src/main/resources/mappers/ClusterSetMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/ConsumptionEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/ConsumptionPulsarEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/ConsumptionService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ConsumptionServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/mq/MiddlewareFactory.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/consumption/listener/ConsumptionCompleteProcessListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/consumption/listener/ConsumptionPassTaskListener.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/ConsumptionServiceTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/InlongGroupProcessOperationTest.java
inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql

Fixes #4223
[INLONG-4223][Manager] Refactor the consumption table structure.

[INLONG-4223][Manager] Refactor the consumption table structure

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/PulsarExtractNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/PulsarExtractNodeTest.java
inlong-sort/sort-connectors/pom.xml
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/pulsar/table/DynamicPulsarSerializationSchema.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/pulsar/table/PulsarDynamicTableFactory.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/pulsar/table/PulsarDynamicTableSink.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/pulsar/table/UpsertPulsarDynamicTableFactory.java
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/PulsarSqlParserTest.java
inlong-sort/sort-single-tenant/src/test/resources/META-INF/services/org.apache.flink.table.factories.Factory
licenses/inlong-sort/LICENSE
pom.xml

Fixes #4141
Sort lightwieght support load data from pulsar
Add Pulsar Extrace Node

[InLong-4141][Sort] Sort lightwieght support load data from Pulsar

---

inlong-sort/sort-single-tenant/pom.xml

Fixes #4244 
resolve problem of shade plugin
change pom file

[INLONG-4244][Sort] Remove flink-avro relocation

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/sink/HbaseSink.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSinkTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SinkType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hbase/HbaseSinkDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hbase/HbaseSinkListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hbase/HbaseSinkRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hbase/HbaseSinkResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/hbase/HbaseSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/LoadNodeUtils.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/sink/HbaseStreamSinkServiceTest.java

[INLONG-4197][Manager] Add Hbase sink info and load node utils

---

.asf.yaml
.github/workflows/ci_build.yml
.github/workflows/ci_chart_test.yml
.github/workflows/ci_docker.yml
.github/workflows/ci_ut.yml

Fixes #4267 
The checks pipeline of PR was incorrect.
1. Remove the contexts for checks,
2. Set the required approving review count to 2.

[INLONG-4267][GitHub] The checks pipeline of PR was incorrect

---

.github/workflows/ci_build.yml
.github/workflows/ci_chart_test.yml
.github/workflows/ci_docker.yml
.github/workflows/ci_ut.yml

fix: #4267
Fixes #<xyz>
*(example:)*

[INLONG-4267][CI] Revert the CI config

---

inlong-sort/sort-common/pom.xml
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/Format.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/InLongMsgFormat.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/format/InLongMsgFormatTest.java
inlong-sort/sort-formats/format-inlongmsg-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgFormatFactory.java
inlong-sort/sort-formats/format-inlongmsg-base/src/test/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgFormatFactoryTest.java
inlong-sort/sort-formats/format-inlongmsg-base/src/test/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgRowDataSerDeTest.java

Import inlong format json serialize/deserialize
Fixes #4259
Import inlong format json serialize/deserialize
Add Json Serialize InLongMsg format and its ut.

[INLONG-4259][Sort] Import inlong format json serialize/deserialize

---

inlong-manager/manager-plugins/pom.xml
licenses/inlong-manager/LICENSE
licenses/inlong-manager/NOTICE

Fixes #4254
Add flink-table-api-java-1.13.5.jar、flink-table-runtime-blink_2.11-1.13.5.jar package dependency for inlong-manager/manager-plugins
Add some flink-table-runtime-blink_2.11-1.13.5.jar、flink-table-runtime-blink_2.11-1.13.5.jar for inlong-manager/manager-plugins
- [ X] This change is a trivial rework/code cleanup without any test coverage.

[INLONG-4254][Manager] Add flink table dependencies for inlong-manager/manager-plugins

---

LICENSE
NOTICE
licenses/LICENSE
licenses/NOTICE
licenses/inlong-agent/LICENSE
licenses/inlong-agent/NOTICE
licenses/inlong-audit/LICENSE
licenses/inlong-audit/NOTICE
licenses/inlong-dashboard/LICENSE
licenses/inlong-dashboard/NOTICE
licenses/inlong-dataproxy/LICENSE
licenses/inlong-dataproxy/NOTICE
licenses/inlong-manager/LICENSE
licenses/inlong-manager/NOTICE
licenses/inlong-sort-standalone/LICENSE
licenses/inlong-sort-standalone/NOTICE
licenses/inlong-sort/LICENSE
licenses/inlong-sort/NOTICE
licenses/inlong-tubemq-manager/LICENSE
licenses/inlong-tubemq-manager/NOTICE
licenses/inlong-tubemq-server/LICENSE
licenses/inlong-tubemq-server/NOTICE

[INLONG-4277][License] Check the LICENSE and NOTICE of the project source code

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/PostgresConstant.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/LoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/ClickHouseLoadNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/ClickHouseLoadNodeTest.java
inlong-sort/sort-connectors/pom.xml
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/clickhouse/table/ClickHouseDialect.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/clickhouse/table/ClickHouseRowConverter.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/jdbc/table/AbstractJdbcDialect.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/jdbc/table/JdbcDialects.java
inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/jdbc/table/JdbcDynamicTableFactory.java
inlong-sort/sort-connectors/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
inlong-sort/sort-single-tenant/pom.xml
inlong-sort/sort-single-tenant/src/test/java/org/apache/inlong/sort/singletenant/flink/parser/ClickHouseSqlParserTest.java

Fixes #4227
Sort lightwieght support extract data to clickhouse
Add clickhouse load node.
Add jdbc-inlong table factory to enhance custom jdbc dialect.
Add Clickhouse jdbcdialect.

[InLong-4227][Sort] Sort lightwieght support extract data to ClickHouse

---

licenses/inlong-agent/LICENSE
licenses/inlong-agent/NOTICE
licenses/inlong-agent/notices/NOTICE-commons-compress.txt
licenses/inlong-agent/notices/NOTICE-jackson-module-jaxb-annotations.txt

[INLONG-4288][License] Update Agent's third-party dependency LICENSE

---

inlong-common/src/main/java/org/apache/inlong/common/enums/TaskTypeEnum.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SourceType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/binlog/BinlogSourceListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaSourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/pulsar/PulsarSourceDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/pulsar/PulsarSourceListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/pulsar/PulsarSourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/pulsar/PulsarSourceResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/CreateSortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/CreateSortConfigListenerV2.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/PushSortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/DataFlowUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/ExtractNodeUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/NodeRelationShipUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/pulsar/PulsarSourceOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/listener/GroupTaskListenerFactory.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/enums/ScanStartupMode.java

[INLONG-4278][Manager] Support Pulsar extract node in Manager

---

inlong-common/src/main/java/org/apache/inlong/common/enums/TaskTypeEnum.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/sink/PostgresSink.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/source/PostgresSource.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSinkTransfer.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSourceTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SinkType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SourceType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/postgres/PostgresSinkDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/postgres/PostgresSinkListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/postgres/PostgresSinkRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/postgres/PostgresSinkResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/postgres/PostgresSourceDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/postgres/PostgresSourceListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/postgres/PostgresSourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/postgres/PostgresSourceResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/postgres/PostgresSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/ExtractNodeUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/LoadNodeUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/postgres/PostgresSourceOperation.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/sink/PostgresStreamSinkServiceTest.java

Add postgres source and sink node configuration utils
Fixes #4240

[INLONG-4240][Manager] Support postgres source and sink

---

inlong-manager/manager-service/pom.xml
licenses/inlong-manager/LICENSE
licenses/inlong-manager/NOTICE
pom.xml

[INLONG-4309][Manager] Supplement HBase dependencies and license file

---

inlong-dashboard/src/pages/ApprovalDetail/Access.tsx
inlong-dashboard/src/pages/ApprovalDetail/AccessConfig.tsx
inlong-dashboard/src/pages/Approvals/Applies/index.tsx
inlong-dashboard/src/pages/Approvals/Approvals/index.tsx

[INLONG-4319][Dashboard] Approve page support cluster info

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/ByteUtil.java
inlong-common/src/main/java/org/apache/inlong/common/msg/DataInputBuffer.java
inlong-common/src/main/java/org/apache/inlong/common/msg/DataOutputBuffer.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/RmtDataCache.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/client/CallFuture.java
inlong-tubemq/tubemq-example/src/main/java/org/apache/inlong/tubemq/example/ClientBalanceConsumerExample.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/zookeeper/RecoverableZooKeeper.java

[INLONG-4321][TubeMQ] Add Javadoc comments for methods

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/FileSystemLoadNode.java

Fix parameter error connector of file system
Fixes #4306

[INLONG-4306][Sort] Parameter error connector of file system

---

inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/group/GroupController.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/executors/AddTopicExecutor.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/TaskServiceImpl.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/tube/BrokerConf.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/tube/TubeHttpTopicInfoList.java

Fixes https://github.com/apache/incubator-inlong/issues/4324
*(example:)* …

[INLONG-4324][TubeMQ] Add Javadoc for methods

---

inlong-sort/pom.xml
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/ExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/SqlServerExtractNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/SqlServerExtractNodeTest.java
inlong-sort/sort-connectors/pom.xml
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/SqlServerNodeSqlParseTest.java
licenses/inlong-sort/LICENSE
licenses/inlong-sort/NOTICE
pom.xml

Add SqlServer data extract support
Fixes #4262

[INLONG-4262][Sort] Add SqlServer data extract support

---

inlong-sort/sort-core/pom.xml

[INLONG-4342][Sort] Remove the duplicate audit-sdk dependency

---

inlong-manager/manager-service/pom.xml
licenses/inlong-agent/LICENSE
licenses/inlong-dataproxy/LICENSE
licenses/inlong-manager/LICENSE
pom.xml

[INLONG-4351]][POM] Update the fastjson to solve the CVE

---

codestyle/checkstyle.xml
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/meta/MetricsMeta.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/es/ElasticsearchApi.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/IEvent2LogItemHandler.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/MySqlSource.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/utils/RecordUtils.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/utils/TStringUtils.java

[INLONG-4349][Doc] Update check style to avoid the Javadoc missing and error

---

inlong-manager/manager-test/src/main/resources/application-test.properties
inlong-manager/manager-web/src/main/resources/application-test.properties

Fix registration sql function exception
Fixes #4325
Druid provides a built-in StatFilter for statistical monitoring information. Turning it on and off will not affect its own program. official documentation：
https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter

[INLONG-4325][Manager] Fix registration SQL function exception

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/source/AgentFileSource.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/source/AutoPushSource.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/source/MySQLBinlogSource.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/source/MySQLSource.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/source/PostgresSource.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSourceTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/pulsar/PulsarSourceResponse.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/CreateSortConfigListenerV2.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/CreateStreamSortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/ExtractNodeUtils.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/enums/KafkaScanStartupMode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/enums/PulsarScanStartupMode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNodeTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DistinctNodeSqlParseTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/FlinkSqlParserTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/FullOuterJoinSqlParseTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/InnerJoinRelationShipSqlParseTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/LeftOuterJoinSqlParseTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/MetaFieldSyncTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/RightOuterJoinSqlParseTest.java

[INLONG-4364][Manager] Optimize Sort protocal and Pulsar extract node

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/SqlServerLoadNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/SqlServerLoadNodeTest.java
inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/SqlServerDialect.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/SqlServerNodeSqlParseTest.java

Enhance upsert capability for SqlServer
Fixes #4346

[INLONG-4346][Sort] Enhance upsert capability for SqlServer

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/HiveLoadNode.java

Fixes #4371 
remove null constraint on hive version, fixes #4371 
fixes #4371 

[INLONG-4371][Sort] Remove null constraint on Hive version

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/auth/DefaultAuthentication.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupApproveRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/pulsar/PulsarSourceDTO.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/plugin/PluginClassLoader.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
inlong-manager/manager-web/pom.xml
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/event/LogableEventListener.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/util/WorkflowBeanUtils.java

Fixes #4369 
Support for modification of information after approval.
Add `inlongClusterTag` in `InlongGroupApproveRequest`, after approving the inlong group, set the cluster tag for the inlong group.
- Does this pull request introduces a new feature? (no)

[INLONG-4369][Manager] Support for modification of information after approval

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/CreateGroupWorkflowDefinition.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/stream/CreateStreamWorkflowDefinition.java

[INLONG-4315][Manager] Fix incorrect task service node order in create-group workflow

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java

[INLONG-4354][SDK] Fix NPE of the ProxyConfigEntry cluster id

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/LoadNodeUtils.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/ClickHouseLoadNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/ClickHouseLoadNodeTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/ClickHouseSqlParserTest.java

Support clickhouse sink
Fixes #4332

[INLONG-4332][Manager][Sort] Support ClickHouse load node

---

inlong-dashboard/src/components/MetaData/StorageHive.tsx
inlong-dashboard/src/locales/cn.json
inlong-dashboard/src/locales/en.json

[INLONG-4423][Dashboard] Hive Sink adds hiveConfDir parameter

---

docker/docker-compose/docker-compose.yml

[INLONG-4434][Docker] Fix the wrong ENV for Pulsar address

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ThirdPartyClusterServiceImpl.java

Fixes #4438
Add warning log to remind register dataproxy cluster, avoid throw exception directly
*(example:)*

[INLONG-4438][Manager] Add warning log to remind register dataproxy cluster

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/auth/Authentication.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupMode.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/MetaFieldType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/TransformType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sort/BaseSortConf.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/kafka/KafkaOffset.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/StreamNodeRelation.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/StreamPipeline.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/transform/filter/FilterDefinition.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/transform/splitter/SplitterDefinition.java
inlong-manager/manager-common/src/test/java/org/apache/inlong/manager/common/pojo/stream/StreamPipelineTest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ConsumptionServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/InlongStreamServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/CreateSortConfigListenerV2.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/CreateStreamSortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/light/LightGroupSortListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/ExtractNodeUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/FieldRelationUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/FilterFunctionUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/LoadNodeUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/NodeRelationUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/TransformNodeUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/consumption/NewConsumptionWorkflowDefinition.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/NewGroupWorkflowDefinition.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/listener/GroupUpdateCompleteListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/stream/listener/StreamUpdateCompleteListener.java

Fixes #4445 
Change the relationship to relation to adapt the Sort protocol.

[INLONG-4445][Manager] Change the relationship to relation to adapt the Sort protocol

---

inlong-tubemq/tubemq-docker/tubemq-all/Dockerfile

[INLONG-4451][TubeMQ] Update the base docker image for TubeMQ

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java

- Title Example: [INLONG-4462][Manager] Fix NPE when parsing pageInfo in manager client
- Fixes #4462 
*(example:)*
- If a feature is not documented yet in this PR, please create …

[INLONG-4462][Manager] Fix NPE when parsing pageInfo in manager client

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java

- Title Example: [INLONG-4466] [Manager]Fix inlong parser in oracle source
- Fixes #4466 
*Fix the bug that the oracle could not be parsed*
*(example:)* …

[INLONG-4466][Manager] the oracle data source could not be parsed

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebAdminGroupCtrlHandler.java

[INLONG-4470][TubeMQ] The "admin_query_black_consumer_group_info" method adds query topicName field

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/postgres/PostgresColumnInfo.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/postgres/PostgresSinkDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/postgres/PostgresTableInfo.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/postgres/PostgresJdbcUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/postgres/PostgresResourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/postgres/PostgresSqlBuilder.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/sink/PostgresStreamSinkServiceTest.java

Support create postgres resource
Fixes #4356

[INLONG-4356][Manager] Support create postgres resource

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/HiveLoadNode.java

- Fixes #4493 
remove hiveConfDir not null constraint.
modify `HiveLoadNode` class.

[INLONG-4493][Sort] Remove hiveConfDir not null constraint

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/DefaultMetaDataService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/MetaDataService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/ConsumeCtrlMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/MetaConfigMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsConsumeCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsMetaConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebAdminGroupCtrlHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebGroupConsumeCtrlHandler.java

[INLONG-4486][TubeMQ] Adjust the parameter requirements of group consume delete control APIs

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/SinkListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/StreamSink.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/SourceListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/StreamSource.java

- Title Example: [INLONG-4487][Manager] Fix json parse exception for streamSource/streamSink
- Fixes #4487 
*(example:)* …

[INLONG-4487][Manager] Fix JSON parse exception for stream source and stream sink

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebAdminGroupCtrlHandler.java

[INLONG-3475][TubeMQ] Add an API for batch deletion of authorized consumer group records(addendum)

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/impl/InnerInlongManagerClientTest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/StreamSource.java

-  [INLONG-4503][Manager] Fix Client executes request error
- Fixes #4503
Fix Client executes request error
- Add exception handling method
- Add its unit test
- InnerInlongManagerClientTest

[INLONG-4503][Manager] Fix the error of manager client executes the request

---

inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/BaseExample.java
inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/File2HBaseExample.java
inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/File2IcebergExample.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/iceberg/IcebergColumnInfo.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/iceberg/IcebergType.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/iceberg/IcebergCatalogUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/iceberg/IcebergSinkOperation.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java

[INLONG-4513][Manager] Add Iceberg and HBase examples for the manager client

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/FileCollectType.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/FileJob.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobWrapper.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/trigger/TriggerManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/TextFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/trigger/DirectoryTrigger.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/TestFileAgent.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/utils/TestUtils.java

Supports collect of full data for file type
Fixes #4397

[INLONG-4397][Agent] Supports collect of full data for file type

---

inlong-sort/pom.xml
inlong-sort/sort-connectors/hbase/pom.xml
inlong-sort/sort-connectors/hbase/src/main/resources/hbase-default.xml
licenses/inlong-sort/LICENSE

- Fixes #4557 
Fix sink data to hbase problem
modify hbase dependency and add hbase-default.xml

[INLONG-4557][Sort] Fix HBase connector dependecy and pom relocation problem

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SinkType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/greenplum/GreenplumSink.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/greenplum/GreenplumSinkDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/greenplum/GreenplumSinkListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/greenplum/GreenplumSinkRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/greenplum/GreenplumSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/LoadNodeUtils.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/sink/GreenplumStreamSinkServiceTest.java

- Title Example: [INLONG-4528][Manager] Support Greenplum sink
- Fixes #4528 
*Support Greenplum sink*
*Support Greenplum sink.*
*(example:)*
- If a feature is not documented yet …

[INLONG-4528][Manager] Support Greenplum sink

---

inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/core/TransactionHelper.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/core/impl/ProcessorExecutorImpl.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/processor/ServiceTaskProcessor.java

[INLONG-4556][Manager] Optimize ProcessorExecutor Logic

---

inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
inlong-manager/manager-test/src/main/resources/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql

[INLONG-4552][Manager] Add composite index for table in DDL

---

.github/ISSUE_TEMPLATE/bug-report.yml

- Fixes #4565 
Add the 1.2.0 version option for the bug report.
Add the 1.2.0 version option for the bug report.

[INLONG-4565][CI] Add the 1.2.0 version option for the bug report

---

inlong-dashboard/src/pages/Clusters/NodeEditModal.tsx
inlong-dashboard/src/pages/Clusters/config/TubeMQ.tsx
inlong-dashboard/src/pages/Clusters/config/index.tsx

- Fixes #4577
Support TubeMQ cluster management.
Support TubeMQ cluster management.

[INLONG-4577][Dashboard] Support TubeMQ cluster management

---

inlong-dashboard/src/components/MetaData/DataSourcesFile.ts
inlong-dashboard/src/components/MetaData/StorageHive.tsx

- Fixes #4580 
Add required in `DataSourceFile.ts` and `StorageHive.tsx` files.

[INLONG-4580][Dashboard] Add required for file source IP and hive conf dir

---

inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java

- Fixes #4583
Fix the SQL error for query InlongGroup.
Remove the limit in SQL, because the PageHelper will add the limit automatically.

[INLONG-4583][Manager] Fix the SQL error for query InlongGroup

---

inlong-manager/manager-client-examples/pom.xml
inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/ut/BaseTest.java
inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/ut/Kafka2HiveTest.java

- Fixes #4534 
Add complete create data flow task unit test(Kafka2Hive)
Add complete create data flow task unit test(Kafka2Hive)
- Kafka2HiveTest

[INLONG-4534][Manager] Add complete create data flow task unit test

---

inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/BaseExample.java
inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/File2HBaseExample.java
inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/File2IcebergExample.java
inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/ut/BaseTest.java
inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/ut/Kafka2HiveTest.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/StreamTransformTransfer.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/StreamSink.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/StreamSource.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/stream/StreamNode.java
inlong-manager/manager-common/src/test/java/org/apache/inlong/manager/common/pojo/transform/TransformDefinitionTest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/ck/ClickHouseSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/es/ElasticsearchSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/greenplum/GreenplumSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/hbase/HBaseSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/hdfs/HdfsSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/hive/HiveSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/iceberg/IcebergSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/kafka/KafkaSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/mysql/MySQLSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/postgres/PostgresSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/sqlserver/SqlServerSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/LoadNodeUtils.java

[INLONG-4586][Manager] Fix redefined streamFields in stream source

---

inlong-dashboard/src/configs/menus/index.ts
inlong-dashboard/src/configs/routes/index.tsx
inlong-dashboard/src/pages/ApprovalDetail/Steps.tsx
inlong-dashboard/src/pages/ApprovalDetail/index.tsx
inlong-dashboard/src/pages/Approvals/Applies/config.tsx
inlong-dashboard/src/pages/Approvals/Applies/index.tsx
inlong-dashboard/src/pages/Approvals/Approvals/config.tsx
inlong-dashboard/src/pages/Approvals/Approvals/index.tsx
inlong-dashboard/src/pages/Approvals/index.tsx

[INLONG-4588][Dashboard] Approval management splits different routes

---

CHANGES.md

- Fixes #4567
Update changes log for the 1.2.0 version.
Update changes log for the 1.2.0 version.

[INLONG-4567][Release] Update changes log for the 1.2.0 version

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/pulsar/PulsarSource.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/CreateSortConfigListenerV2.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/ExtractNodeUtils.java

[INLONG-4598][Manager] Fix topic not match bug

---

inlong-sort/sort-connectors/jdbc/pom.xml

- [INLONG-4596][Sort] Fix jdbc-connector packaging lost dependencies
- Fixes #4596 
Fix jdbc-connector packaging lost dependencies
modify pom of jdbc-connector

[INLONG-4596][Sort] Fix jdbc-connector packaging lost dependencies

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/SinkRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/ck/ClickHouseSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/es/ElasticsearchSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/greenplum/GreenplumSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/hbase/HBaseSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/hdfs/HdfsSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/hive/HiveSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/iceberg/IcebergSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/kafka/KafkaSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/mysql/MySQLSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/postgres/PostgresSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/sqlserver/SqlServerSinkOperation.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/sink/GreenplumStreamSinkServiceTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/sink/HdfsStreamSinkServiceTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/sink/MysqlStreamSinkServiceTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sort/DisableZkForSortTest.java

- Fixes #4601
Change fieldList to sinkFieldList in SinkRequest.
Change fieldList to sinkFieldList in SinkRequest.

[INLONG-4601][Manager] The fieldList in SinkRequest should be changed to sinkFieldList

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SinkType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/oracle/OracleSink.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/oracle/OracleSinkDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/oracle/OracleSinkListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/oracle/OracleSinkRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/oracle/OracleSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/LoadNodeUtils.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/sink/OracleStreamSinkServiceTest.java

- Title Example: [INLONG-4403] [Manager] Support oracle sink
- Fixes #4403 
*Support oracle sink*
*Add Iceberg sink info and load node utils.*
*(example:)* …

[INLONG-4403][Manager] Support Oracle sink

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/FieldType.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/FieldInfoUtils.java

[INLONG-4607][Manager] Add ck field type
- Fixes #4607 
Add ck field type
Add ck field type

[INLONG-4607][Manager] Add ck field type

---

inlong-dashboard/src/components/AccessHelper/DataStorageEditor/DetailModal.tsx
inlong-dashboard/src/components/MetaData/StorageClickhouse.tsx
inlong-dashboard/src/components/MetaData/StorageHive.tsx
inlong-dashboard/src/components/MetaData/StorageIceberg.tsx

- Fixes #4610
Change the fieldList to sinkFieldList.
Change the fieldList to sinkFieldList.

[INLONG-4610][Dashboard] Change the fieldList to sinkFieldList

---

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderChannel.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderGroup.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderManager.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/util/Config.java
inlong-audit/audit-sdk/src/test/java/org/apache/inlong/audit/send/SenderGroupTest.java

- Fixes #4559
- Audit SDK support random routing

[INLONG-4559][Audit] Support select channels by random routing

---

inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestKafkaReader.java

[Agent] Many ConnectException logs in unit test of Kafka source 
- Fixes #4483 
*Fix  many ConnectException logs in unit test of Kafka source

[INLONG-4483][Agent] Many ConnectException logs in unit test of Kafka source

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/plugin/PluginClassLoader.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/plugin/PluginClassLoaderTest.java

- Fixes #4615 
Manager pluginClassLoader cannot work well in Windows system,  this pr is aimed to fix it 
*(example:)* …

[INLONG-4615][Manager] PluginClassLoader adapts to the Windows system

---

inlong-dashboard/src/components/MetaData/StorageIceberg.tsx
inlong-dashboard/src/locales/cn.json
inlong-dashboard/src/locales/en.json
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/iceberg/IcebergSink.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/iceberg/IcebergSinkRequest.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkOperation.java

[INLONG-4612][Dashboard][Manager] Update iceberg config ui and related protocol key names

---

inlong-sort/sort-connectors/hive/pom.xml

-[INLONG-4619][Sort] Fix hive connector maven package problem
- Fixes #4619 
Fix hive connector maven package problem
modify pom

[INLONG-4619][Sort] Fix hive connector maven package problem

---

inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkOperation.java

[INLONG-4626][Manager] Remove redundant connector sub directory

---

CHANGES.md

- Fixes #4567
Update changes log for the 1.2.0 version (addendum).

[INLONG-4567][Release] Update changes log for the 1.2.0 version (addendum)

---

inlong-distribution/pom.xml
inlong-distribution/src/main/assemblies/release.xml
inlong-distribution/src/main/assemblies/sort-connectors.xml

[Improve][InLong] Re-optimization distribute package
- Fixes #4647 
1.remove redundant package sort-connectors jar in release tar.gz
2.rename sort-connectors folder in connector.tar.gz
3.add dependency to support multiple thread compile
Re-optimization distribute package

[Improve][Sort] Re-optimize the distribution package of the Sort connectors

---

inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkOperation.java

[INLONG-4648][Manager] Read the path of Sort connectors from configuration file

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/es/ElasticsearchSinkDTO.java

- Title Example: [INLONG-4643][Manager] Add some parameters in Elasticsearch Sink DTO
- Fixes #4643 
Fix some missing parameters
Add some parameters in ElasticsearchSinkDTO
*(example:)* …

[INLONG-4643][Manager] Add some parameters in ElasticsearchSinkDTO

---

inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/plugin/PluginServiceTest.java

[INLONG-4660][Manager] PluginServiceTest adapts to the Windows system

---

inlong-sort/pom.xml
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/DLCConstant.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/LoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/DLCIcebergLoadNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/DLCIcebergLoadNodeTest.java
inlong-sort/sort-connectors/iceberg-dlc/pom.xml
inlong-sort/sort-connectors/iceberg-dlc/src/main/java/org/apache/inlong/sort/iceberg/catalog/hybris/CachedClientPool.java
inlong-sort/sort-connectors/iceberg-dlc/src/main/java/org/apache/inlong/sort/iceberg/catalog/hybris/DLCWrappedHybrisClientPool.java
inlong-sort/sort-connectors/iceberg-dlc/src/main/java/org/apache/inlong/sort/iceberg/catalog/hybris/DlcWrappedHybrisCatalog.java
inlong-sort/sort-connectors/iceberg-dlc/src/main/java/org/apache/inlong/sort/iceberg/catalog/hybris/HiveTableOperations.java
inlong-sort/sort-connectors/pom.xml
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DLCIcebergSqlParseTest.java
licenses/inlong-sort-connectors/LICENSE
licenses/inlong-sort-connectors/licenses/LICENSE-cos_api-bundle.txt
licenses/inlong-sort-connectors/notices/NOTICE-cos_api-bundle.txt
pom.xml

Title: [INLONG-4431][Sort] Sort lightwieght support load data to DLC
- Fixes #4431 
To enrich more connector，the dlc is tencent data lake compute product.
https://cloud.tencent.com/product/dlc
add dlc load node.

[INLONG-4431][Sort] Sort lightweight support load data to DLC

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SourceType.java

…SourceType
- Title Example: [[INLONG-4663][Manager] Change Mongo datasource mapping to MongoDB 
- Fixes #4663 
Change Mongo datasource mapping to MongoDB 
Change Mongo datasource mapping to MongoDB 
*(example:)* …

[INLONG-4663][Manager] Change Mongo data source mapping to MongoDB

---

inlong-sort/README.md

Title: [INLONG-4670][Sort] Update the README.md for the sort
- Fixes #4670 
Update the README.md for the sort
The README.md of the sort will be updated.
*(example:)*
- If a …

[INLONG-4670][Sort] Update the README.md for the Sort module

---

inlong-common/src/main/java/org/apache/inlong/common/enums/MetaField.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/util/MetaInfoParseUtil.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/util/MetaInfoParseUtilTest.java

- [INLONG-4678][Sort] Add sql meta field append for other data node
- Fixes #4678 
Add sql meta field append for other data node
* Add SQLServer/MongoDB/PostgreSQL meta field sql append.  
* Etract parse meta field method to tool class.

[INLONG-4678][Sort] Add util class of parsing meta info for data node

---

inlong-manager/pom.xml
pom.xml

- Fixes #4682 
The Jupiter version we are using is 5.8.2 but the engine is 5.3.2. Align engine with Jupiter version
Upgrade Jupiter engine 5.3.2 -> 5.8.2
- InnerInlongManagerClientTest

[INLONG-4682][Manager] Upgrade Jupiter engine version

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupStatus.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupInfo.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupRequest.java

[INLONG-4687][Manager] Add middlewareType field back to adapt the old behavior

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/AgentUtils.java
inlong-agent/agent-common/src/test/java/org/apache/inlong/agent/common/TestAgentUtils.java

[INLONG-3266][Agent] Get local IP when IP in config is not present 

---

README.md

[INLONG-4696][Doc] Update the supported data nodes

---

README.md

[INLONG-4698][Doc] Update the definitions and features to make them accurate

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/AbstractSinkOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/ck/ClickHouseSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/es/ElasticsearchSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/greenplum/GreenplumSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/hbase/HBaseSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/hdfs/HdfsSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/hive/HiveSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/iceberg/IcebergSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/kafka/KafkaSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/mysql/MySQLSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/oracle/OracleSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/postgres/PostgresSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/sqlserver/SqlServerSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/tdsqlpostgresql/TDSQLPostgreSQLSinkOperation.java

- Fixes #4632 
*Abstract operations on sink configuration to reduce repetitive code.*

[INLONG-4632][Manager] Abstract operations on sink configuration to reduce repetitive code

---

README.md

[INLONG-4716][Doc] Update the links for readme

---

.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/ct.yml
.github/workflows/README.md
.github/workflows/ci_check_pr_title.yml
CONTRIBUTING.md
README.md
docker/kubernetes/Chart.yaml
docker/kubernetes/README.md
inlong-dashboard/README.md
inlong-tubemq/pom.xml
inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/README.md
inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/proto/readme.md
inlong-tubemq/tubemq-client-twins/tubemq-client-go/README.md
inlong-tubemq/tubemq-client-twins/tubemq-client-python/README.md
pom.xml

[INLONG-4727][Doc] Update InLong project link in readme and pom.xml

---

licenses/LICENSE
licenses/inlong-agent/LICENSE
licenses/inlong-audit/LICENSE
licenses/inlong-dashboard/LICENSE
licenses/inlong-dataproxy/LICENSE
licenses/inlong-manager/LICENSE
licenses/inlong-sort-connectors/LICENSE
licenses/inlong-sort-standalone/LICENSE
licenses/inlong-sort/LICENSE
licenses/inlong-tubemq-manager/LICENSE
licenses/inlong-tubemq-server/LICENSE

[INLONG-4737][Doc] Remove "(Incubating)" tag in licenses dirs

---

inlong-dashboard/src/pages/AccessDashboard/ExecutionLogModal.tsx

[INLONG-4739][Dashboard] The pagination of the execution log of the group is invalid

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SinkType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/dlc/DLCIcebergSink.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/dlc/DLCIcebergSinkDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/dlc/DLCIcebergSinkListResponse.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/dlc/DLCIcebergSinkRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/dlc/DLCIcebergSinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/LoadNodeUtils.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/sink/DLCIcebergStreamSinkServiceTest.java

- Fixes #4442 
Support DLCIceberg sink
Support DLCIceberg sink
*(example:)*

[INLONG-4442][Manager] Support DLCIceberg sink

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongGroup.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/BlankInlongGroup.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongGroupApi.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongStreamApi.java
inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClientTest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupResetRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/operation/InlongGroupProcessOperation.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java

- Fixes #4742 
Resolve group hanging problems;
Modifify group status when process is hanging
*(example:)*
- If a feature …

[INLONG-4742][Manager] Support Reset when inlong group is pending on Configuring

---

inlong-dashboard/src/pages/Clusters/NodeManage.tsx
inlong-dashboard/src/pages/Clusters/index.tsx

[INLONG-4752][Dashboard] Keyword param error

---

inlong-manager/manager-client-examples/pom.xml
inlong-manager/manager-client-tools/pom.xml
inlong-manager/manager-client/pom.xml
inlong-manager/manager-common/pom.xml
inlong-manager/manager-plugins/pom.xml
inlong-manager/pom.xml

Fixes #4771 
I check licenses , may be nothing to change

[INLONG-4771][Manager] Change junit-jupiter dependency to test scope

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongStreamExtEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/ConsumptionPulsarEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupExtEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamExtEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamFieldEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkExtEntityMapper.xml

- Fixes #4781 
Refactor the InlongStreamExtEntityMapper file.

[INLONG-4781][Manager] Refactor the InlongStreamExtEntityMapper file

---

inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/config/Swagger2Config.java

- Fixes #4755
Resolve LocalDateTime and LocalTime format error in Swagger.

[INLONG-4755][Manager] Resolve LocalDateTime and LocalTime format error in Swagger

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClient.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/auth/DefaultAuthentication.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/consumption/ConsumptionQuery.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/user/UserDetail.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/user/UserDetailPageRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/util/LoginUserUtils.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/UserRoleEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/UserRoleEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/ConsumptionEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/UserRoleEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/RoleService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/RoleServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/UserServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/operationlog/OperationLogRecorder.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/ExtractNodeUtils.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/WebAuthorizingRealm.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/config/ControllerExceptionHandler.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/ConsumptionController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/DataNodeController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSinkController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSourceController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamTransformController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/UserController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/WorkflowApproverController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/WorkflowController.java

- Title Example: [INLONG-4793][Manager] Change the userName to username.
- Fixes #4793 
*Username is a complete word and should not be treated as two words.*
*Change the userName to username.*

[INLONG-4793][Manager] Change the userName to username

---

bin/inlong-daemon

- Fixes #4797
*(example:)*
- If a …

[INLONG-4797][Manager] Remove the register dataproxy for standalone

---

bin/init-config.sh
conf/inlong.conf
inlong-manager/manager-plugins/src/main/resources/flink-sort-plugin.properties

- Fixes #4799
*(example:)*
- If a …

[INLONG-4799][Manager] Add Flink plugin initialization for standalone deployment

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java

- Fixes #4803
*(example:)*
- If a …

[INLONG-4803][DataProxy] Add warn log when there is no mq info when start for the first time

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/codec/ProtocolEncoder.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/EncryptConfigEntry.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/EncryptInfo.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/UdpClientExample.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/EncryptUtil.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java
inlong-sdk/dataproxy-sdk/src/test/java/org/apache/inlong/sdk/dataproxy/EncryptUtilTest.java

[INLONG-4790][SDK] Upgrade DES encryption decryption to AES

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/TubeSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java
pom.xml

- Fixes #4816
*(example:)*
- If a …

[INLONG-4816][DataProxy] Add warn log when there is no TubeMQ info when start for the first time

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/mq/CreateTubeTopicTaskListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/mq/DeletePulsarResourceTaskListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/mq/DeletePulsarTopicTaskListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/mq/PulsarResourceCreateSelector.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/mq/PulsarResourceDeleteSelector.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/mq/PulsarTopicCreateSelector.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/mq/PulsarTopicDeleteSelector.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/mq/util/PulsarOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/DeleteGroupWorkflowDefinition.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/listener/GroupTaskListenerFactory.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/listener/StreamTaskListenerFactory.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/stream/DeleteStreamWorkflowDefinition.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/definition/ServiceTaskType.java

- Fixes #4811 
As see in topic
*(example:)* …

[INLONG-4811][Manager] Add delete MQ task in group and stream workflow definition

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/Db.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/JobProfileDb.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/RocksDbImp.java

When the manager module initializes the loading job, the trigger object is read and an exception occurs: null value for key job.instance.id
- Fixes #4821

[INLONG-4821][Agent] Fix the error of null value for key job.instance.id

---

inlong-agent/agent-core/src/test/resources/log4j2.xml
inlong-agent/agent-plugins/src/test/resources/log4j2.xml
inlong-agent/conf/log4j2.xml
inlong-audit/conf/log4j2.xml
inlong-dataproxy/conf/log4j2.xml
inlong-dataproxy/dataproxy-source/src/main/resources/log4j2.xml
inlong-manager/manager-client-tools/src/test/resources/log4j2.xml
inlong-tubemq/conf/log4j2.xml
inlong-tubemq/tubemq-manager/conf/log4j2.xml

Add line numbers to Agent module log output
- Fixes #4824

[INLONG-4824][Log] Print line numbers in log info for all modules

---

inlong-sort-standalone/sort-standalone-source/pom.xml
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/clickhouse/ClickHouseChannelWorker.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/clickhouse/ClickHouseIdConfig.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/clickhouse/ClickHouseSink.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/clickhouse/ClickHouseSinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/clickhouse/DefaultEventHandler.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/clickhouse/IEventHandler.java

- Title: [INLONG-4726][SortStandalone] Support ClickHouse sink
- Fixes #4726 
*(example:)*

[INLONG-4726][SortStandalone] Support ClickHouse sink

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/ZookeeperEnabledSelector.java

- Title : [INLONG-4830][Manager]  Change log level to warning 
- Fixes #4830 
*(example:)*

[INLONG-4830][Manager] Change log level to warning

---

docker/kubernetes/templates/mysql-pvc.yaml

[INLONG-4826][Kubernetes] Change storageClassName location
- Fixes #4826 
Change storageClassName location
Change storageClassName location

[INLONG-4826][Kubernetes] Change storageClassName location

---

inlong-dashboard/src/pages/Clusters/config/TubeMQ.tsx

Update he Tube configuration form,add masterRpcUrl and update masterUrl to masterWebUrl.
- Fixes #4845 
Add masterRpcUrl
Update masterUrl to masterWebUrl
- [* ] This change is a trivial rework/code cleanup without any test coverage.
*(example:)*

[INLONG-4845][Dashboard] Update the Tube configuration form

---

docker/docker-compose/docker-compose.yml
inlong-audit/audit-docker/Dockerfile
inlong-audit/audit-docker/audit-docker.sh
inlong-dataproxy/dataproxy-docker/Dockerfile
inlong-dataproxy/dataproxy-docker/dataproxy-docker.sh

- Fixes #4838
*(example:)*
- If a …

[INLONG-4838][Docker] Add MQ Type environment for Audit and DataProxy

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/BindTagRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/ClusterNodeRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/ClusterRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/ClusterTagRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/pulsar/PulsarClusterRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/common/SaveValidation.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/common/UpdateValidation.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/consumption/ConsumptionInfo.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/node/DataNodeRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/SinkPageRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/SinkRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/hive/HiveSinkRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/SourcePageRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/source/SourceRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/transform/TransformRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/user/UserInfo.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamTransformEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/StreamTransformEntityMapper.xml
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/transform/StreamTransformServiceTest.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/DataNodeController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java

- Fixes #4847
Add prompt message for the non-blank check.

[INLONG-4847][Manager] Add prompt message for the non-blank check

---

inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/WebBaseTest.java
inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/controller/AnnoControllerTest.java

- Fixes #4852 
*The unit test of manager-web used deprecated APPLICATION_JSON_UTF8*
*Replace deprecated APPLICATION_JSON_UTF8 with APPLICATION_JSON*

[INLONG-4852][Manager] Replace deprecated APPLICATION_JSON_UTF8 with APPLICATION_JSON

---

inlong-dashboard/src/components/AccessHelper/FieldsConfig/dataFields.tsx
inlong-dashboard/src/components/Layout/index.tsx
inlong-dashboard/src/pages/AccessDetail/DataStream/helper.ts
inlong-dashboard/src/pages/ClusterTags/TagDetailModal.tsx
inlong-dashboard/src/pages/Login/index.tsx

[INLONG-4857][Dashboard] Unable to get stream information

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/pb/config/pojo/GetProxyConfigByAgentResponse.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/pb/config/pojo/ProxyClusterConfig.java

[INLONG-4871][SDK] The generateMd5 method generate md2 not md5

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkOperation.java
inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/enums/ConnectorJarType.java

- Title Example:[INLONG-4812][Manager] Choose the specified connector instead of all
- Fixes #4812 
Choose the specified connector instead of all
Choose the specified connector instead of all
*(example:)* …

[INLONG-4812][Manager] Choose the specified connector instead of all

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java

Re-issue failed source task when configuration is fixed.
- Fixes #4875

[INLONG-4875][Manager] Re-issue failed source task

---

inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/AnnoController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/AuditController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/ConsumptionController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/DataNodeController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/HeartbeatController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamConfigLogWebController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSinkController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSourceController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamTransformController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/UserController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/WorkflowApproverController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/WorkflowController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/WorkflowEventController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/AgentController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DBCollectorController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenClusterController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenHeartbeatController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/SortController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/StreamConfigLogController.java

- Fixes #4900
Modify the request address of the API for quick search.
Move the API address from the classes header to methods header.

[INLONG-4900][Manager] Modify the request address of the API for quick search

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/snapshot/BinlogSnapshotBase.java

-  [INLONG-4899][Agent] Create binlog offset file Exception
- Fixes #4899 
*(example:)* …

[INLONG-4899][Agent] Create binlog offset file Exception

---

inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/TErrCodeConstants.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/paramcheck/PBParameterUtils.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/utils/WebParameterUtils.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/TMaster.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/DefaultMetaDataService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/MetaDataService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/MetaConfigMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/TopicDeployMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsMetaConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsTopicDeployMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebAdminGroupCtrlHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebGroupConsumeCtrlHandler.java
inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/common/PBParameterTest.java

[INLONG-4883][TubeMQ] No error report for incorrect topic subscription

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/OffsetRecordInfo.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/TServerConstants.java

[INLONG-4927][TubeMQ] Add version info in history offset record

---

inlong-audit/bin/proxy-start.sh

[INLONG-4921][Audit] Set the configuration file to an absolute path

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/cluster/ClusterTagRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupApproveRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/group/InlongGroupRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/workflow/WorkflowApprover.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterEntityMapper.xml
inlong-manager/manager-dao/src/test/java/org/apache/inlong/manager/dao/DaoBaseTest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/common/utils/ValidationUtilsTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/group/GroupServiceTest.java

- Fixes #4914
List inlong cluster error when the keyword was not null.

[INLONG-4914][Manager] List inlong cluster error when the keyword was not null

---

inlong-audit/conf/application.properties

[INLONG-4919][Audit] Delete the wrong driver-class-name

---

inlong-dashboard/src/pages/AccessDetail/DataSources/index.tsx
inlong-dashboard/src/pages/AccessDetail/DataStorage/index.tsx

[INLONG-4865][Dashboard] The storage config can still be modified after submitting for approval

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerServiceServer.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/MessageStoreManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/nodeinfo/ConsumerNodeInfo.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/web/BrokerAdminServlet.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/TMaster.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodeconsumer/ConsumerInfo.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebOtherInfoHandler.java

[INLONG-4942][TubeMQ] Add the display of the IP address of consumer

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/UserServiceImpl.java

- Fixes #4951 
The problem is manager only deals with the situation where tag name is changed. Other tag property changes like in-charges should also be properly dealt with.

[INLONG-4951][Manager] Fix cluster tag property update error

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/Utils.java

- Fixes #4995
Refactor code to avoid CodeQL scan warning.

[INLONG-4995][SDK] Refactor code to avoid CodeQL Scan warning

---

.github/workflows/codeql-analysis.yml
.github/workflows/codeql_analysis.yml

Fixes #2440
Add a workflow to Scan InLong common vulnerabilities.

[INLONG-2440][CI] Add a workflow to Scan InLong common vulnerabilities

---

bin/inlong-daemon
inlong-audit/audit-docker/audit-docker.sh
inlong-dataproxy/dataproxy-docker/dataproxy-docker.sh
inlong-tubemq/tubemq-docker/tubemq-all/tubemq-docker.sh

Fix dataproxy-docker script judgement
- Fixes #5009 
Fix dataproxy-docker script judgement
Fix dataproxy-docker script judgement
Bash cannot recognize symbol "==". Change it into "="

[INLONG-5009][Docker] Fix dataproxy-docker script judgement

---

inlong-sort/sort-connectors/elasticsearch-6/pom.xml
inlong-sort/sort-connectors/elasticsearch-7/pom.xml
inlong-sort/sort-connectors/elasticsearch-base/pom.xml

- Fixes #5012
Remove the duplicate declaration of elasticsearch7.

[INLONG-5012][Sort] Remove the duplicate declaration of elasticsearch7

---

inlong-audit/bin/proxy-start.sh
inlong-audit/bin/store-start.sh

Fixes: #4983 
modify the proxy-start command to start it rightly
update the startup command

[INLONG-4983][Audit] Update audit-proxy startup command

---

.github/workflows/ci_build.yml
.github/workflows/codeql_analysis.yml
pom.xml

Improve Vulnerabilities Scan build speed
- Fixes #5016 
Improve Vulnerabilities Scan build speed
Add repository to improve speed
16mins lost on repository:

[INLONG-5016][CI] Improve Vulnerabilities Scan build speed

---

inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/InnerInlongManagerClientTest.java

- Fixes #5026
Remove the real IP address.

[INLONG-5026][Manager] Remove the real IP address

---

inlong-dashboard/src/components/AccessHelper/DataSourcesEditor/CreateModal.tsx
inlong-dashboard/src/components/AccessHelper/DataStorageEditor/DetailModal.tsx
inlong-dashboard/src/configs/routes/index.tsx
inlong-dashboard/src/pages/AccessDetail/DataStream/StreamItemModal.tsx
inlong-dashboard/src/pages/AccessDetail/DataStream/helper.ts
inlong-dashboard/src/pages/AccessDetail/DataStream/index.tsx
inlong-dashboard/src/pages/AccessDetail/Info/index.tsx
inlong-dashboard/src/pages/ClusterTags/ClusterBindModal.tsx
inlong-dashboard/src/pages/ClusterTags/TagDetailModal.tsx
inlong-dashboard/src/pages/Clusters/CreateModal.tsx
inlong-dashboard/src/pages/Clusters/NodeEditModal.tsx
inlong-dashboard/src/pages/ConsumeCreate/Info/index.tsx
inlong-dashboard/src/pages/ConsumeDetail/Info/config.tsx
inlong-dashboard/src/pages/ConsumeDetail/Info/index.tsx
inlong-dashboard/src/pages/ConsumeDetail/common.d.ts
inlong-dashboard/src/pages/ConsumeDetail/index.tsx
inlong-dashboard/src/pages/UserManagement/DetailModal.tsx

[INLONG-5035][Dashboard] Support version control for backend APIs

---

inlong-dashboard/src/components/ConsumeHelper/BusinessSelect/MyBusinessModal.tsx
inlong-dashboard/src/pages/ConsumeDashboard/index.tsx
inlong-dashboard/src/pages/UserManagement/index.tsx

[INLONG-5059][Dashboard] Unable to get total number

---

inlong-dashboard/src/pages/AccessDetail/DataSources/index.tsx
inlong-dashboard/src/pages/AccessDetail/DataStorage/index.tsx

[INLONG-5056][Dashboard] Unable to get stream list when creating

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java

- Fixes #5055
Data won't send because of pulsar client error:
Debug and analysis shows that it originates from a NP problem:
Eager initialization and use clear instead of nulling.

[INLONG-5055][Dataproxy] Fix NPE error of Pulsar client

---

inlong-dashboard/src/pages/AccessDetail/Info/index.tsx

[INLONG-5077][Dashboard] Cannot read properties of undefined (reading 'version')

---

inlong-dashboard/src/components/MetaData/StorageEs.tsx

- Fixes #5082
Fix Elasticsearch fields cannot be saved.

[INLONG-5082][Dashboard] Fix Elasticsearch fields cannot be saved

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsarzone/PulsarClusterProducer.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/InLongTopicManagerImpl.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/kafka/AckOffsetOnRebalance.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/kafka/InLongKafkaFetcherImpl.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSource.java

- Title: [INLONG-5092][SortSdk]Change Kafka default partition assignment strategy to RangeAssignor
- Fixes #5092 
*(example:)* …

[INLONG-5092][SDK] Change Kafka default partition assignment strategy to RangeAssignor

---

inlong-sort/sort-connectors/hbase/pom.xml
inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/HBase2DynamicTableFactory.java
inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/metric/MetricData.java
inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/options/InLongOptions.java
inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/sink/HBaseDynamicTableSink.java
inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/sink/HBaseSinkFunction.java
inlong-sort/sort-connectors/hbase/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/MySqlSource.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/MySqlSourceBuilder.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/config/MySqlSourceConfig.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/config/MySqlSourceConfigFactory.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/config/MySqlSourceOptions.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/metrics/MySqlSourceReaderMetrics.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlRecordEmitter.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlTableInlongSourceFactory.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlTableSource.java
inlong-sort/sort-connectors/postgres-cdc/src/main/java/org.apache.inlong.sort.cdc.postgres/DebeziumSourceFunction.java
inlong-sort/sort-connectors/postgres-cdc/src/main/java/org.apache.inlong.sort.cdc.postgres/MetricData.java
inlong-sort/sort-connectors/postgres-cdc/src/main/java/org.apache.inlong.sort.cdc.postgres/PostgreSQLSource.java
inlong-sort/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/cdc/postgres/table/PostgreSQLTableFactory.java
inlong-sort/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/cdc/postgres/table/PostgreSQLTableSource.java
inlong-sort/sort-connectors/postgres-cdc/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
licenses/inlong-sort-connectors/LICENSE

- [INLONG-5072][Sort] Add metric computing for user query metric by label value groupId or streamId or nodeId
- Fixes #5072 
Add metric computing of mysql and postgresql and hbase for user query metric by label value groupId or streamId or nodeId
add postgres cdc table param
add mysql cdc table param
add hbase table param
add metric for mysql-cdc and postgresql-cdc and HBase

[INLONG-5072][Sort] Add metric computing of MySQL and PostgreSQL and HBase for user query metric by label

---

.github/workflows/ci_build.yml
.github/workflows/ci_ut.yml
.github/workflows/codeql_analysis.yml

[INLONG-5064][CI] Decrease Vulnerabilities Scan run time
- Fixes #5064 
Decrease Vulnerabilities Scan run time
Decrease Vulnerabilities Scan run time

[INLONG-5064][CI] Decrease Vulnerabilities Scan run time

---

inlong-distribution/pom.xml

- Fixes #5115
*(example:)*
- If a …

[INLONG-5115][POM] Remove the redundant agent dependencies

---

docker/build-docker-images.sh
inlong-manager/manager-docker/Dockerfile
inlong-manager/manager-docker/pom.xml
inlong-sort/sort-common/pom.xml
pom.xml

- Fixes #5124
*(example:)*
- If a …

[INLONG-5124][Docker] Add initial sort connectors to the manager docker image

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/DefaultSortConfigOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/ExtractNodeUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/FieldRelationUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/LoadNodeUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/TransformNodeUtils.java

Title: [INLONG-5103][Manager] Add constant field support for stream source and transform node
Fixes #5103 
Add constant field support for stream source and transform node
Constant field will be supported in stream source and transform node.
*(example:)* …

[INLONG-5103][Manager] Add constant field support for stream source and transform node

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/DefaultSortConfigOperator.java

fix NPE
- Fixes #5144 
Add check NPE for transformation list.
Execute sot success.
*(example:)*

[INLONG-5144][Manager] Fail to execute Group-InitSort

---

inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/CMakeLists.txt

[INLONG-5138][Bug][TubeMQ] compile error with gcc >= 8.0 on rapidjson

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/mysql/MySQLColumnInfo.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/mysql/MySQLSinkDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/mysql/MySQLTableInfo.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/mysql/MySQLJdbcUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/mysql/MySQLResourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/mysql/MySQLSqlBuilder.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/sink/MySQLSinkServiceTest.java
inlong-tubemq/tubemq-manager/sql/apache_tube_manager.sql

- About #5085 
*(example:)*
- If a …

[INLONG-5085][Manager] Support create MySQL databases and tables

---

README.md

- Fixes #5154
*(example:)*
- If a …

[INLONG-5154][Doc] Update the architecture image

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/mq/util/PulsarOperator.java

- Fixes #5112
Improve creating Pulsar topic by using the lookups method.
1. Add retry for creating Pulsar topic.
2. Creating Pulsar topic by using the lookups method.

[INLONG-5112][Manager] Creating Pulsar topic by using the lookups method

---

inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/CacheClusterObject.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/CacheClusterSetObject.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/CacheTopicObject.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/DataProxyConfigResponse.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/DataProxyNodeInfo.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/DataProxyNodeResponse.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/InLongIdObject.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/ProxyChannel.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/ProxyClusterObject.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/ProxySink.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/ProxySource.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/RepositoryTimerTask.java
inlong-manager/manager-service/pom.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceTest.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java

- Fixes #5136
Update the get DataProxy cluster nodes API.
Return more info for DataProxy cluster nodes.
`InlongClusterServiceTest`

[INLONG-5136][Manager] Update the get DataProxy cluster nodes API

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ConfigConstants.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyClusterConfig.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigEntry.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/Sender.java
inlong-sdk/dataproxy-sdk/src/test/java/org/apache/inlong/sdk/dataproxy/ProxyConfigManagerTest.java
inlong-sdk/dataproxy-sdk/src/test/resources/proxylist.json

…e parsing method
- [INLONG-5160][DataPorxy-SDK] Update DataProxy cluster API and response parsing method
- Fixes #5160 
*(example:)*
- If yes, how is the feature documented? (not applicable / docs …

[INLONG-5160][DataPorxySDK] Update DataProxy cluster API and response parsing method

---

docker/kubernetes/templates/_helpers.tpl
docker/kubernetes/templates/audit-statefulset.yaml
docker/kubernetes/templates/manager-statefulset.yaml
docker/kubernetes/templates/tubemq-manager-statefulset.yaml

[INLONG-5179][K8S] Add external mysql judgement for manager, audit and tube-manager
- Fixes #5179 
Add external mysql judgement for manager, audit and tube-manager
Add external mysql judgement for manager, audit and tube-manager

[INLONG-5179][Kubernetes] Add external mysql judgement for manager, audit and tube-manager

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java

- Fixes #5163
The predicate should be after getting the url2token config.

[INLONG-5163][DataProxy] Fixing Pulsar clients initialization error

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/oracle/OracleColumnInfo.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/oracle/OracleSinkDTO.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/pojo/sink/oracle/OracleTableInfo.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/oracle/OracleJdbcUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/oracle/OracleResourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/oracle/OracleSqlBuilder.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/sink/OracleSinkServiceTest.java

- About #5086 
*(example:)*
- If a …

[INLONG-5086][Manager] Support create Oracle databases and tables

---

inlong-dashboard/src/components/StaffSelect/index.tsx
inlong-dashboard/src/pages/AccessDetail/DataStream/StreamItemModal.tsx
inlong-dashboard/src/pages/AccessDetail/DataStream/config.tsx
inlong-dashboard/src/pages/Login/index.tsx

[INLONG-5213][Dashboard] Adapt to the new data structure of the stream list API

---

inlong-sdk/sort-sdk/pom.xml
inlong-sort/sort-connectors/elasticsearch-6/pom.xml
inlong-sort/sort-connectors/elasticsearch-7/pom.xml
inlong-sort/sort-connectors/iceberg-dlc/pom.xml

- Fixes #5211 
Replace 1.3.0-snapshot with project.version
change
inlong-sdk/sort-sdk/pom.xml
inlong-sort/sort-connectors/elasticsearch-6/pom.xml
inlong-sort/sort-connectors/elasticsearch-7/pom.xml
inlong-sort/sort-connectors/iceberg-dlc/pom.xml
*(example:)* …

[INLONG-5211][Sort] Replace 1.3.0-snapshot with project.version

---

inlong-dashboard/src/pages/AccessDetail/DataStream/StreamItemModal.tsx
inlong-dashboard/src/pages/AccessDetail/DataStream/config.tsx

[INLONG-5234][Dashboard] Some fields are missing when creating a new stream

---

inlong-sort/sort-connectors/connector-base/pom.xml
inlong-sort/sort-connectors/connector-base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-connectors/connector-base/src/main/java/org/apache/inlong/sort/base/metric/MetricData.java
inlong-sort/sort-connectors/connector-base/src/main/java/org/apache/inlong/sort/base/metric/SinkMetricData.java
inlong-sort/sort-connectors/connector-base/src/main/java/org/apache/inlong/sort/base/metric/SourceMetricData.java
inlong-sort/sort-connectors/hbase/pom.xml
inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/sink/HBaseSinkFunction.java
inlong-sort/sort-connectors/pom.xml
inlong-sort/sort-connectors/postgres-cdc/pom.xml
inlong-sort/sort-connectors/postgres-cdc/src/main/java/org.apache.inlong.sort.cdc.postgres/DebeziumSourceFunction.java

- Fixes #5217 
Add connector-base component for common code
add SinkMetricData and SourceMetricData

[INLONG-5217][Sort] Add connector-base component for common code

---

inlong-dashboard/src/pages/AccessDetail/DataSources/index.tsx
inlong-dashboard/src/pages/AccessDetail/DataStorage/index.tsx
inlong-dashboard/src/pages/AccessDetail/DataStream/config.tsx

[INLONG-5120][Dashboard] The list page of stream, source and sink supports status filtering

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/HttpManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java

[INLONG-5277][Agent] Fix the unmatched HTTP request method

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/atomic.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/ini_help.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/ini_help.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/logger.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/logger.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/msg_protocol.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/noncopyable.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/read_write_mutex.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/recv_buffer.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/sdk_constant.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/singleton.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/utils.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/utils.h

- [INLONG-5249][SDK] DataProxy SDK(cpp) utils file
- Fixes #5249 
*(example:)* …

[INLONG-5249][SDK] DataProxy SDK(cpp) utils file

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/executor_thread_pool.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/executor_thread_pool.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/socket_connection.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/socket_connection.h

- [INLONG-5256][SDK] DataProxy SDK(cpp) network operation and management
- Fixes #5256 
*(example:)*
- If …

[INLONG-5256][SDK] DataProxy SDK(cpp) network operation and management

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/CMakeLists.txt
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/build.sh
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/CMakeLists.txt
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/CMakeLists.txt
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/third_party/CMakeLists.txt

-[INLONG-5265][SDK] DataProxy SDK(cpp) build config
- Fixes #5265 
*(example:)* …

[INLONG-5265][SDK] DataProxy SDK(cpp) build config

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/pack_queue.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/pack_queue.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/buffer_pool.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/buffer_pool.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/send_buffer.h

- [INLONG-5253][SDK] DataProxy SDK(cpp) buffer manager
- Fixes #5253 
*(example:)* …

[INLONG-5253][SDK] DataProxy SDK(cpp) buffer manager

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/tc_api.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/sdk_core.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/sdk_core.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/user_msg.h

- [INLONG-5258][SDK] DataProxy SDK(cpp) core interface
- Fixes #5258 
*(example:)* …

[INLONG-5258][SDK] DataProxy SDK(cpp) core interface

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/client_config.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/client_config.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/proxylist_config.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/proxylist_config.h

- [INLONG-5251][SDK] DataProxy SDK(cpp) proxy client config and proxylist manager
- Fixes #5251 
*(example:)* …

[INLONG-5251][SDK] Add proxy client config and proxylist manager for DataProxy C++ SDK

---

inlong-agent/agent-core/src/test/resources/agent.properties
inlong-agent/agent-plugins/src/test/resources/agent.properties
inlong-agent/conf/agent.properties
inlong-common/src/main/java/org/apache/inlong/common/util/BasicAuth.java
inlong-dataproxy/conf/common.properties
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/AuthUtils.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/impl/InlongShiroImpl.java
inlong-manager/manager-web/src/main/resources/application.properties
inlong-manager/manager-web/src/test/resources/application.properties

- Fixes #5283
See the link above for motivation.

[INLONG-5283][Manager] Add OpenAPI authentication option (default off)

---

pom.xml

[INLONG-5294][CVE] Upgrade to gson 2.8.9

---

pom.xml

[INLONG-5292][CVE] Upgrade shiro to 1.9.1

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/disk/MsgFileStore.java

Fixes #5303
Simplify the flush check for `FileMsgStore`

[INLONG-5303][TubeMQ] Simplify MsgFileStore code

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/admin/ProxyServiceAdminEventHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/MessageFilter.java
inlong-sdk/sdk-common/src/main/java/org/apache/inlong/sdk/commons/admin/AbstractAdminEventHandler.java
inlong-sdk/sdk-common/src/main/java/org/apache/inlong/sdk/commons/admin/AdminHttpSource.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/admin/ConsumerServiceAdminEventHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/web/AbstractWebHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/MasterStatusCheckFilter.java

see https://github.com/apache/inlong/issues/5014

[INLONG-5014][CodeQL] Fix the code scanning alerts exposed by CodeQL

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongStream.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongStreamClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongStreamApi.java

- Fixes #4928 
Add inlong stream process API and inlong stream list/delete API in manager client.

[INLONG-4928][Manager] Modify inlong stream API in the Manager client

---

inlong-sort/sort-formats/format-inlongmsg-pb/src/main/resources/org.apache.flink.table.factories.Factory

- Fixes #5327 
*(example:)*
- If a …

[INLONG-5327][Sort] Add pb msg service file

---

inlong-dashboard/nginx.conf

- Fixes #5340
404 error is reported when running the dashboard container.

[INLONG-5340][Dashboard] 404 error is reported when running the dashboard container

---

inlong-dashboard/src/pages/ApprovalDetail/AccessConfig.tsx

[INLONG-5345][Dashboard] Group approval supports partial field modification

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/FieldType.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/fieldformat/ArrayFormat.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/fieldformat/DecimalFormat.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/fieldformat/MapFormat.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/fieldformat/StructFormat.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldFormatUtils.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtils.java
inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sort/util/FieldFormatUtilsTest.java

- Fixes #5333 
To support all complex field type, we use field format to describe, and serialize | deserialize method is also provided
*(example:)* …

[INLONG-5333][Manager] Add array, map, struct, decimal format

---

inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/consumer_impl.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/heartbeat.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/version.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/log/config.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/rpc/client.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/selector/ip_selector.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/selector/selector.go

- Fixes #5314 
Reconnect to another address if heartbeat encounters exception
*(example:)* …

[INLONG-5314][TubeMQ] Reconnect to another address if heartbeat encounters exception

---

inlong-dashboard/src/pages/AccessDetail/DataStream/StreamItemModal.tsx

[INLONG-5349][Dashboard] Failed to create stream

---

inlong-dashboard/src/components/AccessHelper/DataStorageEditor/DetailModal.tsx
inlong-dashboard/src/components/MetaData/index.ts

[INLONG-5355][Dashboard] SinkType config error

---

inlong-sort/sort-connectors/connector-base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-connectors/pulsar/pom.xml
inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/Constants.java
inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java
inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarDynamicTableFactory.java
inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarDynamicTableSource.java
inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/UpsertPulsarDynamicTableFactory.java
inlong-sort/sort-connectors/pulsar/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory

- Fixes #5262
Add metric report for pulsar source
Add metric report for pulsar source

[INLONG-5262][Sort] Add metric report for Pulsar source

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ErrorCodeEnum.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/WorkflowApproverService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/WorkflowApproverServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/workflow/WorkflowApproverServiceImplTest.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/WorkflowApproverController.java

- Fixes #5359
Add query workflow approver API.
WorkflowApproverServiceImplTest

[INLONG-5359][Manager] Add query workflow approver API

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/DataCollectType.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/FileJob.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/TextFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/TextFileReader.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestTextFileReader.java

This feature supports both incremental and full file content
- Fixes #5347 
1.Added configuration parameters
*TestTextFileReader

[INLONG-5347][Agent] Incremental and full reads of file contents

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/WorkflowApproverEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/WorkflowApproverEntityMapper.xml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/workflow/ApproverPageRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/workflow/ApproverRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/WorkflowApproverService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/WorkflowApproverServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/workflow/WorkflowApproverServiceImplTest.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/WorkflowApproverController.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/core/impl/WorkflowQueryServiceImpl.java

- Fixes #5368
Fix the error of updating the workflow approver.
WorkflowApproverServiceImplTest

[INLONG-5368][Manager] Fix the error of updating the workflow approver

---

inlong-tubemq/conf/broker.ini
inlong-tubemq/tubemq-server/pom.xml
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerConfig.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerServiceServer.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/stats/audit/AuditUtils.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/fileconfig/ADConfig.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/fileconfig/AbstractFileConfig.java
inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/common/ADConfigTest.java

- Fixes: https://github.com/apache/inlong/issues/5373

[INLONG-5373][TubeMQ] TubeMQ supports outputting traffic information through the audit SDK

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/UserTypeEnum.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/UserEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/UserEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/UserEntityMapper.xml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/user/UserInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/user/UserRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java
inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/AnnoController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/UserController.java

[INLONG-5369][Manager] Add user extended parameters to store 3rd party authentication info

---

inlong-sort/sort-connectors/hbase/pom.xml
inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/options/InLongOptions.java
inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/sink/HBaseSinkFunction.java

- [INLONG-5353][Sort] Fix HBase connector packaging problem and inlong metrics delimiter problem
- Fixes #5353 
Fix HBase connector packaging problem and inlong metrics delimiter problem
* modify HBase connector pom file
* modify HBase connector inlong metric delimiter

[INLONG-5353][Sort] Fix HBase connector packaging problem and inlong metrics delimiter problem

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/FileJob.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
inlong-dashboard/package-lock.json
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSource.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceDTO.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java

1.The collection mode of configuration file content can be incremental or full.
2.Line ends the regular expression.
3.Data source separator.
4.Appends file metadata parameters.
- Fixes #5382 
Enhance the ability to collect files.
*(example:)*

[INLONG-5382][Manager][Agent] Optimized the file collection configuration

---

inlong-dashboard/src/components/ConsumeHelper/FieldsConfig/basicFields.tsx
inlong-dashboard/src/pages/ApprovalDetail/ConsumeConfig.tsx
inlong-dashboard/src/pages/ConsumeDashboard/config.tsx
inlong-dashboard/src/pages/ConsumeDetail/Info/config.tsx
inlong-dashboard/src/pages/ConsumeDetail/Info/index.tsx
inlong-dashboard/src/pages/ConsumeDetail/index.tsx

[INLONG-5391][Dashboard] Unified consumption creation/management logic

---

inlong-dashboard/src/components/Layout/NavWidget/index.tsx
inlong-dashboard/src/pages/ApprovalManagement/DetailModal.tsx
inlong-dashboard/src/pages/UserManagement/DetailModal.tsx

- Fixes https://github.com/apache/inlong/issues/5390

[INLONG-5390][Dashboard] Optimize user editing, add and modify personal keys

---

inlong-agent/agent-docker/agent-docker.sh

[INLONG-5393][Agent] Fix docker image of agent stuck in starting
- Fixes #5393 
Fix docker image of agent stuck in starting
See issue #5393 
See issue #5393

[INLONG-5393][Agent] Fix docker image of agent stuck in starting

---

inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/function/EncryptFunction.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/function/EncryptFunctionTest.java

- Fixes #5404 
[INLONG-5404][Sort] Fix sort EncryptFunction checkstyle
[INLONG-5404][Sort] Fix sort EncryptFunction checkstyle

[INLONG-5404][Sort] Fix sort EncryptFunction checkstyle

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/postgresql/PostgreSQLColumnInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/postgresql/PostgreSQLTableInfo.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/postgresql/PostgreSQLJdbcUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/postgresql/PostgreSQLResourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/postgresql/PostgreSQLSqlBuilder.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/PostgreSQLSinkServiceTest.java

- Fixes #5411 
*(example:)*
- If a …

[INLONG-5411][Manager] Optimize the creation code of databases and tables of PostgreSQL

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ServiceDiscoveryUtils.java

[INLONG-5408][SDK] Fix the NullPointerException while call getManagerIpList

---

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/InLongTopicFetcher.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/Interceptor.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/interceptor/MsgTimeInterceptor.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/kafka/InLongKafkaFetcherImpl.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/pulsar/InLongPulsarFetcherImpl.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/tube/InLongTubeFetcherImpl.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/util/TimeUtil.java
inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/InLongTopicManagerImplTest.java
inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/decode/MessageDeserializerTest.java
inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/kafka/InLongKafkaFetcherImplTest.java
inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/pulsar/InLongPulsarFetcherImplTest.java
inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/tube/InLongTubeFetcherImplTest.java

- Fixes #5095
sort sdk support consume message in a certain time interval
*(example:)*

[INLONG-5095][SortSDK] Support consumes data stream from a specified time

---

inlong-dashboard/src/locales/cn.json
inlong-dashboard/src/locales/en.json
inlong-dashboard/src/pages/ApprovalManagement/config.tsx
inlong-dashboard/src/pages/ApprovalManagement/index.tsx
inlong-dashboard/src/pages/UserManagement/DetailModal.tsx
inlong-dashboard/src/pages/UserManagement/config.tsx

- Fixes https://github.com/apache/inlong/issues/5421

[INLONG-5421][Dashboard] Optimize the approval management list

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/GroupInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/InlongMetric.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNode.java
inlong-sort/sort-connectors/connector-base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-connectors/kafka/pom.xml
inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/DynamicKafkaDeserializationSchema.java
inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicSource.java
inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicTableFactory.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java

- Fixes #5158 
add metric for kafka source with flink metrics group and audit sdk
add metric for kafka source with flink metrics group and audit sdk

[INLONG-5158][Sort] Sort add metric for kafka source with flink metrics group and audit sdk

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/fileconfig/ADConfig.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/fileconfig/AbstractFileConfig.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/fileconfig/PrometheusConfig.java
inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/broker/BrokerConfigTest.java
inlong-tubemq/tubemq-server/src/test/resources/broker_audit_prom_1.ini
inlong-tubemq/tubemq-server/src/test/resources/broker_audit_prom_2.ini

[INLONG-5435][TubeMQ] Adjust the parameter requirements in Audit and Prometheus sections

---

inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/auth/Authentication.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/auth/DefaultAuthentication.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/auth/SecretAuthentication.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/auth/SecretTokenAuthentication.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/auth/TokenAuthentication.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/util/JsonUtils.java

- [INLONG-5424][Manager] Fix json serialization for Authentication when get inlongGroupInfo
- Fixes #5424 
Fix json serialization for Authentication when get inlongGroupInfo
* modify UT for inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java, you can reproduce problem if you modify this UT
* Add annation for Authentication

[INLONG-5424][Manager] Fix JSON serialization error for Authentication when getting inlongGroupInfo

---

docker/build-docker-images.sh

[INLONG-5439][Docker] Fix arm docker build script
- Fixes #5439 
Fix arm docker build script
Fix arm docker build script
Fix arm docker build script

[INLONG-5439][Docker] Fix arm docker build script

---

inlong-dashboard/src/locales/cn.json
inlong-dashboard/src/locales/en.json
inlong-dashboard/src/pages/Clusters/NodeEditModal.tsx

- Fixes https://github.com/apache/inlong/issues/5406

[INLONG-5406][Dashboard] No restrictions are added to the input of port numbers, such as dataproxy node

---

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/dispatch/DispatchManager.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/dispatch/DispatchProfile.java

[INLONG-5423][Sort] Revise invalid partition time when dispatch messages

---

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/InLongTopicFetcher.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/Interceptor.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/Seeker.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SeekerFactory.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/entity/InLongTopic.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/QueryConsumeConfigImpl.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/interceptor/MsgTimeInterceptor.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/kafka/AckOffsetOnRebalance.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/kafka/InLongKafkaFetcherImpl.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/kafka/KafkaSeeker.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/pulsar/InLongPulsarFetcherImpl.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/pulsar/PulsarSeeker.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/tube/InLongTubeFetcherImpl.java
inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/pulsar/InLongPulsarFetcherImplTest.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsSinkContext.java

[INLONG-5418][SDK] Sort SDK support seek topic or partitions to a given timestamp

---

inlong-dashboard/src/components/AccessHelper/DataSourcesEditor/CreateModal.tsx
inlong-dashboard/src/components/AccessHelper/DataSourcesEditor/index.tsx
inlong-dashboard/src/components/AccessHelper/DataStorageEditor/DetailModal.tsx
inlong-dashboard/src/components/AccessHelper/DataStorageEditor/Editor.tsx
inlong-dashboard/src/components/AccessHelper/FieldsConfig/dataFields.tsx
inlong-dashboard/src/meta/sinks/clickhouse.tsx
inlong-dashboard/src/meta/sinks/common/sourceFields.ts
inlong-dashboard/src/meta/sinks/es.tsx
inlong-dashboard/src/meta/sinks/greenplum.tsx
inlong-dashboard/src/meta/sinks/hbase.tsx
inlong-dashboard/src/meta/sinks/hive.tsx
inlong-dashboard/src/meta/sinks/iceberg.tsx
inlong-dashboard/src/meta/sinks/index.ts
inlong-dashboard/src/meta/sinks/kafka.tsx
inlong-dashboard/src/meta/sinks/mysql.tsx
inlong-dashboard/src/meta/sinks/oracle.tsx
inlong-dashboard/src/meta/sinks/postgreSql.tsx
inlong-dashboard/src/meta/sinks/sqlServer.tsx
inlong-dashboard/src/meta/sinks/tdsqlPostgreSql.tsx
inlong-dashboard/src/meta/sources/autoPush.ts
inlong-dashboard/src/meta/sources/binLog.ts
inlong-dashboard/src/meta/sources/file.ts
inlong-dashboard/src/meta/sources/index.ts
inlong-dashboard/src/pages/AccessDetail/DataSources/index.tsx
inlong-dashboard/src/pages/AccessDetail/DataStorage/index.tsx

[INLONG-5456][Dashboard] Support source/sink metadata management

---

inlong-dashboard/src/components/AccessHelper/FieldsConfig/businessFields.tsx
inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/ut/Kafka2HiveTest.java
inlong-manager/manager-client-tools/src/test/resources/create_group.json
inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/impl/InlongGroupImplTest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/pulsar/InlongPulsarInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/pulsar/InlongPulsarRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java

Fix  selection and creation are inconsistent.
- Fixes #5419 
No message
No message

[INLONG-5419][Manager][Dashboard] Fix the Pulsar creates model of queue error

---

inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/MQClusterInfo.java

[INLONG-5433][DataProxy] Select the corresponding configuration parameters according to the type of MQ

---

inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/ElasticsearchSinkBase.java
inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/table/RowElasticsearchSinkFunction.java

Title: [INLONG-5470][Sort] Fix compile error
Fixes #5470 
Fix compile error
Fix the code of compile error.
*(example:)* …

[INLONG-5470][Sort] Fix compile error

---

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsCallback.java
licenses/inlong-sort-standalone/LICENSE
pom.xml

[INLONG-5448][Sort] Optimize cls callback when send failed

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/BinlogReader.java

- [INLONG-5164][Agent] BinlogReader adds audit and metrics
- Fixes #5164 
*(example:)* …

[INLONG-5164][Agent] BinlogReader adds audit and metrics

---

inlong-sort/sort-connectors/mysql-cdc/pom.xml
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/DebeziumSourceFunction.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/MySqlSource.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlTableSource.java

- [INLONG-5478][Manager] Add MySQL connector inlong metric feature for no primary key table
- Fixes #5478 
Add MySQL connector inlong metric feature for no primary key table
* Add metric computing for no primary key table

[INLONG-5478][Manager] Add MySQL connector inlong metric feature for no primary key table

---

inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/table/Elasticsearch6DynamicSink.java
inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/ElasticsearchSink.java
inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7DynamicSink.java
inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7DynamicSinkFactory.java
inlong-sort/sort-connectors/elasticsearch-base/pom.xml
inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/table/RowElasticsearchSinkFunction.java

- Fixes #5210 
Add reporting metrics for Elasticsearch 7 connector and audit SDK
Elasticsearch 7 connector

[INLONG-5210][Sort] Add reporting metrics for Elasticsearch 7 connector and audit SDK

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/FileJob.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSource.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceDTO.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceRequest.java

Support metadata filters by labels.
- Fixes #5474 
No
No

[INLONG-5474][Manager][Agent] Add metadata parameter

---

inlong-manager/manager-dao/src/main/resources/mappers/ClusterSetMapper.xml

- Title: [INLONG-5497][Manager] DataProxyConfigRepository get error field name
- Fixes #5497 
*(example:)* …

[INLONG-5497][Manager] DataProxyConfigRepository get error field name

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongCluster.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongClusterImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/heartbeat/HeartbeatManager.java

- Fixes #5476
1. the cache remove cause should be filtered
2. should use cleanup to do eager eviction in time 
https://github.com/ben-manes/caffeine/wiki/Cleanup
This is exactly the case of heartbeat scenario
3. Query by clusterTag is broken, fix it

[INLONG-5476][Manager] Fix heartbeat status and node list query problem

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java

- Fixes #5499 
Make sure after receiving the command from the agent, the data source will change to normal state
After updating the data source status, return to version correctly

[INLONG-5499][Manager] Fix the status of the data source was wrong

---

inlong-manager/manager-web/sql/apache_inlong_manager.sql

- Title Example: [INLONG-5501][Component] Title of the pull request
*(The following *5501* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)*
- Fixes #5501
*(example:)*
- If a …

[INLONG-5501][Manager] Repair type of workflow_process.form_data when data too long

---

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaProducerCluster.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/PartitionerSelector.java
inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/kafka/PartitionerSelectorTest.java

[INLONG-5451][Sort] Kafka sink use customized partitioner

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java

- [INLONG-5517][Manager] Fix not write back version data for manager cient when update source or sink or transform
- Fixes #5517 
Fix not write back version data for manager cient when update source or sink or transform
* modify InlongStreamImpl about adding write back version data

[INLONG-5517][Manager] Fix not write back version when updating operate in manager client

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/FunctionParam.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/function/JsonGetterFunction.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/function/JsonGetterFunction.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/NativeFlinkSqlParser.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/function/JsonGetterFunctionTest.java
inlong-sort/sort-formats/format-inlongmsg-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgDeserializationSchema.java

- Fixes #5485 
[INLONG-5485][Sort] support json udf getter and json getter function in sort
[INLONG-5485][Sort] support json udf getter and json getter function in sort
run ut success

[INLONG-5485][Sort] Support JSON UDF getter and JSON getter function

---

inlong-dashboard/src/components/Layout/index.tsx
inlong-dashboard/src/configs/menus/index.ts
inlong-dashboard/src/i18n.ts

[INLONG-5523][Dashboard] Support menu permission control

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarResourceOperator.java

- Fixes #5491 
Fix pulsar failed to configure nonpartitioned topic problem
When creating topic, judge whether to partition

[INLONG-5491][Manager] Fix the error of configuring the Pulsar nonpartitioned topic

---

inlong-sort/sort-connectors/base/pom.xml
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/SinkMetricData.java
inlong-sort/sort-connectors/hive/pom.xml
inlong-sort/sort-connectors/hive/src/main/java/org/apache/inlong/sort/hive/HiveTableSink.java
inlong-sort/sort-connectors/hive/src/main/java/org/apache/inlong/sort/hive/filesystem/AbstractStreamingWriter.java
inlong-sort/sort-connectors/hive/src/main/java/org/apache/inlong/sort/hive/filesystem/CompactFileWriter.java
inlong-sort/sort-connectors/hive/src/main/java/org/apache/inlong/sort/hive/filesystem/StreamingFileWriter.java
inlong-sort/sort-connectors/hive/src/main/java/org/apache/inlong/sort/hive/filesystem/StreamingSink.java
inlong-sort/sort-connectors/hive/src/main/java/org/apache/inlong/sort/hive/table/HiveTableInlongFactory.java
inlong-sort/sort-connectors/iceberg/pom.xml
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/FlinkDynamicTableFactory.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/IcebergTableSink.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/DeltaManifests.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/DeltaManifestsSerializer.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/FlinkManifestUtil.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/FlinkSink.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/IcebergFilesCommitter.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/IcebergStreamWriter.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/ManifestOutputFileFactory.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/PartitionKeySelector.java

[INLONG-5488][Sort] Add metric for iceberg and dlc with flink metrics group and audit sdk
- Fixes #5488 
Enrich iceberg and dlc metric ability.
add metric output for iceberg and dlc.

[INLONG-5488][Sort] Add metric for iceberg and dlc with flink metrics group and audit sdk

---

inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/table/Elasticsearch6DynamicSink.java
inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/table/Elasticsearch6DynamicSinkFactory.java
inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7DynamicSinkFactory.java
inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/table/RowElasticsearchSinkFunction.java

- Fixes #5484 
Add audit info for Elasticsearch 6 connector and report metric when delete mode
Elasticsearch 6 connector and sink function

[INLONG-5484][Sort] Add audit info for Elasticsearch 6 connector and report metric when delete mode

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/DefaultInlongStreamBuilder.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java

Some objects like inlong group's version is not set before updating cause server to fail.
- Fixes #5529

[INLONG-5529][Manger] Fix version not set error before updating inlong data objects.

---

inlong-dashboard/src/pages/UserManagement/DetailModal.tsx

- Fixes https://github.com/apache/inlong/issues/5522

[INLONG-5522][Dashboard] Disable editing of user roles and names

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/DefaultInlongStreamBuilder.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongStreamClient.java

[INLONG-5536][Manger] Fix version missing when updating stream info

---

inlong-sort/sort-connectors/sqlserver-cdc/pom.xml
inlong-sort/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/cdc/sqlserver/SqlServerSource.java
inlong-sort/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/cdc/sqlserver/table/DebeziumSourceFunction.java
inlong-sort/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/cdc/sqlserver/table/SqlServerTableFactory.java
inlong-sort/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/cdc/sqlserver/table/SqlServerTableSource.java
inlong-sort/sort-connectors/sqlserver-cdc/src/main/resources/META-INF.services/org.apache.flink.table.factories.Factory
licenses/inlong-sort-connectors/LICENSE

- Fixes #5156 
Add metric for sql server source with flink metrics group
Add metric for sql server source with flink metrics group

[INLONG-5156][Sort] Add metric for SQLServer source with Flink metrics group

---

inlong-sort/sort-connectors/pulsar/pom.xml
inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java
inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarDynamicTableFactory.java
inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarDynamicTableSource.java
inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/UpsertPulsarDynamicTableFactory.java

- Fixes #5352 
[INLONG-5352][Sort] Add audit report for pulsar source
[INLONG-5352][Sort] Add audit report for pulsar source
run ut success

[INLONG-5352][Sort] Add audit report for Pulsar source

---

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/SourceMetricData.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/util/ValidateMetricOptionUtils.java
inlong-sort/sort-connectors/mysql-cdc/pom.xml
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/DebeziumSourceFunction.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/MySqlSource.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/MySqlSource.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/MySqlSourceBuilder.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/config/MySqlSourceConfig.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/config/MySqlSourceConfigFactory.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/config/MySqlSourceOptions.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/metrics/MySqlSourceReaderMetrics.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlRecordEmitter.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlTableInlongSourceFactory.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlTableSource.java

- [INLONG-5459][Sort] Add Audit for mysql extract node
- Fixes #5459 
Add Audit for mysql extract node
* Add inlong audit option for mysql cdc connector
* Add audit computing for mysql extract node

[INLONG-5459][Sort] Add audit for MySQL extract node

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/pojo/MQClusterConfig.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/SimpleMessageTubeSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/TubeSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/MsgDedupHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/TubeProducerHolder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/TubeUtils.java

[INLONG-5538][DataProxy] Optimize the Producer construction logic in TubeSink

---

inlong-common/src/main/java/org/apache/inlong/common/metric/MetricListenerRunnable.java

[INLONG-5553][Common] Adjust the log output level of MetricListenerRunnable

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/AttributeConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/ConfigConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/PulsarSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/TubeSink.java

[INLONG-5551][DataProxy] Add metric log output information in TubeSink

---

inlong-sort/sort-connectors/oracle-cdc/pom.xml
inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/DebeziumSourceFunction.java
inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/OracleSource.java
inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/table/OracleTableSource.java
inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/table/OracleTableSourceFactory.java

-[INLONG-5462][Sort] Add audit for Oracle extract Node
- Fixes #5462 
Add audit for Oracle extract Node
* Add inlong.audit option for Oracle extract Node
* Add audit computing for Oracle extract Node

[INLONG-5462][Sort] Add audit for Oracle extract Node

---

inlong-sort/sort-connectors/postgres-cdc/pom.xml
inlong-sort/sort-connectors/postgres-cdc/src/main/java/org.apache.inlong.sort.cdc.postgres/DebeziumSourceFunction.java
inlong-sort/sort-connectors/postgres-cdc/src/main/java/org.apache.inlong.sort.cdc.postgres/PostgreSQLSource.java
inlong-sort/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/cdc/postgres/table/PostgreSQLTableFactory.java
inlong-sort/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/cdc/postgres/table/PostgreSQLTableSource.java

- [INLONG-5460][Sort] Add Audit for postgreSQL extract node
- Fixes #5460
Add Audit for postgreSQL extract node
* Add inlong.audit option for postgreSQL extract node
* Add audit computing for  postgreSQL extract node

[INLONG-5460][Sort] Add Audit for postgreSQL extract node

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/stats/prometheus/BrokerPromMetricService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/stats/prometheus/MasterPromMetricService.java

[INLONG-5567][TubeMQ] Master start failed with NullPointerException

---

docker/kubernetes/templates/mysql-configmap.yaml
docker/kubernetes/templates/mysql-statefulset.yaml

Add configmap.yaml for mysql to add some custom configuration
- Fixes #5527 
Add configmap.yaml for mysql to add some custom configuration
Add configmap.yaml for mysql to add some custom configuration

[INLONG-5527][Docker] Add configmap.yaml for mysql to add some custom configuration

---

inlong-manager/manager-web/assembly.xml
inlong-manager/pom.xml

- Fixes #5570
*Add manager client packages into the lib directory.*
*(example:)*

[INLONG-5570][Manager] Add manager client packages into the lib directory

---

inlong-sort/sort-connectors/mongodb-cdc/pom.xml
inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/DebeziumSourceFunction.java
inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/MongoDBSource.java
inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/table/MongoDBTableSource.java
inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/table/MongoDBTableSourceFactory.java

- [INLONG-5461][Sort] Add Audit for mongoDB extract node
- Fixes #5461 
Add Audit for mongoDB extract node
* Add inlong.audit for mongoDB extract node
* Add audit computing for mongoDB extract node

[INLONG-5461][Sort] Add audit for MongoDB extract node

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/ClientFactory.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/WorkflowApproverClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/WorkflowApproverApi.java
inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java
inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/WorkflowApproverClientTest.java

- Fixes #5559 
Supplement the workflow approver API in the manager client
Supplement the workflow approver API in the manager client
- WorkflowApproverClientTest

[INLONG-5559][Manager] Supplement the workflow approver API in the manager client

---

docker/kubernetes/templates/agent-statefulset.yaml
docker/kubernetes/templates/audit-statefulset.yaml
docker/kubernetes/templates/dashboard-statefulset.yaml
docker/kubernetes/templates/dataproxy-statefulset.yaml
docker/kubernetes/templates/manager-statefulset.yaml
docker/kubernetes/templates/mysql-statefulset.yaml
docker/kubernetes/templates/tubemq-broker-statefulset.yaml
docker/kubernetes/templates/tubemq-manager-statefulset.yaml
docker/kubernetes/templates/tubemq-master-statefulset.yaml
docker/kubernetes/templates/zookeeper-statefulset.yaml

[INLONG-5583][Kubernetes] Add timezone to helm chart
- Fixes #5583 
Add timezone to helm chart
Add timezone to helm chart
Add timezone to helm chart

[INLONG-5583][Kubernetes] Add timezone to helm chart

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/LookupOptions.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/RedisConstant.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/enums/ExtractMode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/enums/RedisCommand.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/enums/RedisMode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/ExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/RedisExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/relation/InnerTemporalJoin.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/relation/JoinRelation.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/relation/LeftOuterTemporalJoin.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/relation/NodeRelation.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/relation/TemporalJoin.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/RedisExtractNodeTest.java
inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/config/RedisOptions.java
inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/table/RedisDynamicTableFactory.java
inlong-sort/sort-core/pom.xml
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/RedisTemporalJoinSqlParseTest.java

Title: [INLONG-5576][Sort] Add redis extract node and support temporal join
Fixes #5576 
Add redis extract node and support temporal join for FlinkSqlParser.
1.Add RedisExtractNode
2.Support temporal join(left and inner join) for FlinkSqlParser
*(example:)* …

[INLONG-5576][Sort] Add Redis extract node and support temporal join

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/KafkaConstant.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/OracleConstant.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/ExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/MongoExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/OracleExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/PulsarExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/SqlServerExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/ClickHouseLoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/DLCIcebergLoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/ElasticsearchLoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/GreenplumLoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/HiveLoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/IcebergLoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/KafkaLoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/MySqlLoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/OracleLoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/PostgresLoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/SqlServerLoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/TDSQLPostgresLoadNode.java
inlong-sort/sort-connectors/postgres-cdc/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
inlong-sort/sort-connectors/pulsar/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
inlong-sort/sort-connectors/sqlserver-cdc/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory

- [INLONG-5580][Sort] Add inlongMetric interface for node
- Fixes #5580
Add inlongMetric interface for node
* Add  inlongMetric interface for some node
* Modify connector option for some node
* Fix sqlserver resource 
* Remove duplication license header for postgres

[INLONG-5580][Sort] Add InlongMetric interface for extract and load nodes

---

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/ClientContext.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/Configurable.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/InlongTopicManager.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/InlongTopicManagerFactory.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/Interceptor.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/Seeker.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SingleTopicFetcher.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SingleTopicFetcherBuilder.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClientConfig.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClientFactory.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/TopicFetcher.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/TopicFetcherBuilder.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/TopicManager.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/kafka/AckOffsetOnRebalance.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/kafka/KafkaSeeker.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/kafka/KafkaSingleTopicFetcher.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/kafka/KafkaSingleTopicFetcherBuilder.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/pulsar/PulsarSeeker.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/pulsar/PulsarSingleTopicFetcher.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/pulsar/PulsarSingleTopicFetcherBuilder.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/tube/TubeConsumerCreater.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/tube/TubeConsumerCreator.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/tube/TubeSingleTopicFetcher.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/tube/TubeSingleTopicFetcherBuilder.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/InlongTopicManagerImpl.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/SortClientImplV2.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/tube/InLongTubeFetcherImpl.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/interceptor/MsgTimeInterceptor.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/manager/InlongSingleTopicManager.java
inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/manager/InlongSingleTopicManagerTest.java

- Fixes #5510
Refactor topic fetcher to support both single and multi topic consumer
1. refactor interface of topic fetcher to support both single and multi topic
2. introduce builder to provide configuration ability
3. optimize fetcher and manager
*(example:)* …

[INLONG-5510][SDK] Refactor single topic fetcher in Sort Sdk

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/trigger/TriggerManager.java

change INCREMENT to FULL
- Fixes #5601 
No message
No message

[INLONG-5601][Agent] Update the default triggering policy for file collection is FULL

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/pulsar/PulsarSourceOperator.java

- Fixes #5604
Add token info for Pulsar source.

[INLONG-5604][Manager] Add token info for Pulsar source

---

inlong-dataproxy/conf/common.properties
inlong-dataproxy/dataproxy-docker/Dockerfile
inlong-dataproxy/dataproxy-docker/dataproxy-docker.sh
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/ConfigConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/heartbeat/HeartbeatManager.java

[INLONG-5603][DataProxy] The in charges person and other info are not reported

---

inlong-distribution/src/main/assemblies/sort-connectors.xml
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/DorisConstant.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/ExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/DorisExtractNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/DorisExtractNodeTest.java
inlong-sort/sort-connectors/doris/README.md
inlong-sort/sort-connectors/doris/pom.xml
inlong-sort/sort-connectors/pom.xml
inlong-sort/sort-core/pom.xml
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DorisExtractToMySqlLoadTest.java
licenses/inlong-sort-connectors/LICENSE
licenses/inlong-sort-connectors/NOTICE
pom.xml

- Fixes #5040 
Add Apache Doris Extract Node for Sort
- Add doris Extract Node
- Add apache doris official doris-flink-connector
- Add doris Extract Node test case
- add the Unit test of DorisExtractLoad DorisExtractNodeTest
- add the Unit test of DorisExtractLoad DorisExtractToDorisLoadTest

[INLONG-5040][Sort] Add Apache Doris extract node for Sort

---

inlong-dashboard/src/metas/sources/file.ts

[INLONG-5615][Dashboard] Fix file source agent ip field

---

inlong-dashboard/src/components/HighSelect/index.tsx
inlong-dashboard/src/components/UserSelect/index.tsx
inlong-dashboard/src/locales/cn.json
inlong-dashboard/src/locales/en.json

[INLONG-5620][Dashboard] UserSelect uses HighSelect's built-in properties directly

---

.github/ISSUE_TEMPLATE/bug-report.yml

- Fixes #5631 
[INLONG-5631][Release] Add the 1.3.0 version option for the bug report
[INLONG-5631][Release] Add the 1.3.0 version option for the bug report

[INLONG-5631][Release] Add the 1.3.0 version option for the bug report

---

CHANGES.md

- Fixes #5634 
[INLONG-5634][Release] Update changes log for the 1.3.0 version
[INLONG-5634][Release] Update changes log for the 1.3.0 version

[INLONG-5634][Release] Update changes log for the 1.3.0 version

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/HttpBaseSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/SimpleHttpSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/SimpleMessageHandler.java

[INLONG-5633][DataProxy] Add statistical information to the HTTP source

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/README.md
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/client_config.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/tc_api.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/client_config.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/logger.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/pack_queue.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/proxylist_config.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/proxylist_config.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/sdk_constant.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/sdk_core.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/sdk_core.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/buffer_pool.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/buffer_pool.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/executor_thread_pool.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/executor_thread_pool.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/send_buffer.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/socket_connection.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/socket_connection.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/CMakeLists.txt
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/base/client_config_test.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/base/proxylist_config_test.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/net/big_pack_test.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/net/buffer_pool_test.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/net/send_buffer_test.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/net/socket_connection_test.cc

- [INLONG-5437][SDK] Support initializing SDK(cpp) by ClientConfig object
- Fixes #5437 
*(example:)*
- …

[INLONG-5437][SDK] Support initializing SDK(cpp) by ClientConfig object

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/pulsar/PulsarClusterRequest.java

- Fixes #5650 
Remove the non-null check of the Pulsar adminURL.

[INLONG-5650][Manager] Remove the non-null check of the Pulsar adminURL

---

inlong-dataproxy/dataproxy-docker/dataproxy-docker.sh

- Fixes #5658
*(example:)*
- If a …

[INLONG-5658][DataProxy] Fix incorrect docker script

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/KubernetesConstants.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/FileReaderOperator.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/KubernetesFileReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/MetaDataUtils.java

To update data structure and to support SORT in the InLong.
- Fixes #5663 
For example:

[INLONG-5663][Agent] To update data structure for k8s log

---

inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/example/consumer/test_consumer.cc
inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/include/tubemq/tubemq_config.h
inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/tubemq_config.cc

[INLONG-5672][TubeMQ] Add SetLogPrintLevel() in TubeMQServiceConfig class

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongGroupContext.java

[INLONG-5678][Manager] Provide source info for group status

---

inlong-dashboard/src/pages/ProcessManagement/DetailModal.tsx

[INLONG-5685][Dashboard] Fix the error of setting approvers params

---

inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/baseconsumer.cc
inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/const_config.h

[INLONG-5681][TubeMQ] The C++ SDK does not switch after the active Master node hangs up

---

inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/tests/logger_test/CMakeLists.txt
inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/tests/logger_test/main.cc

[INLONG-5687][TubeMQ] Missing log content in the tests directory

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql

Remove appending agent ip for the agent ip is already written in the subtask.
- Fixes #5691

[INLONG-5691][Manager] Remove the append operation for agent IPs

---

inlong-dashboard/src/components/EditableTable/index.tsx

[INLONG-5696][Dashboard] Fix the EditableTable value update error when columns change

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/ExtractNodeUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/pulsar/PulsarSourceOperator.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/CsvFormat.java

[INLONG-5689][Manager] PulsarSource set fieldDelimiter when use CSV format
- Fixes #5689
PulsarSource set fieldDelimiter when use CSV format

[INLONG-5689][Manager] PulsarSource set fieldDelimiter when use CSV format

---

inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/ListCommand.java
inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/LogCommand.java

[INLONG-5705][Manager] Fix the deprecated dependency of PageInfo

---

inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/baseconsumer.cc

Co-authored-by: Charley <charleli@apache.org>
- Fixes #5700

[INLONG-5700][TubeMQ] Core file generated while the C++ consumer is closed

---

inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java

[INLONG-5710][Audit] Fix the ck service initialization problem

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/ExtractNodeUtils.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/Format.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/RawFormat.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/format/RawFormatTest.java

[INLONG-5701][Manager][Sort] Support raw format
- Fixes #5701 
- Pulsar and Kafka source support set raw format.
- Add raw format

[INLONG-5701][Manager][Sort] Support raw format

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/README.md
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/conf/config_example.json
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/client_config.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/tc_api.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/client_config.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/logger.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/logger.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/pack_queue.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/proxylist_config.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/sdk_constant.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/sdk_core.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/sdk_core.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/utils.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/buffer_pool.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/executor_thread_pool.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/socket_connection.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/base/client_config_test.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/base/pack_queue_test.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/base/proxylist_config_test.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/base/test_log.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/base/test_utils.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/main/init_exit_test.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/net/big_pack_test.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/net/buffer_pool_test.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/net/executor_test.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/net/send_buffer_test.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/test/net/socket_connection_test.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/third_party/CMakeLists.txt

- [INLONG-5642][SDK] Change SDK(cpp) logger framework
- Fixes #5642 
- Using a custom logger framework instead of log4cplus
- Fix crash in high frequency init and close scene
- Update ut
- Update README.md
- Update `proxy_cfg_preurl` in `config_example.json`
*(example:)* …

[INLONG-5642][SDK] Change SDK(cpp) logger framework

---

inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/baseconsumer.cc

[INLONG-5700][TubeMQ] Core file generated while the C++ consumer is closed(addendum)

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java

- Fix source and sink metrics are incorrect when msgType equals 5.
- Fixes #5723 
*(example:)*
- If a …

[INLONG-5723][DataProxy]  Fix source and sink metrics are incorrect when msgType equals 5

---

inlong-sort/sort-connectors/elasticsearch-6/pom.xml
inlong-sort/sort-connectors/elasticsearch-7/pom.xml
inlong-sort/sort-connectors/hbase/pom.xml
inlong-sort/sort-core/pom.xml
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/Elasticsearch6SqlParseTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/Elasticsearch7SqlParseTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/ElasticsearchSqlParseTest.java
pom.xml

- Fixes #5712 
Fix class not found in Elasticsearch 6 connector for producting
modify some poms and add test

[INLONG-5712][Sort] Fix class not found in Elasticsearch 6 connector for producting

---

inlong-sort/sort-connectors/hive/pom.xml

- [INLONG-5733][Sort] Fix hive connector Slf4j class conflict
- Fixes #5733 
* Fix Slf4j class conflict of hive connector 
* exclude slf4j dependency

[INLONG-5733][Sort] Fix slf4j class conflict in Hive connector

---

inlong-dashboard/src/metas/nodes/index.tsx
inlong-dashboard/src/pages/Clusters/CreateModal.tsx
inlong-dashboard/src/pages/GroupDetail/DataSources/DetailModal.tsx
inlong-dashboard/src/pages/GroupDetail/DataStorage/DetailModal.tsx
inlong-dashboard/src/pages/Nodes/DetailModal.tsx

[INLONG-5749][Dashboard] Fix bad node public params

---

inlong-sort/sort-formats/format-inlongmsg-pb/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory

- Fixes #5746
*(example:)*
- If a …

[INLONG-5746][Sort] Add SPI path for Inlong PB msg

---

inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java
inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/withoutadmin/CallbackCollector.java

- [INLONG-5762][Sort] Fix pulsar source metric computing
- Fixes #5762 
Fix pulsar source metric computing
* Add CallbackCollector for computing
* modify metric name

[INLONG-5762][Sort] Fix the computing for the Pulsar source metric

---

inlong-agent/agent-docker/agent-docker.sh
inlong-manager/manager-service/pom.xml

[INLONG-5741][Kubernete] Change agent docker configuration unified with physical
- Fixes #5741 
Change agent docker configuration unified with physical
Change agent docker configuration unified with physical
Change agent docker configuration unified with physical

[INLONG-5741][Agent] Keep the docker config of Agent consistent with physical machine

---

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSource.java

[INLONG-5666][SortStandalone] Supports init multiple Sort SDK to improve performance

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/PulsarSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/SimpleMessageTubeSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/TubeSink.java

[INLONG-5788][DataProxy] Fix the incorrect readFailSize metric value

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/FileReaderOperator.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/MonitorTextFile.java

Fix NPE
- Fixes #5803 
No message.
No message.

[INLONG-5803][Agent] Fix NPE when collect file data

---

inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/BaseMessageConsumer.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/balance/ConsumerEvent.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/cluster/SubscribeInfo.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/TMaster.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodeconsumer/ConsumerEventManager.java

[INLONG-5795][TubeMQ] Optimize the implementation of ConsumerEvent.toStrBuilder()

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/source/AbstractSourceOperateListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java

- Fixes #5799
1. the template task should not be operated
2.  fix the incorrect status predicator

[INLONG-5799][Manager] Fix the source delete/stop/restart bug

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java

[INLONG-5820][Manager] Fix the auto push source task operating problem

---

inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java
inlong-sort/sort-formats/format-inlongmsg-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgDeserializationSchema.java

- [INLONG-5818][Sort] Fix pulsar connector metric computing
- Fixes #5818 
Fix pulsar connector metric computing
* Modify log to slf4j
* Change metric computing

[INLONG-5818][Sort] Fix metric computing for Pulsar connector

---

pom.xml

[INLONG-5824][Manager] Fix the broken logging due to log4j conflicts

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java

- Fixes #5825
*(example:)*
- If a …

[INLONG-5825][Manager] Remove the limitation of MQ type of group in SortSourceService

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/MonitorTextFile.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/FileDataUtils.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/MetaDataUtils.java

Fix to merge data bug
- Fixes #5828 
Don't have any metadata.
No message

[INLONG-5828][Agent] Fix to merge data error when collect nonstandard log of k8s

---

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/decode/MessageDeserializer.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/util/StringUtil.java
inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/decode/MessageDeserializerTest.java

- Fixes #5808
*(example:)*
- If a …

[INLONG-5808][SDK] Sort SDK supports parse InlongMsg

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/InlongGroupContext.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/StreamSource.java

[INLONG-5844][Manager] Sub sources should be filtered when querying task status

---

inlong-manager/manager-dao/src/main/resources/mappers/InlongConsumeEntityMapper.xml

- Fixes #5846
SQL exception to check if consumer exists.
I will add the unit tests in this PR: https://github.com/apache/inlong/pull/5777

[INLONG-5846][Manager] Fix the SQL exception to check if the consumer exists

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/executors/AddTopicExecutor.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/BrokerServiceImpl.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/RegionServiceImpl.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/TubeMQErrorConst.java
inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/service/interfaces/BrokerService.java
inlong-tubemq/tubemq-manager/src/test/java/org/apache/inlong/tubemq/manager/service/broker/TestBrokerService.java

- Fixes https://github.com/apache/inlong/issues/5853
There is a typo that makes _exist_ to _exsit_.
Fix it.

[INLONG-5853][TubeMQ] Fix typo in AddTopicExecutor

---

inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/baseconsumer.cc
inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/tubemq_client.cc
inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/version.h

- Fixes #5848 
1. fix the bug;
2. change the version

[INLONG-5848][TubeMQ] Get duplicated call when calling TubeMQConsumer::Start()

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/MonitorTextFile.java

Support symbolic links for file,  to reset postion is 0 when  change symbolic links for file.
- Fixes #5861 
No message
No message

[INLONG-5861][Agent] Support symbolic links for file

---

inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/baseconsumer.cc
inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/baseconsumer.h

[INLONG-5867][TubeMQ] Add registered partition information printing

---

inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CreateCommand.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongClientImpl.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongGroupTransfer.java

- Fixes #5849
Update the inlong group ext info by the client.

[INLONG-5849][Manager] Update the inlong group ext info by the client

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/DebeziumSourceFormat.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/MongoJob.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/GsonUtil.java
inlong-agent/agent-plugins/pom.xml
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/MongoDBSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/BinlogReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/MongoDBReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/PostgreSQLReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/snapshot/AbstractSnapshot.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/snapshot/BinlogSnapshotBase.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/snapshot/MongoDBSnapshotBase.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/snapshot/PostgreSQLSnapshotBase.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/snapshot/SnapshotBase.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/PostgreSQLOffsetManagerTest.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestBinlogOffsetManager.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestMongoDBReader.java
licenses/inlong-agent/LICENSE
pom.xml

- Fixes #5045 
*[Agent] Support collect data from MongoDB*

[INLONG-5045][Agent] Support collect data from MongoDB

---

.github/workflows/ci_docker.yml
docker/build-docker-images.sh
docker/publish-by-arch.sh

[[INLONG-5870] Change sh to bash
- Fixes #5870 
Change sh to bash
Change sh to bash
Change sh to bash

[INLONG-5870][Docker] Add dependency to fix the arm images building

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/SimpleMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/audit/AuditUtils.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/DefaultServiceDecoder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleMessageHandler.java

[INLONG-5880][DataProxy] Add data reporting time process logic

---

inlong-manager/manager-pojo/pom.xml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTO.java
inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTOTest.java
inlong-manager/manager-pojo/src/test/resources/log4j2.xml

- Fixes #5881
Fix the vulnerability to security attacks for the MySQL JDBC URL.
Filter the sensitive params in the MySQL JDBC URL.
- 

[INLONG-5881][Manager] Fix the vulnerability to security attacks for the MySQL JDBC URL

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/ServiceBaseTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/AgentServiceTest.java

[INLONG-5885][Manager] Refactor the task issue logic to simply code complexity

---

bin/inlong-daemon

- Fixes #5890
*(example:)*
- If a …

[INLONG-5890][Script] Add tcp protocol when connecting to MySQL

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTO.java
inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTOTest.java

- Fixes #5881
Fix the vulnerability for the MySQL JDBC URL.
- org.apache.inlong.manager.pojo.sink.mysql.MySQLSinkDTOTest

[INLONG-5881][Manager] Fix the vulnerability for the MySQL JDBC URL (addendum)

---

inlong-dashboard/src/metas/sinks/clickhouse.tsx

- Fixes #5894
*(example:)*
- If a …

[INLONG-5894][Dashboard] Remove the password required restrict for test/development clickhouse cluster

---

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/util/JdbcUrlUtils.java
inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/metric/TestUrlValidate.java
inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDynamicTableFactory.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/JdbcUrlUtils.java

- Fixes #5889 
Fix MySQL Node JDBC Url for RCE vulnerability
Fix MySQL Node JDBC Url for RCE vulnerability
run ut 

[INLONG-5889][Sort] Fix MySQL Node JDBC Url For RCE Vulnerability

---

inlong-dashboard/package-lock.json
inlong-dashboard/package.json
inlong-dashboard/src/components/FormGenerator/FormGenerator.tsx
inlong-dashboard/src/components/FormGenerator/FormItemContent.tsx
inlong-dashboard/src/metas/sinks/clickhouse.tsx
inlong-dashboard/src/metas/sinks/common/status.tsx
inlong-dashboard/src/metas/sinks/es.tsx
inlong-dashboard/src/metas/sinks/greenplum.tsx
inlong-dashboard/src/metas/sinks/hbase.tsx
inlong-dashboard/src/metas/sinks/hive.tsx
inlong-dashboard/src/metas/sinks/iceberg.tsx
inlong-dashboard/src/metas/sinks/index.ts
inlong-dashboard/src/metas/sinks/kafka.tsx
inlong-dashboard/src/metas/sinks/mysql.tsx
inlong-dashboard/src/metas/sinks/oracle.tsx
inlong-dashboard/src/metas/sinks/postgreSql.tsx
inlong-dashboard/src/metas/sinks/sqlServer.tsx
inlong-dashboard/src/metas/sinks/tdsqlPostgreSql.tsx
inlong-dashboard/src/metas/sources/index.ts
inlong-dashboard/src/pages/GroupDetail/DataSources/index.tsx
inlong-dashboard/src/pages/GroupDetail/DataStorage/DetailModal.tsx
inlong-dashboard/src/pages/GroupDetail/DataStorage/index.tsx
inlong-dashboard/src/themes/cover.less

[INLONG-5901][Dashboard] Unified sinks type definition

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/SimpleMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/DateTimeUtils.java

[INLONG-5899][DataProxy] Optimize Http's SimpleMessageHandler class

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/SimpleMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/DefaultServiceDecoder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServiceDecoder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleMessageHandler.java

[INLONG-5915][DataProxy] Optimize source's ServerMessageHandler class

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/ConfigConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/SimpleMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/audit/AuditUtils.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/SimpleMessageTubeSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/TubeSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/TubeUtils.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/InLongMsgVer.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/MessageUtils.java

[INLONG-5917][DataProxy] Optimize TubeSink class

---

inlong-manager/manager-client-tools/pom.xml
inlong-manager/manager-client/pom.xml
inlong-manager/manager-web/assembly.xml

- Fixes #5904 
1.Add packaging configuration.
2.Add them into lib directory.

[INLONG-5904][Manager] Add manager client packages into lib directory

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/PulsarSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/TubeSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/SinkTask.java

[INLONG-5918][DataProxy] Optimize PulsarSink class

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/ConfigConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/HttpBaseSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/SimpleMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/DataProxyMetricItemSet.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/PulsarSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/TubeSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/SendMessageCallBack.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/BaseSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleTcpSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleUdpSource.java

[INLONG-5924][DataProxy] Supplementary monitoring indicator dimension items

---

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/MetricState.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/SinkMetricData.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/util/MetricStateUtils.java
inlong-sort/sort-connectors/kafka/pom.xml
inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaConsumer.java
inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaConsumerBase.java
inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaProducer.java
inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/DynamicKafkaDeserializationSchema.java
inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicSource.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/DebeziumSourceFunction.java
licenses/inlong-sort-connectors/LICENSE

- [INLONG-5922][Sort] Add metric state for kafka and modify mysql metric init
- Fixes #5922 
Add metric state for kafka and modify mysql metric init
* Add  kafka source metric state
* Add kafka sink metric state
* modify mysql metric init

[INLONG-5922][Sort] Add metric state for kafka and modify mysql metric init

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/message/PackProxyMessage.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java
inlong-common/src/main/java/org/apache/inlong/common/msg/AttributeConstants.java

- Title Example: [INLONG-5874][Agent] Add msgTime attribute in PackProxyMessage
- Fixes #5874 
*(example:)* …

[INLONG-5874][Agent] Use dataTime to report audit metrics

---

inlong-dashboard/src/pages/GroupDetail/Audit/config.tsx
inlong-dashboard/src/pages/GroupDetail/Audit/index.tsx

[INLONG-5931][Dashboard] Support query audit data by role

---

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/SinkMetricData.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/SourceMetricData.java
inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/DebeziumSourceFunction.java

- [INLONG-5913][Sort] Add metric state for oracle and fix speed computing error
- Fixes #5913 
Add metric state for oracle and fix speed computing error
* Add oracle metric state
* Fix speed computing error

[INLONG-5913][Sort] Add metric state for oracle and fix speed computing error

---

inlong-dashboard/src/components/FormGenerator/FormGenerator.tsx

[INLONG-5938][Dashboard] The API parameter of calling to get the topic is lost

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java

[INLONG-5941][DataProxy] Store the initial number of message items in 

---

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/util/MetricStateUtils.java
inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/DebeziumSourceFunction.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/DebeziumSourceFunction.java
inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/DebeziumSourceFunction.java
inlong-sort/sort-connectors/postgres-cdc/src/main/java/org.apache.inlong.sort.cdc.postgres/DebeziumSourceFunction.java
inlong-sort/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/cdc/sqlserver/table/DebeziumSourceFunction.java

- Fixes #5930
1\ Support metric state recovery for sqlserver-cdc
2\ fix some bug in metricutils
Support metric state recovery for sqlserver-cdc

[INLONG-5930][Sort] Support metric state recovery for sqlserver-cdc

---

inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/daemon/AbstractDaemonService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/DefaultOffsetManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/OffsetRecordService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/stats/TrafficStatsService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/utils/SimpleVisitTokenManager.java

[INLONG-5946][TubeMQ] AbstractDaemonService implementation optimization

---

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderGroup.java

- Fixes #5963
*release the allocated memory*
*Solve the sdk memory leak problem.*
*(example:)*

[INLONG-5963][Audit] Solve the sdk memory leak problem

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/Db.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/JobProfileDb.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/RocksDbImp.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/Job.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobWrapper.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/Task.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/trigger/TriggerManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/filter/DateFormatRegex.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/TextFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/FileReaderOperator.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/MonitorTextFile.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/TextFileReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/trigger/DirectoryTrigger.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/trigger/PathPattern.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/PluginUtils.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/TestFileAgent.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/filter/TestDateFormatRegex.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestTextFileReader.java
inlong-agent/agent-plugins/src/test/resources/fileAgent.trigger.json
inlong-agent/agent-plugins/src/test/resources/fileAgentJob.json

Fix WatchService is no effect in the k8s.
- Fixes #5909 
Trigger a new task when Data changes, for example: add data.
Validate the job for same GroupId and StreamId.

[INLONG-5909][Agent] Fix WatchService is no effect in the k8s

---

inlong-sort/sort-connectors/hive/src/main/java/org/apache/inlong/sort/hive/filesystem/AbstractStreamingWriter.java

- [INLONG-5969][Sort] Support metrics state restore for hive connector
- Fixes #5969 
*Support metrics state restore for hive connector*
*Support metrics state restore for hive connector.*

[INLONG-5969][Sort] Support metrics state restore for hive connector

---

inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/IcebergStreamWriter.java

- [INLONG-5970][Sort] Support metrics state restore for iceberg connector
- Fixes #5970
*Support metrics state restore for iceberg connector*
*Support metrics state restore for iceberg connector.*

[INLONG-5970][Sort] Support metrics state restore for iceberg connector

---

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/MetricOption.java
inlong-sort/sort-connectors/iceberg-dlc/src/main/java/org/apache/inlong/sort/iceberg/flink/sink/IcebergStreamWriter.java

- [INLONG-5971][Sort] Support metrics state restore for dlc connector
- Fixes #5971 
*Support metrics state restore for dlc connector*
*Support metrics state restore for dlc connector.*

[INLONG-5971][Sort] Support metrics state restore for dlc-iceberg connector

---

inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/AbstractJdbcOutputFormat.java
inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/GenericJdbcSinkFunction.java
inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcBatchingOutputFormat.java

- Fixes #5943 
Add metric state for JDBC 
JDBC connector

[INLONG-5943][Sort] Add metric state for JDBC 

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/mysql/MySQLDataNodeDTO.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/mysql/MySQLDataNodeInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/mysql/MySQLDataNodeRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/MySQLDataNodeOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/mysql/MySQLDataNodeOperator.java

- Fixes #5956 
Support MySQL node and dbsync cluster configuration
Added MySQL and dbsync related request, info, and DTO classes

[INLONG-5956][Manager] Support MySQL node configuration

---

inlong-dashboard/src/components/EditableTable/index.tsx
inlong-dashboard/src/metas/sinks/clickhouse.tsx
inlong-dashboard/src/metas/sinks/mysql.tsx

[INLONG-5986][Dashboard] Support fieldType field to set length

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/agent/AgentClusterDTO.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/agent/AgentClusterInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/agent/AgentClusterRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/AgentClusterOperator.java

- Fixes #5962 
Add additional parameters for the agent cluster
Add additional parameters for the agent cluster

[INLONG-5962][Manager] Add additional parameters for the agent cluster

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java

[INLONG-5998][Manager] Only allow lower case letters for source name

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/DataProxyMetricItemSet.java

[INLONG-6012][DataProxy] Adjust the fields statistics unit in DataProxyMetricItemSet

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ConsumeStatus.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ProcessName.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongConsumeEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/InlongConsumeEntityMapper.xml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/workflow/form/process/ApplyConsumeProcessForm.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/workflow/form/process/BaseProcessForm.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/workflow/form/task/BaseTaskForm.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/workflow/form/task/ConsumeApproveForm.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/AbstractConsumeOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/ConsumePulsarOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/InlongConsumeProcessService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/InlongConsumeService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/InlongConsumeServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ConsumptionServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongPulsarOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/consume/OperateConsumeTaskListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/consume/apply/ApproveConsumeProcessListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/consume/apply/CancelConsumeProcessListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/consume/apply/RejectConsumeProcessListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/consume/ApplyConsumeProcessHandler.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/consume/ApplyConsumeWorkflowDefinition.java
inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongConsumeController.java

- Title: [INLONG-5984][Manager] Optimize the logic related to the InlongConsume process
- Fixes #5984
Optimize the logic related to the InlongConsume process.
1. Optimize the inlong consume workflow to use the InlongConsume related logic.
2. Fix the bugs of updating and deleting operations.

[INLONG-5984][Manager] Optimize the logic related to the InlongConsume process

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CommonConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/Job.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskPositionManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/trigger/TriggerManager.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/task/TestTaskWrapper.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/FileReaderOperator.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/DataConfig.java

Add the Partition Key settings for file source.
Synchronization mode the parameter needs to be set.
- Fixes #5988 
No message
No message

[INLONG-5988][Agent] Add the Partition Key settings for file source

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/BinlogReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/KafkaReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/MongoDBReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/PostgreSQLReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/RedisReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/SQLServerReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/SqlReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/FileReaderOperator.java

- [INLONG-6009][Agent] Report data size to audit
- Fixes #6009 
*(example:)* …

[INLONG-6009][Agent] Report data size to InLong Audit

---

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/MetricOption.java

*[INLONG-6016][Sort] Serialization failed when submit load DLC sort job*
- Fixes #6016 
*Fix serialization failed when submit load DLC sort job*
*Add `Serializable` interface for `MetricOption`*

[INLONG-6016][Sort] Serialization failed when submit load DLC sort job

---

inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/db/entities/AuditDataPo.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/InsertData.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/MySqlService.java
inlong-audit/audit-store/src/main/resources/mapper/AuditDataDao.xml
inlong-audit/audit-store/src/main/resources/sql/apache_inlong_audit.sql
inlong-audit/sql/apache_inlong_audit.sql

- Fixes #6024
Fix the invalid default value for 'sdk_ts'.
Change the default value for `sdk_ts`.

[INLONG-6024][Audit] Fix the invalid default value for 'sdk_ts'

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/TubeBroker.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/metadata/TopicMetadata.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/MessageStore.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/MessageStoreManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/disk/MsgFileStore.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/mem/MsgMemStore.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/DefaultOffsetManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/stats/MsgStoreStatsHolder.java
inlong-tubemq/tubemq-server/src/test/java/org/apache/inlong/tubemq/server/broker/stats/MsgStoreStatsHolderTest.java

[INLONG-6035][TubeMQ] Add Broker's message append and file refresh delay statistics

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/AgentUtils.java

Support for hidden directories.
For example:/tmp/test/**/test.xml
- Fixes #6033 
add util
No message

[INLONG-6033][Agent] Support for hidden directories

---

inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/config/ConsumerConfig.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/BaseMessageConsumer.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/RmtDataCache.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/SimpleClientBalanceConsumer.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/policies/FlowCtrlRuleHandler.java
inlong-tubemq/tubemq-core/src/test/java/org/apache/inlong/tubemq/corebase/policies/TestFlowCtrlRuleHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/TubeBroker.java

[INLONG-6038][TubeMQ] Optimize FlowCtrlRuleHandler.updateFlowCtrlInfo()

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/AgentMetricItem.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/channel/MemoryChannel.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/BinlogReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/KafkaReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/MongoDBReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/PostgreSQLReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/SQLServerReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/SqlReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/FileReaderOperator.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestSQLServerReader.java

Fix lost read and send count
- Fixes #6022 
Fix lost read and send count
Fix lost read and send count
Fix lost read and send count

[INLONG-6022][Agent] Fix lost read and send count

---

inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkEntityMapper.xml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/hive/HiveDataNodeInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/SinkInfo.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeOperateHelper.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/hive/HiveResourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/AbstractSinkOperator.java

- Fixes #6018
Use the hive data node information where convenient.

[INLONG-6018][Manager] Using the Hive data node when creating group resources

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentMain.java
inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/protocol/Commands.java
inlong-audit/audit-common/src/main/proto/AuditApi.proto
inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/source/ServerMessageHandler.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditOperator.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderHandler.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderManager.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/util/AuditData.java
inlong-audit/audit-sdk/src/test/java/org/apache/inlong/audit/util/AuditDataTest.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/audit/AuditUtils.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/node/Application.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/node/ManagerPropsConfigProvider.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/SortStandaloneApplication.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/metrics/audit/AuditUtils.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/SinkMetricData.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/SourceMetricData.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/stats/audit/AuditUtils.java

- Title: [INLONG-6031][Audit] Clean code for InLong Audit
- Fixes #6031
[INLONG-6031][Audit] Clean code for InLong Audit.
1. If necessary, change the field to static or final. And modify the static final field to UPPER_CASE mode.
2. Modify log info to be clear and easy to understand.
3. Modify Java docs to be clear and easy to understand.

[INLONG-6031][Audit] Clean code for InLong Audit

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java

[INLONG-6040][DataProxy] DataProxy does not fully update the configurations

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java

[INLONG-6052][DataProxy] Wrong value set in PulsarClientService

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java

[INLONG-6058][DataProxy] Add parameter checking and optimize client creation logic

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/PulsarSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java

[INLONG-6065][DataProxy] Delete the Pulsar client synchronously when deleting a topic

---

inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java

[INLONG-6069][Audit] Initializing the ClickHouse service before its starts

---

inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/ClickHouseService.java

[INLONG-6076][Audit] Bugs in the ClickHouseService.processOutput()

---

.github/workflows/ci_greeting.yml

- Fixes #6082
Fix the error in the greeting action.
Since the provider of the `first-interaction` toolkit did not fix its errors, add the `continue-on-error: true` parameter to support the execution of other pipelines in case of errors.

[INLONG-6082][CI] Fix the error in the greeting action

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/bdbstore/bdbentitys/BdbGroupFilterCondEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/bdbstore/bdbentitys/BdbGroupFlowCtrlEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/bdbstore/bdbentitys/BdbTopicAuthControlEntity.java

[INLONG-6092][TubeMQ] Change the way to obtain the modifyUser and modifyDate

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/TMaster.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodeconsumer/ConsumeGroupInfo.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodeconsumer/ConsumerEventManager.java

[INLONG-6096][TubeMQ] Optimize some code styles under the nodeconsumer module

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebAdminFlowRuleHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebAdminGroupCtrlHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebAdminTopicAuthHandler.java

[INLONG-6098][TubeMQ] Add preprocessing condition check

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/FieldType.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/fieldformat/BinaryFormat.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/fieldformat/VarBinaryFormat.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldFormatUtils.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtils.java
inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sort/util/FieldFormatUtilsTest.java
inlong-sort/sort-formats/format-base/src/main/java/org/apache/inlong/sort/formats/base/TableFormatUtils.java
inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/common/BinaryFormatInfo.java
inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/common/FormatInfo.java
inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/common/VarBinaryFormatInfo.java
inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/common/VarBinaryTypeInfo.java
inlong-sort/sort-formats/format-common/src/test/java/org/apache/inlong/sort/formats/common/VarBinaryFormatInfoTest.java

-  [INLONG-6078][Manager][Sort] Add VarBinary data type and extend binary for supporting length
- Fixes #6078 
* Add VarBinary data type and extend binary for supporting length
* modify binary data type
* Add varbinary data type

[INLONG-6078][Manager][Sort] Add VarBinary data type and extend binary for supporting length

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebGroupConsumeCtrlHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebGroupResCtrlHandler.java

[INLONG-6108][TubeMQ] Added booked consume group query APIs

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/DefaultMetaDataService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/MetaDataService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/MetaConfigMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/TopicDeployMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsMetaConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsTopicDeployMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebTopicCtrlHandler.java

[INLONG-6110][TubeMQ] Optimize the implementation logic of adding or modifying TopicCtrlEntity records

---

inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/cluster/TopicInfo.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/BrokerPSInfoHolder.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/BrokerRunManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/BrokerRunStatusInfo.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/BrokerTopicInfoView.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/DefBrokerRunManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/action/screen/Master.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/action/screen/config/BrokerList.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebTopicDeployHandler.java

[INLONG-6117][TubeMQ] Optimize the implementation of adminQueryBrokerTopicCfgAndRunInfo

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java

- Fixes #6121
The source list is not assigned when list streams. Fix it.

[INLONG-6121][Manager] Fix source list unassigned error when list stream

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java

- Title Example: [INLONG-6119][SDK] Fix log level and improve proxylist update strategy
- Fixes #6119 
*(example:)* …

[INLONG-6119][SDK] Fix log level and improve proxylist update strategy

---

inlong-audit/audit-docker/audit-docker.sh

Add audit.config.store.mode Configurable to k8s
- Fixes #6073 
Add audit.config.store.mode Configurable to k8s
Add audit.config.store.mode Configurable to k8s

[INLONG-6073][Kubernetes] Add audit.config.store.mode configurable to k8s

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/utils/WebParameterUtils.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/DefaultMetaDataService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/MetaDataService.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/GroupConsumeCtrlEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/GroupResCtrlEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/TopicCtrlEntity.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/MetaConfigMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/mapper/TopicCtrlMapper.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsMetaConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsTopicCtrlMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/bdbimpl/BdbMetaConfigMapperImpl.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebOtherInfoHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebTopicDeployHandler.java

[INLONG-6124][TubeMQ] Small optimizations about the implementation of metadata logic

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/AgentPrometheusMetricListener.java
inlong-agent/agent-common/src/test/java/org/apache/inlong/agent/metrics/TestPrometheusListener.java

To solve Prometheus listener error and add unit tests.
Fixes: #6115
1、solve Prometheus listener error.
2、add Prometheus unit test.
3、solve Prometheus "expected text error"
4、add JVM status exporter.

[INLONG-6115][Agent] To solve Prometheus listener error and add unit tests

---

inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/producer/MaxMsgSizeHolder.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/producer/ProducerManager.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/producer/SimpleMessageProducer.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/utils/DataConverterUtil.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/utils/Tuple3.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/RemoteConErrStats.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/client/CallFuture.java
inlong-tubemq/tubemq-core/src/test/java/org/apache/inlong/tubemq/corerpc/codec/DataConverterUtilTest.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/TMaster.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/BrokerAbnHolder.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/BrokerPSInfoHolder.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/BrokerRunManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/BrokerSyncData.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/BrokerTopicInfoView.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/DefBrokerRunManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebMasterInfoHandler.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebTopicDeployHandler.java

[INLONG-6129][TubeMQ] Optimize the broker's node management

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerServiceServer.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/metadata/BrokerDefMetadata.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/MessageStoreManager.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/nodeinfo/ConsumerNodeInfo.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/web/BrokerAdminServlet.java

[INLONG-6133][TubeMQ] Add query parameter groupName in method admin_query_consumer_regmap

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/FileJob.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/TextFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/KubernetesFileReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/FileDataUtils.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/MetaDataUtils.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/PluginUtils.java

Filter file names by file attributes.
- Fixes #6131 
1.  Filter files by file properties, for example: logs of k8s.
2. Add rule filter file.
1. Add file utils.

[INLONG-6131][Agent] Support file filtering by condition

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/AvroFormat.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/CanalJsonFormat.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/CsvFormat.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/DebeziumJsonFormat.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/Format.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/InLongMsgFormat.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/JsonFormat.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/RawFormat.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/KafkaLoadNode.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/AbstractDynamicSchemaFormat.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/CanalJsonDynamicSchemaFormat.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormat.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/DynamicSchemaFormatFactory.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/JsonDynamicSchemaFormat.java
inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/format/CanalJsonDynamicSchemaFormatTest.java
inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormatTest.java
inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/format/DynamicSchemaFormatBaseTest.java
inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/DynamicKafkaSerializationSchema.java
inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/KafkaDynamicSink.java
inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicTableFactory.java
inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/UpsertKafkaDynamicTableFactory.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/KafkaLoadSqlParseTest.java

Title: [INLONG-6116][Sort] Support dynamic topic for KafkaLoadNode
Fixes #6116 
Support dynamic topic for KafkaLoadNode when the format of kafka is raw and the 'key.fields' is not specifyed.
This is mainly for some whole database migration scenarios, we assume that the upstream input data is a mixed schema of whole database migration, we ignore the real schema for now, receive the entire record in a binary raw data format, and fetch and parse its schema and data on the kafka sink side, and according to Some data values ​​are dynamically written to related topics.
Dynamic topic writing has some limitations:
1.The …

[INLONG-6116][Sort] Support dynamic topic for KafkaLoadNode

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebAdminGroupCtrlHandler.java

[INLONG-6142][TubeMQ] Added client-balanced consumer group control API

---

inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/common/TClientConstants.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/TServerConstants.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/statusdef/StepStatus.java

[INLONG-6144][TubeMQ] Adjust default constant configuration

---

inlong-tubemq/resources/assets/scripts/common/module.js
inlong-tubemq/resources/assets/scripts/topicList.js
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/web/handler/WebTopicDeployHandler.java

[INLONG-6138][TubeMQ] Update the API called by the js files in the resource

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java

- [INLONG-6146][Manager] Fix error jackson dependency when build dataflow json string
- Fixes #6146 
* Fix error jackson dependency when build dataflow json string
* Modify DefaultSortConfigOperator#buildConfig

[INLONG-6146][Manager] Fix error jackson dependency when build dataflow json string

---

inlong-sort/sort-connectors/iceberg-dlc/src/main/java/org/apache/inlong/sort/iceberg/flink/sink/RowDataTaskWriterFactory.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/RowDataTaskWriterFactory.java

[INLONG-6149][Sort] Iceberg delete key cause ArrayIndexOutOfBoundsException
- Title Example: [INLONG-6149][Sort] Iceberg delete key cause ArrayIndexOutOfBoundsExc…
- Fixes #6149 
*Slove Iceberg delete key cause ArrayIndexOutOfBoundsException*
*Add a eq delete schema for upsert mode for delete schema*

[INLONG-6149][Sort] Iceberg delete key cause ArrayIndexOutOfBoundsException

---

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/InlongTopicManagerFactory.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/kafka/AckOffsetOnRebalance.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/kafka/KafkaSingleTopicFetcher.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/kafka/InLongKafkaFetcherImpl.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/manager/InlongMultiTopicManager.java

- Fixes #5495
Current consume policy is one kafka/pulsar consumer only consume one topic.
Multi-topic policy is applied to those cases that all topics under this task share the same consumer strategy (such as roll back)
*(example:)*
- If …

[INLONG-5495][SDK] Support multi-topic manager 

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/PulsarSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/SinkTask.java

[INLONG-6156][DataProxy] Twice event write when topic is empty

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/TubeBroker.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/fileconfig/AbstractFileConfig.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/fileconfig/ZKConfig.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/fileconfig/ZKMetaConfig.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/MasterConfig.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/TMaster.java

[INLONG-6158][TubeMQ] Add ZooKeeper request timeout configuration

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/heartbeat/HeartbeatManager.java

Fix heartbeat status update
- Fixes #6159 
When heartbeat received, heartbeat manager init thread and update thread may get same version in inlong_cluster_node table. Then two threads will use same version to update this table. One of them will failed. As update operation in reportHeartbeat function will be skipped if last heartbeat with same type exists cache. So heartbeat status may be timeout still cache dropped.
Add return judgment. 
When MySql return is larger than zero, it means at least one field is updated. So when return is zero, skip add this heartbeat into cache. To avoid next heartbeat received, because last heartbeat cached, cause skipping update MySql.
Add return judgment. 
When MySql return is larger than zero, it means at least one field is updated. So when return is zero, …

[INLONG-6159][Manager] Fix heartbeat status update failed error

---

inlong-dashboard/src/components/FormGenerator/FormGenerator.tsx
inlong-dashboard/src/metas/sources/file.ts

[INLONG-6163][Dashboard] Form will lose old data when data changes are merged

---

inlong-agent/conf/log4j2.xml
inlong-audit/conf/log4j2.xml
inlong-dataproxy/conf/log4j2.xml
inlong-manager/manager-web/src/main/resources/log4j2.xml

Add logs rolling policies and rollover strategy. Default store 10 days logs.
- Fixes #6106 
Add logs rolling policies and rollover strategy. Default store 10 days logs.
Add logs rolling policies and rollover strategy. Default store 10 days logs.
Add logs rolling policies and rollover strategy. Default store 10 days logs.

[INLONG-6106][Logs] Add logs rolling policies and delete strategy

---

inlong-audit/audit-docker/Dockerfile
inlong-audit/audit-docker/audit-docker.sh
inlong-audit/conf/application.properties
inlong-audit/conf/audit-proxy-tube.conf
inlong-manager/manager-docker/Dockerfile
inlong-manager/manager-docker/manager-docker.sh

- Fixes #6169
*(example:)*
- If a …

[INLONG-6169][Docker] Add more env params for audit

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/DataFormat.java

- [INLONG-6179][Manager] Add RAW dataformat enum
- Fixes #6179 
* Add RAW dataformat enum
* modify DataFormat

[INLONG-6179][Manager] Add RAW dataformat enum

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java

[INLONG-6182][SDK] Fix the RequestTimeoutMillis initialization value error

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/DataNodeClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/DataNodeApi.java
inlong-manager/manager-dao/src/main/resources/mappers/DataNodeEntityMapper.xml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/common/UpdateResult.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/AbstractDataNodeOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/DataNodeController.java
inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/controller/DataNodeControllerTest.java

- Fixes #6042 
*(example:)*
- If a …

[INLONG-6042][Manager] Support delete and update DataNode by unique key

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java

Update DP config and add  add param protocolType.
- Fixes #6190 
Support to query Manger for SDK
add param protocolType 

[INLONG-6190][SDK] Update DataProxy config

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/StreamSinkApi.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/HiveSinkServiceTest.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSinkController.java

- Fixes #6086 
support base stream sink operator
support delete stream sink by related id
*(example:)* …

[INLONG-6086][Manager] Support updating and deleting stream sink by key

---

README.md

- Fixes #6177
*(example:)*
- If a …

[INLONG-6177][Doc] Update the supported Data Nodes table

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/StreamSinkClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/StreamSinkApi.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSinkEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/HiveSinkServiceTest.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSinkController.java

- Fixes #6192
Clean and reuse code for StreamSink.

[INLONG-6192][Manager] Clean and reuse code for StreamSink

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/DataNodeClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongClusterClient.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/DataNodeEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/DataNodeEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeOperateHelper.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceTest.java
inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/controller/DataNodeControllerTest.java

- Fixes #6209
Clean and reuse code for DataNode.

[INLONG-6209][Manager] Clean and reuse code for DataNode

---

inlong-dataproxy/conf/dataproxy-tube.conf

[INLONG-6228][DataProxy] Modify the default values of the dataproxy-tube.conf file

---

inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestSQLServerConnect.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestSQLServerReader.java

- Fixes #6207 
*(example:)*
- If a …

[INLONG-6207][Agent] Optimize the unit test for TestSQLServerReader

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/NodeRelationUtils.java

- Fixes #6188
*(example:)*
- If a …

[INLONG-6188][Manager] Join supports multiple fields

---

inlong-sort/sort-connectors/base/pom.xml
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/AbstractDynamicSchemaFormat.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/CanalJsonDynamicSchemaFormat.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormat.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/JsonDynamicSchemaFormat.java

[INLONG-6214][Sort] Import schema and data parsing ability for DynamicSchemaFormat
- [INLONG-6214][Sort] Import schema and data parsing ability for DynamicSchemaFormat
- Fixes #6214
*Import schema and data parsing ability for DynamicSchemaFormat*
*Import schema and data parsing ability for DynamicSchemaFormat*

[INLONG-6214][Sort] Import schema and data parsing ability for DynamicSchemaFormat

---

inlong-dataproxy/conf/common.properties
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/SourceReportConfigHolder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/SourceReportInfo.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/ConfigConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/heartbeat/HeartbeatManager.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/SimpleHttpSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleTcpSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleUdpSource.java
inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/config/holder/TestSourceReportHolder.java

[INLONG-6234][DataProxy] Adjust the source report information acquisition source

---

inlong-audit/audit-docker/Dockerfile
inlong-audit/audit-docker/audit-docker.sh
inlong-manager/manager-docker/Dockerfile
inlong-manager/manager-docker/manager-docker.sh

Add manager and audit database name configuration
- Fixes #6241 
Add manager and audit database name configuration
Add manager and audit database name configuration
Add manager and audit database name configuration

[INLONG-6241][Docker] Add manager and audit database name configuration

---

inlong-common/src/main/java/org/apache/inlong/common/enums/MetaField.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/Metadata.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/MySqlExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/KafkaLoadNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/MySqlExtractNodeTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/KafkaLoadNodeTest.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlReadableMetadata.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/AllMigrateTest.java
inlong-sort/sort-formats/format-json/pom.xml
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/debezium/DebeziumJson.java
pom.xml

- Fixes #6174 
[INLONG-6174][Sort] Mysql connector support meta data with debezium format 
[INLONG-6174][Sort] Mysql connector support meta data with debezium format 
run allmigrateUt

[INLONG-6174][Sort] MySql connector support meta data with debezium format 

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CommonConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobWrapper.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskWrapper.java

Fix ConcurrentModification error when TestFileAgent UT
- Fixes #6251 
Run TestFIle UT error, change ArrayList to CopyOnWriteArrayList.
ArrayList to CopyOnWriteArrayList
TestFileAgent.testOneJobFullPath()

[INLONG-6251][Agent] Fix UT ConcurrentModification error

---

bin/init-config.sh
docker/docker-compose/docker-compose.yml
inlong-dataproxy/conf/dataproxy-pulsar.conf
inlong-dataproxy/conf/dataproxy-tube.conf
inlong-dataproxy/dataproxy-docker/dataproxy-docker.sh
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/heartbeat/HeartbeatManager.java

Update the heartbeat configuration.
- Fixes #6266 
Modify the container environment heartbeat IP acquisition.
agent1.sources.tcp-source.host = localhost

[INLONG-6266][Manager][DataProxy] Change the heartbeat configuration
