inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/LoadNodeUtils.java
-  Fixes #6268
support whole database migration for mysql-kafka
added raw format support to support raw debezium messages from mysql.
N/A
=> [INLONG-6268][Manager] Support raw format for Load nodes

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/sink/MultipleSinkOption.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/sink/SchemaUpdateExceptionPolicy.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/sink/TableChange.java
[INLONG-6246][Sort] Import multiple sink option and schema update handle policy
- Title Example: [INLONG-6246][Sort] Import multiple sink option and schema update handle policy
- Fixes #6246
*Import multiple sink option and schema update handle policy*
*Import multiple sink option and schema update handle policy*
=> [INLONG-6246][Sort] Import multiple sink option and schema update handle policy

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/SinkTask.java
=> [INLONG-6278][DataProxy] Needless to sleep() for order event

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java
=> [INLONG-6282][Manager] Fix the delete API not working problem in the manager client

inlong-dashboard/Dockerfile, inlong-dataproxy/dataproxy-docker/dataproxy-docker.sh
[INLONG-6280][Docker] Add tools for dashboard image
- Fixes #6280 
Add tools for dashboard images.
Add tools for dashboard images.
=> [INLONG-6280][Docker] Add tools for dashboard image

inlong-audit/audit-docker/Dockerfile, inlong-audit/audit-docker/audit-docker.sh
[INLONG-6289][Docker][Audit] Add configuration to choose starting proxy or store or both 
- Fixes #6289 
Add configuration to choose starting proxy or store or both 
Add configuration to choose starting proxy or store or both 
Add configuration to choose starting proxy or store or both
=> [INLONG-6289][Docker][Audit] Add configuration to choose starting proxy or store or both 

pom.xml
- Fixes #6291
*(example:)*
- If a …
=> [INLONG-6291][CVE] Update ini4j to fix the CVE-2022-41404

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/MqttJob.java, inlong-agent/agent-plugins/pom.xml, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/MqttSource.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/MqttReader.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestMqttConnect.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestMqttReader.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestMqttSource.java, inlong-common/src/main/java/org/apache/inlong/common/enums/TaskTypeEnum.java, licenses/inlong-agent/LICENSE, licenses/inlong-agent/licenses/LICENSE-paho.mqtt.java.txt, pom.xml
- About #4986 
*(example:)*
- If a …
=> [INLONG-4986][Agent] Support MQTT Source

inlong-tubemq/tubemq-manager/pom.xml, licenses/inlong-tubemq-manager/LICENSE
- Fixes #6303
*(example:)*
- If a …
=> [INLONG-6303][Dependency] Unify the guava version for the TubeMQ manager

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/CanalJsonDynamicSchemaFormat.java
[INLONG-6271][Sort] Unhandled update_before data in canal json in multiple sink scene
- [INLONG-6271][Sort] Unhandled update_before data in canal json in multiple sink scene
- Fixes #6271
*handle update_before data in canal json in multiple sink scene*
*handle update_before data in canal json in multiple sink scene*
=> [INLONG-6271][Sort] Unhandled update_before data in canal json in multiple sink scene

inlong-dashboard/src/metas/index.ts, inlong-dashboard/src/metas/sinks/common/SinkDefaultInfo.ts, inlong-dashboard/src/metas/sinks/common/SinkInfo.ts, inlong-dashboard/src/metas/sinks/defaults/Clickhouse.ts, inlong-dashboard/src/metas/sinks/defaults/Hive.ts, inlong-dashboard/src/metas/sinks/defaults/Kafka.ts, inlong-dashboard/src/metas/sinks/defaults/index.ts, inlong-dashboard/src/metas/sinks/extends/index.ts, inlong-dashboard/src/metas/sources/defaults/index.ts, inlong-dashboard/src/pages/GroupDetail/DataStorage/DetailModal.tsx, inlong-dashboard/src/pages/GroupDetail/DataStorage/index.tsx
Links to the sinks section of #6273
=> [INLONG-6273][Dashboard] Support asynchronous loading of sink plugins

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/sink/MultipleSinkOption.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/sink/SchemaUpdateExceptionPolicy.java, inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/FlinkDynamicTableFactory.java, inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/IcebergTableSink.java, inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/DynamicSchemaHandleOperator.java
[INLONG-6300][Sort] Schema update policy unifie behavior for all column change type
- [INLONG-6300][Sort] Schema update policy unifie behavior for all column change type
- Fixes #6300 
*Schema update policy unifie behavior for all column change type.*
*Schema update policy unifie behavior for all column change type.*
=> [INLONG-6300][Sort] Schema update policy unifie behavior for all column change type

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/heartbeat/HeartbeatManager.java
Fix  heartbeat information is null. 
- Fixes #6316 
Ip and port are null.
=> [INLONG-6316][DataProxy] Fix  heartbeat information is null

inlong-common/src/main/java/org/apache/inlong/common/enums/DataProxyErrCode.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/AttributeConstants.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/ConfigConstants.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/MessageUtils.java
=> [INLONG-6324][DataProxy] Optimize DataProxy's message processing on the source side

inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/table/RowDataDebeziumDeserializeSchema.java
- Fixes #6326 
Fix Incorrect type of log in all migrate converter
Fix Incorrect type of log in all migrate converter
run allmigrate test
=> [INLONG-6326][Sort] Fix the incorrect log type in the all migrate converter

docker/docker-compose/docker-compose.yml
- Fixes #6140
*(example:)*
- If a …
=> [INLONG-6140][Docker] Decrease the docker-compose version to be compatible with more environments

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/AgentPrometheusMetricListener.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/prometheus/PrometheusMetricListener.java
=> [INLONG-6331][Dataproxy] To fix dataproxy prometheus problem

inlong-agent/agent-docker/Dockerfile
=> [INLONG-6341][Docker] Update the default cluster and tag name for agent

inlong-dashboard/src/metas/sinks/defaults/Clickhouse.ts, inlong-dashboard/src/metas/sinks/defaults/Es.ts, inlong-dashboard/src/metas/sinks/defaults/Greenplum.ts, inlong-dashboard/src/metas/sinks/defaults/HBase.ts, inlong-dashboard/src/metas/sinks/defaults/Iceberg.ts, inlong-dashboard/src/metas/sinks/defaults/Kafka.ts, inlong-dashboard/src/metas/sinks/defaults/Mysql.ts, inlong-dashboard/src/metas/sinks/defaults/Oracle.ts, inlong-dashboard/src/metas/sinks/defaults/PostgreSql.ts, inlong-dashboard/src/metas/sinks/defaults/SQLServer.ts, inlong-dashboard/src/metas/sinks/defaults/TDSQLPostgreSql.ts, inlong-dashboard/src/metas/sinks/defaults/index.ts
- Fixes https://github.com/apache/inlong/issues/6330
=> [INLONG-6330][Dashboard] Other sinks support asynchronous loading of plugins

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/StreamSinkClient.java
- Fixes #6349
*(example:)*
- If a …
=> [INLONG-6349][Manager] StreamSinkClient support update/delete by key

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/DorisLoadNode.java, inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/internal/GenericDorisSinkFunction.java, inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/model/RespContent.java, inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java, inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicTableFactory.java, inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicTableSink.java, inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisStreamLoad.java, licenses/inlong-sort-connectors/LICENSE
- Title Example: [INLONG-6345] add metrics for Doris connector
- Fixes #6345 
add metrics
add metrics
*(example:)*
=> [INLONG-6345][Sort] Add metrics for Doris connector

inlong-dashboard/src/utils/index.ts
=> [INLONG-6359][Dashboard] The utils method adds null data compatibility

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SortStatus.java
=> [INLONG-6361][Manager] Fix the json deserialization exception with jackson version < 2.13

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java
- [INLONG-6366][Agent] Update position when data is successfully sent in order-send mode
- Fixes #6366 
*(example:)* …
=> [INLONG-6366][Agent] Update position when data is successfully sent in order-send mode

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
…perties in getSortSource
- Fixes #6371
*(example:)* …
=> [INLONG-6371][Manager] Fix the lack of topic and cache zone properties in getSortSource

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/BatchProxyMessage.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/message/PackProxyMessage.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/AbstractSink.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java, inlong-common/src/main/java/org/apache/inlong/common/msg/AttributeConstants.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java
- [INLONG-6376][Agent] Refactor sink and complement send metric
- Fixes #6376 
*(example:)*
- If a …
=> [INLONG-6376][Agent] Refactor sink and complement send metric

inlong-dashboard/src/locales/cn.json, inlong-dashboard/src/locales/en.json, inlong-dashboard/src/metas/clusters/defaults/Kafka.ts
- Fixes https://github.com/apache/inlong/issues/6375
- The details are as follows:
=> [INLONG-6375][Dashboard] Cluster supports new Kafka type

inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/debezium/table/RowDataDebeziumDeserializeSchema.java, inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/table/OracleReadableMetaData.java
[INLONG-6356][Sort] Oracle connector supports precision and binary type
- Fixes #6356
Oracle connector supports precision and binary type
=> [INLONG-6356][Sort] Oracle connector supports precision and binary type

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java, inlong-common/src/main/java/org/apache/inlong/common/enums/ComponentTypeEnum.java, inlong-common/src/main/java/org/apache/inlong/common/enums/DataProxyErrCode.java, inlong-common/src/main/java/org/apache/inlong/common/enums/DataTypeEnum.java, inlong-common/src/main/java/org/apache/inlong/common/enums/ManagerOpEnum.java, inlong-common/src/main/java/org/apache/inlong/common/enums/PullJobTypeEnum.java, inlong-common/src/main/java/org/apache/inlong/common/enums/RowKindEnum.java, inlong-common/src/main/java/org/apache/inlong/common/enums/TaskTypeEnum.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/heartbeat/HeartbeatManager.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/pulsar/PulsarClientService.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java, inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/HeartbeatClientTest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/ExtractNodeUtils.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/LoadNodeUtils.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/pulsar/PulsarSourceOperator.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceTest.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/heartbeat/HeartbeatManagerTest.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/HeartbeatServiceTest.java
- Fixes #6393
Remove the usage of lombok.
=> [INLONG-6393][Common] Remove the usage of lombok

inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/FlinkSink.java, inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergMultipleStreamWriter.java
[INLONG-6379][Sort] Bugfix:iceberg miss metric data in multiple sink scences
- [INLONG-6379][Sort] Bugfix:iceberg miss metric data in multiple sink scences
- Fixes #6379 
*Bugfix:iceberg miss metric data in multiple sink scences*
*Bugfix:iceberg miss metric data in multiple sink scences*
=> [INLONG-6379][Sort] Iceberg misses metric data in multiple sink scenes

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskPositionManager.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/MonitorTextFile.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/TextFileReader.java
Fix reboot will reset file position error when multiple  agent reboots.
- Fixes #6332 
Do not to change position when agent reboots.
Update position by local RocksDB.
=> [INLONG-6332][Agent] Fix reboot will reset file position error

inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlReadableMetadata.java
- Fixes #6370 
The op type in debezium format should be u or update
The op type in debezium format should be u or update
*(example:)*
=> [INLONG-6370][Sort] The op type in debezium format should be u or update

inlong-common/src/main/java/org/apache/inlong/common/enums/MetaField.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/Metadata.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/OracleExtractNode.java, inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/OracleExtractNodeTest.java, inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/table/OracleReadableMetaData.java
[INLONG-6402][Sort] Modify the metadata field of oracle connector
- Fixes #6402 
Modify the metadata field of oracle connector.
=> [INLONG-6402][Sort] Modify the metadata field of oracle connector

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/standalone/SortSourceClusterInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/standalone/SortSourceGroupInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/standalone/SortSourceStreamSinkInfo.java
- Fixes #6415 
Json serialization failure in SortSourceService when one field is primitive type.
=> [INLONG-6415][Manager] Fix json serialization failure in SortSourceService

inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/RmtDataCache.java, inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/producer/ProducerManager.java, inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/utils/DataConverterUtil.java, inlong-tubemq/tubemq-core/src/test/java/org/apache/inlong/tubemq/corerpc/codec/DataConverterUtilTest.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/bdbstore/bdbentitys/BdbBrokerConfEntity.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/BrokerConfEntity.java
=> [INLONG-6419][TubeMQ] Correct some misuse of META_DEFAULT_BROKER_PORT

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/bdbstore/bdbentitys/BdbBrokerConfEntity.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/DefaultMetaDataService.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/BrokerConfEntity.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/DefBrokerRunManager.java
=> [INLONG-6421][TubeMQ] Fix the host is blank error

inlong-common/src/main/java/org/apache/inlong/common/enums/NodeSrvStatus.java, inlong-common/src/main/java/org/apache/inlong/common/heartbeat/ComponentHeartbeat.java, inlong-common/src/main/java/org/apache/inlong/common/heartbeat/HeartbeatMsg.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/heartbeat/HeartbeatManager.java
=> [INLONG-6439][DataProxy] Added service status and load fields in heartbeat request

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/msgstore/MessageStoreManager.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/dao/entity/TopicDeployEntity.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsConsumeCtrlMapperImpl.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/metamanage/metastore/impl/AbsTopicDeployMapperImpl.java
=> [INLONG-6422][TubeMQ] Deleting the topic was unsuccessful

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/MasterConfig.java
=> [INLONG-6446][TubeMQ] Fix misuse of SECT_TOKEN_BROKER

CHANGES.md
- Fixes #6431
add all closed issues to the changelog for release 1.4.0.
=> [INLONG-6431][Release] Update changes log for the 1.4.0 version

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/OffsetRecordService.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/TMaster.java
=> [INLONG-6423][TubeMQ] Consumer registration failed due to BDB error

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/SqlServerConstants.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/SqlServerJob.java, inlong-agent/agent-plugins/pom.xml, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/SQLServerSource.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/SQLServerReader.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/snapshot/SqlServerSnapshotBase.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestSQLServerConnect.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestSQLServerReader.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestSQLServerSource.java, pom.xml
- Fixes #6327 
*(example:)*
- If a …
=> [INLONG-6327][Agent] Support collect data from SQLServer by Debezium

.github/workflows/ci_docker.yml
- Fixes #6459
branch-1.4 as the base branch to release 1.4.x.
branch-1.5 as the base branch to release 1.5.x in the future.
=> [INLONG-6459][CI] Match the branch-version as release branch

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java
- [INLONG-6417][SDK] Support proxy-send mode
- Fixes #6417 
*(example:)* …
=> [INLONG-6417][SDK] Support proxy-send mode

conf/inlong.conf, docker/docker-compose/.env, docker/kubernetes/values.yaml, inlong-agent/agent-docker/README.md, inlong-audit/audit-docker/README.md, inlong-dataproxy/dataproxy-docker/README.md, inlong-manager/manager-docker/README.md, inlong-tubemq/tubemq-docker/tubemq-all/README.md, inlong-tubemq/tubemq-docker/tubemq-manager/README.md
- Fixes #6435
Change the tag of Docker images to 1.4.0
=> [INLONG-6435][Release] Change the tag of Docker images to 1.4.0

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/AbstractDynamicSchemaFormat.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/CanalJsonDynamicSchemaFormat.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormat.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/DynamicSchemaFormatFactory.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/JsonDynamicSchemaFormat.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/JsonToRowDataConverters.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/sink/MultipleSinkOption.java, inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/format/CanalJsonDynamicSchemaFormatTest.java, inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormatTest.java, inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormatWithSchemaTest.java, inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicTableFactory.java, inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/FlinkDynamicTableFactory.java, inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/IcebergTableSink.java, inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/DynamicSchemaHandleOperator.java, inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicTableFactory.java
[INLONG-6409][Sort] Bugfix:unspported Time and Timestamp iceberg auto create table in spark session query
- [INLONG-6409][Sort] Bugfix:unspported Time and Timestamp iceberg auto create table in spark session query
- Fixes #6409 
*Spported Time and Timestamp iceberg auto create table in spark session query*
*convert time to string and timestamp to timestamp with local zone.*
=> [INLONG-6409][Sort] Unspported Time and Timestamp iceberg auto create table in spark session query

inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergMultipleStreamWriter.java
- Title Example: [INLONG-6379][Sort] Complement iceberg multiple sink metric data compute
- Fixes #6379 
*Complement iceberg multiple sink metric data compute*
*Complement iceberg multiple sink metric data compute*
=> [INLONG-6379][Sort] Complement iceberg multiple sink metric data compute

docker/docker-compose/docker-compose.yml
- Fixes #6475
Add a base Flink environment for docker-compose, making the developer easy to start.
=> [INLONG-6475][Docker] Add a base flink environment for docker-compose

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/PulsarSink.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/TubeSink.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/TubeProducerHolder.java
=> [INLONG-6406][DataProxy] Should support creating sink dynamically after started (addendum)

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java
- Title : [INLONG-6491][Manager] Support getting backup info in getAllConfig
- Fixes #6491 
*(example:)* …
=> [INLONG-6491][Manager] Support getting backup info in getAllConfig

inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/DynamicSchemaHandleOperator.java
[INLONG-6484][Sort] Bugfix: fix schema update circular dependency error in multiple sink iceberg scenes
- [INLONG-6484][Sort] Fix schema update Circular dependency error in multiple sink iceberg scenes
- Fixes #6484 
*Fix schema update Circular dependency error in multiple sink iceberg scenes*
*Fix schema update Circular dependency error in multiple sink iceberg scenes*
=> [INLONG-6484][Sort] Fix schema update circular dependency error in multiple sink iceberg scenes

inlong-dashboard/src/metas/streams/common/StreamDefaultInfo.ts, inlong-dashboard/src/pages/GroupDetail/DataStream/StreamItemModal.tsx
=> [INLONG-6493][Dashboard] After the Stream is configured successfully, some parameters cannot be modified

inlong-dashboard/src/components/EditableTable/index.tsx
=> [INLONG-6511][Dashboard] The Select/AutoComplete component in EditableTable will mistakenly change the value and cause re-rendering

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java
=> [INLONG-6515][Manager] Fix the NullPointerException for the cache configuration of DataProxy

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/group/InitGroupCompleteListener.java
- Fixes #6525 
Fix the problem that  when the enable_create_resource parameter of inlongGroup is set to 0, the stream and source status cannot be updated after the group configuration is completed.
Update the status of stream and source after the group configuration is completed
=> [INLONG-6525][Manager] Update the status of stream and source after the group configuration is completed

inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSourceController.java
- Fixes #6526 
Fix the problem of mananger-client calling to forcibly delete the source interface failed
Modified the parameter name of the interface.
=> [INLONG-6526][Manager] Fix the manager-client force delete the stream source failed

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupStatus.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SimpleGroupStatus.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SinkStatus.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/StreamStatus.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamProcessService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java
- Fixes #6517
Support delete stream sink when the inlong group was config_failed.
=> [INLONG-6517][Manager] Support delete stream sink when the inlong group was config_failed

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/JsonToRowDataConverters.java
[INLONG-6538][Sort] Fix wrong bool type convert in multiple sink scenes
- Title Example: [INLONG-6538][Sort] Fix wrong bool type convert in multiple sink scenes
- Fixes #6538 
*Fix wrong bool type convert in multiple sink scenes*
*'true' and '1' regard as true*
=> [INLONG-6538][Sort] Fix wrong bool type convert in multiple sink scenes

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/codec/EncodeObject.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/codec/ProtocolDecoder.java
- Fixes #6550 
Fix the decode heartbeat response error.
=> [INLONG-6550][SDK] Fix the decode heartbeat response error

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepositoryTest.java
- Fixes #6515 
Fix the NPE in the cache configuration of DataProxy.
=> [INLONG-6515][Manager] NPE is thrown in the cache configuration of DataProxy

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/group/InitGroupCompleteListener.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/stream/InitStreamCompleteListener.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java
- Fixes #6544
Should update the source status after the inlong stream is completed.
=> [INLONG-6544][Manager] Should update the source status after the inlong stream is completed

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java
=> [INLONG-6531][Manager] Add load value in the response of getIpList method (addendum)

.github/workflows/ci_docker.yml, docker/build-docker-images.sh
Add notes for building arm images
- Fixes #6522 
Add notes for building arm images
Add notes for building arm images
Add notes for building arm images
=> [INLONG-6522][Docker] Add notes for building arm images

inlong-dashboard/src/pages/GroupDetail/DataStorage/index.tsx
- Fixes https://github.com/apache/inlong/issues/6572
=> [INLONG-6572][Dashboard] Stream is not deleted by default when the sink is deleted

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
- Fixes #6561 
Fix the problem that the group cannot be deleted
Delete stream before deleting group.
=> [INLONG-6561][Manager] Fix the InlongGroup cannot be deleted

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ClusterType.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/es/ElasticsearchClusterDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/es/ElasticsearchClusterInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/es/ElasticsearchClusterRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/ElasticsearchClusterOperator.java
- Fixes #6497 
Support Elasticsearch cluster
- Does this pull request introduce a new feature? yes 
=> [INLONG-6497][Manager] Support Elasticsearch cluster

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/IdTopicConfigHolder.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/DefaultEventHandler.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/EventHandler.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/SinkContext.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/BatchPackManager.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/BatchPackProfile.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/BatchPackProfileCallback.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueClusterProducer.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueHandler.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneProducer.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSink.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSinkContext.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneWorker.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/OrderBatchPackProfileV0.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/SimpleBatchPackProfileV0.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/kafka/KafkaHandler.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/tube/TubeHandler.java
- Title: [INLONG-6153][DataProxy]Optimize the sink architecture of DataProxy
- Fixes #6153 
*(example:)* …
=> [INLONG-6153][DataProxy] Optimize the sink architecture

inlong-dashboard/src/locales/cn.json, inlong-dashboard/src/locales/en.json
=> [INLONG-6581][Dashboard] The file format prompt of the FILE source is error

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClientConfig.java
=> [INLONG-6588][SDK] Change the NumberUtils dependency of Sort-Sdk

inlong-tools/grafana/dashboards/agent.json, inlong-tools/grafana/dashboards/dataproxy.json
- Fixes #4957 
*(example:)*
- If a …
=> [INLONG-4957][Agent][DataProxy] Add Grafana metrics dashboard

README.md
=> [INLONG-6624][Doc] Add Stargazers and Contributor chart for readme

inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/DataConfig.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongGroupEntity.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupApproveRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/AbstractGroupOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupService.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/ServiceBaseTest.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/group/GroupServiceTest.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sort/SortServiceImplTest.java, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql
=> [INLONG-6610][Manager] Support the saving and query of data report-to settings

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClientFactory.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSource.java
- Fixes #6626
*(example:)*
- If a …
=> [INLONG-6626][Sort] Use SortClientV2 by default

inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaProducer.java, inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/DynamicKafkaDeserializationSchema.java
- [INLONG-6615][Sort] Fix upsert kafka will throw NPE when get delete record
- Fixes #6615 
* Fix upsert kafka will throw NPE when get delete record
* Add null judge for DELETE record
=> [INLONG-6615][Sort] Fix upsert Kafka will throw NPE when getting deleted record

inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/src/utils.cc, inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/utils/RegexDef.java
=> [INLONG-6638][TubeMQ] C++ client supports filtering consume with the "-" character

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/es/ElasticsearchFieldInfo.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/es/ElasticsearchApi.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/es/ElasticsearchResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/AbstractSinkOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/es/ElasticsearchSinkOperator.java
- Fixes #6665
Support to save additional information for Elasticsearch field
=> [INLONG-6665][Manager] Support to save additional information for Elasticsearch field

inlong-dashboard/src/metas/index.ts
=> [INLONG-6680][Dashboard] Set the plugin to default when there is no target plugin

inlong-dashboard/package-lock.json, inlong-dashboard/src/metas/nodes/defaults/index.ts, inlong-dashboard/src/metas/sinks/common/SinkDefaultInfo.ts
=> [INLONG-6678][Dashboard] Add sinkType parameter in sinkFieldList

inlong-dashboard/src/pages/Clusters/CreateModal.tsx, inlong-dashboard/src/pages/Clusters/index.tsx, inlong-dashboard/src/pages/GroupDetail/DataSources/DetailModal.tsx, inlong-dashboard/src/pages/GroupDetail/DataSources/index.tsx, inlong-dashboard/src/pages/GroupDetail/DataStorage/DetailModal.tsx, inlong-dashboard/src/pages/GroupDetail/DataStorage/index.tsx, inlong-dashboard/src/pages/Nodes/DetailModal.tsx, inlong-dashboard/src/pages/Nodes/index.tsx
=> [INLONG-6694][Dashboard] Create with filter value first, if there is a filter plugin

inlong-dashboard/src/metas/sinks/defaults/Iceberg.ts
- Fixes https://github.com/apache/inlong/issues/6697
=> [INLONG-6697][Dashboard] Optimize iceberg sink Required

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
=> [INLONG-6610][Manager] Support the saving and query of data report-to settings (addendum)

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/SortCluster.java
- Fixes #6707 
Delay the release of audit metric instances to avoid the reported audit metric missing
*(example:)*
=> [INLONG-6707][Sort] Delay the release of audit metrics

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/IdTopicConfigHolder.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/loader/ManagerIdTopicConfigLoader.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/pojo/IdTopicConfig.java
=> [INLONG-6715][DataProxy]  Fix json problem in data proxy

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterEntityMapper.xml
- Fixes #6720 
Implement InlongClusterEntityMapper.selectByClusterTag
Implement InlongClusterEntityMapper.selectByClusterTag
=> [INLONG-6720][Manager] Implement InlongClusterEntityMapper.selectByClusterTag

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
=> [INLONG-6610][Manager] Support query all MQ clusters by cluster tag (addendum)

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/QueryConsumeConfig.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/QueryConsumeConfigImpl.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/SortClientImplV2.java, inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/loader/ClassResourceQueryConsumeConfig.java
- Fixes #6656
Make QueryConsumerConfig plugin to support different cases
*(example:)*
=> [INLONG-6656][SDK] Support QueryConsumerConfig plugin

README.md
- Fixes https://github.com/apache/inlong/issues/6705
=> [INLONG-6705][Doc] Update the supported Extract Node table

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/DataProxyMetricItem.java
- Fixes #6708
Add more metrics of DataProxy
*(example:)*
=> [INLONG-6708][DataProxy] Add more metrics of DataProxy

inlong-tubemq/tubemq-client-twins/tubemq-client-python/README.md, inlong-tubemq/tubemq-client-twins/tubemq-client-python/src/cpp/tubemq_client.cc, inlong-tubemq/tubemq-client-twins/tubemq-client-python/src/cpp/tubemq_config.cc, inlong-tubemq/tubemq-client-twins/tubemq-client-python/src/cpp/tubemq_message.cc, inlong-tubemq/tubemq-client-twins/tubemq-client-python/src/python/example/test_producer.py, inlong-tubemq/tubemq-client-twins/tubemq-client-python/src/python/tubemq/__init__.py, inlong-tubemq/tubemq-client-twins/tubemq-client-python/src/python/tubemq/client.py
- Implement #4969 
Implement the python producer sdk through pybind11 that wrapping the c++ sdk.
add pybind11 `module`, `class`, in `tubemq-client-python`
=> [INLONG-4969][TubeMQ] Python SDK for Producing Message

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/BatchProxyMessage.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java, inlong-agent/agent-common/src/test/java/org/apache/inlong/agent/conf/TestConfiguration.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/message/PackProxyMessage.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/AbstractSink.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/PulsarSink.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/PulsarSinkTest.java, inlong-agent/agent-plugins/src/test/resources/pulsarSinkJob.json, inlong-common/src/main/java/org/apache/inlong/common/enums/TaskTypeEnum.java, inlong-common/src/main/java/org/apache/inlong/common/msg/AttributeConstants.java, inlong-common/src/main/java/org/apache/inlong/common/util/MessageUtils.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java
- [INLONG-6704][Agent] Add PulsarSink
- Fixes #6704 
- Let `inlong-agent` support directly sending data to Pulsar to avoid missing data.
- Add pulsar sink ability.
- Abstract some method to `inlong-common`.
*(example:)* …
=> [INLONG-6704][Agent] Add PulsarSink

inlong-sort/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/stream/AbstractStreamingWriter.java
- [INLONG-6575][Sort] Add dirty data metric for Filesystem
- Fixes #6575 
* Add dirty data metric for Filesystem
* Add dirty data metric for Filesystem
=> [INLONG-6575][Sort] Add dirty data metric for Filesystem

inlong-manager/manager-dao/src/main/resources/mappers/DataNodeEntityMapper.xml
- Fixes #6768 
Fix the problem of unable to find dataNode information according to keyword
Fix the problem of unable to find dataNode information according to keyword
=> [INLONG-6768][Manager] Fix the problem of unable to find dataNode information according to keyword

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hive/HiveSinkRequest.java
- Fixes #6763 
Remove unnecessary validation when saving HiveSinkRequest
Remove unnecessary validation when saving HiveSinkRequest
=> [INLONG-6763][Manager] Remove unnecessary validation when saving HiveSinkRequest

inlong-dashboard/.env.production, inlong-dashboard/craco.config.ts, inlong-dashboard/package-lock.json, inlong-dashboard/package.json
=> [INLONG-6775][Dashboard] Fix the risk of source code exposure in the production environment

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
- Fixes #6773 
Fix the problem of sink cannot jump from the configuration to successful configuration
Adjust sink status based on `enableCreateResource`.
=> [INLONG-6773][Manager] Fix the problem of sink cannot jump from the configuration to successful configuration

inlong-distribution/src/main/assemblies/sort-connectors.xml, inlong-sort/pom.xml, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java, inlong-sort/sort-connectors/hudi/pom.xml, inlong-sort/sort-connectors/hudi/src/main/java/org/apache/inlong/sort/hudi/table/HudiTableInlongFactory.java, inlong-sort/sort-connectors/hudi/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, inlong-sort/sort-connectors/pom.xml, licenses/inlong-sort-connectors/licenses/LICENSE-hudi-flink1.13-bundle.txt, pom.xml
**Introduce apache hudi sort connector**
- Fixes #6782 
*(example:)*
=> [INLONG-6782][Sort] Support Apache Hudi connector

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/LoadNodeUtils.java
[INLONG-6806] Fix the hosts incorrect parameter delivered by the manager
- Fixes #6806
Fix the hosts incorrect parameter of es connector delivered by the manager
Fix the hosts incorrect parameter of es connector delivered by the manager
=> [INLONG-6806][Manager] Fix the hosts incorrect parameter of es connector delivered by the manager

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/LoadNode.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/HudiLoadNode.java, inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/HudiLoadNodeTest.java, inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/HudiNodeSqlParserTest.java
*[INLONG-6784][Sort] Support apache hudi LoadNode*
- Fixes #6784 
*(example:)*
=> [INLONG-6784][Sort] Support load node of Apache Hudi

README.md
*[INLONG-6787][Doc] Add the usage document for Apache Hudi*
- Fixes #6787 
*(example:)*
=> [INLONG-6787][Doc] Add the usage document for Apache Hudi

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongGroupClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongGroupApi.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongGroupEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupTopicRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java
- Fixes #6676
Support list all inlong topic infos under one given cluster tag
*(example:)*
=> [INLONG-6676][Manager] Support list all InlongTopicInfo under a given cluster tag

README.md
- Fixes #6833
*(example:)*
- If a …
=> [INLONG-6833][Doc] Add doris and starrocks load node in README.md

inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/netty/NettyClientFactory.java
- Fixes #6850 
fix duplicated exception caught
Remove the duplicated exception caught
This change is a code cleanup without any test coverage.
No docs are needed.
=> [INLONG-6850][TubeMQ] fix duplicated excception caught

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentMain.java, inlong-dataproxy/bin/dataproxy-stop.sh
- Fixes #6852
agent and dataproxy report audit data when the program exits
=> [INLONG-6852][Audit] agent and dataproxy report audit data when the program exits

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/ConfigConstants.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClientConfig.java
- Fixes #5669
Extract SortClientConfig parameters key to constants
=> [INLONG-5669][SDK] Extract SortClientConfig parameters key to constants

inlong-dashboard/src/loaders/Loader.ts, inlong-dashboard/src/loaders/clusters/ClusterDefaultLoader.ts, inlong-dashboard/src/loaders/clusters/ClusterLoader.ts, inlong-dashboard/src/loaders/clusters/index.ts, inlong-dashboard/src/loaders/consumes/ConsumeDefaultLoader.ts, inlong-dashboard/src/loaders/consumes/ConsumeLoader.ts, inlong-dashboard/src/loaders/consumes/index.ts, inlong-dashboard/src/loaders/groups/GroupDefaultLoader.ts, inlong-dashboard/src/loaders/groups/GroupLoader.ts, inlong-dashboard/src/loaders/groups/index.ts, inlong-dashboard/src/loaders/index.ts, inlong-dashboard/src/loaders/nodes/NodeDefaultLoader.ts, inlong-dashboard/src/loaders/nodes/NodeLoader.ts, inlong-dashboard/src/loaders/nodes/index.ts, inlong-dashboard/src/loaders/sinks/SinkDefaultLoader.ts, inlong-dashboard/src/loaders/sinks/SinkLoader.ts, inlong-dashboard/src/loaders/sinks/index.ts, inlong-dashboard/src/loaders/sources/SourceDefaultLoader.ts, inlong-dashboard/src/loaders/sources/SourceLoader.ts, inlong-dashboard/src/loaders/sources/index.ts, inlong-dashboard/src/loaders/streams/StreamDefaultLoader.ts, inlong-dashboard/src/loaders/streams/StreamLoader.ts, inlong-dashboard/src/loaders/streams/index.ts, inlong-dashboard/src/metas/clusters/index.ts, inlong-dashboard/src/metas/consumes/index.ts, inlong-dashboard/src/metas/nodes/index.ts, inlong-dashboard/src/metas/sinks/index.ts, inlong-dashboard/src/metas/sources/index.ts, inlong-dashboard/src/metas/streams/index.ts
=> [INLONG-6826][Dashboard] Support loading different plugins using different loaders

inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/File2HudiExample.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/SinkType.java, inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/enums/ConnectorJarType.java, inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/RestartStreamListener.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/hudi/HudiDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/hudi/HudiDataNodeInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/hudi/HudiDataNodeRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hudi/HudiColumnInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hudi/HudiPartition.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hudi/HudiPartitionField.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hudi/HudiSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hudi/HudiSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hudi/HudiSinkRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hudi/HudiTableInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hudi/HudiType.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/LoadNodeUtils.java, inlong-manager/manager-service/pom.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/hudi/HudiDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/hudi/HudiCatalogClient.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/hudi/HudiResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/hudi/HudiSinkOperator.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/HudiSinkServiceTest.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/HudiConstant.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/HudiLoadNode.java, inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/HudiLoadNodeTest.java, inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/HudiNodeSqlParserTest.java
*[Manager] Support register and manage hudi sort*
- Fixes #6785 
*(example:)*
=> [INLONG-6785][Manager] Support register and manage the resource of Apache Hudi

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/user/UserLoginLockStatus.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/AnnoController.java, inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/controller/AnnoControllerTest.java
- Fixes #6771
if the user login fails, we should limit the login times to prevent violent retries.
here we can limit it to 10 fails times and wait for 3 minutes.
loginService
- AnnoControllerTest
=> [INLONG-6771][Manager] Add login failure limit

inlong-dashboard/pom.xml
- Fixes #6865
refer to https://github.com/eirslett/frontend-maven-plugin/issues/855, to keep a stable package-lock.
=> [INLONG-6865][Dashboard] Support npm ci command for stable package-lock

inlong-dashboard/src/metas/streams/common/StreamDefaultInfo.ts
- Fixes https://github.com/apache/inlong/issues/6874
=> [INLONG-6874][Dashboard] Stream removes the Raw-CSV data format

inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/example/consumer/test_consumer.cc, inlong-tubemq/tubemq-client-twins/tubemq-client-python/src/python/example/test_consumer.py, inlong-tubemq/tubemq-client-twins/tubemq-client-python/src/python/tubemq/client.py
=> [INLONG-6878][TubeMQ] Improve the description of the return code in the consumer SDK

inlong-sort/sort-connectors/hive/src/main/java/org/apache/inlong/sort/hive/filesystem/AbstractStreamingWriter.java
- [INLONG-6864][Sort] Modify hive metric computing to ensure metric data accuracy
- Fixes #6864 
* Modify hive metric computing to ensure metric data accuracy
* computing metric after checkpoint
=> [INLONG-6864][Sort] Modify hive metric computing to ensure metric data accuracy

.github/workflows/ci_docker.yml
=> [INLONG-6888][CI] Fix the bug of all Docker workflow failed

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/ExtractNodeUtils.java
- Fixes #6876 
see https://github.com/apache/inlong/pull/6859
see https://github.com/apache/inlong/pull/6859
=> [INLONG-6876][Manager] Always enable "scan.incremental.snapshot" for MySQL extract node

docker/docker-compose/README.md
- Fixes #6882
After the https://github.com/apache/inlong/pull/6693, we need to update the docker-compose version requirement in the readme
=> [INLONG-6882][Docker] Update the docker-compose version requirement in the readme

.github/workflows/ci_chart_test.yml, .github/workflows/ci_docker.yml
- Fixes #6893
caused by https://github.com/apache/inlong/pull/6556
=> [INLONG-6893][CI] Fix build and push docker image skipped

.github/workflows/ci_chart_test.yml, .github/workflows/ci_docker.yml
- Fixes #6893
caused by https://github.com/apache/inlong/pull/6556
=> [INLONG-6893][CI] Fix build and push docker image skipped(addendum)

inlong-dataproxy/conf/dataproxy-tubemq.conf, inlong-dataproxy/conf/dataproxy.conf, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/tube/TubeHandler.java, inlong-manager/manager-dao/src/main/resources/mappers/ClusterSetMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/tubemq/TubeClusterDTO.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/TubeClusterOperator.java
- Fixes #6890
- fix sql condition enum
- optimize config file naming and sink code
=> [INLONG-6890][DataProxy] Fix tubemq MQ_TYPE enum and optimize sink code and config file

inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
- Title: [INLONG-6886][Sort] Add dirty message for doris sink
- Fixes #6886
Add dirty message for doris sink. The dirty message is the cause of dirty data, in this part, i will ingest it for doris sink and it can be used by '${DIRTY_MESSAGE}' if needed.
Add dirty message handle for 'DorisDynamicSchemaOutputFormat'
*(example:)*
- If yes, how is …
=> [INLONG-6886][Sort] Add dirty message for doris sink

inlong-dashboard/src/pages/GroupDetail/DataStorage/DetailModal.tsx
=> [INLONG-6900][Dashboard] Support pulling up the field list of Source in Sink

inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java, inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/util/DorisParseUtils.java
fixes [[Bug][Sort] date rowkind field for doris sink is parsed to null](https://github.com/apache/inlong/issues/6823)
=> [INLONG-6823][Sort] Parse the epoch date to normal date for Doris sink

inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicTableFactory.java
- [INLONG-6914][Sort] Fix Doris connector parallelism setting error
- Fixes #6914 
* Fix Doris connector parallelism setting error
* Modify default parallelism setting to null
=> [INLONG-6914][Sort] Fix Doris connector parallelism setting error

inlong-dashboard/src/locales/cn.json, inlong-dashboard/src/locales/en.json, inlong-dashboard/src/metas/sources/defaults/File.ts
- Fixes https://github.com/apache/inlong/issues/6904
=> [INLONG-6904][Dashboard] File source type supports selecting agent cluster

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/StreamTransformService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/StreamTransformServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/openapi/OpenAPIAuthenticatingRealm.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/openapi/OpenAPIFilter.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenStreamSourceController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenStreamTransformController.java
=> [INLONG-6933][Manager] Add OpenAPIs for InLong stream-source and stream-transform operations

inlong-dashboard/src/pages/Process/index.tsx
- Fixes https://github.com/apache/inlong/issues/6923
=> [INLONG-6923][Dashboard] Application and Approval Interchange for Approval Management

inlong-dashboard/src/metas/sources/defaults/index.ts
=> [INLONG-6940][Dashboard] Type name correction

inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcBatchingOutputFormat.java, inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDynamicTableSink.java
- Fixes #6949 
support all rowkinds for metric computing for jdbc connector
[INLONG-6949][Sort] support all rowkinds for metric computing for jdbc connector
=> [INLONG-6949][Sort] support all rowkinds for metric computing and restore metrics state for dirty metric for jdbc connector

inlong-dashboard/src/locales/cn.json, inlong-dashboard/src/locales/en.json, inlong-dashboard/src/metas/nodes/defaults/Elasticsearch.ts, inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/es/ElasticsearchSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/es/ElasticsearchSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/es/ElasticsearchSinkRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/LoadNodeUtils.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/es/ElasticsearchConfig.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/es/ElasticsearchResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/es/ElasticsearchSinkOperator.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/ElasticsearchSinkServiceTest.java
- Title: [INLONG-6838][Manager] Support multi addresses for ES load node
- Fixes #6838 
Support multi addresses for ES load node
Get `url` parameter from ES data node. And then, support multi addresses for ES load node.
=> [INLONG-6838][Manager] Support multi addresses for ES load node

bin/inlong-daemon
=> [INLONG-6955][Script] Support starts the DataProxy with Kafka in the deployment script

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/starrocks/StarRocksColumnInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/starrocks/StarRocksSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/starrocks/StarRocksSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/starrocks/StarRocksSinkRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/starrocks/StarRocksTableInfo.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/starrocks/StarRocksJdbcUtils.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/starrocks/StarRocksResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/starrocks/StarRocksSqlBuilder.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/starrocks/StarRocksSinkOperator.java
- Fixes #6938 
Supports to create a starRocks database or table
Supports to create a starRocks database or table
=> [INLONG-6938][Manager] Supports to create a StarRocks database or table

inlong-dataproxy/dataproxy-docker/dataproxy-docker.sh
- Fixes #6964
User `#!/bin/bash` to avoid.
=> [INLONG-6964][DataProxy] Fix the start error when deploy in docker-compose

inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/metrics/MySqlSourceReaderMetrics.java, inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlRecordEmitter.java, inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlSourceReader.java, inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/split/MySqlMetricSplit.java, inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/split/MySqlSplitSerializer.java
- [INLONG-6962][Sort] Add read phase metric and table level metric for MySQL-CDC
- Fixes #6962
Add table granularity read indicators and read stage indicators in mysql cdc incremental snapshot mode.
Add table granularity read indicators and read stage indicators in mysql cdc incremental snapshot mode.
=> [INLONG-6962][Sort] Add read phase metric and table level metric for MySQL-CDC

inlong-dashboard/src/metas/sources/defaults/File.ts
=> [INLONG-6975][Dashboard] The cluster name of the File source does not support modification

inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/MockSink.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/PulsarSinkTest.java
- Title Example: [INLONG-6970][Agent] Improve UnitTest
- Fixes #6970 
*(example:)* …
=> [INLONG-6970][Agent] Improve UnitTest for PulsarSink

inlong-common/src/main/java/org/apache/inlong/common/enums/TaskTypeEnum.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/SourceType.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/ExtractNodeUtils.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/hudi/HudiSource.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/hudi/HudiSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/hudi/HudiSourceRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/hudi/HudiSourceOperator.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/HudiConstant.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/ExtractNode.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/HudiExtractNode.java, inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/HudiExtractNodeTest.java
*[INLONG-6858][Sort] Support extract node of Apache Hudi*
- Fixes #6858 
*(example:)*
=> [INLONG-6858][Manager][Sort] Support extract node of Apache Hudi

inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml
- Fixes #6992 
Fix the problem of streamSource is always in the status of TO_BE_ISSUED_DELETE
StreamSource without clusterName are also selected to issue.
=> [INLONG-6992][Manager] Fix the problem of streamSource is always in the status of TO_BE_ISSUED_DELETE

inlong-dashboard/src/components/FormGenerator/FormGenerator.tsx, inlong-dashboard/src/pages/GroupDetail/Info/index.tsx
=> [INLONG-6983][Dashboard] Group page supports multiple columns

inlong-dataproxy/conf/dataproxy-mulit-pulsar-http-example.conf, inlong-dataproxy/conf/dataproxy-mulit-pulsar-udp-example.conf, inlong-dataproxy/conf/dataproxy-tubemq.conf, inlong-dataproxy/conf/dataproxy.conf, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/ConfigConstants.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/HttpBaseSource.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/PulsarSink.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/TubeSink.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/BaseSource.java
=> [INLONG-6985][DataProxy] Make maxMonitorCnt setting configurable

inlong-dashboard/src/metas/clusters/common/ClusterDefaultInfo.ts
=> [INLONG-6926][Dashboard] Change the cluster type to lower case

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SinkSubMetricData.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SinkTopicMetricData.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/util/MetricStateUtils.java, inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/DynamicKafkaSerializationSchema.java, inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaProducer.java, inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/KafkaDynamicSink.java, inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicTableFactory.java, inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/UpsertKafkaDynamicTableFactory.java
- Fixes #6749 
1. Check whether the writing is successful and then count.
2. Add dirty metric.
3. Supports topic-level metrics.
=> [INLONG-6657][Sort] Add dirty metric for Kafka

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/DataNodeType.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/starrocks/StarRocksDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/starrocks/StarRocksDataNodeInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/starrocks/StarRocksDataNodeRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/starrocks/StarRocksDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/starrocks/StarRocksResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/starrocks/StarRocksSinkOperator.java
- Fixes #6988 
Use the data node info for StarRocks
- read from data node when starRocks url is not supplied
=> [INLONG-6988][Manager] Use the data node info for StarRocks

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/message/SequentialID.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/message/SequentialIDTest.java, inlong-common/src/main/java/org/apache/inlong/common/util/SnowFlake.java
- Title Example: [INLONG-6960][Agent] Fix repeat uuid generation for different messages
- Fixes #6960 
- using snowflake algorithm to generate uuid
*(example:)* …
=> [INLONG-6960][Agent] Fix repeat uuid generation for different messages

inlong-dashboard/src/metas/streams/common/StreamDefaultInfo.ts
=> [INLONG-6935][Dashboard] Add Key-Value format for InlongStream

inlong-dashboard/src/metas/nodes/common/NodeDefaultInfo.ts, inlong-dashboard/src/metas/nodes/defaults/index.ts, inlong-dashboard/src/pages/ConsumeDashboard/index.tsx
- Fixes https://github.com/apache/inlong/issues/7009
=> [INLONG-7009][Dashboard] The data node type supports lowercase

inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/split/MySqlSplitSerializer.java
- [INLONG-7014][Sort] Mysql state restore is compatible with old task state
- Fixes #7014 
* Mysql state restore is compatible with old task state
* 
* Modify `MySqlSplitSerializer` to adapt state update
=> [INLONG-7014][Sort] Mysql state restore is compatible with old task state

inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/common/ClientStatsInfo.java, inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/metric/impl/ESTHistogram.java, inlong-tubemq/tubemq-core/src/test/java/org/apache/inlong/tubemq/corebase/metric/HistogramTest.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerServiceServer.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/stats/BrokerSrvStatsHolder.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/web/BrokerAdminServlet.java
=> [INLONG-6997][TubeMQ] Add sendMessage and getMessage latency statistics

inlong-dashboard/src/locales/cn.json, inlong-dashboard/src/locales/en.json, inlong-dashboard/src/metas/streams/common/StreamDefaultInfo.ts, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamInfo.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/pulsar/PulsarSourceOperator.java
**[INLONG-6961][Dashboard][Manager] Support for configing non-InlongMsg formats**
- Fixes #6961 
*(example:)* …
=> [INLONG-6961][Dashboard][Manager] Support for configing non-InlongMsg formats

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java
*[INLONG-7011][Manager] Check Pulsar non-partition table if exist*
- Fixes #7011 
*(example:)*
=> [INLONG-7011][Manager] Check Pulsar non-partition table if exist

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaOperator.java
- Fixes #7026 
Fixed the problem of not checked before creating the kafka topic.
Check the existence of a kafka topic before creating it.
=> [INLONG-7026][Manager] Fixed the problem of not checked before creating the kafka topic

inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
- Title: [INLONG-7019][Sort] Rethrow the system error when flush data to doris
- Fixes #7019
Rethrow the system error when flush data to doris, otherwise, data will be lost and no longer be written.
Rethrow the system error for method 'flushSingleTable' of 'DorisDynamicSchemaOutputFormat'
*(example:)* …
=> [INLONG-7019][Sort] Rethrow the system error when flush data to doris

inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/DataProxyTopicInfo.java
=> [INLONG-7039][Manager] Unknown method isNoneBlank

inlong-dashboard/src/metas/consumes/common/ConsumeDefaultInfo.ts
=> [INLONG-7047][Dashboard] Specific meanings of data subscription list fields

inlong-dashboard/src/metas/groups/common/GroupDefaultInfo.ts
=> [INLONG-7045][Dashboard] Data stream group ID, character verification

inlong-dashboard/src/metas/streams/common/StreamDefaultInfo.ts
- Fixes #7000 
Add AVRO format for InlongStream.
=> [INLONG-7000][Dashboard] Add AVRO format for InlongStream

inlong-dashboard/src/metas/streams/common/StreamDefaultInfo.ts
- Fixes #6996 
Add JSON format for InlongStream.
=> [INLONG-6996][Dashboard] Add JSON format for InlongStream

inlong-common/src/main/java/org/apache/inlong/common/msg/AttributeConstants.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/SimpleMessageHandler.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/DefaultServiceDecoder.java
=> [INLONG-7054][DataProxy] Add the processing of the rtms field

inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
- [INLONG-6912][Sort] Add table level metric for Doris
- Fixes #6912 
*(example:)*
=> [INLONG-6912][Sort] Add table level metric for Doris

inlong-dashboard/src/locales/cn.json, inlong-dashboard/src/locales/en.json
- Fixes #7064
*(example:)*
- If a …
=> [INLONG-7064][Dashboard] Update the FilePathHelp value

inlong-dashboard/src/pages/ConsumeDashboard/config.tsx, inlong-dashboard/src/pages/ConsumeDashboard/index.tsx, inlong-dashboard/src/pages/GroupDashboard/config.tsx, inlong-dashboard/src/pages/GroupDashboard/index.tsx
=> [INLONG-6994][Dashboard] Add MQ type filter box for inlong group and consume list

inlong-dashboard/src/locales/cn.json, inlong-dashboard/src/locales/en.json, inlong-dashboard/src/metas/sinks/defaults/Elasticsearch.ts
=> [INLONG-7043][Dashboard] Add field prompt for ES sink

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hudi/HudiType.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/hudi/HudiCatalogClient.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/hudi/HudiTypeConverter.java
*[INLONG-7049][Manager] Support complex data types in Hudi Sink*
- Fixes #7049 
Adapt to hive data types in hudi sink
=> [INLONG-7049][Manager] Support complex data types in Hudi Sink

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java, inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/DebeziumSourceFunction.java, inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/MongoDBSource.java, inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/debezium/table/MongoDBConnectorDeserializationSchema.java, inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/debezium/utils/RecordUtils.java, inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/table/MongoDBTableSource.java
- [INLONG-6925][Sort] Add read phase metric and table level metric for MongoDB-CDC
- Fixes #6925 
*(example:)* …
=> [INLONG-6925][Sort] Add read phase metric and table level metric for MongoDB-CDC

inlong-dataproxy/conf/dataproxy.conf, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneProducer.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java
=> [INLONG-7070][Manager][DataProxy] Fix mq configuration dispatching problem

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SinkTableMetricData.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SinkTopicMetricData.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/util/MetricStateUtils.java, inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/DynamicKafkaSerializationSchema.java, inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaProducer.java
- [INLONG-7066][Sort] Kafka connector lost topic level dirty data metric and state restore for multi sink
- Fixes #7066 
* Kafka connector lost topic level dirty data metric and state restore for multi sink, So I support it.
* Add kafka sink init metric value when multi sink
* Add dirty metric supporting when multi sink
* modify some toString method
=> [INLONG-7066][Sort] Kafka connector lost topic level dirty data metric and state restore for multi sink

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamExtParam.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/greenplum/GreenplumSqlBuilder.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/oracle/OracleSqlBuilder.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/postgresql/PostgreSQLSqlBuilder.java
- Fixes #7080 
Use the `StringUtils.isNotBlank` uniformly instead of `StringUtils.isNoneBlank`.
Use the `StringUtils.isNotBlank` uniformly instead of `StringUtils.isNoneBlank`.
=> [INLONG-7080][Manager] Use the StringUtils.isNotBlank uniformly

inlong-dashboard/src/metas/consumes/common/ConsumeDefaultInfo.ts
- Fixes https://github.com/apache/inlong/issues/7063
=> [INLONG-7063][Dashboard] Optimize the topic name of the new consumption page

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/heartbeat/HeartbeatManager.java
=> [INLONG-7086][DataProxy] Add default ext tag report value

inlong-common/src/main/java/org/apache/inlong/common/msg/MsgType.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/base/SinkRspEvent.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/OrderBatchPackProfileV0.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/DefaultServiceDecoder.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleMessageHandler.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/MessageUtils.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/codec/EncodeObject.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java
- Title Example: [INLONG-7093][SDK] Add report time metric
- Fixes #7093 
- add report time metrics
- move MsgType to inlong-common
*(example:)* …
=> [INLONG-7093][SDK] Add report time metric

inlong-dashboard/src/locales/cn.json, inlong-dashboard/src/locales/en.json, inlong-dashboard/src/metas/groups/defaults/Pulsar.ts, inlong-dashboard/src/pages/GroupDetail/DataStream/StreamItemModal.tsx
- Fixes https://github.com/apache/inlong/issues/7096
=> [INLONG-7096][Dashboard] Selecting Pulsar MQ Optimization

inlong-common/src/main/java/org/apache/inlong/common/monitor/MonitorIndex.java
=> [INLONG-7098][Metrics] Add UUID in MonitorIndex

inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/utils/ServiceStatusHolder.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/offset/OffsetHistoryInfo.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/web/BrokerAdminServlet.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/fielddef/WebFieldDef.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/nodemanage/nodebroker/BrokerAbnHolder.java
=> [INLONG-7106][TubeMQ] Add reset offset API by time

.github/ISSUE_TEMPLATE/bug-report.yml
- Fixes #7109
add 1.5.0, and remove the no longer maintain versions.
=> [INLONG-7109][Release] Add the 1.5.0 version option for the bug report

CHANGES.md
- Fixes #7110
add the changelog for 1.5.0
=> [INLONG-7110][Release] Update changes log for the 1.5.0 version

inlong-distribution/src/main/assemblies/release.xml, inlong-manager/manager-web/sql/changes-1.05.sql, inlong-manager/manager-web/sql/changes-1.5.0.sql
- [INLONG-7104] Add database change script of 1.05 for InLongManager
- Fixes #7104 
*(example:)*
=> [INLONG-7104][Manager] Add database change script of 1.5.0 for InLongManager

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/mysql/MySQLResourceOperator.java
- Fixes #7130 
JDBC is null when the stream sink init.
Get information through data nodes, when JDBC URL is null.
=> [INLONG-7130][Manager] Fix null JDBC URL when mysql stream sink init

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/AbstractClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/PulsarClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/AbstractDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/es/ElasticsearchDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/hive/HiveDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/es/ElasticsearchApi.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/DataNodeController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java
- Fixes #7135 
Support the connection test of data nodes and clusters
Support the connection test of data nodes and clusters
=> [INLONG-7135][Manager] Support the connection test of data nodes and clusters

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/MongoExtractNode.java, inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/MongoExtractNodeTest.java, inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java
- Title Example: [INLONG-7121][Sort] Repair bug for MongoDb parse flink sql
- Fixes #7121 
*(example:)* …
=> [INLONG-7121][Sort] Fix the parsing error of Flink SQL for MongoDB

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtySinkHelper.java, inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingOutputFormat.java, inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/manager/StarRocksSinkManager.java, inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/StarRocksDynamicSinkFunction.java
- Fixes [[Improve][Sort] Support multiple dirty sink archive helper and fix some existing connectors #7126](https://github.com/apache/inlong/issues/7126)
follow up for dirty data archive feature and its relevant problems encountered during test phase
=> [INLONG-7126][Sort] Support multiple dirty sink archive helper

inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
- Fixes #7140 
- Fixes #7140 
catch exception in mysql snapshot split
=> [INLONG-7140][Sort] Sort mysql cdc connector mysql snapshot split exit catch exception

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/KafkaClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/TubeClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/ck/ClickHouseDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/iceberg/IcebergDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/mysql/MySQLDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/starrocks/StarRocksDataNodeOperator.java
- Fixes #7138
Support the connection test for kafka, tube, starrocks, mysql, clickhouse.
Support the connection test for kafka, tube, starrocks, mysql, clickhouse.
=> [INLONG-7138][Manager] Support the connection test for kafka, tube, starrocks, etc

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/LoadNodeUtils.java
- Fixes #7149 
Fix the problem of tableName parameter in ClickHouseLoadNode is incorrect.
Replace tableName in ClickHouseLoadNode with databaseName.tableName.
=> [INLONG-7149][Manager] Replace tableName in ClickHouseLoadNode with databaseName.tableName

inlong-dashboard/src/metas/consumes/common/status.tsx
- Fixes https://github.com/apache/inlong/issues/7153
=> [INLONG-7153][Dashboard] The data subscription status code shows the specific meaning

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/FileReaderOperator.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/TestFileAgent.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestTextFileReader.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/TestTextFileTask.java, inlong-agent/agent-plugins/src/test/resources/test/3.txt
- [INLONG-7156][Agent] Support directly sending raw file data
- Fixes #7156 
*(example:)*
- If a feature …
=> [INLONG-7156][Agent] Support directly sending raw file data

inlong-dashboard/src/components/NodeSelect/index.tsx, inlong-dashboard/src/metas/consumes/defaults/Kafka.ts, inlong-dashboard/src/metas/groups/defaults/Kafka.ts, inlong-dashboard/src/pages/GroupDetail/Audit/config.tsx
- Fixes https://github.com/apache/inlong/issues/7162
=> [INLONG-7162][Dashboard] Kafka MQ type details optimization

inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/debezium/reader/BinlogSplitReader.java
- Fixes #7161 
- This a supplement for pr https://github.com/apache/inlong/pull/7164
=> [INLONG-7161][Sort] Fix bug that Mysql connector only output the latest record in snapshot stage for table without primary key (Supplement) 

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/validation/UpdateByIdValidation.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/validation/UpdateByKeyValidation.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/DataNodePageRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/DataNodeRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/ck/ClickHouseDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/es/ElasticsearchDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/hive/HiveDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/hudi/HudiDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/iceberg/IcebergDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/mysql/MySQLDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/starrocks/StarRocksDataNodeDTO.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/AbstractDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeOperatorFactory.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/ck/ClickHouseDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/es/ElasticsearchDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/hive/HiveDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/hudi/HudiDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/iceberg/IcebergDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/mysql/MySQLDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/starrocks/StarRocksDataNodeOperator.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/DataNodeController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenDataNodeController.java, inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/controller/DataNodeControllerTest.java
=> [INLONG-7169][Manager] Optimize OpenDataNodeController implementation

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ErrorCodeEnum.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupStatus.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/kafka/InlongKafkaDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/pulsar/InlongPulsarDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/tubemq/InlongTubeMQDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/autopush/AutoPushSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/hudi/HudiSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/mongodb/MongoDBSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/mqtt/MqttSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/mysql/MySQLBinlogSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/oracle/OracleSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/postgresql/PostgreSQLSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/redis/RedisSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/sqlserver/SQLServerSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/tubemq/TubeMQSourceDTO.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/AbstractGroupOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupOperator4Kafka.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupOperator4NoneMQ.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupOperator4Pulsar.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupOperator4TubeMQ.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupOperatorFactory.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInLongGroupController.java
=> [INLONG-7178][Manager] Optimize parameter checks for InlongGroup, and simplify the exception and log info

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerServiceServer.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/aaaserver/CertificateBrokerHandler.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/aaaserver/CertificateMasterHandler.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/aaaserver/CertifiedInfo.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/aaaserver/SimpleCertificateBrokerHandler.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/aaaserver/SimpleCertificateMasterHandler.java, inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/master/TMaster.java
=> [INLONG-7184][TubeMQ] Replace CertifiedResult with ProcessResult

NOTICE, licenses/NOTICE, licenses/inlong-agent/NOTICE, licenses/inlong-audit/NOTICE, licenses/inlong-dashboard/NOTICE, licenses/inlong-dataproxy/NOTICE, licenses/inlong-manager/NOTICE, licenses/inlong-sort-connectors/NOTICE, licenses/inlong-sort-standalone/NOTICE, licenses/inlong-sort/NOTICE, licenses/inlong-tubemq-manager/NOTICE, licenses/inlong-tubemq-server/NOTICE
=> [INLONG-7188][Doc] Change the project Copyright to 2019-2023

inlong-dashboard/src/metas/consumes/common/ConsumeDefaultInfo.ts, inlong-dashboard/src/pages/ConsumeDetail/Info/config.tsx, inlong-dashboard/src/pages/ConsumeDetail/Info/index.tsx
- Fixes https://github.com/apache/inlong/issues/7190
=> [INLONG-7190][Dashboard] New data subscription optimization

inlong-sort/sort-connectors/elasticsearch-6/pom.xml, inlong-sort/sort-connectors/elasticsearch-7/pom.xml, inlong-sort/sort-connectors/hbase/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, inlong-sort/sort-connectors/mysql-cdc/pom.xml, inlong-sort/sort-connectors/oracle-cdc/pom.xml, inlong-sort/sort-connectors/postgres-cdc/pom.xml, inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/HbaseLoadFlinkSqlParseTest.java, sting
- Fixes #7202 
Fix Unit Tests ( including PostgreSql \ Hbase \ Elasticsearch ) in sort-core
Relocate classes that has conflict 
mvn clean package -Dmaven.javadoc.skip=true
=> [INLONG-7202][Sort] Fix unit tests ( including PostgreSql \ Hbase \ Elasticsearch ) in sort-core

inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/InlongStreamServiceTest.java
- Fixes #7206 
Fix the problem of the selectBriefList method in the InlongGroupEntity.xml file is incorrect
Fix the problem of the selectBriefList method in the InlongGroupEntity.xml file is incorrect
=> [INLONG-7206][Manager] Fix the problem of the selectBriefList method in the InlongGroupEntity.xml file is incorrect

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ck/ClickHouseSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/es/ElasticsearchFieldInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/starrocks/StarRocksColumnInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/AbstractClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/AgentClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeOperateHelper.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/ck/ClickHouseSinkOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInLongStreamController.java
=> [INLONG-7204][Manager] Optimize OpenInLongStreamController implementation

inlong-dashboard/src/locales/cn.json, inlong-dashboard/src/locales/en.json, inlong-dashboard/src/metas/sources/defaults/PostgreSQL.ts
- Fixes https://github.com/apache/inlong/issues/7215
=> [INLONG-7215][Dashboard] PostgreSQL source parameter optimization

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/SourceRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/autopush/AutoPushSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/binlog/BinlogSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/file/FileSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/hudi/HudiSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/mongodb/MongoDBSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/mqtt/MqttSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/oracle/OracleSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/postgresql/PostgreSQLSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/pulsar/PulsarSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/redis/RedisSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/sqlserver/SQLServerSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/tubemq/TubeMQSourceOperator.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSourceController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenStreamSourceController.java
=> [INLONG-7226][Manager] Optimize OpenStreamSourceController implementation

inlong-audit/audit-store/pom.xml, pom.xml
- Fixes #7234
Avoid other modules affecting log4j of audit-store
Add log4j dependency to audit-store alone.
=> [INLONG-7234][Audit] Add log4j for audit-store

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/util/Preconditions.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupProcessService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenDataNodeController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInLongGroupController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInLongStreamController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenStreamSinkController.java, inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/controller/DataNodeControllerTest.java
=> [INLONG-7229][Manager] Add checks for unmodifiable field values

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/validation/SaveValidation.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/DeleteTransformRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/TransformRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/StreamTransformServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenStreamSourceController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenStreamTransformController.java
=> [INLONG-7261][Manager] Optimize OpenStreamTransformController implementation

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/plugin/PluginService.java
- [INLONG-7275][Manager] Support modify the plugin's location
- Fixes #7275 
*(example:)*
=> [INLONG-7275][Manager] Add the default location for plugin

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterTagEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterTagEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/BindTagRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterNodeRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterTagRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/agent/AgentClusterDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/es/ElasticsearchClusterDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/kafka/KafkaClusterDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/pulsar/PulsarClusterDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/tubemq/TubeClusterDTO.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/AbstractClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/AgentClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/DataProxyClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/ElasticsearchClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterOperatorFactory.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/KafkaClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/PulsarClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/TubeClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/AbstractClusterNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/AgentClusterNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/DefaultClusterNodeOperator.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/common/utils/ValidationUtilsTest.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceTest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInLongClusterController.java
- Fixes #7278
Modifications:
1. Adjust the exception throwing content and increase the error code;
2. Adjust the log printing level, from info to debug
3. Adjust the check of whether the field is empty when the ClusterTagRequest, ClusterRequest, and ClusterNodeRequest objects are modified;
4. Fix the bug when inspecting the code
=> [INLONG-7278][Manager] Optimize OpenInLongClusterController implementation

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
Add missing code modifications
- Fixes #7280
=> [INLONG-7280][Manager] rename checkXXX to expectXXX in Preconditions (addendum)

inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/DeleteSortListener.java, inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/DeleteStreamListener.java, inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/RestartSortListener.java, inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/RestartStreamListener.java, inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/SuspendSortListener.java, inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/listener/SuspendStreamListener.java
- Fixes #7294 
Fix the problem of suspend, restart, delete sort task failed.
If `sort.properties` is empty, get sortUrl from the configuration file `flink-sort-plugin.properties`.
=> [INLONG-7294][Manager] Fix the problem of suspend, restart, delete sort task failed

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/KuduLoadNode.java
- [INLONG-7268][Sort] Support Apache Kudu LoadNode
- Fixes #7268 
*(example:)*
=> [INLONG-7268][Sort] Support load node of Apache Kudu

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/LoadNode.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/RedisLoadNode.java, inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/RedisNodeSqlParserTest.java
- [INLONG-7240][Sort] Support load node of Redis
- Fixes #7240 
*(example:)*
=> [INLONG-7240][Sort] Support load node of Redis

inlong-dashboard/src/metas/nodes/defaults/Hive.ts
- Fixes https://github.com/apache/inlong/issues/7297
=> [INLONG-7297][Dashboard] Hive node parameter optimization

docker/build-docker-images.sh, docker/publish-by-arch.sh, inlong-tubemq/tubemq-docker/tubemq-all/Dockerfile
- Fixes #6560
Update the base image for zookeeper to 3.5, and update the workflow script.
=> [INLONG-6560][Docker] Add arm64 image for inlong/tubemq

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupProcessService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/StreamTransformServiceImpl.java
Replace getRoles() with getAccountType() in Open APIs
- Fixes #7300
=> [INLONG-7300][Manager] Replace getRoles() with getAccountType()

README.md
- [INLONG-7266][Document] Add user docs for Kudu LoadNote
- Fixes #7266 
*(example:)*
=> [INLONG-7266][Document] Add user docs for Kudu LoadNote

README.md
- [INLONG-7244][Document] Add user docs for redis LoadNote
- Fixes #7244 
*(example:)*
=> [INLONG-7244][Document] Add user docs for Redis LoadNote

inlong-dashboard/src/metas/sinks/defaults/Redis.ts
- [INLONG-7305][Dashboard] Use properties to save extended parameters in RedisLoadNode
- Fixes #7305 
*(example:)* …
=> [INLONG-7305][Dashboard] Use properties to save extended parameters in RedisLoadNode

inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/sink/AbstractRedisSinkFunction.java, inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/sink/RedisBitmapSinkFunction.java, inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/sink/RedisDynamicTableSink.java, inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/sink/RedisHashSinkFunction.java, inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/sink/RedisPlainSinkFunction.java, inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/sink/RedisSinkFunction.java, inlong-sort/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/table/RedisDynamicTableFactory.java
- [INLONG-7245][Sort] Support metric and audit in sort-connect-redis
- Fixes #7245 
*(example:)*
=> [INLONG-7245][Sort] Support metric and audit in sort-connect-redis

inlong-dashboard/scripts/sync.js, inlong-dashboard/scripts/utils.js, inlong-dashboard/src/components/Layout/index.tsx, inlong-dashboard/src/configs/locales/index.ts, inlong-dashboard/src/configs/menus/index.ts, inlong-dashboard/src/metas/DataWithBackend.ts, inlong-dashboard/src/models/index.ts, inlong-dashboard/src/router.tsx, inlong-dashboard/src/utils/index.ts
=> [INLONG-7313][Dashboard] Automatically generate a unique ID and depth key for the menu

inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/controller/AnnoControllerTest.java
- Fixes #7310 
Fix the problem of too manager AuthenticationException for Manager UT.
Comment part of the test methods with disable.
These test methods throw a lot of error logs, so they are saved in local test.
=> [INLONG-7310][Manager] Comment part of the test methods with disable

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/PulsarClusterOperator.java
- Fixes #7256 
Add a check for serverUrl
Add a check for serverUrl
=> [INLONG-7256][Manager] Add a check for Pulsar service URL

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/AuditController.java
- Fixes #7317 
Fix the problem of manager threw database not found in unit tests
Add `@Lazy`.
=> [INLONG-7317][Manager] Fix the problem of manager threw database not found in unit tests

docker/build-docker-images.sh, docker/publish-by-arch.sh
[INLONG-7323][Improve][Docker] Add manifest for tubemq-all and tubemq-manager
- Fixes #7323 
Add manifest for tubemq-all and tubemq-manager
Add manifest for tubemq-all and tubemq-manager
Add manifest for tubemq-all and tubemq-manager
=> [INLONG-7323][Docker] Add manifest for tubemq-all and tubemq-manager

inlong-manager/manager-web/sql/apache_inlong_manager.sql
- Fixes #7328
Fix bug that error in querying audit info
Add sql data 
=> [INLONG-7328][Manager] Error in querying audit info

inlong-sort/sort-connectors/hbase/pom.xml
- [INLONG-7335][Sort] Fix Hbase connector lost spi file when shade
- Fixes #7335 
* Fix Hbase connector lost spi file when shade
* Modify pom of hbase connector
=> [INLONG-7335][Sort] Fix Hbase connector lost spi file when shade

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/hive/HiveDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/hive/HiveDataNodeInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/hive/HiveDataNodeRequest.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sort/SortServiceImplTest.java
- Fixes #7355 
Fix the problem of HiveDataNode cannot save the datapath.
Change `hdfsPath` to `dataPath`
=> [INLONG-7355][Manager] Fix the problem of HiveDataNode cannot save the datapath

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/TransformType.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/ExtractNodeUtils.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldRelationUtils.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FilterFunctionUtils.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/NodeRelationUtils.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/StreamParseUtils.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/redis/RedisLookupOptions.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/redis/RedisSource.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/redis/RedisSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/redis/RedisSourceRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/joiner/IntervalJoinerDefinition.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/joiner/LookUpJoinerDefinition.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/joiner/TemporalJoinerDefinition.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/source/RedisSourceServiceTest.java
Prepare a Pull Request
Fixes  #7334 
Motivation
Support stream join dimension table
=> [INLONG-7334][Manager] Support stream join dimension table

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/RedisExtractNode.java
- Fixes #7346 
Add metadata support for redis dimension table join
=> [INLONG-7346][Sort] Add metadata support for join of Redis dimension table

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtils.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/FieldInfo.java, inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java, inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/MongoExtractFlinkSqlParseTest.java
- Fixes #7331 
Support complex type field
Support sub filed of complex type filed (eg: filedInfo.subFiled)
=> [INLONG-7331][Sort][Manager] Support complex type field

inlong-dashboard/craco.config.ts, inlong-dashboard/src/App.tsx, inlong-dashboard/vite.config.ts
=> [INLONG-7360][Dashboard] env.local variable can not work

inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/FlinkSink.java
[INLONG-7363][Sort] Fix iceberg connector null pointer error
- Fixes #7363 
Fix iceberg connector null pointer error.
Get `overwrite` from `builder`.
=> [INLONG-7363][Sort] Fix iceberg connector null pointer error

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/PulsarClusterOperator.java
- Fixes #7337 
Fix test pulsar connection error
org.apache.inlong.manager.service.cluster.InlongClusterServiceImpl#testConnection
=> [INLONG-7337][Manager] Fix test Pulsar connection error

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/MongoJob.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/MongoDBSource.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/MongoDBReader.java
- Fixes https://github.com/apache/inlong/issues/7365
=> [INLONG-7365][Agent] The username for the MongoDB connector is missing

inlong-dashboard/src/App.tsx, inlong-dashboard/src/configs/default/conf.ts, inlong-dashboard/src/utils/request.ts
=> [INLONG-7367][Dashboard] Enabled more global config

inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/source/SimpleTcpSource.java
- Fixes #6919 
Fix bug that no exceptions are printed in the log
Log add exception info
=> [INLONG-6919][Audit] Fix bug that no exceptions are printed in the log

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/SinkRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/SourceRequest.java
- Fixes #7375 
*(example:)*
- If a …
=> [INLONG-7375][Manager] Change the pattern limitation of InlongCluster name

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/SinkRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/SourceRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/DeleteTransformRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/TransformRequest.java
- Fixes #7373 
*(example:)*
- If a …
=> [INLONG-7373][Manager] Change the length limitation of InlongStreamId

inlong-sort/sort-connectors/filesystem/pom.xml, inlong-sort/sort-connectors/hbase/pom.xml, inlong-sort/sort-connectors/hudi/pom.xml, inlong-sort/sort-connectors/iceberg/pom.xml, inlong-sort/sort-connectors/kafka/pom.xml, inlong-sort/sort-connectors/mongodb-cdc/pom.xml, inlong-sort/sort-connectors/mysql-cdc/pom.xml, inlong-sort/sort-connectors/oracle-cdc/pom.xml, inlong-sort/sort-connectors/postgres-cdc/pom.xml, inlong-sort/sort-connectors/pulsar/pom.xml, inlong-sort/sort-connectors/sqlserver-cdc/pom.xml, inlong-sort/sort-dist/pom.xml
- Fixes #7377 
- Fixes #7377 
add protobuf in pulsar connector and remove protobuf in sort-dist
run a stream from file to clickhouse
=> [INLONG-7377][Sort] Fix sort-dist protobuf conflicts with protobuf in sort-connectors

inlong-dashboard/src/locales/cn.json, inlong-dashboard/src/locales/en.json, inlong-dashboard/src/metas/nodes/defaults/MySQL.ts, inlong-dashboard/src/metas/sinks/defaults/MySQL.ts
- Fixes https://github.com/apache/inlong/issues/7382
=> [INLONG-7382][Dashboard] Add a database name for MySQL sink

inlong-dashboard/package-lock.json, inlong-dashboard/src/App.tsx
=> [INLONG-7384][Dashboard] Login page error

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
- Fixes #7395 
There are lots of requests with expire or error params to SortSouceService and SortClusterService, which results in massive error requst log and contaminate other logs
=> [INLONG-7395][Manager] Reduce log in SortSouceService and SortClusterService

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java
- Fixes #7401 
Fix the problem of partitions could not be created based on numPartitions in the inlong group
Fix the problem of partitions could not be created based on numPartitions in the inlong group
=> [INLONG-7401][Manager] Fix that cannot create Pulsar partitions based on numPartitions param

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterNodeEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterNodeEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/SourcePageRequest.java
- Fixes #7406 
Support  to get streamSource by dataNodeName and inlongClusterName.
Support  to get streamSource by dataNodeName and inlongClusterName.
=> [INLONG-7406][Manager] Add the query criteria for streamSource

inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlReadableMetadata.java
- Fixes #7397 
- Fixes #7397 
For UPDATE_BEFORE output DELETE 
For UPDATE_AFTER output INSERT
Run AllmigrateTest
=> [INLONG-7397][Sort] Fix MySql connector output two data with the same UPDATE operation

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/mysql/MySQLDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTO.java
- Fixes #7421 
Add a check to the URL encoding of mysql JDBC URL in MySQLDataNode.
Add a check to the URL encoding of mysql JDBC URL in MySQLDataNode.
=> [INLONG-7421][Manager] Add encoding check to the MySQL JDBC URL in MySQLDataNode

inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/FlinkPulsarSource.java, inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java, inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarDynamicTableSource.java, licenses/inlong-sort-connectors/LICENSE
- Fixes #7423 
- Fixes #7423 
Support audit metrics in Pulsar connector 
Run a file job in inlong dashboard and check the audit section
=> [INLONG-7423][Sort] Pulsar connector with adminUrl support audit metrics

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTO.java
[INLONG-7426][Manager] Improve the accuracy of variable naming for MySQLSinkDTO.
- Fixes #7426
Improve the accuracy of variable naming for MySQLSinkDTO, I don't think the variable name of 'dateMatcher' fits the current scenario. so i change it to 'dataMatcher'
=> [INLONG-7426][Manager] Improve the accuracy of variable naming for MySQLSinkDTO

inlong-tubemq/tubemq-docker/tubemq-all/Dockerfile
- Fixes #7430
https://issues.apache.org/jira/browse/ZOOKEEPER-2464
Update the base image to fix the NPE for TubeMQ
=> [INLONG-7430][Docker] Update the base image to fix the NPE for TubeMQ

inlong-manager/manager-dao/src/main/resources/mappers/DataNodeEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterNodeEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupProcessService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java, inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/controller/DataNodeControllerTest.java
- Fixes #7429 
Fix the information returned when deleting a non-existent StreamSource、InlongCluster、DataNode is incorrect.
Fix the information returned when deleting a non-existent StreamSource、InlongCluster、DataNode is incorrect.
=> [INLONG-7429][Manager] Fix the information returned when deleting a non-existent object

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/ServiceBaseTest.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/stream/InlongStreamTest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSinkController.java
- Fixes #7415 
Support to creating schema of StreamSource and StreamSink by JSON
Support to creating schema of StreamSource and StreamSink by JSON
=> [INLONG-7004][Manager] Support to creating schema of StreamSource by JSON

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/JobProfileDto.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/MqttJob.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/MqttSource.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/MqttReader.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestMqttSource.java
- Fixes https://github.com/apache/inlong/issues/7419
=> [INLONG-7419][Agent] Fix error of MQTT connector

inlong-dashboard/src/configs/menus/index.ts, inlong-dashboard/src/pages/GroupDetail/Audit/config.tsx, inlong-dashboard/src/pages/GroupDetail/DataStorage/DetailModal.tsx
=> [INLONG-7438][Dashboard] Support more Sort index display instead of directly displaying ID

inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/SinkPageRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/SourcePageRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamPageRequest.java
- Fixes #7444 
Supports query InlongStream、StreamSource、StreamSink by status list.
Supports query InlongStream、StreamSource、StreamSink by status list.
=> [INLONG-7444][Manager] Support query inlong objects by status list

inlong-manager/manager-dao/src/main/resources/mappers/DataNodeEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterPageRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/DataNodePageRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/DataNodeServiceTest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/DataNodeController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java
- Fixes #7460 
Add user authentication when operate DataNode.
Add user authentication when operate DataNode.
=> [INLONG-7460][Manager] Add user authentication when operate DataNode

inlong-sort/sort-connectors/elasticsearch-6/pom.xml, inlong-sort/sort-connectors/elasticsearch-7/pom.xml
- [INLONG-7464][Sort] Fix  Elasticsearch connector lost dependency
- Fixes #7464 
* Fix  Elasticsearch connector lost dependency
* es pom file include joda-time
=> [INLONG-7464][Sort] Fix  Elasticsearch connector lost dependency

inlong-sort/sort-connectors/hbase/pom.xml, inlong-sort/sort-connectors/kafka/pom.xml
- [INLONG-7449][Sort] Fix Kafka connector dependency lost
- Fixes #7449
* Fix Kafka connector dependency lost
* kafka pom file add dependency
* Hbase pom file remove duplication shade
=> [INLONG-7449][Sort] Fix Kafka connector dependency lost

inlong-sort/sort-connectors/filesystem/pom.xml
- T[INLONG-7451][Sort] Fix FileSystem connector dependency lost
- Fixes #7451 
* Fix FileSystem connector dependency lost
* filesystem connector pom file add dependency
=> [INLONG-7451][Sort] Fix FileSystem connector dependency lost

docker/build-docker-images.sh, inlong-manager/manager-docker/Dockerfile, inlong-manager/manager-docker/pom.xml
- Fixes #7475
Add Kafka connector to the manager image for testing, it will be convenient to use Kafka.
=> [INLONG-7475][Docker] Add Kafka connector to the manager image for test

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongStreamClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/StreamSinkClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongStreamApi.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/StreamSinkApi.java, inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java
- Fixes #7496 
Add parseFields method for manager-client.
Add parseFields method for manager-client.
=> [INLONG-7496][Manager] Add parseFields method for manager-client

inlong-dataproxy/pom.xml, pom.xml
=> [INLONG-7480][CVE] Add a specified tomcat-embed-core dependency for fixing the CVE problem

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
- Fixes #7473 
Fix StreamSource in the TO_BE_ISSUED_DELETE state cannot be issued properly.
Fix StreamSource in the TO_BE_ISSUED_DELETE state cannot be issued properly.
=> [INLONG-7473][Manager] Fix StreamSource in the TO_BE_ISSUED_DELETE state cannot be issued properly

inlong-dashboard/src/pages/GroupDetail/Audit/config.tsx, inlong-dashboard/src/pages/GroupDetail/DataSources/index.tsx, inlong-dashboard/src/pages/GroupDetail/DataStorage/index.tsx
- Fixes https://github.com/apache/inlong/issues/7493
=> [INLONG-7493][Dashboard] Not use upper case for source, sink, and audit labels

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/DataNode.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/DataNodeImpl.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/DataNodeClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/StreamSinkClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/StreamSourceClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/DataNodeApi.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/StreamSinkApi.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/StreamSourceApi.java, inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSinkController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSourceController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenStreamSinkController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenStreamSourceController.java
- Fixes #7490 
Support paging query InLong objects info based on conditions in manager-client.
Support paging query InLong objects info based on conditions in manager-client
=> [INLONG-7490][Manager] Support paging query InLong objects info based on conditions in manager-client

inlong-dashboard/src/pages/GroupDetail/DataSources/index.tsx, inlong-dashboard/src/pages/GroupDetail/DataStorage/index.tsx
- Fixes https://github.com/apache/inlong/issues/7506
=> [INLONG-7506][Dashboard] Change query method of source and sink from get to post

inlong-dashboard/src/pages/GroupDetail/Audit/index.tsx
=> [INLONG-7521][Dashboard] Arrange according to the size of Auditid

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/ck/ClickHouseDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ck/ClickHouseColumnInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ck/ClickHouseFieldInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ck/ClickHouseSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ck/ClickHouseSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ck/ClickHouseSinkRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ck/ClickHouseTableInfo.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/ck/ClickHouseDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/ck/ClickHouseJdbcUtils.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/ck/ClickHouseResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/ck/ClickHouseSqlBuilder.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/ck/ClickHouseSinkOperator.java
- Fixes #7525 
1.Support to save additional info for the ClickHouse field.
2.Support to set the ttl of the table.
1.Support to save additional info for the ClickHouse field.
2.Support to set the ttl of the table.
=> [INLONG-7525][Manager] Support to save additional info for the ClickHouse field

inlong-dashboard/src/metas/nodes/defaults/ClickHouse.ts, inlong-dashboard/src/metas/sinks/defaults/ClickHouse.ts
- Fixes https://github.com/apache/inlong/issues/7531
=> [INLONG-7531][Dashboard] Clickhouse source supports filling life cycle

inlong-dashboard/src/locales/cn.json, inlong-dashboard/src/locales/en.json, inlong-dashboard/src/metas/sources/defaults/File.ts
- Fixes https://github.com/apache/inlong/issues/7542
=> [INLONG-7542][Dashboard] File source supports selecting clusters

inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/manager/StarRocksSinkManager.java, inlong-sort/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/StarRocksDynamicSinkFunction.java
- Fixes #7539
1. Source cdc connectors like mysql and postgres, pack operation type (INSERT、DELETE and UPDATE) into GenericRowData. StarRocks connector is using the RowKind of GenericRowData. This row kind is always INSERT.
StarRocks connector should parse this type from RowData with canal-json or debezium-json format.
2. When `schema-update.policy` is `LOG_WITH_IGNORE`, but `dirty.ignore` is false,  we should not invoke dirty helper to archive …
=> [INLONG-7539][Sort] StarRocks connector parses row kind from GenericRowData

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java, inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNodeTest.java
- Fixes #7389 
Add audit id info for source.
Add audit id info for source.
=> [INLONG-7389][Manager][Sort] Add audit id info for source

inlong-dashboard/src/locales/cn.json, inlong-dashboard/src/locales/en.json, inlong-dashboard/src/metas/sinks/defaults/Kudu.ts
=> [INLONG-7563][Dashboard] Support specific partitions in the kudu sink

docker/docker-compose/docker-compose.yml, docker/kubernetes/templates/audit-statefulset.yaml, docker/kubernetes/values.yaml, inlong-audit/audit-docker/Dockerfile, inlong-audit/audit-docker/audit-docker.sh, inlong-dataproxy/dataproxy-docker/Dockerfile
- Fixes #7572
Add the Kafka support for audit docker deployment
=> [INLONG-7572][Docker] Add the Kafka support for audit docker deployment

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/FileReaderOperator.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/MonitorTextFile.java, inlong-agent/conf/log4j2.xml
- [INLONG-7533][Agent] Change agent log-level to INFO
- Fixes #7533
*Reduce the amount of log debug log*
=> [INLONG-7533][Agent] Fix that log cannot be collected for position reset

inlong-manager/manager-web/sql/changes-1.6.0.sql
- Fixes #7575 
Add audit_base table change script of 1.6.0 for Manager
Add audit_base table change script of 1.6.0 for Manager
=> [INLONG-7575][Manager] Add audit_base table change script of 1.6.0 for Manager

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/AuditBaseEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/AuditBaseEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
- Fixes #7586 
Fix the audit information in the database cannot be obtained after being updated.
Fix the audit information in the database cannot be obtained after being updated.
=> [INLONG-7586][Manager] Fix the audit information in the database cannot be obtained after being updated

inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.6.0.sql
=> [INLONG-7565][Manager] Add audit id for Apache Kudu

.github/ISSUE_TEMPLATE/bug-report.yml
- Fixes #7597
Add the 1.6.0 version option for the bug report
Add the 1.6.0 version option for the bug report
=> [INLONG-7597][Release] Add the 1.6.0 version option for the bug report

docker/docker-compose/docker-compose.yml
- Fixes #7607
Add privilege requirement for audit container
=> [INLONG-7607][Docker] Add privilege requirement for audit container

inlong-dashboard/src/locales/cn.json, inlong-dashboard/src/locales/en.json, inlong-dashboard/src/pages/GroupDetail/index.tsx
- Fixes https://github.com/apache/inlong/issues/7560
=> [INLONG-7560][Dashboard] When submitting group approval, determine whether to create source and sink

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/queue/QueueResourceListener.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/sink/SinkResourceListener.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/sort/SortConfigListener.java
- Fixes #7593 
Fix unable to delete group.
Fix unable to delete group.
=> [INLONG-7593][Manager] Change the InlongGroup status when executing Sort and Queue listeners

inlong-dashboard/src/metas/nodes/defaults/ClickHouse.ts, inlong-dashboard/src/metas/sources/defaults/File.ts
- Fixes https://github.com/apache/inlong/issues/7611
=> [INLONG-7611][Dashboard] File source select cluster add limit

inlong-sort/sort-connectors/base/pom.xml, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/MetricsCollector.java, inlong-sort/sort-connectors/kafka/pom.xml, inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaConsumer.java, inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/FlinkKafkaConsumerBase.java, inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/DynamicKafkaDeserializationSchema.java, inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicSource.java, inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicTableFactory.java, inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/UpsertKafkaDynamicTableFactory.java, inlong-sort/sort-connectors/pulsar/pom.xml, inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/DynamicPulsarDeserializationSchema.java
- Fixes #7609 
[INLONG-7609][Sort][Feature] Add audit for kafka source connector
[INLONG-7609][Sort][Feature] Add audit for kafka source connector
=> [INLONG-7609][Sort] Add audit for Kafka source connector

inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java, inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicTableFactory.java, inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicTableSink.java, inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisStreamLoad.java
- Fixes #7584
1、When migrating all tables in database, doris server prefers CSV format than JSON format for lower CPU loads.
2、Dirty data could be archived to storage like S3. It is useful when data accounting and auditing.
1、`serialize` method in `DorisDynamicSchemaOutputFormat` class can serialize CSV or JSON data by `DorisDynamicTableFactory` option.
2、`physicalData`,  which is a Map,  carries …
=> [INLONG-7584][Sort] Doris connector supports writing CSV and archiving dirty data

CHANGES.md
- Fixes #7598
Update changes log for the 1.6.0 version
=> [INLONG-7598][Release] Update changes log for the 1.6.0 version

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/StreamSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hive/HiveSink.java
- Fixes #7625 
*(example:)*
- If a …
=> [INLONG-7625][Manager] Make data encoding type as a common property of StreamSink

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupStatus.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/AbstractDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/mysql/MySQLDataNodeOperator.java
- Fixes #7619 
Support retry mysqlSources after updating MysqlDataNode.
Support retry mysqlSources after updating MysqlDataNode.
=> [INLONG-7619][Manager] Support update and retry MySQL sources after updating MySQLDataNode

inlong-dashboard/src/App.tsx
Modify the relative position of Suspense and lazy.
- Fixes #7630
=> [INLONG-7630][Dashboard] The page flickers when the route is changed

docker/docker-compose/docker-compose.yml, docker/kubernetes/templates/audit-statefulset.yaml, inlong-audit/audit-docker/Dockerfile, inlong-audit/audit-docker/audit-docker.sh
- Fixes #7636 
Modify the Kafka config for Audit docker deployment without MQ config.
Modify the Kafka config for Audit docker deployment
=> [INLONG-7636][Docker] Modify the Kafka config for Audit docker deployment

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
- Fixes #7632 
Mask the audit information that Sort sent successfully.
Mask the audit information that Sort sent successfully.
=> [INLONG-7632][Manager] Mask the audit information that Sort sent successfully

bin/init-config.sh, conf/inlong.conf
- Fixes #7641 
Modify script for Audit standalone deployment.
Remove the config of MQ server URL.
=> [INLONG-7641][Script] Modify script for Audit standalone deployment

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/kudu/KuduSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/kudu/KuduSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/kudu/KuduSinkRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/kudu/KuduTableInfo.java, inlong-manager/manager-service/pom.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/kudu/KuduResourceClient.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/kudu/KuduResourceOperator.java, pom.xml
- [INLONG-7273][Manager] Support creating table in Kudu cluster
- Fixes #7273
=> [INLONG-7273][Manager] Support creating table in Kudu cluster

inlong-manager/manager-web/bin/shutdown.sh
- Fixes #7511
Make manager more graceful to stop script shutdown
The details can be found at https://github.com/apache/inlong/issues/7511.
=> [INLONG-7511][Manager] Update the stop script to make sure the process stops completely

inlong-dashboard/src/locales/cn.json, inlong-dashboard/src/locales/en.json, inlong-dashboard/src/metas/sinks/defaults/Kudu.ts
=> [INLONG-7643][Dashboard] Support specifying buckets when creating kudu resource

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SourceStatus.java
- Fixes #7651 
Fix streamSource in normal state cannot be modified.
Fix streamSource in normal state cannot be modified.
=> [INLONG-7651][Manager] Fix streamSource in normal state cannot be modified

inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamPageRequest.java
- Fixes #7648 
Support list streams by a specific group principal
Extense the condition dimension of stream list interface
*(example:)* …
=> [INLONG-7648][Manager] Support list streams by a specific group principal

inlong-manager/manager-service/pom.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/hudi/HudiCatalogClient.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/hudi/HudiFileFormat.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/hudi/HudiUtils.java
=> [INLONG-7655][Manager] Remove the dependency of hudi-flink1.13-bundle

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSourceController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenStreamSourceController.java
- Fixes #7666 
Support to freezing and restarting streamSource.
Support to freezing and restarting streamSource.
=> [INLONG-7666][Manager] Support to freezing and restarting streamSource

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java
- Fixes #7675 
Check OrderType when calling listAll to prevent sql injection.
Check OrderType when calling listAll to prevent sql injection.
=> [INLONG-7675][Manager] Check OrderType when calling listAll to prevent sql injection

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/DataNodeType.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/kudu/KuduDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/kudu/KuduDataNodeInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/kudu/KuduDataNodeRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/kudu/KuduDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/kudu/KuduSinkOperator.java
*[INLONG-7686][Manager] Support kudu node management*
- Fixes #7686
=> [INLONG-7686][Manager] Support kudu node management

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
- Fixes #7670 
Filter out invalid sinks when make configuraton of sort source
SortSourceServiceImpl
*(example:)*
=> [INLONG-7670][Manager] Filter out sinks with empty cluster

inlong-tubemq/tubemq-docker/tubemq-build/Dockerfile
- Fixes #7698
Update the gcc version to fix the faild build
=> [INLONG-7698][Docker] Update the gcc version to fix the faild build

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SimpleSourceStatus.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SourceStatus.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/group/UpdateGroupCompleteListener.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/source/AbstractSourceOperateListener.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/autopush/AutoPushSourceOperator.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/source/listener/StreamSourceListenerTest.java
- Fixes #7678 
Rename `FROZEN` to `STOP` for source status.
Rename `FROZEN` to `STOP` for source status.
=> [INLONG-7678][Manager] Rename FROZEN to STOP for source status

inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/MySqlSource.java, inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/MySqlSourceBuilder.java, inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/config/MySqlSourceConfig.java, inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/config/MySqlSourceConfigFactory.java, inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/config/MySqlSourceOptions.java, inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlRecordEmitter.java, inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/utils/RecordUtils.java, inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlReadableMetadata.java, inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlTableInlongSourceFactory.java, inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlTableSource.java, inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/AllMigrateTest.java, inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJson.java, inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/debezium/DebeziumJson.java
- Fixes #7662
Add a flag to determine whether the data is incremental data in all migrate
Add a flag to determine whether the data is incremental data in all migrate
Run allmigrateTest
=> [INLONG-7662][Sort] Add a flag in mysql connector to determine whether the data is incremental data in all migrate

inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/debezium/table/MongoDBConnectorDeserializationSchema.java
- [INLONG-7700][Sort] Update some copy class file when update mongo-cdc version to 2.3
- Fixes #7700 
* Update some copy class file when update mongo-cdc version to 2.3
* update `MongoDBConnectorDeserializationSchema` class
=> [INLONG-7700][Sort] Update some copy class file when update mongo-cdc version to 2.3

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/hudi/HudiDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/iceberg/IcebergDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/hudi/HudiCatalogClient.java
*[INLONG-7701][Manager] Support test connection for hudi in NodeManagement*
- Fixes #7701
=> [INLONG-7701][Manager] Support test connection for hudi in NodeManagement

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/kudu/KuduDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/kudu/KuduResourceClient.java
*[Manager] Support test connection for kudu in NodeManagement*
- Fixes #7713
=> [INLONG-7713][Manager] Support test connection for Apache Kudu

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ErrorCodeEnum.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupProcessService.java
- Fixes #7722 
It's no error message displayed when the task failed.
Check task result before returning
=> [INLONG-7722][Manager] Check task result before returning

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongStreamClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/StreamSinkClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongStreamApi.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/StreamSinkApi.java, inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ParseFieldRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtils.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/stream/InlongStreamTest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSinkController.java
*[INLONG-7688][Manager] Creating schema of StreamSource by SQL*
- Fixes #7688
=> [INLONG-7688][Manager] Creating schema of StreamSource by SQL

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/kudu/KuduDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/kudu/KuduDataNodeInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/kudu/KuduDataNodeRequest.java, inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/common/KuduOptions.java, inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/sink/AbstractKuduSinkFunction.java, inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/sink/KuduAsyncSinkFunction.java, inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/sink/KuduSinkFunction.java, inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/source/KuduLookupFunction.java, inlong-sort/sort-connectors/kudu/src/main/java/org/apache/inlong/sort/kudu/table/KuduDynamicTableFactory.java
*[INLONG-7711][Sort][Manager] Support specifying parameters for the kudu client*
- Fixes #7711
=> [INLONG-7711][Sort][Manager] Support specifying parameters for the kudu client

inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CommandToolMain.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CreateCommand.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/DeleteCommand.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/RestartCommand.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/SuspendCommand.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongGroupClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongGroupApi.java
- Fixes #6672 
Add `inlongctl` status management for the group.
1. Add `suspend` and `restart` commands.
2. Modify the `suspendProcess` return type for the manager client.
=> [INLONG-6672][Manager] Add suspend and restart command

inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingOutputFormat.java
- Fixes #7731 
Fix the problem of calling getAndSetPkFromErrMsg method parameter order
=> [INLONG-7731][Sort] Fix the problem of calling getAndSetPkFromErrMsg method parameter order

inlong-dashboard/src/plugins/clusters/common/ClusterDefaultInfo.ts, inlong-dashboard/src/plugins/nodes/common/NodeDefaultInfo.ts, inlong-dashboard/src/ui/pages/Clusters/CreateModal.tsx, inlong-dashboard/src/ui/pages/Nodes/DetailModal.tsx
- Fixes https://github.com/apache/inlong/issues/7738
=> [INLONG-7738][Dashboard] The name and type of cluster and node cannot be modified

inlong-dashboard/craco.config.ts
=> [INLONG-7758][Dashboard] Login page display error

inlong-dashboard/src/ui/components/HighSelect/index.tsx, inlong-dashboard/src/ui/components/Layout/NavWidget/index.tsx, inlong-dashboard/src/ui/components/UserSelect/index.tsx, inlong-dashboard/src/ui/pages/ClusterTags/ClusterList.tsx, inlong-dashboard/src/ui/pages/ClusterTags/index.module.less, inlong-dashboard/src/ui/pages/ClusterTags/index.tsx, inlong-dashboard/src/ui/pages/Clusters/NodeManage.tsx, inlong-dashboard/src/ui/pages/Clusters/index.tsx, inlong-dashboard/src/ui/pages/GroupDashboard/index.tsx, inlong-dashboard/src/ui/pages/GroupDetail/DataSources/index.tsx, inlong-dashboard/src/ui/pages/GroupDetail/DataStorage/index.tsx, inlong-dashboard/src/ui/pages/GroupDetail/DataStream/index.tsx, inlong-dashboard/src/ui/pages/Nodes/index.tsx, inlong-dashboard/src/ui/pages/ProcessManagement/index.tsx, inlong-dashboard/src/ui/pages/UserManagement/index.tsx
=> [INLONG-7756][Dashboard] Group logs can not display

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ParseFieldRequest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSinkController.java
- Fixes #7760 
Fix parse fields failed for streamSink and InlongStream.
Fix parse fields failed for streamSink and InlongStream.
=> [INLONG-7760][Manager] Fix parse fields failed for streamSink and InlongStream

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java
*[INLONG-7690][Manager] Creating schema of StreamSource by CSV*
- Fixes #7690
=> [INLONG-7690][Manager] Creating schema of StreamSource by CSV

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/redis/RedisDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/redis/RedisDataNodeInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/redis/RedisDataNodeRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/redis/RedisSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/redis/RedisSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/redis/RedisSinkRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/LoadNodeUtils.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/redis/RedisDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/redis/RedisSinkOperator.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/RedisLoadNode.java
*[INLONG-7730][Manager] Support node management for Redis*
- Fixes #7730
=> [INLONG-7730][Manager] Support node management for Redis

docker/docker-compose/docker-compose.yml
- Fixes #7777
website->dashboard.
=> [INLONG-7777][Docker] Fixed the typo for dashboard in docker-compose

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSourceController.java
- Fixes #7774 
Add permission verification for streamSource.
Add permission verification for streamSource.
=> [INLONG-7774][Manager] Add permission verification for streamSource

inlong-manager/manager-service/pom.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/redis/RedisDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/redis/RedisResourceClient.java, licenses/inlong-manager/licenses/LICENSE-jedis.txt, pom.xml
*[INLONG-7719][Manager] Support test connection for Redis in NodeManagement*
- Fixes #7719
=> [INLONG-7719][Manager] Support test connection for Redis in NodeManagement

inlong-dashboard/src/plugins/groups/defaults/Pulsar.ts, inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json
- Fixes https://github.com/apache/inlong/issues/7749
=> [INLONG-7749][Dashboard] Support rate limit for pulsar mq mark-delete operation

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/proxylist_config.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/sdk_constant.h
- Fixes #7781
Solve the problem of cpp-sdk send data by HTTP protocol
The cpp-sdk should send data by TCP protocol
=> [INLONG-7781][SDK]  Solve the problem of cpp-sdk send data by HTTP protocol

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/RemoteConfigManager.java
- Fixes #7769 
*(example:)*
- If a …
=> [INLONG-7769][DataProxy] Fix NPE when request Inlong Manager failed

inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CreateCommand.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/consts/GroupConstants.java
- Fixes #7778 
Optimize the create command for ease of use.
Set default value for group conf.
=> [INLONG-7778][Manager] Add default value for JSON file of the create command

inlong-dashboard/src/plugins/sinks/defaults/ClickHouse.ts
- Fixes https://github.com/apache/inlong/issues/7785
=> [INLONG-7785][Dashboard] Clickhouse sink engine defaults to MergeTree

inlong-dashboard/src/configs/menus/conf.tsx, inlong-dashboard/src/ui/components/Layout/NavWidget/LocaleSelect.tsx, inlong-dashboard/src/ui/components/Layout/index.tsx, inlong-dashboard/src/ui/components/PageContainer/index.module.less, inlong-dashboard/src/ui/components/UserSelect/index.tsx, inlong-dashboard/src/ui/pages/ClusterTags/index.tsx, inlong-dashboard/src/ui/pages/GroupDetail/DataSources/index.tsx, inlong-dashboard/src/ui/pages/GroupDetail/DataStorage/index.tsx
=> [INLONG-7796][Dashboard] Add icon to menu

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/user/UserRequest.java
- Fixes #7804 
Limit the length of user password.
Limit the length of user password.
=> [INLONG-7804][Manager] Limit the length of user password

inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/core/impl/ProcessServiceImpl.java
- Fixes #7798 
Add user authentication when operate workflow.
Add user authentication when operate workflow.
=> [INLONG-7798][Manager] Add user authentication when operate workflow

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/redis/RedisDataNodeDTO.java
- Fixes #7800 
Update redis data node failed.
Set value for `RedisDataNodeDTO`.
=> [INLONG-7800][Manager] Fix update redis data node failure

inlong-dashboard/src/plugins/sources/defaults/MQTT.ts, inlong-dashboard/src/plugins/sources/defaults/Mongodb.ts, inlong-dashboard/src/plugins/sources/defaults/Oracle.ts, inlong-dashboard/src/plugins/sources/defaults/PostgreSQL.ts, inlong-dashboard/src/plugins/sources/defaults/Redis.ts, inlong-dashboard/src/plugins/sources/defaults/SQLServer.ts
- Fixes https://github.com/apache/inlong/issues/7802
=> [INLONG-7802][Dashboard] Requirements for optimizing data sources

inlong-sort/sort-connectors/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/util/ColumnFilterUtil.java, inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/MySqlSource.java, inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlRecordEmitter.java, inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/AllMigrateWithSpecifyingFieldTest.java
- Fixes #7693 
MySQL CDC Connector supports specifying field synchronization
=> [INLONG-7693][Sort] MySQL CDC Connector supports specifying field synchronization

inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/CacheClusterObject.java, inlong-manager/manager-dao/src/main/resources/mappers/ClusterSetMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/dataproxy/CacheCluster.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java
- Fixes #7810 
Fix no token field in the return result of getAllConfig.
Fix no token field in the return result of getAllConfig.
Add token information to `CacheClusterObject` and `CacheCluster`, convert the token information to json, and send it to dataproxy.
=> [INLONG-7810][Manager] Fix no token field in the return result of getAllConfig

inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/table/Elasticsearch6DynamicSink.java
=> [INLONG-7813][Sort] Fix the initialize error of DocumentType for ES6

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/ExcelTool.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/validator/ExcelCellValidator.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/validator/NonEmptyCellValidator.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/StreamField.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/StreamFieldTypeCellValidator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java
=> [INLONG-7816][Manager] Support validation rules when exporting Excel file

inlong-dashboard/src/plugins/sinks/defaults/ClickHouse.ts
- Fixes https://github.com/apache/inlong/issues/7826
=> [INLONG-7826][Dashboard] When the Clickhouse sink engine is ReplicatedMergeTree, it supports filling in the life cycle

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/ExcelTool.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/annotation/Font.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/annotation/Style.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/tuple/ImmutableQuartet.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/tuple/Quartet.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/StreamField.java
[INLONG-7820][Manager] Support style and font when exporting Excel file
- Fixes #7820
=> [INLONG-7820][Manager] Support style and font when exporting Excel file

licenses/inlong-manager/licenses/LICENSE-poi.txt, licenses/inlong-manager/notices/NOTICE-poi.txt, pom.xml
=> [INLONG-7839][Manager] Bump version of apache-poi:poi to 5.2.3

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/GroupCheckService.java
- Fixes #7837 
Fix the Admin user cannot modify streamSource when it is not the responsible person.
Fix the Admin user cannot modify streamSource when it is not the responsible person.
=> [INLONG-7837][Manager] Fix the Admin user cannot modify streamSource when it is not the responsible person

inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterTagEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterTagPageRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/user/UserRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/AnnoController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java
- Fixes #7835 
Support remove the permission when delete user.
Support remove the permission when delete user.
=> [INLONG-7835][Manager] Support remove the permission when delete user

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/ExcelTool.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/annotation/ExcelField.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/StreamField.java
[INLONG-7841][Manager] Support header style and font when exporting Excel file
- Fixes #7841
=> [INLONG-7841][Manager] Support header style and font when exporting Excel file

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ck/ClickHouseSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ck/ClickHouseSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ck/ClickHouseSinkRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ck/ClickHouseTableInfo.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/ck/ClickHouseSqlBuilder.java
- Fixes #7844 
Support to set cluster when create table for clickhouse.
Support to set cluster when create table for clickhouse.
=> [INLONG-7844][Manager] Support to set cluster when create table for clickhouse

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/BinlogSource.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/BinlogReader.java
- Fixes #7847 
It failed to create a MySQL reader.
Init `instanceId`.
=> [INLONG-7847][Agent] Fix failure to create mysql reader

inlong-dashboard/src/plugins/sources/defaults/MySQLBinlog.ts, inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json
- Fixes https://github.com/apache/inlong/issues/7871
=> [INLONG-7871][Dashboard] MySQL source supports filling in the database name whitelist

inlong-common/src/main/java/org/apache/inlong/common/constant/Constants.java, inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/flink/enums/Constants.java, inlong-manager/manager-plugins/src/main/java/org/apache/inlong/manager/plugin/util/FlinkConfiguration.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Constants.java, inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
- Fixes #6668 
Using already existing constants and removing hard codings
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)  not documented
- If a feature is not applicable for documentation, explain why? This change needs no documentation as it's using already created constants at hard-coded strings 
=> [INLONG-6668][Sort] Reusing existing constants

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/stream/InlongStreamTest.java
[INLONG-7895][Manager] Support field description when parsing field by SQL
Fixes #7895
=> [INLONG-7895][Manager] Support field description when parsing field by SQL

inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamEntityMapper.xml
- Fixes #7901 
Fix streams cannot be queried by responsible person.
Fix streams cannot be queried by responsible person.
=> [INLONG-7901][Manager] Fix streams cannot be queried by responsible person

inlong-distribution/src/main/assemblies/release.xml
- Fixes #7910
Exclude the change-xxx.sql files for the docker-compose package, the changes-xxx.sql in the sql directory will affect the docker-compose deployment.
=> [INLONG-7910][Docker] Exclude the change-xxx.sql files for the docker-compose package

inlong-dashboard/src/plugins/clusters/common/ClusterDefaultInfo.ts, inlong-dashboard/src/plugins/nodes/common/NodeDefaultInfo.ts, inlong-dashboard/src/plugins/sinks/defaults/ClickHouse.ts, inlong-dashboard/src/ui/components/NodeSelect/index.tsx, inlong-dashboard/src/ui/pages/ProcessDetail/GroupConfig.tsx
- Fixes https://github.com/apache/inlong/issues/7915
=> [INLONG-7915][Dashboard] Clickhouse sink engine field optimization

inlong-dashboard/src/plugins/sources/defaults/File.ts
- Fixes https://github.com/apache/inlong/issues/7918
=> [INLONG-7918][Dashboard] File source cluster name is displayed as displayName

inlong-dashboard/src/plugins/streams/common/StreamDefaultInfo.ts
- Fixes #7927 
1. Optimize the display of data type.
1. Optimize the display of data type.
=> [INLONG-7927][Dashboard] Optimize the display of data type

inlong-dashboard/src/plugins/sinks/defaults/ClickHouse.ts, inlong-dashboard/src/plugins/sinks/defaults/Doris.ts, inlong-dashboard/src/plugins/sinks/defaults/Elasticsearch.ts, inlong-dashboard/src/plugins/sinks/defaults/Greenplum.ts, inlong-dashboard/src/plugins/sinks/defaults/HBase.ts, inlong-dashboard/src/plugins/sinks/defaults/Hive.ts, inlong-dashboard/src/plugins/sinks/defaults/Hudi.ts, inlong-dashboard/src/plugins/sinks/defaults/Iceberg.ts, inlong-dashboard/src/plugins/sinks/defaults/Kudu.ts, inlong-dashboard/src/plugins/sinks/defaults/MySQL.ts, inlong-dashboard/src/plugins/sinks/defaults/Oracle.ts, inlong-dashboard/src/plugins/sinks/defaults/PostgreSQL.ts, inlong-dashboard/src/plugins/sinks/defaults/Redis.ts, inlong-dashboard/src/plugins/sinks/defaults/SQLServer.ts, inlong-dashboard/src/plugins/sinks/defaults/StarRocks.ts, inlong-dashboard/src/plugins/sinks/defaults/TDSQLPostgreSQL.ts, inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json
- Fixes  https://github.com/apache/inlong/issues/7929
=> [INLONG-7929][Dashboard] The select box cannot be triggered when the form is not entered

inlong-dashboard/src/ui/pages/GroupDashboard/index.tsx, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongGroupEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupPageRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java
- Fixes #7941 
1. We need to distinguish lightweight tasks when querying groups.
1. Add `lightweight` param.
=> [INLONG-7941][Manager][Dashborad] Add param to distinguish lightweight

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/InlongConsumeProcessService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/InlongConsumeService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/InlongConsumeServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/consume/InlongConsumeServiceTest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongConsumeController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSinkController.java
- Fixes #7948 
Add user authentication when operate inlong consume.
Add user authentication when operate inlong consume.
=> [INLONG-7948][Manager] Add user authentication when operate inlong consume

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
- Fixes #7946 
Add user authentication when bind clusterTag.
Add user authentication when bind clusterTag.
=> [INLONG-7946][Manager] Add user authentication when bind clusterTag

.github/ISSUE_TEMPLATE/bug-report.yml
- Fixes #7963
Add the 1.7.0 version option for the bug report
=> [INLONG-7963][Release] Add the 1.7.0 version option for the bug report

CHANGES.md
- Fixes #7964
Update changes log for the 1.7.0 version
=> [INLONG-7964][Release] Update changes log for the 1.7.0 version

inlong-sort/sort-connectors/elasticsearch-base/pom.xml
- Fixes #7983 
Remove the duplicate dependency
=> [INLONG-7983][Sort] Remove the duplicate dependency

CHANGES.md, inlong-manager/manager-docker/Dockerfile
- Fixes #7986
Add JDBC connector jar for test when docker-compose deployment
=> [INLONG-7968][Docker] Add JDBC connector jar for test

CHANGES.md, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/AgentServiceTest.java
- Fixes #7981 
Fix the following issues:
1.Failed to stop source correctly when suspend a group.
2.A task was generated when an agent was added to a SUSPENDED group.
=> [INLONG-7981][Manager] Failed to stop source correctly when suspend a group

inlong-sort/sort-connectors/kafka/src/test/java/org/apache/inlong/sort/kafka/partitioner/InLongFixedPartitionPartitionerTest.java
- Fixes https://github.com/apache/inlong/issues/7990
remove duplicate license
*(example:)* …
=> [INLONG-7990][Sort]  fix license for InLongFixedPartitionPartitionerTest

CHANGES.md, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/postgresql/PostgreSQLDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/postgresql/PostgreSQLDataNodeInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/postgresql/PostgreSQLDataNodeRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/postgresql/PostgreSQLDataNodeOperator.java, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.7.0.sql
- Fixes #7999
Support the `PostgreSQL` data node.
Add PostgreSQL DTO, Info, Request, and Operator classes.
=> [INLONG-7999][Manager] Support PostgreSQL data node

inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/AllMigrateMongoDBTest.java
[INLONG-7994][Sort] Add UT for all migration to MongoDB CDC
- Fixes #7994 
Add UT for all migration to MongoDB CDC
Add `AllMigrateMongoDBTest.java`
Run `AllMigrateMongoDBTest.java`
=> [INLONG-7994][Sort] Add UT for all migration to MongoDB CDC

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/SimpleMessageHandler.java
=> [INLONG-8003][Bug] dataproxy http returns suc all the time

CHANGES.md, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java
- Fixes #8006 
Set displayName for the auto-registered cluster.
Set displayName for the auto-registered cluster.
=> [INLONG-8006][Manager] Set displayName for the auto-registered cluster

CHANGES.md, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/ExtractNodeUtils.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaResourceOperators.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperator.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/enums/KafkaScanStartupMode.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNode.java
- Fixes #7996 
Support issued kafka consumer group to sort.
Support issued kafka consumer group to sort.
=> [INLONG-7996][Manager] Support issued kafka consumer group to sort

CHANGES.md, inlong-agent/agent-plugins/pom.xml, inlong-audit/audit-proxy/pom.xml, inlong-audit/audit-store/pom.xml, inlong-dataproxy/pom.xml, inlong-manager/manager-service/pom.xml, inlong-sort-standalone/pom.xml, inlong-sort/sort-connectors/pulsar/pom.xml
- Fixes #8009
Exclude the useless dependency for pulsar-client to decrease the distribution package size
before: 891MB
after: 794MB
=> [INLONG-8009][Package] Exclude the useless dependency for pulsar-client

CHANGES.md, inlong-dashboard/src/plugins/clusters/common/ClusterDefaultInfo.ts, inlong-dashboard/src/plugins/nodes/common/NodeDefaultInfo.ts
- Fixes https://github.com/apache/inlong/issues/8011
=> [INLONG-8011][Dashboard] Cluster name and node name can be modified when editing

README.md
=> [INLONG-8017][Doc] Update the build status icon for the readme title

CHANGES.md, inlong-dashboard/src/configs/menus/conf.tsx, inlong-dashboard/src/i18n.ts
- Fixes https://github.com/apache/inlong/issues/8022
=> [INLONG-8022][Dashboard] Node management title text optimization

inlong-dashboard/src/ui/components/FieldParseModule/index.tsx, inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json
=> [INLONG-7971][Dashboard] Support batch import stream fields by Excel

CHANGES.md, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java, inlong-manager/manager-web/src/main/resources/application-dev.properties, inlong-manager/manager-web/src/main/resources/application-prod.properties, inlong-manager/manager-web/src/main/resources/application-test.properties
- Fixes #8021 
Periodically delete sources with inconsistent states.
Periodically delete sources with inconsistent states.
=> [INLONG-8021][Manager] Periodically delete sources with inconsistent states

CHANGES.md, inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/internal/FlinkPulsarSource.java, inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/internal/FlinkPulsarSourceWithoutAdmin.java, inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/internal/PulsarFetcher.java, inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/internal/ReaderThread.java
- Fixes #8029 
Fixes #8029 
use fixed subscription name when starting a pulsar reader
see https://github.com/streamnative/pulsar-flink/blob/master/docs/README_CN.md
run pulsar migrate test
=> [INLONG-8029][Sort] Use fixed subscription name when start a pulsar reader

inlong-sort/README.md, inlong-sort/quick_start.md
Add documentation on how to compile Flink v1.15 .
- Fixes #8054 
make the content the same as the official website.
=> [INLONG-8054][Sort] Update document information of Sort

inlong-dashboard/src/ui/components/FieldParseModule/index.tsx
=> [INLONG-8051][Dashboard] Optimize the display effect of the batch parse dialog

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/StatConstants.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/BaseSource.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/InLongMessageFactory.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/InLongMessageHandler.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/SimpleHttpSource.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/SimpleTcpSource.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/SimpleUdpSource.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/SourceConstants.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/httpMsg/InLongHttpMsgHandler.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/v0msg/AbsV0MsgCodec.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/v0msg/CodecBinMsg.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/v0msg/CodecTextMsg.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/v1msg/InlongTcpSourceCallback.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/ConfStringUtils.java
- Fixes #8073
1. Add HTTP processing handler
2. Adjust the current implementation and merge public functions
3. Adjust the order in which each class file references the package
=> [INLONG-8073][DataProxy] Add HTTP message processing logic in source2

.github/workflows/ci_build.yml, .github/workflows/ci_greeting.yml
- Fixes #8082 
Modify the error section in ci_build.yml
=> [INLONG-8082][CI] Fix the error of ci_build.yml ci_greeting.yml parsing failure

inlong-dashboard/package.json, inlong-dashboard/src/ui/pages/GroupDetail/DataSources/index.tsx, inlong-dashboard/src/ui/pages/GroupDetail/DataStorage/index.tsx
- Fixes https://github.com/apache/inlong/issues/8078
=> [INLONG-8078][Dashboard] Fix the Source and sink list pagination does not work

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
- Fixes #8080 
Fix the total parameter found on the page is different from the actual value.
Fix the total parameter found on the page is different from the actual value.
=> [INLONG-8080][Manager] Fix the total parameter found on the page is different from the actual value

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java, inlong-manager/manager-web/src/main/resources/application-dev.properties, inlong-manager/manager-web/src/main/resources/application-prod.properties, inlong-manager/manager-web/src/main/resources/application-test.properties
- Fixes #8088 
Support configure heartbeat timeout interval.
Support configure heartbeat timeout interval.
=> [INLONG-8088][Manager] Support configure heartbeat timeout interval

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongTenantEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongTenantEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/tenant/InlongTenantInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/tenant/InlongTenantPageRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/tenant/InlongTenantRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/tenant/InlongTenantService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/tenant/InlongTenantServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/tenant/InlongTenantServiceTest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongTenantController.java
=> [INLONG-8093][Manager] Add inlong tenant related APIs

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongClientImpl.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupStatusInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/ExtractNodeUtils.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/LoadNodeUtils.java
- Fixes #8114
Fix the NEP that may appear when building Properties , Filter empty values ​​to prevent NEP, because empty values ​​are meaningless to pass downstream.
=> [INLONG-8114][Manager] Fix the NEP that may appear when building Properties.

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/enums/SchemaChangePolicy.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/enums/SchemaChangeType.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/util/SchemaChangeUtils.java, inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/util/SchemaChangeUtilsTest.java, inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/Constants.java, inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtyType.java, inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/format/JsonDynamicSchemaFormat.java, inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/schema/SchemaChangeHandleException.java
- [INLONG-7853][Sort] Add common handle for schema-change in sink
- Fixes #7853 
Add common handle for schema-change in sink
1. Add protocols for schema-change
2. Add tool for schema-change
*(example:)*
=> [INLONG-7853][Sort] Add common handle for schema-change in sink

inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/heartbeat.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/producer.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/example/producer_example.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/metadata/topic_info.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/rpc/client.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/rpc/master.go
- Add `Heartbeat` for GO producer SDK
- Implement #8122 
- Partent issue #4968
=> [INLONG-8122][TubeMQ] Implement "Heartbeat" method for GO SDK

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Constants.java, inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/Entrance.java
- [INLONG-8116][Sort] Support table api config setting
- Fixes #8116 
Support table api config setting
ref to https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/config/
Add two table config setting in sort core
=> [INLONG-8116][Sort] Support table api config setting

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/AbstractClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/AgentClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/DataProxyClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/ElasticsearchClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/KafkaClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/PulsarClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/TubeClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/AbstractGroupOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupOperator4NoneMQ.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java
- Fixes #8136 
Support obtaining resource information used by the current group, like cluster info.
Support obtaining resource information used by the current group.
=> [INLONG-8136][Manager] Support obtaining resource information used by the current group

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterNodeEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterNodeEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
- Fixes #8148 
use '='  instead of 'like' 
use local database can verify
=> [INLONG-8148][Manager] Support precise query of cluster nodes based on IP

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepositoryV2.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java
- Fixes #8163 
- Paren #7914 
Make dataproxy config interface compatible with old versions
*(example:)* …
=> [INLONG-8163][Manager][DataProxy] Make DataProxy config interface compatible with old versions

inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/client.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/partition_router.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/producer.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/example/producer_example.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/metadata/partition.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/rpc/broker.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/rpc/client.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/util/util.go
- Add `SendMessage` for GO producer SDK
- Implement #8165
- Partent issue #4968
=> [INLONG-8165][TubeMQ] Implement "SendMessage" method for GO SDK

inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/task/TestTaskWrapper.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestTextFileReader.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/TestTextFileTask.java
- INLONG-8183][Agent] Optimize agent UT
- Fixes #8183 
*Optimize agent UT to reduce the number of UT failures.*
*Reduce the data volume and timeout time of UT.*
=> [INLONG-8183][Agent] Optimize agent UT

pom.xml
- [INLONG-8176][Agent] Upgrade rocksdb version to 6.29.4.1
- Fixes #8176 
*Modify Upgrade rocksdb to be compatible with M1*
*Upgrade rocksdb version to 6.29.4.1.*
=> [INLONG-8176][Agent] Upgrade rocksdb version to 6.29.4.1

inlong-dashboard/src/plugins/sinks/defaults/Iceberg.ts, inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json
- Fixes https://github.com/apache/inlong/issues/8190
=> [INLONG-8190][Dashboard] Change the display name for PostgreSQL's schema

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamBriefInfo.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInLongStreamController.java
- Fixes #8199 
Supports get brief information of inlong stream.
Supports get brief information of inlong stream.
=> [INLONG-8199][Manager] Supports get brief information of inlong stream

inlong-common/src/main/java/org/apache/inlong/common/util/BasicAuth.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongTenantEntityMapper.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongUserRoleEntityMapper.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/TenantUserRoleEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongTenantEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/InlongUserRoleEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/TenantUserRoleEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/tenant/InlongTenantService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/tenant/InlongTenantServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/InlongRoleService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/InlongRoleServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/TenantRoleService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/TenantRoleServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/tenant/InlongTenantServiceTest.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/user/InlongRoleServiceTest.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/user/TenantRoleServiceTest.java, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.8.0.sql, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/InlongShiroImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/tenant/TenantAuthenticatingFilter.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/tenant/TenantAuthenticatingRealm.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/tenant/TenantToken.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongRoleController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongTenantController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongTenantRoleController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/UserController.java
- Fixes #8200 
Fliter out requests which user has no permission to the specific tenant
*(example:)* …
=> [INLONG-8200][Manager] Add tenant permission filter

inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json, inlong-dashboard/src/ui/pages/GroupDetail/Audit/config.tsx
- Fixes https://github.com/apache/inlong/issues/8204
=> [INLONG-8204][Dashboard] Support querying audit information by sink id

inlong-distribution/pom.xml, inlong-distribution/src/main/assemblies/sort-connectors-v1.15.xml
- Fixes #8220 
Add connector postgre for flink1.15 in distribution
Add connector postgre for flink1.15 in distribution
=> [INLONG-8220][Sort] Add connector postgre for flink1.15 in distribution

inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/kafka/KafkaSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/kafka/KafkaSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/kafka/KafkaSinkRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/KafkaProvider.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/kafka/KafkaResourceOperator.java
[INLONG-8226][Manager] Correct KafkaSink's partitionNum property type definition
- Fixes #8226
Correct KafkaSink's partitionNum property type definition, currently it is of String type, but the integer type is more reasonable.
=> [INLONG-8226][Manager] Correct KafkaSink's partitionNum property type definition

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/DynamicKafkaDeserializationSchema.java
- [INLONG-8218][Sort] Fix kafka connector reader data byte calculation error
- Fixes #8218 
*  Fix kafka connector reader data byte calculation error
* modify metrics calculation of `DynamicKafkaDeserializationSchema`
=> [INLONG-8218][Sort] Fix kafka connector reader data byte calculation error

inlong-dashboard/src/plugins/sinks/defaults/ClickHouse.ts, inlong-dashboard/src/plugins/sinks/defaults/Doris.ts, inlong-dashboard/src/plugins/sinks/defaults/Elasticsearch.ts, inlong-dashboard/src/plugins/sinks/defaults/Greenplum.ts, inlong-dashboard/src/plugins/sinks/defaults/HBase.ts, inlong-dashboard/src/plugins/sinks/defaults/Hive.ts, inlong-dashboard/src/plugins/sinks/defaults/Hudi.ts, inlong-dashboard/src/plugins/sinks/defaults/Iceberg.ts, inlong-dashboard/src/plugins/sinks/defaults/Kudu.ts, inlong-dashboard/src/plugins/sinks/defaults/MySQL.ts, inlong-dashboard/src/plugins/sinks/defaults/Oracle.ts, inlong-dashboard/src/plugins/sinks/defaults/PostgreSQL.ts, inlong-dashboard/src/plugins/sinks/defaults/Redis.ts, inlong-dashboard/src/plugins/sinks/defaults/SQLServer.ts, inlong-dashboard/src/plugins/sinks/defaults/StarRocks.ts, inlong-dashboard/src/plugins/sinks/defaults/TDSQLPostgreSQL.ts, inlong-dashboard/src/ui/components/EditableTable/index.tsx
=> [INLONG-8046][Dashboard] Support batch import of sink fields

inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/DataNodeController.java, inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/controller/DataNodeControllerTest.java
- Fixes #8247 
Removes the restriction that only the admin user can create DataNodes.
Removes the restriction that only the admin user can create DataNodes.
=> [INLONG-8247][Manager] Removes the restriction that only the admin user can create DataNodes

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/TriggerFileReader.java
*fix the bug that thread leaks after job finished*
- Fixes #8244 
*fix the bug that thread leaks after job finished*
*fix the bug that thread leaks from direction trigger after job finished*
*(example:)*
=> [INLONG-8244][Agent] Fix the thread leaks after job finished

inlong-dashboard/src/ui/pages/GroupDetail/DataStorage/DetailModal.tsx, inlong-dashboard/src/ui/pages/GroupDetail/DataStream/StreamItemModal.tsx
- Fixes https://github.com/apache/inlong/issues/8254
*(example:)* …
=> [INLONG-8254][Dashboard] Supports get brief information of inlong stream

inlong-dashboard/src/ui/components/NodeSelect/index.tsx
- Fixes https://github.com/apache/inlong/issues/8257
=> [INLONG-8257][Dashboard] Optimize the data node to display normally

inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/filter/TenantInsertionFilter.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/filter/WebFilterConfig.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/utils/HttpContextUtils.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/utils/InlongRequestWrapper.java, inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/filter/TenantInsertionFilterTest.java
=> [INLONG-8231][Manager] Add tenant into param and body of each request

inlong-sort/sort-flink/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/debezium/table/RowDataDebeziumDeserializeSchema.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlRecordEmitter.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlTableSource.java
- [INLONG-8274][Sort] Fix mysql connector will throw exception when synchronizing incremental data
- Fixes #8274 
* Fix mysql connector will throw exception when synchronizing incremental data
* Add schemaChange judge for ddl process
=> [INLONG-8274][Sort] Fix mysql connector will throw exception when synchronizing incremental data

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/user/UserInfo.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/tenant/TenantAuthenticatingRealm.java
=> [INLONG-8278][Manager] Add tenant into the login user info

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ConfigConstants.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/HostInfo.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/http/InternalHttpSender.java
=> [INLONG-8272][SDK] Fix DataProxy's HTTP SDK verification response code error

.asf.yaml, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/ClientConfiguration.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/AuthInterceptor.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/ClientUtils.java
- Fixes #8281 
Add the tenant request header information when initializing the Manager Http client
The details can be found at [#8281 ](https://github.com/apache/inlong/issues/8281).
=> [INLONG-8281][Manager] Add the tenant request header when initializing the manager-client

licenses/inlong-manager/LICENSE, licenses/inlong-sort-connectors/LICENSE, pom.xml
- [INLONG-8326][Build] Remove duplicate dependency declarations of "jsqlparser"
- Fixes #8326 
Remove duplicate dependencies and duplicate versions.
=> [INLONG-8326][Build] Remove duplicate dependency declarations of "jsqlparser"

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepositoryV2.java
- Fixes #8330 
Fix the information returned by the getAllConfig interface is incorrect.
Fix the information returned by the getAllConfig interface is incorrect.
=> [INLONG-8330][Manager] Fix the information returned by the getAllConfig interface is incorrect

inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/MiniAgent.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/TestFileAgent.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/TestTextFileTask.java
- Fixes #8347
*The agent UT of testTimeOffset has ConcurrentModification problem,and  it will block the PR of the whole project*
*Optimize the agent UT of testTimeOffset*
=> [INLONG-8347][Agent] Optimize the agent UT of testTimeOffset

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/config/JDBCSourceConfig.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongGroupEntity.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/interceptor/MultiTenantInterceptor.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/interceptor/MultiTenantInterceptorConfiguration.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongGroupEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml, inlong-manager/manager-dao/src/test/java/org/apache/inlong/manager/dao/DaoBaseTest.java, inlong-manager/manager-dao/src/test/java/org/apache/inlong/manager/dao/mapper/InlongGroupEntityMapperTest.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/ServiceBaseTest.java, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.8.0.sql, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java
=> [INLONG-8276][Manager] InlongGroup support multiple tenant

inlong-dashboard/src/plugins/RenderRow.ts, inlong-dashboard/src/plugins/sinks/common/SinkDefaultInfo.ts
- Fixes #8350
Support light mode, reuse plugins, rel #8302
=> [INLONG-8350][Dashboard] Dashboard plugin support light

inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/trigger/TestTriggerManager.java
- Fixes #8352
*The agent UT of testRestartTriggerJobRestore has problem,and it will block the PR of the whole project.*
*Optimize the agent UT of testRestartTriggerJobRestore.*
=> [INLONG-8352][Agent] Optimize the agent UT of testRestartTriggerJobRestore

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongClusterEntity.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterEntityMapper.xml, inlong-manager/manager-dao/src/test/java/org/apache/inlong/manager/dao/mapper/InlongClusterEntityMapperTest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterPageRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterRequest.java, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.8.0.sql, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java
- Fixes #8365 
InlongCluster support multiple tenant
*(example:)*
- If a feature …
=> [INLONG-8365][Manager] InlongCluster support multiple tenant

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/queue/tubemq/TubeBrokerInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/queue/tubemq/TubeMessageResponse.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/QueueResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/tubemq/TubeMQOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/tubemq/TubeMQResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java
- Fixes #8354 
Support previewing data of tube.
Support previewing data of tube.
=> [INLONG-8354][Manager] Support previewing data of TubeMQ

inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/TestTextFileTask.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/trigger/TestTriggerManager.java
- Fixes #8376
*The agent UT of TestTriggerManager has problem,and it will block the PR of the whole project.*
*Optimize the agent UT of TestTriggerManager.*
=> [INLONG-8376][Agent] Optimize the agent UT of TestTriggerManager

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongClusterTagEntity.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterTagEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterTagEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterTagPageRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterTagRequest.java, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.8.0.sql, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java
- Fixes #8378 
- Parent #7914 #8275 
*(example:)* …
=> [INLONG-8378][Manager] InlongClusterTag support multi-tenancy

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneProducer.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSink.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneWorker.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/BufferQueue.java
- Fixes #8385
1. Add takeDispatchedRecord() in BufferQueue class
2. Replace calling pollDispatchedRecord() with takeDispatchedRecord() in the MessageQueueZoneWorker class
=> [INLONG-8385][DataProxy] Add take method in BufferQueue class

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongConsumeEntity.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongConsumeEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongConsumeEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/InlongConsumePageRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/InlongConsumeRequest.java, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.8.0.sql, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongConsumeController.java
- Fixes #8380 
- Parent #8275 #7914 
*(example:)*
=> [INLONG-8380][Manager] InlongConsume support multi-tenancy

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/AbstractDataNodeOperator.java
- Fixes #8400
Fix the streamSource with no data_node_name has been incorrectly modified.
Fix the streamSource with no data_node_name has been incorrectly modified.
=> [INLONG-8400][Manager] Fix the streamSource with no data_node_name has been incorrectly modified

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/TenantUserTypeEnum.java, inlong-manager/manager-dao/src/main/resources/mappers/TenantUserRoleEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/user/TenantRolePageRequest.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/user/TenantRoleServiceTest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongRoleController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongTenantController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongTenantRoleController.java
- Fixes #8394 
To enhance the tenant role list interface, make it support fuzzy match
*(example:)*
=> [INLONG-8394][Manager] TenantRole list interface support fuzzy match

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/InlongRoleServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/TenantRoleServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/InlongShiroImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/openapi/OpenAPIFilter.java
- Fixes #8398 
Optimize multiple tenant related logs
Reduce log level from warn to debug when not found tenant role or inlong role of the target user.
Return empty SecretToken when api auth is disabled.
*(example:)* …
=> [INLONG-8398][Manager] Optimize multiple tenant related logs

inlong-manager/manager-dao/src/main/resources/mappers/AuditEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/audit/AuditInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/audit/AuditRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/AuditServiceTest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/AuditController.java
- Fixes #8396 
1.Support for querying audit data with average delay.
2.Support querying audit data for multiple days.
1.Support for querying audit data with average delay.
2.Support querying audit data for multiple days
=> [INLONG-8396][Manager] Support for querying audit data with average delay

.asf.yaml, README.md, pom.xml
- Fixes #8419
From the coming version, InLong supports Data Ingestion, Data Synchronization, and Data Subscription at the same time, I think we could add full-scenario for InLong.
Update the description about InLong
=> [INLONG-8419][Doc] Update the description about InLong

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergSingleFileCommiter.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/test/java/org/apache/inlong/sort/iceberg/sink/HadoopCatalogResource.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/test/java/org/apache/inlong/sort/iceberg/sink/TestRollbackAndRecover.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/test/java/org/apache/inlong/sort/iceberg/sink/util/SimpleDataUtil.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/test/java/org/apache/inlong/sort/iceberg/sink/util/TestTableLoader.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/test/java/org/apache/inlong/sort/iceberg/sink/util/TestTables.java, licenses/inlong-sort-connectors/LICENSE
- [INLONG-8366][Sort] Data loss occurs when checkpoint restores ingesting into iceberg
- Fixes #8366 
*(example:)* …
=> [INLONG-8366][Sort] Lost data in Iceberg when restoring checkpoint

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
- Fixes #8425 
Fix error in obtaining audit information when sink is not configured.
Fix error in obtaining audit information when sink is not configured.
=> [INLONG-8425][Manager] Fix error in obtaining audit information when sink is not configured

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java
- Fixes #8434 
Fix error converting null to string when converting JSON string.
Fix error converting null to string when converting JSON string.
=> [INLONG-8434][Manager] Fix error converting null to string when converting JSON string

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenDataNodeController.java
- Fixes #8438 
Removes the restriction that only the admin user can create DataNodes by openAPI.
Removes the restriction that only the admin user can create DataNodes by openAPI.
=> [INLONG-8438][Manager] Removes the restriction that only the admin user can create DataNodes by openAPI

inlong-manager/manager-client/pom.xml, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/ClientFactory.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongTenantClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongTenantRoleClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongTenantApi.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongTenantRoleApi.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/TenantRoleService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/TenantRoleServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/user/TenantRoleServiceTest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongTenantRoleController.java
- Fixes #8423  
add two clients in mangaer client
- InlongTenant client 
- InlongTenantRole client
The details can be found at [#8423  ](https://github.com/apache/inlong/issues/8423).
=> [INLONG-8423][Manager] Manager client support tenant operation

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/ComponentHeartbeatEntityMapper.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/GroupHeartbeatEntityMapper.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamHeartbeatEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/ComponentHeartbeatEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/GroupHeartbeatEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/StreamHeartbeatEntityMapper.xml, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.8.0.sql
- Fixes #8449 
Fix abnormal growth of self increasing primary key in heartbeat table.
Fix abnormal growth of self increasing primary key in heartbeat table.
=> [INLONG-8449][Manager] Fix abnormal growth of self increasing primary key in heartbeat table

inlong-dashboard/src/configs/menus/conf.tsx, inlong-dashboard/src/ui/components/Layout/Tenant/index.tsx, inlong-dashboard/src/ui/pages/TenantManagement/DetailModal.tsx
- Fixes https://github.com/apache/inlong/issues/8461
=> [INLONG-8461][Dashboard] Cluster management tag optimization

.github/ISSUE_TEMPLATE/bug-report.yml
- Fixes #8451 
Add the 1.8.0 version option for the bug report
=> [INLONG-8451][Release] Add the 1.8.0 version option for the bug report

CHANGES.md
- Fixes #8452 
Update changes log for the 1.8.0 version
=> [INLONG-8452][Release] Update changes log for the 1.8.0 version

pom.xml
*[INLONG-8478][CVE] Upgrade com.h2database:h2 to version 2.2.220*
- Fixes #8478
=> [INLONG-8478][CVE] Upgrade com.h2database:h2 to version 2.2.220

inlong-dashboard/src/ui/components/FieldList/DetailModal.tsx, inlong-dashboard/src/ui/pages/SynchronizeDetail/Info/index.tsx, inlong-dashboard/src/ui/pages/SynchronizeDetail/index.tsx
- Fixes https://github.com/apache/inlong/issues/8486
=> [INLONG-8486][Dashboard] Data synchronization field mapping optimization

.github/workflows/ci_build.yml, .github/workflows/ci_docker.yml, .github/workflows/ci_ut.yml, .github/workflows/ci_ut_flink15.yml, .github/workflows/codeql_analysis.yml
- Fixes #8494
- Use different Maven cache key for workflows
- Remove unnecessary packages to release more disk space
=> [INLONG-8494][CI] Use different maven cache key for workflows

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongStreamClient.java
- Fixes #8491   
Manager client support list inlong streams with sources and sinks by paginating
The details can be found at [#8491   ](https://github.com/apache/inlong/issues/8491).
=> [INLONG-8491][Manager] Manager client support list inlong streams with sources and sinks by paginating

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamProcessService.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInLongStreamController.java
- Fixes #8498 
Add permission verification for InlongStreamProcessService.
Add permission verification for InlongStreamProcessService.
=> [INLONG-8498][Manager] Add permission verification for InlongStreamProcessService

inlong-dashboard/src/plugins/consumes/common/ConsumeDefaultInfo.ts
- Fixes #8512
change the `result` to `result.topic`
=> [INLONG-8512][Dashboard] Tube consumer bug fix when selecting topic

inlong-manager/manager-plugins/base/src/main/assembly/assembly.xml
- Fixes #8516 
Missing scala dependency for Manager plugin Flink 1.15
Add scala dependency for manager plugin Flink 1.15
=> [INLONG-8516][Manager] Add scala dependency for manager plugin Flink 1.15

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/BriefMQMessage.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/DeserializeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/InlongMsgDeserializeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/PbMsgDeserializeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/RawMsgDeserializeOperator.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/decode/MessageDeserializer.java
- Fixes #8504 
Modify nodeIp in dataproxy message to clientIp.
Modify nodeIp in dataproxy message to clientIp.
=> [INLONG-8504][Manager] Modify nodeIp in dataproxy message to clientIp

inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CreateCommand.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/DescribeCommand.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/ListCommand.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/UpdateCommand.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/TenantInfo.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/TenantRoleInfo.java
- Fixes #8374 
Manager client tools support create tenant and  tenant role.
Manager client tools support updatetenant and  tenant role.
Manager client tools support list tenant and tenant role by names.
*(example:)*
- Does this pull …
=> [INLONG-8374][Manager] Manager client tools support multiple tenant

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/httpMsg/HttpMessageHandler.java
- Fixes #8507 
Modify nodeIp in dataproxy message to clientIp
=> [INLONG-8507][Dataproxy] Modify nodeIp in dataproxy message to clientIp

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/FileReaderOperator.java
makeup the code to figure out whether it is kvm、k8s or not
[INLONG-8520][Agent] makeup the code to figure out whether it is kvm, k8s or not
- Fixes #8520
*the file agent messages to dataproxy are all json format*
*makeup the code to figure out whether it is kvm, k8s or not*
*(example:)* …
=> [INLONG-8520][Agent] Makeup the code to figure out whether it is kvm, k8s or not

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/TenantRoleService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/TenantRoleServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/ServiceBaseTest.java, inlong-manager/manager-web/sql/changes-1.8.0.sql, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/filter/TenantInsertionFilter.java, inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/filter/TenantInsertionFilterTest.java
- Fixes #8511 
Add admin permission of public tenant to all users
=> [INLONG-8511][Manager] Add admin permission of public tenant to all users

inlong-agent/bin/agent-env.sh
- Fixes #8524
Unify the JVM options for Agent.
Add G1GC and gc-logs related options.
=> [INLONG-8524][Agent] Update the JVM Options for Agent

inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/utils/InlongRequestWrapper.java
- Fixes #8527
Fix wrong capitalization of InlongRequestWrapper
=> [INLONG-8527][Manager] Fix wrong capitalization of InlongRequestWrapper

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/ck/ClickHouseConfig.java
- [INLONG-8490][Manager] Fix the null pointer problem in updateRuntimeConfig method
- Fixes #8535 
Correct the judgment logic of "changed" in updateRuntimeConfig method.
=> [INLONG-8490][Manager] Fix the null pointer problem in updateRuntimeConfig method

inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
- Fixes #8537 
Fix insert group failed.
Fix insert group failed.
=> [INLONG-8537][Manager] Fix insert group failed

docker/build-docker-images.sh, inlong-manager/manager-docker/Dockerfile, inlong-manager/manager-docker/pom.xml
- Fixes #8533 
Add MySQL connector to the manager image for test
Add MySQL connector to the manager image for test
=> [INLONG-8533][Docker] Add MySQL connector to the manager image for test

inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
- Fixes #8541 
Fix saving InlongGroup with error tenant
*(example:)*
=> [INLONG-8541][Manager] Fix saving InlongGroup with error tenant

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/fieldtype/strategy/ClickHouseFieldTypeStrategy.java, inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtilsTest.java
[INLONG-8514][Manager] Support ClickHouse field type with Nullable modifier
- Fixes #8514
support ClickHouse field type with Nullable modifier,for example Nullable(Int8(11))
=> [INLONG-8514][Manager] Support ClickHouse field type with Nullable modifier

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/AgentServiceTest.java
…group
- Fixes #8539 
see issue #8539 
*(example:)* …
=> [INLONG-8539][Manager] Logically remove all sources when agent heartbeat contains no group message

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java
- Fixes #8552
Fix the data preview obtained is not the latest message.
Fix the data preview obtained is not the latest message.
=> [INLONG-8552][Manager] Fix the data preview obtained is not the latest message

inlong-manager/pom.xml
- Fixes #8570 
Modify packaging order.
Modify packaging order.
=> [INLONG-8570][Manager] Modify packaging order

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamBriefInfo.java, inlong-manager/manager-service/pom.xml
- Fixes #8572 
Fix missing information in InlongStreamBriefInfo.
Fix missing information in InlongStreamBriefInfo.
=> [INLONG-8572][Manager] Fix missing information in InlongStreamBriefInfo

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/interceptor/MultiTenantInterceptor.java, inlong-manager/manager-dao/src/main/resources/mappers/DataNodeEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterTagEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/InlongConsumeEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/user/UserRoleCode.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/tenant/InlongTenantServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/TenantRoleServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sort/SortServiceImplTest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/tenant/TenantAuthenticatingRealm.java
- Fixes #8567 
*(example:)*
- If a …
=> [INLONG-8567][Manager] Add new role INLONG_SERVICE for internal service query

inlong-dashboard/src/plugins/nodes/defaults/Hive.ts, inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json
- Fixes https://github.com/apache/inlong/issues/8560
=> [INLONG-8560][Dashboard] Hive supports filling in username and password

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/AbstractDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/mysql/MySQLDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java
- Fixes #8564 
Fix modify dataNode information unable to issue task.
Fix modify dataNode information unable to issue task.
=> [INLONG-8564][Manager] Fix unable to issue tasks when modifying data node info

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/tubemq/TubeMQSourceOperator.java
- Fixes #8580 
Fix Error in pushing topic information when using TubeMQ.
Fix Error in pushing topic information when using TubeMQ.
=> [INLONG-8580][Manager] Fix Error in pushing topic information when using TubeMQ

inlong-dashboard/src/ui/pages/GroupDetail/ResourceInfo/index.tsx
- Fixes https://github.com/apache/inlong/issues/8546
=> [INLONG-8546][Dashboard] Resource details abnormal display repair

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
- Fixes #8582 
Remove unnecessary log information in InlongClusterServiceImpl.
Remove unnecessary log information in InlongClusterServiceImpl.
=> [INLONG-8582][Manager] Remove unnecessary log information in InlongClusterServiceImpl

inlong-dashboard/src/core/stores/index.ts, inlong-dashboard/src/ui/components/Layout/Tenant/index.tsx, inlong-dashboard/src/ui/pages/TenantManagement/DetailModal.tsx, inlong-dashboard/src/ui/pages/TenantManagement/index.tsx
- Fixes https://github.com/apache/inlong/issues/8575
=> [INLONG-8575][Dashboard]  Tenant management query optimization

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongClusterEntity.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongClusterTagEntity.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/TenantClusterTagEntity.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterEntityMapper.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/TenantClusterTagEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterTagEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/TenantClusterTagEntityMapper.xml, inlong-manager/manager-dao/src/test/java/org/apache/inlong/manager/dao/mapper/InlongClusterEntityMapperTest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterPageRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterTagRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterTagResponse.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/TenantClusterTagInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/TenantClusterTagPageRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/TenantClusterTagRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/InlongRoleService.java, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.9.0.sql, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongTenantRoleController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/UserController.java
- Fixes #8590 
*(example:)*
- If a …
=> [INLONG-8590][Manager] Make Cluster and ClusterTags as public resources

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTO.java, inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTOTest.java
- Fixes #8603 
Fix the vulnerability to security attacks for the MySQL JDBC URL.
Fix the vulnerability to security attacks for the MySQL JDBC URL.
=> [INLONG-8603][Manager] Fix the vulnerability to security attacks for the MySQL JDBC URL

.github/workflows/ci_build.yml, .github/workflows/ci_ut.yml
- Fixes #8614
Remove unnecessary packages for UT and build workflow
=> [INLONG-8614][CI] Remove unnecessary packages for UT and build workflow

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarFederationSink.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarFederationSinkContext.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarIdConfig.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarProducerCluster.java
- Fixes #8598 
*(example:)*
- If a …
=> [INLONG-8598][Sort] Optimize sortstandalone pulsar sink

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
- Fixes #8617
*(example:)*
- If a …
=> [INLONG-8617][Manager] Optimize compatibility of SortSdk config interface

inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/UserController.java
- Fixes #8622 
User API can be accessed with too many permissions
UserController API Permissions
=> [INLONG-8622][Manager] User API Permissions Optimization

inlong-dashboard/src/ui/pages/TenantManagement/index.tsx
- Fixes https://github.com/apache/inlong/issues/8624
=> [INLONG-8624][Dashboard] Tenant management search tenants are displayed normally

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java
fix: sending invalid data to dataproxy failed blocks normal data sending
1. clean the resend queue and release the semaphore
2. sender manager will send the data in the resend queue first
[INLONG-8629][agent] sending invalid data to dataproxy failed blocks normal data sending
- Fixes #8629 
*sending invalid data to dataproxy failed blocks normal data sendin*
*1. clean the resend queue and release the semaphore
2. sender manager will send the data in the resend queue first*
*(example:)* …
=> [INLONG-8629][Agent] Fix sending invalid data to dataproxy failed blocks normal data sending

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/worker.go
- [INLONG-8631][DataProxy][Golang SDK] Handle context.Done() in Send()
- Fixes #8631
Handle context.Done() in Send()
*(example:)* …
=> [INLONG-8631][SDK] Handle context.Done() in Send()

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/request.go, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/worker.go
- [INLONG-8637][DataProxy][Golang SDK] Pool data request and batch request
- Fixes #8637
Pool data request and batch request
Pool data request and batch request
*(example:)*
- If a feature …
=> [INLONG-8637][SDK] Pool data request and batch request

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/worker.go, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/logger/logger.go
- [INLONG-8633][DataProxy][Golang SDK] Update debug log level
- Fixes #8633 
Disable debug level logs;
Downgrade some log from level warn to debug;
*(example:)* …
=> [INLONG-8633][SDK] Update debug log level

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java
stop sending task snapshot to manager, manger never use the snapshot.
- Fixes #8647 
*manger never use the snapshot*
*stop sending task snapshot to manager*
*(example:)*
=> [INLONG-8647][Agent] Stop sending task snapshot to manager

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/conf/ConfigJetty.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobManager.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/job/JobWrapper.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/trigger/TriggerManager.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/TextFileSource.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/TriggerFileReader.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/trigger/DirectoryTrigger.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/PluginUtils.java
- Fixes #8655 
*fix bug: JobWrapper thread leaks when the job is stopped*
* clear  JobWrapper::allTasks in the cleanup function*
*(example:)*
=> [INLONG-8655][Agent] Fix bug: JobWrapper thread leaks when the job is stopped

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSink.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSinkContext.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneWorker.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/BaseSource.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageFactory.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleHttpSource.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleTcpSource.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleUdpSource.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/httpMsg/HttpMessageHandler.java
- Fixes #8657
1. cache source's name and ChannelProcessor;
2. cache sink's name and Channel
=> [INLONG-8657][DataProxy] Cache Source, Sink name and Channel object content

inlong-dashboard/src/plugins/sources/defaults/MySQLBinlog.ts
- Fixes #8661 
*(example:)*
- If a …
=> [INLONG-8661][Dashboard] Fix:field require

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/user/LoginUserUtils.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInLongClusterController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInlongTenantController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInlongTenantRoleController.java
- Fixes #8663  
Manager component Add tenant related openAPI
The details can be found at [#8663  ](https://github.com/apache/inlong/issues/8663).
=> [INLONG-8663][Manager] Add tenant related OpenAPI

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongTenantApi.java
- Fixes #8675 
update InlongTenantApi get method request type with post
The details can be found at [#8675 ](https://github.com/apache/inlong/issues/8675).
=> [INLONG-8675][Manager] Update InlongTenantApi get method request type with post

inlong-agent/agent-docker/Dockerfile, inlong-audit/audit-docker/Dockerfile, inlong-manager/manager-docker/Dockerfile, inlong-sort/quick_start.md, inlong-tubemq/tubemq-docker/tubemq-manager/Dockerfile, pom.xml
- Fixes #8688 
Update Mysql-Connector to avoid security problem.
Upgrade Mysql version and edit README.MD
*(example:)*
- …
=> [INLONG-8688][Security] Upgrade Mysql-connector version

inlong-tubemq/resources/assets/scripts/common/module.js
- Fixes #8717 
Fix display wrong response message in TubeMQ Master web panel.
- Edit the error code check login in js.
- Add scrollbar in the tip windows, as:
*(example:)*
- If a feature …
=> [INLONG-8717][TubeMQ] Display wrong response message in TubeMQ Master web panel

inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/DataNodeController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java, inlong-manager/manager-web/src/main/resources/log4j2.xml
- Fixes #8627 
Enhanced validation of request parameters.
Add validation of the parameters of the testConnection method in the Controller.
=> [INLONG-8627][Manager] Add parameters validation for the testConnection method

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/AgentServiceTest.java
- Fixes #8739 
Fix The file collection task was mistakenly deleted.
Fix The file collection task was mistakenly deleted.
=> [INLONG-8739][Manager] Fix The file collection task was mistakenly deleted

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/Constants.java, inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/schema/SchemaChangeHelper.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/IcebergTableSink.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/schema/IcebergSchemaChangeHelper.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/FlinkSink.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/DynamicSchemaHandleOperator.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergMultipleStreamWriter.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergSchemaChangeUtils.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/RecordWithSchema.java
- [INLONG-8734][Sort] Improve iceberg sync ddl
- Fixes #8734 
Improve iceberg sync ddl
* Add `sink.multiple.auto-create-table-when-snapshot` option for control auto create table when sanpshot
* Improve dirty data metric computing
* Fix alter operation error
* Fix exception print  of `DynamicSchemaHandleOperator`, beacause `javax.ws.rs.NotSupportedException` class not found, I will use RuntimeException replace.
=> [INLONG-8734][Sort] Improve iceberg sync ddl

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/enums/AlterType.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/expressions/AlterColumn.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/utils/OperationUtils.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/test/java/org/apache/inlong/sort/cdc/TestOperation.java
- Fixes #8743
Support more types of ddl in all migration
Added 
1、create table with character constraint (test)
2、support add constraint 
3、support drop constraint 
4、ALTER TABLE test CHANGE COLUMN  (test)
Run TestOperation
=> [INLONG-8743][Sort] Support more types of ddl in all migration

inlong-sort/sort-flink/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/util/MetaDataUtil.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/utils/MetaDataUtils.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/table/OracleReadableMetaData.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/cdc/postgres/table/PostgreSQLReadableMetaData.java, inlong-sort/sort-formats/format-json-v1.13/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJson.java
- Fixes #8745
The sink connctor should have access to the incremental phase and postgre types 
to create table and modify table schema
Add incremental and PostGre type in postgre connector
Run AllmigratePostgreTest
=> [INLONG-8745][Sort] Add incremental and PostGre type in postgre connector

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/sdk_conf.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.cc
- Fixes #8747
*Optimize the local configuration management of cpp sdk.*
*Use the singleton design pattern to optimize the local configuration management of cpp sdk.*
=> [INLONG-8747][SDK] Optimize the local configuration management of cpp sdk

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java, inlong-manager/manager-web/src/main/resources/application-dev.properties, inlong-manager/manager-web/src/main/resources/application-prod.properties, inlong-manager/manager-web/src/main/resources/application-test.properties
- Fixes #8749 
Support configuring whether to initialize node state during startup.
Support configuring whether to initialize node state during startup.
=> [INLONG-8749][Manager] Support configuring whether to initialize node state during startup

inlong-dashboard/src/ui/pages/SynchronizeDetail/SyncT/SourceSinkCard.tsx
- Fixes #8760 
Make Transform Button wrap
Make Transform Button wrap
Result: 
*(example:)* …
=> [INLONG-8760][Dashboard] Make the transform button wrap

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
- Fixes #8771 
Audit data error for MySQL source.
1. Fix audit data error.
2. Add source type for DataSync mode.
Dashboard: https://github.com/apache/inlong/pull/8704
=> [INLONG-8771][Manager] Fix audit data error and add source type for DataSync

inlong-dashboard/src/ui/components/FieldList/index.tsx
- Fixes https://github.com/apache/inlong/issues/8757
=> [INLONG-8757][Dashboard] Implement buttons using a link

inlong-sort/sort-flink/sort-flink-v1.13/pom.xml, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/jdbc/pom.xml, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/pom.xml, inlong-sort/sort-flink/sort-flink-v1.15/pom.xml
- Fixes #8776 
Connectors should add jdbc driver jar to its uber jar
Connectors add jdbc driver jar to its uber jar
=> [INLONG-8776][Sort] Connectors should add jdbc driver jar to its uber jar

inlong-dashboard/src/ui/components/Layout/NavWidget/PasswordModal.tsx, inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json, inlong-dashboard/src/ui/pages/Login/index.tsx
=> [INLONG-8779][Dashboard] Modify password verification optimization

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/AddFieldRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/stream/InlongStreamTest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInLongStreamController.java
- Fixes #8794 
Support add streamField and sinkField and remove duplicates when adding fields.
Support add streamField and sinkField and remove duplicates when adding fields.
=> [INLONG-8794][Manager] Support add streamField and sinkField

inlong-dashboard/src/ui/components/UserSelect/index.tsx
- Fixes #8800 
Start searching all users when getting focus.
=> [INLONG-8800][Dashboard] Owners search component optimization

inlong-dashboard/src/plugins/sources/defaults/MySQLBinlog.ts, inlong-dashboard/src/ui/components/FieldList/DetailModal.tsx, inlong-dashboard/src/ui/components/GroupLogs/GroupLogs.tsx, inlong-dashboard/src/ui/pages/SynchronizeDetail/Info/index.tsx, inlong-dashboard/src/ui/pages/SynchronizeDetail/SyncT/SourceSinkCard.tsx
- Fixes https://github.com/apache/inlong/issues/8788
SourceField and SinkField are aligned with the width of source and sink above.
Set the timeout period when the group re-executes the log operation, and the responsible person defaults to the current user when creating a new synchronization.
=> [INLONG-8788][Dashboard] Data synchronization page optimization

inlong-dashboard/src/ui/pages/Process/Applies/config.tsx, inlong-dashboard/src/ui/pages/Process/Approvals/config.tsx
- Fixes https://github.com/apache/inlong/issues/8810
link add inlongGroupMode
*(example:)* …
=> [INLONG-8810][Dashboard] Approval management process ID link optimization

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTO.java, inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTOTest.java
- Fixes #8813 
Replacing Whitespace Characters in MySQL JDBC URL.
Replacing Whitespace Characters in MySQL JDBC URL.
=> [INLONG-8813][Manager] Replacing whitespace characters in MySQL JDBC URL

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
- Fixes #8829 
Support configuring whether to use zookeeper by request.
Support configuring whether to use zookeeper by request.
=> [INLONG-8829][Manager] Support configuring whether to use zookeeper by request

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongGroupEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/tenant/InlongTenantServiceImpl.java
[INLONG-8805][Manager] Check tenant status before deleting tenant
*[INLONG-8805][Manager] Check tenant status before deleting tenant*
- Fixes #8805
[INLONG-8805][Manager] Check tenant status before deleting tenant*
*(example:)*
- If yes, how is the feature documented? (not applicable / …
=> [INLONG-8805][Manager] Check tenant status before deleting tenant

inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/DescribeCommand.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/ListCommand.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/DefaultInlongStreamBuilder.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongStreamImpl.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/StreamTransformClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/StreamTransformApi.java
- Fixes #8832 
Fix the problem of The request type for transform/list in the client does not match the actual one.
Fix the problem of The request type for transform/list in the client does not match the actual one.
=> [INLONG-8832][Manager] Fix the problem of The request type for transform/list in the client does not match the actual one

doap_InLong.rdf
- Fixes #8846
Add ASF DOAP File for InLong
=> [INLONG-8846][Doc] Add ASF DOAP File for InLong

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/NodeRelationUtils.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/TransformNodeUtils.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java
- Fixes #8834 
Fix the problem of no relationship generated after setting the transformNode.
Fix the problem of no relationship generated after setting the transformNode.
=> [INLONG-8834][Manager] Fix the problem of no relationship generated after setting the transformNode

inlong-dashboard/src/plugins/sinks/defaults/StarRocks.ts, inlong-dashboard/src/ui/pages/TenantManagement/TenantModal.tsx
- Fixes https://github.com/apache/inlong/issues/8843
create tenant: description  input --> textarea
=> [INLONG-8843][Dashboard] StarRocks sink field optimization

inlong-manager/manager-dao/src/main/resources/mappers/TenantUserRoleEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/tenant/InlongTenantServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/TenantRoleServiceImpl.java
- Fixes #8852 
Supports fuzzy matching of username based on keyword.
Supports fuzzy matching of username based on keyword.
=> [INLONG-8852][Manager]  Supports fuzzy matching of username based on keyword

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/api_code.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.cc
- Fixes #8854 
*Optimize dataproxy cpp sdk and improve the stability and performance of sdk*
*Add sdk return code information for dataproxy cpp sdk*
=> [INLONG-8854][SDK] Add return code information for dataproxy cpp sdk

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/ini_help.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/ini_help.h
Prepare a Pull Request
- Fixes #8858 
*Add sdk init helper information to improve the stability and performance of dataproxy cpp  sdk.*
*Add sdk init helper information for inlong dataproxy cpp sdk.*
=> [INLONG-8858][SDK] Add init helper information for dataproxy cpp sdk

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/noncopyable.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/read_write_mutex.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/singleton.h
- Fixes #8861 
*Add mutex utils for dataproxy cpp sdk to improve the stability and performance of dataproxy cpp sdk*
*Add mutex utils for dataproxy cpp sdk.*
=> [INLONG-8861][SDK] Add mutex utils for dataproxy cpp sdk

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/recv_group.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/recv_group.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/recv_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/recv_manager.h
- Fixes #8866 
*Optimize sdk data receiving framework for dataproxy cpp sdk to improve the stability and performance*
*Optimize sdk data receiving framework for dataproxy cpp sdk.*
=> [INLONG-8866][SDK] Optimize data receiving framework for dataproxy cpp sdk

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/send_group.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/send_group.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/send_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/send_manager.h
- Fixes #8868
*Optimize send data framework for dataproxy cpp sdk  to improve the stability and performance of dataproxy cpp sdk*
*Optimize send data framework for dataproxy cpp sdk.*
=> [INLONG-8868][SDK] Optimize send data framework for dataproxy cpp sdk

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/sdk_msg.h
- Fixes #8856 
*Add sdk msg information to improve the stability and performance of dataproxy cpp sdk*
*Add sdk msg information for inlong dataproxy cpp sdk for dataproxy cpp sdk.*
=> [INLONG-8856][SDK] Add msg information for dataproxy cpp sdk

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/client/stat.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/client/tcp_client.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/client/tcp_client.h
- Fixes #8885 
*Optimize tcp manager framework for dataproxy cpp sdk to improve the stability and performance.*
*Optimize tcp manager framework for dataproxy cpp sdk.*
=> [INLONG-8885][SDK] Optimize tcp manager framework for dataproxy cpp sdk 

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/inlong_api.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/api_imp.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/api_imp.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/inlong_api.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/atomic.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/utils.h
- Fixes #8887 
*Optimize api framework for dataproxy cpp sdk to improve the stability and performance.*
*Optimize api framework for dataproxy cpp sdk.*
=> [INLONG-8887][SDK] Optimize api framework for dataproxy cpp sdk

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/CMakeLists.txt, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/sdk_conf.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/client/CMakeLists.txt, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/CMakeLists.txt, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/ini_help.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/CMakeLists.txt, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/utils.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/utils.h
- Fixes #8889 
*Optimize CmakeList for dataproxy cpp sdk to improve the stability and performance*
*Optimize CmakeList for dataproxy cpp sdk.*
=> [INLONG-8889][SDK] Optimize CmakeList for dataproxy cpp sdk

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/hudi/src/main/java/org/apache/inlong/sort/hudi/table/HudiTableInlongFactory.java, inlong-tubemq/tubemq-client-twins/tubemq-client-cpp/example/producer/test_producer.cc
- Fixes #8903
*(example:)*
- If a …
=> [INLONG-8903][TubeMQ] Fix the int64 not recognized by the compiler and Missing @Override annotations

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/send_group.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/capi_constant.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/utils.cc
- Fixes #8910
*Adjust some default configuration parameters such as proxy-num.*
*Adjust some default configuration parameters such as proxy-num.*
=> [INLONG-8910][SDK] Adjust default configuration parameters

inlong-manager/manager-pojo/pom.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/common/PageResult.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/InlongConsumeServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/WorkflowApproverServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/WorkflowEventServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/AbstractSinkOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/tenant/InlongTenantServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/StreamTransformServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/InlongRoleService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/InlongRoleServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/TenantRoleServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/WorkflowServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/user/InlongRoleServiceTest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongRoleController.java
=> [INLONG-8447][Manager] Optimize paging logic

inlong-manager/manager-service/pom.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/hudi/HudiCatalogClient.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sort/SortServiceImplTest.java, inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/Constants.java, inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceMetricData.java, inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/util/CalculateObjectSizeUtils.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/pom.xml, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/FlinkDynamicTableFactory.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/IcebergReadableMetadata.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/IcebergSource.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/IcebergTableSource.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/ArrayBatchRecords.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/ArrayPoolDataIteratorBatcher.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/IcebergSourceReader.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/IcebergSourceRecordEmitter.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/IcebergSourceSplitReader.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/InlongIcebergSourceReaderMetrics.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/MetaDataReaderFunction.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/RecordFactory.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/RowDataReaderFunction.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/RowDataRecordFactory.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/utils/RecyclableJoinedRowData.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/utils/RowDataCloneUtil.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-flink-dependencies/pom.xml, licenses/inlong-sort-connectors/LICENSE, pom.xml
- Fixes #8838
1. IcebergSource support metadata
2. Optimize reusing of RowData
*(example:)*
=> [INLONG-8838][Sort] IcebergSource support metadata

.github/ISSUE_TEMPLATE/bug-report.yml
- Fixes #8874 
Add the 1.9.0 version option for the bug report
=> [INLONG-8874][Release] Add the 1.9.0 version option for the bug report

inlong-audit/audit-store/pom.xml, inlong-manager/manager-dao/pom.xml
- Fixes #8926 
Fix the issue of missing dependencies.
Fix the issue of missing dependencies.
=> [INLONG-8926][Manager] Fix the issue of missing dependencies

inlong-dataproxy/bin/dataproxy-ng
- Fixes #8936 
Append the $JAVA_OPTS parameter when $ENABLE_OBSERVABILITY is false
=> [INLONG-8936][DataProxy] The log's path for DataProxy is wrong

inlong-distribution/src/main/assemblies/sort-connectors-v1.15.xml, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/IcebergSource.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/InlongIcebergSourceReaderMetrics.java
- Fixes #8934
Add Iceberg connectors into the release bundle
*(example:)*
- If a …
=> [INLONG-8934][Distribution] Add Iceberg connectors into the release bundle

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ck/ClickHouseSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/doris/DorisSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hive/HiveSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/postgresql/PostgreSQLSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/starrocks/StarRocksSinkDTO.java
- Fixes #8944 
Fix the issue of not setting encryptVersion.
Fix the issue of not setting encryptVersion.
=> [INLONG-8944][Manager] Fix the issue of not setting encryptVersion

inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/config/Swagger2Config.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongRoleController.java
- Fixes #8965
Update the description for Swagger API, and make the description more accurate.
for https://github.com/apache/inlong-website/pull/863
=> [INLONG-8965][Doc] Update the description for Swagger API

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceMetricData.java, inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/util/CalculateObjectSizeUtils.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/IcebergSource.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/IcebergSourceReader.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/IcebergSourceSplitReader.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/InlongIcebergSourceReaderMetrics.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/RowDataRecordFactory.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/utils/RecyclableJoinedRowData.java
- Fixes #8969 
Optimize Iceberg Source audit report logic
*(example:)*
- If a …
=> [INLONG-8969][Sort] Optimize Iceberg Source audit report logic

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/redis/README.md
- Fixes #8973 
*(example:)*
- If a …
=> [INLONG-8973][Sort] Fix redis connector in flink 1.13 typo

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/AbstractSinkOperator.java
- Fixes #8986 
Fix Sort standalone get params from manager error
The details can be found at [#8986](https://github.com/apache/inlong/issues/8986).
=> [INLONG-8986][Manager] Sort standalone get params from manager error

inlong-dashboard/src/ui/components/GroupLogs/GroupLogs.tsx
- Fixes https://github.com/apache/inlong/issues/8983
=> [INLONG-8983][Dashboard] Log component query optimization

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/NodeFactory.java
- Fixes #8992 
NPE is caused by not using transform.
Add judgment conditions
=> [INLONG-8992][Manager] Fix NPE when using transform

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/config/RedisOptions.java
- Fixes #8979
*(example:)*
- If a …
=> [INLONG-8979][Sort] fix command opt desc

inlong-common/src/main/java/org/apache/inlong/common/enums/MessageWrapType.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/audit/AuditUtils.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/DefaultEventHandler.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/httpMsg/HttpMessageHandler.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/v0msg/AbsV0MsgCodec.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/MessageUtils.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/DeserializeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/DeserializeOperatorFactory.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/InlongMsgDeserializeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/PbMsgDeserializeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/RawMsgDeserializeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/tubemq/TubeMQOperator.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/decode/MessageDeserializer.java
- Fixes #8990 
Rename DataProxyMsgEncType to Message WrapType.
Rename DataProxyMsgEncType to Message WrapType.
=> [INLONG-8990][Manager] Rename DataProxyMsgEncType to Message WrapType

CHANGES.md
- Fixes #8875 
[Release] Update changes log for the 1.9.0 version
=> [INLONG-8875][Release] Update changes log for the 1.9.0 version

inlong-manager/manager-dao/pom.xml, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongStreamEntity.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/base/ExtractNodeProvider.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/KafkaProvider.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/PulsarProvider.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSource.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSource.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamBriefInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamExtParam.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/pulsar/PulsarSourceOperator.java, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.10.0.sql
- Fixes #8988 
Supports multiple wrap types for message body.
Supports multiple wrap types for message body.
=> [INLONG-8988][Manager] Supports multiple wrap types for message body

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/MetaConfigHolder.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/pojo/DataType.java, inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/pojo/IdTopicConfig.java, inlong-manager/manager-dao/pom.xml, inlong-manager/manager-dao/src/main/resources/mappers/ClusterSetMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/dataproxy/InlongStreamId.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamExtParam.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepositoryV2.java
- Fixes #9003
*(example:)*
- If a …
=> [INLONG-9003][DataProxy][Manager] Support extended fields

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/StreamSourceClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/StreamSourceApi.java
- Fixes #9017 
Add stop interface in stream source API.
Add stop interface in stream source API.
=> [INLONG-9017][Manager] Add stop interface in stream source API

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
- Fixes https://github.com/apache/inlong/issues/9013
When reading the source code used by Netty in InLong, my understanding was incorrect due to inconsistent annotations
version-->body_ver
*(example:)* …
=> [INLONG-9013][DataProxy] Inconsistent annotations

inlong-distribution/pom.xml, inlong-sdk/sort-sdk/pom.xml, inlong-sort/pom.xml, pom.xml
- Fixes #9025
the size inlong-distribution binary files are very big, it's better to avoid deploying the distribution packages to repositories.
=> [INLONG-9025][Build] Avoid deploying the distribution packages to repositories

inlong-manager/manager-dao/src/main/resources/mappers/ClusterSetMapper.xml
- Fixes #9027 
Fix SQL error in ClusterSetMapper.selectInlongStreamId.
Fix SQL error in ClusterSetMapper.selectInlongStreamId.
=> [INLONG-9027][Manager] Fix SQL error in ClusterSetMapper.selectInlongStreamId

inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkOperation.java, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/DeleteSortListener.java, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/DeleteStreamListener.java, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/RestartSortListener.java, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/RestartStreamListener.java, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/StartupSortListener.java, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/SuspendSortListener.java, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/SuspendStreamListener.java
- Fixes #9023 
Fix the problem of failed to stop job task.
Fix the problem of failed to stop job task.
=> [INLONG-9023][Manager] Fix the problem of failed to stop job task

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/queue/QueueResourceListener.java
- Fixes #9036
Support create tables for dataSync.
Support create tables for dataSync.
=> [INLONG-9036][Manager] Support create tables for dataSync

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarFederationWorker.java
- Fixes #9038 
Fix failure of parsing InlongMessage when exporting Pulsar
*(example:)* …
=> [INLONG-9038][Sort] Fix failure of parsing InlongMessage when exporting Pulsar

inlong-distribution/src/main/assemblies/sort-connectors-v1.15.xml, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pom.xml, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/pom.xml, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/PulsarTableFactory.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/PulsarTableOptionUtils.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/PulsarTableOptions.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/PulsarTableValidationUtils.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarReadableMetadata.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarRowDataConverter.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableDeserializationSchema.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableDeserializationSchemaFactory.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableSource.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, licenses/inlong-sort-connectors/LICENSE
- Fixes #8695 
Add Pulsar connector based on flink 1.15
Add Pulsar connector based on flink 1.15
Tested on flink1.15 with iceberg sink 
Will add a IT on later pr 
=> [INLONG-8695][Sort] Add Pulsar connector based on flink 1.15
