apache/inlong

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/BatchPackManager.java

fix #7512  
avoid generating a lot of log files
change log level from `info` to `debug`

[INLONG-7512][DataProxy] Change the log level to DEBUG to avoid generating a lot of log files

---

inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java

- Fixes #7646 
When the MQ configuration has not been registered in the manager, Audit obtains the MQ configuration and causes NPE.
If the MQ configuration is not obtained, wait for 5 seconds and retry.

[INLONG-7646][Audit] Fix NPE when mq configuration is not registered

---

inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/OracleExtractSqlParseTest.java

[INLONG-7683][Sort] Fix errors in Oracle UT
- Fixes #7683 
In Flink SQL, the Oracle table should be in the format of `schemaName.tableName`, not just `tableName`. For more details, please refer to the documentation at https://inlong.apache.org/zh-CN/docs/next/data_node/extract_node/oracle-cdc.
Modify `tableName` to `schemaName.tableName`

[INLONG-7683][Sort] Fix errors in Oracle UT

---

inlong-sort/sort-connectors/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/source/meta/split/SourceSplitState.java
inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/source/reader/OracleRecordEmitter.java

[INLONG-7695][Sort] Fix the error of enabling incremental snapshots when Oracle run all database migration job
- Fixes #7695
When running an all database migration job, we need to obtain its `tableSchema`, otherwise a null pointer error will be reported.
Get `tableSchema` from `splitState`.

[INLONG-7695][Sort] Fix NPE when running Oracle all database migration jobs

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/pulsar/PulsarClusterRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/tubemq/TubeClusterRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/DataNodeRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/mysql/MySQLDataNodeRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ck/ClickHouseSinkRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/greenplum/GreenplumSinkRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hive/HiveSinkRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hudi/HudiSinkRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTO.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/oracle/OracleSinkRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/postgresql/PostgreSQLSinkRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/sqlserver/SQLServerSinkRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/starrocks/StarRocksSinkRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/tdsqlpostgresql/TDSQLPostgreSQLSinkRequest.java
inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTOTest.java

- Fixes #7673 
Remove whitespace when saving mysql jdbcUrl to avoid circumventing sensitive parameters.
Prohibit users from adding URLs with spaces.
Remove whitespace when saving mysql jdbcUrl.
Prohibit users from adding URLs with spaces

[INLONG-7673][Manager] Remove whitespace when saving url

---

inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/assigners/MySqlHybridSplitAssigner.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/assigners/MySqlSnapshotSplitAssigner.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/assigners/state/PendingSplitsStateSerializer.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/assigners/state/SnapshotPendingSplitsState.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/split/MySqlSchemalessSnapshotSplit.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/split/MySqlSnapshotSplit.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/split/MySqlSplit.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/split/MySqlSplitSerializer.java
licenses/inlong-sort-connectors/LICENSE

- Fixes #7697 
Reduce the memory usage of JM when split table chunks
See also in https://github.com/ververica/flink-cdc-connectors/pull/1523
Change Split in MySqlSnapshotSplitAssigner to SchemaLessSplit 
Only store one copy of table schema in MySqlSnapshotSplitAssigner
Run Allmigrate Test

[INLONG-7697][Sort] Reduce the memory usage of JM when split table chunks

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupApproveRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/pulsar/InlongPulsarDTO.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/pulsar/InlongPulsarInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/pulsar/InlongPulsarRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java

- Fixes #7733 
Support set the rate limit for the mark-delete operation of pulsar namespace.
If the rate limit for the mark-delete operation of pulsar namespace  is not setted, the ack persistence rate increases, resulting in FGC.
Support set the rate limit for the mark-delete operation of pulsar namespace.

[INLONG-7733][Manager] Support set the rate limit for the mark-delete operation of pulsar namespace

---

inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/DynamicSchemaHandleOperator.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergMultipleStreamWriter.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/RecordWithSchema.java

- Fixes https://github.com/apache/inlong/issues/7715
When mysql synchronizes iceberg, it is found that the dirty data index of the single table dimension is lost.
Since DynamicSchemaHandleOperator also registers the metric index of a single table, it overlaps with the dirty data index in IcebergMultipleStreamWriter, resulting in the loss of the index;
By adding the dirty data flag bit in RecordWithSchema, pass it to IcebergMultipleStreamWriter, count the number of dirty data in IcebergMultipleStreamWriter, and temporarily not count in DynamicSchemaHandleOperator
*(example:)*
- *Extended integration test for recovery after broker …

[INLONG-7715][Sort] Fix single table metric invalid

---

inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/FlinkDynamicTableFactory.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/FlinkSink.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/RateLimitMapFunction.java

- [INLONG-7724][Sort] Add rate limit  to ingest data into iceberg
- Fixes #7724 
In the existing data synchronization, snapshot data and incremental data are send to kafka first, and then streaming write to Iceberg by Flink. Because the direct consumption of snapshot data will lead to problems such as high throughput and serious disorder (writing partition randomly), which will lead to write performance degradation and throughput glitches. It will always crash beacuse memory limit.e.g.
Rate limit
At this time, the write.rate.limit option can be turned on to ensure smooth writing, it will decrese throughput .
*(example:)*
- *Added integration tests for end-to-end …

[INLONG-7724][Sort] Add rate limit  to ingest data into iceberg

---

inlong-tools/dev/inlong-dev-toolkit.sh

[INLONG-7742][Tool] Add only support for MacOS and Linux prompts to inlong-dev-toolkit

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/PulsarSink.java

- Title: [INLONG-7752][Agent] PulsarSink threadPool throw reject exception
- Fixes #7752 
Fix `PulsarSink` threadPool throw reject exception when  delete file data source on dashboard and then add  file data source.
Do not shut down the global thread pool when destroy the `PulsarSink` of one task.

[INLONG-7752][Agent] PulsarSink threadPool throw reject exception

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/es/ElasticsearchSink.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/LoadNodeUtils.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/ElasticsearchLoadNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/ElasticSearchNodeTest.java
inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/MultipleRowElasticsearchSinkFunction.java
inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/table/Elasticsearch6DynamicSink.java
inlong-sort/sort-connectors/elasticsearch-6/src/main/java/org/apache/inlong/sort/elasticsearch6/table/Elasticsearch6DynamicSinkFactory.java
inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/MultipleRowElasticsearchSinkFunction.java
inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7Configuration.java
inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7DynamicSink.java
inlong-sort/sort-connectors/elasticsearch-7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7DynamicSinkFactory.java
inlong-sort/sort-connectors/elasticsearch-base/pom.xml
inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/table/ElasticsearchConfiguration.java
inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/table/ElasticsearchOptions.java
inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/table/MultipleElasticsearchSinkFunctionBase.java
inlong-sort/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/table/TableSchemaFactory.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/ESMultipleSinkTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/ElasticsearchSqlParseTest.java

- Fixes #7581 
Support multiple sink migration for ES sink.
mainly modified multipleElasticRowFunction for 2 key features:
1. support 4 additional options for esloadnode
2. parsing canal-json data
TODO:
1. table-level metric
2. dirty data
4. runtime strategy+other features

[INLONG-7581][Sort] Support multiple-sink migration for Elasticsearch

---

inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlRecordEmitter.java

[INLONG-7762][Sort] Fix capturing unrelated tables when open DDL change detection
- Fixes #7762 
Fix capturing unrelated tables when open DDL change detection
Remove the following code.
```java
// for create table ddl, there's no table change events
// still we need to generate a ddl message
if (tableChanges.isEmpty()) {
outputDdlElement(element, output, splitState, null);
}
```

[INLONG-7762][Sort] Fix capturing unrelated tables when open DDL change detection

---

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlRecordEmitter.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/utils/RecordUtils.java

[INLONG-7787][Sort] Fix cannot output drop statement
- Fixes #7787 
The `tableChanges` of the drop ddl statement is empty, so it cannot enter the `outputDdlElement()` method. We need to check below whether the drop ddl statement belongs to the currently captured table. If so, output the DDL element.
1. Get the ddl statement from `historyRecord` and determine if it is a drop statement.
2. Obtain its `tableId` and query in the state to check if it belongs to the captured tables.
```java
// For drop table ddl, there's no table change events.
if (tableChanges.isEmpty()) {
String ddl = historyRecord.document().getString(Fields.DDL_STATEMENTS);
if (ddl.toUpperCase().startsWith(DDL_OP_DROP)) {
TableId tableId = RecordUtils.getTableId(element);
// If this table is one of the captured tables, …
```

[INLONG-7787][Sort] Fix cannot output drop statement

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/loader/ManagerCacheClusterConfigLoader.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/pojo/CacheClusterConfig.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java

- Fixes #7815
Based on the change of the issue (#7810), when DataProxy initializes the Pulsar client, if the params parameter set in the cluster configuration CacheClusterConfig does not carry authentication information, the authorization information is obtained from the token field

[INLONG-7815][DataProxy] Get authorization information from token field

---

inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlSourceReader.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/utils/TableDiscoveryUtils.java

[INLONG-7790][Sort] Capture newly added tables when setting "scan.newly-added-table.enabled=true" and "scan.startup.mode=latest-offset"
- Fixes #7790 
Capture newly added tables when setting "scan.newly-added-table.enabled=true" and "scan.startup.mode=latest-offset"
When executing the `discoverTableSchemasForBinlogSplit()` method, determine whether to query the schema of newly added tables based on `sourceConfig.isScanNewlyAddedTableEnabled()`.

[INLONG-7790][Sort] Capture newly added tables when setting "scan.newly-added-table.enabled=true" and "scan.startup.mode=latest-offset"

---

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/log/LogDirtySink.java
inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/dirty/RegexReplaceTest.java
inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcBatchingOutputFormat.java
inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingOutputFormat.java
inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/TableMetricStatementExecutor.java

- Fixes #7249 
JDBC needs to archive dirty data. In this pr, I tried to explore to possibility of accurate dirty data archive for jdbc by modifying the executors. The modifications are well-tested and stable in most cases, and in other cases it will give a warning "jdbc enhance failed for class:{}", and won't affect normal code.
Support dirty data accurate archive by using reflection to replace some kinds of executors, and replace the tablesimplestatementexecutor with one that adds metrics.
1.There are 8 total implementations of flink-cdc-executors.
The currently supported sink executor types are:
TableBufferedStatementExecutor
TableBufferReducedStatementExecutor
TableSimpleStatementExecutor
unsupported executor types: (will not archive dirty data, but will not break code) …

[INLONG-7249][Sort] JDBC accurate dirty data archive and metric calculation

---

inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/assigners/MySqlSnapshotSplitAssigner.java

- Fixes #7857 
[INLONG-7857][Sort] Fix duplicated chunk happens when open scan-newly-added-table in mysql-cdc
[INLONG-7857][Sort] Fix duplicated chunk happens when open scan-newly-added-table in mysql-cdc

[INLONG-7857][Sort] Fix duplicated chunk happens when open scan-newly-added-table in mysql-cdc

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/ExcelTool.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java

[INLONG-7843][Manager] Creating the schema of StreamSource by importing an Excel file
- Fixes #7843 
```json
{
"success": true,
"errMsg": null,
"data": [
{
"id": null,
"inlongGroupId": null,
"inlongStreamId": null,
"fieldName": "f1",
"fieldType": "long",
"fieldComment": "f1 field, long value",
"isPredefinedField": null,
"fieldValue": null,
"preExpression": null,
"isMetaField": 0,
"metaFieldName": null,
"fieldFormat": null,
"originNodeName": null,
"originFieldName": null,
"extParams": null
},
{
"id": null,
"inlongGroupId": null,
"inlongStreamId": null,
"fieldName": "f2",
"fieldType": "double",
"fieldComment": "f2 field, double value",
"isPredefinedField": null,
"fieldValue": null,
"preExpression": null,
"isMetaField": 0,
"metaFieldName": null,
"fieldFormat": null,
"originNodeName": null, …
```

[INLONG-7843][Manager] Creating the schema of StreamSource by importing an Excel file

---

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlRecordEmitter.java

[INLONG-7825][Sort] Fix cannot output ddl statement of captured tables
- Fixes #7825 
Some captured table's DDL statements do not have tablechange, but they still need to be ouput downstream.
Remove the restriction of drop and send all DDL statements generated by captured tables downstream.

[INLONG-7825][Sort] Fix cannot output ddl statement of captured tables

---

inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/source/utils/OracleConnectionUtils.java

[INLONG-7858][Sort] Fix Oracle CDC fetch two different db name for the same table
- Fixes #7858 
If the database name configured for Oracle CDC in Flink SQL is lowercase, such as the following example (`'database-name' = 'xe'`), 
```sql
CREATE TABLE products (
ID INT NOT NULL,
NAME STRING,
DESCRIPTION STRING,
WEIGHT DECIMAL(10, 3),
PRIMARY KEY(id) NOT ENFORCED
) WITH (
'connector' = 'oracle-cdc',
'hostname' = 'localhost',
'port' = '1521',
'username' = 'flinkuser',
'password' = 'flinkpw',
'database-name' = 'xe',
'schema-name' = 'FLINKUSER',
'table-name' = 'TEST_03');
```
the following problems will occur:
1. For the same table (`TEST_03`)，the snapshot phase  will use the lowercase database name  (`xe.FLINKUSER.TEST_03 `), and the incremental phase will use the uppercase database name …

[INLONG-7858][Sort] Fix Oracle CDC fetch two different db name for the same table

---

inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/debezium/task/context/StatefulTaskContext.java

[INLONG-7828][Sort] Mysql CDC check the availability of binlog based on gitd firstly
- Fixes #7828 
When connecting to the Mysql master, if the master-slave switch is executed, the binlog file of the master will change, and the task may fail to find the binlog file. 
```
Caused by: java.lang.IllegalStateException: The connector is trying to read binlog starting at Struct{version=1.5.4.Final,connector=mysql,name=mysql_binlog_source,ts_ms=1681704265482,db=,server_id=0,file=mysql-bin.000014,pos=315,row=0}, but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.
at org.apache.inlong.sort.cdc.mysql.debezium.task.context.StatefulTaskContext.loadStartingOffsetState(StatefulTaskContext.java:187) ~[classes/:?]
at …
```

[INLONG-7828][Sort] Mysql CDC check the availability of binlog based on gitd firstly

---

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/AbstractDynamicSchemaFormat.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/CanalJsonDynamicSchemaFormat.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/format/DebeziumJsonDynamicSchemaFormat.java

- Title: [INLONG-7850][Sort] Add support for extracting ddl statement and operation from origin data
- Fixes #7850
Add support for extracting ddl statement and operation from origin data
1. Defines the abstract method with extractDDL  and extractOperation in AbstractDynamicSchemaFormat
2. Implement the abstract method in CanalJsonDynamicSchemaFormat and DebeziumJsonDynamicSchemaFormat

[INLONG-7850][Sort] Add support for extracting ddl statement and operation from origin data

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/ExcelTool.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/validator/ExcelCellValidator.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/tool/excel/validator/NonEmptyCellValidator.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/util/Preconditions.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/StreamFieldTypeCellValidator.java

- Fixes #7867 
```json
{
"success": false,
"errMsg": "Error in Row 3, Column 4:StreamField type must one of [date, string, double, float, int, long, timestamp];\nError in Row 5, Column 1:Value can not be empty!;",
"data": null
}
```

[INLONG-7867][Manager] Support data validation when importing Excel file

---

inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/debezium/task/MySqlBinlogSplitReadTask.java

- Fixes #7855 
Fix Sort hang up reader in snapshot phase when reducing parallelism
1、When a subtask receives two chunk splits to read;
2、The first chunk reads perfectly, and then it will start a BinlogClient to read the binlogs from lw to hw in chunk1. 
3、When the second chunk arrives the BinlogClient will be reused
4、So when reading chunk2 and start to read from lw to hw in chunk2, the binlog reader will be reused and the event listener in chunk1 will be reused also. So that the BINLOG_END event in chunk2 will never be received  
remove the eventListener in the formal chunk 

[INLONG-7855][Sort] Fix Sort hang up reader in snapshot phase when reducing parallelism

---

inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/table/MongoDBTableSource.java
inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/table/MongoDBTableSourceFactory.java

[INLONG-7862][Sort] MongoCDC supports disabling the Changelog Normalize operator
- Fixes #7862 
MongoDB CDC is implemented based on MongoDB's official Change Streams. However, Change Streams lack pre-update messages (-U). In order to convert them to Flink's standard upsert changelog, Flink introduces the Change Normalize operator to transform them into standard changelog, as shown in the figure below:
However, Change Normalize will bring additional computational overhead. When the amount of data is particularly large, this operator will consume performance. Therefore, we may add a parameter to control whether to use the Change Normalize operator.
The impact of turning off the Change Normalize operator is as follows:
1. Advantages: Efficiency improvement for synchronizing large amounts of …

[INLONG-7862][Sort] MongoCDC supports disabling the Changelog Normalize operator

---

inlong-common/pom.xml
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/Utils/ColumnUtils.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/enums/AlterType.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/enums/IndexType.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/enums/OperationType.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/enums/PositionType.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/expressions/AlterColumn.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/expressions/Column.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/expressions/Position.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/indexes/Index.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/operations/AlterOperation.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/operations/CreateTableOperation.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/operations/DropTableOperation.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/operations/Operation.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/operations/RenameTableOperation.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/operations/TruncateTableOperation.java
inlong-sort/sort-connectors/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/debezium/table/RowDataDebeziumDeserializeSchema.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlRecordEmitter.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlReadableMetadata.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/utils/MetaDataUtils.java
inlong-sort/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/utils/OperationUtils.java
inlong-sort/sort-connectors/mysql-cdc/src/test/java/org/apache/inlong/sort/cdc/TestOperation.java
inlong-sort/sort-formats/format-json/pom.xml
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/canal/CanalJson.java
inlong-sort/sort-formats/format-json/src/main/java/org/apache/inlong/sort/formats/json/debezium/DebeziumJson.java
inlong-sort/sort-formats/format-json/src/test/java/org/apache/inlong/sort/formats/json/canal/CanalJsonSerializationTest.java
inlong-sort/sort-formats/format-json/src/test/java/org/apache/inlong/sort/formats/json/canal/DebeziumJsonSerializationTest.java
licenses/inlong-sort-connectors/LICENSE
pom.xml

- Fixes #7660 
With the in-depth use of community users, it is found that for some CDC data source synchronization scenarios, when DDL occurs in upstream data sources, the following pain points often exist:
1 The DDL change of the upstream data source causes task errors and the data cannot be correctly synchronized to the downstream.
2 To synchronize the DDL changes of the upstream data source to the downstream, it is necessary to manually process the DDL change process: task suspension -> downstream processing DDL changes -> task restart, which cost a lot of time 
3 it is often necessary to manually convert the upstream DDL to the DDL supported by the downstream, which requires the person who operates the DDL change to be familiar with both upstream and downstream data sources.
Aiming at …

[INLONG-7660][Sort] Support DDL model for MySQL connector when running in all migrate mode

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/ShiroConfig.java

- Fixes #7883 
Invalidate user session when deleting user.
Invalidate user session when deleting user.

[INLONG-7883][Manager] Invalidate user session when deleting user

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtils.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/TransformNodeUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java

- Fixes #7888 
`fields`  is empty in `StreamSource`.
1. Set `StreamSource.fieldList` from `InlongStream.fieldList`.(If the dashboard supports creating fields directly in the source, it can be ignored)
2. In lightweight mode, `NodeRelation` should get the node name from `source` and `sink`, not `InlongStreamInfo.extParams`.
Creating lightweight tasks also requires dashboard support, it can only be created by modifying the parameters of DB now.

[INLONG-7888][Manager] Fix the empty fields in lightweight task

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/stream/InlongStreamTest.java

[INLONG-7893][Manager] Support field description when parsing field by json
Fixes #7893

[INLONG-7893][Manager] Support field description when parsing field by JSON

---

inlong-sort/sort-connectors/oracle-cdc/pom.xml
inlong-sort/sort-connectors/oracle-cdc/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
inlong-sort/sort-connectors/oracle-cdc/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
licenses/inlong-sort-connectors/LICENSE

[INLONG-7909][Sort] Fix Oracle CDC cannot capture ddl changes
- Fixes #7909 
In debezium 1.6.4-final, the connector user, `SYS`, and `SYSTEM` users are prohibited from querying DDL operations.
```java
/**
* Builds a common SQL fragment used to obtain DDL operations via LogMiner.
*
* @param userName jdbc connection username, should not be {@code null}
* @return predicate that can be used to obtain DDL operations via LogMiner
*/
private static String buildDdlPredicate(String userName) {
final StringBuilder predicate = new StringBuilder(256);
predicate.append("(OPERATION_CODE = 5 ");
predicate.append("AND USERNAME NOT IN ('SYS','SYSTEM','").append(userName.toUpperCase()).append("') ");
predicate.append("AND INFO NOT LIKE 'INTERNAL DDL%' ");
predicate.append("AND (TABLE_NAME IS NULL OR …
```

[INLONG-7909][Sort] Fix Oracle CDC cannot capture ddl changes

---

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/SinkMetricData.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/SourceMetricData.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SinkTableMetricData.java
inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/util/CalculateObjectSizeUtils.java
inlong-sort/sort-connectors/base/src/test/java/org/apache/inlong/sort/base/util/CalculateObjectSizeUtilsTest.java
inlong-sort/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
inlong-sort/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/stream/AbstractStreamingWriter.java
inlong-sort/sort-connectors/hbase/src/main/java/org/apache/inlong/sort/hbase/sink/HBaseSinkFunction.java
inlong-sort/sort-connectors/hive/src/main/java/org/apache/inlong/sort/hive/filesystem/AbstractStreamingWriter.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/DynamicSchemaHandleOperator.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergMultipleStreamWriter.java
inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcBatchingOutputFormat.java
inlong-sort/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/TableMetricStatementExecutor.java

- [INLONG-7906][Sort] Improve logic of calculation object byte size
- Fixes #7906 
* Improve logic of calculation object byte size
* Add `CalculateObjectSizeUtils` to calculate object size
* Modify some connector metric data size computing logic

[INLONG-7906][Sort] Improve logic of calculation object byte size

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/mongodb/MongoDBSourceRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/oracle/OracleSourceRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/postgresql/PostgreSQLSourceRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/sqlserver/SQLServerSourceRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/kafka/KafkaSourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/pulsar/PulsarSourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/tubemq/TubeMQSourceOperator.java

- Fixes #7934 
1. We need to use different data serialization types based on different data sources. For files, various formats such as CSV and JSON can be used, but for MySQL, PostgreSQL, etc., only debezium Json can be used, so it is placed in the `serializationType` of the stream source as a fixed value.
1. If the source does not set the serialization type, it is considered that it can use multiple data types.
2. Set fixed value for source using debezium.

[INLONG-7934][Manager] Optimize the serializationType to support debezium json

---

inlong-common/src/main/java/org/apache/inlong/common/util/MaskDataUtils.java
inlong-common/src/test/java/org/apache/inlong/common/util/MaskDataUtilsTest.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/result/FlinkSqlParseResult.java

[INLONG-7952][Sort] Mask sensitive message of Flink SQL in the logs
- Fixes #7952 
The logs printed in **Inlong** contain password message in Flink SQL, and we hope to replace the password or other sensitive message with * for display.
```sql
4123 [main] INFO  org.apache.inlong.sort.parser.impl.FlinkSqlParser [] - start parse node, node id:1
4131 [main] INFO  org.apache.inlong.sort.parser.impl.FlinkSqlParser [] - node id:1, create table sql:
CREATE TABLE `table_1`(
PRIMARY KEY (`id`) NOT ENFORCED,
`id` INT,
`name` STRING,
`age` INT)
WITH (
'inlong.metric.labels' = 'groupId=1&streamId=1&nodeId=1',
'connector' = 'mysql-cdc-inlong',
'hostname' = 'localhost',
'database-name' = 'test',
'port' = '3306',
'server-id' = '10011',
'scan.incremental.snapshot.enabled' = 'true',
'username' = 'root', …
```

[INLONG-7952][Sort] Mask sensitive message of Flink SQL in the logs

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/AbstractClusterNodeOperator.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceTest.java

- Fixes #7912 
manager only issues normal dataproxy node information.
manager only issues normal dataproxy node information.

[INLONG-7912][Manager] Only issue normal DataProxy nodes

---

inlong-sort/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/table/OracleReadableMetaData.java

[INLONG-7957][Sort] Fix Oracle connector output two data with the same UPDATE operation
- Fixes #7957 
Refer: https://github.com/apache/inlong/pull/7398

[INLONG-7957][Sort] Fix Oracle connector output two data with the same UPDATE operation

---

inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/debezium/DebeziumJson.java
inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/debezium/table/MongoDBConnectorDeserializationSchema.java
inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/source/reader/MongoDBRecordEmitter.java
inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/source/reader/fetch/MongoDBScanFetchTask.java
inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/source/reader/fetch/MongoDBStreamFetchTask.java
inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/source/utils/MetaDataUtils.java
inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/source/utils/MongoUtils.java
inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/table/MongoDBReadableMetadata.java

[INLONG-7958][Sort] Fix MongoDB's schema becomes unordered after extracting the row data
- Fixes #7958 
1. MongoDB's schema becomes unordered after extracting the row data. The sink (e.g. iceberg) automatically builds the table, and the source schema being shuffled during the synchronization process will result in inconsistent schema order between source and sink.
2. For all database migration, Mognodb CDC does not specify a primary key, so **upsert** cannot be implemented. Refer to https://ververica.github.io/flink-cdc-connectors/master/content/connectors/mongodb-cdc.html, we should specify `_id` as the default primary key.
> MongoDB’s change event record doesn’t have updated before message. So, we can only convert it to Flink’s UPSERT changelog stream. An upsert stream requires a unique …

[INLONG-7958][Sort] Fix MongoDB's schema becomes unordered after extracting the row data

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/ExtractNodeUtils.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSource.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSourceDTO.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSourceRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarResourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/pulsar/PulsarSourceOperator.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/PulsarExtractNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/PulsarExtractNodeTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/PulsarSqlParserTest.java

- Fixes #7936 
Support issued pulsar subscriptions to sort.
Support issued pulsar subscriptions to sort.

[INLONG-7936][Manager] Support issued pulsar subscriptions to sort

---

inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/PulsarExtractNodeTest.java
inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/internal/FlinkPulsarSource.java
inlong-sort/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/internal/PulsarMetadataReader.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/PulsarSqlParserTest.java

- Fixes #7940 
[INLONG-7940][Manager] Use pulsar subscriptions and specify subscription offset in pulsar connector
[INLONG-7940][Manager] Use pulsar subscriptions and specify subscription offset in pulsar connector
See SCAN_STARTUP_SUB_START_OFFSET SCAN_STARTUP_SUB_NAME SCAN_STARTUP_MODE in PulsarTableOptions

[INLONG-7940][Sort] Use pulsar subscriptions and specify subscription offset in pulsar connector

---

inlong-sort/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/table/MongoDBReadableMetadata.java

[INLONG-7970][Sort] Fix read metadata filed failed of mongodb cdc
- Fixes #7970 
Sorry, this bug was introduced by this PR https://github.com/apache/inlong/pull/7960.
Wrap a String with StringData.

[INLONG-7970][Sort] Fix read metadata filed failed of mongodb cdc

---

inlong-sort/sort-connectors/base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/partitioner/InLongFixedPartitionPartitioner.java
inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/partitioner/RawDataHashPartitioner.java
inlong-sort/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicTableFactory.java
inlong-sort/sort-connectors/kafka/src/test/java/InLongFixedPartitionPartitionerTest.java
inlong-sort/sort-connectors/kafka/src/test/java/org/apache/inlong/sort/kafka/partitioner/InLongFixedPartitionPartitionerTest.java

- Fixes https://github.com/apache/inlong/issues/7903
Kafka sink supports fixed partition strategy.
1. Added InLongFixedPartitionPartitioner;
2. In RawDataHashPartitioner, it is supported to specify the partition strategy according to the data source; …

[INLONG-7903][Sort] Kafka sink supports fixed partition strategy

---

inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/AllMigrateMongoDBTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/AllMigrateOracleTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/AllMigratePostgreSQLTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/AllMigrateTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/AllMigrateWithSpecifyingFieldTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/ClickHouseSqlParserTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/DorisMultipleSinkTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/ESMultipleSinkTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/FilesystemSqlParserTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/NativeFlinkSqlParserTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/PulsarSqlParserTest.java

[INLONG-8013][Sort] Fix UT failed
- Fixes #8013 
There are two ways to solve it:
1. All test classes need to inherit from `AbstractTestBase`, because `AbstractTestBase` can reuse the same Flink cluster, which can reduce resource usage.
2. Add the `taskmanager.memory.network.min` parameter to limit the memory consumption of the network (the default memory for the network is 64 MB). More details see: https://nightlies.apache.org/flink/flink-docs-release-1.17/docs/deployment/memory/mem_setup_tm/
```java
EnvironmentSettings settings = EnvironmentSettings
.newInstance()
.useBlinkPlanner()
.inStreamingMode()
.build();
Configuration configuration = new Configuration();
// Set …
```

[INLONG-8013][Sort] Fix UT failed caused by OOM

---

inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/GroupedPartitionedDeltaWriter.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/GroupedPartitionedFanoutWriter.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/trick/BaseDeltaTaskWriter.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/trick/BaseTaskWriter.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/trick/CharSequenceSet.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/trick/SortedPosDeleteWriter.java
inlong-sort/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/trick/StructCopy.java

[INLONG-7830][Sort] Using multi-threading to closing files ingesting data into iceberg
- [INLONG-7830][Sort] Using multi-threading to closing files ingesting data into iceberg
- Fixes #7830
Using multi-threading to closing files ingesting data into iceberg

[INLONG-7830][Sort] Using multi-threading to closing files ingesting data into iceberg

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/SortStatusInfo.java

- Fixes #8024
Add extended properties when getting the status of the sort task info
When calling the Inlong-Sort-API  /sort/listStatus ，add other extended parameters when getting the status of the sort task.

[INLONG-8024][Manager] Add extended properties when getting the status of the sort task info

---

CHANGES.md
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java
inlong-manager/manager-web/src/main/resources/application-dev.properties

- Fixes #8035 
Fix Non-file tasks cannot be recovered from the heartbeat timeout state.
Fix Non-file tasks cannot be recovered from the heartbeat timeout state.

[INLONG-8035][Manager] Fix Non-file tasks cannot be recovered from the heartbeat timeout state

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamTransformEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/StreamTransformEntityMapper.xml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/TransformPageRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/StreamTransformService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/StreamTransformServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/transform/StreamTransformServiceTest.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamTransformController.java

- Fixes #8039 
Support pagination query transform
1. Add an interface to get a single transform.
2. Add pagination to the query interface.
3. Modify `GET` to `POST` for the list interface.
manager/service/transform/StreamTransformServiceTest.java

[INLONG-8039][Manager] Optimize the transform interface to support pagination query

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlSourceReader.java

- Fixes #8005 
- Fixes #8005 
see also in https://github.com/ververica/flink-cdc-connectors/issues/1149
remove the duplicate split request when binlog reader hangs up 

[INLONG-8005][Sort] Fix duplicate split request when add new table in mysql connector

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongClientImpl.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupStatusInfo.java

- Fixes #8066
When calling the Inlong-Sort-API, add other extended parameters
Including the extended properties of sort when getting the status info of the inlongGroup.
When calling the Inlong-Sort-API, add other extended parameters
Including the extended properties of sort when getting the status info of the inlongGroup task.

[INLONG-8066][Manager] Add sort extended properties when getting the status info of the InlongGroup

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortClusterServiceImpl.java

- Fixes #8072
Fix NPE when taskName of streamSink is empty or null
Add filter to filter out streamsinks with blank task name and blank datanode name

[INLONG-8072][Manager] Fix NPE when taskName of streamSink is empty or null

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/CommonConfigHolder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/StatConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/SinkContext.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSinkContext.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/kafka/KafkaHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/tube/TubeHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/BaseSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/SourceConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/httpMsg/InLongHttpMsgHandler.java

- Fixes #8084 
1. Summarize the abnormal event statistics function parameters into the common.properties file for configuration;
2. Add abnormal event statistics on the sink side
3. Fix the bug that the proxy and the order-preserving type are not responsed when the message is discarded

[INLONG-8084][DataProxy] Add abnormal event statistics in sink

---

.github/workflows/ci_build.yml
.github/workflows/ci_ut.yml
.github/workflows/codeql_analysis.yml
.idea/vcs.xml

- Fixes #8042 
- Maven http connection reset on GitHub Actions VMs.
- Maven is switching to "Maven Resolver" ("aether") in newer versions instead of using Wagon.
- Disable Maven http connection pooling also for aether
- Set request timeout to 60000ms also for aether
Also, I changed the link to the inlong project in idea/vcs.xml

[INLONG-8042][CI] Update the CI workflow to avoid the network being unreachable

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongTenantEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongTenantEntityMapper.java
inlong-manager/manager-dao/src/main/resources/generatorConfig.xml
inlong-manager/manager-dao/src/main/resources/mappers/InlongTenantEntityMapper.xml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/tenant/TenantInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/tenant/TenantPageRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/tenant/TenantRequest.java
inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/changes-1.8.0.sql

[INLONG-8087][Manager]  Add definition of Inlong tenant table

---

inlong-sort/sort-flink/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/doris/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/elasticsearch-6/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/elasticsearch-7/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/elasticsearch-base/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/filesystem/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/hbase/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/hive/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/hudi/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/jdbc/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/kafka/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/kudu/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mongodb-cdc/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/postgres-cdc/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/pulsar/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/redis/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/sqlserver-cdc/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/starrocks/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/tubemq/pom.xml
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pom.xml
inlong-sort/sort-flink/sort-flink-v1.15/sort-flink-dependencies/pom.xml

- Fixes #8101 
Now the packaging phase of sort connectors only support flink 1.13
If we need the package for flink 1.15 we should change the pom flink version to flink 1.15 which is time consuming.
change the pom. 
to package module flink1.13 and flink1.15 the same time and change the aritifact id to distinguish the two flink versions

[INLONG-8101][Sort] Support multi-version packaging of sort-connectors

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/ComponentHeartbeatEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/ComponentHeartbeatEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java
inlong-manager/manager-web/src/main/resources/application-dev.properties
inlong-manager/manager-web/src/main/resources/application-prod.properties
inlong-manager/manager-web/src/main/resources/application-test.properties

- Fixes #8121 
Supports cluster node status management in the case of multiple manager nodes.
The state management of the cluster nodes in the current manager is achieved through caching.
If the manager has multiple nodes, the cluster node status in the database will be refreshed to `heartbeat timeout` when the cache in any manager becomes invalid.
Therefore, when the cache fails, need to check whether the current cluster node is normal according to whether the current heartbeat information is expired.
Supports cluster node status management in the case of multiple manager nodes.

[INLONG-8121][Manager] Supports cluster node status management in the case of multiple manager nodes

---

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SourceTableMetricData.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/MySqlSourceBuilder.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/config/MySqlSourceConfig.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/config/MySqlSourceConfigFactory.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/reader/MySqlRecordEmitter.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlTableSource.java

- [INLONG-8110][Sort] Only whole database migration need table level metric
- Fixes #8110 
Only whole database migration need table level metric. mysql connector DebeziumSoureFunction is right, but parallel read source is not consistent behavior.
Add judge to report table level metric in MySqlRecordEmitter class

[INLONG-8110][Sort] Only whole database migration need table level metric

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/assigners/MySqlSnapshotSplitAssigner.java

[INLONG-8038][Sort] Optimize MySQL CDC chunk splitting logic
- Fixes #8038 
When the data volume grows rapidly and the snapshot phase takes a long time, the data volume of the last chunk may be very large, leading to OOM. Therefore, it is recommended to read the last chunk first to prevent OOM.
Because these splits are assigned to readers in order, we only need to adjust the order of splits by moving the last split to the front.
```java
// assign splits in order 
Optional<MySqlSplit> split = splitAssigner.getNext();
if (split.isPresent()) {
final MySqlSplit mySqlSplit = split.get();
context.assignSplit(mySqlSplit, nextAwaiting);
awaitingReader.remove();
LOG.info("Assign split {} to subtask {}", mySqlSplit, nextAwaiting);
} else {
// there is no available splits by now, skip assigning …
```

[INLONG-8038][Sort] Optimize MySQL CDC chunk splitting

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/SourcePageRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java

- Fixes #8152 
Paging queries remove the restriction that group id is not empty.
Paging queries remove the restriction that group id is not empty.

[INLONG-8152][Manager] Paging queries remove the restriction that group id is not empty

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java

- Fixes #8150 
this method throw too much exceptions when group is not found or deleted
return emtpy list when group is not found or deleted
*(example:)* …

[INLONG-8150][Manager] Not throw an exception when getting the cluster nodes

---

inlong-common/src/main/java/org/apache/inlong/common/util/BasicAuth.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/InlongManagerMain.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/filter/EmptyTenantFilter.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/filter/HttpServletRequestFilter.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/filter/WebFilterConfig.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/utils/InlongRequestWrapper.java
inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/filter/EmptyTenantFilterTest.java

- Fixes #8169 
To support multi-tenancy https://github.com/apache/inlong/issues/7914, all requests need to carry tenant fields in header.
To be compitable with old version, if the requst does not, use "public" tenant.
*(example:)*
- If yes, how is …

[INLONG-8169][Manager] Add default tenant "public" if the request does not specify

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/schema/IcebergSchemaChangeHelper.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/DynamicSchemaHandleOperator.java

- Fixes https://github.com/apache/inlong/issues/8173
When Column#position may be null, the doAddColumn method may throw NPE:
https://github.com/apache/inlong/blob/a38bab22169a06010c54b0d27ed3b40656c667e6/inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/schema/IcebergSchemaChangeHelper.java#L134-L136
When Column#position is null, append to the last column by default.
*(example:)*
- *Added integration tests for end-to-end …

[INLONG-8173][Sort] Fix the NPE problem when adding new columns

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/filesystem/src/main/java/org/apache/inlong/sort/filesystem/stream/AbstractStreamingWriter.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/TableMetricStatementExecutor.java

- [INLONG-8177][Sort] Improve jdbc connector object calculation and fix filesystem connector report dirty data metrics error
- Fixes #8177 
* Improve jdbc connector object calculation
* Fix filesystem connector report dirty data metrics error
* Modify jdbc connector object calculation
* Modify filesystem connector dirty data metrics report
*(example:)*
- If a …

[INLONG-8177][Sort] Improve jdbc connector object calculation and fix filesystem connector report dirty data metrics error

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/AuditClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/ClientFactory.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/AuditApi.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/audit/AuditRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java

- Fixes #8188 
1.Support querying audit information by sink id.
2.Add `auditClient`.
1.Support querying audit information by sink id.
2.Add `auditClient`.

[INLONG-8188][Manager] Support querying audit information by sink id

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/MetaConfigHolder.java

- Fixes #8192 
1. Adjust the Topic construction method of Kafka;
2. Check the validity of the namespace field, which must exist and not be empty;
3. Remove unnecessary log output

[INLONG-8192][DataProxy] The topic name generated by dataproxy is incorrect

---

inlong-common/src/main/java/org/apache/inlong/common/enums/DataProxyErrCode.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/HttpAttrConst.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/StatConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/heartbeat/HeartbeatManager.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/audit/AuditUtils.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/tube/TubeHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/BaseSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/InLongMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/SimpleHttpSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/SimpleTcpSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/httpMsg/InLongHttpMsgHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/v0msg/CodecBinMsg.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/v0msg/CodecTextMsg.java

- Fixes #8212 
1. Adjust the implementation of InLongHttpMsgHandler, use QueryStringDecoder to parse the fields in the request; add content data processing of POST requests; adjust abnormal IP inspection processing, and gather HTTP-related constants in the same file
2. Adjust the name of HTTP-related indicator statistics Key;
3. Adjust the log output level, delete the information that does not need to be printed frequently,
4. Other detailed revisions

[INLONG-8212][DataProxy] Improve HTTP related message handling

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/threads/MetricWorkerThread.java

*[INLONG-8215][DataProxySDK] thread leak after sdk shut down*
- Fixes #8215
*io threads were not shut down after sdk shut down, cause threads leaking*
*shut down the io threads and metrics threads when the sdk shut down*
*(example:)*

[INLONG-8215][SDK] Fix thread leak bug for DataProxy

---

inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/source/ServerMessageHandler.java

- [INLONG-8224][Audit] Fix audit-proxy memory leak
- Fixes #8224
*Fix the problem of netty memory leak.*
*When the use of ByteBuf is completed, release it in time to prevent the memory from being released.*

[INLONG-8224][Audit] Fix audit-proxy memory leak

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CommonConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/PackProxyMessage.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskPositionManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/KafkaSink.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/PulsarSink.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/FileReaderOperator.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/MonitorTextFile.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestTextFileReader.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/TestTextFileTask.java

[INLONG-8180][Agent] improve the efficiency and safety for log file reading
- Fixes #8180 
*case the agent oom when it meets one line that was 1G long；the agent take most cpu just to read the file*
*1、limit the length of one time reading，avoid oom
2、read multi lines one time to reduce io*
*(example:)* …

[INLONG-8180][Agent] Improve the efficiency and safety of log file reading

---

inlong-common/src/main/java/org/apache/inlong/common/enums/DataProxyErrCode.java
inlong-dataproxy/conf/log4j2.xml
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/channel/FailoverChannelProcessor.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/CommonConfigHolder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/StatConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/exception/MainChannelFullException.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/stats/AbsStatsDaemon.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/stats/MonitorIndex.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/stats/MonitorStats.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/BaseSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/InLongMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/SimpleHttpSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/SimpleTcpSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/SimpleUdpSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/SourceConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/httpMsg/InLongHttpMsgHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/v0msg/AbsV0MsgCodec.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/v0msg/CodecBinMsg.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/v0msg/CodecTextMsg.java

- Fixes #8228
1. Add MonitorIndex and MonitorStats classes, adjust statistics and output methods;
2. Add detailed indicator processing logic and API;
3. Refine the key of the error indicator, and distinguish different error scenarios according to the indicator key
4. Add SO_BACKLOG, SO_REUSEADDR, SO_LINGER parameter settings for netty;
5. Other optimization and modification

[INLONG-8228][DataProxy] Optimize the implementation of the index output to files

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/CommonConfigHolder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/StatConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/TubeUtils.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/BatchPackManager.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/BatchPackProfile.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSinkContext.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/PackProfile.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/SimplePackProfile.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/kafka/KafkaHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/tube/TubeHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/InLongMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/httpMsg/InLongHttpMsgHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/v0msg/CodecBinMsg.java
inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/config/holder/TestCommonConfigHolder.java
inlong-dataproxy/dataproxy-source/src/test/resources/common.properties

- Fixes #8267
1. Add the control of whether to retry the message sending failure and the maximum number of retries;
2. Adjust the index output when message outputting to MQ;
3. Add documentation comments and minor adjustments

[INLONG-8267][DataProxy] Add the control of whether to retry and the count of retries for the failure message

---

inlong-common/src/main/java/org/apache/inlong/common/enums/DataProxyMsgEncType.java
inlong-common/src/main/java/org/apache/inlong/common/enums/DataProxyMsgEncVer.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/http/SimpleMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/audit/AuditUtils.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/DefaultEventHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/TubeUtils.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/BatchPackManager.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSinkContext.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/SimplePackProfile.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/kafka/KafkaHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/tube/TubeHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SimpleMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/httpMsg/InLongHttpMsgHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/v0msg/AbsV0MsgCodec.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/MessageUtils.java
inlong-sdk/sdk-common/src/main/java/org/apache/inlong/sdk/commons/protocol/EventConstants.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/decode/MessageDeserializer.java

- Fixes #8284 
1. Define a new class DataProxyMsgEncVer, whose value completely covers EventConstants.HEADER_KEY_VERSION and is consistent;
2. Add parallel processing to the places involving EventConstants.HEADER_KEY_VERSION and ConfigConstants.MSG_ENCODE_VER;
3. Adjust the implementation of MessageDeserializer, and use the DataProxyMsgEncVer enumeration value for judgment;
4. Optimize the SimplePackProfile class event to add the attribute value set of MQ message, which only contains necessary fields;
5. Other small optimization measures

[INLONG-8284][DataProxy] Unify the message encoding definition of DataProxy

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerServiceServer.java

- Fixes #8286
Add the "attr" field to the return result of the admin_snapshot_message method to carry the attribute information of the Message

[INLONG-8286][TubeMQ] Supports the return package type when querying messages

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/SinkContext.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/BatchPackManager.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/BatchPackProfileCallback.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueClusterProducer.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneProducer.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSinkContext.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneWorker.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/PackProfile.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/RandomCacheClusterSelector.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/SimplePackProfile.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/kafka/KafkaHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/tube/TubeHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/v1msg/InlongTcpSourceCallback.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/BufferQueue.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/SizeSemaphore.java

- Fixes #8294
Modifications:
1. Adjust the scope of the log object in the class from Public to private or protected;
2. Modify the log output content, add the Sink object name, and additional prompt information to facilitate the location and search of problem logs
3. Adjust the reference and operation of the dispatchQueue object, concentrate the object in the MessageQueueZoneSink class and encapsulate it with functions to avoid missing operations;
4. Remove the unused reloadTimer implementation in the SinkContext class;
5. Adjust the variable settings of related classes and add parameter setting instructions according to the IDE prompts

[INLONG-8294][DataProxy] Optimize the log output in the Sink module

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/heartbeat/HeartbeatManager.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/BaseSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/HttpUtils.java

- Fixes #8305
Modifications:
1. Construct the HttpPost object creation method getHttPost() in the HttpUtils class;
2. Replace the implementation of creating HttpPost objects in the HeartbeatManager and ConfigManager classes;
3. Add log output printing in BaseSource

[INLONG-8305][DataProxy] Optimize HttpPost object creation

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/fieldtype/strategy/MySQLFieldTypeStrategy.java
inlong-manager/manager-common/src/main/resources/mysql-field-type-mapping.yaml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/MySQLBinlogProvider.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/MySQLProvider.java
inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtilsTest.java

[INLONG-8288][Manager] Add MySQL field type mapping strategy to improve usability
- Fixes #8288
Inlong Mysql ExtractNode or LoadNode currently does not support some special field types, add MySQL field type mapping strategy to mapping to the corresponding type to run correctly

[INLONG-8288][Manager] Add MySQL field type mapping strategy to improve usability

---

licenses/inlong-agent/LICENSE
licenses/inlong-audit/LICENSE
licenses/inlong-dataproxy/LICENSE
licenses/inlong-manager/LICENSE
licenses/inlong-sort-connectors/LICENSE
licenses/inlong-sort-standalone/LICENSE
licenses/inlong-sort/LICENSE
pom.xml

-INLONG-8309][Other]Upgrade org.xerial.snappy:snappy-java from version 1.1.8.4 to version 1.1.10.1
- Fixes #8309 
*Upgrade org.xerial.snappy:snappy-java from version 1.1.8.4 to version 1.1.10.1*

[INLONG-8309][CVE] Upgrade snappy-java from version 1.1.8.4 to version 1.1.10.1

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/channel/FailoverChannelProcessor.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/pojo/IdTopicConfig.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/StatConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSink.java
inlong-sdk/sdk-common/src/main/java/org/apache/inlong/sdk/commons/protocol/ProxyEvent.java

- Fixes #8311
1. Add the processing logic for FlumeEvent type events in MessageQueueZoneSink.process();
2. Add the processing logic of ProxyPackEvent in FailoverChannelProcessor
3. Add data statistics indicators and adjust some log output

[INLONG-8311][DataProxy] Add event handling support for FlumeEvent type

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/io/debezium/connector/mysql/GtidUtils.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/debezium/task/context/StatefulTaskContext.java
licenses/inlong-sort-connectors/LICENSE

[INLONG-8307][Sort] Fix job restart failed from savepoint When set 'scan.startup.mode' = 'timestamp|earliest-offset|specific-offset'
- Fixes #8307 
When set 'scan.startup.mode' = 'timestamp|earliest-offset|specific-offset', it will assign an incorrect GTID, when restart from Savepoint, the incorrect GTID will lead failure of the job. We should adjusted GTID to ensure the completeness. More details refer for: https://github.com/ververica/flink-cdc-connectors/pull/2220.
1. Adjust GTID in the MySqlOffsetContext.
2. Adjust GTID merging logic to support recovering from job which previously specifying starting offset on start.

[INLONG-8307][Sort] Fix job restart failed from savepoint When set 'scan.startup.mode' = 'timestamp|earliest-offset|specific-offset'

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/StatConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneProducer.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/v0msg/CodecBinMsg.java

- Fixes #8318
1. Adjust the synchronization mechanism for metadata changes of the MessageQueueZoneSink class
2. Add log output, fix bug

[INLONG-8318][DataProxy] Change notification synchronization through condition variables and locks

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/DataNodeType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/fieldtype/strategy/OracleFieldTypeStrategy.java
inlong-manager/manager-common/src/main/resources/oracle-field-type-mapping.yaml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/OracleProvider.java
inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtilsTest.java

[INLONG-8313][Manager] Add Oracle field type mapping strategy to improve usability
- Fixes #8313
Inlong Oracle ExtractNode or LoadNode currently does not support some special field types, add Oracle field type mapping strategy to mapping to the corresponding type to run correctly

[INLONG-8313][Manager] Add Oracle field type mapping strategy to improve usability

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/SimplePackProfile.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/kafka/KafkaHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/tube/TubeHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/InLongMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source2/v0msg/AbsV0MsgCodec.java

- Fixes #8323
1. Add the corresponding Topic output when the Producer is null;
2. Add attribute information to the return message to facilitate error location

[INLONG-8323][DataProxy] Add Topic detailed information output when Producer is null

---

inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/BaseMessageConsumer.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/consumer/SimpleClientBalanceConsumer.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/producer/ProducerManager.java

- Fixes #8321
1. replace milliseconds with nanoseconds;
2. add random numbers;

[INLONG-8321][TubeMQ] Improve the precision of tube consumer id

---

inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/TestTextFileTask.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/trigger/TestTriggerManager.java

- Fixes #8334
If the agent's UT fails, it will block the entire job and needs to be optimized,so it need to optimize the agent UT.
Optimize the file collection UT code  to improve PR pass rate.

[INLONG-8334][Agent] Optimize agent UT of agent to avoid failed

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/utils/MetaDataUtils.java

- Fixes #8341
When MySQL table has decimal(38,10) field, MySQL cdc connector only sends precision 38, but scale 10 is lost.
Refer to `getOracleType` method from [Oracle cdc connector](https://github.com/apache/inlong/blob/b73455a34729d416ee76d0ec22cb6857f5d15ea3/inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/table/OracleReadableMetaData.java#L456C38-L456C38) , MySQL cdc connector …

[INLONG-8341][Sort] MySQL cdc connector can get scale for decimal field

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/DataNodeType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/fieldtype/strategy/SQLServerFieldTypeStrategy.java
inlong-manager/manager-common/src/main/resources/sqlserver-field-type-mapping.yaml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/SQLServerProvider.java
inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtilsTest.java

[INLONG-8327][Manager] Add SQLServer field type mapping strategy to improve usability
- Fixes #8327
Inlong SQLServer ExtractNode or LoadNode currently does not support some special field types, add SQLServer field type mapping strategy to mapping to the corresponding type to run correctly

[INLONG-8327][Manager] Add SQLServer field type mapping strategy to improve usability

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/SimplePackProfile.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/v0msg/CodecBinMsg.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/v0msg/CodecTextMsg.java

- Fixes #8368
1. Align message pack construction time
2. Align message length setting
3. Align and construct the necessary field values carried by the MQ message

[INLONG-8368][DataProxy] Sink does not have audit data

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/debezium/reader/SnapshotSplitReader.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/debezium/task/MySqlSnapshotSplitReadTask.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/MySqlSource.java

- [INLONG-8363][Sort] MySQL connector supports to discard tables without capturing in snapshot phase
- Fixes #8363
MySQL connector captures binlog in snapshot phase all the time even if tables have been removed in flink sql.
For example, flink sql has captured table1, table2 and table3. Table1 has large scale data. MySQL connector chunk splitter is splitting table1 into many chunks, and reading binlog file by sequence. It will take a lot of time to finish reading table1.
If we don't want to capture table1 and remove it from flink sql, we pause the flink job with checkpoint, then start the job again. Even if table1 don't exist in flink sql, MySQL connector still captures table1, as flink job restores states from last checkpoint and table1 is still in checkpoint.
Maybe we need to do …

[INLONG-8363][Sort] MySQL connector supports to discard tables without capturing in snapshot phase

---

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/MetricData.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceMetricData.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/sub/SourceTableMetricData.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/metrics/MySqlSourceReaderMetrics.java

- [INLONG-8372][Sort] MySQL connector supports uploading flink job delay metrics
- Fixes #8372
Now mysql cdc connector has two [delay metrics](https://github.com/ververica/flink-cdc-connectors/blob/ba5fcbc97b46bbe57a2937622afa1562885beed8/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/metrics/MySqlSourceReaderMetrics.java#L52C36-L52C36): `currentFetchEventTimeLag` and `currentEmitEventTimeLag`. 
We could know if mysql cdc connector can follow MySQL binlog in time by this two metrics. The higher values ,the delay is severer.
Inlong metrics don't contain these now.
1. `MetricData` has `registerGauge` method which is used for registering a gauge metric.
2. `SourceMetricData` has two new `Gauge` parameters: `currentFetchEventTimeLag` and …

[INLONG-8372][Sort] MySQL connector supports uploading flink job delay metrics

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/operations/Operation.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/ddl/operations/UnsupportedOperation.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/utils/OperationUtils.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/test/java/org/apache/inlong/sort/cdc/TestOperation.java

- Fixes #8382
Provide unsupported operation for ddl that is not parseable
Provide unsupported operation for ddl that is not parseable
Run TestOperation testUnsupportedOperation()

[INLONG-8382][Sort] Provide unsupported operation for ddl that is not parseable

---

.github/workflows/ci_ut_flink15.yml
inlong-sort/sort-core/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mongodb-cdc/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/postgres-cdc/pom.xml

Fix the artifactId of the dependency of sort-format-json is wrong.
- Fixes #8411 

[INLONG-8411][Sort] Fix the artifactId of the dependency of sort-format-json is wrong

---

inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/auth/openapi/OpenAPIFilter.java

- Fixes #8421 
To fix null point exception when disable OpenApi auth.
Fix the condition error.
- Does this pull request introduce a new feature?  no

[INLONG-8421][Manager] Fix NPE when disable OpenApi auth

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/demo/send_demo.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/base/sdk_constant.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/socket_connection.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/net/socket_connection.h

- Fixes #8409
*When reporting data to DataProxy through dataproxy-sdk-cpp, after DataProxy returns an error, dataproxy-sdk-cpp still counts successfully*
*According to the latest dp return packet protocol, the errorcode is analyzed and judged.*

[INLONG-8409][SDK] Data sending fails but dataproxy-sdk-cpp returns success

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/HttpClientExample.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/TcpClientExample.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/HttpProxySender.java

- Fixes #7766
1. Based on the modification requirements of [a], when initializing the sending objects DefaultMessageSender and HttpProxySender, it is mandatory to add the corresponding protocol type setting call;
2. Set the protocol type explicitly in the example
a. #6190

[INLONG-7766][SDK] Adjusted frame length exceeds occurred when reporting data through the HTTP protocol

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/source/OracleDialect.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/source/reader/fetch/OracleSourceFetchTaskContext.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/source/utils/OracleConnectionUtils.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/source/utils/OracleUtils.java

[INLONG-7882][Sort] Oracle CDC reduces the number of session connections
- Fixes #7882 
Oracle CDC reduces the number of session connections. 
We use oracle connection in context for each reader subtask, Instead of creating a new oracle connection every time.
Use oracle connection in context for each reader subtask.
```java
public void configure(SourceSplitBase sourceSplitBase) {
/**...**/       
this.databaseSchema = OracleUtils.createOracleDatabaseSchema(connectorConfig, connection);
/**...**/
}
```

[INLONG-7882][Sort] Oracle CDC reduces the number of session connections

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/debezium/table/MongoDBConnectorDeserializationSchema.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/debezium/utils/RecordUtils.java

[INLONG-8407][Sort] Optimize mongodb cdc to obtain documentKey
- Fixes #8407 
The ddl operation of mongodb does not have a documentKey, so we do not need to check whether it is null. We may be able to check whether it is null later.
1. Remove the check that record is DML.
2. Remove the check on whether the documentKey is null.

[INLONG-8407][Sort] Optimize mongodb cdc to obtain documentKey

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/fieldtype/strategy/ClickHouseFieldTypeStrategy.java
inlong-manager/manager-common/src/main/resources/clickhouse-field-type-mapping.yaml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/ClickHouseProvider.java
inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtilsTest.java

[INLONG-8443][Manager] Add ClickHouse field type mapping strategy to improve usability
- Fixes #8443
Inlong ClickHouse ExtractNode or LoadNode currently does not support some special field types, add ClickHouse field type mapping strategy to mapping to the corresponding type to run correctly

[INLONG-8443][Manager] Add ClickHouse field type mapping strategy to improve usability

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/PackProfile.java

- Fixes #8459
Adjust the type of count and size fields from int to long

[INLONG-8459][DataProxy] Fix code scanning alert - Implicit narrowing conversion in compound assignment

---

inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupApproveRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupRequest.java

- Fixes #8462 
Fix attribute was overwritten by the default value error when modifying the group.
Fix attribute was overwritten by the default value error when modifying the group.

[INLONG-8462][Manager] Fix attribute was overwritten by the default value error when modifying the group

---

.github/workflows/ci_ut_flink15.yml
inlong-sort/sort-core/pom.xml
inlong-sort/sort-formats/format-json-v1.15/pom.xml
inlong-sort/sort-formats/format-json-v1.15/src/main/java/org/apache/inlong/sort/formats/json/utils/FormatJsonUtil.java
inlong-sort/sort-formats/pom.xml

- Fixes #8481
Fix unit test for sort-core in flink-1.15
1\
change the test code to 
mvn --update-snapshots -e -V clean test -am -pl inlong-sort/sort-core -DfailIfNoTests=false -Pv1.15
when using -pl to specify a module, we should use -am to compile the related modules 
Also should specify the profile
2\
sort-core test on flink 1.15 do not have most connectors for flink1.15 so the connectors parser tests should be removed
3\
for flink 1.15 guava version should be 
30.1.x
--
<br class="Apple-interchange-newline">
run test

[INLONG-8481][Sort] Fix unit test for sort-core in flink-1.15

---

inlong-sort-standalone/pom.xml
inlong-sort/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/hive/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/hudi/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/pom.xml
pom.xml

*[INLONG-8474][CVE] Unify the version of "hive-exec"*
- Fixes #8474 
1, unify hive2.x 2.3.7
2, unify hive3. 3.1.3

[INLONG-8474][CVE] Unify the version of "hive-exec"

---

inlong-dashboard/src/ui/pages/GroupDetail/DataStream/PreviewModal.tsx

- Fixes #8500 
`/stream/queryMessage` -> `/stream/listMessage`

[INLONG-8500][Dashboard] Fix stream data preview url error

---

inlong-manager/manager-dao/src/main/resources/mappers/AuditEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java

*[INLONG-8490][Manager] Duplicate queried audit data according to all fields*
- Fixes #8490 
*Network problems may lead to repeated transmission of audit data. At present, the data found by audit is only queried according to several query conditions, and then the total_count and total_delay are counted according to log_ts. However, there may be duplicate data in the found data, which will cause the total_count and total_delay to be greater than the true value.*
*When querying "clickhouse" and "mysql", duplicate sentences were added. This deduplication operation is based on all fields of audit_data. Therefore, we can ensure that the queried audit data is not repeated, and that the total_count and total_delay of statistics are correct.*

[INLONG-8490][Manager] Duplicate queried audit data according to all fields

---

inlong-agent/agent-docker/Dockerfile
inlong-agent/bin/agent-env.sh

- [INLONG-8146][Agent] add -XX:NativeMemoryTracking in agent-env.sh
- Fixes #8146 
Add this params, we can use 'jcmd <PID> VM.native_memory summary' to analyze Off-Heap Memory
*(example:)*

[INLONG-8146][Agent] Add -XX:NativeMemoryTracking in agent-env.sh

---

inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/AgentServiceTest.java

- [INLONG-8509][Manager] Optimize preProcessTemplateFileTask in AgentServiceImpl
- Fixes #8509 
In old method, the program will init many stream sources with status 104(Frozen), which will make many dirty records in mysql
Check if node is compile with template stream source when init  sub stream source
*(example:)* …

[INLONG-8509][Manager] Optimize preProcessTemplateFileTask in AgentServiceImpl

---

docker/build-docker-images.sh

- Fixes #8543 
The path of the mysql connector is wrong when docker build
`../mysql/..` to `../mysql-cdc/..`

[INLONG-8543][Docker] Fix mysql connector path error when docker build

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/DorisLoadNode.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtyOptions.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/format/JsonDynamicSchemaFormat.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/doris/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/http/HttpGetEntity.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/schema/OperationHelper.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/schema/SchemaChangeHelper.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicSchemaOutputFormat.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicTableFactory.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/table/DorisDynamicTableSink.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/doris/src/test/java/org/apache/inlong/sort/doris/schema/OperationHelperTest.java

- Title: [INLONG-7763][Sort] Support ddl change for doris
- Fixes #7763 
Support ddl change for doris, you can select schema change policy for every schema change type according the  `SchemaChangeType` and `SchemaChangePolicy`  from PR(https://github.com/apache/inlong/pull/8105), the example as follows:
```
CREATE TABLE `table_1`(
`raw` STRING METADATA FROM 'meta.data_canal' VIRTUAL)
WITH (
'include-schema-change' = 'true',
'inlong.metric.labels' = 'groupId=1&streamId=1&nodeId=1',
'server-time-zone' = 'Asia/Shanghai',
'migrate-all' = 'true',
'connector' = 'mysql-cdc-inlong',
'hostname' = 'localhost',
'database-name' = …
```

[INLONG-7763][Sort] Support ddl change for doris

---

inlong-sort/sort-end-to-end-tests/pom.xml

- Fixes #8549
Fix incorrect use of maven plugin on integration test among sort-end-to-end-tests
The end-to-end-test use Maven Surefire Plugin to control interation test
However in maven doc https://maven.apache.org/surefire/maven-failsafe-plugin/index.html, maven-failsafe-plugin is the right way to control integration test
Surefire plugin is used for unit test and cannot be applied to --DskipITs=true
use maven-failsafe-plugin for sort-end-to-end-tests

[INLONG-8549][Sort] Fix incorrect use of maven plugin on integration test among sort-end-to-end-tests

---

inlong-manager/manager-plugins/base/src/main/assembly/assembly.xml
inlong-manager/manager-web/assembly.xml

- Fixes #8556 
The jar packages of manager-plugin-flink1.13 and manager-plugin-flink1.15 cannot exist at the same time when inlong-manager is running.
- Remove manager-plugins-flink-v1.13.jar and manager-plugins-flink-v1.15.jar from the inlong-manager lib directory.
- Add manager-plugins-flink-v1.13.jar to the inlong-manager/plugins/flink-v1.13 directory.
- Add manager-plugins-flink-v1.15.jar to the inlong-manager/plugins/flink-v1.15 directory.

[INLONG-8556][Manager] Optimize the location of the manager-plugins-flink jar package

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/StatConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java

- Fixes #8576
1. Adjust handling when messages are incomplete;
2. Add the indicator statistics of getting messages from Channel

[INLONG-8576][DataProxy] Adjust handling when messages are incomplete

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/metrics/MySqlSourceReaderMetrics.java

- Fixes #8578
Fix npe inside outputReadPhaseMetrics in mysql-cdc
NPE happens when we do not provide metric labels
should check for metricdata before call method 
run allmigrate test

[INLONG-8578][Sort] Fix npe inside outputReadPhaseMetrics in mysql-cdc

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/source/utils/OracleConnectionUtils.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/table/OracleTableSourceFactory.java

[INLONG-8558][Sort] Use database name in upper case at the OracleTableSourceFactory
- Fixes #8558 
In the incremental phase, **debezium** has use the uppercase database name, so I believe it is necessary to also do so in the snapshot phase. More details refer for https://github.com/apache/inlong/pull/7865.
Now, I think maybe we should use database name in upper case at the beginning. For example, in the constructor of the Source(OracleTableSourceFactory).
In the constructor of the Oracle Source(OracleTableSourceFactory), convert the database name to uppercase.

[INLONG-8558][Sort] Use database name in upper case at the OracleTableSourceFactory

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/HttpAttrConst.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/httpMsg/HttpMessageHandler.java

- Fixes #8589
Add the processing of "callback=xxx" parameter in HTTP access request

[INLONG-8589][DataProxy] Add callback parameter support for Http access

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/cdc/mongodb/source/reader/fetch/MongoDBFetchTaskContext.java

[INLONG-8594][Sort] Fix SourceRecord range check of MongoDB CDC
- Fixes #8594 
When change record is chunk range of snapshot phase, MongoDB cannot output the record. The method `MongoDBFetchTaskContext#isRecordBetween` is not work.
Fix `MongoDBFetchTaskContext#isRecordBetween` checking function.

[INLONG-8594][Sort] Fix SourceRecord range check of MongoDB CDC

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/ConfigConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/stats/MonitorIndex.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/SinkContext.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/TubeUtils.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSinkContext.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/SimplePackProfile.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/kafka/KafkaHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/tube/TubeHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/BaseSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/httpMsg/HttpMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/v0msg/AbsV0MsgCodec.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/v0msg/CodecBinMsg.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/v0msg/CodecTextMsg.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/DateTimeUtils.java

- Fixes #8597
1. Adjust the output format of the index.log indicator, add version information, and separate keys and values with "=", and adjust the output position of some fields;
2. For the output indicators on the Sink side, add groupId, streamId information, and dt time;
3. Optimize and adjust the implementation logic of the indicator output function on the Source and Sink sides
4. Add sending time information to the message sent to MQ

[INLONG-8597][DataProxy] Adjust the format of the metric output to the file

---

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/IcebergTableSink.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/schema/IcebergModeSwitchHelper.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/schema/RowDataConverter.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/FlinkSink.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/RowDataTaskWriterFactory.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/DynamicSchemaHandleOperator.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergMultipleStreamWriter.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergSingleFileCommiter.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergSingleStreamWriter.java

- Fixes #8596 
There are some minor errors in https://github.com/apache/inlong/pull/8238
1、the cache write result should be cleared after emitting
2、the streaming task should work in append mode when switch enabled
3、the writing data should not be binaryRowdata but be GenericRowdata, this can be done using a rowdataConverter
1、cache write result be cleared after emitting
2、the streaming task work in append mode when switch enabled
3、use a rowdataConverter to convert binaryData to GenericRowdata

[INLONG-8596][Sort] Fix bugs and reformat code in Iceberg dynamic switching between append and upsert

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/debezium/table/RowDataDebeziumDeserializeSchema.java

[INLONG-8601][Sort] Fix NPE in schema.name of Oracle CDC
- Fixes #8601 
Some data types have a null `schema.name`, such as INT64, so we need to check whether `schema.name` is null to avoid 
NPE.
Check whether `schema.name` is nul.

[INLONG-8601][Sort] Fix NPE in schema.name of Oracle CDC

---

inlong-sort/sort-core/pom.xml

[INLONG-8279][Sort] Fix NPE when run MySqlLoadSqlParseTest
- Fixes #8279
After filling in the real database connection parameters in `MySqlLoadSqlParseTest#testMySqlLoadSqlParse()`, running the UT occurs NPE. According to the source code, the **debezium-ddl-parser** fails to parse the `varchar(255)` type.
However, when running the MySQL Connector separately instead of the UT, the parsing works correctly. In the UT, there are multiple versions of **debezium-ddl-parser**. By default, version **1.6.4-Final** is used, while MySQL depends on version **1.5.4-Final**. Therefore, we can only exclude the **1.6.4-Final** version from the Oracle Connector for now.
Exclude the **1.6.4-Final** version from the Oracle Connector.

[INLONG-8279][Sort] Fix NPE when run MySqlLoadSqlParseTest

---

inlong-manager/manager-dao/src/main/resources/mappers/DataNodeEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml

- Fixes #8619 
There is no need to check the role of the internal interface call of config management. 
Remove the INLONG_SERVICE role requirement of **selectAllGroup** method in InlongGroupEntity.xml
Remove the INLONG_SERVICE role requirement of **selectAllDataNodeEntity** method in DataNodeEntity.xml
*(example:)*
- Does this pull request …

[INLONG-8619][Manager] Remove the inlong role check of internal interfaces

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/debezium/table/RowDataDebeziumDeserializeSchema.java

[INLONG-8602][Sort] Fix StackOverflowError of Oracle CDC
- Fixes #8602 
**DebeziumDeserializationSchema** has three methods:
- `void deserialize(SourceRecord record, Collector<T> out)`
- `default void deserialize(SourceRecord record, Collector<T> out, TableChanges.TableChange tableSchema)`
- `default void deserialize(SourceRecord record, Collector<T> out, Boolean isStreamingPhase)`
**RowDataDebeziumDeserializeSchema** is an implementation of **DebeziumDeserializationSchema**. When calling the `RowDataDebeziumDeserializeSchema.deserialize(SourceRecord record, Collector<RowData> out)` method, it invokes the `deserialize(record, out)` method, as shown in the code below:
```java
@Override
public void deserialize(SourceRecord record, Collector<RowData> out) throws Exception { …
```

[INLONG-8602][Sort] Fix StackOverflowError of Oracle CDC

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/request.go
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/worker.go

- [INLONG-8639][DataProxy][Golang SDK] Improve send failed logic
- Fixes #8639
When send failed, delete batch and retry in a same gorotine.
When send failed, delete batch and retry in a same gorotine.
*(example:)* …

[INLONG-8639][SDK] Improve send failed logic

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java

fix bug: proxysink thread leaks when the dataproxy sdk init failed
- Fixes #8649 
*proxysink thread leaks when the dataproxy sdk init failed*
*start the thread after the sender has manager start*
*(example:)*

[INLONG-8649][Agent] Fix the proxysink thread leaks when the dataproxy sdk init failed

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/conf/ConfigJetty.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/trigger/TriggerManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/TextFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/TriggerFileReader.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/trigger/DirectoryTrigger.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/PluginUtils.java

the capacity of loading trigger from local file make it hard to operation and maintenance and we never use it online.
[INLONG-8645][Agent] delete the capacity of loading trigger from local file
- Fixes #8645 
*the capacity of loading trigger from local file make it hard to operation and maintenance and we never use it online.*
*delete the capacity of loading trigger from local file*
*(example:)* …

[INLONG-8645][Agent] Delete the capacity of loading trigger from local file

---

inlong-audit/pom.xml

- Fixes #8642
*Remove the audit commons-text dependency, because audit does not use it, but this library will trigger security issues.*
*Remove the commons-text in the audit pom.*

[INLONG-8642][Audit] Remove the audit commons-text dependency

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/source/reader/fetch/OracleScanFetchTask.java

[INLONG-8667][Sort] Fix the class name error in OracleSnapshotContext
- Fixes #8667 
In Oracle CDC, this should be `OracleSnapshotContext`, not `MySqlSnapshotContext`.
Rename `MySqlSnapshotContext` to `OracleSnapshotContext`.

[INLONG-8667][Sort] Fix the class name error in OracleSnapshotContext

---

inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/utils/HttpContextUtils.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/utils/InlongRequestWrapper.java

- Fixes #8671
Find no method parameter data iff the request is POST method and use x-www-form-urlencoded format.
This bug is due to the InlongRequestWrapper only parse the data in query string as the parameters.
But in HTTP standards, the x-www-form-urlencoded format with POST method request should parse the body as the parameters too.
1. Parse parameterMap as HTTP standard first.
2. Adjust the order of parameter parsing and body parsing.
*(example:)*
- If yes, how is the feature documented? (not applicable / docs …

[INLONG-8671][Manager] Fix no method parameter of form data in POST request

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/v0msg/AbsV0MsgCodec.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/v0msg/CodecBinMsg.java

- Fixes #8679
1. Migrate the fields related to index messages in CodecBinMsg, such as indexMsg and fileCheckMsg, to the abstract class AbsV0MsgCodec
2. Remove unnecessary checks when message delivery to Channel fails

[INLONG-8679][DataProxy] Migrate index-related variables to abstract classes

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/JobConstants.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/trigger/DirectoryTrigger.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/trigger/PathPattern.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/PluginUtils.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/filter/TestDateFormatRegex.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/trigger/TestWatchDirTrigger.java

- Fixes #8652 
*the capacity of setting blacklist make it hard to operation and maintenance and we never use it online.*
*delete the relation code*
*(example:)*

[INLONG-8652][Agent] Delete the capacity of setting blacklist

---

inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/sink/PulsarSink.java
inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/source/ServerMessageHandler.java
inlong-audit/conf/log4j2.xml

- Fixes #8699
*Currently, audit-proxym enables debug logs by default, which will lead to a large number of service logs and affect performance.*
*Reduce useless logs with high frequency, and adjust the default log level to INFO.*

[INLONG-8699][Audit] Optimize the service log of audit-proxy

---

licenses/inlong-agent/LICENSE
licenses/inlong-audit/LICENSE
licenses/inlong-dataproxy/LICENSE
licenses/inlong-sort-standalone/LICENSE
pom.xml

- Fixes #8683 
Upgrade org.eclipse.jetty:jetty-server Version to avoid the security problems
Upgrade org.eclipse.jetty:jetty-server version to 9.4.51.v20230217
*(example:)*
- If a feature …

[INLONG-8683][Security] Upgrade org.eclipse.jetty:jetty-server to version 9.4.51.v20230217

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/common/utils/WebParameterUtils.java

- Fixes #8720 
Remove unused StringBuilder ret in WebParamaterUtils.
Remove unused StringBuilder ret in WebParamaterUtils 
*(example:)* …

[INLONG-8720][TubeMQ] Remove unused return params in WebParamaterUtils

---

inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/BrokerServiceServer.java

- Fixes #8716
Adjust the errCode value of the outer layer of the API, and successfully unify it to 0

[INLONG-8716][TubeMQ] set error code 0 when it works

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/SinkContext.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/SimplePackProfile.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/BaseSource.java

- Fixes #8725
1. Cache file metrics output values in BaseSource
2. Cache file indicator output value in SinkContext
3. Optimize the implementation of the responseV0Msg function of the SimplePackProfile class, adjust the parameter name and code block placement

[INLONG-8725][DataProxy] Cache file metric output switch value at usage location

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSinkContext.java

- Fixes #8729
For SimplePackProfile type messages, only successful operations are counted

[INLONG-8729][DataProxy] Wrong result in the addSendResultMetric function also reports success

---

inlong-manager/manager-service/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/hudi/pom.xml
licenses/inlong-manager/LICENSE
licenses/inlong-sort-connectors/LICENSE
licenses/inlong-sort-standalone/LICENSE
pom.xml

- Title :[INLONG-8685][Sort] Denial of service due to parser crash
- Fixes #8685 
Denial of service due to parser crash
Upgrade com.fasterxml.woodstox:woodstox-core to version 5.4.0
- Does this pull request introduce a new feature?  no

[INLONG-8685][Sort] Fix the denial of service due to parser crash

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/CMakeLists.txt
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/third_party/CMakeLists.txt

- Fixes #8728
*The current openssl dependencies cannot be downloaded automatically and need to be installed manually, which is inconvenient.*
*Put the openssl library in the third_party third-party library and install it automatically.*

[INLONG-8728][SDK] Optimize the problem of third-party openssl library dependency

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/source/reader/fetch/OracleScanFetchTask.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/source/reader/fetch/OracleStreamFetchTask.java

[INLONG-8436][Sort] Fix the backfill task not running bug in oracle cdc connector
- Fixes #8436
Fix the backfill task not running bug in oracle cdc connector.
1. In the `OracleScanFetchTask#doExecute` method, for Snapshot step 3, we need to set the `highWatermark` instead of the `lowWatermark`.
```java
((SnapshotSplitChangeEventSourceContext) (context)).setHighWatermark(highWatermark);
```
2. The `RedoLogSplitReadTask` should use the StartingOffset of `RedoLogSplit` instead of the StartingOffset of `SnapshotSplit`.
```java
final RedoLogSplitReadTask backfillRedoLogReadReTask =
createBackfillRedoLogReadTask(backfillRedoLogSplit, sourceFetchContext);
final LogMinerOracleOffsetContextLoader loader =
new LogMinerOracleOffsetContextLoader(
((OracleSourceFetchTaskContext) …
```

[INLONG-8436][Sort] Fix the backfill task not running bug in oracle cdc connector

---

inlong-audit/pom.xml
inlong-dataproxy/pom.xml
inlong-sdk/pom.xml
inlong-sort-standalone/pom.xml
licenses/inlong-agent/LICENSE
licenses/inlong-audit/LICENSE
licenses/inlong-dataproxy/LICENSE
licenses/inlong-manager/LICENSE
licenses/inlong-sort-standalone/LICENSE
pom.xml

- Fixes #8753
*Separate commons-text from org.apache.flume, because flume uses the old version of commons-text, there will be security issues*
*Separate commons-text from org.apache.flume.*

[INLONG-8753][Audit] Separate commons-text from org.apache.flume

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/CommonConfigHolder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/MetaConfigHolder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/kafka/KafkaHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/tube/TubeHandler.java
inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/config/holder/TestMetaConfigHolder.java

- Fixes #8758
1. Add metadata pull time consumption check and log output;
2. Increase the concurrent check of metadata loading and updating;
3. Distinguish metadata management on the source and sink sides, the source side deletes immediately, and the sink only adds but does not delete;
4. Other viewing issues modified

[INLONG-8758][DataProxy] Metadata synchronization management optimization

---

inlong-tubemq/tubemq-manager/bin/restart-manager.sh

- Fixes #8768 
**New restart-manager script for fast restart implementation and quick changes to the manager configuration.**
**Add restart-manager.sh to inlong-tubemq-manager/bin**
*(example:)* …

[INLONG-8768][TubeMQ] Add restart-manager.sh to inlong-tubemq-manager

---

inlong-manager/manager-dao/src/main/resources/mappers/InlongStreamEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/consume/InlongConsumeServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/WorkflowApproverServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamProcessService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/StreamTransformServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/DataNodeController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongConsumeController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongTenantController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongTenantRoleController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/UserController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/WorkflowApproverController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenDataNodeController.java

- Fixes #8563 
1. All users can operate all resources under their tenant.
2. Only tenant admins can add/delete one user into/from theirs tenant
So we need to remove all **@RequeireRoles** annotation from resources controller like InlongGroup, InlongStream, dataNode etc.
Some shared resources like InlongCluster should be restriced under **INLONG_ADMIN**
*(example:)*
- *Added integration tests for end-to-end deployment with large payloads …

[INLONG-8563][Manager] Opitmize the permission check of tenant-related operation

---

inlong-agent/bin/agent-env.sh
inlong-agent/bin/agent.sh
inlong-agent/conf/log4j2.xml
inlong-dataproxy/bin/dataproxy-ng
inlong-dataproxy/conf/log4j2.xml
inlong-manager/manager-web/bin/startup.sh
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/trace/ResponseWrapper.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/trace/TraceFilter.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/trace/WrapperOutputStream.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/trace/WrapperWriter.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/utils/InlongRequestWrapper.java
inlong-manager/manager-web/src/main/resources/log4j2.xml
pom.xml

- Title Example: [INLONG-8611][Manager] Add full link trace.
- Fixes #8611 
*Inlong lacks observability, which is not conducive to link tracking and error location.*
Oentelemetry java agent is introduced for link embedding, collection and reporting, and span log is added to realize keyword search. It mainly includes the following functions:
- Opentelemetry java agent has automatically collected some fixed attributes for each span. In order to better meet the needs of inlong's link tracking, we have added some special attributes for span. Such as inlongGroupId, inlongstream, clusterName, clusterTag. Enter "key = value", for example, "inlongGroupId=test-group", and relevant links will be found. 
- Whether each response succeeds or fails, the trace id of its link can be found in the response …

[INLONG-8611][Manager] Add full link trace based on Opentelemetry

---

inlong-sort/sort-flink/sort-flink-v1.13/pom.xml

- Fixes #8783 
Mysql connector jdbc version should be compatible with mysql-cdc version
Specify mysql driver version to 8.0.21

[INLONG-8783][Sort] Mysql connector jdbc version should be compatible with mysql-cdc version

---

inlong-dashboard/package-lock.json
inlong-dashboard/package.json

- Fixes #8684 
Vite Server Options (server.fs.deny) can be bypassed using double forward-slash (//)
Upgrade vite to version 3.2.7

[INLONG-8684][Dashboard] Fixed the Vite Server Options (server.fs.deny) can be bypassed using double forward-slash (//)

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/IcebergTableSink.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/FlinkSink.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/DynamicSchemaHandleOperator.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergMultipleStreamWriter.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergSingleStreamWriter.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcBatchingOutputFormat.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingOutputFormat.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/TableJdbcUpsertOutputFormat.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDynamicOutputFormatBuilder.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDynamicTableFactory.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDynamicTableSink.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/debezium/DebeziumSourceFunction.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/MySqlSource.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/MySqlSource.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/MySqlSourceBuilder.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/config/MySqlSourceConfig.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/config/MySqlSourceConfigFactory.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlTableInlongSourceFactory.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/table/MySqlTableSource.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/StarRocksDynamicSinkFunction.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/StarRocksDynamicTableSink.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/StarRocksDynamicTableSinkFactory.java

- Fixes #8797 
1. Sort does not support audit ids sent by the Manager for data sync.
1. The manager adds audit IDs to send.
2. `JDBC`, `MySQL-CDC`, `Iceberg`, and `Starrocks` connectors support audit id.

[INLONG-8797][Manager][Sort] Support multiple audit ids for data sync

---

inlong-agent/bin/agent-env.sh
inlong-agent/bin/agent.sh
inlong-dataproxy/bin/dataproxy-ng
inlong-manager/manager-web/bin/startup.sh

- Title Example: [INLONG-8799][Manager][Agent][Dataproxy] Fix the configuration related to "Opentelemetry".
- Fixes #8799 
- Correct the path of javaagent in dataproxy.
- Make it be configurable whether the observable service is turned on or not.
- Add Default otlp export address is missing.
- Add export protocol of logs.

[INLONG-8799][Manager][Agent][Dataproxy] Fix the configuration related to "Opentelemetry".

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/doris/src/main/java/org/apache/inlong/sort/doris/schema/SchemaChangeHelper.java

- Fixes #8786
A user experience exception when combining doris ddl changes with a very long fenode list.
parse the fenodes, try to execute http request on each one, return when any succeeds.
Tested using a flink job.
Trivial change.

[INLONG-8786][Sort] Fix doris schema change in case of multiple uri 

---

inlong-sort/sort-flink/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/relational/JdbcSourceEventDispatcher.java
inlong-sort/sort-flink/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/relational/handler/SchemaChangeEventHandler.java
inlong-sort/sort-flink/cdc-base/src/main/java/org/apache/inlong/sort/cdc/base/util/RecordUtils.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/source/reader/fetch/OracleSourceFetchTaskContext.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/source/reader/handler/OracleSchemaChangeEventHandler.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/source/relational/OracleSourceEventDispatcher.java

[INLONG-8796] Add SchemaChangeEventHandler to deal schema change event by each connector
- Fixes #8796 
When a SchemaChangeEvent is triggered, the `schemaChangeRecordValue` will obtain binlog information from **sourceInfo**. However, only MySQL CDC has binlog information, and other CDC will report an error after triggering a SchemaChangeEvent event.  So I provided an interface for each connector to implement their own sourceinfo parsing. 
Add the `SchemaChangeEventHandler` interface, and each connector implements this interface to parse source.

[INLONG-8796][Sort] Add SchemaChangeEventHandler to deal schema change event by each connector

---

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/ClientContext.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/ConfigConstants.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/InlongTopicManagerFactory.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClientConfig.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClientFactory.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/TopicFetcher.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/TopicManager.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/QueryConsumeConfigImpl.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/SortClientImplV2.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/manager/InlongMultiTopicManager.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/manager/InlongSingleTopicManager.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/manager/InlongTopicManager.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/metrics/SortSdkMetricItem.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/metrics/SortSdkPrometheusMetricListener.java

- Fixes #8766 
Manage consumers in parallel to address the issue of inefficient consumer creating.
New version of topic manager
*(example:)*

[INLONG-8766][SDK] SortSdk create consumer in parallel

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigHolder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/MetaConfigHolder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/PropertiesHolder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/VisitConfigHolder.java

- Fixes #8819
1. Adjust the initialization value of lastModifyTime, only when the configuration file is updated successfully will the last modification time of the file be saved;
2. Adjust the return value of the subclass loadFromFileToHolder() function so that it returns true as long as the loading operation is performed.
3. Adjust the MD5 value comparison function in MetaConfigHolder to use case-sensitive mode;
4. Adjust the log output content to accurately express the problems found in each inspection link

[INLONG-8819][DataProxy] Optimize ConfigHolder related subclass loading processing

---

docker/docker-compose/README.md

- Fixes #8827
Inlong manager sql directory is incorrect in docker README
make directory right 

[INLONG-8827][Manager] Fix Inlong manager sql directory in docker README

---

inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/protocol/AuditData.java
inlong-audit/audit-common/src/main/proto/AuditApi.proto
inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/source/ServerMessageHandler.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditOperator.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/db/entities/AuditDataPo.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/db/entities/ClickHouseDataPo.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/db/entities/ESDataPo.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/ClickHouseService.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/ElasticsearchService.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/MySqlService.java
inlong-audit/sql/apache_inlong_audit.sql
inlong-audit/sql/apache_inlong_audit_clickhouse.sql
inlong-audit/sql/clickhouse-changes-1.9.0.sql
inlong-audit/sql/mysql-changes-1.9.0.sql

- Fixes #8836
*The same audit id may have multiple different data sources or data targets, and an audit_tag information needs to be added to further distinguish.*
*Differentiate different audit objects under the same audit_id by adding audit_tag information.*

[INLONG-8836][Audit] Add audit_tag information to distinguish data sources and data targets 

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskManager.java

- Fixes #8850 
*When  initialize taskmanager, there is no need to unregister of MetricRegister*
*Remove unregister of MetricRegister when initialize taskmanager*

[INLONG-8850][Agent] Remove unregister of MetricRegister when initialize taskmanager 

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/uitls/capi_constant.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/uitls/logger.h

- Fixes #8860 
*Add log utils for dataproxy cpp sd to improve the stability and performance of dataproxy cpp sdk.*
*Add sdk log utils for dataproxy cpp sdk.*

[INLONG-8860][SDK] Add log utils for dataproxy cpp sdk

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/block_memory.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/send_buffer.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/utils.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/utils.h

- Fixes #8864 
Add memory utils for dataproxy cpp sdk to improve the stability and performance of dataproxy cpp sdk*
*Add memory utils for dataproxy cpp sdk.*

[INLONG-8864][SDK] Add memory utils for dataproxy cpp sdk

---

inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/producer/MessageSentResult.java
inlong-tubemq/tubemq-client/src/main/java/org/apache/inlong/tubemq/client/producer/SimpleMessageProducer.java
inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corebase/TErrCodeConstants.java

- Fixes #8871 
1. Add new error code in TErrCodeConstants.java;
2. Use an error code in SimpleMessageProducer.checkMessageAndStatus() to return the check result instead of throwing an exception
3. In the SimpleMessageProducer.sendMessage() function, returns the result of the checkMessageAndStatus() check failure

[INLONG-8871][TubeMQ] Use an error code in checkMessageAndStatus() to return the check result instead of throwing an exception

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/PostgresDialect.java

- Fixes #8653 
plz refer to issue
adjusted the sql.
This change is used in the production environment.

[INLONG-8653][Sort] Fix the query sql for jdbc sink postgres dialect multiple table scenerios. 

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/MySqlSource.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/debezium/DebeziumUtils.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/OracleSource.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/oracle-cdc/src/main/java/org/apache/inlong/sort/cdc/oracle/source/config/OracleSourceConfigFactory.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/cdc/postgres/PostgreSQLSource.java

[INLONG-8897] update dbz option name 'xx. whitelist' to 'xx.include.list'(xx = database, schema or table)
- Fixes #8897 
The options `database.whitelist, schema.whitelist, table.whitelist` have been deprecated in Debezium. Starting from Debezium version 1.3, they have been replaced with `database.include.list, schema.include.list, table.include.list`. For more details, please refer to this link: https://debezium.io/blog/2020/09/03/debezium-1-3-beta1-released/
update dbz option name 'xx. whitelist' to 'xx.include.list'(xx = database, schema or table)

[INLONG-8897][Sort] update dbz option name 'xx. whitelist' to 'xx.include.list'(xx = database, schema or table)

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/CommonConfigHolder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/holder/MetaConfigHolder.java

- Fixes #8899
1. Optimize the metadata update logic and remove the locking process of lastUpdVersion.
2. Allow the default Topic configuration to be separated by commas

[INLONG-8899][DataProxy] Optimize metadata update logic

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/ConfigManager.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/ConfigConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/StatConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/kafka/KafkaHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/pulsar/PulsarHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/tube/TubeHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/BaseSource.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SourceConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/httpMsg/HttpMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/v0msg/CodecBinMsg.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/v0msg/CodecTextMsg.java
inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/source/UdpSourceTest.java

- Fixes #8914
1. Add detailed event indicator printing API at the Source side, and adjust the output of some events from simple event statistics to detailed event statistics;
2. Optimize the logic of obtaining the default Topic on the Sink side, and update the event indicator output type to detailed indicators;
3. Remove unused default attribute acquisition logic;
4. Optimize some log output

[INLONG-8914][DataProxy] Optimize DataProxy event statistics

---

bin/inlong-daemon

- Fixes #8918 
*Fix a script parameter error in `bin/inlong-daemon`*
*Change `tube` to `tubemq` (Line 81)*
*https://github.com/apache/inlong/blob/95580578336373f484622d3442d4ee01e9a41541/bin/inlong-daemon#L81*

[INLONG-8918][DataProxy] Change tube to tubemq

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/DataNodeEntityMapper.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongConsumeEntityMapper.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongGroupEntityMapper.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/TenantClusterTagEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/DataNodeEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/InlongConsumeEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/TenantClusterTagEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/GroupCheckService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/tenant/InlongTenantService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/tenant/InlongTenantServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongTenantController.java

- Fixes #8403
We need a set of interfaces to support resource migrate from/to different tenant.
There are three major resources will be migrated from one tenant to another, Inlong Group, Inlong Consume and DataNode.
All migration should be start with a specific Inlong Group , then migrate the group-related Inlong Consume and DataNode.
The migration is followed by these steps:
1. Check if the target tenant exists
2. List all Inlong Stream of this group
3. List all InlongConsume of this group
4. List all DataNode of related StreamSink
5. List all DataNode of related StreamSource
6. Copy DataNode if the the target tenant doesn't have it
7. Change the datanode name of each sink to the new one
8. Copy TenantClusterTag if the the target tenant doesn't have it
*Describe the modifications you've …

[INLONG-8403][Manager] Support resource migrate to another tenant

---

inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/resources/flinkSql/postgres_test.sql
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SinkMetricData.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/starrocks/pom.xml
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/StarRocksDynamicTableSinkFactory.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/table/SinkFunctionFactory.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/table/StarRocksDynamicSinkFunctionV2.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/table/StarRocksDynamicTableSink.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/utils/SchemaUtils.java
licenses/inlong-sort-connectors/LICENSE

- Fixes #8839 
Add audit metric in starrocks connector on flink 1.15
Add audit metric in starrocks connector on flink 1.15
1、modify end to end test to cope with starrocks trasnaction load
2、add starrocks sink function v1 to support starrocks version before v2.4
3、add schema utils to extract data time 
Run Iceberg -> starrocks
Check the audit data

[INLONG-8839][Sort] Add audit metric in starrocks connector on flink 1.15

---

inlong-tubemq/tubemq-manager/src/main/java/org/apache/inlong/tubemq/manager/controller/node/request/AddTopicReq.java

- Fixes https://github.com/apache/inlong/issues/8812
The parameter of the AddTopicReq class is missing memCacheMsgSizeInMB compared to the HTTP API parameter.
add memCacheMsgSizeInMB attribute to AddTopicReq
*(example:)*
- If yes, how is the feature documented? (not applicable / …

[INLONG-8812][Tubemq]add memCacheMsgSizeInMB attribute to AddTopicReq

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/IcebergConstant.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/IcebergExtractNode.java

- Fixes #8953 
Iceberg source force defaults the StartSnapshot to the latest and cannot be reset.
Offer the option to allow the user to assign the start snapshot strategy from the earliest.
*(example:)* …

[INLONG-8953][Sort] Fix Iceberg source defaults the StartSnapshot to the latest

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java

- Fixes #8946 
1. The manager only issues audit IDs through the sink type, all are placed in source Flink SQL.
image
2. When using the dashboard to query audit information, the manager should add the source type.
1. When creating Flink SQL, add the read audit ID to the source; add the send audit ID to the sink.
2. Add source type when getting audit information.

[INLONG-8946][Manager] Optimize the audit ID method issued by the manager

---

inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkOperation.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java

- Fixes #8975 
When the manager issues an audit ID, it distinguishes between `data ingestion` and `data synchronization`.
When the group mode is `data synchronization`, the manager issues the audit ID of the `source`.
When the group mode is `data ingestion`, the manager issues the audit ID of the `sink`.

[INLONG-8975][Manager] Manager issues an audit IDs based on the group mode

---

inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/DataConfig.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SourceStatus.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSource.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceDTO.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/AgentService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/AgentController.java

- Fixes #8995 
Add an interface for querying used task information for agent.
Add an interface for querying used task information for agent.

[INLONG-8995][Manager] Add an interface for querying used task information for agent

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ClientMgr.java

- Fixes https://github.com/apache/inlong/issues/9007
In the org. apache. inlong. sdk. dataproxy. network. ClientManager class, the getClientByWeightRoundRobin() method will cause ArrayList to exceed the bounds.Directly using random numbers as index to get Nettyclient.
Restrict the index of a list to the size range of the list using the remainder operation.
*(example:)*
- *Extended integration test for …

[INLONG-9007][SDK] ClientList out of bounds

---

inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.13/src/test/java/org/apache/inlong/sort/tests/utils/MySqlContainer.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/utils/MySqlContainer.java

- Fixes #8997
*(example:)*
- If a …

[INLONG-8997][Sort] Keep the logic the same of mysql with flink v1.13 in end to end test

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/IcebergLoadNode.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/FlinkDynamicTableFactory.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/IcebergWritableMetadata.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/CommitSummary.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/DeltaManifests.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/DeltaManifestsSerializer.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/EqualityFieldKeySelector.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/FlinkManifestUtil.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/FlinkSink.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/IcebergFilesCommitter.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/IcebergFilesCommitterMetrics.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/IcebergStreamWriter.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/IcebergStreamWriterMetrics.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/IcebergTableSink.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/ManifestOutputFileFactory.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/PartitionKeySelector.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/InlongIcebergSourceReaderMetrics.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/RowDataRecordFactory.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/utils/RecyclableJoinedRowData.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/utils/RowDataCloneUtil.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/utils/SinkMetadataUtils.java
licenses/inlong-sort-connectors/LICENSE

- Fixes #8982 
Support iceberg sink on flink 1.15 and support inlong audit
*(example:)*

[INLONG-8982][Sort] Iceberg sink on flink 1.15

---

inlong-tubemq/tubemq-server/pom.xml
licenses/inlong-agent/LICENSE
licenses/inlong-audit/LICENSE
licenses/inlong-dataproxy/LICENSE
licenses/inlong-manager/LICENSE
licenses/inlong-sort-standalone/LICENSE
licenses/inlong-tubemq-server/LICENSE
pom.xml

- Fixes #9046
Bump ZooKeeper to 3.7.2 to fix Authorization Bypass

[INLONG-9046][CVE] Bump ZooKeeper to 3.7.2 to fix Authorization Bypass

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/sdk_conf.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/api_imp.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/recv_group.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/recv_manager.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/recv_manager.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/capi_constant.h

- Fixes #9058
*Limit the number of inlong-groupid and inlong-streamid of a single SDK instance to prevent excessive resource consumption*
*Through configuration, limit the number of inlong-groupid and inlong-streamid of a single SDK instance to prevent excessive resource consumption.*

[INLONG-9058][SDK] Limit the number of inlong-groupid and inlong-streamid

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/impl/InlongGroupImpl.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupStatus.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/SimpleGroupStatus.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupProcessService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/group/UpdateGroupCompleteListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/group/UpdateGroupListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/queue/QueueResourceListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/sort/SortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamProcessService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/tenant/InlongTenantServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/AgentServiceTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/group/InlongGroupProcessServiceTest.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/source/listener/StreamSourceListenerTest.java
inlong-manager/manager-web/sql/changes-1.10.0.sql

- Fixes #9066 
Renaming group related states.
`SUSPENDING` rename to `CONFIG_OFFLINE_ING`.
`SUSPENDED` rename to `CONFIGURATION_OFFLINE`.
`RESTARTING` rename to `CONFIG_ONLINE_ING`.
`DELETING` rename to `CONFIG_DELETING`.
`DELETED` rename to `CONFIG_DELETED`.
Delete `RESTARTED`.
Renaming group related states.

[INLONG-9066][Manager] Renaming group related states

---

inlong-common/src/main/java/org/apache/inlong/common/enums/MessageWrapType.java

- Fixes #9070 
Add MessageWrapType.forType method for MessageWrapType.
Currently, the `MessageWrapType` type can only be obtained based on `id`, and an interface needs to be added to obtain the `MessageWrapType` type through `name`.
Add MessageWrapType.forType method for MessageWrapType.

[INLONG-9070][Manager] Add MessageWrapType.forType method for MessageWrapType

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/OffsetProfile.java

- [INLONG-9091][Agent] Add offset profile
- Fixes #9091 
Agent uses one job profile to store all the file collect infos that belong to the job. The infos contains basic file infos and the offsets. However hundreds and thousands of files in one collect task is not uncommon. It will be a nightmare to all the infos in one record.
*Offset will be sotred independently*
*(example:)* …

[INLONG-9091][Agent] Add offset profile

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongGroupClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongStreamClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongStreamApi.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/resource/sink/StandaloneAutoAssignTest.java

- Fixes #9109 
Fix the issue of streamApi URL errors.
Fix the issue of streamApi URL errors.

[INLONG-9109][Manager] Fix the issue of streamApi URL errors

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CommonConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/OffsetDb.java

[INLONG-9120][Agent] Add offset db to store the offset data
- Fixes #9120 
Add offset db to store the offset data
Add offset db to store the offset data
*(example:)*

[INLONG-9120][Agent] Add offset db to store the offset data

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/filecollect/PackageAckInfo.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/filecollect/ProxyMessageCache.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/filecollect/SenderMessage.java

[INLONG-9132][Agent] Add file used message cache
- Fixes #9132 
To make the file used message cache independent from common cache
Add file used message cache
*(example:)*

[INLONG-9132][Agent] Add file used message cache

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongStreamApi.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/AbstractGroupOperator.java

- Fixes #9147
The group details are displayed with the tag of the cluster to which the group belongs.
The group details are displayed with the tag of the cluster to which the group belongs.

[INLONG-9147][Manager] The group details are displayed with the tag of the cluster to which the group belongs

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/request.go
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/worker.go

- Fixes #9180 
Cache up batchReq.dataReqs Golang SDK to improve perf
request.go
worker.go
*(example:)*

[INLONG-9180][SDK] Cache up batchReq.dataReqs Golang SDK

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/options.go

- Fixes #9178 
Currently, the default values of the config options of Golang SDK are too BIG, which will cost a lot of memory, we can make it smaller, and some are to small, we need to make it bigger.
options.go
*(example:)*

[INLONG-9178][SDK] Update the default values of the config options of Golang SDK

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/client.go
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/worker.go

- Fixes #9170 
Currently, date types in worker.sendFailedBatches and woker.responseBatches are objects, not pointers, which will cost more memory in runtime, we can use pointer instead of ojbects.
worker.go
``` go
sendFailedBatches  chan sendFailedBatchReq // send failed batches channel
responseBatches    chan batchRsp           // batch response channel
```
to 
``` go
sendFailedBatches  chan *sendFailedBatchReq // send failed batches channel
responseBatches    chan *batchRsp           // batch response channel
```
*(example:)*
- Does this pull request introduce a new …

[INLONG-9170][SDK] Use pointers instead of objects

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/request.go

- Fixes #9174
Currently, when we parse the attr in response, we use Strings.Spilt() to parse, which will alloc new strings in runtime, and this is a frequently called method, and will finally decrease the perf of the SDK. We need to improve it.
Use `Strings.FieldsFunc()` instead of `Strings.Spilt()`
*(example:)* …

[INLONG-9174][SDK] Optimize response attr parsing in Golang SDK

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/client.go
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/worker.go

- Fixes #9176
Currently, when we send a message, if the worker is unavailable, we will try another one and wait 1ms, which will make the SDK step into a 'Blocking' like state, it is better to fail fast.
Fail fast when work is unavailable
*(example:)*

[INLONG-9176][SDK] Fail fast when work is unavailable in Golang SDK

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/worker.go

- Fixes #9172
Although the log level is not enabled, Some debug logs in the frequently called methods of Golang SDK will lead to string allocation, which will decrease the perf of the SDK, we need to delete/comment them.
worker.go
*(example:)*

[INLONG-9172][SDK] Delete useless debug logs in Golang SDK

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestLogFileSource.java

[INLONG-9190][Agent] Log file source clear buffer queue does not take effect
- Fixes #9190 
Log file source clear buffer queue does not take effect
Fix the bug and add ut check
*(example:)*

[INLONG-9190][Agent] Fix log file source clear buffer queue does not take effect

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/file/TaskManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/FileScanner.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/LogFileCollectTask.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/NewDateUtils.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/utils/TestUtils.java

[INLONG-9194][Agent] Calc time offset failed if the param is "0"
- Fixes #9194 
Fix the bug: calc time offset failed if the param is "0"
handle the case of param be ""
*(example:)*

[INLONG-9194][Agent] Calc time offset failed if the param is "0"

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/instance/TestInstanceManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/FileScanner.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/LogFileCollectTask.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/PluginUtils.java

[INLONG-9214][Agent] Limit max file count to collect once
- Fixes #9214 
Limit max file count to collect once
Limit max file count to collect once
*(example:)*

[INLONG-9214][Agent] Limit max file count to collect once

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/ProxySink.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java

[INLONG-9233][Agent] Fix bug: source, proxy, sender get stuck
- Fixes #9233 
source, proxy, sender get stuck
make sure they can jump out of endless loop
*(example:)*

[INLONG-9233][Agent] Fix bug: source, proxy, sender get stuck

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/filecollect/ProxyMessageCache.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/AgentUtils.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/MetaDataUtils.java

[INLONG-9237][Agent] Move addictive fields to package attributes
- Fixes #9237 
Move addictive fields to package attributes
Move addictive fields to package attributes
*(example:)*

[INLONG-9237][Agent] Move addictive fields to package attributes

---

inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/instance/MockInstance.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/instance/TestInstanceManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestLogFileSource.java

[INLONG-9253][Agent] Fix bug: get byte postion of file by line count offset failed
- Fixes #9253 
Fix bug: get byte postion of file by line count offset failed
Fix bug: get byte postion of file by line count offset failed
*(example:)*

[INLONG-9253][Agent] Fix bug: get byte postion of file by line count offset failed

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/IcebergProvider.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/PulsarProvider.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/TubeMqProvider.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/StreamSource.java

- Fixes #9248
Supports configuring builtIn fields for tube source and pulsar source.
If auditing needs to be configured for `Tube ->iceberg`, `pulsar - iceberg` , the manager needs to issue the corresponding auditing builtIn field.
Supports configuring builtIn fields for tube source and pulsar source.

[INLONG-9248][Manager] Supports configuring builtIn fields for tube source and pulsar source

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/ProxySink.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestLogFileSource.java

[INLONG-9267][Agent] Fix bug: data loss when there are many files to read once
- Fixes #9267 
Fix bug: data loss when there are many files to read once
Fix bug: data loss when there are many files to read once
*(example:)*

[INLONG-9267][Agent] Fix bug: data loss when there are many files to read once

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/ExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/PulsarExtractNode.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/PulsarTableFactory.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarReadableMetadata.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableDeserializationSchema.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableDeserializationSchemaFactory.java

- Fixes #9246 
*(example:)*
- If a …

[INLONG-9246][Sort] Pulsar source support audit when the deserialized type is not InlongMsg

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/StreamField.java
inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtilsTest.java

When creating 'StreamField', 'isMetaField' must be initialized
- [INLONG-9271] [Manager]When creating 'StreamField', 'isMetaField' must be initialized
- Fixes #9271 
When I create 'StreamField' using a constructor, 'isMetaField' has an initial value
- [√ ] This change added tests and can be verified as follows:
*(example:)*
- Added integration tests ：org.apache.inlong.manager.pojo.sort.util.FieldInfoUtilsTest#testCreateFieldTypeInfo
- Does …

[INLONG-9271][Manager] When creating 'StreamField', 'isMetaField' must be initialized

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/IcebergSingleFileCommiter.java

- [INLONG-9273][Sort] IcebergSingleFileCommiter will throw exception for error code
- Fixes #9273 
* Fix IcebergSingleFileCommiter throw exception
pendingMap.clear() will be enough. 
* remove error code

[INLONG-9273][Sort] IcebergSingleFileCommiter will throw exception for error code

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/DateTransUtils.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/FileScanner.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/LogFileCollectTask.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/WatchEntity.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/NewDateUtils.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/utils/TestUtils.java

[INLONG-9286][Agent] Adjust the time offset calculation function
- Fixes #9286 
Adjust the time offset calculation function to align with the front-end and annotations for easy understanding.
Adjust the time offset calculation function to align with the front-end and annotations for easy understanding.
*(example:)* …

[INLONG-9286][Agent] Adjust the time offset calculation function

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/filecollect/ProxyMessageCache.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/DateTransUtils.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/file/TaskManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestLogFileSource.java

[INLONG-9284][Agent] Report audit by data time not real time
- Fixes #9284 
Report audit by data time not real time
Report audit by data time not real time
*(example:)*

[INLONG-9284][Agent] Report audit by data time not real time

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/iceberg/IcebergSink.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/iceberg/IcebergSinkRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/IcebergProvider.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/IcebergConstant.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/IcebergLoadNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/IcebergLoadNodeTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/IcebergNodeSqlParserTest.java

- Fixes #9240 
*(example:)*
- If a …

[INLONG-9240][Manager][Sort] Add append mode for the Iceberg connector

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/InstanceProfile.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/TaskProfile.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/filecollect/ProxyMessageCache.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/FileTask.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/AgentBaseTestsHelper.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/instance/TestInstanceManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/AgentBaseTestsHelper.java

[INLONG-9300][Agent] Divide data time into source time and sink time
- Fixes #9300 
Divide data time into source time and sink time
Divide data time into source time and sink time
*(example:)*

[INLONG-9300][Agent] Divide data time into source time and sink time

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/TaskProfile.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/filecollect/OffsetAckInfo.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/filecollect/ProxyMessage.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/filecollect/ProxyMessageCache.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/filecollect/SenderMessage.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/DateTransUtils.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/ProxySink.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/WatchEntity.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/NewDateUtils.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/filecollect/TestSenderManager.java

[INLONG-9308][Agent] The sink end of the file instance supports sending data with different streamIds
- Fixes #9308 
The sink end of the file instance supports sending data with different streamIds
The sink end of the file instance supports sending data with different streamIds
*(example:)* …

[INLONG-9308][Agent] The sink end of the file instance supports sending data with different streamIds

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/filecollect/ProxyMessage.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/filecollect/ProxyMessageCache.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/extend/ExtendedHandler.java

[INLONG-9310][Agent] Add extended handler in file source
- Fixes #9310 
Add extended handler in file source
Add extended handler in file source
*(example:)*

[INLONG-9310][Agent] Add extended handler in file source

---

inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/AgentBaseTestsHelper.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/instance/TestInstanceManager.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/task/TestTaskManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java

[INLONG-9315][Agent] Convert data time from source time zone to sink time zone
- Fixes #9315 
If we dont do the converting, the data time we be displayed differently: local(GMT+0:00) time 2023112210 will be displayed in the form of 2023112218 by sort (GMT+8:00), not conducive to quick understanding.
Convert data time from source time zone to sink time zone
*(example:)* …

[INLONG-9315][Agent] Convert data time from source time zone to sink time zone

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongClusterClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongClusterApi.java

- Fixes #9318 
ManagerClient supports pulling clusters based on tenant roles.
ManagerClient supports pulling clusters based on tenant roles..

[INLONG-9318][Manager] ManagerClient supports pulling clusters based on tenant roles

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/redis/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/redis/src/test/java/org/apache/inlong/sort/redis/RedisTableTest.java

- Fixes #9034
Fix sort redis test with incorrect use of sleep
Use Await to replace sleep 
See RedisTest

[INLONG-9034][Sort] Fix sort redis test with incorrect use of sleep

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/AbstractConfiguration.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/filecollect/ProxyMessageCache.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/file/TaskManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java

[INLONG-9338][Agent] Real time file collection uses the current time as the data time
- Fixes #9338 
Real time file collection uses the current time as the data time
Real time file collection uses the current time as the data time
*(example:)*

[INLONG-9338][Agent] Real time file collection uses the current time as the data time

---

inlong-common/src/main/java/org/apache/inlong/common/enums/TaskTypeEnum.java
inlong-common/src/test/java/org/apache/inlong/common/enums/TaskTypeEnumTest.java

Improve the TaskTypeEnum.java file in Inlong-common-enums
- [INLONG-8433][Agent] Improve the TaskTypeEnum.java file in Inlong-common-enums
- Fixes #8433 
In the getTaskType() method we are using switch case to get the task , we can improve it using Hashmap to store the Task and then can get Task Type from HashMap, which is more efficient.
use Hashmap to store the Task and then can get Task Type from HashMap
- [√] This change added tests and can be verified as follows:
add test file: org.apache.inlong.common.enums.TaskTypeEnumTest#testGetTaskType
- …

[INLONG-8433][Agent] Improve the TaskTypeEnum file

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/plugin/file/Task.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/file/TaskManager.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/task/MockTask.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/CronTask.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/LogFileCollectTask.java

[INLONG-9347][Agent] Check task profile before save into db
- Fixes #9347
Check task profile before save into db
Check task profile before save into db
*(example:)*

[INLONG-9347][Agent] Check task profile before save into db

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/IcebergLoadNode.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/FlinkDynamicTableFactory.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/DynamicSchemaHandleOperator.java

- Fixes #9359 
Fix iceberg all migrate connector stack overflow error
When creating iceberg table, the field id will increase one 
so when comparing table schema we should not use schema.sameSchema which will return false  
run mysql -> iceberg

[INLONG-9359][Sort] Fix iceberg all migrate connector stack overflow error

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java

[INLONG-9369][Agent] Increase sending failure audit and real-time audit
- Fixes #9369 
Increase sending failure audit and real-time audit
Increase sending failure audit and real-time audit
*(example:)*

[INLONG-9369][Agent] Increase sending failure audit and real-time audit

---

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceMetricData.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/internal/FlinkPulsarSource.java

- Fixes #9384
Fix pulsar audit data loss when restarting
Flush audit report when checkpoint 
Flush audit report when checkpoint 

[INLONG-9384][Sort] Fix pulsar audit data loss when restarting

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java

[INLONG-9375][Agent] Modify the agent's real-time audit id to prevent duplication
- Fixes #9375 
Modify the agent's real-time audit id to prevent duplication
Modify the agent's real-time audit id to prevent duplication
*(example:)*

[INLONG-9375][Agent] Modify the agent's real-time audit id to prevent duplication

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/FileInstance.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/FileScanner.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/LogFileCollectTask.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/WatchEntity.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/NewDateUtils.java

[INLONG-9390][Agent] Collect supplementary data in chronological order
- Fixes #9390 
Collect supplementary data in chronological order, and prioritize data from the current cycle
Collect supplementary data in chronological order, and prioritize data from the current cycle
*(example:)* …

[INLONG-9390][Agent] Collect supplementary data in chronological order

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java

[INLONG-9397][Agent] Do not directly delete the instance records of the local db when stopping the instances
- Fixes #9397 
Do not directly delete the instance records of the local db when stopping the instance to prevent data duplication
Do not directly delete the instance records of the local db when stopping the instance to prevent data duplication
*(example:)*
- If a feature is not applicable for documentation, explain …

[INLONG-9397][Agent] Do not directly delete the instance records of the local db when stopping the instances

---

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceMetricData.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/IcebergStreamWriter.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/IcebergStreamWriterMetrics.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/IcebergSourceReader.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/InlongIcebergSourceReaderMetrics.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/DynamicTubeMQDeserializationSchema.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/DynamicTubeMQTableDeserializationSchema.java

- Fixes #9380 
*(example:)*
- If a …

[INLONG-9380][Sort] Audit lost when stop job immediately after checkpoint

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/redis/pom.xml
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/redis/src/test/java/org/apache/inlong/sort/redis/RedisTableTest.java
pom.xml

- Fixes #9388 
The current version of embedded-redis does not support macOS Sonoma.

[INLONG-9388][Sort] Updated version of embedded-redis in sort-connector-redis

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/hbase/pom.xml
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/hbase/pom.xml
licenses/inlong-manager/notices/NOTICE-flink-shaded-zookeeper-3.txt
licenses/inlong-sort-connectors/LICENSE

- Fixes #9465
Bump zookeeper to 3.7.2 to fix the CVE, and 3.7.2 is compatible with HBase.

[INLONG-9465][CVE] Bump zookeeper to 3.7.2

---

inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/function/EmbeddingFunction.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/function/embedding/EmbeddingInput.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/function/embedding/LanguageModel.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/NativeFlinkSqlParser.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/function/EmbeddingFunctionTest.java

- Fixes #9473
Support transform of embedding for LLM applications
- add a new transform UDF named `EmbeddingFunction`
- add test in `EmbeddingFunctionTest`
Added new test  `EmbeddingFunctionTest`
No docs needed.

[INLONG-9473][Sort] Support transform of embedding for LLM applications

---

licenses/inlong-agent/LICENSE
licenses/inlong-dataproxy/LICENSE
pom.xml

- Fixes #9477
Bump kafka-client to 2.7.2 to solve the CVE.

[INLONG-9477][CVE] Bump kafka-client to 2.7.2

---

inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestLogFileSource.java

[INLONG-9481][Agent] Add unit test of reading with offset
- Fixes #9481 
Add unit test of reading with offset
Add unit test of reading with offset
*(example:)*

[INLONG-9481][Agent] Add unit test of reading with offset

---

inlong-common/src/main/java/org/apache/inlong/common/heartbeat/AddressInfo.java
inlong-common/src/main/java/org/apache/inlong/common/heartbeat/HeartbeatMsg.java
inlong-common/src/main/java/org/apache/inlong/common/heartbeat/ReportResourceType.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/dataproxy/DataProxyClusterNodeDTO.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/dataproxy/DataProxyClusterNodeRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/dataproxy/DataProxyClusterNodeResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java

- Fixes #8392
Optimize the HeartbeatMsg class.
Optimize the HeartbeatMsg class.
1.Added differentiation of reported business types based on reporting source type parameters.
2.Due to the fact that dataproxy reports multiple IP addresses, ports, and other information, these information are no longer organized in the form of strings and commas, but are placed in a list object.
3.Dataproxy nodes add reporting types to distinguish which dataproxy node information will be pulled when SDK reports.

[INLONG-8392][Manager] Optimize the HeartbeatMsg class

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/SortConsumerInfo.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/maintenanceTools/MaintenanceToolsService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/maintenanceTools/MaintenanceToolsServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/QueueResourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaQueueResourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarQueueResourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/tubemq/TubeMQQueueResourceOperator.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/MaintenanceToolsController.java

- Fixes #9518 
Support resetting the consumption location of the consumption group used by sort.
Convenient for management personnel to batch reset the consumption group locations used by sort.
Management personnel can batch modify the corresponding consumption group location information by uploading files.
Support resetting the consumption location of the consumption group used by sort.
1.Added interface to retrieve all consumption groups used by sort through Sinkid.
2.Added interface for resetting consumption group sites through Sinkid.

[INLONG-9518][Manager] Support resetting the consumption location of the consumption group used by sort

---

inlong-tubemq/tubemq-server/src/main/assembly/assembly.xml

- Fixes #9033
Fix the tubectl script missing for packaging
Add all resources in the binary directory.

[INLONG-9033][TubeMQ] Fix the tubectl script missing for packaging

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/dataproxy/DataProxyClusterNodeDTO.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/dataproxy/DataProxyClusterNodeRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/dataproxy/DataProxyClusterNodeResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java

- Fixes #9528 
Support configuring the switch to enable dataProxy nodes.
Support configuring the switch to enable dataProxy nodes.
When the dataproxy node is enabled, it will be issued to the agent or SDK, otherwise it will not.

[INLONG-9528][Manager] Support configuring the switch to enable dataProxy nodes

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/HudiExtractNode.java

- Fixes #9532
Fix the wrong params for HudiExtractNode
Fix the wrong params for HudiExtractNode, Discussed in https://github.com/apache/inlong/discussions/9275

[INLONG-9532][Sort] Fix the wrong params for HudiExtractNode

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/fieldtype/strategy/IcebergFieldTypeStrategy.java
inlong-manager/manager-common/src/main/resources/iceberg-field-type-mapping.yaml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/IcebergProvider.java
inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtilsTest.java

[INLONG-9508][Manager] Add Iceberg field type mapping strategy to improve usability
- Fixes #9508
Inlong Iceberg ExtractNode or LoadNode currently does not support some special field types, add Iceberg field type mapping strategy to mapping to the corresponding type to run correctly

[INLONG-9508][Manager] Add Iceberg field type mapping strategy to improve usability

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/AuditClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/AuditApi.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/AuditEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/AuditEntityMapper.xml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/audit/AuditInfo.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/AuditService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java

- Fixes #9523
Support querying all audit information based on IP address.
Support querying all audit information based on IP address.

[INLONG-9523][Manager] Support querying all audit information based on IP address

---

inlong-sort/sort-formats/format-inlongmsg-base/pom.xml
inlong-sort/sort-formats/format-inlongmsg-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgDecodingFormat.java
inlong-sort/sort-formats/format-inlongmsg-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgFormatFactory.java
inlong-sort/sort-formats/format-inlongmsg-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgOptions.java
inlong-sort/sort-formats/format-inlongmsg-base/src/test/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgRowDataSerDeTest.java

- Fixes #9491 
*(example:)*
- If a …

[INLONG-9491][Sort] CSV format support ignore trailing unmappable fields

---

inlong-manager/manager-dao/src/main/resources/mappers/AuditEntityMapper.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/AbstractStandaloneSinkResourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/ck/ClickHouseSinkOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/es/ElasticsearchSinkOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/iceberg/IcebergSinkOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/kudu/KuduSinkOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/starrocks/StarRocksSinkOperator.java

- Fixes #9552
1.Fix the problem of sink remains in configuration after standalone cluster allocation failure.
2.Fix the problem of serializing information in extparams when dealing with serializing field information.
1.Fix the problem of sink remains in configuration after standalone cluster allocation failure.
2.Fix the problem of serializing information in extparams when dealing with serializing field information.

[INLONG-9552][Manager] Fix the problem of sink remains in configuration after standalone cluster allocation failure

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/plugin/file/Sink.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/FileInstance.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/ProxySink.java

[INLONG-9556][Agent] Prevent thread freeze caused by deleting data sources when the backend cannot send out
- Fixes #9556 
Prevent thread freeze caused by deleting data sources when the backend cannot send out
Prevent thread freeze caused by deleting data sources when the backend cannot send out
*(example:)* …

[INLONG-9556][Agent] Prevent thread freeze caused by deleting data sources when the backend cannot send out

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/filecollect/ProxyMessageCache.java

[INLONG-9572][Agent] Set data time of message cache by sink data time
- Fixes #9572 
Adapt data time to sink side time zone
Set data time of message cache by sink data time
*(example:)*

[INLONG-9572][Agent] Set data time of message cache by sink data time

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/file/TaskManager.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/task/TestTaskManager.java

[INLONG-9580][Agent] Add unit testing to taskmanager to test their ability to recover tasks from DB
- Fixes #9580 
Add unit testing to taskmanager to test their ability to recover tasks from DB
Add unit testing to taskmanager to test their ability to recover tasks from DB
*(example:)* …

[INLONG-9580][Agent] Add unit testing to taskmanager to test their ability to recover tasks from DB

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/instance/TestInstanceManager.java

[INLONG-9582][Agent] Add unit testing to instance manager to test their ability to recover tasks from DB
- Fixes #9582
Add unit testing to instance manager to test their ability to recover tasks from DB
Add unit testing to instance manager to test their ability to recover tasks from DB
*(example:)* …

[INLONG-9582][Agent] Add unit testing to instance manager to test their ability to recover tasks from DB

---

inlong-tubemq/tubemq-docker/tubemq-cpp/Dockerfile

- Fixes #9603
Bump openssl to 1.1.1w to fix the build error.

[INLONG-9603][TubeMQ] Bump openssl to 1.1.1w

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/threadPool/VisiableThreadPoolTaskExecutor.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupProcessService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamProcessService.java

- Fixes #9591
Support printing thread status before submitting tasks.
Support observing information such as the number of running threads and completed threads in the thread pool.
Support printing thread status before submitting tasks.

[INLONG-9591][Manager] Support printing thread status before submitting tasks

---

inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/StartupSortListener.java

- Fixes #9632 
fix the problem of miss checking all streams in StartupSortListener
add logs for the illegal stream and continue to check the remaining streams

[INLONG-9632][Manager] ensure every stream in group will be processed

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/FieldType.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtils.java

- Fixes #9204 
It failed to use the PostgreSQL sink type.
Add `INTEGER`, `FLOAT4`, and `FLOAT8` to the field type.

[INLONG-9204][Manager] Add field type for PostgreSQL

---

pom.xml

- Fixes #9666
Bump wiremock-jre8 to 2.35.1 to fix the CVE

[INLONG-9666][CVE] Bump wiremock-jre8 to 2.35.1 to fix the CVE

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/AuditSourceType.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ErrorCodeEnum.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/audit/AbstractAuditSourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/audit/AuditSourceClickhouseOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/audit/AuditSourceElasticsearchOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/audit/AuditSourceMysqlOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/audit/InlongAuditSourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/audit/InlongAuditSourceOperatorFactory.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java

- Fixes #9671 
Adding JDBC URL checks to the updateAuditSource method
Adding JDBC URL checks to the updateAuditSource method

[INLONG-9671][Manager] Adding JDBC URL checks to the updateAuditSource method

---

pom.xml

see #9684 
it's possible/probable that logback.version is not even used any more
https://github.com/search?q=repo%3Aapache%2Finlong%20logback.version&type=code

[INLONG-9684][Manager] remove unused logback.version

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/util/MySQLSensitiveUrlUtils.java

- Fixes #9689 
Optimize MySQL JDBC URL check.
Removed `#` and subsequent strings.
Prevent parameters from becoming invalid due to the addition of # in jdbcurl。
Optimize MySQL JDBC URL check.
Prevent parameters from becoming invalid due to the addition of # in jdbcurl.

[INLONG-9689][Manager] Optimize MySQL JDBC URL check

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/AbstractSink.java

[INLONG-9702][Agent] Change the data transmission interval to depend on local file configuration
- Fixes #9702 
Change the data transmission interval to depend on local file configuration
Change the data transmission interval to depend on local file configuration
*(example:)* …

[INLONG-9702][Agent] Change the data transmission interval to depend on local file configuration

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/file/LogFileTask.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/TestLogFileTask.java

[INLONG-9721][Agent] Add a common cycle parameter to the task configuration
- Fixes #9721 
Add a common cycle parameter to the task configuration, with the default cycle set to real-time; The cycle of the file type task is obtained from the extension parameters in the manager task configuration
Add a common cycle parameter to the task configuration, with the default cycle set to real-time; The cycle of the file type task is obtained from the extension parameters in the manager task configuration
*(example:)*
- If …

[INLONG-9721][Agent] Add a common cycle parameter to the task configuration

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/TaskProfile.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CommonConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/FetcherConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/FileTask.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/AgentBaseTestsHelper.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/file/LogFileTask.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/AgentBaseTestsHelper.java

[INLONG-9736][Agent] Make time zone a common parameter
- Fixes #9736
Make time zone a common parameter
Make time zone a common parameter
*(example:)*

[INLONG-9736][Agent] Make time zone a common parameter

---

inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/FailureHandler.java
inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/IgnoreFailureHandler.java
inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/NoOpFailureHandler.java
inlong-sort/sort-formats/format-row/format-inlongmsg-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/AbstractInLongMsgFormatDeserializer.java
inlong-sort/sort-formats/format-row/format-inlongmsg-csv/src/test/java/org/apache/inlong/sort/formats/inlongmsgcsv/InLongMsgCsvFormatDeserializerTest.java
inlong-sort/sort-formats/format-row/format-inlongmsg-kv/src/test/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvFormatDeserializerTest.java
inlong-sort/sort-formats/format-row/format-inlongmsg-tlogcsv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvFormatDeserializerTest.java
inlong-sort/sort-formats/format-row/format-inlongmsg-tlogkv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvFormatDeserializerTest.java
inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/AbstractInLongMsgFormatDeserializer.java
inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-csv/src/test/java/org/apache/inlong/sort/formats/inlongmsgcsv/InLongMsgCsvFormatDeserializerTest.java
inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-kv/src/test/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvFormatDeserializerTest.java
inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogcsv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvFormatDeserializerTest.java

[INLONG-9739][Sort] onParsingBodyFailure function in FailureHandler class need add 'head' paramete to generate failure metric

---

inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/RestartSortListener.java
inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/StartupSortListener.java
inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/StartupStreamListener.java

- Fixes #9756
Make jobName more readable
dd separator between groupId and streamId
no doc needed

[INLONG-9756][Manager] add separator between groupId and streamId in JobName

---

inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/util/FlinkConfiguration.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/maintenanceTools/MaintenanceToolsServiceImpl.java

- Fixes #9760
make sure BufferedReader closes properly after use
Unify the use of BufferedReader by try-with-resource block 
no docs needed

[INLONG-9760][Manager] make sure BufferedReader close properly

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/table/StarRocksDynamicSinkFunctionV2.java

- Fixes #9758 
Support the case that one job with multiple flows, the state of each flow should be distinguished.
*(example:)* …

[INLONG-9758][Sort] StarRocks connector support state key when initializing

---

inlong-common/src/main/java/org/apache/inlong/common/enums/InlongCompressType.java
inlong-manager/manager-dao/src/main/resources/mappers/ClusterSetMapper.xml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/dataproxy/InlongStreamId.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamBriefInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamExtParam.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java

- Fixes #9770
Unified compression type configuration.
Unified compression type configuration.

[INLONG-9770][Manager] Unified compression type configuration

---

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderGroup.java

- Fixes #9784
*Optimize sending memory management when the audit-proxy config is null.*
*Add memory release logic when the audit-proxy config is null.*

[INLONG-9784][Audit] Optimize sending memory management when the audit-proxy config is null

---

inlong-manager/manager-client-examples/src/test/java/org/apache/inlong/manager/client/ut/BaseTest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/GroupMode.java
inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/StartupSortListener.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupPageRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/group/InitGroupCompleteListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/group/UpdateGroupCompleteListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/queue/QueueResourceListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/stream/InitStreamCompleteListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java

- Fixes #9781 
Support task type definition for offline sync 
Add offline sync task type definition
no need

[INLONG-9781][Manager] Add offline sync task type definition

---

inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/util/StringUtils.java
inlong-sort/sort-formats/format-common/src/test/java/org/apache/inlong/sort/formats/common/StringUtilsTest.java
inlong-sort/sort-formats/format-row/format-csv/src/test/java/org/apache/inlong/sort/formats/csv/CsvUtilsTest.java
inlong-sort/sort-formats/format-row/format-kv/src/test/java/org/apache/inlong/sort/formats/kv/KvUtilsTest.java
inlong-sort/sort-formats/format-rowdata/format-rowdata-kv/src/test/java/org/apache/inlong/sort/formats/kv/KvUtilsTest.java

[INLONG-9788][Sort] Supports data parse that contains delimiters in kv and csv data format

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/redis/src/main/java/org/apache/inlong/sort/redis/common/config/RedisDataType.java

Fix #9795
- Title Example: [INLONG-9795][Sort] Optimize the definition of enumeration variables…
The current enumeration class org.apache.inlong.sort.redis.common.config.RedisDataType is defined as,
; symbol ends. Although there is no grammatical problem with this, the code looks confusing, so it is recommended to modify it and remove it.
; symbol makes the code look clearer.
Removed the trailing symbol "" of the enumeration class org.apache.inlong.sort.redis.common.config.RedisDataType,
;".
None
- Does this pull request introduce a new feature? (yes / no) no …

[INLONG-9795][Sort] Optimize the definition of enumeration variables and remove the semicolon

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/PulsarJob.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/PulsarTask.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/PulsarInstance.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/PulsarSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/PulsarTask.java

- Fixes #9804 
1. Add `resetTime` in `PulsarTask`, used to reset consume.
2. Add `PulsarSource` to consume message.
3. Add `PulsarTask` and `PulsarInstance` to manage `PulsarSource`.
When the dataproxy is invalid for a period of time and restarted, the data will be sent later and the memory will be restored.

[INLONG-9804][Agent] Add Pulsar source for Agent

---

inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/installer/ConfigResult.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/installer/ModuleConfig.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/installer/PackageConfig.java

[INLONG-9816][Agent] Add config class for installer
- Fixes #9816 
Add config class for installer
Add config class for installer
*(example:)*

[INLONG-9816][Agent] Add config class for installer

---

inlong-manager/manager-plugins/manager-plugins-flink-v1.13/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkClientService.java
inlong-manager/manager-plugins/manager-plugins-flink-v1.15/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkClientService.java

- Fixes #9825 
reduce the creation of RestClusterClient
create a single RestClusterClient for a configuration, and re-use the object to do the flink job operations like get job status, stop job etc.

[INLONG-9825][Manager] Reduce the creation of RestClusterClient

---

inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/installer/ModuleConfig.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/installer/ModuleStateEnum.java

[INLONG-9833][Agent] Add module state to distinguish whether the module has been downloaded or installed
- Fixes #9833
Add module state to distinguish whether the module has been downloaded or installed
Add module state to distinguish whether the module has been downloaded or installed
*(example:)* …

[INLONG-9833][Agent] Add module state to distinguish whether the module has been downloaded or installed

---

inlong-agent/agent-installer/assembly.xml
inlong-agent/agent-installer/bin/installer-env.sh
inlong-agent/agent-installer/bin/installer.sh
inlong-agent/agent-installer/pom.xml

[INLONG-9829][Agent] Add guardian scripts
- Fixes #9829 
Add guardian scripts
Add guardian scripts
*(example:)*

[INLONG-9829][Agent] Add guardian scripts

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/HttpManager.java

[INLONG-9848][Agent] Add the getAuthHeader function in the HttpManager class
- Fixes #9848
Add the getAuthHeader function in the HttpManager class
Add the getAuthHeader function in the HttpManager class to separate the authorization related logic. The installer needs to use authorization to download files
*(example:)*
- If a feature is not documented yet in …

[INLONG-9848][Agent] Add the getAuthHeader function in the HttpManager class

---

inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/installer/ConfigResult.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/installer/PackageConfig.java

[INLONG-9852][Agent] Place the configuration item for the installation package storage path in the installation package configuration
- Fixes #9852
Place the configuration item for the installation package storage path in the installation package configuration
Place the configuration item for the installation package storage path in the installation package configuration
*(example:)* …

[INLONG-9852][Agent] Place the configuration item for the installation package storage path in the installation package configuration

---

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ManagerFetcher.java
inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java

[INLONG-9850][Agent] Add a function to retrieve HttpManager in the ModuleManager class
- Fixes #9850
Add a function to retrieve HttpManager in the ModuleManager class, which needs to be used when downloading and installing packages
Add a function to retrieve HttpManager in the ModuleManager class, which needs to be used when downloading and installing packages
*(example:)* …

[INLONG-9850][Agent] Add a function to retrieve HttpManager in the ModuleManager class

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/file/LogFileTask.java

[INLONG-9863][Agent] To avoid data loss caused by too many supplementary files
- Fixes #9863
To avoid data loss caused by too many supplementary files:
The dealWithEventMap function will submit all the file information that needs to be collected to the instanceManager, but the instanceManager will limit the number of files to be processed. If the limit of the instanceManager is exceeded, the dealWithEventMap will end prematurely, and any file information that cannot be submitted will be retained in the internal memory, waiting for the next execution of the dealWithEventMap to submit.
To avoid data loss caused by too many supplementary files
*(example:)*
- *Added integration tests for end-to-end deployment with large …

[INLONG-9863][Agent] To avoid data loss caused by too many supplementary files

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java
inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/StartupSortListener.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/StreamParseUtils.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/StreamTaskListenerFactory.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/schedule/StreamScheduleResourceListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/sort/SortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/stream/InitStreamCompleteListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/stream/CreateStreamWorkflowDefinition.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/event/task/ScheduleOperateListener.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/plugin/ProcessPlugin.java

- Fixes #9862 
For real-time data sync, the whole procedure is as follows:
Currently, InLong does not support submitting Flink batch jobs for offline data sync.
The main differences between offline sync and real-time sync are as follows:
- Offline synchronization requires corresponding scheduling information to be configured
- Offline task submission is triggered  by the scheduling system instead of manager
The interaction process with the scheduling system is as follows:
- Register the scheduling information at the point of approval 
- The scheduling system generates an instance to submit Flink batch tasks by InLong callback.
Design principles for the association between synchronization tasks and the scheduling system are as follows:
- Management of task configuration and scheduling …

[INLONG-9862][Manager] Support submit flink job for offline sync

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/ClientUtils.java

- Fixes #9876
optimize the format of error message
optimize the format of error message. 
With this pul request, the error msg will be `Request to Inlong  failed: Inlong group already exists` instead of 
`Request to Inlong Inlong group already exists failed: null`

[INLONG-9876][Manager] optimize the format of error message

---

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java

[INLONG-9858][Agent] Increase local read and write capabilities for module config
- Fixes #9858
Increase local read and write capabilities for module config
Increase local read and write capabilities for module config
*(example:)*

[INLONG-9858][Agent] Increase local read and write capabilities for module config

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarQueueResourceOperator.java

- Fixes #9902
Data preview supports pulsar multi cluster.
Data preview supports pulsar multi cluster.

[INLONG-9902][Manager] Data preview supports pulsar multi cluster

---

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java

[INLONG-9859][Agent] Increase installation package download capability and local MD5 computing power
- Fixes #9859
Increase installation package download capability and local MD5 computing power
Increase installation package download capability and local MD5 computing power
*(example:)* …

[INLONG-9859][Agent] Increase installation package download capability and local MD5 computing power

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditReporterImpl.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderManager.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/util/AuditDimensions.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/util/AuditValues.java
inlong-audit/sql/apache_inlong_audit.sql
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/audit/AuditUtils.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/metrics/audit/AuditUtils.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SinkMetricData.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceMetricData.java
inlong-tubemq/tubemq-server/src/main/java/org/apache/inlong/tubemq/server/broker/stats/audit/AuditUtils.java

- Fixes #9904
*Flink checkpoint requires the audit SDK to support the isolation of audit data and ensure that each checkpoint cycle can be accurately reconciled.*
*The audit SDK supports checkpoint by adding resource isolation logic.*

[INLONG-9904][Audit] SDK support checkpoint feature

---

inlong-audit/audit-service/src/main/java/entities/AuditCycle.java
inlong-audit/audit-service/src/main/java/entities/Request.java
inlong-audit/audit-service/src/main/java/entities/SourceEntities.java
inlong-audit/audit-service/src/main/java/entities/StartEndTime.java
inlong-audit/audit-service/src/main/java/entities/StatData.java

- Fixes #9907 
*The audit-service service is a brand-new service that supports audit peripheral functions, including real-time aggregation, backtracking aggregation, openapi, etc.*
*Audit-service add codes of entities.*

[INLONG-9907][Audit] Audit-service add codes of entities

---

inlong-agent/bin/agent-config.sh
inlong-agent/conf/agent.properties

[INLONG-9922][Agent] Add a configuration copy script to copy the configuration from the installer to the agent
- Fixes #9922
Enable the installer to automatically synchronize configuration with the agent during installation
Add a configuration copy script to copy the configuration from the installer to the agent
no doc needed

[INLONG-9922][Agent] Add a script to copy the configuration from the installer to the agent

---

NOTICE
licenses/NOTICE
licenses/inlong-agent/NOTICE
licenses/inlong-audit/NOTICE
licenses/inlong-dashboard/NOTICE
licenses/inlong-dataproxy/NOTICE
licenses/inlong-manager/NOTICE
licenses/inlong-sort-connectors/NOTICE
licenses/inlong-sort-standalone/NOTICE
licenses/inlong-sort/NOTICE
licenses/inlong-tubemq-manager/NOTICE
licenses/inlong-tubemq-server/NOTICE

- Fixes #9934 
Copyright date in NOTICE is still 2019-2023, which needs updating.
update Copyright date in NOTICE to 2024

[INLONG-9934][doc] update copyright date to 2024

---

inlong-audit/audit-service/src/main/java/config/ConfigConstants.java
inlong-audit/audit-service/src/main/java/config/SqlConstants.java
inlong-audit/audit-service/src/main/java/elector/ElectorChangeListenerImpl.java
inlong-audit/audit-service/src/main/java/elector/api/Selector.java
inlong-audit/audit-service/src/main/java/elector/api/SelectorFactory.java
inlong-audit/audit-service/src/main/java/elector/impl/DBDataSource.java
inlong-audit/audit-service/src/main/java/elector/impl/ElectorImpl.java
inlong-audit/audit-service/src/main/java/elector/impl/SelectorImpl.java

- Fixes #9928 
*Audit-service performs HA election through mysql to improve the high availability of the system.*
*Audit-service support HA active and backup.*

[INLONG-9928][Audit] Audit-service HA election through mysql

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarQueueResourceOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/QueryCountDownLatch.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/QueryLatestMessagesRunnable.java

- Fixes #9936 
When clusterTag have multiple Pulsar clusters and the amount of data is little, reading the data preview data from only one Pulsar cluster may result in no data being found. If polling all Pulsar clusters, it may cause query timeouts. In this case, it is necessary to query all Pulsar clusters in parallel to avoid timeout exceptions.
*(example:)* …

[INLONG-9936][Manager] Support for parallel acquisition of data preview data from multiple Pulsar clusters

---

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ManagerFetcher.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java

[INLONG-9946][Agent] Verify the return code, only proceed with the subsequent process if the return code is successful
- Fixes #9946
The manager will verify MD5, and if no changes are found in MD5, a no update return code will be returned
Verify the return code, only proceed with the subsequent process if the return code is successful
no doc needed

[INLONG-9946][Agent] Verify the return code, only proceed with the subsequent process if the return code is successful

---

inlong-dashboard/src/ui/pages/GroupDetail/Audit/index.tsx

- Fixes #9950
The end time and start time used by the audit query are the same.
Fix the end time.

[INLONG-9950][Dashboard] Fix audit query using incorrect end time

---

inlong-dashboard/src/ui/locales/cn.json
inlong-dashboard/src/ui/locales/en.json
inlong-dashboard/src/ui/pages/Clusters/NodeEditModal.tsx

- Fixes #9944 
Add `Agent` and `Installer` for Agent Cluster Node.
1. Get node info and only keep the first element to `Agent` and give the rest to the `Installer`.

[INLONG-9944][Dashboard] Add Agent and Installer for Agent Cluster Node

---

inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.13/src/test/java/org/apache/inlong/sort/tests/utils/FlinkContainerTestEnv.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/Kafka2StarRocksTest.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/Mongodb2StarRocksTest.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/Mysql2StarRocksTest.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/Postgres2StarRocksTest.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/RedisToRedisTest.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/Sqlserver2StarRocksTest.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/utils/FlinkContainerTestEnv.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/utils/FlinkContainerTestEnvJRE11.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/utils/FlinkContainerTestEnvJRE8.java

- [INLONG-9402][Sort] Solve errors in UT test logs for sort-end-to-end-tests, but UT results show as successful
- Fixes #9402 
As issue #9402 description, there were two case encountered error but the final result show as successful.
- Case1
Question: Warning: Illegal reflective access by org.apache.flink.api.java.ClosureCleaner (file:/opt/flink/lib/flink-dist-1.15.4.jar) to field java.lang.String.value.
Reason: This error message indicates an illegal reflective access operation occurring while using Apache Flink, which is an open-source framework for processing streaming and batch data. Specifically, the error occurs because org.apache.flink.api.java.ClosureCleaner attempts to access the value field of the java.lang.String class illegally. This is more common with higher versions of …

[INLONG-9402][Sort] Solve errors in UT test logs for sort-end-to-end-tests, but UT results show as successful

---

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarFederationSinkContext.java

- Fixes #9965 
The calculation of pulsar sink node duration is totally the same with the whole process duration.
The node duration should be sendTime - fetchTime
*(example:)*
- If a …

[INLONG-9965][Sort] Fix wrong node duration of SortStandalone Pulsar Sink

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/KafkaSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/PulsarSource.java

[INLONG-9969][Agent] Release the memory semaphore of the source only when the data is placed in the queue
- Fixes #9969
Due to the immediate release of semaphores after data is read from the data source, memory control cannot be achieved.
Release the memory semaphore of the source only when the data is placed in the queue
*(example:)*
no doc need

[INLONG-9969][Agent] Release the memory semaphore of the source only when the data is placed in the queue

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/KafkaSource.java
inlong-dashboard/src/plugins/sources/defaults/Kafka.ts
inlong-dashboard/src/plugins/sources/defaults/Pulsar.ts
inlong-dashboard/src/ui/locales/en.json

- Fixes #9963 
`Kafka` and `Pulsar source` are missing agent IP fields.
Add agent IP field to `Kafka` and `Pulsar source`

[INLONG-9963][Dashboard][Agent] Add agentIp fields to Kafka and Pulsar source

---

inlong-common/src/main/java/org/apache/inlong/common/enums/IndicatorType.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/AuditBaseEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/AuditBaseEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/AuditBaseEntityMapper.xml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/audit/AuditBaseResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/AuditService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java
inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/changes-1.12.0.sql

- Fixes #9976
Support multiple types of audit indicator queries.
Support multiple types of audit indicator queries.

[INLONG-9976][Manager] Support multiple types of audit indicator queries

---

inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/cache/AbstractCache.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/cache/DayCache.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/channel/DataQueue.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/ConfigConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/Configuration.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/OpenApiConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/SqlConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/entities/JdbcConfig.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/entities/StatData.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/main/Application.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/selector/SelectorChangeListenerImpl.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/selector/api/SelectorChangeListener.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/selector/api/SelectorConfig.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/selector/api/SelectorFactory.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/selector/impl/DBDataSource.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/selector/impl/SelectorImpl.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/selector/task/DBMonitorTask.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/ApiService.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/EtlService.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/sink/CacheSink.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/sink/JdbcSink.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/source/JdbcSource.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/utils/JdbcUtils.java
inlong-audit/bin/service-start.sh
inlong-audit/bin/service-stop.sh
inlong-audit/conf/audit-service.properties
inlong-audit/pom.xml
inlong-audit/sql/audit-service/apcache_inlong_audit_aggregate.sql

- Fixes #9977
*In order to improve the concurrency and decoupling of audit external services, audit-service needs to provide a complete set of external openapi.*
*By adding an http interface to provide external audit data, there is less coupling with other modules..*

[INLONG-9977][Audit] Audit-service increases the capabilities of openapi

---

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcBatchingOutputFormat.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcMultiBatchingOutputFormat.java

- [INLONG-XYZ][Sort] Add if statement to solve continuously printing logs
- Fixes #9925 
The log keeps printing the same message. This message should be printed when there is update or delete operation for ck and should not appear so many times.And because it continuously write log files, the disk will not has free space soon.
I found that the program through JDBC module continuously  batch write to clickhouse. But when batch count equals 0, the program still execute batch write command. So the log nonstop print. I add  if statement. Only batch count greater than 0, it will execute batch write command.

[INLONG-9925][Sort] Add if statement to solve continuously printing logs

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/PulsarProvider.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/PulsarExtractNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/PulsarExtractNodeTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/PulsarSqlParserTest.java
inlong-sort/sort-dist/pom.xml
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarDynamicTableFactory.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableSource.java

- Fixes #9972
According to https://pulsar.apache.org/docs/next/security-jwt/
Some pulsar cluster have authentication opened in some cases, the sort connector should support authentication
Added two parameter used in authentication
1、pulsar client auth plugin class name, e.g. org.apache.pulsar.client.impl.auth.AuthenticationToken
2、pulsar client auth params, the value should be compatible with the clientAuthPluginClassName, see also in 
https://pulsar.apache.org/docs/next/security-jwt/
Tested in pulsar cluster with authentication and the ExtractNode teste in PulsarSqlParserTest

[INLONG-9972][Sort] Pulsar connector support authentication when connecting to Pulsar cluster

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/PulsarProvider.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSource.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSourceDTO.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSourceRequest.java

- Fixes #9985
Support authentication params for pulsar source.
Support authentication params for pulsar source.

[INLONG-9985][Manager] Support authentication params for pulsar source

---

inlong-manager/manager-service/pom.xml

- Fixes #9980 
The manager project does not use derby.jar, and the inclusion of derby.jar in the project may add new security shares, so remove it.

[INLONG-9980][Manager] Remove the derby.jar file from the manager project

---

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java

[INLONG-9987][Agent] Fix the issue of deleting the first digit when the first digit in MD5 is 0
- Fixes #9987
Fix the issue of deleting the first digit when the first digit in MD5 is 0
No longer using BigInteger to convert md5 values
*(example:)*
No doc needed

[INLONG-9987][Agent] Fix the issue of deleting the first digit when the first digit in MD5 is 0

---

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java

[INLONG-9990][Agent] Avoid MD5 calculation functions directly returning
- Fixes #9990
Avoid MD5 calculation functions directly returning
Avoid MD5 calculation functions directly returning
*(example:)*
No doc needed

[INLONG-9990][Agent] Avoid MD5 calculation functions directly returning

---

inlong-common/src/main/java/org/apache/inlong/common/constant/Constants.java
inlong-common/src/main/java/org/apache/inlong/common/msg/AttributeConstants.java

- Fixes #9993
*There is a scenario where data is re-recorded in the agent. Since each re-record needs to be audited and reconciled, each module of inlong needs to add an audit_version attribute uniformly.*
*The audit_version information is added to the attr attribute by the agent and transparently transmitted to DataProxy and sort.*

[INLONG-9993][Audit] The data protocol adds an audit_version attribute

---

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/CommonInstance.java

[INLONG-9997][Agent] Handling situations where the installation package md5 remains unchanged and other parameters md5 change
- Fixes #9997
Handling situations where the installation package md5 remains unchanged and other parameters md5 change
Save config and restart the module
*(example:)*
No doc needed

[INLONG-9997][Agent] Handling situations where the installation package md5 remains unchanged and other parameters md5 change

---

inlong-dashboard/src/ui/pages/GroupDetail/Audit/config.tsx

- Fixes #10001 
The end date time on the audit page was initialized incorrectly, causing an error when selecting an audit item.
Fix the initial value label.

[INLONG-10001][Dashboard] Fix end date time initialization error on audit page

---

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java

[INLONG-9999][Agent] Handle scenarios where the module list is empty to prevent accidental deletion
- Fixes #9999
Handle scenarios where the module list is empty to prevent accidental deletion
Directly return when the module list is empty
*(example:)*
No doc needed

[INLONG-9999][Agent] Handle scenarios where the module list is empty to prevent accidental deletion

---

inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/consts/ConfigConstants.java
inlong-audit/audit-release/pom.xml
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditReporterImpl.java
inlong-audit/audit-service/pom.xml
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/cache/AbstractCache.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/cache/DayCache.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/cache/RealTimeQuery.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/ConfigConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/Configuration.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/OpenApiConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/SqlConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/entities/ApiType.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/entities/AuditCycle.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/entities/StatData.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/main/Application.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/ApiService.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/ConfigService.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/EtlService.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/sink/CacheSink.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/source/JdbcSource.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/utils/CacheUtils.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/utils/JdbcUtils.java
inlong-audit/sql/audit-service/apcache_inlong_audit_aggregate.sql

- Fixes #10003 
- Audit-service support querying multiple clickhouse/starrocks clusters at the same time.
- OpenAPI supports simultaneous real-time query of multiple data source clusters.
- OpenAPI supports minute, hour, day,getIps,getIds interface.
*Dynamically configure audit data source information through DB, and perform statistics and cache on multiple audit data sources simultaneously through configuration.*

[INLONG-10003][Audit] Audit-service supports multiple data source clusters

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/state/AbstractStateWrapper.java

[INLONG-8962][Agent] Fix the bug: before state and after state are the same in StateCallback.call
- Fixes #8962 
Fix the bug: before state and after state are the same in StateCallback.call
Store the before state as the param of  StateCallback.call
*(example:)*
No doc needed

[INLONG-8962][Agent] Fix the bug: before state and after state are the same in StateCallback.call

---

inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/WebBaseTest.java
inlong-manager/manager-web/src/test/java/org/apache/inlong/manager/web/controller/HeartbeatControllerTest.java

- Title Example: [INLONG-9883][Manager] Add unit test of HeartbeatController
- Fixes #9883 
Complete the pr #9887 
Add HeartbeatController, Modify assert statement condition

[INLONG-9883][Manager] Add unit test of HeartbeatController

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/audit/AuditResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/audit/AuditRunnable.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
inlong-manager/manager-web/src/main/resources/application-dev.properties
inlong-manager/manager-web/src/main/resources/application-prod.properties
inlong-manager/manager-web/src/main/resources/application-test.properties

- Fixes #10034
Support calling the audit service interface to query audit information.
Support calling the audit service interface to query audit information.

[INLONG-10034][Manager] Support calling the audit service interface to query audit information

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/file/ProxyMessageCache.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/CommonInstance.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/AbstractSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/AbstractTask.java

[INLONG-10035][Agent] Report audit data using the new SDK interface
- Fixes #10035
new audi sdk api #10016
Report audit data using the new SDK interface
Report audit data using the new SDK interface
*(example:)*
No doc needed

[INLONG-10035][Agent] Report audit data using the new SDK interface

---

inlong-tubemq/tubemq-client-twins/tubemq-client-go/config/config.go
inlong-tubemq/tubemq-client-twins/tubemq-client-go/log/config.go

- Title Example: [INLONG-8791][TubeMQ] Add log level and log path configuration API to Tubemq-client-go
- Fixes #8791 
The PR #8793 has a little problem, I solve it.
- Add validation to SetLogPath and SetLogLeve.
- Add log level and log path configuration API.

[INLONG-8791][TubeMQ] Add log level and log path configuration API to Tubemq-client-go

---

inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/field/format/DateFormatInfo.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/field/format/TimeFormatInfo.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/field/format/TimestampFormatInfo.java

- Fixes #10041 
The serialization and deserialization of the Timestamp, Time, and Date format of Sort will produce unexcepted results because SimpleDateFormatter is thread-unsafe.
*(example:)* …

[INLONG-10041][Sort] Thread unsafety of time format serialization

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/file/LogFileTask.java

[INLONG-10047][Agent] Fix the bug in the logic for judging the completion status of the supplementary recording task
- Fixes #10047
Fix the bug in the logic for judging the completion status of the supplementary recording task
Need to simultaneously check if the local instance queue is empty
*(example:)*
No doc needed

[INLONG-10047][Agent] Fix the bug in the logic for judging the completion status of the supplementary recording task

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes #10051 
improve the pull request template, make the template more clear
hide prompt information of template in formal pull request
*(example:)*

[INLONG-10051][Github] Improve the pull request template

---

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java
inlong-agent/agent-installer/src/test/java/installer/TestModuleManager.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/installer/ConfigResult.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java

Fixes #10059
There are an bug in the comparison of installation package md5, an exception will occur when md5 is null
Use Objects.equals instead of equals to handle null md5
*(example:)*
No doc needed

[INLONG-10059][Agent] Fix the exception of installation package comparison

---

.github/workflows/ci_build.yml
inlong-distribution/pom.xml
inlong-distribution/src/main/assemblies/sort-connectors-v1.18.xml
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pom.xml
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/pom.xml
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableFactory.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableOptionUtils.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableOptions.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableValidationUtils.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/resources/META-INF.services/org.apache.flink.table.factories.Factory
licenses/inlong-sort-connectors/LICENSE

Fixes #10053 
Add support of pulsar connectors for flink 1.18
- create new modules for connectors-v1.18 and connector-pulsar-v1.18
- make sure PulsarTableOptions is compatible with `PulsarExtractNode`
*(example:)*

[INLONG-10053][Sort] Support flink-connector-pulsar based on flink 1.18

---

inlong-manager/manager-plugins/base/pom.xml
inlong-manager/manager-plugins/base/src/main/assembly/assembly.xml
inlong-manager/manager-plugins/manager-plugins-flink-v1.18/pom.xml
inlong-manager/manager-plugins/manager-plugins-flink-v1.18/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkClientService.java
inlong-manager/manager-plugins/pom.xml

Fixes #10056
add support for new manager plugin based on flink 1.18
- add `FlinkClientService` for flink 1.18
- support assemble for flink 1.18 plugin
- support build plugins with different profiles(v1.13, v1.15, v1.18)
*(example:)*

[INLONG-10056][Manager] Support new manager plugin for flink 1.18

---

inlong-common/src/main/java/org/apache/inlong/common/enums/InlongCompressType.java
inlong-dataproxy/conf/common.properties
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/CommonConfigHolder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/DefaultEventHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/common/EventHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSink.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/MessageQueueZoneSinkContext.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/sink/mq/PackProfile.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/SourceConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/utils/AddressUtils.java
inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/config/holder/TestCommonConfigHolder.java
inlong-dataproxy/dataproxy-source/src/test/resources/common.properties

Fixes #10066 
1. Uniformly configure the Key to lowercase, and use "." to classify;
2. Configure pre-reading according to different types;
3. Optimize the acquisition of configuration values, and check whether key configurations are empty and legal;

[INLONG-10066][DataProxy] Optimize the related configuration settings in the CommonConfigHolder.java file

---

inlong-dashboard/src/ui/pages/GroupDetail/Info/index.tsx
inlong-dashboard/src/ui/pages/SynchronizeDetail/Info/index.tsx

Fixes #10082 
The pulsar tenant field is missing when updating group info
Add `pulsarTenant` when updating group info and mqType is `PULSAR`

[INLONG-10082][Dashboard] Fixed missing pulsar tenant field when updating group info

---

inlong-distribution/src/main/assemblies/sort-connectors-v1.18.xml
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/jdbc/pom.xml
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/GenericJdbcSinkFunction.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/JdbcOutputFormat.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/internal/TableJdbcUpsertOutputFormat.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDynamicTableFactory.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcDynamicTableSink.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/table/JdbcOutputFormatBuilder.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/jdbc/src/main/resources/META-INF.services/org.apache.flink.table.factories.Factory
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pom.xml
licenses/inlong-sort-connectors/LICENSE

Fixes #10055 
Add support of pulsar connectors for flink 1.18
- create new module connector-jdbc-v1.18
- add audit metrics for jdbc sink
*(example:)*

[INLONG-10055][Sort] Support flink-connector-jdbc based on flink 1.18

---

inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableFactory.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableOptionUtils.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableOptions.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableValidationUtils.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/source/PulsarTableDeserializationSchema.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/source/PulsarTableDeserializationSchemaFactory.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/source/PulsarTableSource.java
licenses/inlong-sort-connectors/LICENSE

Fixes #10069 
add support audit metrics for sort-connector-pulsar-1.18 as 1.13 and 1.15 does.
- add support audit metrics(only for source now) for sort-connector-pulsar-1.18
- add LICENSE
*(example:)*

[INLONG-10069][Sort] Support audit metrics for sort-connector-pulsar-1.18

---

inlong-audit/audit-docker/Dockerfile
inlong-audit/audit-docker/audit-docker.sh
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/config/JdbcConfig.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/config/StoreConfig.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/db/entities/JdbcDataPo.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/ClickHouseService.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/ElasticsearchService.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/InsertData.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/JdbcService.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/MySqlService.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/consume/BaseConsume.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/consume/PulsarConsume.java
inlong-audit/conf/application.properties
inlong-audit/conf/audit-service.properties

- Fixes #10099 
The audit-store service supports logging into all storages that support JDBC.
By customizing the JDBC driver class, the audit-store service supports warehousing all storage that supports JDBC.

[INLONG-10099][Audit] Audit-store adds the general JDBC sink capability

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/audit/AuditUtils.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/httpMsg/HttpMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/v0msg/AbsV0MsgCodec.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/v0msg/CodecBinMsg.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/v0msg/CodecTextMsg.java

Fixes #10111 
1. Read the auditVersion field value from the reported message;
2. Write this field to the Audit record when the reception and sending are successful.

[INLONG-10111][DataProxy] Add auditVersion field processing

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/kafka/KafkaDataNodeOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/kafka/KafkaSinkOperator.java

- Fixes #10105 
Fix sort standalone get kafka config error
The details can be found at [#10105 ](https://github.com/apache/inlong/issues/10105).

[INLONG-10105][Manager] Fix sort standalone get kafka config error

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/OffsetProfile.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/file/OffsetAckInfo.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/file/ProxyMessage.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/KafkaSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/MongoDBSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/PulsarSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/AbstractSource.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/filecollect/TestSenderManager.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestLogFileSource.java

Fixes #10115
Offset needs to be changed to save in string format because some data sources have non integer positions
Change the offset save format from long to string
*(example:)*
No doc needed

[INLONG-10115][Agent] Change the offset save format from long to string

---

inlong-sdk/transform-sdk/pom.xml
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/PbNode.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/PbSourceData.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/PbSourceDecoder.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/TransformException.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/PbSourceInfo.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/TransformProcessor.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/ColumnParser.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/pojo/TestTransformConfig.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformProcessor.java

[SDK] Support to transform from PB protocol to CSV/KV protocol by single SQL
Fixes #10117 
Parent issue: 
#10022
Support to transform from PB protocol to CSV/KV protocol by single SQL
- Support to parse the following PB protocol
syntax = "proto3";
package test;
message SdkMessage {
bytes msg = 1;
int64 msgTime = 2;
map<string, string> extinfo = 3;
}
message SdkDataRequest {
string sid = 1;
repeated SdkMessage msgs = 2;
uint64 packageID = 3;
}
- Support to parse the following PB data
SdkDataRequest.Builder requestBuilder = SdkDataRequest.newBuilder();
requestBuilder.setSid("sid");
requestBuilder.setPackageID(1);
{
SdkMessage.Builder msgBuilder = SdkMessage.newBuilder();
msgBuilder.setMsgTime(1713243918000L);
msgBuilder.setMsg(ByteString.copyFrom("msgValue4".getBytes())); …

[INLONG-10117][SDK] Support to transform from PB protocol to CSV/KV protocol by single SQL

---

pom.xml

Fixes #10126 
`mvn clean compile package` error : com.sleepycat.je version 7.3.7 not found
Change *com.sleepycat.je* version to resolve maven compile error.
- [✅] This change is a trivial rework/code cleanup without any test coverage.

[INLONG-10126][TubeMQ] Fix maven sleepycat je.version 7.3.7 can not found

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/TransformProcessor.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/EqualsToOperator.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/GreaterThanEqualsOperator.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/GreaterThanOperator.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/MinorThanEqualsOperator.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/NotEqualsToOperator.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/AdditionParser.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/DivisionParser.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/MultiplicationParser.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/ParenthesisParser.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/SubtractionParser.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformProcessor.java

Fixes #10129 
Transform SQL support +-*/ operations
 
- Support to parse the following PB protocol
syntax = "proto3";
package test;
message SdkMessage {
bytes msg = 1;
int64 msgTime = 2;
map<string, string> extinfo = 3;
}
message SdkDataRequest {
string sid = 1;
repeated SdkMessage msgs = 2;
uint64 packageID = 3;
}
- Support to parse the following PB data
SdkDataRequest.Builder requestBuilder = SdkDataRequest.newBuilder();
requestBuilder.setSid("sid");
requestBuilder.setPackageID(1);
{
SdkMessage.Builder msgBuilder = SdkMessage.newBuilder();
msgBuilder.setMsgTime(1713243918000L);
msgBuilder.setMsg(ByteString.copyFrom("msgValue4".getBytes()));
msgBuilder.putExtinfo("key", "value");
SdkMessage msgObj = msgBuilder.build();
requestBuilder.addMsgs(msgObj);
}
{
SdkMessage.Builder msgBuilder = …

[INLONG-10129][SDK] Transform SQL support +-*/ operations

---

.github/workflows/ci_build.yml
.github/workflows/ci_chart_test.yml
.github/workflows/ci_check_format.yml
.github/workflows/ci_check_license.yml
.github/workflows/ci_check_pr_title.yml
.github/workflows/ci_docker.yml
.github/workflows/ci_ut.yml
.github/workflows/ci_ut_flink13.yml
.github/workflows/ci_ut_flink15.yml
.github/workflows/codeql_analysis.yml

Fixes #10138
Node.js 16 actions are deprecated, bump actions/checkout@v3, actions/setup-java@v3, actions/cache@v3 to v4
Node.js 16 actions are deprecated, bump actions/checkout@v3, actions/setup-java@v3, actions/cache@v3 to v4

[INLONG-10138][CI] Bump actions/checkout@v3, actions/setup-java@v3, actions/cache@v3 to v4

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ConcatFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/NowFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformProcessor.java

Fixes #10130 
Transform SQL support string concat function
- Support to parse the following PB protocol
syntax = "proto3";
package test;
message SdkMessage {
bytes msg = 1;
int64 msgTime = 2;
map<string, string> extinfo = 3;
}
message SdkDataRequest {
string sid = 1;
repeated SdkMessage msgs = 2;
uint64 packageID = 3;
}
- Support to parse the following PB data
SdkDataRequest.Builder requestBuilder = SdkDataRequest.newBuilder();
requestBuilder.setSid("sid");
requestBuilder.setPackageID(1);
{
SdkMessage.Builder msgBuilder = SdkMessage.newBuilder();
msgBuilder.setMsgTime(1713243918000L);
msgBuilder.setMsg(ByteString.copyFrom("msgValue4".getBytes()));
msgBuilder.putExtinfo("key", "value");
SdkMessage msgObj = msgBuilder.build();
requestBuilder.addMsgs(msgObj);
}
{
SdkMessage.Builder …

[INLONG-10130][SDK] Transform SQL support string concat function

---

inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/ConfigService.java

- Fixes #10147 
When the audit system uses MySQL as the storage, the audit service can use the same MySQL configuration as the storage system, making it more convenient to use.
If the audit data source is not configured in the service configuration table audit_source_config, use the same MySQL configuration as the service.

[INLONG-10147][Audit] Less usage costs when the Audit uses the MySQL as storage

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/CsvSourceDecoder.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/CsvSinkEncoder.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/DefaultSinkData.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/KvSinkEncoder.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/SinkData.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/CsvSinkInfo.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/CsvSourceInfo.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/KvSinkInfo.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/KvSourceInfo.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/TransformProcessor.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformProcessor.java

Fixes #10154 
[SDK] Support to transform CSV/KV data to CSV/KV data without field list configuration
- Support to parse the following CSV string, the delimiter is '|', without field list configuration.
2024-04-28 00:00:00|ok
- Generate the final data by the following SQL, using $1 mark the first field.
select $1 ftime,$2 extinfo from source where $2='ok'
- The final data is the following string, using alias name in SQL as field key.
ftime=2024-04-28 00:00:00&extinfo=ok
- Support to parse the following KV string, without field list configuration.
ftime=2024-04-28 00:00:00&extinfo=ok
- Generate the final data by the following SQL.
select ftime,extinfo from source where extinfo='ok'
- The final data is the following CSV string, the delimiter is '|', , without field list configuration, using …

[INLONG-10154][SDK] Support to transform CSV/KV data to CSV/KV data without field list configuration

---

inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/ConfigConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/OpenApiConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/source/JdbcSource.java

- Fixes #10157
Use a custom thread pool instead of the system thread pool.
Use a custom thread pool instead of the system thread pool.

[INLONG-10157][Audit] Use a custom thread pool instead of the system thread pool

---

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/MetricOption.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SinkMetricData.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceMetricData.java

Prepare a Pull Request
- [INLONG-10152][Sort] Refactor MetricOption code structure.
- Fixes #10152 
The MetricOption constructor Does not conform to the single responsibility design pattern，check arguments not exist in constructor will make code clearly.
Adjust constructor and move check arguments code statement.

[INLONG-10152][Sort] Refactor MetricOption code structure.

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/go.mod
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/go.sum

- [INLONG-10162][DataProxy] Upgrade golang.org/x/net to version 0.23.0
- Fixes #10162 
An attacker may cause an HTTP/2 endpoint to read arbitrary amounts of header data by sending an excessive number of CONTINUATION frames. Maintaining HPACK state requires parsing and processing all HEADERS and CONTINUATION frames on a connection. When a request's headers exceed MaxHeaderBytes, no memory is allocated to store the excess headers, but they are still parsed. This permits an attacker to cause an HTTP/2 endpoint to read arbitrary amounts of header data, all associated with a request which is going to be rejected. These headers can include Huffman-encoded data which is significantly more expensive for the receiver to decode than for an attacker to send. The fix sets a limit on the amount of …

[INLONG-10162][DataProxy] Upgrade golang.org/x/net to version 0.23.0.

---

inlong-sdk/sdk-common/src/main/java/org/apache/inlong/sdk/commons/protocol/ProxyEvent.java

[INLONG-10184][SDK] The header in ProxyEvent need contain both 'rtms' and 'auditVersion'.

---

docker/docker-compose/docker-compose.yml
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java
inlong-agent/agent-docker/Dockerfile
inlong-agent/agent-docker/README.md
inlong-agent/conf/agent.properties

Fixes #10091
The agent does not listen to the port, and the relevant code is useless
Delete useless code
*(example:)*
No doc needed

[INLONG-10091][Agent] Delete the useless code related to 8008 listen port

---

inlong-dashboard/src/plugins/clusters/common/ClusterDefaultInfo.ts

Fixes #10179 
The drop-down box in the Create Cluster modal does not need to be of type All
Remove the All-type in the Create Cluster modal

[INLONG-10179][DashBoard] Remove the All types In cluster management

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/kafka/KafkaResourceOperator.java

- Fixes #10204 
Kafka sink supports automatic allocation of sort standalone cluster
The details can be found at [#10204 ](https://github.com/apache/inlong/issues/10204).

[INLONG-10204][Manager] Kafka sink supports automatic allocation of sort standalone cluster

---

inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/file/ConfigManager.java
inlong-audit/audit-docker/audit-docker.sh
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java
inlong-audit/conf/application.properties

Fixes #10201 
Renamed configuration variables for clarity
- Rename configuration variables
- Rename audit docker variables

[INLONG-10201][Audit] Renamed configuration variables for clarity

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/plugin/Instance.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskManager.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/instance/MockInstance.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/CommonInstance.java

Fixes #10189
Handling data proxy SDK initialization exceptions
1 Add instance heartbeat timeout detection
2 Clean up timeout instances and wait for retry
3 Move the source startup operation from the initialization function to the main Instance thread
*(example:)*
No doc needed

[INLONG-10189][Agent] Handling SDK initialization exceptions

---

inlong-agent/agent-installer/assembly.xml
inlong-agent/agent-installer/environment/init.sh

Fixes #10210
The installer needs to add a script for environment initialization
Add a script for environment initialization
*(example:)*
No doc needed

[INLONG-10210][Agent] Add a script for environment initialization

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/doris/DorisDataNodeOperator.java

Fixes #10076 
Doris data node supports test connections.
Add test connections for Doris data node.

[INLONG-10076][Manager] Doris data node supports test connections

---

inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/SortClusterConfig.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/SortTaskConfig.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/DataFlowConfig.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsIdConfig.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsSink.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsSinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/v2/SinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/v2/SortSdkSource.java
inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/cls/TestClsIdConfig.java
inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/cls/TestDefaultEvent2LogItemHandler.java

[INLONG-10208][Sort] ClsSink support unified configuration

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/sqlserver/RowDataDebeziumDeserializeSchema.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/sqlserver/SqlServerTableSource.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/sqlserver/SqlserverTableFactory.java
licenses/inlong-sort-connectors/LICENSE

- [INLONG-10194][Sort] Sqlserver connectors support audit ID
- Fixes https://github.com/apache/inlong/issues/10194
- parent issue: https://github.com/apache/inlong/issues/8803
Sqlserver connector not support audit function. So this pr will make it support audit function.
Modify Sqlserver connector source.when source/sink receive data, it will send audit information at same time.Some implement are as follows:
Program will get the audit information from the incoming sql statement and pass it to the deserialization classes. During  deserialization, the program will report the number of data received.

[INLONG-10194][Sort] Sqlserver connector support audit ID

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/CMakeLists.txt
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/build.sh
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/third_party/CMakeLists.txt

- Fixes #10221
DataProxy SDK of cpp supports automatic installation of log4cplus components.
In the CMake file CMakeLists.txt, add the automatic installation of log4cplus.

[INLONG-10221][SDK] DataProxy SDK of cpp supports automatic installation of log4cplus components

---

inlong-dashboard/src/ui/pages/GroupDetail/Audit/config.tsx
inlong-dashboard/src/ui/pages/ModuleAudit/IdModule/config.tsx
inlong-dashboard/src/ui/pages/ModuleAudit/IpModule/config.tsx

Fixes #10226
Audit items cannot be searched.
Although filtering is performed, the option is the filtered value, but the page is rendered before filtering, causing it to not be displayed.
Use `Ant Design`'s filter function to perform local searches

[INLONG-10226][Dashboard] Fix audit item search failure

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/mysql/MySqlTableSource.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/mysql/MysqlTableFactory.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/mysql/RowDataDebeziumDeserializeSchema.java
licenses/inlong-sort-connectors/LICENSE

- [INLONG-10238][Sort] Mysql connectors support audit ID
- Fixes https://github.com/apache/inlong/issues/10238
- parent issue: https://github.com/apache/inlong/issues/8803
Mysql connector not support audit function. So this pr will make it support audit function.
Modify Mysql connector source.when source receive data, it will send audit information at same time.Some implement are as follows:
Program will get the audit information from the incoming sql statement and pass it to the deserialization classes. During deserialization, the program will report the number of data received.

[INLONG-10238][Sort] MySQL connector support audit ID

---

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditIdEnum.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditReporterImpl.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/entity/AuditInformation.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/entity/AuditType.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/entity/FlowType.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/exceptions/AuditTypeNotExistException.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/util/AuditManagerUtils.java
inlong-audit/audit-sdk/src/test/java/org/apache/inlong/audit/util/AuditManagerUtilsTest.java

- Fixes #10242
As there are more and more Audit items, it becomes more and more troublesome for the Manager to manage Audit items, so the Audit SDK is needed for unified management.
The Audit SDK uniformly generates audit item IDs according to rules and manages them uniformly.

[INLONG-10242][Audit] Audit SDK compatible with InLong Manager to manage audit items

---

inlong-tubemq/tubemq-core/src/main/java/org/apache/inlong/tubemq/corerpc/utils/MixUtils.java

Fixes #9613 
In the unwrapException function, check whether clazz belongs to Throwable class or its subclass to avoid Remote Code Execution (RCE) issues.

[INLONG-9613][TubeMQ] Adjust FATAL type error return content, without carrying class name

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/ClientFactory.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InLongScheduleClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InLongScheduleApi.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ErrorCodeEnum.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ScheduleStatus.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/ScheduleEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/ScheduleEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/ScheduleEntityMapper.xml
inlong-manager/manager-dao/src/test/java/org/apache/inlong/manager/dao/mapper/ScheduleEntityTest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/schedule/ScheduleInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/schedule/ScheduleInfoRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/schedule/ScheduleService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/schedule/ScheduleServiceImpl.java
inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/changes-1.13.0.sql
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InLongSchedulerController.java

Fixes #10247 
Add metadata management of schedule information for offline sync.
1. define key properties of  schedule info
2. support  CURD for schedule information 
3. support managing of schedule info using manager client
- inlong-manager/manager-dao/src/test/java/org/apache/inlong/manager/dao/mapper/ScheduleEntityTest.java

[INLONG-10247][Manager]  Support schedule information management for offline sync

---

inlong-audit/audit-docker/audit-docker.sh
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/config/JdbcConfig.java
inlong-audit/conf/application.properties

- Fixes #10263
Solve the conflict between the jdbc.url parameter of Audit Store and the container environment variable.
Audit Store replacement parameter name of jdbc.url to audit.store.jdbc.url.

[INLONG-10263][Audit] Solve the conflict between the jdbc.url parameter of Audit Store and the container environment variable

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/file/ProxyMessageCache.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/OffsetManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/CommonInstance.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/AbstractSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/AbstractTask.java

Fixes #10268 
Using task ID as the data version can result in inconsistent data versions across different machines
Get the data version from the auditVersion field, this field is globally controlled by the Manager, and the data versions between different machines can be kept consistent
*(example:)*
No doc needed

[INLONG-10268][Agent] Get the data version from the auditVersion field

---

inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/cache/RealTimeQuery.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/source/JdbcSource.java
inlong-audit/audit-service/src/test/java/utils/CacheUtilsTest.java

- Fixes #10274
The OpenAPI of Audit Service returns the average transmission time.
The OpenAPI of Audit Service returns the average transmission time instead of the total transmission time.

[INLONG-10274][Audit] The OpenAPI of Audit Service returns the average transmission time

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/InstanceProfile.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/file/ProxyMessageCache.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/OffsetManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/AbstractSource.java

Fixes #10281 
Real time file collection need to take the current time as the data time
Real time file collection uses the current time as the audit time and data, and transmits it downstream
*(example:)*
No doc needed

[INLONG-10281][Agent] Real time file collection takes the current time as the data time

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/ServiceBaseTest.java

- Fixes #10290 
Prohibit groups that have not been successfully configured from obtaining dataproxy addresses.
Prevent dataproxy from sending data to MQ clusters without creating a topic.
Prohibit groups that have not been successfully configured from obtaining dataproxy addresses.
The manager determines whether to return dataproxy node information based on the group status.

[INLONG-10290][Manager] Prohibit groups that have not been successfully configured from obtaining dataproxy addresses

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mysql-cdc/pom.xml
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/mysql/MySqlTableSource.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/mysql/RowDataDebeziumDeserializeSchema.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/mysql/source/MySqlSource.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/mysql/source/MySqlSourceBuilder.java
licenses/inlong-sort-connectors/LICENSE

Fixes #10297
1、Move the initialization of audit operator to where the mysql reader initialized  (on flink cluster) 
2、Add mysql jdbc connector to fat jar 
3、 Add metrics report when delete data 
Test on flink connector with audit service open
Mysql: 
Starrocks:
Audit:

[INLONG-10297][Sort] Fix mysql connector cannot submit to flink cluster

---

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditReporterImpl.java
inlong-audit/audit-sdk/src/test/java/org/apache/inlong/audit/AuditReporterImplTest.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/SqlConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/ApiService.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/source/JdbcSource.java

- Fixes #10306 
Compatible with scenarios where the Audit Tag is empty
Compatible with scenarios where the Audit Tag is empty

[INLONG-10306][Audit] Compatible with scenarios where the Audit Tag is empty

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/AbstractTask.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/KafkaTask.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/MongoDBTask.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/PulsarTask.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/file/LogFileTask.java

Fixes #10302 
The Task base class needs to add an interface that limits the number of instances obtained
Add an interface for limiting the number of instances obtained
*(example:)*
No doc needed

[INLONG-10302][Agent] Add an interface for limiting the number of instances obtained

---

inlong-dashboard/src/ui/locales/cn.json
inlong-dashboard/src/ui/locales/en.json
inlong-dashboard/src/ui/pages/GroupDetail/OperationLog/config.tsx

Fixes #10314 
Add an operation time to the operation log table
Added an operation time column to the operation log table

[INLONG-10314][DashBoard] Add an operation time to the operation log table

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/PostgreSQLTask.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/PostgreSQLInstance.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/PostgreSQLSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/PostgreSQLTask.java
pom.xml

Fixes #10318
Add PostgreSQL data source for Agent
- Modify the variable names corresponding to `Agent` and `Manager`
- Read `PostgreSQL` data using `debezium`
- Upgrade `postgresql-jdbc` version to 42.4.5 to solve 
`java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer`

[INLONG-10318][Agent] Add PostgreSQL data source for Agent

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/pom.xml

[INLONG-10332][Sort] Relocation the google.protobuf
Fixes #10332 
com.google.protobuf not packge in iceberg.jar
pom.xml add relocation statement

[INLONG-10332][Sort] Relocate the google.protobuf in Iceberg Connector 

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/postgre/DebeziumChangeFetcher.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/postgre/DebeziumDeserializationSchema.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/postgre/DebeziumSourceFunction.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/postgre/PostgreSQLSource.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/postgre/PostgreSQLTableSource.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/postgre/RowDataDebeziumDeserializeSchema.java
licenses/inlong-sort-connectors/LICENSE

Fixes #10339
Make AuditOperator serialized before report audit information.
Some deserialization Code.

[INLONG-10339][Sort] Fix PostgreSQL AuditOperator not serialized

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/sqlserver/DebeziumChangeFetcher.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/sqlserver/DebeziumDeserializationSchema.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/sqlserver/DebeziumSourceFunction.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/sqlserver/RowDataDebeziumDeserializeSchema.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/sqlserver/SqlServerSource.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/sqlserver/SqlServerTableSource.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/sqlserver/SqlserverTableFactory.java
licenses/inlong-sort-connectors/LICENSE

Fixes #10338 
Make AuditOperator serialized before report audit information.
Some deserialization Code.

[INLONG-10338][Sort] Fix Sqlserver AuditOperator not serialized

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/Format.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/format/KvFormat.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/format/KvFormatTest.java
inlong-sort/sort-dist/pom.xml
inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/base/TableFormatUtils.java
inlong-sort/sort-formats/format-rowdata/format-rowdata-kv/src/main/java/org/apache/inlong/sort/formats/kv/KvFormatFactory.java

Fixes #10323
There is no kv format support in sort common module when deserializing data 
1、Add a Kv Format
2、Remove ROW_FORMAT_INFO in KvFormatFactory because ROW_FORMAT_INFO won't be passed and we can get field infos from Context.getDatatype();
Tested in tube -> sr

[INLONG-10323][Sort] Support Kv deserialization format in sort module

---

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditIdEnum.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/entity/AuditType.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/util/AuditManagerUtils.java

- Fixes #10379
Add HDFS Audit items in the Audit SDK
Add HDFS Audit items in the Audit SDK

[INLONG-10379][Audit] Add HDFS Audit items in the Audit SDK

---

inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/entities/AuditComponent.java
inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/file/ConfigManager.java
inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/heartbeat/Heartbeat.java
inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/node/Application.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/cache/AuditProxyCache.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/OpenApiConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/SqlConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/entities/AuditProxy.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/entities/Heartbeat.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/heartbeat/ProxyHeartbeat.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/ApiService.java
inlong-audit/sql/apache_inlong_audit_mysql.sql

- Fixes #10321
Audit supports the Audit Proxy service discovery and management
In order to facilitate unified management of audit domain names, audit-proxy has added heartbeat management capabilities. In addition, audit-service provides domain name management capabilities.

[INLONG-10321][Audit] Audit supports the Audit Proxy service discovery and management

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/OperationTarget.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/TenantTemplateEntity.java
inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/TenantTemplateEntityMapper.java
inlong-manager/manager-dao/src/main/resources/mappers/TemplateEntityMapper.xml
inlong-manager/manager-dao/src/main/resources/mappers/TenantTemplateEntityMapper.xml
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/TemplateField.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/TenantTemplateInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/TenantTemplatePageRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/TenantTemplateRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/TemplateServiceImpl.java
inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/changes-1.13.0.sql
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/TemplateController.java

Fixes #10363 
Support template multi tenant management.
Allow configuration templates to have visibility across multiple tenants.
Support template multi tenant management.

[INLONG-10363][Manager] Support template multi tenant management

---

inlong-dashboard/src/configs/menus/conf.tsx
inlong-dashboard/src/configs/routes/conf.ts
inlong-dashboard/src/i18n.ts
inlong-dashboard/src/plugins/groups/common/GroupDataTemplateInfo.ts
inlong-dashboard/src/plugins/streams/common/StreamDefaultInfo.ts
inlong-dashboard/src/ui/locales/cn.json
inlong-dashboard/src/ui/locales/en.json
inlong-dashboard/src/ui/pages/Clusters/NodeEditModal.tsx
inlong-dashboard/src/ui/pages/GroupDataTemplate/CreateModal.tsx
inlong-dashboard/src/ui/pages/GroupDataTemplate/index.tsx
inlong-dashboard/src/ui/pages/GroupDetail/DataStream/StreamItemModal.tsx

Fixes #10377 
Add template functionality to metadata fields
A source data template page has been created, which includes the addition, modification, and query functions. On the data flow editing page, templates can be selected to fill in the source data fields

[INLONG-10377][Dashboard] Add Source Data Field Template

---

inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/AgentConfigInfo.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/AgentConfigRequest.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ClusterType.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/zk/AgentZkClusterDTO.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/zk/AgentZkClusterInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/zk/AgentZkClusterRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/AgentZkClusterOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/AgentService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/AgentController.java

Fixes #10391
Supports configuring zk clusters and issuing zk addresses to agents.
Supports configuring zk clusters and issuing zk addresses to agents.

[INLONG-10391][Manager] Supports configuring zk clusters and issuing zk addresses to agents

---

inlong-manager/manager-schedule/pom.xml
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/schedule/ScheduleEngine.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/schedule/ScheduleEngineClient.java
inlong-manager/pom.xml

Fixes #10395 
The first part of support schedule client and engine, define the interfaces for schedule client and engine
1. create a new module `manager-schedule` in manager 
2. add interfaces for scheduler client and engine

[INLONG-10395][Manager] Add interface for schedule client and engine

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/FetcherConstants.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/AgentConfigRequest.java

Fixes #10399 
Global configuration is required for agent writing zk and real-time control of sending speed
Increase the ability to periodically pull global configurations from the manager
*(example:)*
No doc needed

[INLONG-10399][Agent] Add global configurations updater

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNodeTest.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/kafka/pom.xml
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/DynamicKafkaDeserializationSchema.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicSource.java

Fixes #10381
Kafka source connector not attach input time when send audit. It will due to the report audit time not same with input time
Make DeserializationSchema report audit attach input time when deserialize.

[INLONG-10381][Sort] Kafka source connector report audit attach input time

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cmd/CommandExecutor.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cmd/CommandExecutorImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cmd/shell/ShellExecutorImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java
inlong-manager/manager-web/src/main/resources/exec_cmd.exp
inlong-manager/manager-web/src/main/resources/ssh_key_cmd.exp

Fixes #10261 
Implement SSH key-based authentication when installing the agent via SSH.
The implementation plan is as follows:
1. On the dashboard node, add an option to distinguish between username/password and SSH key authentication when selecting the SSH method. For SSH key authentication, the user also needs to input the username, port, and IP information.
2. When the user selects SSH key authentication, the dashboard actively calls the SSH key retrieval interface.
3. If the manager node does not have an SSH key pair, it calls ssh-keygen to generate one. If a key pair already exists, it is returned directly.
4.  When executing the installation command, if no user password is provided, the installation defaults to using SSH key authentication.
* Added an SSH key generation interface.
* …

[INLONG-10261][Manager] Support installing agents by SSH key-based authentication

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/ScheduleEntity.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/schedule/ScheduleInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/schedule/ScheduleInfoRequest.java
inlong-manager/manager-schedule/pom.xml
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/schedule/ScheduleType.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/schedule/ScheduleUnit.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/schedule/exception/QuartzScheduleException.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/schedule/quartz/QuartzOfflineSyncJob.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/schedule/quartz/QuartzScheduleClient.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/schedule/quartz/QuartzScheduleEngine.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/schedule/quartz/QuartzSchedulerListener.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/schedule/util/ScheduleUtils.java
inlong-manager/manager-schedule/src/test/java/org/apache/inlong/schedule/BaseScheduleTest.java
inlong-manager/manager-schedule/src/test/java/org/apache/inlong/schedule/quartz/MockJob.java
inlong-manager/manager-schedule/src/test/java/org/apache/inlong/schedule/quartz/QuartzScheduleEngineTest.java
inlong-manager/manager-schedule/src/test/java/org/apache/inlong/schedule/util/ScheduleUtilsTest.java
inlong-manager/manager-schedule/src/test/resources/log4j2.xml
inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/changes-1.13.0.sql
inlong-manager/pom.xml

Fixes #10396 
The second part of schedule capacity, adding basic schedule capability for schedule clients and engines based on quartz
1. add default implementations for the scheduling engine `QuartzScheduleEngine` and schedule client `QuartzScheduleClient` based on quartz 
2. add tests to cover these changes
3. correct the type of `crontabExpression` in `ScheduleInfo` and `ScheduleInfoRequest` from Integer to String
4. keep the `manager-docker` module as the last module
- org.apache.inlong.schedule.quartz.QuartzScheduleEngineTest
- org.apache.inlong.schedule.util.ScheduleUtilsTest

[INLONG-10396][Manager] Support build-in schedule base on quartz

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CommonConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/store/RocksDBStoreImpl.java
inlong-agent/agent-common/src/test/java/org/apache/inlong/agent/store/TestRocksDBStoreImpl.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskManager.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/instance/TestInstanceManager.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/store/TestRocksDbKey.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/store/ZKImp.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/store/ZooKeeperImpl.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/RocksDBUtils.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestLogFileSource.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/store/TestStoreKey.java

Fixes #10410 
Add ZK plugin to save offset info
1 Add ZKImp class support for read and write ZK
2 Increase index validation unit testing for RockDB and ZK plugins
*(example:)*
No doc needed

[INLONG-10410][Agent] Add ZK plugin to save offset info

---

inlong-dashboard/src/ui/components/Layout/Tenant/index.tsx
inlong-dashboard/src/ui/pages/GroupDetail/index.tsx

Fixes #10419 
Automatically switch tenants when opening a page with `groupID`.
Get the tenant and jump when entering the `groupDetail` page.

[INLONG-10419][Dashboard] Automatically switch tenants when opening a page with groupId

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/client.go
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/discoverer.go
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/options.go
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/options_basic.go

Fixes #10427
The Go SDK supports authentication for Manager access
1. Add authentication interface definition
2. Add authentication interface instance configuration
3. Add authentication processing logic
When the manager enables authentication, it can be accessed through authentication.

[INLONG-10427][SDK] The Go SDK supports authentication for Manager access

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java

Fixes #10438 
GetConfig does not throw an exception when obtaining the zk address fails.
When the getconfig interface does not obtain the zk address, the agent will use local configuration.
GetConfig does not throw an exception when obtaining the zk address fails.

[INLONG-10438][Manager] GetConfig does not throw an exception when obtaining the zk address fails

---

inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/cache/AbstractCache.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/ConfigConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/SqlConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/entities/CacheKeyEntity.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/sink/JdbcSink.java

- Fixes #10402
Audit Service supports the hourly Audit data one day ago.
Supports querying historical data that does not exist in the cache from the audit storage and automatic partition management.

[INLONG-10402][Audit] Audit Service supports the hourly Audit data one day ago

---

inlong-dataproxy/conf/common.properties
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/config/CommonConfigHolder.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/metrics/audit/AuditUtils.java
inlong-dataproxy/dataproxy-source/src/test/resources/common.properties

Fixes #10441 
1. add "audit.obtain.proxys.from.manager configure" configuration key for  obtaining Audit-Proxy through InLong Manager
2. Call different setAuditProxy methods according to the "audit.obtain.proxys.from.manager configure" configuration value

[INLONG-10441][DataProxy] Supports obtaining Audit-Proxy through InLong Manager

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java
inlong-agent/agent-installer/conf/installer.properties
inlong-agent/bin/agent-config.sh
inlong-agent/conf/agent.properties

Fixes #10446 
Adjusting audit SDK address settings
If the audit proxy address is configured, use the audit proxy address; otherwise, use the manager address
*(example:)*
No doc needed

[INLONG-10446][Agent] Adjusting audit SDK address settings

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ErrorCodeEnum.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ScheduleStatus.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/schedule/ScheduleInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/schedule/ScheduleInfoRequest.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/NoopScheduleClient.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/ScheduleClientFactory.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/ScheduleEngine.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/ScheduleEngineType.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/quartz/QuartzScheduleClient.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/quartz/QuartzScheduleEngine.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/util/ScheduleUtils.java
inlong-manager/manager-schedule/src/test/java/org/apache/inlong/manager/schedule/quartz/MockJob.java
inlong-manager/manager-schedule/src/test/java/org/apache/inlong/manager/schedule/quartz/QuartzScheduleEngineTest.java
inlong-manager/manager-schedule/src/test/java/org/apache/inlong/manager/schedule/util/ScheduleUtilsTest.java
inlong-manager/manager-service/pom.xml
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/schedule/GroupScheduleResourceListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/schedule/ScheduleOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/schedule/ScheduleOperatorImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/schedule/ScheduleServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InLongSchedulerController.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInLongGroupController.java
inlong-manager/manager-web/src/main/resources/application-dev.properties
inlong-manager/manager-web/src/main/resources/application-prod.properties
inlong-manager/manager-web/src/main/resources/application-test.properties
inlong-manager/manager-web/src/main/resources/application.properties

Fixes #10360 
Combine schedule state transition with group operations. details see description in #10360
The finite state machine for schedule :
This is the transient status of the schedule info.
With specified operations, the status will change to corresponding value.
|Status|Operation|
|---------------|-------------------------------------------|
|NEW                 | inlong group created with schedule info|
|APPROVED      |  the new inlong group approved by admin|
|REGISTERED   | schedule info registered to schedule engine|
|UPDATED         |update schedule info for a group|
|DELETED         |delete a group|
1. add schedule info in `InlongGroupRequest`
2. add configuration `inlong.schedule.engine` to indicate the schedule engine type
3. replace the implementation …

[INLONG-10360][Manager] Combine schedule state transition with group operations

---

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/MetricsCollector.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceExactlyMetric.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceMetricData.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceMetricsReporter.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/DynamicTubeMQDeserializationSchema.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/DynamicTubeMQTableDeserializationSchema.java

Fixes #10311 
Now，every connectors report audit information only support at least once. So，This pr base it to implements report audit information exactly once. The audit information will not be wrong in much exception situation.
1. Using the checkpoint principle in Flink to modify the process, the modified flow chart is shown in Figure 1 and Figure 2. In Figure 1, the callback method of notifyCompleteCheckpoint is used to upload audit information instead of scheduled upload.
Each Source/Sink will save the checkpointId of the currently ongoing checkpoint, which is nowCheckpointId in the figure. When the audit information is written to the Buffer, nowCheckpointId will be attached, indicating that the audit information
is written during this ongoing checkpoint. The audit information and …

[INLONG-10311][Sort] Implement TubeMQ Source report audit information exactly once And fix consuming TubeMQ data twice

---

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SinkExactlyMetric.java

Fixes #10450 
I plan to implement sort connectors report audit information and make no impact on other modules.So, it need to add a new version SinkMetric class
A new SinkMetric class support to report audit information and make no imapact on other modules.

[INLONG-10450][Sort] Add a new version SinkMetric class to support report audit information exactly once and make No impact on other modules

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/store/RocksDBStoreImpl.java

Fixes #10476 
The audit address should only be obtained from the manager
1. Delete the code for obtaining audit addresses from the configuration file
2. Delete audit cache related code
*(example:)*
No doc needed

[INLONG-10476][Agent] The audit address should only be obtained from the manager

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/tenant/InlongTenantServiceImpl.java

[INLONG-10474][Manager] Restrict sortTaskName and sortConsumeName the same with datanodeName when migrate Inlong Group

---

inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/StartupSortListener.java

Fixes #10487 
Fix the error of not return success ListenerResult due to config display failed.
Add return LIstenerResult.success to display right config information.

[INLONG-10487][Manager] Fix the error of not return success ListenerResult

---

inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/Mongodb2StarRocksTest.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/utils/StarRocksManager.java

Fixes #10489
Because inlong-starrocks container not build before Mongodb2StarRocks.But other test build it, so workflow will occur error sometims.
import StarRocksManager field and method to call it's static code statement to build inlong-starrocks image before Mongodb2StarRocksTest run.

[INLONG-10489][Sort] Optimize Mongodb2StarRocksTest in workflow

---

inlong-dashboard/src/ui/locales/cn.json
inlong-dashboard/src/ui/locales/en.json
inlong-dashboard/src/ui/pages/GroupDetail/Audit/config.tsx
inlong-dashboard/src/ui/pages/GroupDetail/Audit/index.tsx

Fixes #10468 
Audit data showing totals and variances.
- Calculate the difference ratio between each column and the first column.
- Calculate the sum of each column, including all pages.
- Limit the date selection range based on time units.
`MINUTE` - 1 day
`HOUR` - 3 days
`DAY` - 7 days
- Add commas to audit data for easier reading.
Before:
After:
Minute Audit
Hourly Audit
Audit by day

[INLONG-10468][Dashboard] Audit data showing totals and variances

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/PulsarProvider.java

Fixes #10495
Fix the problem of ScanStartupSubStartOffset is set to null in pulsar extranode.
Fix the problem of ScanStartupSubStartOffset is set to null in pulsar extranode.

[INLONG-10495][Manager] Fix the problem of ScanStartupSubStartOffset is set to null in pulsar extranode

---

inlong-tools/dev/inlong-dev-toolkit.sh

fixes #10064 
fix sort-connectors path with multi  sort flink version in inlong-dev-toolkit
default sort.flink.version=v1.15
set sort.flink.version=v1.13

[INLONG-10064][Feature][Tool] Support multi-version flinks in inlong-dev-toolkit

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/PulsarTableOptionUtils.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/PulsarTableOptions.java

Fixes #10508 
After update the default flink version to flink 1.15, the pulsar startup mode should support external-subscription value which is supported in flink 1.13 
add external-subscription value in scan.startup.mode

[INLONG-10508][Sort] Fix pulsar connector flink 1.15 scan start up mode parameter cannot keep consistent with flink 1.13

---

inlong-dashboard/src/plugins/streams/common/StreamDefaultInfo.ts

Fixes #10501 
Modify component type to be more intuitive
Change the separator component type from select box to radio button
Before：
After：

[INLONG-10501][Dashboard] Modify component type to be more intuitive

---

inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/StartupSortListener.java
inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/offline/FlinkOfflineJobOperator.java
inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/util/FlinkUtils.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/schedule/ScheduleInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/schedule/ScheduleInfoRequest.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/NoopScheduleClient.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/sort/SortConfigListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/schedule/OfflineJobOperatorFactory.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/schedule/ScheduleOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/schedule/ScheduleOperatorImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java
inlong-manager/manager-web/src/main/resources/application.properties
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/processor/OfflineJobOperator.java

Fixes #10459 
Support submitting Flink batch job when the scheduling instance callback.
Details see descriptions in #10459 
1. make sure `StartupSortListener` only take effect in real time sync workflow 
2. add `OfflineOperator` interface and `FlinkOfflineOperator`  to handle the submitting of flink batch job
3. add interface to `InLongGroupController` to receive the callback of schedule instance
4. improve update logic for schedule info
5. other tiny improvements in `NoopScheduleClient` and `application.properties`

[INLONG-10459][Manager] Support schedule instance callback to submit Flink batch job

---

inlong-manager/manager-docker/Dockerfile
inlong-manager/manager-docker/pom.xml

Fixes #10516 
The Jdbc module was not package in sort-flink1.15, and the Jdbc module was developed. So, The projects need to add it to pom.xml.
The dockerfile and pom.xml

[INLONG-10516][Manager] Add flink 1.15 jdbc connectors to manager image

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongGroupClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongGroupApi.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java
inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/offline/FlinkOfflineJobOperator.java
inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/util/FlinkUtils.java
inlong-manager/manager-schedule/pom.xml
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/quartz/QuartzOfflineSyncJob.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/quartz/QuartzScheduleEngine.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/quartz/QuartzSchedulerListener.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/util/ScheduleUtils.java
inlong-manager/manager-schedule/src/test/java/org/apache/inlong/manager/schedule/util/ScheduleUtilsTest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/schedule/GroupScheduleResourceListener.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/schedule/ScheduleOperatorImpl.java
inlong-manager/manager-web/src/test/resources/application.properties

Fixes #10514
Support built-in schedule engine trigger submitting of Flink batch job.
1. add the callback logic for `QuartzOfflineSyncJob`
2. add interface of `submitOfflineJob` for manager-client
3. support set Flink environment runtime-mode parameter
4.  add logs for `QuartzScheduleListener`

[INLONG-10514][Manager] Support built-in schedule engine trigger submitting of Flink batch job

---

inlong-dashboard/src/plugins/groups/common/GroupDataTemplateInfo.ts
inlong-dashboard/src/ui/locales/cn.json
inlong-dashboard/src/ui/locales/en.json
inlong-dashboard/src/ui/pages/GroupDataTemplate/CreateModal.tsx
inlong-dashboard/src/ui/pages/GroupDataTemplate/index.tsx
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/PulsarProvider.java

Fixes #10500
When editing the template, select the visual range first, the visual range should be a drop-down selection box, if the visual range is tenant level, the tenant information needs to be filled, otherwise it is hidden
if the visual range is tenant level, the tenant information needs to be filled, otherwise it is hidden, let the visual range be a drop-down selection box
before:
after:
create 
before:
if you select a tenant in the visual range drop-down selection box  show the tenant list
change the list to show
before
after

[INLONG-10500][Dashboard] Change the visible range to a drop-down box

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CycleUnitType.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/DateTransUtils.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/file/FileScanner.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/file/LogFileTask.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/file/WatchEntity.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/FilePathUtil.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/NewDateUtils.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/AgentBaseTestsHelper.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/TestLogFileTask.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/utils/TestUtils.java
inlong-agent/agent-plugins/src/test/resources/testScan/202309281030_1/test_1.txt
inlong-agent/agent-plugins/src/test/resources/testScan/2023092810_1/test_1.txt
inlong-agent/agent-plugins/src/test/resources/testScan/202309301059_1/test_1.txt
inlong-agent/agent-plugins/src/test/resources/testScan/20241030/23/59.txt

Fixes #10535 
Support minute level tasks for file collection 
1 Add m cycle types and modify the corresponding regular matching code
2 Add corresponding unit tests for file scanning
*(example:)*
No doc needed

[INLONG-10535][Agent] Support minute level tasks

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/CMakeLists.txt
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/README.md
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/build.sh
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/inlong_dataproxy.cpp

Fixes #10531 
InLong dataproxy SDK now supports Java, C++ and Go, We want to extend the language scope so that python developers can use the InLong dataproxy SDK in their projects.
1. Use pybind11 to wrap the existing C++ SDK to create a python module
2. Provide a build srcipt for developers to install this module easily.
The overview of build procedure is as follows:
*(example:)*
- If yes, how is the feature documented? docs

[INLONG-10531][SDK] Add InLong dataproxy python SDK based on C++ SDK

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/source/PulsarSource.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/source/PulsarSourceBuilder.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/source/PulsarSourceReaderFactory.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/source/reader/PulsarOrderedSourceReader.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/source/reader/PulsarSourceReaderBase.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/source/reader/PulsarUnorderedSourceReader.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableDeserializationSchema.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableSource.java
licenses/inlong-sort-connectors/LICENSE

[INLONG-10358][Sort] Make pulsar source support report audit information exactly once

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/cls/ClsSinkOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/es/ElasticsearchSinkOperator.java

Fixes #10543
The delimiter and other configurations in CLS and ES sink are obtained from the stream.
The delimiter and other configurations in CLS and ES sink are obtained from the stream.
Unified metadata configuration to prevent one configuration from appearing in multiple places.

[INLONG-10543][Manager] The delimiter and other configurations in CLS and ES sink are obtained from the stream

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/file/LogFileTask.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/file/WatchEntity.java

Fixes #10542 
Remove the deleted watch directions to prevent continuous memory growth
Only when the watch directions reaches a certain number and is checked every five minutes
*(example:)*
No doc needed

[INLONG-10542][Agent] Remove the deleted watch directions

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/fetcher/TestManager.java

Fixes #10547 
Provide a clear prompt after the mq type is incorrect
Directly prompt for mq type error
*(example:)*
No doc needed

[INLONG-10547][Agent] Provide a clear prompt after the mq type is incorrect

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/README.md
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/demo/config_example.json
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/demo/send_demo.py

Fixes #10532
Add a dataproxy python SDK sample and the corresponding usage document for users to learn how to use this SDK
1. Add a python file including the basic interface usage of dataproxy python SDK.
2. Add the interface usage instructions in README.
*(example:)*

[INLONG-10532][SDK] Add dataproxy python SDK sample and the corresponding document

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/IcebergSourceReader.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/source/reader/InlongIcebergSourceReaderMetrics.java

[INLONG-10355][Sort] Make Iceberg source support report audit information exactly once

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/table/StarRocksDynamicSinkFunctionV2.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/utils/SchemaUtils.java

[INLONG-10357][Sort] Make StarRocks sink support report audit information exactly once

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/kafka/pom.xml
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/source/KafkaSource.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/source/KafkaSourceBuilder.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/source/reader/KafkaSourceReader.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/DynamicKafkaDeserializationSchema.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicSource.java
licenses/inlong-sort-connectors/LICENSE

[INLONG-10317][Sort] Make Kafka source support report audit information exactly once

---

inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/CommonPropertiesHolder.java
inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/loader/SortConfigQueryConsumeConfig.java
inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/pojo/IdConfig.java
inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/metrics/SortConfigMetricListener.java
inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/metrics/SortConfigMetricReporter.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/SinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsIdConfig.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsSinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsIdConfig.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaFederationSinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaIdConfig.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarFederationSinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarIdConfig.java

[INLONG-10555][Sort] SortStandalone support report the difference between two configuration

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java

Fixes #10564 
When requesting configuration, use MD5 to support the manager in distinguishing whether updates are needed
Request configuration with md5 included
*(example:)*
No doc needed

[INLONG-10564][Agent] Request configuration with md5 included

---

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/ScheduleEntity.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/schedule/ScheduleInfo.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/schedule/ScheduleInfoRequest.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/ScheduleUnit.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/quartz/QuartzScheduleEngine.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/util/ScheduleUtils.java
inlong-manager/manager-schedule/src/test/java/org/apache/inlong/manager/schedule/BaseScheduleTest.java
inlong-manager/manager-schedule/src/test/java/org/apache/inlong/manager/schedule/quartz/MockQuartzJob.java
inlong-manager/manager-schedule/src/test/java/org/apache/inlong/manager/schedule/quartz/QuartzScheduleEngineTest.java
inlong-manager/manager-schedule/src/test/java/org/apache/inlong/manager/schedule/util/ScheduleUtilsTest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/schedule/GroupScheduleResourceListener.java
inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql
inlong-manager/manager-web/sql/apache_inlong_manager.sql
inlong-manager/manager-web/sql/changes-1.13.0.sql
inlong-manager/manager-web/src/test/resources/application.properties

Fixes #10566 
fix auth failed and cronexpression field type
1. fix auth error
2. fix cronexpression field type error
3. correct schedule_unit to default null, since when crontab expression is not null schedule_unit can be null

[INLONG-10566][Manager] Fix auth failed and cronexpression field type error

---

inlong-common/src/main/java/org/apache/inlong/common/bounded/Boundaries.java
inlong-common/src/main/java/org/apache/inlong/common/bounded/BoundaryType.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Constants.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/ExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/PulsarExtractNode.java
inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/Entrance.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableFactory.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableOptions.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/source/PulsarTableSource.java

Fixes #10560 
The pulsar source only supports un-bounded data sources, this pull request aims to add the support for bounded pulsar source.
1. define the boundaries for the source
2. make pulsar source support bounded data(this pull request only support time boundaries)
This is worked for offline sync jobs with Flink batch runtime mode.
Every time the Flink batch task begins, set the start and stop timestamp(the publish time of pulsar msg) of the Pulsar source. 
The time to finish the batch Flink job is determined by the stop boundary(StopCursor for the Pulsar source).
Note: since the boundaries, especially the stop boundary, are defined by the pulsar message's publish time, the batch Flink job may not be finished if no messages are published into the Pulsar topic.
*(Please pick either of …

[INLONG-10560][Sort] Support bounded pulsar source

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/table/StarRocksDynamicTableSink.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/table/StarRocksSinkOP.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/table/StarRocksTableRowTransformer.java

Fixes #10568
The starrocks connector handle UNKNOWN data type as same as json. It is unreasonable. So, it need to be modified.
- Copy the starrocks connector class code.
- Add the UNKOWN data type handle statement.

[INLONG-10568][Sort] Change the starrocks connector UNKNOWN data type handle method

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongGroupClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongGroupApi.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java
inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ErrorCodeEnum.java
inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkService.java
inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/flink/dto/FlinkInfo.java
inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/util/FlinkUtils.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/schedule/OfflineJobSubmitRequest.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/quartz/QuartzOfflineSyncJob.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/util/ScheduleUtils.java
inlong-manager/manager-schedule/src/test/java/org/apache/inlong/manager/schedule/BaseScheduleTest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/schedule/ScheduleOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/schedule/ScheduleOperatorImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/bounded/BoundedSourceType.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java
inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/processor/OfflineJobOperator.java

Fixes #10561 
We already support bounded pulsar source in #10560, this pull request provides the ability to configure the boundaries from InLong-Manager.
1. modify the manager-client and InLong manager to support set boundaries for sources
2. built-in quartz schedule engine supports set boundaries for batch Flink job
- Does this pull request introduce a new feature? (yes )

[INLONG-10561][Manager] Support configrations for bounded source

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/mysql/RowDataDebeziumDeserializeSchema.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/mysql/source/MySqlSource.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/mysql/source/reader/MySqlSourceReader.java
licenses/inlong-sort-connectors/LICENSE

[INLONG-10575][Sort] Make mysql source support report audit information exactly once

---

.asf.yaml

Fixes #10582 
Since https://github.com/apache/inlong/pull/10579 merges the dev-offline-sync branch to master and we keep the whole commit history list, so https://github.com/apache/inlong/issues/10580 enables merge and rebase-merge.
Now https://github.com/apache/inlong/pull/10579 is closed so that we can change the merge behavior back.
Disable merge and rebase merge

[INLONG-10582][ASF] Disable merge and rebase merge

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/PulsarTableFactory.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarReadableMetadata.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarRowDataConverter.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableDeserializationSchema.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableDeserializationSchemaFactory.java

Fixes #10573
Pulsar source connector not attach input time when send audit. It will due to the report audit time not same with input time
- Remove innerFormat field
- Make MetricCollector's timestamp as same as metadata timestamp

[INLONG-10573][Sort] Make pulsar source connector report audit attach input time

---

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongGroupClient.java
inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongGroupApi.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/schedule/OfflineJobRequest.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/quartz/QuartzOfflineSyncJob.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java

Fixes #10589 
Some class names are not suitable like OfflineJobSubmitRequest.
Also, according to the convention, the controller shouldn't print logs.
1. Rename OfflineJobSubmitRequest to OfflineJobRequest
2. remove log in InlongGroupController

[INLONG-10589][Manager]  Rename OfflineJobSubmitRequest and remove log in controller 

---

inlong-dashboard/src/plugins/clusters/defaults/SortKafka.ts
inlong-dashboard/src/plugins/clusters/defaults/index.ts

Fixes #10584 
New cluster type adds sortkafka types
Added sortkafka type on the new cluster page
before
after

[INLONG-10584][Dashboard]  New cluster type adds sortkafka types

---

inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/TestLogFileTask.java

Fixes #10598 
Delete excess unit tests, the unit testing content above is sufficient to cover.
Delete excess unit tests
*(example:)*
No doc needed

[INLONG-10598][Agent] Delete excess unit tests

---

inlong-dashboard/src/ui/pages/GroupDetail/Audit/config.tsx
inlong-dashboard/src/ui/pages/ModuleAudit/IdModule/config.tsx
inlong-dashboard/src/ui/pages/ModuleAudit/IpModule/config.tsx

Fixes #10591 
Audit item query ignores case,If the values ​​of the drop-down boxes have the same value, the filter search will fail,When the language is English, the option is not displayed in English
Modify the filtering method, filter and modify the value of option
before
language is English ,the option is not displayed in English
after
before
Audit item query  not ignores case 
after

[INLONG-10591][Dashboard] Audit item query ignores case

---

inlong-dashboard/src/ui/pages/ClusterTags/ClusterList.tsx

Fixes #10504 
Added details button to tag management
Added details button to tag management
before
after

[INLONG-10504][Dashboard] Added details button to tag management

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/AbsFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ExpFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/LnFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/Log10Function.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/Log2Function.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/LogFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/PowerFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/SqrtFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformArithmeticFunctionsProcessor.java

Fixes #10607 
Transform SQL support arithmetic functions(Including log10, log2, log and exp)
Add four arithmetic function classes: Log2Function, Log10Function, LogFunction, and ExpFunction. Also, add the corresponding unit test codes
*(example:)*

[INLONG-10607][SDK] Transform SQL support arithmetic functions(Including log10, log2, log and exp)

---

inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/pom.xml
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/source/PulsarReadableMetadata.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/source/PulsarRowDataConverter.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/source/PulsarTableDeserializationSchema.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/source/PulsarTableDeserializationSchemaFactory.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/source/PulsarTableSource.java
licenses/inlong-sort-connectors/LICENSE

Fixes #10623
referece #10574 
Pulsar source connector not attach input time when send audit. It will due to the report audit time not same with input time
- Copy PulsarReadableMetadata.java and PulsarRowDataConverter.java
- Add a metadata field and append it on the produced rowdata
- Make MetricCollector's timestamp as same as metadata timestamp

[INLONG-10623][Sort] Fix the Pulsar connector on flink1.18 not set audit time

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/DebeziumSourceFunction.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/MongoDBConnectorDeserializationSchema.java

[INLONG-10610][Sort] Make MongoDB source support report audit information exactly once

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/sqlserver/DebeziumSourceFunction.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/sqlserver/RowDataDebeziumDeserializeSchema.java

[INLONG-10630][Sort] Make SQL Server source support report audit information exactly once

---

inlong-dashboard/src/ui/locales/cn.json
inlong-dashboard/src/ui/locales/en.json
inlong-dashboard/src/ui/pages/ClusterTags/TagDetailModal.tsx

Fixes #10592 
When there are too many selections in the drop-down box, omit some of them
Set the drop-down box Attributes, When the drop-down box displays more than 9, the extra parts will be omitted, and the total number will be added to the remaining tenants.
before
after

[INLONG-10592][Dashboard] When there are too many selections in the drop-down box, omit some of them

---

inlong-sort/sort-end-to-end-tests/pom.xml
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.18/pom.xml
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.18/src/main/java/org/apache/inlong/sort/tests/utils/FlinkContainerTestEnv.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.18/src/main/java/org/apache/inlong/sort/tests/utils/FlinkContainerTestEnvJRE11.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.18/src/main/java/org/apache/inlong/sort/tests/utils/FlinkContainerTestEnvJRE8.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.18/src/main/java/org/apache/inlong/sort/tests/utils/PlaceholderResolver.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.18/src/main/java/org/apache/inlong/sort/tests/utils/TestUtils.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.18/src/main/resources/log4j2-test.properties

Fixes #10628 
The Inlong-sort already develop sort-connector on flink1.18, but not has env to test it.
So, this pr provide a base env to provide end to end test.
- Copy code from end2end test on flink1.15
- Add Flink1.18 jobmanager docker container 
- Add Flink1.18 taskmanager docker container 
- Add Java8 and Java11 env

[INLONG-10628][Sort] Implement the end2end test env on flink1.18

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentMain.java
inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/Main.java

Fixes #10633 
The initialization function of AuditUtils needs to pass in the configuration, because the config files of installer and agent are different.
Initialize function adds configuration input parameters
*(example:)*
No doc needed

[INLONG-10633][Agent] The initialization function of AuditUtils pass in the configuration

---

inlong-agent/agent-installer/bin/crontab.sh

Fixes #10645 
Installer needs to add process protection
Add process daemon in crontab
*(example:)*
No doc needed

[INLONG-10645][Agent] Installer adds process protection

---

inlong-dashboard/src/ui/pages/GroupDetail/Audit/config.tsx

Fixes #10461 
After modifying the theme, the corresponding text will be inverted.
Modify the logic of color judgment on the audit page
before: The theme color is black, but the data color in the table on the audit page is not white, making it unclear.
after: 
The theme color is black and the font color will become white

[INLONG-10641][Dashboard] Switching theme font color without inverse color

---

inlong-dashboard/src/plugins/sources/defaults/File.ts
inlong-dashboard/src/ui/locales/cn.json
inlong-dashboard/src/ui/locales/en.json

Fixes #10651
Let the File Type data stream support minute-level periods
Add data minute-level period type in File.ts file
before:
after:

[INLONG-10651][Dashboard] File Type data stream supports minute-level periods

---

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ManagerFetcher.java
inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java
inlong-agent/agent-installer/src/test/java/installer/TestModuleManager.java
inlong-agent/agent-installer/src/test/resources/conf/modules.json

Fixes #10650
When the installer updates the configuration, it is necessary to first determine the version
When the installer updates the configuration, it first checks the version
*(example:)*
No doc needed

[INLONG-10650][Agent] When the installer updates the configuration, it first checks the version

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/connpool/connpool.go
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/client.go
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/util/backoff.go

Add rebalance and recover support of conn pool in Golang SDK
Fixes #10668
1. Impove the conn pool
2. Rebalance the conns opened by the conn pool periodically
3. Recover the endpoints periodically if they are down
4. Refactor the conn pool without sync.Mutex
1. If an endpoint can not be connected, mark it as unavailable
2. Recover the endpoints periodically if they are unavailable
3. Rebalance the conns opened by the conn pool periodically
4. Close the conn pool when closing the SDK
*(example:)* …

[INLONG-10668][SDK] Add rebalance and recover support of conn pool in Golang SDK

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/client.go
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/worker.go

Fixes #10670
There is a potential block bug in the Golang SDK:
In the callback of conn.AsyncWrite() we may call worker.updateConn(), updateConn() may try to open new conn in some case, if so, it will call gnet.Client.Dial(), but gnet.Client.Dial() will be blocked unitl gnet event loop mark the conn is opened, but now the event loop is running in conn.AsyncWrite()'s callback:
conn.AsyncWrite()'s callback-->worker.updateConn()-->gnet.Client.Dial()-->waiting for conn.AsyncWrite()'s callback to return.
1. update conn async in the conn.AsyncWrite() callback;
2. update conn async when conn is closed.
*(example:)*
- *Extended integration test …

[INLONG-16070][SDK] Fix potential block in Golang SDK

---

inlong-dashboard/src/ui/pages/Clusters/NodeEditModal.tsx

Fixes #10681 
Eliminate the update failure caused by the moduleIdList array nesting problem that occurs when the agent node is modified.
Added assignment judgment for moduleIdList, first judge whether it is an array, if so, directly concat another value, otherwise it is first to become an array and then concat
before:
after:

[INLONG-10681][Dashboard] There is a nesting problem in moduleIdList

---

inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/source/PulsarSource.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/source/PulsarSourceBuilder.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/source/reader/PulsarSourceReader.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableFactory.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/source/PulsarTableDeserializationSchema.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/source/PulsarTableSource.java
licenses/inlong-sort-connectors/LICENSE

[INLONG-10682][Sort] Make pulsar source support to send audit information exactly once and add ExtractNode.INLONG_MSG to helper validate

---

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditReporterImpl.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/util/AuditManagerUtils.java
inlong-audit/audit-sdk/src/test/java/org/apache/inlong/audit/util/AuditManagerUtilsTest.java

- Fixes #10687
Independent the Audit items of Agent from module reconciliation to make page query auditing clearer.
Independent the Audit items of Agent from module reconciliation.

[INLONG-10687][Audit] Independent the Audit items of Agent from module reconciliation

---

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/StarRocksDynamicTableSinkFactory.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/table/StarRocksDynamicTableSink.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/table/StarRocksTableRowTransformer.java

[INLONG-10696][Sort] StarRocks sink supports ignore json parse error

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/ExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/LoadNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/Node.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/OceanBaseExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/OceanBaseLoadNode.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/OceanBaseExtractNodeTest.java
inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/load/OceanBaseLoadNodeTest.java
inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/MySqlExtractNodeToOceanBaseLoadNodeTest.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/jdbc/JdbcDialect.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/jdbc/src/main/java/org/apache/inlong/sort/jdbc/dialect/jdbc/JdbcDialectFactory.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/jdbc/src/main/resources/META-INF/services/org.apache.inlong.sort.jdbc.dialect.JdbcDialectFactory

Fixes #10704
Added support for Oceanbase data sources to adapt to the Oceanbase ecosystem. close #10704
It mainly adds oceanbase data source support and uses the oceanbase-client driver to connect.
It mainly adds oceanbase data source support and uses the oceanbase-client driver to connect. And write oceanbase's ExtractNode logic and LoadNode logic. The specific implementation logic is the same as mysql.Added support for oceanbase on the front-end page. Since the jdbc-inlong processing logic in the flink15 connection lacks the jdbc dialect, an error is reported. This is modified here.
Here's how the page test works
Please use the following test classes for testing …

[INLONG-10704][Sort] Sort Add Oceanbase Support

---

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditReporterImpl.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/entity/AuditMetric.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderManager.java

- Fixes #10728
In order to prevent the memory of the audit SDK from increasing when the Audit Proxy is unavailable, so add global memory for the Audit SDK.
Add global memory control for the Audit SDK

[INLONG-10728][Audit] Add global memory control for the Audit SDK

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/build.sh

Fixes #10736
Enable python sdk build script to automatically skip the c++ sdk build process when it has been compiled.
Modify the python sdk build script.
*(example:)*

[INLONG-10736][SDK] Python sdk build script support for skipping c++ sdk build step

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/SqlServerTask.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/SQLServerInstance.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/SQLServerSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/SQLServerTask.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/SQLServerTimeConverter.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestSQLServerSource.java

Fixes #10289 
Update the SQLServer Source for agent
Start a Debezium thread to collect change data from SQLServer and convert time fields to string. Then put sourceData into a queue. The agent will regularly read data from this queue and send it to DataProxy.

[INLONG-10289][Agent] Update the SQLServer Source

---

inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/elasticsearch7/pom.xml
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/elasticsearch7/src/main/java/org/apache/inlong/sort/elasticsearch7/Elasticsearch7ApiCallBridge.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/elasticsearch7/src/main/java/org/apache/inlong/sort/elasticsearch7/Elasticsearch7BulkProcessorIndexer.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/elasticsearch7/src/main/java/org/apache/inlong/sort/elasticsearch7/ElasticsearchSink.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/elasticsearch7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7Configuration.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/elasticsearch7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7DynamicSink.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/elasticsearch7/src/main/java/org/apache/inlong/sort/elasticsearch7/table/Elasticsearch7DynamicSinkFactory.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/elasticsearch7/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pom.xml
licenses/inlong-sort-connectors/LICENSE

Fixes #10721
There is no es connector in sort-connectors， but es is a popular distributed, RESTful search and analytics engine.
So, this pr will add the es7 connector onflink 1.18.
Reference the official connector flink-connector-elasticsearch7 and it will support send audit information later.

[INLONG-10721][Sort] Add elasticsearch7 connector on flink 1.18

---

inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/SqlConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/source/JdbcSource.java
inlong-audit/audit-service/src/test/java/org/apache/inlong/audit/source/JdbcSourceTest.java
inlong-audit/audit-service/src/test/java/org/apache/inlong/audit/utils/CacheUtilsTest.java

- Fixes #10745
Unify the range of audit aggregation intervals
When querying data based on time, use >= and < to make interval judgments instead of the between judger.

[INLONG-10745][Audit] Unify the range of audit aggregation intervals

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/OracleTask.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java
inlong-agent/agent-plugins/pom.xml
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/OracleInstance.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/OracleSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/OracleTask.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestOracleConnect.java

Fixes #10288 
Update the Oracle source for agent
1. Modify TaskProfileDto and OracleTask to accept and parse the configuration.
2. Add OracleTask, OracleInstance, and OracleSource classes
3. Resolve code redundancy in PostgreSQL Task

[INLONG-10288][Agent]  Update the Oracle Source

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/SqlServerTask.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/SQLServerSource.java

Fixes #10742
Set the formatting of Unix timestamp in Debezium JSON data for SQLServerSource to "yyyy-MM-dd HH:mm:ss" as optional
Add a "unixTimestampFormatEnable" parameter to determine whether to format the Unix timestamp

[INLONG-10742][Agent] Set the formatting of unix timestamp for SQLServerSource as optional

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/OffsetManager.java

Fixes #10749 
After the task is deleted, the instance records of the local database may be leaked
After the task is deleted, the instance local record will be cleared after timeout
*(example:)*
No doc needed

[INLONG-10749][Agent] Fix Instance store leak bug

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/PulsarSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/AbstractSource.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/service/AuditMsgConsumerServer.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/pb/network/TcpChannelGroup.java
inlong-sdk/sdk-common/src/main/java/org/apache/inlong/sdk/commons/protocol/ProxyEvent.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/kafka/KafkaSeeker.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/format/JsonDynamicSchemaFormat.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarRowDataConverter.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/source/PulsarRowDataConverter.java
inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/util/StringUtils.java

Fixes #10748
A code scan found some null pointer dereference risks in the code, which will produce `NullPointerException` in some cases.
Add some object non-null judgments or modify the code's processing logic.
*(example:)*

[INLONG-10748][Common] Fix some null pointer dereference risks in the code.

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/DateFormatFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/LocateFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/SubstringFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ToDateFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformStringFunctionsProcessor.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformTemporalFunctionsProcessor.java

Fixes #10618 
Transform SQL support four common functions(Including substring, locate, to_date and date_format)
- Add two string function classes: SubstringFunction and LocateFunction.
- Add two temporal function classes: ToDateFunction and DateFormatFunction.
- Add two transform function test classes: TestTransformStringFunctionsProcessor and TestTransformTemporalFunctionsProcessor.
*(example:)*

[INLONG-10618][SDK] Transform SQL support common functions(Including substring, locate, to_date and date_format)

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/CeilFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/FloorFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/SinFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/SinhFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformArithmeticFunctionsProcessor.java

Fixes #10613
Add four arithmetic function classes: CeilFunction, FloorFunction, SinFunction, and SinhFunction. Also, add the corresponding unit test codes
*(example:)*

[INLONG-10613][SDK] Transform SQL support arithmetic functions(Including ceil, floor, sin and sinh)

---

inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/util/StringUtils.java
inlong-sort/sort-formats/format-common/src/test/java/org/apache/inlong/sort/formats/common/StringUtilsTest.java

Fixes #10768
In the case that the input string is 
"name|age=20\\||&'\n\name|age=20\\||&'\n\n|home|\\home\\"
1. max size = 0
2. max size = 1
3. max size = 2
4. max size = 3
5. max size = 4
*(example:)*

[INLONG-10768][Sort] Csv utils support specified the max split field size

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/DateExtractFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/DateParser.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformTemporalFunctionsProcessor.java

Fixes #10764
Transform SQL support temporal functions(Including year, quarter, month, week, dayofyear and dayofmonth)
Add one temporal function class `DateExtractFunction` and one class `DateParser` that implements the class `ValueParser`. Also, add the corresponding unit test codes
*(example:)*

[INLONG-10764][SDK] Transform SQL support temporal functions(Including year, quarter, month, week, dayofyear and dayofmonth)

---

inlong-agent/agent-installer/conf/installer.properties
inlong-agent/bin/agent-config.sh
inlong-agent/conf/agent.properties

Fixes #10770 
The code related to audit proxy configuration is no longer useful
Delete audit proxy configuration related code
*(example:)*
No doc needed

[INLONG-10770][Agent] Delete audit proxy configuration related code

---

inlong-dashboard/src/plugins/streams/common/StreamDefaultInfo.ts
inlong-dashboard/src/ui/components/HighRadio/index.tsx
inlong-dashboard/src/ui/locales/cn.json
inlong-dashboard/src/ui/locales/en.json

The following *XYZ* should be replaced by the actual [GitHub Issue](https://github.com/apache/inlong/issues) number)-->
Fixes #10693 
Added custom ASCII code option for source data field separator
Create a combined radio and input combined component. When custom radio is selected, the input input box appears, and the input range is 0-127.
before:
after:

[INLONG-10691][Dashboard] Added custom ASCII code option for source data field separator

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.cc
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/buffer_manager.h
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/capi_constant.h

- Fixes #10780
Optimize memory management for DataProxy CPP SDK
Optimize memory management for DataProxy CPP SDK  to reduce repeated application and release of memory

[INLONG-10780][SDK] Optimize memory management for DataProxy CPP SDK

---

inlong-sort/sort-flink/base/pom.xml
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/sdk/InlongSdkDirtySink.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/sdk/InlongSdkDirtySinkFactory.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/sdk/InlongSdkOptions.java
inlong-sort/sort-flink/base/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory

[INLONG-10791][Sort] Support inlong dirty sink

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/DateFormatFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformTemporalFunctionsProcessor.java

Fixes #10776
In `DateFormatFunction.java`, the first parameter(timestamp) is currently parsed as a `BigDecimal` type. It's incorrect according to the Flink documentation, it should be parsed as a `java.sql.Timestamp` type.
Modify the class `DateFormatFunction` and the correspoding unit test codes
*(example:)*

[INLONG-10776][SDK] Fix incorrect parsing of parameter types in DateFormatFunction

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/FromUnixTimeFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ToTimestampFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/UnixTimestampFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformTemporalFunctionsProcessor.java

Fixes #10781
Transform SQL support temporal functions(Including form_unixtime, unix_timestamp and to_timestamp)
Add three temporal function classes: `FromUnixTimeFunction`, `ToTimestampFunction` and `UnixTimestampFunction`. Also, add the corresponding unit test codes
*(example:)*

[INLONG-10781][SDK] Transform SQL support temporal functions(Including form_unixtime, unix_timestamp and to_timestamp)

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/README.md
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/build.sh

Fixes #10806
Optimize the python dataproxy sdk build script with the following optimizations:
- Enable user to customize the dynamic repository directory in the build script process for the convenience of virtual environment users.
- The pybind11 folder is not deleted at the end of the build, the build process automatically detects if there is a compiled Pybind, and if there is, the Pybind download and build steps will be skipped.
- Do not build dataproxy-cpp-sdk in the python sdk build script, to avoid some potential problems, in the build process to automatically detect whether the c++ sdk has been compiled. If not compiled, it will provide the compilation commands to guide the user to compile the c++ sdk.
- Remove Pybind test step for faster build.
Modify the python sdk build script …

[INLONG-10806][SDK] Optimize python dataproxy sdk build script

---

inlong-dashboard/src/ui/pages/GroupDetail/ResourceInfo/index.tsx

Fixes #10844 
Resource details page sort information interface switch
Resource details page sort information interface switch,before request /group/detail/${inlongGroupId} ,after /sink/listDetail
before
after:

[INLONG-10844][Dashboard] Resource details page sort information interface switch

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ToBase64Function.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformStringFunctionsProcessor.java

Fixes #10841
Add a string function class：ToBase64Function.
Add the corresponding unit test codes
*(example:)*

[INLONG-10841][SDK] Transform SQL supports toBase64 function

---

inlong-common/src/main/java/org/apache/inlong/common/constant/SinkType.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/sink/HttpSinkConfig.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/sink/SinkConfig.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/node/HttpNodeConfig.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/node/NodeConfig.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/http/DefaultEvent2HttpRequestHandler.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/http/HttpCallback.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/http/HttpChannelWorker.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/http/HttpIdConfig.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/http/HttpOutputChannel.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/http/HttpRequest.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/http/HttpSink.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/http/HttpSinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/http/HttpSinkFactory.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/http/IEvent2HttpRequestHandler.java

Fixes #10831
Add a new sink type: `HTTP` for SortStandalone, which can report data to the specific HTTP interface. The flow diagram is shown below:
Add a new sink type package `http` in `sort-standalone-source`.
- If yes, how is the feature documented? docs

[INLONG-10831][Sort] SortStandalone support HTTP sink

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ReplaceFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformStringFunctionsProcessor.java

Fixes #10816 
Add one string function class：ReplaceFunction. 
Add the corresponding unit test codes
*(example:)*

[INLONG-10816][SDK] Transform support Replace function.

---

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/util/MySQLSensitiveUrlUtils.java

fix #9706 
Here is a vulnerability which is fixed in the master branch and the higher versions (https://github.com/apache/inlong/commit/23e3e00cae1fd120b089fca54f7440945dfe11a4) but is not fixed in the branch of release-1.11.0, maybe it should be backported?

[INLONG-9706][Manager] Supports jdbc verification under multiple hosts

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TimestampAddFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformTemporalFunctionsProcessor.java

Fixes #10879 
Add one arithmetic function classe: TimestampAddFunction. Also, add the corresponding unit test codes.
*(example:)*

[INLONG-10879][SDK] Transform support TIMESTAMPADD() function

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TranslateFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformStringFunctionsProcessor.java

issue: #10832
translate(originalString, searchString, replacementString)
translate function that replaces a sequence of characters in a string with another set of characters.
Example:
case1: translate("hello word!", "el", "EL")
case2: translate('ApaCHe Inlong', CH, ch)
*(example:)* …

[INLONG-10832][SDK] Transform SQL support Translate function

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/ThreadUtils.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/file/FileUtils.java
inlong-agent/agent-installer/bin/installer.sh
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/CommonInstance.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/AbstractSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/AbstractTask.java
inlong-agent/bin/agent-env.sh
inlong-agent/bin/oom.sh

Fixes #10889 
When the oom is detected, the process exits
Add oom handling to several main threads to catch exceptions
*(example:)*
No doc needed

[INLONG-10889][Agent] When the oom is detected, the process exits

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java

Fixes #10975
Fix the problem of when saving the group, only the existence of the groupid under the current tenant was verified.
When saving group information, check whether the group exists based on the groupid instead of the groupid and tenant.

[INLONG-10975][Manager] Fix the problem of when saving the group, only the existence of the groupid under the current tenant was verified

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/CsvSourceData.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/CsvSourceDecoder.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/SourceData.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/converter/DoubleConverter.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/converter/LongConverter.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/IfFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/DoubleParser.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformExpressionOperatorsProcessor.java

Fixes #10809 
- Modified the SourceData interface to enable it to return multiple data types; Based on this, the CsvSourceData class was modified.
- The ValueParser interface has reserved the ability to return multiple data types, so SourceData only needs to be aligned with it.
- To enable the functionality of field types, modify the FieldInfo class to have a default TypeConverter.
- If the original FieldInfo class needs to pass TypeConverter through the constructor, otherwise it will be null, causing each Field to have no type; This requires specifying the default implementation of TypeConverter.
- Based on the TypeConverter interface, two converters, DoubleConverter and LongConverter, have been implemented.
- In order to enable InLong Transform to parse floating-point data types in SQL …

[INLONG-10809][SDK] Improvements to TypeConverter field types and CompareValue in OperatorTools

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/LtrimFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RtrimFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestLtrimFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestRtrimFunction.java

Fixes #11017 
Add two function classes: LtrimFunction, RtrimFunction. Also, add the corresponding unit test classes: TestLtrimFunction, TestRtrimFunction.
*(example:)*

[INLONG-11017][SDK] Transform SQL supports RTRIM and LTRIM Functions

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/SplitIndexFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestSplitIndexFunction.java

Fixes #11053 
Add a function class SplitIndexFunction and its test case.
- SPLIT_INDEX(string1, string2, integer1)
Splits string1 by the delimiter string2, returns the integerth (zero-based) string of the split strings. Returns NULL if integer is negative. Returns NULL if any of arguments is NULL.
```java
// case 1
SELECT SPLIT_INDEX('one,two,three,four', ',', 2);
result = 'three'
// case 2
SELECT SPLIT_INDEX('one,two,three,four', ',', -1);
result = null
```
*(example:)* …

[INLONG-11053][SDK] Transform support SPLIT_INDEX function

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/BitLengthFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestBitLengthFunction.java

Fixes #11050 
Add one function classe: BitLengthFunction. Also, add the corresponding unit test classes: TestBitLengthFunction.
*(example:)*

[INLONG-11050][SDK] Transform SQL supports bit_length Function

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/JsonNode.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/JsonSourceData.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/JsonSourceDecoder.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/TestJson2CsvProcessor.java

Fixes #10962 
Extend Inlong transform SQL support selecting data from multi-dimensional array.
transformSql = "select $root.matrix(0,1) from source"
jsonString:
```
{
"matrix":[
[1,2,3],
[4,5,6],
[7,8,9]
]
}
```
result: $root.matrix(0,1)="2"
transformSql = "select $root.arr(1).id, $root.arr(2,1) from source"
jsonString:
```
{
"arr":[
"value1",
{"id":"1001"},
[12,-3,25]
]
}
```
result: $root.arr(1).id = "1001", $root.arr(2,1) = "-3"
transformSql = "select  $root.departments(0).courses(0,1).courseId, sqrt($root.departments(0).courses(0,1).courseId - 2) from source"
jsonString:
```
{
"departments": [
{
"name": "Mathematics",
"courses": [
[
{"courseId": "101","title": "Calculus I"},
{"courseId": "102","title": "Linear Algebra"}
],
[
{"courseId": "201","title": "Calculus II"},
{"courseId": …
```

[INLONG-10962][SDK] Transform JSON Source Support Multi-Dimensional Array

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/LowerFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/UpperFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestLcaseFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestUcaseFunction.java

Fixes #11012 
Modify LowerFunction and UpperFunction. Also, add the corresponding unit test codes.
*(example:)*

[INLONG-11012][SDK] Transform SQL supports LCASE and UCASE Functions

---

inlong-common/src/main/java/org/apache/inlong/common/util/StringUtil.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/FunctionTools.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/LikeParser.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/ParserTools.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestLikeParserProcessor.java

Fixes #10938 
Add one function classe: "LikeParser". Add isBlank method to "StringUtil" and NP Check to "FunctionalTools" and "ParserTools". Also, add the corresponding unit test codes.
*(example:)*

[INLONG-10938][SDK] Transform SQL supports fuzzy matching of LIKE and NOT LIKE

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RandIntegerFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestRandIntegerFunction.java

Fixes #11056 
add RantIntegerFunction class and provide unit tests
* RAND_INTEGER(INT1)--Returns a pseudorandom integer value in the range [0, INT)
* RAND_INTEGER(INT1, INT2)--Returns a pseudorandom integer value in the range [0, INT2) with an initial seed INT1.
* Two RAND_INTEGER functions will return idential sequences of numbers if they have the same initial seed and bound.
*(example:)* …

[INLONG-11056][SDK] Transform support RAND_INTEGER() function

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/IsAlphaFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/IsDecimalFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/IsDigitFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestIsAlphaFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestIsDecimalFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestIsDigitFunction.java

Fixes #11044 
Add three function classes: IsAlphaFunction, IsDecimalFunction, IsDigitFunction. Also, add the corresponding unit test classes: TestIsAlphaFunction, TestIsDecimalFunction, TestIsDigitFunction.
*(example:)*

[INLONG-11044][SDK] Transform SQL supports string judgment functions(IS_ALPHA、IS_DECIMAL、IS_DIGIT)

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FilterFunctionUtils.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/FilterFunction.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/function/BetweenFunction.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/function/MultiValueFilterFunction.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/transformation/function/SingleValueFilterFunction.java

[INLONG-11089][Manager] Optimize Sort filter function

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/CompressFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/UnCompressFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/factory/CompressionAlgorithmFactory.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/factory/UnCompressionAlgorithmFactory.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/handler/CompressHandler.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/handler/DeflaterCompress.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/handler/DeflaterUncompress.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/handler/GzipCompress.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/handler/GzipUncompress.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/handler/UncompressHandler.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/handler/ZipCompress.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/handler/ZipUncompress.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestCompressFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestUnCompressFunction.java

Fixes #11018 
Add two function classes: CompressFunction, UnCompressFunction. Also, add the corresponding unit test classes: TestCompressFunction, TestUnCompressFunction.
*(example:)*

[INLONG-11018][SDK] Transform SQL supports COMPRESS and UNCOMPRESS Functions

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/AvroNode.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/AvroSourceData.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/AvroSourceDecoder.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/SourceDecoderFactory.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/AvroSourceInfo.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/AbstractProcessorTestBase.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/TestAvro2CsvProcessor.java

Fixes #11030
Transform add avro source data. Currently, the transform supports parsing Avro data types including int, float, long double, string, boolean, bytes, fixed, enum.
Add some classes: 
- AvroSourceInfo
- AvroNode
- AvroSourceData
- AvroSourceDecoder
- TestAvro2CsvProcessor
Modified:
- SourceDecoderFactory
- AbstractProcessorTestBase
*(example:)*
- If …

[INLONG-11030][SDK] Add AVRO formatted data source for Transform

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/DataProxyController.java

Fixes #11071 
When the dataproxy module requests the `/dataproxy/getIpList/inlong_agent_system` interface, an error occurs because there is no record in the `inlong_group` table where the `inlong_group_id` is equals to `inlong_agent_system`. This results in the manager console continuously outputting exceptions
- Changed getDataProxyNodes function in the `org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java` file to throw an exception when there is no record in the `inlong_group` table where the `inlong_group_id` is equals to `inlong_agent_system`
- Changed getIpList function in the `org/apache/inlong/manager/web/controller/openapi/DataProxyController.java` file to return fail response when an exception occurs in the `getDataProxyNodes` function. 
Previous error …

[INLONG-11071][Manager] Fix: failed to handle request on inlong_agent_system by admin

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/HttpClientExample.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/TcpClientExample.java

Fixes #11110 
Change the isLocalVisit parameter name to requestByHttp to avoid using https to process requests by default. 
- Changed the isLocalVisit parameter 
- Removed the incorrect description about isLocalVisit
- Added messageSender close operation 
*(example:)*
- If a feature is not documented yet in this PR, please create a follow-up issue for adding …

[INLONG-11110][SDK] Fix incorrect usage of isLocalVisit variable in client example of dataproxy-sdk module

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/UnHexFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestUnHexFunction.java

Fixes #11122 
Add one function class: UnHexFunction. Also, add the corresponding unit test classe: TestUnHexFunction.
*(example:)*

[INLONG-11122][SDK] Transform SQL supports UNHEX function

---

inlong-sdk/transform-sdk/pom.xml
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/BsonSourceData.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/BsonSourceDecoder.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/SourceDecoderFactory.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/BsonSourceInfo.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/TestBson2CsvProcessor.java
pom.xml

Fixes #11020 
Added the parsing capability of Bson data source for Transform.
The following classes have been added: BsonSourceData, BsonSourceDecoder, BsonSourceInfo. 
And added a testing class: TestBson2CsvProcessor.
*(example:)*

[INLONG-11020][SDK] Add BSON formatted data source for Transform

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/BetweenAndOperator.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestBetweenAndOperator.java

Fixes #11139
- expr NOT BETWEEN min AND max
This is the same as NOT (expr BETWEEN min AND max).
*(example:)*

[INLONG-11139][SDK] Transform support Not Between And operator

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/AbstractConfiguration.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/FileTask.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/AbstractSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/extend/DefaultExtendedHandler.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/extend/ExtendedHandler.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/AgentBaseTestsHelper.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/instance/TestInstanceManager.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/KafkaSinkTest.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/PulsarSinkTest.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/filecollect/TestSenderManager.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestLogFileSource.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestSQLServerSource.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/TestLogFileTask.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/TestTaskManager.java
inlong-agent/agent-plugins/src/test/resources/test/mix_20230928_1.txt

Fixes #11135 
Support filtering capability when supplementing data
Add stream filtering configuration item
*(example:)*
No doc needed

[INLONG-11135][Agent] Support filtering capability when supplementing data

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/AbstractTask.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/file/LogFileTask.java

Fixes #11145 
The logic for supplementing data needs to be optimized to prevent data loss
1. If the action queue is full, the action cannot be directly discarded
2. Determination of completion of supplementary data task: The number of scanned files is equal to the number of collected files
*(example:)*
No doc needed

[INLONG-11145][Agent] Optimize the logic of supplementing data

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/converter/BooleanConverter.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/IsBooleanOperator.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/IsNullOperator.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/AbstractFunctionArithmeticTestBase.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/operator/TestIsBooleanOperator.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/operator/TestIsNullOperator.java

Fixes #11109 
Add two Operator classes: IsBooleanOperator, IsNullOperator, and one TypeConverter class: BooleanConverter. Also, add the corresponding unit test classe: TestIsBooleanOperator, TestIsNullOperator.
*(example:)*

[INLONG-11109][SDK] Transform SQL supports parsing of IS

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/AdditionParser.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/IntervalParser.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/SubtractionParser.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/utils/DateUtil.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/parser/AbstractParserTestBase.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/parser/TestAdditionParser.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/parser/TestSubtractionParser.java

Fixes #11081 
Based on [Mysql](https://dev.mysql.com/doc/refman/8.4/en/expressions.html#temporal-intervals):
1. Added IntervalParser class
```
IntervalParser  <-> INTERVAL expr unit ->  Pair(factor,Map(ChronoField,Count)):
`factor`:
1) `expr` can accept strings starting with '-', representing the meaning of subtraction.
So the positive or negative sign of `factor` indicates whether `expr` starts with a '-' or not.
2) For units like WEEK and QUARTER, it is not easy to parse,
so WEEK -> ( unit=DAY, adb(factor)=7 ); QUARTER -> ( unit=MONTH, adb(factor)=3 ).
`Map(ChronoField,Count)`:
IntervalParser will automatically match the corresponding DateTimeFormatter based on the input `expr`,
Based on DateTimeFormatter, IntervalParser will parse the incoming units and store them in a Map.
In …
```

[INLONG-11081][SDK] Transform SQL supports INTERVAL parse

---

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/manager/InlongMultiTopicManager.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/manager/InlongSingleTopicManager.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/manager/InlongTopicManager.java

[INLONG-11156][SDK] SortSDK support that the token configuration of pulsar cluster is null

---

inlong-sdk/transform-sdk/pom.xml
pom.xml

Fixes [#11166 [Bug][Sort] Mongodb2StarRocksTest Failure Due to Potential Dependency Conflicts](https://github.com/apache/inlong/issues/11166)
When running the `Mongodb2StarRocksTest` in the `sort-end-to-end-test-v1.15` module, the test failed due to a `NoClassDefFoundError` exception caused by a missing `org.mongodb.bson` module. 
This issue arose because Pull Request #11136  added the `org.mongodb.bson` dependency in the `pom.xml` file of the project root directory, leading to a conflict with the existing `org.mongodb.bson` dependency in `inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc`. 
Therefore, the problematic POM must be revised to limit the impact of the newly introduced BSON dependency.
- Removed the `org.mongodb.bson` dependency from the `pom.xml` in the root …

[INLONG-11166][SDK] Fixes Mongodb2StarRocksTest failure due to potential dependency conflicts

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/DateAddFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/temporal/TestDateAddFunction.java

Fixes #11079 
Add one function class: DateAddFunction. Also, add the corresponding unit test classe: TestDateAddFunction. 
*(example:)*

[INLONG-11079][SDK] Transform SQL supports DATE_ADD function

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RegexpMatchesFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestRegexpMatchesFunction.java

Fixes #11172 
* add flags in RegexpMatchesFunction to handle more action
* improve handle logic
* fix 'g' flag invalid bug
*(example:)*

[INLONG-11172][SDK] Fix bug in Transform REGEXP_MATCHES() function flags

---

inlong-sort/sort-flink/base/pom.xml
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/util/OpenTelemetryLogger.java
pom.xml

In order to more conveniently view the log output, using OpenTelemetry to achieve centralized log reporting
- Fixes #11065 
In order to more conveniently view the sort task log, we need to achieve a centralized log reporting method.
- Added some Maven dependencies related to openTelemetry at `inlong-sort/sort-flink/base/pom.xml` and `pom.xml`
- Designed and implemented an `OpenTelemetryLogger` class to add log reporting functionality for sort-connectors
*(example:)*
The way to integrate OpenTelemetryAppender for connectors that comply with the …

[INLONG-11065][Sort] Provides a method to add openTelemetryAppender for the sort connector

---

inlong-sdk/transform-sdk/pom.xml
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/ParquetInputByteArray.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/ParquetSourceData.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/ParquetSourceDecoder.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/SourceDecoderFactory.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/ParquetSourceInfo.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/AbstractProcessorTestBase.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/TestParquetCsvProcessor.java

Fixes #11134 
Add Parquet formatted data source for Transform.
Add some classes: ParquetSourceData, ParquetSourceDecoder, ParquetSourceInfo, ParquetInputByteArray. Two classes have been modified: SourceDecoderFactory, AbstractProcessorTestBase. Also, add the corresponding unit test class: TestParquetCsvProcessor.
> ParquetInputByteArray: Parsing Parquet data in the form of files involves disk reading, which is inefficient. This class mainly handles the input of byte stream arrays.
*(example:)*

[INLONG-11134][SDK] Add Parquet formatted data source for Transform

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/MqttSource.java

Fixes #11175 
Due to the timeout mechanism of blocking queue offers（`mqttMessagesQueue.offer(new DefaultMessage(recordValue, headerMap), 1, TimeUnit.SECONDS);`）, messages may be lost when the queue is full
Removed the timeout setting for offer operation in the `MqttSource` file， When the queue is full, the offer operation will be blocked until there is free space in the queue, thus avoiding the problem of messages being discarded.
*(example:)* …

[INLONG-11175][Agent] Fix the problem of mqttsource message loss

---

inlong-dashboard/src/ui/pages/ModuleAudit/AuditModule/config.tsx
inlong-dashboard/src/ui/pages/ModuleAudit/AuditModule/index.tsx
inlong-dashboard/src/ui/pages/ModuleAudit/IdModule/config.tsx
inlong-dashboard/src/ui/pages/ModuleAudit/IdModule/index.tsx
inlong-dashboard/src/ui/pages/ModuleAudit/IpModule/config.tsx
inlong-dashboard/src/ui/pages/ModuleAudit/IpModule/index.tsx
inlong-dashboard/src/ui/pages/ModuleAudit/index.tsx

Fixes #11183 
Module audit page indicator items are merged with other items
Separate request logic to reduce the number of requests, merge indicator items and other categories of items
before:
id,ip
metric:
after:
id,ip
metric:

[INLONG-11183][Dashboard] Module audit page indicator items are merged with other items

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/DateSubFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/temporal/TestDateSubFunction.java

Fixes #11080 
Add one function class: DateSubFunction. Also, add the corresponding unit test classe: TestDateSubFunction.
*(example:)*

[INLONG-11080][SDK] Transform SQL supports DATE_SUB function

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/SimilarToParser.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/parser/TestSimilarToParser.java

Fixes #11132 
add SimilarToParser.class to provide `SIMILAR TO` parsing capability, provide unit tests
*(example:)*

[INLONG-11132][SDK] Transform SQL support parsing SIMILAR TO

---

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/Constants.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceExactlyMetric.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/postgre/DebeziumSourceFunction.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/postgre/PostgreSQLSource.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/postgre/PostgreSQLTableSource.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/postgre/RowDataDebeziumDeserializeSchema.java

Fixes #11129
The primary goal of this PR is to enhance metric instrumentation for the InLong Sort Flink Connector, specifically for the Postgres-CDC connector. This change is aimed at improving observability by introducing additional metrics that track serialization/deserialization, snapshot states, and checkpoint completion.
**This feature focuses on SourceMetric only**
**Deserialization Metrics:**
Added counters to track successful and failed deserialization attempts (`numDeserializeSuccess`, `numDeserializeError`).
Added latency gauge to measure time taken for deserialization (`deserializeTimeLag`).
**SnapshotState Metrics:**
Added counters for the number of snapshots created (`numSnapshotCreate`) and errors encountered during snapshot operations (`numSnapshotError`).
**NotifyComplete …

[INLONG-11129][Sort] Enhanced source metric instrumentation for InLong Sort Flink Connector

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserService.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/user/UserServiceImpl.java

Fixes #11195
It is not allowed to modify group information when ordinary users are not responsible.
Add verification of operator permissions when modifying group information.
*(example:)*

[INLONG-11195][Manager] It is not allowed to modify group information when ordinary users are not responsible

---

inlong-dashboard/src/ui/pages/GroupDataTemplate/index.tsx
inlong-dashboard/src/ui/pages/TenantManagement/config.tsx
inlong-dashboard/src/ui/pages/TenantManagement/index.tsx

Fixes #11197 
Add delete button to cluster management and template management
Add delete button to cluster management and template management
1. template:
before:
after:
2. tenant:
before:
after:

[INLONG-11197][Dashboard] Add delete button to cluster management and template management

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ErfFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ErfcFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestErfFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestErfcFunction.java

Fixes #11262 
Add two function class: ErfFunction, ErfcFunction. Also, add the corresponding unit test classe: TestErfFunction, TestErfcFunction.
*(example:)*

[INLONG-11262][SDK] Transform SQL supports "erf" and "erfc" function

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/NumNonNullsFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/NumNullsFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestNumNonNullsFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestNumNullsFunction.java

Fixes #11260 
Add two function class: NumNonNullsFunction, NumNullsFunction. Also, add the corresponding unit test classe: TestNumNonNullsFunction, TestNumNullsFunction.
*(example:)*

[INLONG-11260][SDK] Transform SQL supports "num_nonnulls" and "num_nulls" function

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/FindInSetFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/TestFindInSetFunction.java

Fixes #11236 
Add one function class: FindInSetFunction. Also, add the corresponding unit test classe: TestFindInSetFunction.
*(example:)*

[INLONG-11236][SDK] Transform SQL supports FIND_IN_SET function

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/JsonExistsFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestJsonExistsFunction.java

Fixes #11221
add JsonExistsFunction.java , provide unit tests
*(example:)*

[INLONG-11221][SDK] Transform support JSON_EXISTS() function

---

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java

Fixes #11307
Fix the problem of unable to obtain extparams from multiple data sources.
Fix the problem of unable to obtain extparams from multiple data sources.

[INLONG-11307][Manager] Fix the problem of unable to obtain extparams from multiple data sources

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/ParquetByteArrayWriter.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/ParquetOutputByteArray.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/ParquetSinkEncoder.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/ParquetValueWriter.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/ParquetWriteRunner.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/ParquetSinkInfo.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/SinkInfo.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/AbstractProcessorTestBase.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/TestJson2ParquetProcessor.java

Fixes #11227 
In order to write Parquet data outside the Hadoop environment, ParquetByteArrayWriter, ParquetOutputByteArray, ParquetValueWriter, and ParquetWriteRunner have been added. On this basis, Parquet Sink was implemented and test cases were added.
*(example:)*

[INLONG-11227][SDK] Add Parquet formatted data sink for Transform

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/SubstringIndexFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestSubstringIndexFunction.java

Fixes #11235 
Add one function class: SubstringIndexFunction. Also, add the corresponding unit test classe: TestSubstringIndexFunction.
*(example:)*

[INLONG-11235][SDK] Transform SQL supports SUBSTRING_INDEX function

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/MinScaleFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ScaleFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TrimScaleFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestMinScaleFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestScaleFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestTrimScaleFunction.java

Fixes #11264 
Add one function class: MinScaleFunction, ScaleFunction, TrimScaleFunction. Also, add the corresponding unit test classe: TestMinScaleFunction, TestScaleFunction, TestTrimScaleFunction.
*(example:)*

[INLONG-11264][SDK] Transform SQL supports functions related to scale

---

inlong-dashboard/src/ui/pages/AgentModule/CreateModal.tsx

Fixes #11210 
Version management removes related interface calls and adds default values
Version management removes related interface calls and adds default values
before :
When entering the version management page, the get/1 interface will be called
after:
remove the interface and set default values for new Module

[INLONG-11210][Dashboard] Version management removes related interface calls and adds default values

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/RedisTask.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/RedisSource.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestRedisSource.java

Fixes #11306 
Some variables are named improperly
Modify the naming of variables in the redis source
*(example:)*
No doc needed

[INLONG-11306][Agent] Modify the naming of variables in the redis source

---

inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/pom.xml
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/Pulsar2StarRocksTest.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/resources/flinkSql/pulsar_test.sql
pom.xml

Fixes [[Improve][Sort] Add end-to-end test case for sort-connector-pulsar-v1.15](https://github.com/apache/inlong/issues/11266)
The `sort-connector-pulsar-v1.15` requires an end-to-end (E2E) test to ensure robustness and facilitate the resolution of future issues related to metric monitoring and reporting. Additionally, this will help streamline the testing process for future bug fixes or feature implementations.
- Added an end-to-end test case for the `sort-connector-pulsar-v1.15`.
- Introduced pulsar test container in root pom.
After adding a while loop to stop the container from being torn down after testing, we can inspect the `StarRocks` table to verify this change:
- Does this pull request introduce a new …

[INLONG-11266][Sort] Add end-to-end test case for sort-connector-pulsar-v1.15

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CommonConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/file/ProxyMessageCache.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/PulsarSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/AbstractSource.java

Fixes #11298 
Fix bug for pulsar source
1 Do not obtain offset when no data is read
2 When reading data at a specified time, the subscription site defaults to Lastest.
*(example:)*
No doc needed

[INLONG-11298][Agent] Fix bug for pulsar source with empty data process and specified time consumption

---

inlong-audit/audit-common/pom.xml

- Fixes #11315
Resolve the conflict between the Audit SDK and other components' Protobuf versions
By shading the Protobuf that the audit SDK depends on, the conflict between the audit SDK and other component Protobuf versions is resolved.

[INLONG-11315][Audit] Resolve the conflict between the Audit SDK and other components' Protobuf versions

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/SubstringFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestSubstringFunction.java

Fixes #11233 
Add a mid function name to the SubstringFunction class. And add test case code.
*(example:)*

[INLONG-11233][SDK] Transform SQL supports mid function

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/PbSinkEncoder.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/SinkEncoderFactory.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/PbSinkInfo.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/SinkInfo.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/TestAny2PbProcessor.java

Fixes #11252 
add PbSinkEncoder to sink data to pb formatted byte[] , add PbSinkInfo to generate Info , provide unit tests from different data formatted Decoder
*(example:)*

[INLONG-11252][SDK] Transform support PB sink data

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/JsonArrayInsertFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestJsonArrayInsertFunction.java

Fixes #11301 
Add the JsonArrayInsertFunction class and enhance the corresponding test class: TestJsonArrayInsertFunction.
*(example:)*

[INLONG-11301][SDK] Transform SQL supports "JSON_ARRAY_INSERT" function

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/EndsWithFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/StartsWithFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestEndsWithFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestStartsWithFunction.java

Fixes #11029
Add two function classes: StartsWith & EndsWith functions and their unit tests.
- STARTSWITH(expr, startExpr):
Returns whether expr starts with startExpr. If startExpr is empty, the result is true.
- ENDSWITH(expr, endExpr):
Returns whether expr ends with endExpr. If endExpr is empty, the result is true.
*(example:)* …

[INLONG-11029][SDK]  Transform SQL support StartsWith & EndsWith functions

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/DatabaseSqlSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/KafkaSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/MongoDBSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/MqttSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/OracleSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/PostgreSQLSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/PulsarSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/RedisSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/SQLServerSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/AbstractSource.java

Fixes #11327 
For the convenience of distinguishing extended classes between open source and internal versions
No longer retrieve extend class from task configuration
*(example:)*
No doc needed

[INLONG-11327][Agent] No longer retrieve extend class from task configuration

---

.github/workflows/ci_docker.yml

Fixes #11321
Fix the docker ci workflow failure when removing unnecessary packages
In #11322 we fix the workflow failure partially which left the docker ci workflow not fixed, this pr fix the  docker ci workflow 

[INLONG-11321][CI] Fix the docker ci workflow failure when removing unnecessary packages

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java
inlong-agent/agent-common/src/test/java/org/apache/inlong/agent/AgentBaseTestsHelper.java
inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/AgentBaseTestsHelper.java
inlong-agent/agent-installer/src/test/java/installer/BaseTestsHelper.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/AgentBaseTestsHelper.java

Fixes #11333 
There are multiple IP addresses for public network machines, and a specific IP address needs to be specified for audit data
Retrieve IP from configuration file during audit reporting
*(example:)*
No doc needed

[INLONG-11333][Agent] Retrieve IP from configuration file during audit reporting

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/InitCapFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestInitCapFunction.java

Fixes #10883 
Add a function class: InitCapFunction and its unit test.
- initcap(string)
Returns a new form of STRING with the first character of each word converted to uppercase and the rest characters to lowercase. Here a word means a sequences of alphanumeric characters.
*(example:)* …

[INLONG-10883][SDK] Transform SQL support InitCap function

---

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceExactlyMetric.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/source/reader/PulsarOrderedSourceReader.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/source/reader/PulsarUnorderedSourceReader.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableDeserializationSchema.java

Fixes [[Feature][Sort] Added new source metrics for sort-connector-pulsar-v1.15 #11340](https://github.com/apache/inlong/issues/11340)
The purpose of this PR is to enhance observability for the sort-connector-pulsar-v1.15 by introducing new source metrics. These metrics will provide detailed insights into the deserialization process and checkpoint management, facilitating better monitoring, troubleshooting, and optimization for users.
Basically the same way of modifying as that of #11130 
**Deserialization Metrics:**
Added counters to track successful and failed deserialization attempts (`numDeserializeSuccess`, `numDeserializeError`).
Added latency gauge to measure time taken for deserialization (`deserializeTimeLag`).
**SnapshotState Metrics:**
Added counters for the number of snapshots …

[INLONG-11340][Sort] Add new source metrics for sort-connector-pulsar-v1.15

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/json/JsonSetFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/json/TestJsonSetFunction.java

Fixes #11305
Add JsonSetFunction.java and its test class testJsonSetFunction.java.
*(example:)*

[INLONG-11305][SDK] Transform SQL supports "JSON_SET" function

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/json/JsonArrayAppendFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/json/JsonArrayInsertFunction.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/json/JsonRemoveFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/json/TestJsonArrayAppendFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/json/TestJsonArrayInsertFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/json/TestJsonRemoveFunction.java

Fixes #11303 
Add JsonRemoveFunction.java and its test class TestJsonRemoveFunction.java. And Fix some code logic.
*(example:)*

[INLONG-11303][SDK] Transform SQL supports "JSON_REMOVE" function

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/sqlserver/DebeziumSourceFunction.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/sqlserver/RowDataDebeziumDeserializeSchema.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/sqlserver/SqlServerSource.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/sqlserver-cdc/src/main/java/org/apache/inlong/sort/sqlserver/SqlServerTableSource.java

Fixes [[Feature][Sort] Add new source metrics for sort-connector-sqlserver-cdc-v1.15 #11357](https://github.com/apache/inlong/issues/11357)
The purpose of this PR is to enhance observability for the `sort-connector-sqlserver-cdc-v1.15` by introducing new source metrics. These metrics will provide detailed insights into the deserialization process and checkpoint management, facilitating better monitoring, troubleshooting, and optimization for users.
Basically the same way of modifying as that of #11130 
**Deserialization Metrics:**
Added counters to track successful and failed deserialization attempts (`numDeserializeSuccess`, `numDeserializeError`).
Added latency gauge to measure time taken for deserialization (`deserializeTimeLag`).
**SnapshotState Metrics:**
Added counters for the …

[INLONG-11357][Sort] Add new source metrics for sort-connector-sqlserver-cdc-v1.15

---

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/DebeziumSourceFunction.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/MongoDBConnectorDeserializationSchema.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/MongoDBSource.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/MongoDBTableSource.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/source/MongoDBSourceBuilder.java

Fixes [[Feature][Sort] Add new source metrics for sort-connector-mongodb-cdc-v1.15 #11355](https://github.com/apache/inlong/issues/11355)
**Coauthored with [yangyang-12-wq](https://github.com/yangyang-12-wq)**
The purpose of this PR is to enhance observability for the `sort-connector-mongodb-cdc-v1.15` by introducing new source metrics. These metrics will provide detailed insights into the deserialization process and checkpoint management, facilitating better monitoring, troubleshooting, and optimization for users.
Basically the same way of modifying as that of #11130 
**Deserialization Metrics:**
Added counters to track successful and failed deserialization attempts (`numDeserializeSuccess`, `numDeserializeError`).
Added latency gauge to measure time taken for deserialization …

[INLONG-11355][Sort] Add new source metrics for sort-connector-mongodb-cdc-v1.15

---

inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/metric/AbstractMetric.java
inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/metric/MetricsManager.java
inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/metric/prometheus/ProxyPrometheusMetric.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/Application.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/config/ConfigConstants.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/config/JdbcConfig.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/config/MessageQueueConfig.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/config/StoreConfig.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/entities/JdbcDataPo.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/metric/MetricDimension.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/metric/MetricItem.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/metric/MetricsManager.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/metric/prometheus/StorePrometheusMetric.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/service/AuditMsgConsumerServer.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/service/InsertData.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/service/JdbcService.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/service/consume/BaseConsume.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/service/consume/KafkaConsume.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/service/consume/PulsarConsume.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/service/consume/TubeConsume.java
inlong-audit/audit-store/src/test/java/org/apache/inlong/audit/store/service/consume/KafkaConsumeTest.java
inlong-audit/audit-store/src/test/java/org/apache/inlong/audit/store/service/consume/PulsarConsumeTest.java
inlong-audit/audit-store/src/test/java/org/apache/inlong/audit/store/service/consume/TubeConsumeTest.java
inlong-audit/conf/application.properties

- Fixes #11360
Add a metric monitoring system for the Audit Store itself
Add a metric monitoring system for the Audit Store itself by configuring Prometheus monitoring via plugins

[INLONG-11360][Audit]  Add a metric monitoring system for the Audit Store itself

---

inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/util/StringUtils.java
inlong-sort/sort-formats/format-common/src/test/java/org/apache/inlong/sort/formats/common/StringUtilsTest.java
inlong-sort/sort-formats/format-row/format-kv/src/test/java/org/apache/inlong/sort/formats/kv/KvUtilsTest.java

[INLONG-11369][Sort] KV split has error when there is a escape char without before & and = in text

---

inlong-common/src/main/java/org/apache/inlong/common/enums/DataProxyErrCode.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/StatConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/v0msg/CodecTextMsg.java

Fixes #11384 
Optimize the field checking logic for MsgType=5 message body

[INLONG-11384][DataProxy] Adjust the message body check logic for MsgType=5

---

inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/sink/pulsar/PulsarClientService.java

- Fixes #11396
Add monitoring of pulsar producer creation failure for Audit Proxy
Add monitoring of pulsar producer creation failure for Audit Proxy when a single pulsar configuration is incorrect

[INLONG-11396][Audit] Add monitoring of pulsar producer creation failure for Audit Proxy

---

inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/consts/StatConstants.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/ServerMessageHandler.java
inlong-dataproxy/dataproxy-source/src/main/java/org/apache/inlong/dataproxy/source/v0msg/CodecTextMsg.java

Fixes #11410
Fill in the length of the corresponding package attribute according to the actual setting value

[INLONG-11410][DataProxy] Fixed the bug of excessive packet length when Go SDK receives DataProxy response

---

inlong-dashboard/src/plugins/sync/common/SyncDefaultInfo.ts
inlong-dashboard/src/ui/pages/SynchronizeDetail/Info/index.tsx

Fixes #11416 
Data synchronization corrects the display problem of uncommitted data
When real-time synchronization is started but has not been submitted for modification, set initial values ​​related to offline synchronization to prevent errors during changes.
before
after:

[INLONG-11416][Dashboard] Data synchronization corrects the display problem of uncommitted data

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentStatusManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/FileStaticManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java

Fixes #11412
Prevent printing too many error logs
Do not report Agent status and file metrics
*(example:)*
No doc needed

[INLONG-11412][Agent] Do not report Agent status and file metrics

---

inlong-distribution/pom.xml
inlong-distribution/script/backup_module_dependencies.sh

Fixes #11444 
Fix the merging modules jars failure, the reason is that the actions of `backup_module_dependencies` should be executed after the `apache-inlong-xxx-SNAPSHOT-bin.tar.gz` is created.
1.  move `backup_module_dependencies` to the place after assemble
2. improve the logic to find inlong version in backup_module_dependencies`

[INLONG-11444][Distribution] Fix the merging modules jars failure

---

inlong-dashboard/src/plugins/sources/common/SourceDefaultInfo.ts
inlong-dashboard/src/ui/pages/ConsumeDashboard/index.tsx
inlong-dashboard/src/ui/pages/GroupDashboard/index.tsx
inlong-dashboard/src/ui/pages/GroupDetail/DataStream/config.tsx
inlong-dashboard/src/ui/pages/SynchronizeDashboard/index.tsx

Fixes #11449 
Add clear and search functions to some drop-down boxes
Add clear and search functions to some drop-down boxes
before:
after:

[INLONG-11449][Dashboard] Add clear and search functions to some drop-down boxes

---

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java
inlong-agent/agent-installer/src/test/java/installer/TestModuleManager.java

Fixes #11451 
The current Installer detection interval is too short, which can easily lead to misjudgment
When the Installer detects that the process does not exist, it increases the wait for retry to prevent misjudgment
*(example:)*
No doc needed

[INLONG-11451][Agent] Prevent Installer from detecting process misjudgment

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/SequentialID.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/pb/network/TcpChannel.java

Fixes #11457
1. Remove the synchronized modifier from the SeqId method
2. Save the id field as AtomicInteger to avoid out-of-bounds judgment every call;
3. Initialize the id value to a random value to avoid duplicate IDs generated on the virtual machine

[INLONG-11457][SDK] Optimize SequentialID class implementation

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java

Fixes #11461 
To prevent interference from error logs
HeartbeatManager does not create a DefaultMessageSender
*(example:)*
No doc needed

[INLONG-11461][Agent] HeartbeatManager does not create a DefaultMessageSender

---

inlong-dashboard/src/ui/pages/GroupDetail/Audit/config.tsx
inlong-dashboard/src/ui/pages/GroupDetail/Audit/index.tsx

Fixes #11465 
The sink drop-down box supports search
The sink drop-down box supports search
before：
after：

[INLONG-11465][Dashboard] The sink drop-down box supports search

---

inlong-common/src/main/java/org/apache/inlong/common/msg/AttributeConstants.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/LoadBalance.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/MessageSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/codec/EncodeObject.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/codec/ProtocolDecoder.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/codec/ProtocolEncoder.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/EncryptConfigEntry.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/UdpClientExample.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/pb/PbProtocolMessageSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/threads/MetricWorkerThread.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/LogCounter.java

Fixes #11469
1. Replace the bodyBytes field in the EncodeObject class with the bodylist field, and adjust the related process logics
2. Remove deprecated functions

[INLONG-11469][SDK] Optimize the single message processing logic in the EncodeObject class

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentStatusManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/FileStaticManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ConfigConstants.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/MessageSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/SendMsgThread.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/TcpClientExample.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/NettyClient.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/Sender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/pb/PbProtocolMessageSender.java

Fixes #11475
Replace the timeout parameter in the MessageSender class functions with the request timeout setting in the ProxyClientConfig class

[INLONG-11475][SDK] Remove the timeout parameter in the MessageSender class functions

---

inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/utils/HttpUtils.java

- Fixes #11489
Use Throwable instead of Exception to capture Java package conflicts.
Use Throwable instead of Exception to capture Java package conflict issues and facilitate troubleshooting.

[INLONG-11489][Audit] Use Throwable instead of Exception to capture Java package conflicts

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/threads/MetricWorkerThread.java

[INLONG-11491][SDK] Fix the judgment error of onMessageAck function in MetricSendCallBack class

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/DataAddTaskRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileDataAddTaskRequest.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSource.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceDTO.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceRequest.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/AgentClusterNodeInstallOperator.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cmd/CommandExecutorImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/file/FileSourceOperator.java

Fixes #11487
1.Support adding data add tasks based on the source ID.
2.Modify the cp command.
1.Support adding data add tasks based on the source ID.
2.Check if the file exists first when using cp command.
3.Modify the parameter name of the data add task.

[INLONG-11487][Manager] Support adding data add tasks based on the source ID

---

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/util/OpenTelemetryLogger.java

Fixes #11455 
Only one OpenTelemetryAppender should be registered
Added duplicate registration judgment to the install and uninstall functions, and use synchronized locks to ensure concurrency safety.
Furthermore, since users may set different logging levels, force log messages to be appended on successful installs and uninstalls to ensure successful reporting at any logging level. This also makes it easier to write unit tests to check that the logging reports are working.
```java
before:
LOG.info("OpenTelemetryLogger installed");
now:
otelAppender.append(
new Log4jLogEvent.Builder()
.setLevel(Level.INFO)
.setMessage(new SimpleMessage("OpenTelemetryLogger installed"))
.build());
```
*(example:)*
- *Added integration …

[INLONG-11455][Sort] Only one OpenTelemetryAppender should be registered

---

inlong-sdk/dirty-data-sdk/src/main/java/org/apache/inlong/sdk/dirtydata/DirtyMessageWrapper.java
inlong-sdk/dirty-data-sdk/src/main/java/org/apache/inlong/sdk/dirtydata/InlongSdkDirtySender.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/dirty/DirtyData.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/DirtyServerType.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/sdk/InlongSdkDirtyOptions.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/sdk/InlongSdkDirtySink.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/sdk/InlongSdkDirtySinkFactory.java
inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/DynamicTubeMQTableDeserializationSchema.java

Fixes #11493 
Add the ability to retry  and limit the amount of dirty SDK in flight
Add two options to configure max retry time and the max callback size
*(example:)*

[INLONG-11493][SDK] Inlong SDK Dirty Sink supports retry sending

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java
inlong-agent/conf/agent.properties

Fixes #11499 
Sometimes it is necessary to assign dedicated audit addresses to certain machines
By default, use the locally configured audit address
*(example:)*
No doc needed

[INLONG-11499][Agent] By default, use the locally configured audit address

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/DirtyDataDetailResponse.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/dirtyData/impl/DirtyQueryLogServiceImpl.java
inlong-manager/manager-web/src/main/resources/application-dev.properties
inlong-manager/manager-web/src/main/resources/application-prod.properties
inlong-manager/manager-web/src/main/resources/application-test.properties

Fixes #11513
Rename configuration names related to dirty data.
Rename configuration names related to dirty data.

[INLONG-11513][Manager] Rename configuration names related to dirty data

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/plugin/Instance.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/CommonInstance.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/AbstractSource.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/instance/MockInstance.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestLogFileSource.java

Fixes #11516 
Accelerate the process exit speed to prevent the process from being forced to exit during restart
1 Reduce cycle waiting time
2 Parallel notification that instacne needs to exit
*(example:)*
No doc needed

[INLONG-11516][Agent] Accelerate the process exit speed

---

inlong-agent/agent-installer/bin/installer.sh
inlong-agent/bin/agent.sh

Fixes #11518 
Support multiple processes
Filter the current user during process detection
*(example:)*
No doc needed

[INLONG-11518][Agent] Support multiple processes

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestLogFileSource.java

Fixes #11527 
The large amount of IO required to restore historical collection sites after Agent restart results in slow startup and requires optimization
1 Save both row and byte position information when saving offset
2 When restarting and restoring, the byte position is directly obtained from the offset information, without the need to traverse files to calculate the position
*(example:)*
No doc needed

[INLONG-11527][Agent] Save both row and byte position information when saving offset

---

inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleConstants.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleEngine.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/exception/DolphinScheduleException.java
inlong-manager/manager-schedule/src/test/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleEngineTest.java

Fixes #11531 
* A project in DS engine doesn't need to be created at bean initialize time, so it only needs to be called when a register-related-handle method is called, and this also allows data synchronization at each processing time
* delete operation need to add retry mechanism
* add `start()` method in `handleRegister()`, `handleUnregister()` and `handleUpdate()`, before related operation be called
* because of situation below, deleting operation should add retry mechanism
*(example:)* …

[INLONG-11531][Manager] Fix bug in DolphinScheduler engine

---

inlong-distribution/src/main/assemblies/sort-connectors-v1.18.xml
inlong-sort/sort-core/pom.xml
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/pom.xml
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/source/KafkaSource.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/source/KafkaSourceBuilder.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/source/reader/KafkaSourceReader.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/DynamicKafkaDeserializationSchema.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/DynamicKafkaRecordSerializationSchema.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaConnectorOptions.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaConnectorOptionsUtil.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicSink.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicSource.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/KafkaDynamicTableFactory.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/ReducingUpsertSink.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/ReducingUpsertWriter.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/SinkBufferFlushMode.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/src/main/java/org/apache/inlong/sort/kafka/table/UpsertKafkaDynamicTableFactory.java
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/pom.xml
licenses/inlong-sort-connectors/LICENSE

Fixes [#11494 [Feature][Sort] Add Kafka connector on Flink 1.18](https://github.com/apache/inlong/issues/11494)
This PR adds a Kafka connector to `inlong-sort` for Flink 1.18 support.
- Migrated the Kafka connector from [flink-kafka-connector 3.2.0](https://github.com/apache/flink-connector-kafka/releases/tag/3.2.0) to support Flink 1.18.
- Updated the relevant Maven `pom.xml` to reflect the changes.
Further formal testing will be introduced in [#11495](https://github.com/apache/inlong/issues/11495).  
Currently, a `KafkaProducer` is used to send messages to Kafka, and these messages are consumed by `sort-connectors-v1.18`, which is introduced in this PR.  
Since there is no verified functional sink yet, the built-in `file-system` sink is used in this test.
In …

[INLONG-11494][Sort] Add Kafka connector on Flink 1.18

---

inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/airflow/AirflowScheduleEngine.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/airflow/config/AirflowConfig.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleEngine.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleOperator.java
inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleUtils.java
inlong-manager/manager-web/src/main/resources/application-dev.properties
inlong-manager/manager-web/src/main/resources/application-prod.properties
inlong-manager/manager-web/src/main/resources/application-test.properties

Fixes #11544
- Simplify Annotations.
- Add default values.
*(example:)*

[INLONG-11544][Manager] Optimize the configuration of the Manager schedule module

---

inlong-sdk/dirty-data-sdk/src/main/java/org/apache/inlong/sdk/dirtydata/InlongSdkDirtySender.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/sdk/InlongSdkDirtySink.java

Fixes #11546 
Provide async and sync way to report dirty data
Add sendDirtyMessage and sendDirtyMessageAsync method
*(example:)*

[INLONG-11546][SDK] Support async and sync report dirty data

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupInfo.java

Fixes #11551 
The result for group info missed the schedule engine field. So this pull request add it.
Add schedule engine to group info result

[INLONG-11551][Manager] Add schedule engine to group info result

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/MemoryManager.java

Fixes #11562 
The current memory control has fixed several types of semaphores, which are not sufficient
Modify the MemoryManager class to support adding semaphore
*(example:)*
No doc needed

[INLONG-11562][Agent] Modify the MemoryManager class to support adding semaphore

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/DatabaseSqlSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/KafkaSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/MongoDBSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/MqttSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/OracleSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/PostgreSQLSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/PulsarSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/RedisSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/SQLServerSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/extend/DefaultExtendedHandler.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/extend/ExtendedHandler.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/AbstractSource.java

Fixes #11560 
Make them applicable to other types of data sources as well
Adjust the directory of data source extension plugins
*(example:)*
No doc needed

[INLONG-11560][Agent] Adjust the directory of data source extension plugins

---

inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.18/pom.xml
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.18/src/test/java/org/apache/inlong/sort/tests/Kafka2Elasticsearch7Test.java
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.18/src/test/resources/env/kafka_test_kafka_init.txt
inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.18/src/test/resources/flinkSql/kafka_to_elasticsearch.sql
inlong-sort/sort-flink/sort-flink-v1.18/sort-connectors/kafka/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory

Fixes #11495
Fixes #11553 
To verify the correctness of #11494 in a formal way.
To fix the problem of #11494, which is documented in #11553
For #11495, added end2end test for Kafka connector by producing kafka message with `kafka-clients` dependency and extract the information with Kafka connector introduced by #11494. To better automate the whole process, the result is loaded to Elasticsearch7 with the existing elsasticsearch7-inlong connector. The result is then retrieved by elasticsearch client dependency and compared with the expected result.
Also, some unused dependecies are removed and the test connects to elasticsearch with co.elastic instead of high-level client.
For #11553, the package name in meta-inf of the Kafka connnector is corrected, so that the `DynamicFactory` class can …

[INLONG-11495][Sort] Add end-to-end test for Kafka connector v1.18

---

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java

Fixes #11556 
Resolve exceptions when saving installation packages
1. Create a non-existent folder
2. Identify the home directory
*(example:)*
No doc needed

[INLONG-11556][Agent] Resolve exceptions when saving installation packages

---

inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/AgentBaseTestsHelper.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/cos/COSTask.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/cos/FileScanner.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/AgentBaseTestsHelper.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/instance/TestInstanceManager.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/KafkaSinkTest.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/PulsarSinkTest.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/filecollect/TestSenderManager.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestLogFileSource.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestRedisSource.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestSQLServerSource.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/TestCOSTask.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/TestLogFileTask.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/TestTaskManager.java

Fixes #11574 
Add COS source unit test
1. Mock COS SDK
2. Check  the ability of scanning folder and file 
*(example:)*
No doc needed

[INLONG-11574][Agent] Add COS source unit test

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/filecollect/TestSenderManager.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ConfigConstants.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/MessageSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigEntry.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/QueueObject.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/Sender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/SyncMessageCallable.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/threads/MetricWorkerThread.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/threads/TimeoutScanThread.java

Fixes #11599
1. When obtaining metadata, increase the frequency control of failed access to avoid repeated access causing access pressure on the Manager;
2. Use the request timeout setting configured in the ProxyClientConfig class, and no longer set the timeout value for each request one by one;
3. Remove unnecessary assignment operations on message objects when data encryption is not performed;
4. Add regionName configuration parameters in the DataProxy

[INLONG-11599][SDK] Optimize the configuration related content in the ProxyClientConfig class

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/worker.go
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/go.mod
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/go.sum
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/util/id.go

Fixes #11597
Speed up UUIDv4 generation.
- Swap references from `github.com/gofrs/uuid` to `github.com/google/uuid` while preserve compatibility. Benchmark is listed in the original issue.
*(example:)*
- Does this pull request introduce a new feature? (yes / no) _no_
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) _not applicable_
- If a feature is not applicable for documentation, explain why? _This is not really a feature_

[INLONG-11597][SDK] Optimize the generation speed of UUIDv4

---

inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/field/format/StringFormatInfo.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/field/format/VarCharFormatInfo.java

Fixes #11606 
When formatting string field values, the original value is not modified.
For example:
Raw data is aa|\tbb\tcc|dd, formatted data is [aa, bb\tcc, dd], the first char '\t' is missing.
Expect data is [aa, \tbb\tcc, dd].
*(example:)*

[INLONG-11606][Sort] When formatting string field values, the original value is not modified

---

inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/utils/DataUtils.java
inlong-audit/audit-common/src/main/test/java/org/apache/inlong/audit/utils/DataUtilsTest.java
inlong-audit/audit-common/src/test/java/org/apache/inlong/audit/utils/DataUtilsTest.java
inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/source/ServerMessageHandler.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/config/JdbcConfig.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/metric/MetricDimension.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/metric/MetricItem.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/metric/MetricsManager.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/metric/prometheus/StorePrometheusMetric.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/service/JdbcService.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/service/consume/PulsarConsume.java
inlong-audit/audit-store/src/main/java/org/apache/inlong/audit/store/utils/PulsarUtils.java

- Fixes #11605
Added audit data legitimacy verification
Verify the legitimacy of the dimensions and indicators of audit data, discard dirty data, and report to monitoring

[INLONG-11605][Audit] Added audit data legitimacy verification

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/RowDataSourceData.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/RowDataSourceDecoder.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/RowDataSinkEncoder.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/utils/FieldToRowDataUtils.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/utils/RowToFieldDataUtils.java

Fixes #11616 
Use self-defined Field and RowData conversion utils instead of the one in Flink.
Because the Flink implementation will lead to the cast exception
*(example:)*

[INLONG-11616][SDK] Use self-defined Field and RowData conversion utils

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/AbstractSource.java

Fixes #11614 
Fix the signal leakage issue of AbstractSource class
After the prepareToRead function executes an exception, it is considered that the data source can be terminated
*(example:)*
No doc needed

[INLONG-11614][Agent] Fix the signal leakage issue of AbstractSource class

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/arithmetic/FibonacciFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestFibonacciFunction.java

Fixes #11002 
Add one arithmetic function classes:FibonacciFunction. Also, add the corresponding unit test codes
refer to pr #11003 
*(example:)*

[INLONG-11002][SDK] Transform SQL support Fibonacci function

---

inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/Exception/InvalidRequestException.java
inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/consts/OpenApiConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/auditor/Audit.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/auditor/ReconciliationData.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/auditor/RequestInfo.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/cache/AbstractCache.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/cache/RealTimeQuery.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/config/SqlConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/node/ApiService.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/utils/AuditUtils.java

- Fixes #11620
Added a new API to provide automatic retry, automatic cache query, and automatic deduplication capabilities
If the query cache fails, directly query the data source. If it still fails, deduplicate the audit data.

[INLONG-11620][Audit] Provide an open API for module reconciliation

---

inlong-dashboard/src/plugins/nodes/defaults/MySQL.ts

Fixes #11643 
MySQL node password changed to optional
MySQL node password changed to optional
before：
after：

[INLONG-11643][Dashboard] The MySQL node password is not required

---

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/sdk/InlongSdkDirtySink.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/dirty/sink/sdk/InlongSdkDirtySinkFactory.java
inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/dirty/utils/AESUtils.java

Fixes #11621
Encrypt the auth key to avoid plain text
*(example:)*

[INLONG-11621][Sort] Support auth key encryption when use inlong sdk dirty sink

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/MetricConfig.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/Sender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/pb/config/ContextProxyClusterConfigLoader.java

Fixes #11656
1. Update all commons.lang references to commons.lang3;
2. Change the key of encryption information from authSecretId to userName
3. When reselecting a node, no connection will be established for the selected node

[INLONG-11656][SDK] DataProxy Java SDK lacks a common-lang dependency

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/README.md
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/connpool/connpool.go
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/client.go
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/options.go
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/options_basic.go

Fixes #11668 
Add max life time support for the connections in the conn pool of Golang SDK
1. inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/README.md
2. inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/connpool/connpool.go
3. inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/client.go
4. inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/options.go
5. inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/options_basic.go
*(example:)* …

[INLONG-11668][SDK] Add max life time support for the connections in the conn pool of Golang SDK

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/common/ErrorCode.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/common/ProcessResult.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/common/SdkConsts.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/HttpProxySender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java
inlong-sdk/dataproxy-sdk/src/test/java/org/apache/inlong/sdk/dataproxy/ProxyConfigManagerTest.java
inlong-sdk/pom.xml

Fixes #11683 
1. Add the ErrorCode class to define the error types encountered during the processing of ProxyConfigManager;
2. Add the ProcessResult class to return the result of the ProxyConfigManager function through the ProcessResult object;
3. Make modifications to the call layer of the ProxyConfigManager function

[INLONG-11683][SDK] Optimize the functions return of the ProxyConfigManager class

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/store/InstanceStore.java

Fixes #11681 
Fix bug of duplicate file collection
Add a delimiter after the task ID when querying multiple instances to prevent misjudgment.
*(example:)*
No doc needed

[INLONG-11681][Agent] Fix bug of duplicate file collection

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentStatusManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/FileStaticManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java

Fixes #11685 
Prevent agent IP uncertainty when the machine has multiple IPs
Only use configuration files to provide IP address
*(example:)*
No needed doc

[INLONG-11685][Agent] Only use configuration files to provide IP address

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/common/EventInfo.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/exception/ProxyEventException.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/http/HttpEventInfo.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/tcp/TcpEventInfo.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/LogCounter.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java
inlong-sdk/dataproxy-sdk/src/test/java/org/apache/inlong/sdk/dataproxy/EventInfoTest.java

Fixes #11689
1. Add EventInfo class and related subclasses TcpEventInfo and HttpEventInfo to manage user reported information;
2. Add ProxyEventException exception class to classify reported information related exceptions;
3. Define the reserved word set with macro definitions

[INLONG-11689][SDK] Optimize user reporting information management

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ConfigHolder.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/HttpClientExample.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/TcpClientExample.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/http/InternalHttpSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ClientHandler.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ClientPipelineFactory.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/DefClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/HttpProxySender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/NettyClient.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/Sender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/http/HttpMsgSenderConfig.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/tcp/TcpEventInfo.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/tcp/TcpMsgSenderConfig.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/threads/MetricWorkerThread.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/threads/TimeoutScanThread.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java
inlong-sdk/dataproxy-sdk/src/test/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfigTest.java
inlong-sdk/dataproxy-sdk/src/test/java/org/apache/inlong/sdk/dataproxy/ProxyConfigManagerTest.java
inlong-sdk/dirty-data-sdk/src/main/java/org/apache/inlong/sdk/dirtydata/InlongSdkDirtySender.java

Fixes #11692
1. Add ConfigHolder  class, and rename ClientMgr to DefClientMgr
2. Adjust the package path of TcpMsgSenderConfig and HttpMsgSenderConfig

[INLONG-11692][SDK] The metadata update function abstracted to ConfigHolder

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/connpool/connpool.go

[INLONG-11694][SDK] Fix infinte loop in Golang SDK

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/MessageSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/MsgSendCallback.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/http/HttpMsgSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/tcp/TcpMsgSender.java

Fixes #11695
1. Abstract the methods supported by TCP Sender and HTTP HttpProxySender, abstract the necessary support interface MessageSender for public message senders, TCP sender interface TcpMsgSender, HTTP sender interface HttpMsgSender,
2. Abstract the callback interface MsgSendCallback, for asynchronous sending, and support the view of specific error information;
3. According to the network management implementation of TCP and HTTP, abstract the client management interface ClientMgr

[INLONG-11695][SDK] MessageSender related interfaces abstraction

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/common/ErrorCode.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/TcpCallFuture.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/TcpNettyClient.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/codec/DecodeObject.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/codec/EncodeObject.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/codec/ProtocolDecoder.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/codec/ProtocolEncoder.java

Fixes #11698
1. Add EncodeObject and DecodeObject classes, and place the corresponding ProtocolDecoder and ProtocolEncoder under the network.tcp path,
2. Add corresponding TCP client object management and call future class

[INLONG-11698][SDK] Optimize TCP encode and decode implementation

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/common/ErrorCode.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/common/SdkConsts.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/ClientHandler.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/ClientPipelineFactory.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/SendQos.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/TcpClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/codec/ProtocolEncoder.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/BaseSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/tcp/InLongTcpMsgSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java

Fixes #11700
1. Construct the message sending base class BaseSender, and then improve the HTTP Sender implementation;
2. Construct the TCP message reporting class InLongTcpMsgSender to send TCP messages;
3. Construct the TCP client Manager to manage TCP message reporting, response processing, and sending timeout, etc;
4. Add comments.

[INLONG-11700][SDK] Optimize TCP message reporting Sender implementation

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/connpool/connpool.go

Fixes #11703 
Refactor
1. rename `connpool.recoverAndRebalance()` to `connpool.innerWork()`
2. use a select/case chan to replace the default case.
*(example:)*

[INLONG-11703][SDK] Improve the cleanExpiredConnTicker select logic in the connpool of the Golang SDK

---

inlong-common/src/main/java/org/apache/inlong/common/enums/MetaField.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/ExtractNode.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/PulsarExtractNode.java

[INLONG-11674][Sort] Pulsar Source supports InlongMsg metadata

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ConfigHolder.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/MetaSyncInfo.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/MetricDataHolder.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/TimeCostInfo.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/TimeWastInfo.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/TrafficInfo.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/DefClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/http/HttpClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/TcpClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/BaseSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/http/InLongHttpMsgSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/tcp/InLongTcpMsgSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java

Fixes #11680
1. Define new indicator models: metadata synchronization indicator MetaSyncInfo, time consumption statistics indicator TimeWastInfo, traffic statistics indicator TrafficInfo
2. Add indicator data aggregation and output class MetricDataHolder to manage indicator statistics and output;
3. Add statistics management for HTTP and TCP data reporting, as well as metadata update operations

[INLONG-11680][SDK] Optimize metric-related implementation

---

inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceTest.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/BaseMsgSenderFactory.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/TimeCostInfo.java

Fixes #11713
For BaseMsgSenderFactory:
1. Add log when sender factory is closed
2. Remove redundant semicolons
3. Use the directly return value of metadata query
For TimeCostInfo:
4. Fix the average time consumption calculation in TimeCostInfo class

[INLONG-11713][SDK] Optimize BaseMsgSenderFactory and TimeCostInfo implementation

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/MetaSyncInfo.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/MetricDataHolder.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/TimeCostInfo.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/TrafficInfo.java

Fixes #11715
1. Add TCP configure items;
2. Delete the redundant cnt field in bucketT;
3. Correct the incorrect field name metaSync

[INLONG-11715][SDK] Optimize metric report content

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/DefClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/TcpClientMgr.java

Fixes #11717
Add out-of-bounds check when  in getClientByRoundRobin()

[INLONG-11717][SDK] Add out-of-bounds check when in getClientByRoundRobin()

---

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/NodeFactory.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/base/LoadNodeProvider.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/base/NodeProvider.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/PulsarProvider.java
inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/TubeMqProvider.java

Fixes #11722
Pulsar source supports Inlong properties field.
Tube source supports Inlong properties field.
When the protocol type is inlongMsg, pulsar source and tube source are equipped with inlong properties built field.

[INLONG-11722][Manager]Pulsar source supports Inlong properties field

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/BaseMsgSenderFactory.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/MsgSenderFactory.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/MsgSenderMultiFactory.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/MsgSenderSingleFactory.java

Fixes #11720
1. Lock when releasing and creating BaseMsgSenderFactory objects
2. Adjust the release interface to remove unnecessary exceptions
3. Remove useless code

[INLONG-11720][SDK] Optimize MsgSenderSingleFactory implementation

---

inlong-sdk/dirty-data-sdk/src/main/java/org/apache/inlong/sdk/dirtydata/InlongSdkDirtySender.java

Fixes #11719
1. Replace the Sender object in the InlongSdkDirtySender class with TcpMsgSender

[INLONG-11719][SDK] Replace the Sender object in the InlongSdkDirtySender class with TcpMsgSender

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/BaseMsgSenderFactory.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/common/ProxyClientConfig.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/MetricConfig.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/MetricDataHolder.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/http/HttpClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/TcpClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/BaseSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java

Fixes #11734
1. Add statistics on the start and end time of stop to confirm the time-consuming point;
2. When stopping, the request waiting for response directly returns the SDK closed response;
3. No more indicator output when stopping;
4. Configure metric settings through ProxyClientConfig.java
5. Other optimizations that facilitate exit

[INLONG-11734][SDK] Optimize SDK stop processing flow

---

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/manager/InlongMultiTopicManager.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/manager/InlongSingleTopicManager.java
inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/manager/InlongTopicManager.java

[INLONG-11711][SDK] SortSDK shares the same PulsarClient among different SortTasks to avoid performance bottlenecks caused by too many PulsarClients
Fixes #11711 
SortSDK shares the same PulsarClient among different SortTasks to avoid performance bottlenecks caused by too many PulsarClients
Excessive PulsarClients lead to significant CPU consumption in waitForNextTick.
*(example:)* …

[INLONG-11711][SDK] SortSDK shares the same PulsarClient among different SortTasks to avoid performance bottlenecks caused by too many PulsarClients

---

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/MetaSyncInfo.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/MetricDataHolder.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/TimeCostInfo.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/TrafficInfo.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/http/HttpClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/TcpClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/TcpNettyClient.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/BaseSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/http/InLongHttpMsgSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/tcp/InLongTcpMsgSender.java

Fixes #11743
Reduce the key length as much as possible and shorten the total length of indicator output;
Refine the message sending process and distinguish between synchronous, asynchronous, HTTP and TCP metric data;
Optimize the residual request processing logic when HTTP exits and add notification logic for calling callbacks;
Other detailed adjustments

[INLONG-11743][SDK] Adjustment of metric statistics

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/BaseMsgSenderFactory.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/MsgSenderFactory.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/MsgSenderMultiFactory.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/MsgSenderSingleFactory.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/common/ErrorCode.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/common/ProxyClientConfig.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/common/SdkConsts.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/MetricDataHolder.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/PkgCacheQuota.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/http/HttpClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/TcpCallFuture.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/TcpClientMgr.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/TcpNettyClient.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/codec/EncodeObject.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/BaseSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/http/HttpMsgSenderConfig.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/http/InLongHttpMsgSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/tcp/InLongTcpMsgSender.java
inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/tcp/TcpMsgSenderConfig.java
inlong-sdk/dataproxy-sdk/src/test/java/org/apache/inlong/sdk/dataproxy/PkgCacheQuotaTest.java
inlong-sdk/dataproxy-sdk/src/test/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfigTest.java

Fixes #11754
1. Add the total pending request and size limit class PkgCacheQuota
2. Adjusted the Sender and factory objects, increased the total request and size limit for the Sender single object and the factory-based
3. Added the permission application and release for the number of requests and request size in the process with pending requests;
4. Adjusted the sending size control of the agent to change it to the total and size limit control for pending requests

[INLONG-11754][SDK] Add the total number of in-flight requests and total size limits

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CommonConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/plugin/file/Task.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/Sender.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/AbstractTask.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/CronTask.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/instance/TestInstanceManager.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/MockTask.java

Fixes #11760 
Prevent multiple collection tasks from executing simultaneously, which can lead to too many instances
Increase the number of global instances control
*(example:)*
No doc needed

[INLONG-11760][Agent] Increase the number of global instances control

---

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/AbstractSource.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestLogFileSource.java

Fixes #11762 
Reduce the waiting time after the collection of data sources that have not been updated for a long time
Modify the logic for determining the end of the data source
*(example:)*
No doc needed

[INLONG-11762][Agent] Modify the logic for determining the end of the data source

---

inlong-agent/conf/log4j2.xml

Fixes #11778 
Separate the logs of the DataProxy SDK
Separating the logs of the DataProxy SDK can help troubleshoot issues
*(example:)*
No doc needed

[INLONG-11778][Agent] Separate the logs of the DataProxy SDK

---

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/dataproxy/Sender.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/dataproxy/SenderManager.java
inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/filecollect/TestSender.java

Fixes #11774 
Modify the lifecycle of the DataProxy SDK object
Modify the lifecycle of the dataproxy SDK object to match the task
*(example:)*
No doc needed

[INLONG-11774][Agent] Modify the lifecycle of the DataProxy SDK object

---

inlong-dashboard/src/ui/pages/Clusters/NodeEditModal.tsx
inlong-dashboard/src/ui/pages/Clusters/NodeManage.tsx

Fixes #11780
DataProxy node edit failed
DataProxy node edit failed
before：
When updating, the validation fails, but the dataproxy node does not need this field for editing
after：
Page style changes
before:
Except for the delete and edit buttons, the other buttons belong to the agent node.
after：

[INLONG-11780][Dashboard] DataProxy node edit failed

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/inlong_dataproxy.cpp

- Fixes #11787
When compiling the  Dataproxy Python SDK, a compilation failure exception will occur
Add mutex header file for Dataproxy Python SDK

[INLONG-11787][SDK] Dataproxy Python SDK lacks mutex header file

---

inlong-dashboard/src/ui/pages/GroupDetail/index.tsx

Fixes #11799 
The page will not refresh after the access groupId is switched
Add a listener for groupId in index.tsx under the GroupDetail directory

[INLONG-11799][Dashboard] The page will not refresh after the access groupId is switched

---

inlong-agent/conf/log4j2.xml

Fixes #11813 
For easy viewing of SDK debug logs during debugging
Add SDK debug log data
*(example:)*
No doc needed

[INLONG-11813][Agent] Add Dataproxy SDK debug log

---

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/CommonConstants.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/AgentEventMetricItem.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/AgentEventMetricItemSet.java
inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/EventReportUtils.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentStatusManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/FileStaticManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java
inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskManager.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java
inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/dataproxy/Sender.java

Fixes #11815 
To be compatible with multiple different monitoring systems
Add a unified reporting point for events
*(example:)*
No doc needed

[INLONG-11815][Agent] Add a unified reporting point for events

---

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditReporterImpl.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/CdcIdEnum.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/MetricIdEnum.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/entity/AuditRules.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/entity/CdcType.java
inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/util/AuditManagerUtils.java
inlong-audit/audit-sdk/src/test/java/org/apache/inlong/audit/util/AuditManagerUtilsTest.java

- Fixes #11817
In the real-time synchronization scenario, it is necessary to audit the insert, update after, update before, and delete operations.
InLong audit adds audit reporting and reconciliation of multiple event types such as insert, update after, update before, delete, etc.

[INLONG-11817][Audit] Audit SDK supports CDC scenario audit reconciliation

---

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/Constant.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/CsvDeserializationInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/InLongMsgCsv2DeserializationInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/InLongMsgCsvDeserializationInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/InLongMsgKvDeserializationInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/InLongMsgTlogCsvDeserializationInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/InLongMsgTlogKvDeserializationInfo.java
inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/KvDeserializationInfo.java

Fixes #11821
KvDeserializationInfo、CsvDeserializationInfo、InLongMsgCsv2DeserializationInfo、InLongMsgCsvDeserializationInfo、InLongMsgKvDeserializationInfo、InLongMsgTlogCsvDeserializationInfo、InLongMsgTlogKvDeserializationInfo  all class of deserialized configurations add two class properties.
first one 'deleteEscapeCharWhileDes', default is true,   escape char will be removed during deserialization in default way.
second one 'autoAppendEscapeCharAfterDes', default is false, escape char will not be supplied after deserialization if the reported data lacks the escape sequence of the separatorin in default way.
such as ,
CSV string: aaa|bbbb|dd\cc ,
when 'deleteEscapeCharWhileDes' is false
result is "aaa bbbb dd\cc"
when 'deleteEscapeCharWhileDes' is true
result is "aaa bbbb ddcc"
other …

[INLONG-11821][Sort] kv and csv deserialization configuration support  whether to remove and automatically add escape configuration

---

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/metrics/status/SortTaskStatus.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/metrics/status/SortTaskStatusMetricListener.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/metrics/status/SortTaskStatusRepository.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaProducerCluster.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/FetchCallback.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/v2/SortCluster.java

Fixes #11836
1. ​​Implement flow control in SortStandalone first​​ to resolve current frequent alert issues.
​​2. Enable flow control at the SortTask granularity​​:
1) Initial buffer size must be ​​1 data unit​​ upon deployment.
2) After successful data transmission, the buffer size increases to ​​one-third of the default configuration value​​ (configurable).
3) ​​Trigger SortTask deactivation in the container​​ if sending failure rate exceeds ​​50% capacity​​ (configurable), ​​and​
failures to scale up within the current minute exceed ​​10 data units​​ (configurable). Force shutdown via kafkaClient.closeTimeout (ensuring time-bound deactivation). Block SortTask reactivation for ​​5 minutes​​ (configurable). …

[INLONG-11836][Sort] Provide SortStandalone flow control to prevent single-task blocking from affecting the normal sorting of other tasks

---

inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/cache/DayCache.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/cache/RealTimeQuery.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/config/AuditColumn.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/config/SqlConstants.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/entities/StatData.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/utils/AuditUtils.java

- Fixes #11855
When there are many data streams under an inlong group, providing audit data at the group level allows you to view the data reconciliation status more intuitively.
Audit supports Audit reconciliation at the granularity of inlong group

[INLONG-11855][Audit] Audit supports Audit reconciliation at the granularity of inlong group 

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/util/id.go

If an IP is not available, we use id = 0 instead of crashing.
Fixes #11871
This PR allows programs which import the InLong DataProxy SDK to initialise properly even if no IP address is available on the system. Modular programs such as Telegraf may import the InLong SDK, but enable/disable its features in the configuration. Currently, such programs crash even if the configuration disables InLong. This PR fixes that.
Fairly trivial, please see the diff.
- happy path: all tests, because the change only impacts the init() function.
- sad path: I manually verified this PR allows Telegraf to start in a Docker container with no network.
- Does this pull request introduce a new feature? No

[INLONG-11871][SDK] Fix init crashes when no IP available

---

inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/auditor/Audit.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/cache/RealTimeQuery.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/entities/StatData.java
inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/except/QueryAuditException.java

- Fixes #11900
In the case of no data, the Audit OpenAPI defaults to 0
When there is no data, fill it with 0

[INLONG-11900][Audit] In the case of no data, the Audit OpenAPI defaults to 0

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/FunctionTools.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/ParserTools.java

[INLONG-11905][SDK] TransformSDK calls the org.reflections library APIs ​​according to version 0.9.12, not version 0.10.2

---

inlong-common/src/main/java/org/apache/inlong/common/constant/DeserializationType.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/dataType/DataTypeConfig.java
inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/dataType/PbConfig.java
inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/datatype/PbDataTypeOperator.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/PbSourceDecoder.java
inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/TransformProcessor.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/TestAny2PbProcessor.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/TestPb2CsvProcessor.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/SinkContext.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/DefaultEvent2LogItemHandler.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/DefaultEvent2IndexRequestHandler.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/http/HttpIdConfig.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaIdConfig.java
inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarIdConfig.java

Fixes #11911 
SortStandalone supports routing PB-format data streams to Kafka and Pulsar
SortStandalone supports routing PB-format data streams to Kafka and Pulsar
*(example:)*

[INLONG-11911][Sort] SortStandalone supports routing PB-format data streams to Kafka and Pulsar

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/string/UrlEncodeFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestUrlEncodeFunction.java

Fixes #11943 
TransformFunction: url_encode supports specifying character sets
TransformFunction: url_encode supports specifying character sets
*(example:)*

[INLONG-11943][Sort] TransformFunction: url_encode supports specifying character sets

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/string/UrlDecodeFunction.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestUrlDecodeFunction.java

Fixes #11942 
TransformFunction: url_decode supports specifying character sets
TransformFunction: url_decode supports specifying character sets
*(example:)*

[INLONG-11942][Sort] TransformFunction: url_decode supports specifying character sets

---

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/utils/FieldToRowDataUtils.java
inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/temporal/TestFromUnixTimeFunction.java

Fixes #11952 
Transform handles field-level exceptions by nullifying only the affected field while preserving the entire record
Transform handles field-level exceptions by nullifying only the affected field while preserving the entire record
*(example:)* …

[INLONG-11952][SDK] Transform handles field-level exceptions by nullifying only the affected field while preserving the entire record

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/client.go
inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/util/id.go

Fixes #11954 
Fix potential data race in Golang SDK
1. Handle all the IO errors;
2. Disard connection's ring buffer after handling the response;
3. Fix lint error in id.go by the way.
*(example:)*

[INLONG-11954][SDK] Fix potential data race in Golang SDK

---

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/inlong_dataproxy.cpp

Fixes #12010
When reporting a string containing Chinese characters, the length of a Chinese character in Python is 1, while the length of a Chinese character in C++ is 3, which causes the string length calculated by Python to be smaller than that in C++. Therefore, the reported length needs to be recalculated according to the C++ rules in the `send()` function to avoid data truncation.
modify the `inlong_dataproxy.cpp` file
*(example:)*

[INLONG-12010][SDK] Fix the problem of truncated string data containing Chinese characters when reporting using Dataproxy Python SDK
