inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/FieldType.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtils.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/SourceRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/iceberg/IcebergCatalogUtils.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/iceberg/IcebergSourceOperator.java
- Fixes #9041 
Support saving schema information when saving iceberg source.
Support saving schema information when saving iceberg source.
=> [INLONG-9041][Manager] Support saving schema information when saving iceberg source

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/client/tcp_client.cc
- Fixes #9044 
*Add server response log to facilitate troubleshooting.*
*Add server response log to facilitate troubleshooting when tcp client has exception.*
=> [INLONG-9044][SDK] Add server response log to facilitate troubleshooting

inlong-manager/manager-dao/src/main/resources/mappers/WorkflowTaskEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/workflow/form/process/ApplyConsumeProcessForm.java
- Fixes #9051 
Add consumer group in the approval form.
Add consumer group in the approval form.
=> [INLONG-9051][Manager] Add consumer group in the ApplyConsumeProcessForm

licenses/inlong-agent/LICENSE, licenses/inlong-audit/LICENSE, licenses/inlong-dataproxy/LICENSE, licenses/inlong-manager/LICENSE, licenses/inlong-sort-connectors/LICENSE, licenses/inlong-sort-standalone/LICENSE, licenses/inlong-sort/LICENSE, pom.xml
- Fixes #9046
Bump snappy-java to 1.1.10.4 to fix the CVE.
=> [INLONG-9046][CVE] Bump snappy-java to 1.1.10.4

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongStreamClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongStreamApi.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInLongStreamController.java
- Fixes #9062 
Add default values for stream related interface parameters.
Add default values for stream related interface parameters.
=> [INLONG-9062][Manager] Add default values for stream related interface parameters

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/TubeMqProvider.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/tubemq/TubeMQSource.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/TubeMQConstant.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/ExtractNode.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/TubeMQExtractNode.java, inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/TubeMQExtractNodeTest.java, inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/TubeMQNodeSqlParseTest.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQDynamicTableFactory.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQDynamicTableFactory.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQOptions.java
- Fixes #9075 
*(example:)*
- If a …
=> [INLONG-9075][Sort] TubeMQSource support InlongMsg format

inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/metrics/SortMetricItem.java
- Fixes #9084 
*(example:)*
- If a …
=> [INLONG-9084][Sort] Fix failure of parsing InlongGroupId when report Inlong Audit

inlong-distribution/pom.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/TubeMqProvider.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/tubemq/TubeMQSource.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/tubemq/TubeMQSourceOperator.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/TubeMQConstant.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/TubeMQExtractNode.java, inlong-sort/sort-core/pom.xml, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQDynamicTableFactory.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQOptions.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/pom.xml, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQProducer.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQDynamicTableFactory.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQOptions.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQTableSink.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQTableSource.java, inlong-tubemq/tubemq-client/pom.xml, inlong-tubemq/tubemq-server/pom.xml
- Fixes #9077 
*(example:)*
- If a …
=> [INLONG-9077][Sort] Fix TubeMQ connector fail to subscribe streamId

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/PulsarExtractNode.java, inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SinkMetricData.java, inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SourceMetricData.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarDynamicTableFactory.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/pom.xml, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/PulsarTableFactory.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableDeserializationSchema.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableDeserializationSchemaFactory.java
- Fixes #9064 
[INLONG-9064][Sort] Add Audit report for Pulsar connector in flink 1.15
[INLONG-9064][Sort] Add Audit report for Pulsar connector in flink 1.15
=> [INLONG-9064][Sort] Add Audit report for Pulsar connector in flink 1.15

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java
- Fixes #9087 
*(example:)*
- If a …
=> [INLONG-9087][Sort] TubeMQ Connector use latest offset mode

.asf.yaml
- Fixes #9104
Add a protected branches strategy for the master branch
Add a protected branches strategy for the master branch
=> [INLONG-9104][ASF] Add a protected branches strategy for the master branch

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/iceberg/IcebergColumnInfo.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/iceberg/IcebergCatalogUtils.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/iceberg/IcebergResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/iceberg/IcebergSinkOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/iceberg/IcebergSourceOperator.java
- Fixes #9098 
Support to save additional info for the Iceberg field.
Support to save additional info for the Iceberg field.
=> [INLONG-9098][Manager] Support to save additional info for the Iceberg field

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongStreamClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongStreamApi.java
- Fixes #9073 
Add `getStreamBriefInfo` method for `InlongStreamClient`.
Add `getStreamBriefInfo` method for `InlongStreamClient`.
=> [INLONG-9073][Manager] Add getStreamBriefInfo method for InlongStreamClient

inlong-dashboard/src/ui/components/Layout/index.tsx, inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json
- Fixes https://github.com/apache/inlong/issues/9107
=> [INLONG-9107][Dashboard] Navigation widget optimization

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/InstanceProfile.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/TaskProfile.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/FileTask.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java
[INLONG-9112][Agent] Add task and instance profile
- Fixes #9112 
Add task and instance profile to serialize task and instance config
Add task and instance profile, and add taskProfileDto to translate manager configure into task profile
*(example:)*
=> [INLONG-9112][Agent] Add task and instance profile

inlong-dashboard/src/ui/components/GroupLogs/GroupLogs.tsx
- Fixes https://github.com/apache/inlong/issues/9114
=> [INLONG-9114][Dashboard] Stream log query parameter optimization

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/ActionType.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceAction.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/ActionType.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskAction.java
[INLONG-9122][Agent] Add task and instance action
- Fixes #9122 
To manage task and instance agent define different action
Add task and instance action
*(example:)*
=> [INLONG-9122][Agent] Add task and instance action

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/AbstractGroupOperator.java
- Fixes #9106 
Fix the problem of unable to modify the responsible person of the group.
Fix the problem of unable to modify the responsible person of the group.
=> [INLONG-9126][Manager] Fix the problem of unable to modify the responsible person of the group

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/InstanceDb.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/KeyValueEntity.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/TaskProfileDb.java
[INLONG-9124][Agent] Add task and instance db
- Fixes #9124 
Add task and instance db
Add task and instance db
*(example:)*
=> [INLONG-9124][Agent] Add task and instance db

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQDynamicTableFactory.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQDynamicTableFactory.java
- Fixes #9128 
*(example:)*
- If a …
=> [INLONG-9128][Sort] Failed to init TubeMQ source with InlongMsg type message

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/TubeMqProvider.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSourceRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/tubemq/TubeMQSource.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/tubemq/TubeMQSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/tubemq/TubeMQSourceRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/tubemq/TubeMQSourceOperator.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/source/TubeMQSourceServiceTest.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/TubeMQExtractNode.java, inlong-sort/sort-common/src/test/java/org/apache/inlong/sort/protocol/node/extract/TubeMQExtractNodeTest.java, inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/TubeMQNodeSqlParseTest.java
- Fixes #9092
Tube supports inlong-msg format.
Tube supports inlong-msg format.
=> [INLONG-9092][Manager] Tube supports inlong-msg format

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/filecollect/ProxyMessageCache.java, inlong-agent/agent-plugins/pom.xml, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/TextFileSource.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/file/FileReaderOperator.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/MetaDataUtils.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/DateUtils.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/FileDataUtils.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/FilePathUtil.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/FileTimeComparator.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/Files.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/MatchPoint.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/NewDateUtils.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/NonRegexPatternPosition.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/PathDateExpression.java
[INLONG-9134][Agent] Add file related utils
- Fixes #9134 
Add file related utils
Add file related utils
*(example:)*
=> [INLONG-9134][Agent] Add file related utils

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/plugin/file/Task.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/file/MemoryManager.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/file/TaskManager.java, inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/AgentBaseTestsHelper.java, inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/task/MockTask.java, inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/task/TestTaskManager.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/NewDateUtils.java
[INLONG-9138][Agent] Add task manager
- Fixes #9138 
Add task manager
Add task manager
*(example:)*
=> [INLONG-9138][Agent] Add task manager

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/CronTask.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/FormatDateLogFileCollectTask.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/PathPattern.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/AgentErrMsg.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/FileScanner.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/LogFileCollectTask.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/TaskType.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/WatchEntity.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/AgentBaseTestsHelper.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/MockInstanceManager.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/TestLogfileCollectTask.java, inlong-agent/agent-plugins/src/test/resources/test/20230928.log_1, inlong-agent/agent-plugins/src/test/resources/test/20230928_1.txt
[INLONG-9143][Agent] Add log file collect task
- Fixes #9143 
Add log file collect task
Add log file collect task
*(example:)*
=> [INLONG-9143][Agent] Add log file collect task

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/AgentErrMsg.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/FileScanner.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/WatchEntity.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/NewDateUtils.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/AgentBaseTestsHelper.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/filecollect/TestSenderManager.java
[INLONG-9149][Agent] Add sender manager for file collect
- Fixes #9149 
Add sender manager for file collect
Add sender manager for file collect
*(example:)*
=> [INLONG-9149][Agent] Add sender manager for file collect

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/plugin/file/Sink.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/AbstractSink.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/ProxySink.java
[INLONG-9155][Agent] Add file used proxy
- Fixes #9155 
Add file used proxy
Add file used proxy
*(example:)*
=> [INLONG-9155][Agent] Add file used proxy

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/FileInstance.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/ProxySink.java
[INLONG-9159][Agent] Add file instance
- Fixes #9159 
Add file instance
Add file instance
*(example:)*
=> [INLONG-9159][Agent] Add file instance

inlong-distribution/src/main/assemblies/sort-connectors-v1.15.xml, inlong-sort/sort-core/pom.xml, inlong-sort/sort-flink/sort-flink-v1.15/pom.xml, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/hudi/pom.xml, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/hudi/src/main/java/org/apache/inlong/sort/hudi/table/sink/HudiTableInlongFactory.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/hudi/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pom.xml, licenses/inlong-sort-connectors/notices/NOTICE-hudi-flink1.15-bundle.txt
- Fixes #8994
Add hudi connector on flink 1.15
Add hudi connector on flink 1.15
Tested on flink1.15 with pulsar -> hudi pipeline
=> [INLONG-8994][Sort] Add Hudi connector on Flink 1.15

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/README.md
- Fixes #9184 
Update README.md in Golang SDK
Update README.md in Golang SDK
*(example:)*
=> [INLONG-9184][SDK] Update README.md in Golang SDK

inlong-dashboard/src/ui/components/Layout/NavWidget/HintSelect.tsx, inlong-dashboard/src/ui/components/Layout/index.tsx, inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json
- Fixes https://github.com/apache/inlong/issues/9196
=> [INLONG-9196][Dashboard] Navigation widget user manual optimization

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/InstanceProfile.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/TaskProfile.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/InstanceDb.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/TaskProfileDb.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/file/MemoryManager.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/file/TaskManager.java, inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/instance/TestInstanceManager.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/ProxySink.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/LogFileCollectTask.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/filecollect/TestSenderManager.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestLogFileSource.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestMqttConnect.java
[INLONG-9200][Agent] Fix bug: duplicate file collect instance
- Fixes #9200 
Fix bug: duplicate file collect instance
Fix bug: duplicate file collect instance
*(example:)*
=> [INLONG-9200][Agent] Fix bug: duplicate file collect instance

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditOperator.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/PulsarExtractNode.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/IcebergLoadNode.java, inlong-sort/sort-core/pom.xml, inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/Constants.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/pom.xml, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableDeserializationSchema.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/table/PulsarTableDeserializationSchemaFactory.java, inlong-sort/sort-formats/format-inlongmsg-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgDecodingFormat.java, inlong-sort/sort-formats/format-inlongmsg-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgUtils.java
- Fixes #9202
Fix audit report error when running pulsar -> iceberg in flink1.15
Fix audit report error when running pulsar -> iceberg in flink1.15
1、add serialization on audit 
2、make iceberg appear in sort-dist
3、add metadata on pulsar and iceberg
=> [INLONG-9202][Sort] Fix audit report error when running pulsar -> iceberg in flink1.15

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/LogFileCollectTask.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/task/TestLogfileCollectTask.java, inlong-agent/agent-plugins/src/test/resources/testScan/20230928_1/test_1.txt, inlong-agent/agent-plugins/src/test/resources/testScan/temp.txt
[INLONG-9207][Agent] Fix bug: task manager stuck
- Fixes #9207 
Fix bug: task manager stuck
Fix bug: task manager stuck
*(example:)*
=> [INLONG-9207][Agent] Fix bug: task manager stuck

inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/DataConfig.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/BaseInlongStream.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamExtParam.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
- Fixes #9209 
Support configuring predefined fields and issuing agents.
Support configuring predefined fields and issuing agents.
=> [INLONG-9209][Manager] Support configuring predefined fields and issuing agents

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/InstanceProfile.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/MetaDataUtils.java
[INLONG-9215][Agent] Add predefine fields
- Fixes #9215 
Add predefine fields
Add predefine fields
*(example:)*
=> [INLONG-9215][Agent] Add predefine fields

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/sdk_conf.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/send_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/send_manager.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/capi_constant.h
- Fixes #9213
*Supports resource isolation for different inlong groupids*
*Support creating resources based on clusterid by configuration in the configuration file.*
=> [INLONG-9213][SDK] Support isolation by inlong groupid

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/sdk_conf.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/client/stat.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/client/tcp_client.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/client/tcp_client.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/proxy_info.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/send_group.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/send_group.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/capi_constant.h
- Fixes #9228
*When the server cluster is very large, it is impossible for the SDK to be fully connected, so dynamic load balancing needs to be used for load balancing.*
*Dynamic load balancing based on server load.*
=> [INLONG-9228][SDK] CPP SDK supports dynamic load balancing

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/utils/SinkMetadataUtils.java
- Fixes #9231 
*(example:)*
- If a …
=> [INLONG-9231][Sort] Find no audit time field when the field is in upper case

inlong-dashboard/src/ui/pages/GroupDetail/Delay/index.tsx
- Fixes https://github.com/apache/inlong/issues/9229
=> [INLONG-9229][Dashboard] Data access transmission delay optimization

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/LogFileCollectTask.java
[INLONG-9244][Agent] Fix bug: miss file from next data time
- Fixes #9244 
Fix bug: miss file from next data time
Fix bug: miss file from next data time
*(example:)*
=> [INLONG-9244][Agent] Fix bug: miss file from next data time

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/file/TaskManager.java, inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/instance/TestInstanceManager.java
[INLONG-9241][Agent] Print task and instance detail every ten seconds
- Fixes #9241 
Print task and instance detail every ten seconds
Print task and instance detail every ten seconds
*(example:)*
=> [INLONG-9241][Agent] Print task and instance detail every ten seconds

inlong-dashboard/src/ui/components/FieldList/DetailModal.tsx, inlong-dashboard/src/ui/pages/SynchronizeDetail/SyncTransform/DetailModal.tsx
=> [INLONG-9260][Dashboard] Enable batch import in Synchronize dashboard and detail page

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java
[INLONG-9265][Agent] Add audit of agent send success
- Fixes #9265 
Add audit of agent send success
Add audit of agent send success
*(example:)*
=> [INLONG-9265][Agent] Add audit of agent send success

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/ExtractNode.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/TubeMQExtractNode.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/pom.xml, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/DynamicTubeMQDeserializationSchema.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/DynamicTubeMQTableDeserializationSchema.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQDynamicTableFactory.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/table/TubeMQTableSource.java
- Fixes #9247 
*(example:)*
- If a …
=> [INLONG-9247][Sort] TubeMQ source support audit when the deserialized type is not InlongMsg

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/sdk_conf.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.cc
- Fixes #9277
*CPP SDK supports dynamic load balancing*
*Get the nearest dataproxy by passing the local IP to the manager*
=> [INLONG-9277][SDK] CPP SDK supports dynamic load balancing

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/pom.xml
- Fixes #9281 
Fix pulsar flink connector cannot support batch messages
Fix pulsar flink connector cannot support batch messages
This bug is fix in 3.0.1-1.16 flink pulsar connector 
=> [INLONG-9281][Sort] Fix pulsar flink connector cannot support batch messages

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/cls/ClsSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/es/ElasticsearchSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/es/ElasticsearchSinkRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamExtParam.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/cls/ClsSinkOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/es/ElasticsearchSinkOperator.java
- Fixes #9280 
*(example:)*
- If a …
=> [INLONG-9280][Manager] Support different size of extended fields of InlongStream

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/FileInstance.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/ProxySink.java
[INLONG-9289][Agent] Improve the completion judgment logic of collecting instances
- Fixes #9289 
Improve the completion judgment logic of collecting instances
Improve the completion judgment logic of collecting instances
*(example:)*
=> [INLONG-9289][Agent] Improve the completion judgment logic of collecting instances

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/CMakeLists.txt, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/api_code.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/sdk_msg.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/api_imp.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/recv_group.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/recv_group.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/send_group.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/recv_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/recv_manager.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/send_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/send_buffer.h
- Fixes #9293 
*Optimize the problem that the more inlong grouids there are, the more memory is consumed.*
*Optimize the problem that the more inlong grouids there are, the more memory is consumed.*
=> [INLONG-9293][SDK] Optimize the problem that the more inlong grouids there are, the more memory is consumed.

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/FileTask.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/AgentBaseTestsHelper.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestLogFileSource.java
[INLONG-9312][Agent] Add data content style
- Fixes #9312 
Add data content style
Add data content style
*(example:)*
=> [INLONG-9312][Agent] Add data content style

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/sdk_conf.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/api_imp.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/capi_constant.h
- Fixes #9320
*Support local disaster recovery manager configuration*
*Support local disaster recovery manager configuration.*
=> [INLONG-9320][SDK] Support local disaster recovery manager configuration

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/audit/AuditSourceRequest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/AuditController.java
- Fixes #9328 
Enhanced validation of request parameters.
Add parameters validation for the updateAuditSource method
=> [INLONG-9328][Manager] Add parameters validation for the updateAuditSource method

inlong-sort/sort-common/pom.xml, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/DorisConstant.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/IcebergLoadNode.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/util/SchemaChangeUtils.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/iceberg/src/main/java/org/apache/inlong/sort/iceberg/sink/multiple/DynamicSchemaHandleOperator.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/cdc/mysql/source/config/MySqlSourceOptions.java
- Fixes #9299
Iceberg support all migrate and auto create table 
Fix bugs of iceberg load including NPE problems 
Fix bugs of iceberg load including NPE problems
=> [INLONG-9299][Sort] Iceberg support all migrate and auto create table

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/sdk_conf.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/api_imp.cc
- Fixes #9341 
*Optimize obtaining local IP information*
*Optimize obtaining local IP information.*
=> [INLONG-9341][SDK] Optimize obtaining local IP information

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSource.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
- Fixes #9343 
Support configuring timeZone related parameters for fileSource.
Support configuring timeZone related parameters for fileSource.
=> [INLONG-9343][Manager] Support configuring timeZone related parameters for fileSource

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/util/JdbcSensitiveUrlUtils.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/starrocks/StarRocksDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/util/MySQLSensitiveUrlUtils.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/starrocks/StarRocksDataNodeOperator.java
- Fixes #9330 
Add a check to the URL encoding of mysql JDBC URL.
Add a check to the URL encoding of mysql JDBC URL.
=> [INLONG-9330][Manager] Add encoding check to the StarRocks JDBC URL

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/demo/send_demo.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/release/inc/sdk_conf.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/recv_group.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/recv_group.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/send_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/send_manager.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/capi_constant.h
- Fixes #9355
*Optimize resource isolation for CPP SDK*
*Optimize resource isolation for CPP SDK.*
=> [INLONG-9355][SDK] Optimize resource isolation for CPP SDK

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/DateTransUtils.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/file/TaskManager.java, inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/instance/TestInstanceManager.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/FileScanner.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/LogFileCollectTask.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/file/NewDateUtils.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/utils/TestUtils.java, inlong-common/src/main/java/org/apache/inlong/common/enums/TaskStateEnum.java
[INLONG-9364][Agent] Remove expired instance from db
- Fixes #9364 
Remove expired instance from db
Remove expired instance from db
*(example:)*
=> [INLONG-9364][Agent] Remove expired instance from db

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/iceberg/IcebergSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/iceberg/IcebergSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/iceberg/IcebergSinkRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/NodeFactory.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/base/ExtractNodeProvider.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/base/LoadNodeProvider.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/IcebergProvider.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamBriefInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamExtParam.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamRequest.java, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.10.0.sql
- Fixes #9362
Iceberg support  config all migrate.
Iceberg support  config all migrate
=> [INLONG-9362][Manager] Iceberg support  config all migrate

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/elasticsearch-6/pom.xml, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/elasticsearch-7/pom.xml
=> [INLONG-9371][Sort] elasticsearch sort shade relocation error

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/SinkType.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/operationlog/OperationLogRecorder.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java
- Fixes #9373 
Fix the issue of failed creation of pulsar namespace.
Fix the issue of failed creation of pulsar namespace.
=> [INLONG-9373][Manager] Fix the issue of failed creation of pulsar namespace

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/capi_constant.h
- Fixes #9378
*Optimize proxy configuration update*
*Optimize proxy configuration update.*
=> [INLONG-9378][SDK] Optimize proxy configuration update

inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/TaskSnapshotRequest.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/SinkType.java
- Fixes #9400
Fix the problem of rrror obtaining sort task type.
Fix the problem of rrror obtaining sort task type.
=> [INLONG-9400][Manager] Fix the problem of error obtaining sort task type

inlong-dashboard/src/ui/pages/GroupDetail/ResourceInfo/index.tsx
- Fixes https://github.com/apache/inlong/issues/9383
=> [INLONG-9383][Dashboard] Resource details display cluster label information

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/constant/IcebergConstant.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/IcebergLoadNode.java
- Fixes #9377 
*(example:)*
- If a …
=> [INLONG-9377][Sort] Fix init iceberg sink failed with upsert mode

.github/workflows/ci_ut.yml, .github/workflows/ci_ut_flink15.yml, inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.13/pom.xml, inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.13/src/test/java/org/apache/inlong/sort/tests/ClickHouseITCase.java, inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.13/src/test/java/org/apache/inlong/sort/tests/KafkaE2EITCase.java, inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.13/src/test/resources/log4j2-test.properties, inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/pom.xml, inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/MongodbToStarRocksITCase.java, inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/MysqlToRocksITCase.java, inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/PostgresToStarRocksITCase.java, inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/SqlserverToStarRocksITCase.java
- Fixes #9394 
Troubleshooting integration tests not executing in sort.
=> [INLONG-9394][Sort] Incorrect use of maven plugin on integration test among sort-end-to-end-tests

.github/ISSUE_TEMPLATE/bug-report.yml
- Fixes #9405 
*(example:)*
- If a …
=> [INLONG-9405][Release] Add the 1.10.0 version option for the bug report

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/SinkMetricData.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/starrocks/src/main/java/org/apache/inlong/sort/starrocks/table/sink/table/StarRocksDynamicSinkFunctionV2.java
- Fixes #9404 
FIx StarRocks Audit lost when stop job immediately after checkpoint
Flush audit data when checkpoint 
Run pulsar -> Sr
=> [INLONG-9404][Sort] StarRocks Audit lost when stop job immediately after checkpoint

CHANGES.md
- Fixes #9406 
*(example:)*
- If a …
=> [INLONG-9406][Release] Update changes log for the 1.10.0 version

inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/GroupInfo.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/SinkInfo.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/SourceInfo.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/StreamInfo.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/TenantInfo.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/TenantRoleInfo.java, inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/pojo/UserInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/audit/AuditSourceResponse.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterNodeResponse.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterTagResponse.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/TenantClusterTagInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/InlongConsumeBriefInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/InlongConsumeInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupBriefInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/heartbeat/ComponentHeartbeatResponse.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/heartbeat/GroupHeartbeatResponse.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/heartbeat/StreamHeartbeatResponse.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/DataNodeInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/operationLog/OperationLogResponse.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/StreamSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/StreamSource.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamBriefInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/tenant/InlongTenantInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/user/InlongRoleInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/user/TenantRoleInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/user/UserInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/workflow/ApproverResponse.java
- Fixes #9423
Fix the issue of time reversal errors.
Fix the issue of time reversal errors.
=> [INLONG-9423][Manager] Fix the issue of time reversal errors

inlong-distribution/src/main/assemblies/sort-connectors-v1.15.xml
- Fixes #9417 
Add MySQL CDC connector for Flink 1.15
=> [INLONG-9417][Sort] Fix the missing MySQL CDC connector for Flink 1.15

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/SenderManager.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java, inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkFieldEntityMapper.xml, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/HttpClientExample.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/TcpClientExample.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ClientMgr.java
- Fixes #9307 
Improve DataProxy SDK code readability
The details can be found at [#9307 ](https://github.com/apache/inlong/issues/9307).
=> [INLONG-9307][SDK] Improve DataProxy SDK code readability

inlong-manager/manager-dao/src/main/resources/mappers/AuditEntityMapper.xml
- Fixes #9433
Fix the issue of NPE exception encountered while querying audit information.
Fix the issue of NPE exception encountered while querying audit information.
=> [INLONG-9433][Manager] Fix the issue of NPE exception encountered while querying audit information

inlong-manager/manager-dao/src/main/resources/mappers/AuditEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/audit/AuditBaseResponse.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/audit/AuditRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/audit/AuditVO.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/AuditService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/AuditController.java
- Fixes #9435
Support querying audit data by audit ID and obtaining audit ID information.
Support querying audit data by audit ID and obtaining audit ID information.
=> [INLONG-9435][Manager] Support querying audit data by audit ID and obtaining audit ID information

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/AuditEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/AuditEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/audit/AuditRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
- Fixes #9440
Support querying audit information based on ip.
Support querying audit information based on ip.
=> [INLONG-9440][Manager] Support querying audit information based on ip

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/MySQLBinlogProvider.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/mysql/MySQLBinlogSource.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/mysql/MySQLBinlogSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/mysql/MySQLBinlogSourceRequest.java
- Fixes #9441 
MySQL data source supports both full and incremental modes.
MySQL data source supports both full and incremental modes.
=> [INLONG-9441][Manager] MySQL data source supports both full and incremental modes

inlong-distribution/pom.xml
- Fixes #9450 
*(example:)*
- If a …
=> [INLONG-9450][Build] Deploying the distribution packages to repositories

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/FileInstance.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/LogFileCollectTask.java
[INLONG-9454][Agent] Increase exit conditions to prevent dead loops
- Fixes #9454 
Increase exit conditions to prevent dead loops
Increase exit conditions to prevent dead loops
*(example:)*
=> [INLONG-9454][Agent] Increase exit conditions to prevent dead loops

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/TaskProfile.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/file/TaskManager.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/FileInstance.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/LogFileCollectTask.java, inlong-manager/manager-web/sql/changes-1.10.0.sql
[INLONG-9457][Agent] Add task and instance heartbeat audit
- Fixes #9457 
Add task and instance heartbeat audit
Add task and instance heartbeat audit
*(example:)*
=> [INLONG-9457][Agent] Add task and instance heartbeat audit

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/plugin/Instance.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java, inlong-agent/agent-core/src/test/java/org/apache/inlong/agent/core/instance/MockInstance.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/FileInstance.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/filecollect/LogFileCollectTask.java
[INLONG-9467][Agent] Improve code exception detection to ensure task and instance state transitions
- Fixes #9467 
Improve code exception detection to ensure task and instance state transitions
Improve code exception detection to ensure task and instance state transitions
*(example:)* …
=> [INLONG-9467][Agent] improve code exception detection to ensure task and instance state transitions

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/util/HttpUtils.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/pulsar/PulsarClusterInfo.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarUtils.java
- Fixes #9470
Fix the problem of failed to verify if the namespace exists.
Fix the problem of failed to verify if the namespace exists.
=> [INLONG-9470][Manager] Fix the problem of failed to verify if the namespace exists

inlong-agent/agent-plugins/pom.xml, inlong-sort/sort-flink/sort-flink-v1.13/pom.xml, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/pom.xml, pom.xml
- Fixes #9479
Remove the useless flink version
=> [INLONG-9479][Sort] Remove the useless flink version

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/DataNodeRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/AbstractStandaloneSinkResourceOperator.java
- Fixes #9484 
*(example:)*
- If a …
=> [INLONG-9484][Manager] Improve logic of sortstandalone sink auto-assign cluster

inlong-dashboard/src/ui/pages/SynchronizeDetail/SyncTransform/index.tsx
- Fixes https://github.com/apache/inlong/issues/9489
=> [INLONG-9489][Dashboard] Transform remove missing stream id

inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceTest.java, inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/function/RoundTimestampFunction.java, inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/FlinkSqlParser.java, inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/NativeFlinkSqlParser.java, inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/function/JsonGetterFunctionTest.java, inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/function/RoundTimestampFunctionTest.java
- Fixes #9476 
Add custom function for data time transform
Add custom function for data time transform
Round timestamp and output formatted timestamp.
For example, if the input timestamp is 1702610371(s), the roundTime is 600(s), and the format is "yyyyMMddHHmm", the formatted timestamp is "2023121510".
Run RoundTimestampFunctionTest
=> [INLONG-9476][Sort] Add custom function for data time transform

inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/parser/impl/NativeFlinkSqlParser.java
=> [INLONG-9493][Sort] Fixed incorrect logging classs name

inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/binlog/BinlogSourceOperator.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/core/impl/AgentServiceTest.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/source/StreamSourceServiceTest.java
- Fixes #9475
Support setting dataNode when configuring streamSource for MYSQL.
Support setting dataNode when configuring streamSource for MYSQL.
=> [INLONG-9475][Manager] Support setting dataNode when configuring streamSource for MYSQL

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/internal/FlinkPulsarSource.java, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/internal/FlinkPulsarSourceWithoutAdmin.java
- Fixes #9499 
fix typos in FlinkPulsarSource and FlinkPulsarSourceWithoutAdmin
fix typos in FlinkPulsarSource and FlinkPulsarSourceWithoutAdmin
not needed
=> [INLONG-9499][Sort] Fix typos in PulsarSource

inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/function/EncryptFunction.java, inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/function/EncryptFunctionTest.java
[INLONG-9501][Sort] Modify EncryptFunction
- Fixes #9501 
Correcting erroneous logic.
=> [INLONG-9501][Sort] Modify EncryptFunction

inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/source/StreamSourceServiceTest.java
- Fixes #9503
Unified Hashmap Dependency Package.
Unified Hashmap Dependency Package.
=> [INLONG-9503][Manager] Unified Hashmap Dependency Package

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/DataNodeType.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/doris/DorisDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/doris/DorisDataNodeInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/doris/DorisDataNodeRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/DorisProvider.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/doris/DorisDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/doris/DorisSinkOperator.java
- Fixes #9510
Supports doris database synchronization.
Supports doris database synchronization.
=> [INLONG-9510][Manager] Supports doris database synchronization

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/tubemq/TubeMQQueueResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/tubemq/TubeMQSourceOperator.java
- Fixes #9513
Fix the problem of the tube consumption group sent to the sort side is incorrect.
The current consumption group passed to the sort side is streamid, but there is no consumption group generated by the manager.
Therefore, it is necessary to distribute the consumption group generated by the manager to the sort side.
=> [INLONG-9513][Manager] Fix the problem of the tube consumption group sent to the sort side is incorrect

inlong-dashboard/src/plugins/sources/common/SourceDefaultInfo.ts, inlong-dashboard/src/plugins/sources/defaults/File.ts, inlong-dashboard/src/plugins/sources/defaults/Hudi.ts, inlong-dashboard/src/plugins/sources/defaults/Iceberg.ts, inlong-dashboard/src/plugins/sources/defaults/MQTT.ts, inlong-dashboard/src/plugins/sources/defaults/Mongodb.ts, inlong-dashboard/src/plugins/sources/defaults/MySQLBinlog.ts, inlong-dashboard/src/plugins/sources/defaults/Oracle.ts, inlong-dashboard/src/plugins/sources/defaults/PostgreSQL.ts, inlong-dashboard/src/plugins/sources/defaults/Pulsar.ts, inlong-dashboard/src/plugins/sources/defaults/Redis.ts, inlong-dashboard/src/plugins/sources/defaults/SQLServer.ts, inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json, inlong-dashboard/src/ui/pages/SynchronizeDetail/SyncAudit/index.tsx, inlong-dashboard/src/ui/pages/SynchronizeDetail/SyncSources/DetailModal.tsx
- Fixes https://github.com/apache/inlong/issues/9505
before:
after:
data synchronize audit table title optimization:
=> [INLONG-9505][Dashboard] Pulsar source parameter optimization

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/binlog/BinlogSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/iceberg/IcebergSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/postgresql/PostgreSQLSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/pulsar/PulsarSourceOperator.java
- Fixes #9533
Support setting dataNode when configuring streamSource for Pulsar、Iceberg、PostgreSQL.
Support setting dataNode when configuring streamSource for Pulsar、Iceberg、PostgreSQL.
=> [INLONG-9533][Manager] Support setting dataNode when configuring streamSource for Pulsar, Iceberg and PostgreSQL

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/dataproxy/DataProxyClusterNodeDTO.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/DataProxyClusterNodeOperator.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceTest.java
- Fixes #9538
Fix the problem of unable to retrieve parameters from ext_params when obtaining dataproxy node information.
Fix the problem of unable to retrieve parameters from ext_params when obtaining dataproxy node information.
=> [INLONG-9538][Manager] Fix the problem of unable to retrieve parameters from ext_params when obtaining dataproxy node information

inlong-sort/sort-dist/pom.xml, inlong-sort/sort-formats/format-inlongmsg-kv/pom.xml, inlong-sort/sort-formats/format-inlongmsg-kv/src/main/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKv.java, inlong-sort/sort-formats/format-inlongmsg-kv/src/main/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvFormatDeserializer.java, inlong-sort/sort-formats/format-inlongmsg-kv/src/main/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvFormatFactory.java, inlong-sort/sort-formats/format-inlongmsg-kv/src/main/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvMixedFormatConverter.java, inlong-sort/sort-formats/format-inlongmsg-kv/src/main/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvMixedFormatDeserializer.java, inlong-sort/sort-formats/format-inlongmsg-kv/src/main/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvUtils.java, inlong-sort/sort-formats/format-inlongmsg-kv/src/main/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvValidator.java, inlong-sort/sort-formats/format-inlongmsg-kv/src/main/resources/META-INF/services/org.apache.flink.table.factories.TableFactory, inlong-sort/sort-formats/format-inlongmsg-kv/src/test/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvFormatDeserializerTest.java, inlong-sort/sort-formats/format-inlongmsg-kv/src/test/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvFormatFactoryTest.java, inlong-sort/sort-formats/format-inlongmsg-kv/src/test/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvTest.java, inlong-sort/sort-formats/pom.xml
- Fixes #9521
*Sort format supports InLongMsg-kv format
*Sort format supports InLongMsg-kv format
=> [INLONG-9521][Sort] Sort format supports InLongMsg-kv format

inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json, inlong-dashboard/src/ui/pages/Clusters/NodeEditModal.tsx, inlong-dashboard/src/ui/pages/Clusters/NodeManage.tsx
- Fixes https://github.com/apache/inlong/issues/9530
=> [INLONG-9530][Dashboard] Dataproxy cluster nodes support adding the enabledOnline parameter

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ConfigConstants.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ServiceDiscoveryUtils.java
- Fixes #9546 
DataProxy SDK support request manager by https
The details can be found at [#9546 ](https://github.com/apache/inlong/issues/9546).
=> [INLONG-9546][SDK] DataProxy SDK support request manager by https

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongClusterClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongGroupClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongTenantClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongClusterApi.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongGroupApi.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongTenantApi.java
- Fixes #9524 
Manager client support migrate group tenant, switch cluster tag, list cluster tag by tenant
The details can be found at [#9524 ](https://github.com/apache/inlong/issues/9524).
=> [INLONG-9524][Manager] Manager client support migrate group tenant, switch cluster tag 

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java
- Fixes #9554 
Fix the shutdownInternalThreads methods throw the NullPointerException
The details can be found at [#9554 ](https://github.com/apache/inlong/issues/9554).
=> [INLONG-9554][SDK] Fix the shutdownInternalThreads methods throw the NullPointerException

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterNodeRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/AgentClusterNodeInstallOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/InlongClusterNodeInstallOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/InlongClusterNodeInstallOperatorFactory.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/doris/DorisDataNodeOperator.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java
- Fixes #9586
Provide installation agent framework.
Provide installation agent framework.
=> [INLONG-9586][Manager] Provide installation agent framework

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/AbstractSink.java
[INLONG-9598][Agent] Modify comments
- Fixes #9598
Modify comments
Modify comments
*(example:)*
=> [INLONG-9598][Agent] Modify comments

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/cls/ClsDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/cls/ClsOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/cls/ClsResourceOperator.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java
- Fixes #9606
Fix the problem of incorrect flow status when cls sink configuration fails.
Fix the problem of incorrect flow status when cls sink configuration fails.
=> [INLONG-9606][Manager] Fix the problem of incorrect flow status when cls sink configuration fails

inlong-dashboard/src/plugins/clusters/common/ClusterDefaultInfo.ts, inlong-dashboard/src/plugins/sources/defaults/Pulsar.ts, inlong-dashboard/src/ui/pages/Clusters/CreateModal.tsx, inlong-dashboard/src/ui/pages/GroupDetail/Audit/index.tsx
- Fixes https://github.com/apache/inlong/issues/9610
pulsar source parameter order adjustment：
=> [INLONG-9610][Dashboard] Cluster creation type optimization

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarProducerCluster.java
- Fixes #9616 
*(example:)*
- If a …
=> [INLONG-9616][Sort] Fix failed to create pulsar producer with the same topic

inlong-sort/sort-formats/format-rowdata/format-rowdata-csv/pom.xml, inlong-sort/sort-formats/format-rowdata/format-rowdata-csv/src/main/java/org/apache/inlong/sort/formats/csv/CsvFormatFactory.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-csv/src/main/java/org/apache/inlong/sort/formats/csv/CsvRowDataDeserializationSchema.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-csv/src/main/java/org/apache/inlong/sort/formats/csv/CsvRowDataSerializationSchema.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-csv/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, inlong-sort/sort-formats/format-rowdata/format-rowdata-csv/src/test/java/org/apache/inlong/sort/formats/csv/CsvFormatFactoryTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-csv/src/test/java/org/apache/inlong/sort/formats/csv/CsvRowDataDeserializationSchemaTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-csv/src/test/java/org/apache/inlong/sort/formats/csv/CsvRowDataSerializationSchemaTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-csv/src/test/resources/log4j-test.properties
Support rowdata way of sort message CSV format
- Fixes #9562
=> [INLONG-9562][Sort] Support rowdata way of sort message CSV format

inlong-sort/sort-formats/format-row/format-inlongmsg-tlogkv/pom.xml, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogkv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKv.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogkv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvFormatDeserializer.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogkv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvFormatFactory.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogkv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvMixedFormatConverter.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogkv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvMixedFormatDeserializer.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogkv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvUtils.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogkv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvValidator.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogkv/src/main/resources/META-INF/services/org.apache.flink.table.factories.TableFactory, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogkv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvFormatDeserializerTest.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogkv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvFormatFactoryTest.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogkv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvTest.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogkv/src/test/resources/log4j-test.properties, inlong-sort/sort-formats/format-row/pom.xml
Support row way of sort InLong message tlog-kv format
- Fixes #9596
=> [INLONG-9596][Sort] Support row way of sort InLong message tlog-kv format

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/CsvDeserializationInfo.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/DeserializationInfo.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/InLongMsgCsv2DeserializationInfo.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/InLongMsgCsvDeserializationInfo.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/InLongMsgKvDeserializationInfo.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/InLongMsgTlogCsvDeserializationInfo.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/InLongMsgTlogKvDeserializationInfo.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/KvDeserializationInfo.java, inlong-sort/sort-formats/format-row/format-csv/src/main/java/org/apache/inlong/sort/formats/csv/Csv.java, inlong-sort/sort-formats/format-row/format-csv/src/test/java/org/apache/inlong/sort/formats/csv/CsvTest.java, inlong-sort/sort-formats/format-row/format-inlongmsg-binlog/src/main/java/org/apache/inlong/sort/formats/inlongmsgbinlog/InLongMsgBinlog.java, inlong-sort/sort-formats/format-row/format-inlongmsg-binlog/src/test/java/org/apache/inlong/sort/formats/inlongmsgbinlog/InLongMsgBinlogTest.java, inlong-sort/sort-formats/format-row/format-inlongmsg-csv/src/main/java/org/apache/inlong/sort/formats/inlongmsgcsv/InLongMsgCsv.java, inlong-sort/sort-formats/format-row/format-inlongmsg-csv/src/test/java/org/apache/inlong/sort/formats/inlongmsgcsv/InLongMsgCsvTest.java, inlong-sort/sort-formats/format-row/format-inlongmsg-kv/src/main/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKv.java, inlong-sort/sort-formats/format-row/format-inlongmsg-kv/src/main/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvMixedFormatConverter.java, inlong-sort/sort-formats/format-row/format-inlongmsg-kv/src/test/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvTest.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-binlog/src/main/java/org/apache/inlong/sort/formats/inlongmsgbinlog/InLongMsgBinlogFormatFactory.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-binlog/src/main/java/org/apache/inlong/sort/formats/inlongmsgbinlog/InLongMsgBinlogRowDataDeserializationSchema.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-binlog/src/test/java/org/apache/inlong/sort/formats/inlongmsgbinlog/InLongMsgBinlogFormatFactoryTest.java
Update all deserializationInfo in sort-common module
- Fixes #9622
=> [INLONG-9622][Sort] Update all deserializationInfo in sort-common module

inlong-sort/sort-formats/format-row/format-inlongmsg-tlogcsv/pom.xml, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogcsv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsv.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogcsv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvFormatDeserializer.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogcsv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvFormatFactory.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogcsv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvMixedFormatConverter.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogcsv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvMixedFormatDeserializer.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogcsv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvUtils.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogcsv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvValidator.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogcsv/src/main/resources/META-INF/services/org.apache.flink.table.factories.TableFactory, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogcsv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvFormatDeserializerTest.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogcsv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvFormatFactoryTest.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogcsv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvTest.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogcsv/src/test/resources/log4j-test.properties, inlong-sort/sort-formats/format-row/pom.xml
Support row way of sort InLong message tlog-csv format
- Fixes #9597
=> [INLONG-9597][Sort] Support row way of sort InLong message tlog-csv format

inlong-dashboard/src/ui/pages/GroupDetail/Audit/config.tsx, inlong-dashboard/src/ui/pages/GroupDetail/Delay/config.tsx, inlong-dashboard/src/ui/pages/SynchronizeDetail/SyncAudit/config.tsx
- Fixes https://github.com/apache/inlong/issues/9627
=> [INLONG-9627][Dashboard]  Audit and transmission delay filtering query optimization

inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/SinkInfo.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/AbstractStandaloneSinkResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/cls/ClsResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/es/ElasticsearchResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/pulsar/PulsarResourceOperator.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSinkContext.java
- Fixes #9634 
*(example:)*
- If a …
=> [INLONG-9634][Manager] Auto assign sort task and consumer group of standalone

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/standalone/SortSourceClusterInfo.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
- Fixes #9222 
*(example:)*
- If a …
=> [INLONG-9222][Manager] SortStandalone configuration support multiple tags

inlong-dashboard/package-lock.json, inlong-dashboard/package.json, inlong-dashboard/vite.config.ts
=> [INLONG-9516][Dashboard] Remove useless dependencies

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/hudi/pom.xml
- Fixes #9644
Unify the Guava version to fix the CVE
=> [INLONG-9644][CVE] Unify the Guava version to fix the CVE

inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/postgres-cdc/pom.xml
- Fixes #9642
Unify the postgresql version to fix the CVE
=> [INLONG-9642][CVE] Unify the postgresql version to fix the CVE

.github/ISSUE_TEMPLATE/bug-report.yml
- Fixes #9648
*(example:)*
- If a …
=> [INLONG-9648][Release] Add the 1.11.0 version option for the bug report

inlong-sort/sort-formats/format-rowdata/format-rowdata-json/pom.xml, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/main/java/org/apache/inlong/sort/formats/json/FieldToRowDataConverters.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/main/java/org/apache/inlong/sort/formats/json/JsonFormatFactory.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/main/java/org/apache/inlong/sort/formats/json/JsonFormatOptions.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/main/java/org/apache/inlong/sort/formats/json/JsonFormatUtils.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/main/java/org/apache/inlong/sort/formats/json/JsonRowDataDeserializationSchema.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/main/java/org/apache/inlong/sort/formats/json/JsonRowDataSerializationSchema.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/main/java/org/apache/inlong/sort/formats/json/JsonRowDeserializationSchema.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/main/java/org/apache/inlong/sort/formats/json/JsonRowSerializationSchema.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/main/java/org/apache/inlong/sort/formats/json/RowDataToFieldConverters.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/test/java/org/apache/inlong/sort/formats/json/FieldToRowDataConvertersTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/test/java/org/apache/inlong/sort/formats/json/JsonFormatFactoryTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/test/java/org/apache/inlong/sort/formats/json/JsonRowDataDeserializationSchemaTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/test/java/org/apache/inlong/sort/formats/json/JsonRowDataSerDeTestBase.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/test/java/org/apache/inlong/sort/formats/json/JsonRowDataSerializationSchemaTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/test/java/org/apache/inlong/sort/formats/json/JsonRowDeserializationSchemaTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/test/java/org/apache/inlong/sort/formats/json/JsonRowSerializationSchemaTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/test/java/org/apache/inlong/sort/formats/json/RowDataToFieldConvertersTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/test/resources/json_source.txt, inlong-sort/sort-formats/format-rowdata/pom.xml
Support rowdata way of sort message json format
- Fixes #9565
=> [INLONG-9565][Sort] Support rowdata way of sort message json format

CHANGES.md
- Fixes #9649 
*(example:)*
- If a …
=> [INLONG-9649][Release] Update changes log for the 1.11.0 version

inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-pb/pom.xml, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-pb/src/main/java/org/apache/inlong/sort/formats/inlongmsgpb/InLongMsgPbDecodingFormat.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-pb/src/main/java/org/apache/inlong/sort/formats/inlongmsgpb/InLongMsgPbDeserializationSchema.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-pb/src/main/java/org/apache/inlong/sort/formats/inlongmsgpb/InLongMsgPbFormatFactory.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-pb/src/main/java/org/apache/inlong/sort/formats/inlongmsgpb/InLongMsgPbOptions.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-pb/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, inlong-sort/sort-formats/format-rowdata/pom.xml
Support rowdata way of sort InLong message pb format
- Fixes #9570
=> [INLONG-9570][Sort] Support rowdata way of sort InLong message pb format

inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-pb/pom.xml, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/test/java/org/apache/inlong/sort/formats/json/RowDataToFieldConvertersTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-kv/pom.xml
- Fixes #9651 
*(example:)*
- If a …
=> [INLONG-9651][Release] Bumped sub-modules' version to 1.12.0-SNAPSHOT and fix error in unit test

inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-pb/pom.xml, inlong-sort/sort-formats/format-rowdata/format-rowdata-kv/pom.xml
- Fixes #9652 
*(example:)*
- If a …
=> [INLONG-9652][Release] Bumped submodule 1.12.0-SNAPSHOT branch version to 1.11.0

inlong-agent/agent-core/pom.xml, licenses/inlong-agent/LICENSE, licenses/inlong-manager/LICENSE, pom.xml
- Fixes #9683
Remove Akka dependency for it is not used
=> [INLONG-9683][Agent] Remove Akka dependency for it is not used

.github/workflows/ci_build.yml, .github/workflows/ci_docker.yml, .github/workflows/ci_ut.yml, .github/workflows/ci_ut_flink15.yml, .github/workflows/codeql_analysis.yml
- Fixes #9690
Clean up the build package for more space to create cache tar file.
=> [INLONG-9690][CI] Clean up more space for build

inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogcsv/pom.xml, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogcsv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvDeserializationSchema.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogcsv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvFormatDeserializer.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogcsv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvFormatFactory.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogcsv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvUtils.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogcsv/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogcsv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvFormatDeserializerTest.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogcsv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvFormatFactoryTest.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogcsv/src/test/resources/log4j-test.properties, inlong-sort/sort-formats/format-rowdata/pom.xml
- Fixes #9692
csv file content like this:
John, 30, Male
Jane, 25, Female
and use tlog-csv format, a single file contains multiple streamid csv format data file, a tlog-csv content like this:
StreamId_1| John, 30, Male
StreamId_2|Jane, 25, Female
=> [INLONG-9692][Sort] Support rowdata way of sort InLong message tlog-csv format

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/KafkaExtractNode.java, inlong-sort/sort-core/src/test/java/org/apache/inlong/sort/parser/KafkaSqlParseTest.java
- [INLONG-9695][Sort]  Fix kafka extract node option config building error when use upsert-kafka connector
- Fixes #9695 
* Fix kafka extract node option config building error when use upsert-kafka connector
* Modify kafka extract node option building
* Add UT for this case
=> [INLONG-9695][Sort]  Fix kafka extract node option config building error when use upsert-kafka connector

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/util/MySQLSensitiveUrlUtils.java
- Fixes #9706 
Supports jdbc verification under multiple hosts.
Supports jdbc verification under multiple hosts.
=> [INLONG-9706][Manager] Supports jdbc verification under multiple hosts

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
[INLONG-9700][Agent] Optimize the message ack logic to reduce semaphore competition
- Fixes #9700 
Optimize the message ack logic to reduce semaphore competition
Optimize the message ack logic to reduce semaphore competition
*(example:)*
=> [INLONG-9700][Agent] Optimize the message ack logic to reduce semaphore competition

inlong-dashboard/src/ui/pages/ModuleAudit/IdModule/index.tsx, inlong-dashboard/src/ui/pages/ModuleAudit/IpModule/index.tsx
- Fixes https://github.com/apache/inlong/issues/9708
=> [INLONG-9708][Dashboard] Module audit query date optimization

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/FileInstance.java
[INLONG-9710][Agent] Improve the accuracy of instance heartbeat auditing
- Fixes #9710 
Improve the accuracy of instance heartbeat auditing
Improve the accuracy of instance heartbeat auditing
*(example:)*
=> [INLONG-9710][Agent] Improve the accuracy of instance heartbeat auditing

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FilterFunctionUtils.java
- Fixes #9718
Transform supports function type fields.
Transform supports function type fields.
=> [INLONG-9718][Manager] Transform supports function type fields

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/db/TaskProfileDb.java
[INLONG-9716][Agent] Delete useless code when storing tasks
- Fixes #9716
Delete useless code when storing tasks
Delete useless code when storing tasks
*(example:)*
=> [INLONG-9716][Agent] Delete useless code when storing tasks

licenses/inlong-agent/LICENSE, licenses/inlong-audit/LICENSE, licenses/inlong-manager/LICENSE, licenses/inlong-sort-connectors/LICENSE, licenses/inlong-tubemq-manager/LICENSE, pom.xml
- Fixes #9714 
Upgrade org.postgresql:postgresql to 42.4.4 since 42.4.3 has SQL injection problem
- postgresql.version in pom.xml
- postgresql version in license files
=> [INLONG-9714][Agent] Fix SQL injection in pgjdbc

inlong-dashboard/src/plugins/sinks/common/sourceFields.ts, inlong-dashboard/src/plugins/streams/common/StreamDefaultInfo.ts, inlong-dashboard/src/ui/components/HighSelect/index.tsx, inlong-dashboard/src/ui/pages/GroupDetail/Audit/config.tsx, inlong-dashboard/src/ui/pages/ModuleAudit/IdModule/config.tsx, inlong-dashboard/src/ui/pages/ModuleAudit/IpModule/config.tsx
- Fixes https://github.com/apache/inlong/issues/9723
Source field names support starting with an underscore.
=> [INLONG-9723][Dashboard] Module audit id query item optimization

inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/DataConfig.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/StreamSourceEntity.java, inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/SourceRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/StreamSource.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.12.0.sql
- Fixes #9727 
Support configuring the timezone for agent collection addresses to streamSource.
Support configuring the timezone for agent collection addresses to streamSource.
=> [INLONG-9727][Manager] Support configuring the timezone for agent collection addresses to streamSource

inlong-dashboard/src/plugins/sinks/defaults/ClickHouse.ts, inlong-dashboard/src/plugins/sinks/defaults/Cls.ts, inlong-dashboard/src/plugins/sinks/defaults/Doris.ts, inlong-dashboard/src/plugins/sinks/defaults/Elasticsearch.ts, inlong-dashboard/src/plugins/sinks/defaults/Greenplum.ts, inlong-dashboard/src/plugins/sinks/defaults/HBase.ts, inlong-dashboard/src/plugins/sinks/defaults/Hive.ts, inlong-dashboard/src/plugins/sinks/defaults/MySQL.ts, inlong-dashboard/src/plugins/sinks/defaults/Oracle.ts, inlong-dashboard/src/plugins/sinks/defaults/PostgreSQL.ts, inlong-dashboard/src/plugins/sinks/defaults/Redis.ts, inlong-dashboard/src/plugins/sinks/defaults/SQLServer.ts, inlong-dashboard/src/plugins/sinks/defaults/StarRocks.ts, inlong-dashboard/src/plugins/sinks/defaults/TDSQLPostgreSQL.ts, inlong-dashboard/src/plugins/sources/defaults/File.ts, inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json
- Fixes https://github.com/apache/inlong/issues/9729
sink before:
sink after:
file source remove data content style, and timeZone-->dataTimeZone
=> [INLONG-9729][Dashboard]  Data access sink field mapping supports underscores

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
- Fixes #9733
Support querying audit data at the minute level.
Support querying audit data at the minute level.
=> [INLONG-9733][Manager] Support querying audit data at the minute level

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongTenantClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongTenantRoleClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongTenantApi.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongTenantRoleApi.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongTenantController.java
- Fixes #9696  
Manager client support delete inlong tenant
The details can be found at [#9696 ](https://github.com/apache/inlong/issues/9696).
=> [INLONG-9696][Manager] Manager client support delete inlong tenant and role

inlong-sort/sort-formats/format-common/pom.xml, inlong-sort/sort-formats/format-row/format-inlongmsg-binlog/pom.xml, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-binlog/pom.xml
=> [INLONG-9715][Sort] Update protobuf-java version in sort module

inlong-distribution/pom.xml, inlong-distribution/script/backup_module_dependencies.sh
- Fixes #9725 
*(example:)*
- If a …
=> [INLONG-9725][Tools] Fix asc sign file of distribution package after merging multiple module jars

docker/docker-compose/.env
- Fixes #9742
The docker env VERSION_TAG was wrong
Modify. the docker env VERSION_TAG
repackage
=> [INLONG-9742][Docker] change the docker VERSION_TAG to 1.11.0

inlong-dashboard/src/ui/pages/ModuleAudit/IdModule/index.tsx
- Fixes https://github.com/apache/inlong/issues/9747
before:
after:
=> [INLONG-9747][Dashboard] Module audit ID query data display optimization

inlong-manager/manager-dao/src/main/resources/mappers/OperationLogEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/operationLog/OperationLogRequest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/AuditController.java
- Fixes #9752 
Operation logs support querying based on successful or unsuccessful calls.
Operation logs support querying based on successful or unsuccessful calls.
=> [INLONG-9752][Manager] Operation logs support querying based on successful or unsuccessful calls

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java
- Fixes #9762 
DataProxy SDK support configure tls version
The details can be found at [#9762 ](https://github.com/apache/inlong/issues/9762).
=> [INLONG-9762][SDK] DataProxy SDK support configure tls version

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/metrics/audit/AuditUtils.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java
[INLONG-9772][Agent] Increase auditing for sending exceptions and resending
- Fixes #9772
Increase auditing for sending exceptions and resending
Increase auditing for sending exceptions and resending
*(example:)*
=> [INLONG-9772][Agent] Increase auditing for sending exceptions and resending

inlong-dashboard/src/ui/pages/ModuleAudit/IpModule/config.tsx
- Fixes https://github.com/apache/inlong/issues/9777
=> [INLONG-9777][Dashboard] Module audit ip query display optimization

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java
- Fixes #9773 
To improve the compatibility, the tenant of InlongGroup in the inner pulsar should be acquire from both the InlongGroupInfo and InlongClusterInfo.
*(example:)*
- If yes, how is the feature documented? (not applicable / docs …
=> [INLONG-9773][Manager] SortSdk configuration support acquire tenant from InlongGroup

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/InLongMsgCsv2DeserializationInfo.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/InLongMsgCsvDeserializationInfo.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/InLongMsgDeserializationInfo.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/InLongMsgKvDeserializationInfo.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/InLongMsgTlogCsvDeserializationInfo.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/InLongMsgTlogKvDeserializationInfo.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/JsonDeserializationInfo.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/deserialization/KvDeserializationInfo.java
=> [INLONG-9783][Sort] Add compatibility processing of tid to streamId changes in the message deserialization base class

inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgUtils.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogcsv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvFormatDeserializerTest.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogkv/pom.xml, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogkv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKv.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogkv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvFormatDeserializer.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogkv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvUtils.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogkv/src/main/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvValidator.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogkv/src/main/resources/META-INF/services/org.apache.flink.table.factories.TableFactory, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogkv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvFormatDeserializerTest.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogkv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvTest.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogkv/src/test/resources/log4j-test.properties, inlong-sort/sort-formats/format-rowdata/pom.xml, inlong-sort/sort-formats/pom.xml
=> [INLONG-9774][Sort] Support rowdata way of sort InLong message tlog-kv format

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/WorkflowApproverClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/WorkflowClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/WorkflowEventClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/WorkflowApi.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/WorkflowApproverApi.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/WorkflowEventApi.java
- Fixes #9793 
Fix the problem of Manager client workflowApi.listprocess failed to pass parameters correctly.
Fix the problem of Manager client workflowApi.listprocess failed to pass parameters correctly.
=> [INLONG-9793][Manager] Fix the problem of Manager client workflowApi.listprocess failed to pass parameters correctly

inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/base/TableFormatUtils.java, inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/FailureHandler.java, inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/IgnoreFailureHandler.java, inlong-sort/sort-formats/format-common/src/main/java/org/apache/inlong/sort/formats/inlongmsg/NoOpFailureHandler.java, inlong-sort/sort-formats/format-row/format-base/src/test/java/org/apache/inlong/sort/formats/base/TableFormatUtilsTest.java, inlong-sort/sort-formats/format-row/format-csv/src/test/java/org/apache/inlong/sort/formats/csv/CsvDeserializationSchemaTest.java, inlong-sort/sort-formats/format-row/format-inlongmsg-csv/src/test/java/org/apache/inlong/sort/formats/inlongmsgcsv/InLongMsgCsvFormatDeserializerTest.java, inlong-sort/sort-formats/format-row/format-inlongmsg-kv/src/test/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvFormatDeserializerTest.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogcsv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvFormatDeserializerTest.java, inlong-sort/sort-formats/format-row/format-inlongmsg-tlogkv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvFormatDeserializerTest.java, inlong-sort/sort-formats/format-row/format-kv/src/test/java/org/apache/inlong/sort/formats/kv/KvDeserializationSchemaTest.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-csv/src/test/java/org/apache/inlong/sort/formats/inlongmsgcsv/InLongMsgCsvFormatDeserializerTest.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-kv/src/test/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvFormatDeserializerTest.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogcsv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogcsv/InLongMsgTlogCsvFormatDeserializerTest.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogkv/src/test/java/org/apache/inlong/sort/formats/inlongmsgtlogkv/InLongMsgTlogKvFormatDeserializerTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-base/src/main/java/org/apache/inlong/sort/formats/base/DefaultDeserializationSchema.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-base/src/test/java/org/apache/inlong/sort/formats/base/TableFormatUtilsTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-csv/src/main/java/org/apache/inlong/sort/formats/csv/CsvRowDataDeserializationSchema.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-csv/src/test/java/org/apache/inlong/sort/formats/csv/CsvRowDataDeserializationSchemaTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/main/java/org/apache/inlong/sort/formats/json/JsonRowDataDeserializationSchema.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/test/java/org/apache/inlong/sort/formats/json/FieldToRowDataConvertersTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/test/java/org/apache/inlong/sort/formats/json/JsonRowDataDeserializationSchemaTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/test/java/org/apache/inlong/sort/formats/json/JsonRowDataSerDeTestBase.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/test/java/org/apache/inlong/sort/formats/json/JsonRowDataSerializationSchemaTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-json/src/test/java/org/apache/inlong/sort/formats/json/RowDataToFieldConvertersTest.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-kv/src/main/java/org/apache/inlong/sort/formats/kv/KvRowDataDeserializationSchema.java, inlong-sort/sort-formats/format-rowdata/format-rowdata-kv/src/test/java/org/apache/inlong/sort/formats/kv/KvRowDataDeserializationSchemaTest.java
=> [INLONG-9791][Sort] Return null instead of throwing an exception when deserialization by type fails

inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/protocol/AuditData.java, inlong-audit/audit-common/src/main/proto/AuditApi.proto, inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/source/ServerMessageHandler.java, inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditOperator.java, inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderManager.java
- Fixes #9797 
*Audit-sdk reporting supports version number dimension to solve the problem of agent supplementary registration.*
*Audit-sdk reporting supports version number dimension for add api.*
=> [INLONG-9797][Audit] Audit-SDK reporting supports version number dimension

inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/source/ServerMessageHandler.java
- Fixes #9807
*Add debug log for audit-proxy to check whether the audit-sdk successfully reports audit data.*
*Add debug log for audit-proxy when it receive data from audit-sdk.*
=> [INLONG-9807][Audit] Add debug log for audit-proxy

inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/StartupSortListener.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/group/InitGroupCompleteListener.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/group/UpdateGroupCompleteListener.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/group/apply/ApproveApplyProcessListener.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/queue/QueueResourceListener.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/stream/InitStreamCompleteListener.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
- Fixes #9813 
Add support for offline data sync management.
Add support for offline data sync management.
No docs need.
=> [INLONG-9813][Manager] Support offline data sync management

inlong-agent/agent-installer/assembly.xml, inlong-agent/agent-installer/conf/installer.properties, inlong-agent/agent-installer/conf/log4j2.xml, inlong-agent/agent-installer/pom.xml
[INLONG-9806][Agent] Add installer configuration file
- Fixes #9806
Add installer configuration file
Add installer configuration file
*(example:)*
=> [INLONG-9806][Agent] Add installer configuration file

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java
- Fixes #9818
Decode Msg based on the manager's configuration.
Decode Msg based on the manager's configuration.
=> [INLONG-9818][Manager] Decode Msg based on the manager's configuration

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkService.java, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/flink/dto/FlinkInfo.java, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/DeleteSortListener.java, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/RestartSortListener.java, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/StartupSortListener.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/configuration/Constants.java, inlong-sort/sort-core/src/main/java/org/apache/inlong/sort/Entrance.java
- Fixes #9822 
Support flink job runtime execution mode configuration
Make the runtime execution mode of flink job configurable
- streaming execution mode for real-time data sync 
- batch execution mode for offline data sync
not need
=> [INLONG-9822][Manager] Support flink job runtime execution mode configuration

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/tubemq/TubeMQOperator.java
- Fixes #9827
Fix the problem of failed to check if the consumption group exists.
Fix the problem of failed to check if the consumption group exists.
Modify the parameter when determining the existence of a consumption group.
=> [INLONG-9827][Manager] Fix the problem of failed to check if the consumption group exists

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/FetcherConstants.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/utils/HttpManager.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java, inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/Manager.java, inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ManagerFetcher.java, inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ManagerResultFormatter.java, inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/installer/ModuleConfig.java
[INLONG-9831][Agent] Increase configuration acquisition capability
- Fixes #9831 
Increase configuration acquisition capability
Increase configuration acquisition capability
*(example:)*
=> [INLONG-9831][Agent] Increase configuration acquisition capability

inlong-dashboard/src/plugins/clusters/defaults/Pulsar.ts, inlong-dashboard/src/ui/locales/cn.json
- Fixes #9837 
Modify variable name
Modify variable name
=> [INLONG-9837][Dashboard] Fix displays errors for Pulsar cluster management

inlong-dashboard/src/ui/pages/GroupDetail/ResourceInfo/index.tsx
- Fixes https://github.com/apache/inlong/issues/9842
=> [INLONG-9842][Dashboard] Data access resource details support paging

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSinkEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/StreamSinkEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/AbstractStandaloneSinkResourceOperator.java
- Fixes #9839 
*(example:)*
- If a …
=> [INLONG-9839][Manager] Optimize the auto assign logic of SortStandalone cluster

inlong-manager/manager-dao/src/main/resources/mappers/DataNodeEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml
- Fixes #9846
Optimize slow query SQL.
Optimize slow query SQL.
=> [INLONG-9846][Manager] Optimize slow query SQL

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ManagerFetcher.java, inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/installer/ConfigRequest.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/installer/ModuleConfig.java
[INLONG-9844][Agent] Add agent installer config request class
- Fixes #9844
Add agent installer config request class
Add agent installer config request class
*(example:)*
=> [INLONG-9844][Agent] Add agent installer config request class

inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-tlogkv/pom.xml
=> [INLONG-9854][Sort] rowdata-tlogkv module artifactId is error,need change

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
- Fixes #9856
Fix the problem for missing tenant information when listTag.
Fix the problem for missing tenant information when listTag.
=> [INLONG-9856][Manager] Fix the problem for missing tenant information when listTag

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/WorkflowClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/WorkflowApi.java, inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupInfo.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/AbstractDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/mysql/MySQLDataNodeOperator.java
- Fixes #9860
Manager client supports querying workflow logs.
Manager client supports querying workflow logs.
=> [INLONG-9860][Manager] Manager client supports querying workflow logs

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarProducerCluster.java
- Fixes #9871 
*(example:)*
- If a …
=> [INLONG-9871][Sort] Use ZLIB as the default compression type of pulsar sink

inlong-sort/sort-formats/format-row/format-inlongmsg-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgUtils.java, inlong-sort/sort-formats/format-row/format-inlongmsg-binlog/src/main/java/org/apache/inlong/sort/formats/inlongmsgbinlog/InLongMsgBinlogUtils.java, inlong-sort/sort-formats/format-row/format-inlongmsg-csv/src/main/java/org/apache/inlong/sort/formats/inlongmsgcsv/InLongMsgCsvUtils.java, inlong-sort/sort-formats/format-row/format-inlongmsg-kv/src/main/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvUtils.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/InLongMsgUtils.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-binlog/src/main/java/org/apache/inlong/sort/formats/inlongmsgbinlog/InLongMsgBinlogUtils.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-csv/src/main/java/org/apache/inlong/sort/formats/inlongmsgcsv/InLongMsgCsvUtils.java, inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-kv/src/main/java/org/apache/inlong/sort/formats/inlongmsgkv/InLongMsgKvUtils.java
=> [INLONG-9879][Sort] Fix the inlongmsg-rowdata-kv format parse head error

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ManagerFetcher.java
[INLONG-9889][Agent] Delete test code
- Fixes #9889 
Delete test code, it will be added back in unit testing
Delete test code
*(example:)*
=> [INLONG-9889][Agent] Delete test code, it will be added back in unit testing

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
Title Name: [INLONG-9884][Manager] Optimized code AuditServiceImpl
https://github.com/apache/inlong/issues/9884
Motivation
Explain here the context, and why you're making that change. What is the problem you're trying to solve.
Modifications
Describe the modifications you've done.
=> [INLONG-9884][Manager] Optimized code AuditServiceImpl

inlong-dashboard/src/ui/pages/GroupDashboard/config.tsx, inlong-dashboard/src/ui/pages/SynchronizeDashboard/config.tsx
- Fixes #9895 
Support restart when the task fails.
Add status code
Before:
After:
=> [INLONG-9895][Dashboard] Support restart when the task fails

inlong-common/src/main/java/org/apache/inlong/common/monitor/CounterGroup.java, inlong-common/src/main/java/org/apache/inlong/common/monitor/CounterGroupExt.java, inlong-common/src/main/java/org/apache/inlong/common/msg/InLongMsgAttrBuilder.java
Title Name: [INLONG-9897] Code cognitive complexity modification
https://github.com/apache/inlong/issues/9897
Motivation
Explain here the context, and why you're making that change. What is the problem you're trying to solve.
Modifications
Describe the modifications you've done.
=> [INLONG-9897][Common] Code cognitive complexity modification

inlong-common/src/main/java/org/apache/inlong/common/msg/InLongMsg.java
Title Name: [INLONG-9893] Optimized code InLongMsg.java
https://github.com/apache/inlong/issues/9893
Motivation
Explain here the context, and why you're making that change. What is the problem you're trying to solve.
Modifications
Describe the modifications you've done.
=> [INLONG-9893][Common] Optimized code InLongMsg

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java
[INLONG-9906][Agent] Add configuration comparison logic and processing of comparison results
- Fixes #9906
Add configuration comparison logic and processing of comparison results
Add configuration comparison logic and processing of comparison results
*(example:)* …
=> [INLONG-9906][Agent] Add configuration comparison logic and processing of comparison results

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java
[INLONG-9910][Agent] Increase daily verification for process monitoring, reinstallation, or re downloading
- Fixes #9910 
Increase daily verification for process monitoring, reinstallation, or re downloading
Increase daily verification for process monitoring, reinstallation, or re downloading
*(example:)* …
=> [INLONG-9910][Agent] Increase daily verification for process monitoring, reinstallation, or re downloading

inlong-audit/audit-service/src/main/java/channel/DataQueue.java, inlong-audit/audit-service/src/main/java/config/ConfigConstants.java, inlong-audit/audit-service/src/main/java/config/Configuration.java, inlong-audit/audit-service/src/main/java/entities/SourceConfig.java, inlong-audit/audit-service/src/main/java/source/AbstractSource.java, inlong-audit/audit-service/src/main/java/source/SourceStat.java
- Fixes #9918
*Audit-service add codes of config*
*Audit-service add codes of config.*
=> [INLONG-9918][Audit] Audit-service add codes of config

inlong-audit/audit-service/pom.xml
- Fixes #9930 
*Add pom for audit-service*
*Add pom for audit-service.*
=> [INLONG-9930][Audit] Add pom for audit-service

inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/ConfigConstants.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/SqlConstants.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/entities/SinkConfig.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/EtlService.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/sink/JdbcSink.java
- Fixes #9943
*Audit-service add codes of jdbc sink for aggregate the data from the data source and store the aggregated data to the target storage.*
*Implement data conversion from clickhouse to mysql and mysql to mysql.*
=> [INLONG-9943][Audit] Audit-service add codes of jdbc sink

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java
- Fixes #9953
Fix the problem of stop stream source failed.
Fix the problem of stop stream source failed.
=> [INLONG-9953][Manager] Fix the problem of stop stream source failed

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/pulsar/PulsarDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/pulsar/PulsarDataNodeInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/pulsar/PulsarDataNodeRequest.java
- Fixes #9870 
Pulsar DataNode support to set compression type
The details can be found at [#9870](https://github.com/apache/inlong/issues/9870).
=> [INLONG-9870][Manager] Pulsar DataNode support to set compression type

inlong-common/src/main/java/org/apache/inlong/common/enums/DataTypeEnum.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/BriefMQMessage.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/datatype/CsvDataTypeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/datatype/DataTypeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/InlongMsgDeserializeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/RawMsgDeserializeOperator.java
- Fixes #9974 
Data preview simplifies interface field information.
Data preview simplifies interface field information.
=> [INLONG-9974][Manager]  Data preview simplifies interface field information

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditReporterImpl.java
- Fixes #10014 
*Add new audit SDK API for Flink Sort*
*Add new audit SDK API for Flink Sort.*
=> [INLONG-10014][Audit] Add new audit SDK API for Flink Sort

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/LoadNode.java
-  [INLONG-9875][Sort] Remove repeat DorisLoadNode.
- Fixes #9875
Declaration repeated
Remove repeat DorisLoadNode. declaration
=> [INLONG-9875][Sort] Remove the repeated DorisLoadNode

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/AbstractTask.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/KafkaTask.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/MongoDBTask.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/PulsarTask.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/file/LogFileTask.java
[INLONG-10012][Agent] Adjust task encapsulation to place common logicin the base class
- Fixes #10012
Adjust task encapsulation to place common logicin the base class
Put the basic initialization logic, release logic, and usage of instanceManager into the base class
*(example:)*
No doc needed
=> [INLONG-10012][Agent] Adjust task encapsulation to place common logicin the base class

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ErrorCodeEnum.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/kafka/KafkaClusterInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/kafka/KafkaClusterRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/cls/ClsDataNodeInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/kafka/KafkaDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/kafka/KafkaDataNodeInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/kafka/KafkaDataNodeRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/kafka/KafkaDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaUtils.java
- Fixes #9960 
Support to config kafka data node
The details can be found at [#9960](https://github.com/apache/inlong/issues/9960).
=> [INLONG-9960][Manager] Support to config kafka data node

CHANGES.md
- Fixes #10025
*(example:)*
- If a …
=> [INLONG-10025][Release] Update changes log for the 1.12.0 version

inlong-sort/pom.xml, inlong-sort/sort-flink/pom.xml, inlong-sort/sort-flink/sort-flink-v1.18/pom.xml, inlong-sort/sort-flink/sort-flink-v1.18/sort-flink-dependencies/pom.xml
Fixes #10054 
Support new flink version 1.18.
This is the first part.
- add new profile v1.18
- add flink 1.18 dependencies
*(example:)*
=> [INLONG-10054][Sort] Add dependencies for flink 1.18

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/audit/AuditResponse.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/audit/AuditRunnable.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
- Fixes #10060 10060
Optimize audit data query related logs.
Optimize audit data query related logs.
=> [INLONG-10060][Manager] Optimize audit data query related logs

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/AuditEntityMapper.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
Fixes #10074 
Fix the problem of Error in querying audit information based on IP address.
Fix the problem of Error in querying audit information based on IP address.
=> [INLONG-10074][Manager] Fix the problem of Error in querying audit information based on IP address

inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json, inlong-dashboard/src/ui/pages/ModuleAudit/IdModule/config.tsx, inlong-dashboard/src/ui/pages/ModuleAudit/IdModule/index.tsx, inlong-dashboard/src/ui/pages/ModuleAudit/IpModule/config.tsx
Fixes #10086
Optimize the search function of module audit
Add refresh button
=> [INLONG-10086][Dashboard] Add refresh function of module audit

inlong-audit/audit-service/pom.xml, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/cache/AbstractCache.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/cache/RealTimeQuery.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/ConfigConstants.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/OpenApiConstants.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/SqlConstants.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/entities/SinkConfig.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/entities/SourceConfig.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/entities/StatData.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/main/Application.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/selector/impl/DBDataSource.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/ApiService.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/EtlService.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/sink/JdbcSink.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/source/JdbcSource.java
- Fixes #10085  
*Optimize the performance of the audit-service by optimizing configuration and SQL.*
*Adjusted some default configuration and SQL for audit-service.*
=> [INLONG-10085][Audit] Optimize the performance of the audit-service

inlong-agent/agent-installer/src/main/java/org/apache/inlong/agent/installer/ModuleManager.java
Fixes #10017
Fix the module update configuration bug
Set the old module status to the new module
*(example:)*
No doc needed
=> [INLONG-10017][Agent] Fix the module update configuration bug

.github/workflows/ci_build.yml, .github/workflows/ci_ut.yml, .github/workflows/ci_ut_flink13.yml, .github/workflows/ci_ut_flink15.yml
Fixes #10120
Update the actions/upload-artifact to V4, for the old version to be deprecated.
Update the actions/upload-artifact to V4
=> [INLONG-10120][CI] Update the actions/upload-artifact to V4

bin/inlong-daemon, docker/docker-compose/README.md, inlong-audit/audit-docker/audit-docker.sh, inlong-distribution/src/main/assemblies/release.xml
Fixes #10122
due to https://github.com/apache/inlong/pull/10090 has change apache_inlong_audit.sql to apache_inlong_audit_mysql.sql, but there are some places missed.
due to https://github.com/apache/inlong/pull/10090 has change apache_inlong_audit.sql to apache_inlong_audit_mysql.sql, but there are some places missed.
=> [INLONG-10122][Audit] Update the apache_inlong_audit.sql to apache_inlong_audit_mysql.sql

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/PbMsgDeserializeOperator.java
- Fixes #10141
Data preview supports returning header and specific field information for inlong msg v1.
Data preview supports returning header and specific field information for inlong msg v1.
=> [INLONG-10141][Manager] Data preview supports returning header and specific field information for inlong msg v1

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/ClusterSetMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/ClusterSetMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterTagRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterTagResponse.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/InlongClusterTagExtParam.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamBriefInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamExtParam.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepositoryV2.java
- Fixes #10135 
inlongCompressType to clustertag configuration
inlongCompressType to clustertag configuration
=> [INLONG-10135][Manager] Move inlongCompressType to clustertag configuration

docker/docker-compose/docker-compose.yml, inlong-common/src/main/java/org/apache/inlong/common/constant/Constants.java, inlong-manager/manager-docker/Dockerfile, inlong-manager/manager-docker/manager-docker.sh, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/flink/FlinkService.java, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/flink/dto/FlinkConfig.java, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/util/FlinkUtils.java, inlong-manager/manager-plugins/base/src/main/resources/flink-sort-plugin.properties
- Fixes #10150 
Remove metrics. audit. proxy. hosts from flink-sort-plugins. properties.
Remove metrics. audit. proxy. hosts from flink-sort-plugins. properties.
=> [INLONG-10150][Manager] Remove metrics. audit. proxy. hosts from flink-sort-plugins. properties

bin/init-config.sh, bin/inlong-daemon, conf/inlong.conf, inlong-audit/audit-docker/Dockerfile, inlong-audit/conf/application.properties, inlong-audit/conf/audit-service.properties, inlong-manager/manager-web/src/main/resources/application-dev.properties, inlong-manager/manager-web/src/main/resources/application-prod.properties, inlong-manager/manager-web/src/main/resources/application-test.properties
Fixes #10171
the standalone deploy can't start the audit service.
- update the script according to the latest configuration
=> [INLONG-10171][Audit] Update the standalone deploy scripts for the audit service

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/SinkType.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ClusterType.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/sort/kafka/SortKafkaClusterInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/sort/kafka/SortKafkaClusterRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/SortClusterOperator.java
- Fixes #10169 
Support configure sort cluster for kafka.
Support configure sort cluster for kafka.
=> [INLONG-10169][Manager] Support configure sort cluster for kafka

inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.12.0.sql
- Fixes #10176
Fix the problem of sort_config table creation statement error
Fix the problem of sort_config table creation statement error
=> [INLONG-10176][Manager] Fix the problem of sort_config table creation statement error

bin/init-config.sh, bin/inlong-daemon, conf/inlong.conf
Fixes #10125
Fix the agent can not start successfully
- Remove the http:// prefix to fix the sed command error
- Remove the port-related code for it's not used.
=> [INLONG-10125][Script] Fix the agent can not start successfully

bin/init-config.sh, bin/inlong-daemon, docker/docker-compose/docker-compose.yml, inlong-audit/bin/service-stop.sh
Fixes #10124
Update the scripts for standalone deployment, users can not deploy successfully for the latest version.
- optimize the init config script for the agent
- add the stop script for the audit service
- decrease the sleep interval for the audit service
- make MySQL could be accessed by the command
=> [INLONG-10124][Script] Update the scripts for standalone deployment

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/AbstractDataNodeOperator.java
- Fixes #10181 
Remove useless exceptions for DataNodeOperator.getNodeConfig.
Remove useless exceptions for DataNodeOperator.getNodeConfig.
=> [INLONG-10181][Manager] Remove useless exceptions for DataNodeOperator.getNodeConfig

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java
Fixes #10187
Handle situations where time offset is empty,
Default to no offset
*(example:)*
No doc need
=> [INLONG-10187][Agent] Handle situations where time offset is empty

inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/AuditController.java
- Fixes #10197
Support OpenAPI for querying audit data.
Support OpenAPI for querying audit data.
=> [INLONG-10197][Manager] Support OpenAPI for querying audit data

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ModuleType.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java, inlong-manager/manager-web/src/main/resources/application-dev.properties, inlong-manager/manager-web/src/main/resources/application-prod.properties, inlong-manager/manager-web/src/main/resources/application-test.properties
- Fixes #10200
Define module type mapping relationships.
Define module type mapping relationships.
=> [INLONG-10200][Manager] Define module type mapping relationships

bin/init-config.sh, inlong-audit/audit-store/src/test/resources/application-test.properties, inlong-manager/manager-web/src/main/resources/application-dev.properties, inlong-manager/manager-web/src/main/resources/application-prod.properties, inlong-manager/manager-web/src/main/resources/application-test.properties
Fixes #10205
Add the metrics.audit.proxy.hosts for standalone deployment, and make the configuration to the right value.
- Add the metrics.audit.proxy.hosts for standalone deployment, and make the configuration to the right value.
- Update some annotaions.
=> [INLONG-10205][Script] Add the metrics.audit.proxy.hosts for standalone deployment

inlong-dashboard/src/plugins/sources/defaults/File.ts
Fixes https://github.com/apache/inlong/issues/10215
Motivation
Add default value for the file data source in a data access module
Modifications
Add default values ​​to the maximum number of files, period, and offset properties of the file data source in the data access module
Verifying this change
=> [INLONG-10215][DashBoard] Add default value for file data source in data access module

inlong-audit/audit-sdk/README.md, inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditIdEnum.java, inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditReporterImpl.java, inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/util/AuditManagerUtils.java
- Fixes #10225
There are more and more Audit modules, requiring Audit SDK for unified distribution and management.
Audit SDK provides the ability to automatically assign and manage Audit IDs.
=> [INLONG-10225][Audit] Audit SDK provides the ability to automatically assign and manage Audit ID

inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/node/NodeConfig.java, inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/v2/SortConfigHolder.java, inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/loader/v2/ClassResourceSortClusterConfigLoader.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsSinkContext.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsIdConfig.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSink.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSinkContext.java, inlong-sort-standalone/sort-standalone-source/src/test/java/SortClusterConfig.conf, inlong-sort-standalone/sort-standalone-source/src/test/resources/SortClusterConfig.conf
=> [INLONG-10229][Sort] EsSink support unified configuration

inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/sink/KafkaSinkConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/sink/SinkConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/node/KafkaNodeConfig.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/kafka/KafkaDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/kafka/KafkaDataNodeInfo.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/kafka/KafkaDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/kafka/KafkaSinkOperator.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaFederationSinkContext.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaIdConfig.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaProducerCluster.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaProducerFederation.java
=> [INLONG-10230][Sort] KafkaSink support unified configuration

inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterNodeEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java
- Fixes #10233
Report heartbeat removal port restriction.
Report heartbeat removal port restriction.
=> [INLONG-10233][Manager] Report heartbeat removal port restriction

inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/v2/SortConfigHolder.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarFederationSinkContext.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarFederationWorker.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarIdConfig.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarProducerCluster.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarProducerFederation.java
=> [INLONG-10228][Sort] PulsarSink support unified configuration

inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/DataConfig.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/DataAddTaskRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/SourceRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/StreamSource.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceDTO.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSourceController.java
- Fixes #10245
Support setting audit version for file collection.
Support setting audit version for file collection.
=> [INLONG-10245][Manager] Support setting audit version for file collection

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarQueueResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/QueryLatestMessagesRunnable.java
- Fixes #10249  
Fix the problem of duplicate data appears during data preview.
Only values greater than or equal to 1 are allowed when passing messagePosition.
=> [INLONG-10249][Manager] Fix the problem of duplicate data appears during data preview

docker/docker-compose/docker-compose.yml, inlong-manager/manager-docker/Dockerfile, inlong-manager/manager-docker/manager-docker.sh
Fixes #10252
Fix the bug can not get the real audit address
configure the audit proxy address
=> [INLONG-10252][Docker] Fix the bug can not get the real audit address

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/starrocks/StarRocksSqlBuilder.java
-  [INLONG-10260][MANAGER] Correct wrong create table statement
- Fixes #10260 
Correct wrong create table statement
Remove a comma~
=> [INLONG-10260][Sort] Correct wrong create table statement

inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/SortClusterConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/SortConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/SortTaskConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/DataFlowConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/mq/MqClusterConfig.java, inlong-common/src/main/java/org/apache/inlong/common/util/ListUtil.java, inlong-common/src/main/java/org/apache/inlong/common/util/SortConfigUtil.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/queue/ClusterConfigListener.java
=> [INLONG-10224][Sort] Unified configuration check utils

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ck/ClickHouseSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/doris/DorisSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hive/HiveSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/postgresql/PostgreSQLSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/starrocks/StarRocksSinkDTO.java
- Fixes #10266 
Fix the problem of password is overwritten when adding field information.
When `request.password `is set to a null value, the password in the database will be mistakenly left blank.
This PR hopes that when `request.password` is not passed, the password in the database will not be incorrectly modified.
Fix the problem of password is overwritten when adding field information.
When `request.password` is null, retrieve the password from the data and assign it a value.
=> [INLONG-10266][Manager] Fix the problem of password is overwritten when adding field information

inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/SortClusterConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/SortConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/SortTaskConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/DataFlowConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/dataType/KvConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/mq/MqClusterConfig.java, inlong-common/src/main/java/org/apache/inlong/common/util/SortConfigUtil.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/entity/InLongTopic.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/tube/TubeSingleTopicFetcher.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/QueryConsumeConfigImpl.java, inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/loader/ClassResourceQueryConsumeConfig.java
Fixes #10272 
Support checks the "latest" config by comparing two configs and merging them with the greater version.
*(example:)*
=> [INLONG-10272][Sort] Unified configuration check utils support check latest config

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/starrocks/StarRocksSqlBuilder.java
- Fixes #10265
Fix the problem of correct wrong starrocks create table statement.
Fix the problem of correct wrong starrocks create table statement.
=> [INLONG-10265][Manager] Fix the problem of correct wrong starrocks create table statement

inlong-manager/manager-client/src/test/java/org/apache/inlong/manager/client/api/inner/ClientFactoryTest.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/SinkType.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/es/ElasticsearchFieldInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/es/ElasticsearchSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/ElasticsearchProvider.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/ClusterConfigService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/ClusterConfigServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/queue/ClusterConfigListener.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/es/ElasticsearchResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/es/ElasticsearchSinkOperator.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/ElasticsearchSinkServiceTest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/ClusterConfigController.java
- Fixes #10277
Support calling API to refresh cluster config.
Support calling API to refresh cluster config.
=> [INLONG-10277][Manager] Support calling API to refresh cluster config

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/tenant/InlongTenantServiceImpl.java
- Fixes #10283  
Fix the problem of migration failed when migrating multiple groups to the same tenant.
1.Add logs
2.Before migration, check if tenant cluster tag exists.
=> [INLONG-10277][Manager] Fix the problem of migration failed when migrating multiple groups to the same tenant

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
- Fixes #10300 
Allow unsubmitted groups to modify mq type.
Allow unsubmitted groups to modify mq type.
When the group modifies the mq type, it is allowed to be modified if it is in a pending submission state.
=> [INLONG-10300][Manager] Allow unsubmitted groups to modify mq type

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSource.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceRequest.java
- Fixes #10305 
Delete k8s related parameters in file collection.
Because these parameters are no longer in use.
Delete k8s related parameters in file collection.
=> [INLONG-10305][Manager] Delete k8s related parameters in file collection

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamRequest.java
-Fixes #10324 
Fix the problem of useExtendedFields in Stream incorrectly overwritten.
Fix the problem of useExtendedFields in Stream incorrectly overwritten
Remove default values from request.
=> [INLONG-10324][Manager] Fix the problem of useExtendedFields in Stream incorrectly overwritten

inlong-common/src/main/java/org/apache/inlong/common/enums/IndicatorType.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
Fixes #10345
Fix the problem of error in obtaining audit id value.
Fix the problem of error in obtaining audit id value.
Fix logical errors in determining success and failure logic.
=> [INLONG-10345][Manager] Fix the problem of error in obtaining audit id value

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongGroupEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java
Fixes #10326 
Support obtaining tenant information based on groupId.
Support obtaining tenant information based on groupId.
Add an API for obtaining tenant information.
=> [INLONG-10326][Manager] Support obtaining tenant information based on groupId

inlong-dashboard/src/plugins/sources/defaults/PostgreSQL.ts, inlong-dashboard/src/ui/pages/GroupDetail/DataSources/DetailModal.tsx
Fixes #10347 
Add Agent IP field to PostgreSQL data source
- Add `agentIP` and `dataTimeZone` for PostgreSQL data source
- Fix the error when `agentIP` is not an array
=> [INLONG-10347][Dashboard] Add Agent IP field to PostgreSQL data source

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
Fixes #10351
Fix the problem of no audit name returned when obtaining audit information.
Fix the problem of no audit name returned when obtaining audit information.
When the manager starts, use audit SDK to obtain audit information.
=> [INLONG-10351][Manager] Fix the problem of no audit name returned when obtaining audit information

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/DebeziumChangeFetcher.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/DebeziumDeserializationSchema.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/DebeziumSourceFunction.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/MongoDBConnectorDeserializationSchema.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/MongoDBSource.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/MongoDBTableSource.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/source/IncrementalSource.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/source/IncrementalSourceRecordEmitter.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/source/MongoDBRecordEmitter.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/source/MongoDBSource.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mongodb-cdc/src/main/java/org/apache/inlong/sort/mongodb/source/MongoDBSourceBuilder.java, licenses/inlong-sort-connectors/LICENSE
Fixes #10340 
MongDB connectors AuditOperator not serialized
Some deserialization Code
=> [INLONG-10340][Sort] Fix MongoDB AuditOperator not serialized

inlong-dashboard/src/ui/pages/GroupDetail/Audit/config.tsx, inlong-dashboard/src/ui/pages/ModuleAudit/IdModule/config.tsx, inlong-dashboard/src/ui/pages/ModuleAudit/IpModule/config.tsx
Fixes #10350 
Fix audit item search failure
Rename label name
=> [INLONG-10350][Dashboard] Fix audit item search failure

inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/StartupSortListener.java, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/listener/StartupStreamListener.java, inlong-manager/manager-plugins/base/src/main/java/org/apache/inlong/manager/plugin/util/FlinkUtils.java
Fixes #10353 
refactor code for building and submitting flink job
1. To extract the logic of building and submitting to `org.apache.inlong.manager.plugin.util.FlinkUtils.java` 
2. Unify the processing for exceptions for stream in StartupSortListener.
=> [INLONG-10353][Manager] Refactor code for building and submitting flink job

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInLongGroupController.java
Fixes #10362 
Simplify code for InLong group management
remove duplicated interface and method
=> [INLONG-10362][Manager] Simplify code for InLong group management

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/consume/BriefMQMessage.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/InlongMsgDeserializeOperator.java
Fixes #10368
Data preview supports obtaining message attribute information.
Data preview supports obtaining message attribute information.
=> [INLONG-10368][Manager] Data preview supports obtaining message attribute information

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ErrorCodeEnum.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/TemplateVisibleRange.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/TemplateEntity.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/TemplateFieldEntity.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/TemplateEntityMapper.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/TemplateFieldEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/TemplateEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/TemplateFieldEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/TemplateField.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/TemplateInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/TemplatePageRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/TemplateRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/TemplateService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/TemplateServiceImpl.java, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.13.0.sql
Fixes #10330
Support field template management.
Users can automatically add field information by selecting a template.
Support field template management.
Divide the visible range of the template into global visibility, visible to responsible parties, and visible to tenants.
The template only allows the responsible person to modify and view based on the visible range.
=> [INLONG-10330][Manager] Support field template management

inlong-common/src/main/java/org/apache/inlong/common/enums/DataTypeEnum.java, inlong-common/src/main/java/org/apache/inlong/common/util/StringUtil.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/base/ExtractNodeProvider.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/KafkaProvider.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/PulsarProvider.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/TubeMqProvider.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSource.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSourceRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSource.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/pulsar/PulsarSourceRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/tubemq/TubeMQSource.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/tubemq/TubeMQSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/tubemq/TubeMQSourceRequest.java
Fixes #10370
Support configuration of kV data format.
Support configuration of kV data format.
\
=> [INLONG-10370][Manager] Support configuration of kV data format

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/TemplateClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/TemplateApi.java
Fixes #10373
Manager client support template operation.
Manager client support template operation.
=> [INLONG-10373][Manager] Manager client support template operation

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/fieldtype/strategy/ClsFieldTypeStrategy.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/fieldtype/strategy/ElasticsearchFieldTypeStrategy.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/fieldtype/strategy/StarRocksFieldTypeStrategy.java, inlong-manager/manager-common/src/main/resources/cls-field-type-mapping.yaml, inlong-manager/manager-common/src/main/resources/es-field-type-mapping.yaml
Fixes #10375
Add field mapping strategy for CLS, StarRocks and Elasticsearch.
Add field mapping strategy for CLS, StarRocks and Elasticsearch.
=> [INLONG-10375][Manager] Add field mapping strategy for CLS, StarRocks and Elasticsearch

inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/DataNodeController.java
Fixes #10382
Support obtaining node information through unique keys.
Support obtaining node information through unique keys.
=> [INLONG-10382][Manager] Support obtaining node information through unique keys

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/audit/AuditProxyResponse.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/AuditService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/AuditController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/AuditController.java
Fixes #10388
Provide an interface to obtain the audit proxy address.
Provide an interface to obtain the audit proxy address.
=> [INLONG-10388][Manager] Provide an interface to obtain the audit proxy address

inlong-manager/manager-common/src/main/resources/iceberg-field-type-mapping.yaml
Fixes #10405
Fix the problem of Iceberg field type mapping error.
Fix the problem of Iceberg field type mapping error.
=> [INLONG-10405][Manager]  Fix the problem of Iceberg field type mapping error

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java
Fixes #10407
Increase the interval for determining heartbeat timeout.
Increase the interval for determining heartbeat timeout.
=> [INLONG-10407][Manager] Increase the interval for determining heartbeat timeout

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSource.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/kafka/KafkaSourceRequest.java
Fixes #10415
Kafka source supports configuring wraptype.
Kafka source supports configuring wraptype.
=> [INLONG-10415][Manager] Kafka source supports configuring wraptype

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/KafkaProvider.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/MySQLBinlogProvider.java
Fixes #10413
Support for configuring built-in fields for mysql and kafka.
Support for configuring built-in fields for mysql and kafka.
=> [INLONG-10413][Manager] Support for configuring built-in fields for mysql and kafka

inlong-dashboard/src/configs/menus/conf.tsx
Fixes #10421
Move template management to system management
Move template management to system management
=> [INLONG-10421][Dashboard] Move template management to system management

inlong-common/src/main/java/org/apache/inlong/common/constant/SinkType.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/SortTaskConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/dataType/DataTypeConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/deserialization/DeserializationConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/sink/SinkConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/mq/MqClusterConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/node/NodeConfig.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/StreamType.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/cls/ClsSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/kafka/KafkaSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/kafka/KafkaSinkRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/DorisProvider.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/cls/ClsDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/es/ElasticsearchDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/kafka/KafkaDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/pulsar/PulsarDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/AbstractSinkOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/cls/ClsSinkOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/es/ElasticsearchSinkOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/kafka/KafkaSinkOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/pulsar/PulsarSinkOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/SortController.java
Fixes #10423
Modify unified configuration related classes and interfaces.
1.Modify unified configuration related classes and interfaces.
2.Added attributes to sinks and nodes such as cls and kafka.
3.Handle situations where sink is not assigned to task.
=> [INLONG-10423][Manager] Modify unified configuration related classes and interfaces

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/kafka/KafkaSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/kafka/KafkaSinkRequest.java
Fixes #10425
Fix the problem of the kafka sink defines duplicate attributes.
Fix the problem of the kafka sink defines duplicate attributes.
Delete duplicate attributes.
=> [INLONG-10425][Manager] Fix the problem of the kafka sink defines duplicate attributes

inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/SortClusterConfig.java
Fixes #10430 
Check failed when the node config is null, or the update and delete happen at the same time.
All of modification of mqClusters (delete/online/update) should refresh all of dataflow under this cluster tag
*(example:)*
=> [INLONG-10430][Manager] Check update error of unified configuration

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/options_basic.go
Fixes #10457
Fix auth spelling errors 
Repair atuh to auth
=> [INLONG-10457][SDK] Fix auth spelling errors

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/kafka/KafkaDataNodeRequest.java
- Fixes #10455 
fix Set KafkaDataNode ack fail
The details can be found at [#10455 ](https://github.com/apache/inlong/issues/10455).
=> [INLONG-10455][Manager] Fix Set KafkaDataNode ack fail

docker/docker-compose/docker-compose.yml, inlong-manager/manager-docker/Dockerfile, inlong-manager/manager-docker/manager-docker.sh
Fixes #10461
Update the way to configure audit service info
- update the docker-compose file
- update the Dockerfile
=> [INLONG-10461][Docker] Update the way to configure audit service info

inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/utils/ThreadUtils.java, inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditReporterImpl.java, inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/ProxyManager.java
- Fixes #10470
Optimize Audit Proxy configuration update retry logic.
When the manager hangs up, retry at intervals until the retry is successful.
=> [INLONG-10470][Audit] Optimize Audit Proxy configuration update retry logic

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/StreamTransformService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/StreamTransformServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSinkController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSourceController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInLongClusterController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInLongGroupController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenInLongStreamController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenStreamSinkController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenStreamSourceController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenStreamTransformController.java
Fixes #10484 
Refactor code in manager-service module, keep logic consistency for API and open API.
1. remove duplicated interfaces and implementations in module `manager-service`
2. extract some duplicates to common method
=> [INLONG-10484][Manager] Refactor code in manager-service module

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/PulsarTableFactory.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/PulsarTableOptionUtils.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/src/main/java/org/apache/inlong/sort/pulsar/PulsarTableOptions.java
=> [INLONG-10492][Sort] Fix init failure of pulsar connector

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/TemplateEntityMapper.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/TenantClusterTagEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/TemplateEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/TemplateServiceImpl.java
Fixes #10498
Template supports modifying associated tenants.
Template supports modifying associated tenants.
By setting up tenants, the template can only be visible within a few tenants.
=> [INLONG-10498][Manager] Template supports modifying associated tenants

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/TemplateInfo.java
Fixes #10506
When obtaining a template, return information such as creator and modifier.
When obtaining a template, return information such as creator and modifier.
Make it easier for users to know who operated on the template.
=> [INLONG-10506][Manager] When obtaining a template, return information such as creator and modifier

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/BaseInlongStream.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/InlongStreamExtParam.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/datatype/KvDataTypeOperator.java
Fixes #10512 
Support preview of data in kv data type.
Support preview of data in kv data type.
Add parameters such as kV separator.
=> [INLONG-10512][Manager] Support preview of data in kv data type

inlong-distribution/src/main/assemblies/sort-connectors-v1.15.xml
Fixes #10518 
Add jdbc fileSet in inlong-distribution sort-connectors-v1.15.xml
sort-connectors-v1.15.xml
=> [INLONG-10518][Sort] Add jdbc fileSet in inlong-distribution sort-connectors-v1.15.xml

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterNodeRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java
Fixes #10434
Allow creating cluster nodes without setting port.
At present, the agent node does not have the concept of port, so there is no need to set port information.
Allow creating cluster nodes without setting port.
=> [INLONG-10434][Manager] Allow creating cluster nodes without setting port

docker/docker-compose/docker-compose.yml, inlong-common/src/main/java/org/apache/inlong/common/heartbeat/HeartbeatMsg.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java
Fixes #10520
Fix the problem of protocol type reported by dataproxy not correctly accepted.
Fix the problem of protocol type reported by dataproxy not correctly accepted.
=> [INLONG-10520][Manager] Fix the problem of protocol type reported by dataproxy not correctly accepted

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClientConfig.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/kafka/KafkaMultiTopicsFetcher.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/kafka/KafkaSingleTopicFetcher.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/pulsar/PulsarMultiTopicsFetcher.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/pulsar/PulsarSingleTopicFetcher.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/tube/TubeSingleTopicFetcher.java, inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/pulsar/InLongPulsarFetcherImplTest.java
=> [INLONG-10522][SDK] SortSDK support assgin subscription

inlong-dashboard/src/plugins/consumes/common/ConsumeDefaultInfo.ts, inlong-dashboard/src/plugins/groups/common/GroupDefaultInfo.ts, inlong-dashboard/src/plugins/sync/common/SyncDefaultInfo.ts, inlong-dashboard/src/ui/pages/AgentModule/config.tsx, inlong-dashboard/src/ui/pages/AgentPackage/config.tsx, inlong-dashboard/src/ui/pages/ClusterTags/ClusterList.tsx, inlong-dashboard/src/ui/pages/Clusters/index.tsx, inlong-dashboard/src/ui/pages/ConsumeDashboard/config.tsx, inlong-dashboard/src/ui/pages/ConsumeDashboard/index.tsx, inlong-dashboard/src/ui/pages/GroupDashboard/config.tsx, inlong-dashboard/src/ui/pages/Nodes/index.tsx, inlong-dashboard/src/ui/pages/SynchronizeDashboard/config.tsx, inlong-dashboard/src/ui/pages/TenantManagement/config.tsx, inlong-dashboard/src/ui/pages/UserManagement/config.tsx
Fixes #10524 
The creation time and modification time in the Modify column are displayed
Modify the time column
before
after:
remove the status
before
after
=> [INLONG-10524][Dashboard] Modify the time column

inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/metrics/SortConfigMetricListener.java, inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/metrics/SortConfigMetricReporter.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/SortStandaloneApplication.java
=> [INLONG-10540][Sort] SortStandalone unified configuration metric reporter

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSinkContext.java, inlong-sort-standalone/sort-standalone-source/src/test/java/common.properties, inlong-sort-standalone/sort-standalone-source/src/test/resources/common.properties
=> [INLONG-10527][Sort] EsSink support switch metadata acquire mode

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaFederationSinkContext.java
=> [INLONG-10528][Sort] KafkaSink support switch metadata acquire mode

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarFederationSinkContext.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarIdConfig.java
=> [INLONG-10529][Sort] PulsarSink support switch metadata acquire mode

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/BaseStreamSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/ck/ClickHouseSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/cls/ClsSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/doris/DorisSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/es/ElasticsearchSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/greenplum/GreenplumSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hbase/HBaseSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hdfs/HDFSSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hive/HiveSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/hudi/HudiSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/iceberg/IcebergSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/kafka/KafkaSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/kudu/KuduSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/oracle/OracleSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/postgresql/PostgreSQLSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/pulsar/PulsarSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/redis/RedisSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/sqlserver/SQLServerSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/starrocks/StarRocksSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/tdsqlpostgresql/TDSQLPostgreSQLSinkDTO.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/entity/InLongTopic.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/util/TimeUtil.java, inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/loader/SortConfigQueryConsumeConfig.java
=> [INLONG-10562][Manager] SortConfig supports set start and stop consuming time

.asf.yaml
Fixes #10580 
We want to merge the dev-offline-sync branch to the master branch and also keep the commit list.
But now we only support squash and merge, so we should enable the merge and rebase options.
Enable merge and rebase
=> [INLONG-10580][ASF] Enable merge and rebase

inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/pojo/CacheClusterConfig.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaFederationSinkContext.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaProducerCluster.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaProducerFederation.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarFederationSinkContext.java
=> [INLONG-10954][Sort] Provide default kafka producer configuration

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarFederationSinkContext.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarProducerCluster.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarProducerFederation.java
=> [INLONG-10597][Sort] Provide default pulsar producer configuration

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsSinkContext.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSinkContext.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaFederationSinkContext.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarFederationSinkContext.java
=> [INLONG-10604][Sort] Fix NPE when unified configuration is not exits

inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/AgentConfigInfo.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/AgentTaskConfigEntity.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/AgentTaskConfigEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/AgentTaskConfigEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/ConfigLoader.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ConfigLoaderImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortSourceServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/StreamTaskListenerFactory.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/source/SourceStartListener.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/repository/DataProxyConfigRepository.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/TemplateServiceImpl.java, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.13.0.sql
Fixes #10601
Optimize the agent task configuration process
1.Add a version number to the agent configuration pull interface to control whether the task needs to be changed, in order to prevent inconsistent configuration pulled by the agent from the manager when the manager is in multiple clusters.
2.Optimize the agent configuration pull process, unify task configurations into one table, and the agent pull interface only operates on this table to prevent low pull efficiency caused by multi table queries.
3.Agent cache is scheduled to pull in batches from the database to prevent cache breakdown.
=> [INLONG-10601][Manager] Optimize the agent task configuration process

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/AbsFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/LnFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/PowerFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/SqrtFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformArithmeticFunctionsProcessor.java
Fixes #10603
Transform SQL support arithmetic functions(Including power, abs, sqrt and ln)
Add four arithmetic function classes: PowerFunction, AbsrFunction, SqrtFunction, and LnFunction. Also, add the corresponding unit test codes
*(example:)*
=> [INLONG-10603][SDK] Transform SQL support arithmetic functions(Including power, abs, sqrt and ln)

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java
Fixes #10611
Configuration may experience repeated old and new data due to caching
Update configuration only when the version number is increased
*(example:)*
No doc needed
=> [INLONG-10611][Agent] Update configuration only when the version number is increased

inlong-dashboard/src/ui/pages/Process/Applies/config.tsx, inlong-dashboard/src/ui/pages/Process/Approvals/config.tsx
Fixes #10620
Resolve page errors
Add non-empty judgment
before:
after: normal display
=> [INLONG-10620][Dashboard]  Fix the page error occurs wrong

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/TemplateServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/ClickHouseSinkServiceTest.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/HudiSinkServiceTest.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/sink/IcebergSinkServiceTest.java
Fixes #10625
Fix problem of the responsible person cannot modify the template configuration.
Fix problem of the responsible person cannot modify the template configuration.
=> [INLONG-10625][Manager] Fix problem of the responsible person cannot modify the template configuration

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/postgre/DebeziumSourceFunction.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/postgres-cdc/src/main/java/org/apache/inlong/sort/postgre/RowDataDebeziumDeserializeSchema.java
=> [INLONG-10609][Sort] Make PostgreSQL source support report audit information exactly once

inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/installer/ConfigResult.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/agent/installer/ModuleConfig.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/AgentTaskConfigEntity.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/ModuleConfigEntityMapper.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/PackageConfigEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/AgentTaskConfigEntityMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/ModuleConfigMapper.xml, inlong-manager/manager-dao/src/main/resources/mappers/PackageConfigMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/AgentClusterNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/ConfigLoader.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/ConfigLoaderImpl.java, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.13.0.sql, inlong-manager/manager-web/src/main/resources/application-dev.properties
Fixes #10635
Optimize the installer configuration process.
Optimize the installer configuration process.
1.When setting up the agent node, module config will be loaded into agent_task_config.
2.If you actively install the installer, it will obtain the default module configuration.
=> [INLONG-10635][Manager] Optimize the installer configuration process

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongStreamClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongStreamApi.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/util/JsonUtils.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/QueryMessageRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/DeserializeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/InlongMsgDeserializeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/PbMsgDeserializeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/RawMsgDeserializeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/QueueResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaQueueResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarQueueResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/QueryLatestMessagesRunnable.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/tubemq/TubeMQOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/tubemq/TubeMQQueueResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/stream/InlongStreamServiceImpl.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/resource/queue/kafka/KafkaOperatorTest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongStreamController.java
Fixes #10638
Data preview supports filtering function.
Data preview supports filtering function.
1.Add `QueryMessageRequest`, Including `FieldName`、 `operationType`、`targetValue`.
2.When data preview needs to be filtered, all three parameters above must be set.
3.`FieldName` is used to set the field as the filtering condition, and `operationType` is used as the filtering operation type, such as `like` 、`=`、`!=` , `TargetValue` is a comparative value.
=> [INLONG-10638][Manager] Data preview supports filtering function

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/datatype/CsvDataTypeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/datatype/KvDataTypeOperator.java
Fixes #10648
Fix the problem of the get sort config interface returns an error status code.
Fix the problem of the get sort config interface returns an error status code.
When sortconfig cannot be obtained, return `RESPONSE_CODE_FAIL`.
=> [INLONG-10648][Manager] Fix the problem of the get sort config interface returns an error status code

inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/metrics/SortConfigMetricReporter.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaIdConfig.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarIdConfig.java
=> [INLONG-10655][Sort] Kafka and Pulsar Sink support parse stream separator

.github/ISSUE_TEMPLATE/bug-report.yml
Fixes #10656
Added information for version 1.13.0.
Add version information in ".github/ISSUE_TEMPLATE/bug-report.yml" file.
=> [INLONG-10656][Release] Add the 1.13.0 version option for the bug report

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/connpool/connpool.go, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/metrics.go, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/worker.go
Fixes #10676 
Fix type asserttion and type switch warnings in Golang SDK
1. Fix type switch warning in worker.go;
2. Fix type assertion warnings in metrics.go;
3. Fix lint warning in connpool.go
*(example:)*
=> [INLONG-10676][SDK] Fix type asserttion and type switch warnings in Golang SDK

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/worker.go
Fixes #10675 
Currently, when send batch failed, we just retry with a linear backoff, it is better to use a exponential backoff.
1. Use exponential backoff instead of linear backoff retrying.
*(example:)*
=> [INLONG-10675][SDK] Use exponential backoff instead of linear backoff retrying in Golang SDK

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/AuditService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/AuditController.java
Fixes #10689
Support querying metric information.
Support querying metric information.
=> [INLONG-10689][Manager] Support querying metric information

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mysql-cdc/pom.xml
=> [INLONG-10694][Sort] Mysql-cdc source fails to convert timestamp type

CHANGES.md
Fixes #10658
Update changes log for the 1.13.0 version.
Update changes log for the 1.13.0 version.
=> [INLONG-10658][Release] Update changes log for the 1.13.0 version

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
Fixes #10709 
when checking group exists, there is a bug caused by schedule configurations.
fix group existing check error caused by schedule configuration
=> [INLONG-10709][Manager] fix group exist check error caused by schedule configuration

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/source/SourceStartListener.java
Fixes #10711
Fix the problem of the stream source did not update its status correctly after executing the workflow.
Fix the problem of the stream source did not update its status correctly after executing the workflow.
=> [INLONG-10711][Manager] Fix the problem of the stream source did not update its status correctly after executing the workflow

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/listener/source/AbstractSourceOperateListener.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
Fixes #10714
Fix the problem of incorrect deletion of data source task.
Fix the problem of incorrect deletion of data source task.
=> [INLONG-10714][Manager] Fix the problem of incorrect deletion of data source task

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/es/ElasticsearchApi.java, inlong-manager/manager-service/src/test/java/org/apache/inlong/manager/service/resource/sink/Base64CompatibleTest.java
Fixes #10723 
see descriptions in #10723 
Update base64 encoder from sun.misc.BASE64Encoder to java.util.Base64.Encoder
test code: 
org.apache.inlong.manager.service.resource.sink.Base64CompatibleTest
=> [INLONG-10723][Manager] Update base64 encoder

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/AbstractStandaloneSinkResourceOperator.java
=> [INLONG-10730][Manager] Fix auto-assign wrong Sortstandalone cluster when no cluster is under the tag

inlong-sdk/dataproxy-sdk/pom.xml
- Fixes #10706 
DataProxy SDK Shaded Native Library
The details can be found at [#10706 ](https://github.com/apache/inlong/issues/10706).
=> [INLONG-10706][SDK] DataProxy SDK Shaded Native Library

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/EsMapSinkEncoder.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/MapSinkEncoder.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/SinkEncoderFactory.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/CsvSinkInfo.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/EsMapSinkInfo.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/MapSinkInfo.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/SinkInfo.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/TransformConfig.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/converter/TypeConverter.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/SinkContext.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/DefaultEvent2IndexRequestHandler.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsChannelWorker.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsIdConfig.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSinkContext.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/IEvent2IndexRequestHandler.java, inlong-sort-standalone/sort-standalone-source/src/test/java/org/apache/inlong/sort/standalone/sink/elasticsearch/TestEsSinkContext.java, inlong-sort/sort-end-to-end-tests/pom.xml
=> [INLONG-10729][Sort] Sorstandalone EsSink support transform

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/AgentConstants.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/store/InstanceStore.java, inlong-agent/agent-core/pom.xml, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentStatusManager.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/OffsetManager.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/TaskManager.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java, inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sinks/filecollect/TestSenderManager.java
Fixes #10751 
Report Agent process status for backend problem analysis
Report Agent process status every minute, including version, os, cpu, memeory, sending static etc
*(example:)*
No doc needed
=> [INLONG-10751][Agent] Report Agent process status for backend problem analysis

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentStatusManager.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/FileStaticManager.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/task/OffsetManager.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java
Fixes #10756 
Report file metrics for backend problem analysis
Report the read-write status to the backend after file collection is completed
*(example:)*
No doc needed
=> [INLONG-10756][Agent] Report file metrics for backend problem analysis

inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/deserialization/DeserializationConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/deserialization/RawDeserializationConfig.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/message/RawMsgDeserializeOperator.java, inlong-sort-standalone/sort-standalone-source/src/test/java/SortConfig.conf, inlong-sort-standalone/sort-standalone-source/src/test/resources/SortConfig.conf
Fixes #10758
Support obtaining serialization configuration when wrapType is raw.
1.Add the `RawDesoialitionConfig.clase`.
2.Rewrite the `RawFsDesequentialOperator.getDesequentialationConfig`.
=> [INLONG-10758][Manager] Support obtaining serialization configuration when wrapType is raw

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java
Fixes #10754 
Fix the problems for crontab expression offline sync job may generate too many schedule instances before the current time
1. check start time and end time, make sure not null
2. make sure the start time is not before the current time
3. make sure the end time is not before the start time
=> [INLONG-10754][Manager] Add start and ent time check for schedule info

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/CMakeLists.txt, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/README.md, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/build_third_party.sh
- Fixes #10774
Optimize Cmake compilation script for CPP DataProxy SDK
Separate third-party libraries from the code base to reduce unnecessary duplication of compilation
=> [INLONG-10774][SDK] Optimize Cmake compilation script for CPP DataProxy SDK

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/DateExtractFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TimestampExtractFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/TimestampParser.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformTemporalFunctionsProcessor.java
Fixes #10767
Transform SQL support temporal functions(Including hour, minute and second)
Add one temporal function class `TimestampExtractFunction` and one class `TimestampParser` that implements the class `ValueParser`. Also, add the corresponding unit test codes
*(example:)*
=> [INLONG-10767][SDK] Transform SQL support temporal functions(Including hour, minute and second)

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/build.sh
Fixes #10789
The build script for the c++ dataproxy sdk has changed, so the python dataproxy sdk build script needs to be updated accordingly.
*(example:)*
=> [INLONG-10789][SDK] Update build script for the python dataproxy sdk

inlong-dashboard/src/ui/locales/en.json
Fixes #10787
update i18n item for better display
changed a wrong i18n(en) item name.
=> [INLONG-10787][Dashboard] Update Missing i18n(en) Item

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.h
- Fixes #10799
Support fork child process for DataProxy CPP SDK
Support fork child process for DataProxy CPP SDK by optimizing the implementation of single instance
=> [INLONG-10799][SDK] Support fork child process for DataProxy CPP SDK

inlong-dashboard/src/plugins/sinks/common/SinkDefaultInfo.ts
Fixes #10783 
Add enableCreateResource field to all sinks
Add enableCreateResource field to all sinks
before:
after:
=> [INLONG-10783][Dashboard] Add enableCreateResource field to all sinks

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/CMakeLists.txt, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/api_imp.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/metric_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/metric_manager.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/metric/environment.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/metric/metric.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/CMakeLists.txt, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/capi_constant.h
- Fixes #10793
Added metric management for DataProxy CPP SDK
Added metric management for DataProxy CPP SDK to facilitate system operation
=> [INLONG-10793][SDK] Added metric management for DataProxy CPP SDK

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/CosFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformArithmeticFunctionsProcessor.java
Fixes #10813 
Add a arithmatic function class: CosFuntion and its unit test.
*(example:)*
=> [INLONG-10813][SDK] Transform support cos function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RoundFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformArithmeticFunctionsProcessor.java
Fixes #10803 
Add one arithmetic function classe: RoundFunction. Also, add the corresponding unit test codes
*(example:)*
=> [INLONG-10803][SDK] Transform SQL support Round function

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/CMakeLists.txt, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/demo/send_demo.py, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/inlong_dataproxy.cpp
Fixes #10811
Fix callback function calls lead to coredump in python sdk
Modify the pybind wrapper code and CMakeLists.
*(example:)*
=> [INLONG-10811][SDK] Fix callback function calls lead to coredump in python sdk

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/sdk_msg.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/msg_manager.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/capi_constant.h
- Fixes #10822
Add message manager for DataProxy C++ SDK
Add message manager for DataProxy C++ SDK to improve ability to send data
=> [INLONG-10822][SDK] Add message manager for DataProxy C++ SDK

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/client/tcp_client.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/client/tcp_client.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/api_code.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/api_imp.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/api_imp.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/sdk_msg.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/recv_group.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/recv_group.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/capi_constant.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/send_buffer.h
- Fixes #10821
Optimize the ability to receive data for DataProxy C++ SDK
Optimize the ability to receive data for DataProxy C++ SDK by optimizing packaging and memory management
=> [INLONG-10821][SDK] Optimize the ability to receive data for DataProxy C++ SDK

inlong-common/src/main/java/org/apache/inlong/common/constant/SinkType.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/sink/HttpSinkConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/dataflow/sink/SinkConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/node/HttpNodeConfig.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/sort/node/NodeConfig.java
Fixes #10828
Add `NodeConfig` and `SinkConfig` for SortStandalne to support HTTP report.
Add two config classes: `HttpNodeConfig` and `HttpSinkConfig`.
*(example:)*
=> [INLONG-10828][SDK] Add config classes for SortStandalone to support HTTP report

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/include/inlong_api.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/client/tcp_client.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/config/sdk_conf.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/api_imp.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/api_imp.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/inlong_api.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/inlong_api.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/sdk_msg.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/recv_group.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/send_group.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/send_group.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/protocol/msg_protocol.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/capi_constant.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/send_buffer.h
- Fixes #10838
Optimize the ability to send data for DataProxy C++ SDK
Optimize the ability to send data for DataProxy C++ SDK by optimize the performance of tcp
=> [INLONG-10838][SDK] Optimize the ability to send data for DataProxy C++ SDK

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/ClusterConfigServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/SortServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java
Fixes #10834
Standalone configuration supports Tube MQ.
1.`ClusterConfigServiceImpl` supports configuring cluster information of tube MQ type and adds the judgment that cluster labels cannot have multiple MQ types at the same time.
2.`DefaultSortConfig` Operator adds types of tubemq type.
=> [INLONG-10834][Manager]  Standalone configuration supports TubeMQ

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TanFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformArithmeticFunctionsProcessor.java
Fixes #10819 
Add a arithmatic function class: TanFuntion and its unit test.
*(example:)*
=> [INLONG-10819][SDK] Transform support tan function

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/api_imp.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/core/api_imp.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/buffer_manager.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/metric_manager.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/msg_manager.h, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/manager/proxy_manager.cc, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/utils/utils.cc
- Fixes #10861
Optimize the coredump caused by the DataProxy C++ SDK
Optimize the coredump caused by the DataProxy C++ SDK by adjusting the logic of process exit
=> [INLONG-10861][SDK] Optimize the coredump caused by the DataProxy C++ SDK

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/DataNodeType.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/SinkType.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/ClusterType.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/sort/http/SortHttpClusterInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/sort/http/SortHttpClusterRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/http/HttpDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/http/HttpDataNodeInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/http/HttpDataNodeRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/BaseStreamSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/SinkRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/StreamSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/http/HttpSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/http/HttpSinkDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/http/HttpSinkRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/SortClusterOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/http/HttpDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/http/HttpSinkOperator.java
Fixes #10884
Support configuring HTTP type sink.
1.Add HTTP datanode.
2.Add HTTP Sink.
=> [INLONG-10884][Manager] Support configuring HTTP type sink

inlong-dashboard/src/plugins/sources/common/SourceDefaultInfo.ts, inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json, inlong-dashboard/src/ui/pages/GroupDetail/DataSources/index.tsx
Fixes #10846 
Add cluster name to data source information display
Add cluster name to data source information display,Fixed the operation bar and added the excess part for sliding
before:
after:
=> [INLONG-10846][Dashboard] Add cluster name to data source information display

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-python/inlong_dataproxy.cpp
Fixes #10894
The pybind binding code exposes a useless interface `AddBid` that interferes with python SDK builds, so remove this interface.
*(example:)*
- Does this pull request introduce a new feature?no
=> [INLONG-10894][SDK] Remove the useless interface 'AddBid' exposed in pybind binding code

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongClusterNodeEntity.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterNodeEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterNodeEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterNodeRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/ClusterNodeResponse.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/AgentClusterNodeInstallOperator.java, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-1.14.0.sql
Fixes #10856
Support agent installation logs.
Support agent installation logs.
1.Add the `operate_log` field to the `inlong_cluster_node` table.
2.Update `operate_Log` information when agent installation fails.
=> [INLONG-10856][Manager] Support agent installation logs

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/BinFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformArithmeticFunctionsProcessor.java
Fixes #10901 
Add a function class: BinFunction and its unit test.
to support flinkSQL common function BIN(INT)
bin(integer)：Returns a string representation of an integer in binary format. If the integer is NULL, NULL is returned.
For example, BIN(4) returns "100" and BIN(12) returns "1100".
*(example:)* …
=> [INLONG-10901][SDK] Transform support BIN(integer) function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/LengthFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformStringFunctionsProcessor.java
Fixes #10905 
Add one arithmetic function classe: LengthFunction. Also, add the corresponding unit test codes.
*(example:)*
=> [INLONG-10905][SDK] Transform support Length() function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ReverseFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformStringFunctionsProcessor.java
Fixes #10823
Add one transform function class: ReverseFunction and its unit test.
- REVERSE(str)
Returns the string str with the order of the characters reversed.
- Such as: REVERSE("abc") = "cba"
*(example:)*
=> [INLONG-10823][SDK] Transform SQL support Reverse function

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/AgentClusterNodeInstallOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/InlongClusterNodeInstallOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cmd/CommandExecutor.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cmd/CommandExecutorImpl.java
Fixes #10907 
Support reinstalling the installer.
1.Support reinstalling the installer.
2.Support unload the installer.
=> [INLONG-10907][Manager] Support reinstalling the installer

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSinkController.java
Fixes #10911 
Support pagination to query sort task details  information.
Support pagination to query sort task details  information.
=> [INLONG-10911][Manager] Support pagination to query sort task details  information

inlong-dashboard/src/ui/pages/GroupDetail/DataStream/PreviewModal.tsx
Fixes #10898
Data ranking increases according to dt sorting
Data ranking increases according to dt sorting
before:
after:
=> [INLONG-10898][Dashboard] Data ranking increases according to dt sorting

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/AcosFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformArithmeticFunctionsProcessor.java
Fixes #10886 
Add a function class: AcosFunction and its unit test.
- ACOS(numeric)
Returns the arc cosine of numeric.
*(example:)*
=> [INLONG-10886][SDK] Transform support ACOS function

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/AgentClusterNodeInstallOperator.java
Fixes #10918 
The correct command was not used when reinstalling the installer.
1.Add startup command.
2.Modify restart command.
=> [INLONG-10918][Manager] The correct command was not used when reinstalling the installer

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/LowerFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/UpperFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformStringFunctionsProcessor.java
Fixes #10869 
Add two arithmetic function classes: LowerFunction and UpperFunction. Also, add the corresponding unit test codes.
*(example:)*
=> [INLONG-10869][SDK] Transform SQL supports case conversion of strings

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/LocalTimeFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformTemporalFunctionsProcessor.java
Fixes #10920 
- Add a function class: LocalTimeFunction and its unit test.
- LocalTime([string1])
Returns the local time (format: HH:mm:ss) in the time zone string1(by default: string1 is system default time zone if not specified).
- CurrentTime([string1])
This is a synonym of LocalTime.
*(example:)* …
=> [INLONG-10920][SDK] Transform support LocalTime function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/LeftFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RightFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformStringFunctionsProcessor.java
Fixes #10906 
Add two function classes: LeftFunction and RightFunction. Also, add the corresponding unit test codes.
*(example:)*
=> [INLONG-10906][SDK] Transform supports the truncation of left and right strings

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/SignFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformArithmeticFunctionsProcessor.java
Fixes #10866 
Add one arithmetic function classe: SignFunction. Also, add the corresponding unit test codes.
*(example:)*
=> [INLONG-10866][SDK] Transform SQL support sign function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/Md5Function.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformArithmeticFunctionsProcessor.java
Fixes #10864 
Add one arithmetic function classe: Md5Function. Also, add the corresponding unit test codes.
*(example:)*
=> [INLONG-10864][SDK] Transform SQL support md5 function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/DateExtractFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformTemporalFunctionsProcessor.java
Fixes #10930
Add a type DAY_OF_WEEK in class DateExtractFunction, implement DAYOFWEEK function and its unit test.
- DAYOFWEEK(date)
Returns the day of a week (an integer between 1(Sunday) and 7(Saturday)) from SQL date.
E.g., DAYOFWEEK(DATE ‘2024-02-29’) returns 5. (Thursday)
*(example:)* …
=> [INLONG-10930][SDK] Transform support DAYOFWEEK function

inlong-manager/manager-service/pom.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/datatype/CsvDataTypeOperator.java
Fixes #10931
Data preview supports data containing escape characters.
Using the transform SDK to parse data.
=> [INLONG-10931][Manager] Data preview supports data containing escape characters

inlong-dashboard/src/ui/locales/en.json
Fixes #10947 
Modify field description missing for English locale
Modify field description missing for English locale
=> [INLONG-10947][Dashboard] Modify field description missing for English locale

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/LocalDateFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformTemporalFunctionsProcessor.java
Fixes #10934
- Add a function class: LocalDateFunction and its unit tests.
- LocalDate([string1])
Returns the local date in the time zone string1(by default: string1 is system default time zone if not specified).
*(example:)*
=> [INLONG-10934][SDK] Transform support LocalDate function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/StrcmpFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformStringFunctionsProcessor.java
Fixes #10939 
Add one function classe: STRCMP . Also, add the corresponding unit test codes.
*(example:)*
=> [INLONG-10939][SDK] Transform SQL supports STRCMP function

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FieldInfoUtils.java
Fixes #10954
Support fields of timestamptz type.
Support fields of timestamptz type.
=> [INLONG-10954][Manager] Support fields of timestamptz type

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/LpadFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RpadFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformStringFunctionsProcessor.java
Fixes #10927 
Add two function classes: RpadFunction and LpadFunction. Also, add the corresponding unit test codes.
*(example:)*
=> [INLONG-10927][SDK] Transform supports padding of left and right strings

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/DateDiffFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformTemporalFunctionsProcessor.java
Fixes #10897 
Add one function classe: DateDiffFunction. Also, add the corresponding unit test codes.
*(example:)*
=> [INLONG-10897][SDK] Transform support DATEDIFF function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/IfNullFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformArithmeticFunctionsProcessor.java
Fixes #10959 
Add one function classe: IfNullFunction . Also, add the corresponding unit test codes.
*(example:)*
=> [INLONG-10959][SDK] Transform support IFNULL function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/JsonSourceData.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/JsonSourceDecoder.java
Fixes #10957
- Improve some if-else structure.
- Some childRoot is always null, replace them with null.
*(example:)*
=> [INLONG-10957][SDK] Improve some code structures

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/datatype/KvDataTypeOperator.java
Fixes #10977 
Data preview supports escaping for KV data type.
Data preview supports escaping for KV data type.
=> [INLONG-10977][Manager] Data preview supports escaping for KV data type

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/DateExtractFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/FromUnixTimeFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/SubstringFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TimestampAddFunction.java
Fixes #10942 
Added official SQL functions for DateExtractFunction, FromUnixTimeFunction, SubstringFunction, and TimestampAdFunction classes
*(example:)*
=> [INLONG-10942][SDK] Add official function names for all Transform functions

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/tubemq/TubeMQOperator.java
Fixes #10988
Data preview filters data in tubes based on streamId.
Add stream filtering criteria when querying tube data.
=> [INLONG-10988][Manager] Data preview filters data in tubes based on streamId

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RadiansFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformArithmeticFunctionsProcessor.java
Fixes #10984 
add Radiansfunction class and provide unit test
*(example:)*
=> [INLONG-10984][SDK] Transform support RADIANS(x) function

inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformProcessor.java
Fixes #10982
To improve usability, I have modified the getFieldList function in TestTransformProcess.java.
The function can get some parameters to return diffirent FieldList now.
*(example:)*
=> [INLONG-10982][SDK] Improve the test code structure

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/PiFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformArithmeticFunctionsProcessor.java
Fixes #10979 
add PiFunction and provide unit test
*(example:)*
=> [INLONG-10979][SDK] Transform support PI() function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/InsertFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformStringFunctionsProcessor.java
Fixes #10971
- INSERT(str, pos, len, newstr)
- Returns the string str, with the substring beginning at position pos and len characters long replaced by the string newstr.
- Returns the original string if pos is not within the length of the string.
- Replaces the rest of the string from position pos if len is not within the length of the rest of the string. 
- Returns NULL if any argument is NULL.
- This function is the same as in mysql.
- INSERT('12345678', 3, 4, 'word') = '12word78'
- INSERT('12345678', -1, 4, 'word') = '12345678'
- INSERT('12345678', 3, 100, 'word') = '12word'
*(example:)*
- *Extended integration test for recovery …
=> [INLONG-10971][SDK] Transform support INSERT function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/BitwiseAndParser.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/BitwiseLeftShiftParser.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/BitwiseOrParser.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/BitwiseRightShiftParser.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/BitwiseXorParser.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformArithmeticFunctionsProcessor.java
Fixes #10965 
Add five function classes: BitwiseAndParser, BitwiseRightShiftParser, BitwiseLeftShiftParser, BitwiseXorParser, BitwiseOrParser. Modified SignParser class Also, add the corresponding unit test codes.
*(example:)*
=> [INLONG-10965][SDK] Transform support Bitwise operation

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/AndOperator.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/EqualsToOperator.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/GreaterThanEqualsOperator.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/GreaterThanOperator.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/MinorThanEqualsOperator.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/MinorThanOperator.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/NotEqualsToOperator.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OrOperator.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/ParenthesisOperator.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/TransformOperator.java
Fixes #10968 
Implement annotation support for operator and refactor the OperatorTools.class，Reference was made to the implementation of https://github.com/apache/inlong/issues/10929
*(example:)*
=> [INLONG-10968][SDK] Support Inlong Transform operator annotation

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/Sha2Function.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ShaFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformArithmeticFunctionsProcessor.java
Fixes #10956 
Add two function classes: ShaFunction, Sha2Function. Also, add the corresponding unit test codes.
*(example:)*
=> [INLONG-10956][SDK] Transform SQL supports SHA encryption algorithm

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java
Fixes #10997
Fix the problem of incorrect setting of transformSQL in dataflowconfig.
Fix the problem of incorrect setting of transformSQL in dataflowconfig.
=> [INLONG-10997][Manager] Fix the problem of incorrect setting of transformSQL in dataflowconfig

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ContainsFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformStringFunctionsProcessor.java
Fixes #10963
add CONTAINS function.
=> [INLONG-10963][SDK] Transform SQL support CONTAINS function.

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/FromBase64Function.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformFromBase64FunctionProcessor.java
Fixes #10893 
Add a function class: FromBase64Function and its unit test.
- from_base64(string)： Returns the base64-decoded result from string; returns NULL if string is NULL.
*(example:)*
=> [INLONG-10893][SDK] Transform SQL support FromBase64 function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ChrFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestChrFunctionProcessor.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestTransformChrFunctionProcessor.java
Fixes #10995
Add a function class: ChrFunction and its unit test.
- chr(number)： Returns the ASCII character having the binary equivalent to integer.
*(example:)*
=> [INLONG-10995][SDK] Transform SQL support Chr function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/BetweenAndOperator.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestBetweenAndOperator.java
Fixes #10867
Add one BetweenOperator class  and test function class to support BETWEEN AND operator.
- x BETWEEN n AND m
Check whether x within n and m.
*(example:)*
=> [INLONG-10867][SDK] Transform support BETWEEN AND operator

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/UuidFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestUuidFunction.java
Fixes #11034 
add UuidFunction class and provide unit test
*(example:)*
=> [INLONG-11034][SDK] Transform support UUID() function

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaProducerCluster.java
=> [INLONG-11068][Sort] Optimize kafka producer parameters

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/EFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestEFunction.java
Fixes #11057 
add EFunction class and provide unit tests
*(example:)*
=> [INLONG-11057][SDK] Transform support E() function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ParseUrlFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/TestParseUrlFunctionProcessor.java
Fixes #11022 
Add a function class: ParseUrlFunction and its unit test.
- parse_url(string1, string2[, string3]):  Returns the specified part from the URL. Valid values for string2 include ‘HOST’, ‘PATH’, ‘QUERY’, ‘REF’, ‘PROTOCOL’, ‘AUTHORITY’, ‘FILE’, and ‘USERINFO’. Returns NULL if any of arguments is NULL.
Also a value of a particular key in QUERY can be extracted by providing the key as the third argument string3.
*(example:)* …
=> [INLONG-11022][SDK] Transform SQL support ParseUrl function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/SoundexFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestSoundexFunction.java
Transform SQL support soundex function: #10900
*(example:)*
=> [INLONG-10900][SDK] Transform SQL support soundex function

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsChannelWorker.java
=> [INLONG-11072][Sort] Optimize EsSink when transform processor is null

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/TransformProcessor.java
=> [INLONG-11074][Sort] Transform support dummy select when the transform sql is empty

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaProducerCluster.java
=> [INLONG-11076][Sort] Discard unretryable data when send kafka failed

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TruncateFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestTruncateFunction.java
Fixes #11035 
add TruncateFunction class and provide unit test
*(example:)*
=> [INLONG-11035][SDK] Transform support TRUNCATE() function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/DecodeFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/EncodeFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestDecodeFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestEncodeFunction.java
Fixes #11037 
add DecodeFunction class and EncodeFunction class, provide unit tests
*(example:)*
=> [INLONG-11037][SDK] Transform support ENCODE() and DECODE() function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/NullIfFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/flowcontrol/TestNullIfFunction.java
Fixes #11064 
Add one function classe: NullIfFunction. Also, add the corresponding unit test classe: TestNullIfFunction, TestUnCompressFunction.
*(example:)*
=> [INLONG-11064][SDK] Transform SQL supports NULLIF function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/TransformProcessor.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TranslateFunction.java
=> [INLONG-11087][SDK] Fix potential null pointer exception of transform SDK

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/PrintfFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestPrintfFunction.java
Fixes #11008 
Add one function class : PrintfFunction , and its unit test.
*(example:)*
=> [INLONG-11008][SDK] Transform SQL support PRINTF function.

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FilterFunctionUtils.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/TransformDefinition.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/transform/filter/FilterDefinition.java, inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/transform/TransformDefinitionTest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
Fixes #11091
Manager supports in filter function configuration.
Added `in` operator.
=> [INLONG-11091][Manager] Manager supports in filter function configuration

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/stream/QueryMessageRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/datatype/CsvDataTypeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/datatype/KvDataTypeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarOperator.java
Fixes #11095
Fix the problem of data preview field misalignment.
Fix the problem of data preview field misalignment.
=> [INLONG-11095][Manager] Fix the problem of data preview field misalignment

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/CsvSourceDecoder.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/MapSinkEncoder.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/TransformProcessor.java
=> [INLONG-11097][SDK] Optimize logs of the transform SDK

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/channel/BufferQueueChannel.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsChannelWorker.java
=> [INLONG-11100][Sort] The buffer queue is not released after sending messages to elasticsearch

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/FunctionTools.java
Fixes #11092 
Modified the FunctionalTools class.
*(example:)*
=> [INLONG-11092][SDK] Fix the issue of inconsistent capitalization of Function names in FunctionalTools

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileDataAddTaskRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSource.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/file/FileSourceRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/file/FileSourceOperator.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSourceController.java
Fixes #11103
Data add task supports filtering based on stream.
Data add task supports filtering based on stream.
=> [INLONG-11103][Manager] Data add task supports filtering based on stream

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TruncateFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestTruncateFunction.java
Fixes #11112 
add name of TRUNCATE() function and provide tests
*(example:)*
=> [INLONG-11112][SDK] Transform TRUNCATE() function add pgsql name

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/IsNullFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/flowcontrol/TestIsNullFunction.java
Fixes #11117 
Add one function class: IsNullFunction. Also, add the corresponding unit test classe: TestIsNullFunction.
*(example:)*
=> [INLONG-11117][SDK] Transform SQL supports ISNULL functions

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/Sha2Function.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ShaFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/OperatorTools.java
Fixes #11125 
* add method in OperatorTools.class
* supports value parse to byte[]
* improve related function
*(example:)*
=> [INLONG-11125][SDK] Transform OperatorTools support parseBytes

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/DecodeFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/EncodeFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestDecodeFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestEncodeFunction.java
Fixes #11124 
* encode() function return byte[] type but not a string
* decode() function parse the byte[] into a string
* update unit tests
*(example:)*
=> [INLONG-11124][SDK] Transform fix ENCODE() and DECODE() function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/GcdFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestGcdFunction.java
Fixes #11121 
Add one function class: GcdFunction. Also, add the corresponding unit test classe: TestGcdFunction.
*(example:)*
=> [INLONG-11121][SDK] Transform SQL supports gcd functions

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/StreamSourceEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/StreamSourceEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/file/FileSourceOperator.java
Fixes #11142 
Fix the problem of data add task not scheduled for cleaning.
Fix the problem of data add task not scheduled for cleaning.
=> [INLONG-11142][Manager] Fix the problem of data add task not scheduled for cleaning

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/AcosdFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/AsindFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/Atan2dFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/AtandFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/CosdFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/CotdFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/SindFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TandFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestAcosdFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestAsindFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestAtan2dFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestAtandFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestCosdFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestCotdFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestSindFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestTandFunction.java
Fixes #11114 
add acosd, asind, atand, atan2d, cosd, cotd, sind, tand functions classes and provide unit tests
*(example:)*
=> [INLONG-11114][SDK] Transform support Trigonometric function in units of degrees

inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/parser/TestAdditionParser.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/parser/TestSubtractionParser.java
=> [INLONG-11161][SDK] Fix TransformSDK UT bug of TestAdditionParser and TestSubtractionParser

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/AbstractStandaloneSinkResourceOperator.java
Fixes #11150
Fix the problem of incorrect setting of sorTaskName for sink.
Fix the problem of incorrect setting of sorTaskName for sink.
=> [INLONG-11150][Manager] Fix the problem of incorrect setting of sorTaskName for sink

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RadixConvertFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/testRadixConvertFunction.java
Fixes #11123 
Add one function class: ConvFunction. Also, add the corresponding unit test classe: TestConvFunction.
*(example:)*
=> [INLONG-11123][SDK] Transform SQL supports conv function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/AvroSourceData.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/AbstractProcessorTestBase.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/TestAvro2CsvProcessor.java
Fixes #11107
Avro Source Data Support Map Type
Modified Avro Test Data: Add some map data.
*(example:)*
=> [INLONG-11107][SDK] Avro Source Data Support Map Type

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RegexpCountFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RegexpExtractAllFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RegexpExtractFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RegexpFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RegexpInstrFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RegexpReplaceFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RegexpSubstrFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestRegexExtractFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestRegexpCountFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestRegexpExtractAllFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestRegexpFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestRegexpInstrFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestRegexpReplaceFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestRegexpSubstrFunction.java
Fixes #11060 
add 7 function class mentioned in issue #11060 and provide unit tests
*(example:)*
=> [INLONG-11060][SDK] Transform support REGEXP_...() related functions

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/SourceDecoderFactory.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/YamlNode.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/YamlSourceData.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/YamlSourceDecoder.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/YamlSourceInfo.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/TestYaml2CsvProcessor.java
Fixes #11005 
add YamlSourceData, YamlSourceDecoder, YamlSourceInfo, provide unit tests
*(example:)*
=> [INLONG-11005][SDK] Add YAML formatted data source for Transform

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/file/FileSourceOperator.java
Fixes #11163
Fix the problem of adding dataaddtask failed.
Fix the problem of adding dataaddtask failed.
=> [INLONG-11163][Manager] Fix the problem of adding dataaddtask failed

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/NodeStatus.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongClusterNodeEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterNodeEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/AgentClusterNodeInstallOperator.java
Fixes #11157
Asynchronous processing agent installation.
Asynchronous processing agent installation.
=> [INLONG-11157][Manager] Asynchronous processing agent installation

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/file/ProxyMessage.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/message/file/ProxyMessageCache.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
Fixes #11179 
Delete useless code
Delete useless code
*(example:)*
No doc needed
=> [INLONG-11179][Agent] Delete useless code

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RegexpSplitToArrayFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestRegexpSplitToArrayFunction.java
Fixes #11168 
add RegexpSplitToArrayFunction and provide unit tests
*(example:)*
=> [INLONG-11168][SDK] Transform support REGEXP_SPLIT_TO_ARRAY() function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/RegexpFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestRegexpFunction.java
Fixes #11167 
add function name of `regexp_like`, provide unit tests
*(example:)*
=> [INLONG-11167][SDK] Transform REGEXP function add usage of regexp_like

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TimestampDiffFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/temporal/TestTimestampDiffFunction.java
Fixes #11152 
Add one function class: TimestampDiffFunction. Also, add the corresponding unit test classe: TestTimestampDiffFunction.
*(example:)*
=> [INLONG-11152][SDK] Transform SQL supports TIMESTAMPDIFF function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TranslateFunction.java
=> [INLONG-11190][SDK] Optimize Transform SDK Translate Function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/CaseParser.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/flowcontrol/TestCaseFunction.java
Fixes #11147
- Add CaseParser class and its test cases
- Mysql doc: https://dev.mysql.com/doc/refman/8.0/en/flow-control-functions.html#operator_case
-  CASE value WHEN compare_value THEN result [WHEN compare_value THEN result ...] [ELSE result] END
-  CASE WHEN condition THEN result [WHEN condition THEN result ...] [ELSE result] END
The first CASE syntax returns the result for the first value=compare_value comparison that is true. The second syntax returns the result for the first condition that is true. If no comparison or condition is true, the result after ELSE is returned, or NULL if there is no ELSE part.
*(example:)*
- *Extended …
=> [INLONG-11147][SDK] Transform support CASE Operator

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TimestampFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/utils/DateUtil.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/temporal/TestTimestampFunction.java
Fixes #11154 
Add one function class: TimestampFunction. Also, add the corresponding unit test classe: TestTimestampFunction. Modified DateUtil to support more features
*(example:)*
=> [INLONG-11154][SDK] Transform SQL supports TIMESTAMP function

.github/workflows/ci_build.yml, .github/workflows/ci_docker.yml, .github/workflows/ci_ut.yml, .github/workflows/ci_ut_flink13.yml, .github/workflows/ci_ut_flink15.yml, .github/workflows/ci_ut_flink18.yml, .github/workflows/codeql_analysis.yml
Fixes #11249 
fix the ci fail due to lack of disk space
add disk step in github action 
=> [INLONG-11249][CI] Fix the ci fail due to lack of disk space

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/CbrtFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestCbrtFunction.java
Fixes #11261 
Add one function class: CbrtFunction. Also, add the corresponding unit test classe: TestCbrtFunction.
*(example:)*
=> [INLONG-11261][SDK] Transform SQL supports "cbrt" function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/SubstringFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestSubstringFunction.java
Fixes #11243 
Modified SubstringFunction class and added relevant test cases.
*(example:)*
=> [INLONG-11243][SDK] Enhance the functionality of the substring function in Transform SQL

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/MapFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestMapFunction.java
Fixes #11242 
add MapFunction.java, provide unit tests
*(example:)*
=> [INLONG-11242][SDK] Transform support MAP() function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ArrayFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestArrayFunction.java
Fixes #11241 
add ArrayFunction.java , provide unit tests
*(example:)*
=> [INLONG-11241][SDK] Transform support ARRAY() function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/JsonArraysFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestJsonArraysFunction.java
Fixes #11225 
add JsonArrays.java, provide unit tests
*(example:)*
=> [INLONG-11225][SDK] Transform support JSON_ARRAY() function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/operator/DistinctOperator.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/operator/TestDistinctOperator.java
Fixes #11226 
add DistinctOperator.java to support parse ability of IS DISTINCT FROM and IS NOT DISTINCT FROM, provide unit tests
*(example:)*
=> [INLONG-11226][SDK] Transform support parse IS DISTINCT FROM

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/FormatFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestFormatFunction.java
Fixes #11238 
Add one function class: FormatFunction. Also, add the corresponding unit test classe: TestFormatFunction.
*(example:)*
=> [INLONG-11238][SDK] Transform SQL supports FORMAT function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/JsonQueryFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestJsonQueryFunction.java
Fixes #11224 
add JsonQueryFunction.java , provide unit tests
*(example:)*
=> [INLONG-11224][SDK] Transform support JSON_QUERY() function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/JsonValueFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestJsonValueFunction.java
Fixes #11223 
add JsonValueFunction.java, provide unit tests
*(example:)*
=> [INLONG-11223][SDK] Transform support JSON_VALUE() function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/LocateFunction.java
=> [INLONG-11239][SDK] Transform SQL supports INSTR function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/GreatestFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/LeastFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/AbstractFunctionArithmeticTestBase.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestGreatestFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestLeastFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/operator/TestIsBooleanOperator.java
Fixes #11220 
add GreatestFunction.java and LeastFunction.java , provide unit tests
*(example:)*
=> [INLONG-11220][SDK] Transform support GREATEST() and LEAST() function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/CoalesceFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestCoalesceFunction.java
Fixes #11219 
add CoalesceFunction.java , provide unit tests
*(example:)*
=> [INLONG-11219][SDK] Transform support COALESCE() function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/ConvertTzFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/temporal/TestConvertTzFunction.java
Fixes #11218
add ConvertTzFunction.java, provide unit tests
*(example:)*
=> [INLONG-11218][SDK] Transform support CONVERT_TZ() function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/JsonQuoteFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/JsonUnQuoteFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestJsonQuoteFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestJsonUnQuoteFunction.java
Fixes #11217 
add JsonQuoteFucntion.java and JsonUnQuote.java , provide unit tests
*(example:)*
=> [INLONG-11217][SDK] Transform support JSON_QUOTE() and JSON_UNQUOTE() function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TrimFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestTrimFunction.java
Fixes #11209 
add usage of `btrim` , provide unit tests
*(example:)*
=> [INLONG-11209][SDK] Transform TRIM() function add usage of BTRIM()

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/StrToMapFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestStrToMapFunction.java
Fixes #11216
add StrToMapFucntion.class and provide unit tests
*(example:)*
=> [INLONG-11216][SDK] Transform support STR_TO_MAP() function

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/SinkType.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/http/HttpResourceOperator.java
Fixes #11153
Fix the problem of HTTP sink does not automatically allocate sort cluster.
Fix the problem of HTTP sink does not automatically allocate sort cluster.
=> [INLONG-11153][Manager] Fix the problem of HTTP sink does not automatically allocate sort cluster

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/DivisionParser.java
Fixes #11214 
Modify the code of DivisionParser.
*(example:)*
=> [INLONG-11214][SDK] Modify the problem of incomplete division in DivisionParser

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/LcmFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/arithmetic/TestLcmFunction.java
Fixes #11263 
Add one function class: LcmFunction. Also, add the corresponding unit test classe: TestLcmFunction.
*(example:)*
=> [INLONG-11263][SDK] Transform SQL supports "lcm" function

inlong-dashboard/src/ui/pages/Clusters/NodeEditModal.tsx
Fixes #11204 
agent node hidden port number
agent node hidden port number
before：
after：
=> [INLONG-11204][Dashboard] Agent node hidden port number

inlong-sdk/transform-sdk/pom.xml, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/SourceDecoderFactory.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/XmlNode.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/XmlSourceData.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/XmlSourceDecoder.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/XmlSourceInfo.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/TestXml2CsvProcessor.java
Fixes #11000 
Add several classes: XmlSourceInfo, XmlNode, XmlSourceData, XmlSourceDecoder. Modified SourceDecoderFactory class. Also, add the corresponding unit test codes.
*(example:)*
=> [INLONG-11000][SDK] Add XML formatted data source for Transform

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TimeDiffFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/temporal/TestTimeDiffFunction.java
Fixes #11192 
Add one function class: TimeDiffFunction. Also, add the corresponding unit test classe: TestTimeDiffFunction. 
*(example:)*
=> [INLONG-11192][SDK] Transform SQL supports TIMEDIFF function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/DateAddFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/DateDiffFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/DateSubFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TimestampAddFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/TimestampDiffFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/AdditionParser.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/IntervalParser.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/parser/SubtractionParser.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/pojo/IntervalInfo.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/utils/DateUtil.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/temporal/TestTimestampAddFunction.java
Fixes #11202 
Optimized some functions related to time and fixed the bug of TimestampAddFunction.
*(example:)*
=> [INLONG-11202][SDK] Optimize the code related to the date type in Transform

inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/ConfigConstants.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/config/SqlConstants.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/entities/PartitionEntity.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/entities/SourceConfig.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/main/Application.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/EtlService.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/PartitionManager.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/sink/AuditSink.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/sink/CacheSink.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/sink/JdbcSink.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/source/JdbcSource.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/utils/JdbcUtils.java, inlong-audit/sql/apache_inlong_audit_mysql.sql
- Fixes #11286
Optimize the statistics of daily audit granularity to reduce the query of real-time data warehouse
Optimize the statistics of daily Audit data
=> [INLONG-11286][Audit] Optimize the statistics of daily Audit data

inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/DataProxyNodeInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/dataproxy/DataProxyClusterDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/dataproxy/DataProxyClusterInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/cluster/dataproxy/DataProxyClusterRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
Fixes #11313
Dataproxy cluster add maximum packet length configuration.
Dataproxy cluster add maximum packet length configuration.
=> [INLONG-11313][Manager] Dataproxy cluster add maximum packet length configuration

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/MapEntriesFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/MapFromArraysFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/MapKeysFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/MapUnionFunction.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/MapValueFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestMapEntriesFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestMapFromArraysFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestMapKeysFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestMapUnionFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestMapValuesFunction.java
Fixes #11283 
add function classes referenced in issue, provide unit tests for each class
*(example:)*
=> [INLONG-11283][SDK]Transform enhance Map-related Collection Functions

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/JsonArrayAppendFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestJsonArrayAppendFunction.java
Fixes #11300 
Add the JsonArrayAppendFunction class and enhance the corresponding test class: TestJsonArrayAppendFunction.
*(example:)*
=> [INLONG-11300][SDK] Transform SQL supports "JSON_ARRAY_APPEND" function

.github/workflows/ci_build.yml, .github/workflows/ci_ut.yml, .github/workflows/ci_ut_flink13.yml, .github/workflows/ci_ut_flink15.yml, .github/workflows/ci_ut_flink18.yml, .github/workflows/codeql_analysis.yml
Fixes #11321
Fix workflow failure when removing unnecessary packages
improve package remove logic
=> [INLONG-11321][CI] Fix workflow failure when removing unnecessary packages

.github/ISSUE_TEMPLATE/bug-report.yml
Fixes #11291 
Add the 2.0.0 version option for the bug report
Add the 2.0.0 version option for the bug report
=> [INLONG-11291][Release] Add the 2.0.0 version option for the bug report

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditReporterImpl.java, inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/util/Config.java
- Fixes #11330
Audit SDK supports custom setting of local IP
Audit SDK provides an API that can set the local IP
=> [INLONG-11330][Audit] Audit SDK supports custom setting of local IP

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/EltFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/string/TestEltFunction.java
Fixes #11229
Add a function class and its test case;
- ELT(index, expr[, exprs]*) 
Returns the index-th expression. index must be an integer between 1 and the number of expressions.
Retuens NULL if index is NULL or out of range.
*(example:)*
=> [INLONG-11229][SDK] Transform Support ELT Function

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/DataAddTaskRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSourceController.java
Fixes #11323
Modify the parameters of the data add tasks for file collection.
1.Modify the parameters of the data add tasks for file collection, add data add tasks  based on agent IP.
2.When all data source tasks are deleted, the agent configuration is not deleted, but is processed when the cluster is deleted.
=> [INLONG-11323][Manager] Modify the parameters of the data add tasks for file collection

inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/DataProxyNodeInfo.java, inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/DataProxyNodeResponse.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
Fixes #11335
Move maxPacketLength to the DataProxyNodeResponse.
Move maxPacketLength to the DataProxyNodeResponse.
=> [INLONG-11335][Manager] Move maxPacketLength to the DataProxyNodeResponse

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ClientMgr.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/Sender.java
- Fixes #11325  
DataProxy SDK supports elegant metadata updates
The details can be found at [#11325 ](https://github.com/apache/inlong/issues/11325).
=> [INLONG-11325][SDK] DataProxy SDK supports elegant metadata updates

CHANGES.md
Fixes #11292 
Update changes log for the 2.0.0 version
Update changes log for the 2.0.0 version
=> [INLONG-11292][Release] Update changes log for the 2.0.0 version

inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/file/ConfigManager.java, inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/metric/AbstractMetric.java, inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/config/ConfigConstants.java, inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/metric/MetricDimension.java, inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/metric/MetricItem.java, inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/metric/MetricsManager.java, inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/metric/prometheus/ProxyPrometheusMetric.java, inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/node/Application.java, inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/sink/KafkaSink.java, inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/sink/PulsarSink.java, inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/sink/TubeSink.java, inlong-audit/audit-proxy/src/main/java/org/apache/inlong/audit/source/ServerMessageHandler.java, inlong-audit/conf/application.properties
- Fixes #11320
Add a metric monitoring system for the Audit Proxy itself
Add a metric monitoring system for the Audit Proxy itself by configuring the monitoring system through plug-ins
=> [INLONG-11320][Audit] Add a metric monitoring system for the Audit Proxy itself

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/json/JsonInsertFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/json/TestJsonInsertFunction.java
Fixes #11302
Add JsonInsertFunction.java and its test class TestJsonInsertFunction.
*(example:)*
=> [INLONG-11302][SDK] Transform SQL supports "JSON_INSERT" function

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/json/JsonReplaceFunction.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/function/json/TestJsonReplaceFunction.java
Fixes #11304
Add JsonReplaceFunction.java and its test class testJsonReplaceFunction.java.
*(example:)*
=> [INLONG-11304][SDK] Transform SQL supports "JSON_REPLACE" function

inlong-manager/manager-dao/src/main/resources/mappers/ComponentHeartbeatEntityMapper.xml
Fixes #11361
Support querying heartbeat information based on IP address.
Support querying heartbeat information based on IP address.
=> [INLONG-11361][Manager] Support querying heartbeat information based on IP address

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/datatype/CsvDataTypeOperator.java
Fixes #11366
Fix the problem of data preview error handling line delimiter.
Fix the problem of data preview error handling line delimiter.
=> [INLONG-11366][Manager] Fix the problem of data preview error handling line delimiter

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/GroupCheckService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/StreamSourceServiceImpl.java
Fixes #11368
Determine whether to issue a streamSource based on the stream status.
Determine whether to issue a streamSource based on the stream status。
=> [INLONG-11368][Manager] Issue a StreamSource based on the stream status

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/process/function/temporal/LocalTimeFunction.java
Fixes #11372
LocalTimeFunctionTest will fail when the time is at an extra minute (seconds=0)，this PR fix the bug.
Add formatter in LocalTimeFunction.java
*(example:)*
=> [INLONG-11372][SDK] Fix LocalTimeFunctionTest may fail in some situation

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java
Fixes #11375
Add a restriction that an IP can only belong to one cluster.
Add a restriction that an IP can only belong to one cluster.
=> [INLONG-11375][Manager] Add a restriction that an IP can only belong to one cluster

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/oceanbase/OceanBaseJdbcUtils.java
Fixes #11377
Add verification for oceanusBase URL.
Add verification for oceanusBase URL.
=> [INLONG-11377][Manager] Add verification for oceanusBase URL

inlong-dashboard/src/plugins/sinks/defaults/Redis.ts, inlong-dashboard/src/ui/pages/GroupDetail/DataStorage/DetailModal.tsx
Fixes #11379 
Redis sink Properties saving problem
Redis sink Properties saving problem
before:
after:
=> [INLONG-11379][Dashboard] Redis sink Properties saving problem

inlong-manager/manager-dao/src/main/resources/mappers/InlongClusterNodeEntityMapper.xml, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/heartbeat/HeartbeatManager.java
Fixes #11387
Support multi-threaded processing agent installation.
Support multi-threaded processing agent installation.
=> [INLONG-11387][Manager] Support multi-threaded processing agent installation

inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/entities/AuditCycle.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/metric/MetricsManager.java
- Fixes #11393
Optimize indicator statistics key for Audit Service
Optimize indicator statistics key for Audit Service
=> [INLONG-11393][Audit] Optimize indicator statistics key for Audit Service

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/AgentClusterNodeInstallOperator.java
Fixes #11389
Installation log display operation time.
Installation log display operation time.
=> [INLONG-11389][Manager] Installation log display operation time

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/InlongGroupClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/InlongGroupApi.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenStreamSourceController.java
Fixes #11391
Add openAPI for adding data add tasks.
Add openAPI for adding data add tasks.
=> [INLONG-11391][Manager] Add openAPI for adding data add tasks

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/AgentClusterNodeInstallOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cmd/CommandExecutor.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cmd/CommandExecutorImpl.java, inlong-manager/manager-web/src/main/resources/application-dev.properties
Fixes #11397
Support copy modules.json when installer reinstall.
Support copy modules.json when installer reinstall.
=> [INLONG-11397][Manager] Support copy modules.json when installer reinstall

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/node/AgentClusterNodeInstallOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cmd/CommandExecutor.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cmd/CommandExecutorImpl.java
Fixes #11402
Download the installer to a temporary directory.
Download the installer to a temporary directory.
=> [INLONG-11402][Manager] Download the installer to a temporary directory

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/util/AuditManagerUtils.java
- Fixes #11404
Optimize the Audit item in the dashboard display
Optimize the Audit item in the dashboard display by excluding some uncommon scenarios
=> [INLONG-11404][Audit] Optimize the Audit item in the dashboard display

inlong-audit/audit-common/src/main/java/org/apache/inlong/audit/utils/NamedThreadFactory.java, inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditReporterImpl.java, inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/ProxyManager.java, inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderManager.java
- Fixes #11406
Provides an interface for asynchronously flushing Audit data
Provides an interface for asynchronously flushing Audit data and  added some logs for troubleshooting
=> [INLONG-11406][Audit] Provides an interface for asynchronously flushing Audit data

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/enums/OperationTarget.java, inlong-manager/manager-dao/src/main/resources/mappers/OperationLogEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/operationLog/OperationLogRequest.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongClusterController.java
Fixes #11415
Support querying cluster node operation records.
Support querying cluster node operation records.
=> [INLONG-11415][Manager] Support querying cluster node operation records

inlong-dashboard/src/ui/pages/GroupDetail/DataStream/PreviewModal.tsx
Fixes #11425 
Data synchronization corrects the display problem of uncommitted data
Data synchronization corrects the display problem of uncommitted data
before:
after:
=> [INLONG-11425][Dashboard] Data synchronization corrects the display problem of uncommitted data

inlong-dashboard/src/ui/components/Layout/NavWidget/PasswordModal.tsx, inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json
Fixes #11429
Modify password to support uppercase letters
Modify password to support uppercase letters
before：
afafter：
=> [INLONG-11429][Dashboard]  Modify password to support uppercase letters

inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json, inlong-dashboard/src/ui/pages/Process/Applies/config.tsx
Fixes #11431
Add copy approval link to my application page
Add copy approval link to my application page
before:
after:
=> [INLONG-11431][Dashboard] Add copy approval link to my application page

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/send/SenderManager.java
- Fixes #11442
Optimize the exception log of Audit SDK
Optimize the exception log of Audit SDK
=> [INLONG-11442][Audit] Optimize the exception log of Audit SDK

inlong-dashboard/src/plugins/sources/common/SourceDefaultInfo.ts, inlong-dashboard/src/plugins/sources/defaults/File.ts, inlong-dashboard/src/plugins/sources/defaults/Kafka.ts, inlong-dashboard/src/plugins/sources/defaults/Mongodb.ts, inlong-dashboard/src/plugins/sources/defaults/PostgreSQL.ts, inlong-dashboard/src/plugins/sources/defaults/Pulsar.ts, inlong-dashboard/src/ui/pages/GroupDetail/DataSources/DetailModal.tsx, inlong-dashboard/src/ui/pages/GroupDetail/OperationLog/config.tsx, inlong-dashboard/src/ui/pages/ModuleAudit/IpModule/index.tsx
Fixes #11441 
Add ClusterTag filtering conditions to the cluster interface
Add ClusterTag filtering conditions to the cluster interface
before:
after：
=> [INLONG-11441][Dashboard] Add ClusterTag filtering conditions to the cluster interface

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ClientMgr.java
Fixes #11453
Get the minimum value of listData or listHB collection
=> [INLONG-11453][SDK] notifyHBControl function array out of bounds

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/MetricConfig.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/Sender.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/threads/MetricWorkerThread.java
Fixes #11459
1. add MetricConfig  class
=> [INLONG-11459][SDK] Add MetricConfig class to save metric-related settings

inlong-sdk/transform-sdk/pom.xml, inlong-sort-standalone/pom.xml, inlong-sort/sort-core/pom.xml, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/hbase/pom.xml, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/jdbc/pom.xml, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/hbase/pom.xml, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/iceberg/pom.xml, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/jdbc/pom.xml
Fixes #11471 
Exclude useless artifact in hadoop-common
Exclude useless artifact in hadoop-common
=> [INLONG-11471][CI] Exclude useless artifact in hadoop-common

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/ScheduleEntity.java, inlong-manager/manager-dao/src/main/resources/mappers/ScheduleEntityMapper.xml, inlong-manager/manager-dao/src/test/java/org/apache/inlong/manager/dao/mapper/ScheduleEntityTest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/schedule/ScheduleInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/schedule/ScheduleInfoRequest.java, inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/ScheduleClientFactory.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/schedule/ScheduleOperatorImpl.java, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-2.1.0.sql
Fixes #11483
Support multiple sceduling engine selection
Support multiple sceduling engine selection
=> [INLONG-11483][Manager] Support multiple scedule engine selection

inlong-dashboard/src/plugins/sources/defaults/File.ts, inlong-dashboard/src/ui/locales/cn.json, inlong-dashboard/src/ui/locales/en.json, inlong-dashboard/src/ui/pages/ModuleAudit/IdModule/index.tsx
Fixes #11496 
File source adds a new judgment on spaces in the file path
File source adds a new judgment on spaces in the file path
before：
after:
=> [INLONG-11496][Dashboard] File source adds a new judgment on spaces in the file path

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/DirtyQueryLogEntity.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/DirtyQueryLogEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/DirtyQueryLogEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/BaseStreamSink.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/DirtyDataDetailResponse.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/DirtyDataRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/DirtyDataResponse.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/DirtyDataTrendDetailResponse.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/DirtyDataTrendRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/SinkRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sink/StreamSink.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/dirtyData/DirtyQueryLogService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/dirtyData/impl/DirtyQueryLogServiceImpl.java, inlong-manager/manager-test/src/main/resources/h2/apache_inlong_manager.sql, inlong-manager/manager-web/sql/apache_inlong_manager.sql, inlong-manager/manager-web/sql/changes-2.1.0.sql, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamSinkController.java, inlong-manager/manager-web/src/main/resources/application-dev.properties, inlong-manager/manager-web/src/main/resources/application-prod.properties, inlong-manager/manager-web/src/main/resources/application-test.properties
Fixes #11508 
Add APIs to dirty data query.
Add APIs to dirty data query.
The dirty data query will have the following process:
1.Submit dirty data query task through `/sink/listDirtyData` and obtain taskid.
2.Retrieve task execution status through `/sink/sqlTaskStatus/{taskId}`.
3.After the task is successfully executed, obtain the dirty data result through` /sink/getDirtyData/{taskId}`.
=> [INLONG-11508][Manager] Add APIs to dirty data query

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java
Fixes #11524 
Save offset before exiting to reduce data duplication
Perform an offset refresh before clearing the offset
*(example:)*
No doc needed
=> [INLONG-11524][Agent] Save offset before exiting to reduce data duplication

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java
Fixes #11522 
Strictly process new instances in the order of submission to facilitate the evaluation of recovery time during data supplementation.
1 Place the newly added instance in a separate queue called addActionQueue without blocking other types of tasks
2 Retrieve instances from addActionQueue in order to execute
*(example:)*
No doc needed
=> [INLONG-11522][Agent]  Strictly process new instances in the order of submission

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/schedule/ScheduleOperatorImpl.java
Fixes #11533 
Enable Manager to use multiple scheduling engines simultaneously.
=> [INLONG-11533][Manager] Enable Manager to use multiple scheduling engines simultaneously

inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/airflow/config/AirflowConfig.java, inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/dolphinscheduler/DolphinScheduleEngine.java, inlong-manager/manager-web/src/main/resources/application-dev.properties, inlong-manager/manager-web/src/main/resources/application-prod.properties, inlong-manager/manager-web/src/main/resources/application-test.properties
Fixes #11535 
modify Schedule engine configs and related classes
*(example:)*
=> [INLONG-11535][Manager] Enhance schedule engine config

inlong-dashboard/src/ui/pages/common/DirtyModal/index.tsx
Fixes #11539 
Dirty data query date format modification
Dirty data query date format modification
before：
after：
=> [INLONG-11539][Dashboard] Dirty data query date format modification

inlong-common/src/main/java/org/apache/inlong/common/pojo/dataproxy/DataProxyNodeResponse.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/codec/ProtocolEncoder.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/UdpClientExample.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/http/InternalHttpSender.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ClientMgr.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/HttpProxySender.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/IpUtils.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/Sender.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/SequentialID.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/pb/context/SinkContext.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/pb/network/IpUtils.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/threads/MetricWorkerThread.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ServiceDiscoveryUtils.java, inlong-sdk/dataproxy-sdk/src/test/java/org/apache/inlong/sdk/dataproxy/ProxyConfigManagerTest.java, inlong-sdk/dataproxy-sdk/src/test/java/org/apache/inlong/sdk/dataproxy/UtilsTest.java, pom.xml
Fixes #11565
1. Rename Utils.java  to IpUtils.java
2.  Remove isBlank() and isNotBlank() functions in IpUtils.java
=> [INLONG-11565][SDK] Optimize the implementation of the Utils.java class

inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/InstanceProfile.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/conf/TaskProfile.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/constant/TaskConstants.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/COSTask.java, inlong-agent/agent-common/src/main/java/org/apache/inlong/agent/pojo/TaskProfileDto.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/file/LogFileTask.java, inlong-common/src/main/java/org/apache/inlong/common/enums/TaskTypeEnum.java
Fixes #11569 
Add COS Task
1. Add COS related macro definitions
2. Add COS type task class
*(example:)*
No doc needed
=> [INLONG-11569][Agent] Add COS Task

inlong-manager/manager-schedule/src/test/resources/airflow/dag_cleaner.py, inlong-manager/manager-schedule/src/test/resources/airflow/dag_creator.py
Fixes #11567
Optimize the original DAGs of Airflow.
*(example:)*
=> [INLONG-11567][Manager] Optimize the original DAG of Airflow

inlong-agent/agent-plugins/pom.xml, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/fetcher/ManagerFetcher.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/COSInstance.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/instance/CommonInstance.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/ProxySink.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/COSSource.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/LogFileSource.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/file/AbstractSource.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/cos/COSTask.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/task/cos/FileScanner.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/cos/COSConfigHandler.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/cos/COSUtils.java, inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/utils/cos/DefaultCOSConfigHandler.java, licenses/inlong-agent/LICENSE, licenses/inlong-agent/licenses/LICENSE-cos-java-sdk.txt, pom.xml
Fixes #11571 
Add classes for actual collection of COS source
1. Add COS Task to generate COS collection instances
2. Add COS Source for collecting actual data from COS
*(example:)*
No doc needed
=> [INLONG-11571][Agent] Add classes for actual collection of COS source

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaIdConfig.java
=> [INLONG-11576][Sort] Support KV separator for kafka sink

inlong-dashboard/src/ui/pages/AgentModule/CreateModal.tsx
Fixes #11577
The Installer Module modify the defaults
The Installer Module modify the defaults
before：
after:
=> [INLONG-11548][Dashboard] The Installer Module modify the default commands

inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/consumer_impl.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/heartbeat.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/remote/remote.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/rpc/master.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/selector/ip_selector.go, inlong-tubemq/tubemq-client-twins/tubemq-client-go/selector/ip_selector_test.go
=> [INLONG-11583][TubeMQ] Go SDK load balance logic not perfect, causing consumption to stop suddenly

inlong-tubemq/tubemq-client-twins/tubemq-client-go/sub/info.go
=> [INLONG-11587][TubeMQ] Go SDK change filter order cause inconsistency error when registering to master

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/util/MySQLSensitiveUrlUtils.java, inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTOTest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/cluster/InlongClusterServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/queue/pulsar/PulsarQueueResourceOperator.java
Fixes #11585
Support JDBC verification under dual write parameters.
Support JDBC verification under dual write parameters.
=> [INLONG-11585][Manager] Support JDBC verification under dual write parameters

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ConfigConstants.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigEntry.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/config/ProxyConfigManager.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/HttpClientExample.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/TcpClientExample.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/ClientMgr.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/HttpProxySender.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/Sender.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/Tuple2.java, inlong-sdk/dataproxy-sdk/src/test/java/org/apache/inlong/sdk/dataproxy/ProxyConfigManagerTest.java, inlong-sdk/dirty-data-sdk/src/main/java/org/apache/inlong/sdk/dirtydata/InlongSdkDirtySender.java
Fixes #11589
1. Adjust the configuration item names and value assignment operations related to configuration management in ProxyClientConfig.java
2. Adjust the implementation logic and related references of ProxyConfigManager.java
3. Other optimization items
=> [INLONG-11589][SDK] Optimize the implementation of proxy configuration management

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/request.go, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/worker.go
=> [INLONG-11601][SDK] Fix data race in Golang SDK

inlong-sdk/transform-sdk/pom.xml, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/RowDataSourceData.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/RowDataSourceDecoder.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/SourceDecoderFactory.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/RowDataSinkEncoder.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/encode/SinkEncoderFactory.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/RowDataSinkInfo.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/RowDataSourceInfo.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/pojo/SinkInfo.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/AbstractProcessorTestBase.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/TestRowData2RowDataProcessor.java
Fixes #11611 
Support Rowdata decode and encode capability
*(example:)*
=> [INLONG-11611][SDK] Transform SDK supports RowData source and sink

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/DataNodeType.java, inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/SourceType.java, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/DataNodeEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/DataNodeEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/cos/COSDataNodeDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/cos/COSDataNodeInfo.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/node/cos/COSDataNodeRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/cos/COSDataAddTaskRequest.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/cos/COSSource.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/cos/COSSourceDTO.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/source/cos/COSSourceRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/DataNodeServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/node/cos/COSDataNodeOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/AbstractSourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/source/cos/COSSourceOperator.java
Fixes #11618 
Support COS stream source.
Support COS stream source.
=> [INLONG-11618][Manager] Support COS stream source

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/Sender.java
Fixes #11629
Strip the thread from the Sender initialization function and put it in the start() function to avoid calling metadata query operations before starting.
=> [INLONG-11629][SDK] Adjust the Sender initialization logic

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java
=> [INLONG-11632][SDK] The manager address was mistakenly truncated

CHANGES.md
Fixes #11637
Update changes log for the 2.1.0 version
Update changes log for the 2.1.0 version
=> [INLONG-11637][Release] Update changes log for the 2.1.0 version

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaProducerCluster.java
=> [INLONG-11658][Sort] Fix the NPE of the Kafka sink error log for some exceptions without metadata information

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/connpool/connpool.go
Fixes #11661 
Do not mark endpoint unavailable when it is the only one in Golang SDK
1. connpool.go
*(example:)*
=> [INLONG-11661][SDK] Do not mark endpoint unavailable when it is the only one in Golang SDK

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/client.go
Fixes #11662 
Enable TCP keep alive for Golang SDK
1. client.go
*(example:)*
=> [INLONG-11662][SDK] Enable TCP keep alive for Golang SDK

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/filecollect/SenderManager.java, inlong-common/src/main/java/org/apache/inlong/common/msg/AttributeConstants.java, inlong-sdk/dataproxy-sdk/pom.xml, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/DefaultMessageSender.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/MessageSender.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/ProxyClientConfig.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/example/HttpClientExample.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/exception/ProxySdkException.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/IpUtils.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/Sender.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/pb/PbProtocolMessageSender.java
Fixes #11670
1. Modify the ProxysdkException class name and location;
2. Add SDK version information acquisition method
3. Add reporting attribute Key "msgUUID" and "sdkVersion"
=> [INLONG-11670][SDK] Rename the ProxysdkException class name to ProxySdkException

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/connpool/connpool.go
Fixes #11660 
Close exist conns if initConns() failed in Golang SDK
1. connpool.go
*(example:)*
=> [INLONG-11660][SDK] Close exist conns if initConns() failed in Golang SDK

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/client.go
Fixes #11663 
Increase the conn pool size for Golang SDK
1. client.go
*(example:)*
=> [INLONG-11663][SDK] Increase the conn pool size for Golang SDK

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/discoverer.go, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/discoverer/dns.go
=> [INLONG-11709][SDK] Delete redundant default case in the discoverer of Golang SDK

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/AgentStatusManager.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/FileStaticManager.java, inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/HeartbeatManager.java
Fixes #11725
1. Replace the Sender used in the agent-core module with TcpMsgSender
=> [INLONG-11725][SDK] Replace the Sender used in the agent-core module with TcpMsgSender

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/util/MySQLSensitiveUrlUtils.java, inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTOTest.java
Fixes #11731
Fix the problem of Sensitive parameters are bypassed during JDBC verification processing.
Fix the problem of Sensitive parameters are bypassed during JDBC verification processing.
=> [INLONG-11731][Manager]Fix the problem of Sensitive parameters are bypassed during JDBC verification processing

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/MetricDataHolder.java
Fixes #11738
When MetricDataHolder exits, output the last metric data to obtain the complete metric data content
=> [INLONG-11738][SDK] Optimize the metric output when MetricDataHolder exits

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/InlongConstants.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/util/MySQLSensitiveUrlUtils.java, inlong-manager/manager-pojo/src/test/java/org/apache/inlong/manager/pojo/sink/mysql/MySQLSinkDTOTest.java
Fixes #11746
Fix the problem of JDBC URL cannot handle special characters.
Fix the problem of JDBC URL cannot handle special characters.
=> [INLONG-11746][Manager] Fix the problem of JDBC URL cannot handle special characters

inlong-dashboard/index.html, inlong-dashboard/src/ui/pages/SynchronizeDashboard/index.tsx, inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/mapper/InlongGroupEntityMapper.java, inlong-manager/manager-dao/src/main/resources/mappers/InlongGroupEntityMapper.xml, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/group/InlongGroupBriefInfo.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/group/InlongGroupServiceImpl.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/InlongGroupController.java
Fixes #11759 
When the user clears the data in the synchronization type selection box, they will erroneously query the data flow group of the ingestion page
This modify improves the user experience
> [!NOTE]
> 1. Before modify:
> <img width="1886" alt="sync_menu_before" src="https://github.com/user-attachments/assets/f99d92ec-82a0-49d5-baf5-e99012309683" />
> 2. Bug:
> <img width="1889" alt="sync_menu_bug" src="https://github.com/user-attachments/assets/f9323852-aa85-4331-b8a8-b8dd8ee572f3" />
> 3. After modify:
> <img width="1893" alt="sync_after" src="https://github.com/user-attachments/assets/8b96f957-f3e3-43a0-bcde-61ee19835c55" />
> 4. Filter query:
> <img width="1906" alt="sync_menu_after2" …
=> [INLONG-11759][Dashboard][Manager] Improve data synchronization page query

inlong-agent/agent-core/src/main/java/org/apache/inlong/agent/core/instance/InstanceManager.java
Fixes #11776 
Optimize the mechanism for controlling the number of instances
Only actions that increase instances need to determine if the task instance is saturated
*(example:)*
No doc needed
=> [INLONG-11776][Agent] Optimize the mechanism for controlling the number of instances

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-cpp/src/group/send_group.cc, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/ParquetSourceData.java, inlong-sort/sort-flink/sort-flink-v1.13/pom.xml, inlong-sort/sort-flink/sort-flink-v1.13/sort-connectors/elasticsearch-base/src/main/java/org/apache/inlong/sort/elasticsearch/table/MultipleElasticsearchSinkFunctionBase.java, pom.xml
=> [INLONG-11770][Sort][SDK] Fix potential Null Pointer Exception

inlong-manager/manager-common/src/main/java/org/apache/inlong/manager/common/consts/SourceType.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/cls/ClsOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/cls/ClsResourceOperator.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/cls/ClsSinkOperator.java
Fixes #11790
1.CLS uses topic id as the unique key.
2.Support modifying the cls topic name.
1.CLS uses topic id as the unique key.
2.Support modifying the cls topic name.
=> [INLONG-11790][Manager] CLS uses topic id as the unique key

inlong-manager/manager-dao/src/main/java/org/apache/inlong/manager/dao/entity/InlongGroupEntity.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sink/StreamSinkServiceImpl.java
Fixes #11792
Support group followers to add sinks.
Support group followers to add sinks.
=> [INLONG-11792][Manager] Support group followers to add sinks

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/node/provider/PulsarProvider.java, inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/extract/PulsarExtractNode.java
Fixes #11794
Pulsar source supports setting scan.startup.mode to null.
Pulsar source supports setting scan.startup.mode to null.
=> [INLONG-11794][Manager] Pulsar source supports setting scan.startup.mode to null

inlong-sort/sort-formats/format-rowdata/format-inlongmsg-rowdata-base/src/main/java/org/apache/inlong/sort/formats/inlongmsg/AbstractInLongMsgFormatDeserializer.java
=> [INLONG-11803][Sort] Solve the NPE problem when parsing InLongMsg

inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/tubemq/src/main/java/org/apache/inlong/sort/tubemq/FlinkTubeMQConsumer.java
=> [INLONG-11805][Sort] Restored Checkpoint Id as part of Tube Connector Session Key

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/tcp/TcpMsgSenderConfig.java
Fixes #11809
Adjust the default value of separateEventByLF to false
=> [INLONG-11809][SDK] Adjust the default value of separateEventByLF to false

inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/CdcExactlyMetric.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/mysql/RowDataDebeziumDeserializeSchema.java
=> [INLONG-11807][Sort] Support exactly metric report in mysql-cdc case

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/AuditIdEnum.java, inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/entity/AuditType.java
- Fixes #11826
Add a new Audit item for MQ Pulsar
Add a new Audit item for MQ Pulsar
=> [INLONG-11826][Audit] Add a new Audit item for MQ Pulsar

inlong-audit/audit-sdk/src/main/java/org/apache/inlong/audit/CdcIdEnum.java
Fixes #11823
Add CDC audit ID for MySQL Binlog.
Add CDC audit ID for MySQL Binlog.
=> [INLONG-11823][Audit] Add CDC audit ID for MySQL Binlog

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/IcebergLoadNode.java
Fixes #11833
Appendmode configuration ignores case.
Appendmode configuration ignores case.
=> [INLONG-11833][Sort] Appendmode configuration ignores case

inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/util/AuditUtils.java, inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/CdcExactlyMetric.java, inlong-sort/sort-flink/base/src/main/java/org/apache/inlong/sort/base/metric/MetricOption.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/mysql/MysqlTableFactory.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/mysql-cdc/src/main/java/org/apache/inlong/sort/mysql/RowDataDebeziumDeserializeSchema.java
Fixes #11829 
1. Use the new changelog audit key to ensure compatibility.
2. Optimize the changelog audit format from string to kv
*(example:)*
=> [INLONG-11829][Sort] Optimize MySQL-CDC changelog audit report

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/SortFlinkConfigOperator.java
Fixes #11838
Add the judgment of whether the cdc audit ID is exist when passing metrics.changelog.audit.key.
Add the judgment of whether the cdc audit ID is exist when passing metrics.changelog.audit.key.
=> [INLONG-11838][Manager] Add the judgment of whether the cdc audit ID is exist when passing metrics.changelog.audit.key

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/client.go, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/message.go
Fixes #11843 
Validate input message of Golang SDK.
Return an error if GroupID/StreamID/Payload is empty.
*(example:)*
=> [INLONG-11843][SDK] Validate input message

inlong-audit/audit-common/pom.xml, inlong-audit/audit-proxy/pom.xml, inlong-audit/audit-service/pom.xml, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/auditor/Audit.java, inlong-audit/audit-service/src/main/java/org/apache/inlong/audit/service/source/JdbcSource.java, inlong-audit/pom.xml, inlong-manager/manager-schedule/pom.xml, inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/airflow/AirflowScheduleEngine.java, inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/airflow/config/AirflowConfig.java, inlong-manager/manager-schedule/src/main/java/org/apache/inlong/manager/schedule/airflow/util/ConcurrentHashSet.java, pom.xml
- Fixes #11831
Optimize the packaging of the Audit SDK.
Reduce the package size of the Audit SDK by adjusting the location of the jar package dependency.
=> [INLONG-11831][Audit] Optimize the packaging of the Audit SDK

.github/ISSUE_TEMPLATE/bug-report.yml
=> [INLONG-11846][Release] Add the 2.2.0 version option for the bug report

CHANGES.md
=> [INLONG-11847][Release] Update changes log for the 2.2.0 version

inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/BaseMsgSenderFactory.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/common/EventInfo.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/MetaSyncInfo.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/MetricDataHolder.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/metric/TimeCostInfo.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/TcpClientMgr.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/codec/DecodeObject.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/network/tcp/codec/EncodeObject.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/sender/tcp/TcpEventInfo.java, inlong-sdk/dataproxy-sdk/src/main/java/org/apache/inlong/sdk/dataproxy/utils/ProxyUtils.java, inlong-sdk/dataproxy-sdk/src/test/java/org/apache/inlong/sdk/dataproxy/ProxyUtilsTest.java
Fixes #11863
1. Implement null checks for both keys and values in event attributes to prevent NullPointerException.
2. Refactor the DecodeObject implementation to handle irregular data formats gracefully, ensuring no uncaught exceptions occur during
3. Add explicit null validation for Map.Entry components:
=> [INLONG-11863][SDK] Enhance Event Attribute Validation and Decoding Logic in SDK

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/util/ip.go
[INLONG-11865][SDK] Optimize the acquisition of local valid IP addresses
Fixes #11865
*(example:)*
=> [INLONG-11865][SDK] Optimize the acquisition of local valid IP addresses

inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/dataproxy/options.go, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/util/id.go, inlong-sdk/dataproxy-sdk-twins/dataproxy-sdk-golang/util/ip.go
[INLONG-11869][SDK]Obtain a valid ip during initialization
Fixes #11869
*(example:)*
=> [INLONG-11869][SDK]Obtain a valid ip during initialization

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/AbstractSourceData.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/AvroSourceData.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/AvroSourceDecoder.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/CsvSourceData.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/CsvSourceDecoder.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/JsonSourceData.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/JsonSourceDecoder.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/KvSourceData.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/KvSourceDecoder.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/ParquetSourceData.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/ParquetSourceDecoder.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/PbSourceData.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/PbSourceDecoder.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/RowDataSourceData.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/RowDataSourceDecoder.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/XmlSourceData.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/XmlSourceDecoder.java, inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/YamlSourceData.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/TestCsv2CsvForErrorOrderProcessor.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/TestCsv2KvProcessor.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/TestJson2CsvProcessor.java, inlong-sdk/transform-sdk/src/test/java/org/apache/inlong/sdk/transform/process/processor/TestKv2CsvProcessor.java
=> [INLONG-11873][SDK] Support parsing field values from extended parameters

inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/inner/client/StreamTransformClient.java, inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/service/StreamTransformApi.java, inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/sort/util/FilterFunctionUtils.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/StreamTransformService.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/StreamTransformServiceImpl.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/transform/TransformSqlParser.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/StreamTransformController.java, inlong-manager/manager-web/src/main/java/org/apache/inlong/manager/web/controller/openapi/OpenStreamTransformController.java
Fixes #11879
Support parsing transform configuration as transform SQL.
Support generating transfomr SQL based on transform configuration.
Support saving transform configuration by synchronizing transform SQL to subscriptions.
=> [INLONG-11879][Manager] Support parsing transform configuration as transform SQL

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sort/DefaultSortConfigOperator.java
Fixes #11881
Sink source field supports configuring the function function.
Sink source field supports configuring the function function.
Use inlongstreamfield for sourcefield in sortstandalone.
=> [INLONG-11881][Manager] Sink source field supports configuring the function

inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/metrics/SortMetricItem.java, inlong-sort-standalone/sort-standalone-source/pom.xml, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsChannelWorker.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsIdConfig.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsSinkContext.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/DefaultEvent2LogItemHandler.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/IEvent2LogItemHandler.java
=> [INLONG-11883][Sort] ​​Sort CLS supports format conversion and data filtering via Transform Functions

inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/v2/SortConfigHolder.java
=> [INLONG-11885][Sort] Unified Metadata supports delayed and phased decommissioning of metadata configurations

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/DefaultEvent2IndexRequestHandler.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsChannelWorker.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsIdConfig.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsSinkContext.java
=> [INLONG-11888][Sort] ​​Sort ElasticSearch supports format conversion and data filtering via Key/Value data format

inlong-manager/manager-pojo/src/main/java/org/apache/inlong/manager/pojo/audit/AuditRequest.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/audit/AuditRunnable.java, inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AuditServiceImpl.java
Fixes #11891
Support querying topic audit information.
Support querying topic audit information.
=> [INLONG-11891][Manager] Support querying topic audit information

inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClient.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/SortClientConfig.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/api/TopicFetcher.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/kafka/KafkaMultiTopicsFetcher.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/kafka/KafkaSingleTopicFetcher.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/pulsar/PulsarMultiTopicsFetcher.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/pulsar/PulsarSingleTopicFetcher.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/fetcher/tube/TubeSingleTopicFetcher.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/SortClientImpl.java, inlong-sdk/sort-sdk/src/main/java/org/apache/inlong/sdk/sort/impl/SortClientImplV2.java, inlong-sort-standalone/sort-standalone-common/src/main/java/org/apache/inlong/sort/standalone/config/holder/CommonPropertiesHolder.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/channel/CacheMessageRecord.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/channel/ProfileEvent.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/elasticsearch/EsCallbackListener.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaProducerCluster.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/source/sortsdk/SortSdkSource.java
=> [INLONG-11892][Sort] SortStandalone support Negative Acknowledgment mechanism for delivery failures

inlong-dashboard/src/ui/pages/GroupDetail/Audit/config.tsx, inlong-dashboard/src/ui/pages/GroupDetail/Audit/index.tsx
…alls to the interface
Fixes #11897 
Clicking the audit page query will call this interface multiple times
Clicking the audit page query will call this interface multiple times
before: Click on the audit page to query multiple calls to the interface
after: Click on the audit page to query once calls to the interface
=> [INLONG-11897][Dashboard] Clicking the audit page query will call this interface multiple times

inlong-sdk/transform-sdk/src/main/java/org/apache/inlong/sdk/transform/decode/KvUtils.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/BaseDecoderBuilder.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/CsvDecoderBuilder.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/DecoderBuilderHolder.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/EventUtils.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/IDecoderBuilder.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/KvDecoderBuilder.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/PbDecoderBuilder.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/SinkContext.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/http/DefaultEvent2HttpRequestHandler.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/http/HttpIdConfig.java, inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/http/HttpSinkContext.java
=> [INLONG-11937][Sort] Allow SortHttp to filter out data in TransformFunction

README.md
Fixes #11957
To fix link error in readme.
Fix link in the commit.
*(example:)*
=> [INLONG-11957][Doc] Fix 404 issue in readme about the uick Start link

inlong-sort/sort-end-to-end-tests/sort-end-to-end-tests-v1.15/src/test/java/org/apache/inlong/sort/tests/Pulsar2StarRocksTest.java, inlong-sort/sort-flink/sort-flink-v1.15/sort-connectors/pulsar/pom.xml
=> [INLONG-11974][Sort] Upgrade pulsar sdk version to 4.0.3

inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/sink/hive/SqlBuilder.java
Fixes #11984
Fix the problem of Hive table creation statement error.
Fix the problem of Hive table creation statement error.
=> [INLONG-11984][Manager] Fix the problem of Hive table creation statement error

inlong-audit/audit-tool/src/main/java/org/apache/inlong/audit/tool/AuditToolMain.java, inlong-audit/audit-tool/src/main/java/org/apache/inlong/audit/tool/evaluator/AlertEvaluator.java, inlong-audit/audit-tool/src/main/java/org/apache/inlong/audit/tool/reporter/OpenTelemetryReporter.java, inlong-audit/audit-tool/src/main/java/org/apache/inlong/audit/tool/task/AuditCheckTask.java, inlong-audit/audit-tool/src/test/java/org/apache/inlong/tool/evaluator/AlertEvaluatorTest.java, inlong-audit/audit-tool/src/test/java/org/apache/inlong/tool/service/AuditMetricServiceTest.java, inlong-audit/audit-tool/src/test/java/org/apache/inlong/tool/task/AuditCheckTaskTest.java
[INLONG-12000][Audit]Implement API for obtaining audit data in Audit Tool
Fixes #11999 
**Motivation**  
This component provides the core functionality for periodic audit data inspection and alert evaluation. It enables the system to automatically check data consistency between source and sink components at configurable intervals, detect anomalies based on predefined threshold rules, and trigger alerts when discrepancies exceed acceptable limits.
**Modifications**  
1. **Periodic Check Task**  
- Added `AuditCheckTask` class implementing scheduled background job  
- Configurable execution interval via `executionIntervalTime` parameter  
- Supports time-window-based audit metric querying with `startLogTs` and `endLogTs`  
2. **Data Query Service Integration**  
- Integrated with …
=> [INLONG-11999][Audit] Add alert evaluation and periodic audit check task

inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sinks/dataproxy/Sender.java
Fixes #11995 
The Agent supports parallel creation of Sender connections to the DataProxy, improving creation efficiency
The Agent supports parallel creation of Sender connections to the DataProxy, improving creation efficiency
*(example:)*
=> [INLONG-11995][Agent] The Agent supports parallel creation of Sender connections to the DataProxy, improving creation efficiency

inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/pulsar/PulsarIdConfig.java
Fixes #12007 
SortPulsar supports topic concatenation
SortPulsar supports topic concatenation
*(example:)*
=> [INLONG-12007][Sort] SortPulsar supports topic concatenation
